### ISSUE TITLE
Create embedded Chocolatey Package

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#1017]
### Title
Embed docfx files in the Chocolatey Package.

### Functional impact
Currently the Chocolatey Package downloads the ZIP containing the docfx files from GitHib. For enterprise deployment it would be better to have it embedded into the Chocolatey Package so that there's no dependency to an external resource for installing (see [Package embedding Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#114-embed-a-package-if-allowed) from the Core Repo how it is handled there).

While there is an feature in Chocolatey Business which allows to internalize packages for enterprise use, it would make it easier if the package already is deployed like this by the vendor on the community feed.

### Minimal repro steps
1. Setup a private Chocolatey feed containing the docfx package
2. Run `choco install docfx` on a machine without internet connection

### Expected result
The Chocolatey Package should install without requiring an internet connection.

### Actual result
The ZIP containing the docfx files is downloaded from GitHub during installation.

**Comment by yufeih** [comment]
The distribution model using [.NET core global tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) pushes everything to NuGet, it does not download any packages from GitHub.
