### ISSUE TITLE
More info on build.cmd should be added

### ISSUE THREAD

**Issue by lextm** [dotnet/docfx#102]
The current code base in dev branch is compiled against .NET Core 5 1.0.0 RC1 Final, while 1.0.0 RC1 Update 1 is already available and on some machines like mine. 

Thus, anyone who don't have 1.0.0 RC1 Final should execute `dnvm install 1.0.0-rc1-final` before executing `build.cmd`.

Meanwhile, someone might have Visual Studio 2015 with Update 1 installed, but no ASP.NET 5/.NET Core 5 RC1 bits. Those should install ASP.NET 5 (1.0.0 RC1 Update 1) from https://get.asp.net.

Yes, I know RC2 will use the `dotnet` command instead, but at least before that we should make it clear for new users.

**Comment by vicancy** [comment]
Thanks for the suggestion, will add
