### ISSUE TITLE
[Bug] Generate documentation from dlls

### ISSUE THREAD

**Issue by ghost1face** [dotnet/docfx#10205]
**Describe the bug**
No documentation generated when using dll references only

**To Reproduce**
1. Install globally `dotnet tool update -g docfx` 
2. Initialize project with defaults `docfx init`
3. Press enter through all the prompts
4. Update default metadata section:  
     ```json 
      "src": [
        {
          "files": [
            /* tried all the following */
            "src/*.dll",
            "src/**.dll",
            "**.dll",
            "../**.dll"
          ]
        }
      ]
     ```
5. Copy a dll and xml file to the `src` directory.  I used `mscorlib` from Reference Assemblies
6. In directory with docfx.json:   `docfx build docfx.json`
7. No documentation generated in `api` and `_site` is a barebones template

**Expected behavior**
Expected documentation to be generated

**Context (please complete the following information):**
- OS: Windows dotnet6 and 8 installed, node 20.17.0 installed through nvm
- Docfx version: [e.g. 2.59.0]  2.77.0

I'm sure I'm just doing something wrong, but by following just the base getting started instructions I've got nothing.  Below is my full `docfx.json` which is what's generated by default and me messing with the metadata/src/files section:

<details>
<summary>Generated docfx.json</summary>

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [
            /* tried all the following */
            "src/*.dll",
            "src/**.dll",
            "**.dll",
            "../**.dll"
          ]
        }
      ],
      "dest": "api",
      "disableGitFeatures": false,
      "disableDefaultFilter": false
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [
      "default"
    ],
    "postProcessors": [],
    "markdownEngineName": "markdig",
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}
```

</details>

Screenshot of output:
![image](https://github.com/user-attachments/assets/ee8d1809-6364-45ba-ac25-b6961f3bbd53)

**Comment by filzrev** [comment]
When generating API documentation.
It need to run `docfx metadata` command before running `docfx build` command.

---
Another problem is docfx version.
It seems docfx that installed by `dotnet tool update -g docfx` command is not be used.

What's the result of following command?

> docfx --version
> where.exe docfx

If docfx is installed as .NET global tools.
Following results are expected to be shown. 
- `2.77.0+bd00e2b93951e9e7fa6e5abd990d2cd77d7a83bd`
- `%USERPROFILE%\.dotnet\tools\docfx.exe`

When other exe path are displayed.
docfx is already installed by other tools (e.g. `chocolately`) and higher PATH priority.
Then It need to modify `PATH` settings.

**Comment by ghost1face** [comment]
Thank you, you were spot on.  There was another installed in the `PATH`.  I went ahead and uninstalled and ran `docfx docfx.json` to run the metadata and build steps.

Appreciate the help!
