### ISSUE TITLE
[Bug] PDF Header template not showing in the TOC section

### ISSUE THREAD

**Issue by taferk** [dotnet/docfx#10219]
**Describe the bug**
When a PDF header template is settled in a`toc.yml` file, it is displayed on all pages except those in the TOC sections.

**To Reproduce**
1. Set a header template in a `toc.yml` file.
    Example:
    ```
          pdfHeaderTemplate: "
              <div style='width: 100%; text-align: center;'>
		          <span style='font-size: 14px;'>My header</span>
              </div>
          "
    ```
2. Build PDF with DocFX

**Expected behavior**
That the header be displayed on all pages of the PDF file

**Context (please complete the following information):**
- OS: Windows
- Docfx version: [2.77.0.0]

**Additional context**
An easy solution could be...:
```
    static HtmlTemplate TocHtmlTemplate(Uri baseUrl, Outline node, Dictionary<Outline, int>? pageNumbers)
    {
     return Html($"""
         <!DOCTYPE html>
         <html>
             <head>
                 <link rel="stylesheet" href="/public/docfx.min.css">
                 <link rel="stylesheet" href="/public/main.css">
             </head>
             <body class="pdftoc">
                 {node.pdfHeaderTemplate}       <---This line fixes the problem
                 <h1>Índice de Contenidos</h1>
                 <ul>{node.items?.Select(TocNode)}</ul>
             </body>
         </html>
         """);
      }
```
...but this solution will only show the header template on the first page of the TOC section.

**Comment by yufeih** [comment]
TOC page is skipped in here: https://github.com/dotnet/docfx/blob/main/src/Docfx.App/PdfBuilder.cs#L381
