### ISSUE TITLE
Can't download online image 

### ISSUE THREAD

**Issue by BleyChen** [dotnet/docfx#1025]
I have a simple problem is that when i want to use docfx to convert .md file to html file. and the md file content has image that use internet link ,but the result is that it didn't download image and change the src reference to local image.

https://raw.githubusercontent.com/fuqi0340/BlogEngine.NET/master/README.md

the converted html file has the following markup:
<img src="https://cloud.githubusercontent.com/assets/1932785/11760070/0012f9d8-a052-11e5-84a8-e9097cb85f23.png" alt="dashboard-3">

image src is still online link , does anyone know what's the problem? thanks!

**Comment by superyyrrzz** [comment]
Hi @BleyChen , DocFX hasn't the logic to convert external link to internal link. If you want the image in the local build output, you can download it and include it in resources like [this](https://github.com/dotnet/docfx/blob/dev/Documentation/docfx.json#L29), and use an internal link in markdown.
