### ISSUE TITLE
Installation on Linux?

### ISSUE THREAD

**Issue by Sharor** [dotnet/docfx#1027]
### Title
Documentation mentions linux install, but not how to

### Functional impact
Cannot run docfx

### Minimal repro steps
Looking at documentation you mention Linux (dotnet core), but there is no clear project that should be setup in any specific way to enable docfx.
1. Download https://github.com/dotnet/docfx/archive/v2.9.3.tar.gz (tar.gz)
2. Only windows binary and build items, documentation does not mention linux install.

### Further technical details
How do you setup docfx for linux ? :)

**Comment by qinezh** [comment]
Hi @Sharor , you need install mono to run DocFX on Linux. [These steps about how to run DocFX on macOS](https://github.com/dotnet/docfx/issues/718#issuecomment-256700598) may help you.

**Comment by Sharor** [comment]
I was on holiday, and will take a look when time presents itself - thank you @qinezh ! :+1:

**Comment by Sharor** [comment]
I just ran the sample project, and it works in a docker box on ubuntu by following the steps in the linked thread - thank you @qinezh :smile:
