### ISSUE TITLE
[Bug] schema.json is not published to it's ID

### ISSUE THREAD

**Issue by bmackinney** [dotnet/docfx#10276]
The schema ID: [https://github.com/dotnet/docfx/schemas/v1.0/schema.json](https://github.com/dotnet/docfx/schemas/v1.0/schema.json) is 404. 

It's available here: [raw.githubusercontent.com/dotnet/docfx/refs/heads/main/schemas/v1.0/schema.json](https://raw.githubusercontent.com/dotnet/docfx/refs/heads/main/schemas/v1.0/schema.json) but is not built into docsite output.

**Comment by filzrev** [comment]
As far as I know. 
`id`/`$id` property of JSON Schema is not required to be `accessible URI`.

https://json-schema.org/draft/2020-12/json-schema-core#section-8.2.1

> Note that this URI is an identifier and not necessarily a network locator. In the case of a network-addressable URL, a schema need not be downloadable from its canonical URI.

**Comment by yufeih** [comment]
Close as the ID is not required to physically exist

**Comment by bmackinney** [comment]
There are several schemas that identify this URL as their meta schema with the $schema. The effect is downstream, and I think it would be easier to fix here than to change those references.
