### ISSUE TITLE
Latest csproj support problem (dev17)

### ISSUE THREAD

**Issue by sethjuarez** [dotnet/docfx#1028]
I upgraded a dotnetcore library using VS17 and made sure it compiled (etc.). I downloaded the latest version of docfx and executed it on a standard [docfx.json](https://github.com/sethjuarez/numl/blob/dev/Docs/docfx.json) file. Unfortunately I get the following error/warning:

> Warning: Error opening project C:/projects/numl/Src/numl/numl.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.. Ignored.
> Warning: No metadata is generated for .

Any ideas?

**Comment by roji** [comment]
Same here, seem that docfx needs to support the new simplified csproj format.

**Comment by superyyrrzz** [comment]
#1254

**Comment by sethjuarez** [comment]
Latest works!
