### ISSUE TITLE
More info on references to an API page in Markdown files should be added

### ISSUE THREAD

**Issue by lextm** [dotnet/docfx#103]
Currently DocFX documentation does not make it clear enough how to add a reference to a certain API page.

For an index page like [this one](https://raw.githubusercontent.com/dockpanelsuite/dockpanelsuite/docfx/docs/index.md) I found that I need to point to the YAML file,

```
<a href="obj/api/WeifenLuo.WinFormsUI.Docking.DockPanel.yml" class="button">Read more...</a>
```

It is not intuitive, so should be better documented for new users.

**Comment by vicancy** [comment]
`<a href="obj/api/WeifenLuo.WinFormsUI.Docking.DockPanel.yml" class="button">Read more...</a>` is not the suggested way to do API reference, @uid is. Will add more examples and tutorials on that.

**Comment by superyyrrzz** [comment]
See doc: http://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-cross-reference
