### ISSUE TITLE
[Feature Request] JSON output? (raw API data, not models)

### ISSUE THREAD

**Issue by pawamoy** [dotnet/docfx#10323]
**Is your feature request related to a problem? Please describe.**
Hello, I'm a fellow "API docs extraction/rendering" maintainer :slightly_smiling_face: I maintain [mkdocstrings](https://github.com/mkdocstrings/mkdocstrings) which is a plugin for [MkDocs](https://github.com/mkdocs/mkdocs), a static-site generator written in Python. mkdocstrings is language-agnostic and already supports a few languages such as Python, Crystal, VBA, as well as C and Typescript (experimental).

I would like to start supporting C# too. The relevant issue is here: https://github.com/mkdocstrings/mkdocstrings/issues/94. 

For this I have to extract API data from C# sources using either:

- a dedicated tool
- tree-sitter to parse and visit the AST/CST myself

Since I'm not an experienced C# developer, I'd largely prefer relying over a dedicated tool that was written by experts, such as docfx, rather than visiting ASTs, which is no trivial task. However it looks like docfx is not able to output the collected API data in a format that can easily be consumed by other tools (for example JSON). The summary at https://dotnet.github.io/docfx/index.html does say:

> Converts .NET assembly, XML code comment, REST API Swagger files and markdown into rendered HTML pages, JSON model or PDF files.

...but searching "json" in the docs yields nothing. Even then, I'm not sure "models" are something I can use, I need the API data in a consumable, non-transformed format.

**Describe the solution you'd like**
Would it be possible to add the option to output JSON instead of HTML? If not, do you know an other tool that is able to output C# API data as JSON? Or do you recommend I try and write a plugin to do just that?

**Describe alternatives you've considered**
- parsing and visiting ASTs in Python to extract API data
- generating HTML and scraping data from it? Doesn't sound fun 😅 

**Additional context**
/

**Comment by filzrev** [comment]
docfx extract API metadata from project/DLLs and generate intermediate `YAML` files.

**Steps to confirm intermediate YAML files**
1. Install docfx command as .NET global tools.
2. Clone docfx repository
3.  Run `docfx metadata` command on `seed/samples` directory
4.  Confirm API metadata files are generated on
  4.1 `obj/api` :  API metadata that generated with `mref`(ManagedReference) output format.
  4.2. `obj/apipage`:  API metadata that generated `apiPage` output format.
  4.3. `obj/md`: API metadata that generated `markdown` output format.

I thought `mref` (ManagedReference) output `raw API data` for docfx.

**Comment by pawamoy** [comment]
Awesome, thank you so much for the detailed answer! I'll try all this and report back. Feel free to close already 🙂

**Comment by pawamoy** [comment]
Can confirm I'm able to generate the intermediate YAML files. I should be able to work from that, thank you again!
