### ISSUE TITLE
[Bug] Release naming issue with scoop.sh

### ISSUE THREAD

**Issue by pseidel-iec** [dotnet/docfx#10444]
**Describe the bug**
The naming of the github releases changed from "v2.78.0" to "2.78.1" and "2.78.2", causing scoop.sh's automatic actions to not update to 2.78.1 or 2.78.2. Was this intentional?

**To Reproduce**
1. Install scoop
2. `scoop update`
3. `scoop install docfx`

**Expected behavior**
Scoop should install 2.78.2.

**Actual behavior**
Scoop installs 2.78.0.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: N/A

**Additional context**
Scoop's checkver.ps1 script sees the new update, but actually updating fails since the template URL requires a "v" before the version number. This "v" was removed starting with 2.78.1.

Was this intentional? If so, I can look into how to file a PR to scoop to fix this.

**Comment by yufeih** [comment]
Thank you @pseidel-iec for pointing it out! No it wasn't intentional. The releases and tags are now updated to include `v`.

**Comment by pseidel-iec** [comment]
Thanks.

It appears to be broken due to the filename this time. Could you rename (or upload a duplicate of) the v2.78.2 windows release artifact to be titled "docfx-win-x64-v2.78.2.zip" (with a "v")?
