### ISSUE TITLE
Namespace before listing all the contained classes.

### ISSUE THREAD

**Issue by ashengilevych** [dotnet/docfx#1046]
Hello! I have some little question for you:

We would like the namespace API page to start by a description before listing all the contained classes.

We created specific file which the named `NamespaceDoc ` . In that file we will write some description to our classes and generate it to the doc API. So, the questions: 

1. Do you have an existing implementation of something like this?
2. Do you plan to implement something like that in a future release?
We must be sure that if we do this, then after updating - everything will work as before.

I will be glad to your answer. Many thanks!

**Comment by vwxyzh** [comment]
In default template, namespace page can show summary, conceptual and remarks, then class table.
You can add an overwrite file to overwrite them.

**Comment by ashengilevych** [comment]
Good, thank you for your reply!
