### ISSUE TITLE
How to create a link to a method with a paramter of generic interface type?

### ISSUE THREAD

**Issue by zwcloud** [dotnet/docfx#1053]
### Title
Failed to create a link to a method with a paramter of generic interface type.

### Functional impact
Cannot create a link to a method with a paramter of generic interface type.

### Minimal repro steps
1. Example class

        namespace ASpace
        {
            class A
            {
                public void Fun(IReadOnlyList<int> list) { }
            }
        }

2. in a MarkDown document

        @ASpace.A.Fun(System.Collections.Generic.IReadOnlyList`1)

3. Generte the metadata and the website. And docfx is serving "XXX\docfx_project\_site" on http://localhost:8080

4. Open the corresponding html page in the browser.
It shows plain text 

        @ASpace.A.Fun(System.Collections.Generic.IReadOnlyList`1)

instead of a link to the method.

### Expected result
A link to the method `ASpace.A.Fun` should be displayed.

### Actual result
It shows plain text 

    @ASpace.A.Fun(System.Collections.Generic.IReadOnlyList`1)

instead of a link to the method.

### Further technical details
I have read [metadata_spec/generics](http://dotnet.github.io/docfx/spec/metadata_dotnet_spec.html#6-generics) and I think I followed the instructions there.

**Comment by superyyrrzz** [comment]
You can try this: `ASpace.A.Fun(System.Collections.Generic.IReadOnlyList{System.Int32})`.
Another quick way to find the uid is to inspect output HTML's `data-uid` attribute.

**Comment by zwcloud** [comment]
It works. Thank you very much!
Any doc on the from {System.Int32}? What is it?

**Comment by vwxyzh** [comment]
@zwcloud our document is [here](http://dotnet.github.io/docfx/spec/metadata_dotnet_spec.html#2-identifiers), and this is same behavior for comment id.
