### ISSUE TITLE
Missing "In This Article" section when building "docfx-seed"

### ISSUE THREAD

**Issue by cameron-elliott** [dotnet/docfx#1065]
When using the current Github repo for "docfx-seed" and the current docfx [2.9.3], I do not get the "In This Article" navigation in the right side. Yet it appears on the docfx-seed github pages site.

Image: http://take.ms/ZKSyw
I followed these steps:
(1) Download docfx 2.9.3 using choco, 
(2) Download current docfx-seed using git 
(3) run docfx in root folder of docfx-seed.

Output is farther below.
Note: In this situation, the "Improve This Doc" label is displaying correctly, but I have struggled to get it to output on my own project, which is not docfx-seed.

_**Can I make two suggestions?**_
1. Suggestion: When internal docfx logic decides that the "IN THIS ARTICLE" section will not be displayed, it should report a message: "Info: IN THIS ARTICLE will be hidden because of reason XYZ..."
2. Suggestion: When internal docfx logic decides that the "Improve This Doc" section will not be displayed, it should report a message: "Info: IMPROVE THIS DOC will be hidden because of reason XYZ..."

On thoughts on how to fix this with docfx-2.9.3 and current docfx-seek are appreciated.

I think docfx is a great project, and hope feedback is found useful.

==============================
C:\Users\cameron\github\docfx-seed>docfx -v
docfx 2.9.3.0
Copyright (C) 2016 Copyright c Microsoft docfx 2015-2016
This is open-source software under MIT License.
Info: Completed executing in 0.3335 milliseconds.

C:\Users\cameron\github\docfx-seed>docfx
Info: Config file docfx.json found, start generating metadata...
Info: 'C:/Users/cameron/github/docfx-seed/src/SampleClass1/SampleClass1.sln' keep up-to-date since '12/27/2016 10:23:17
PM', cached result from 'C:/Users/cameron/github/docfx-seed/obj/api' is used.
Info: 5 plug-in(s) loaded.
Info: Post processor ExtractSearchIndex loaded.
Info: Markdown engine is dfm
Info: [Build Document]Max parallelism is 8.
Info: [Build Document.PrebuildBuildPhaseHandler.ConceptualDocumentProcessor]Building 5 file(s) in ConceptualDocumentProcessor(BuildConceptualDocument=>CountWord=>ValidateConceptualDocumentMetadata)...
Info: [Build Document.PrebuildBuildPhaseHandler.ResourceDocumentProcessor]Building 1 file(s) in ResourceDocumentProcessor(ValidateResourceMetadata)...
Info: [Build Document.PrebuildBuildPhaseHandler.ManagedReferenceDocumentProcessor]Building 26 file(s) in ManagedReferenceDocumentProcessor(BuildManagedReferenceDocument=>ValidateManagedReferenceDocumentMetadata=>ApplyOverwriteDocumentForMref=>FillReferenceInformation)...
Info: [Build Document.PrebuildBuildPhaseHandler.TocDocumentProcessor]Building 4 file(s) in TocDocumentProcessor(BuildTocDocument)...
Info: [Build Document.PrebuildBuildPhaseHandler.RestApiDocumentProcessor]Building 4 file(s) in RestApiDocumentProcessor(BuildRestApiDocument=>ValidateRestApiDocumentMetadata=>ApplyOverwriteDocumentForRestApi)...
Info: [Build Document.PostbuildPhaseHandler.UpdateContext]0 external references found in 1 xref maps.
Info: [Build Document.PostbuildPhaseHandler.Apply Templates]Applying templates to 36 model(s)...
Info: [Build Document]XRef map exported.
Info: [Process in post processor ExtractSearchIndex]Extracting index data from 35 html files
Info: Manifest file saved to C:\Users\cameron\github\docfx-seed\_site\manifest.json.
Info: Completed building documents in 3956.0313 milliseconds.
Info: [Apply Theme]Theme is applied.
Info: Completed executing in 5551.7847 milliseconds.

Build succeeded.
        0 Warning(s)
        0 Error(s)

C:\Users\cameron\github\docfx-seed>

**Comment by superyyrrzz** [comment]
Thank you for your suggestion. We will considering improving this. Generally, `Improve This Doc` should show if your project has a remote url named `origin`.
About "IN THIS ARTICLE", it may be caused by failure to load some scripts when open local html files directly. You can try `docfx serve _site` and visit via `http://localhost:8080`.

**Comment by qinezh** [comment]
You need HTTP server to serve the generated site instead of opening it directly.

**Comment by cameron-elliott** [comment]
Thank you very much, this was the issue.

**Comment by jstafford5380** [comment]
Sorry, question on a random issue lol... Does the "In this article" section have a name? I'm trying to look up some information on how to have it fully expanded by default.

**Comment by yufeih** [comment]
It is called `affix` in the template code.

**Comment by jstafford5380** [comment]
> It is called `affix` in the template code.

thanks!
