### ISSUE TITLE
Failing on AppVeyor 

### ISSUE THREAD

**Issue by richardschneider** [dotnet/docfx#1078]
When building the documentation on AppVeyor, I get a warning.  On my machine, there is no warning.

    docfx metadata doc\docfx.json -f
    Warning: Invalid cref value "!:System.String" found in triple-slash-comments for Decode defined in ../src/Base32.cs Line 66, ignored

The [docfx.json](https://github.com/richardschneider/net-ipfs-core/blob/master/doc/docfx.json) has `"xref": [ "msdn.4.5.2.zip" ]`.  And the zip file is in the [repo](https://github.com/richardschneider/net-ipfs-core/tree/master/doc).

**Comment by vwxyzh** [comment]
`!:System.String` that means Roslyn cannot find the string type, please check your environment can build code correctly.

**Comment by richardschneider** [comment]
Yes, my code compiled on Appveyor, see
https://ci.appveyor.com/project/richardschneider/net-ipfs-core#L44

**Comment by vwxyzh** [comment]
@qinezh any idea?
project is [here](https://github.com/richardschneider/net-ipfs-core)

**Comment by qinezh** [comment]
From the description, it seems that there's something wrong within AppVeyor environment. Maybe you could try to modify some configuration in  `appveyor.yml`, such as disable package cache, etc...

**Comment by richardschneider** [comment]
@qinezh I've just enable package caching.  All NugGet and choco packages and up  to date.  I also changed dappyeyor.yml to use VS 2015.  I'm using dotfx v2.9.3 from choco.

What config changes do you want me to make?

**Comment by richardschneider** [comment]
What are the requirements for docfx?  Do I need a specific .Net framework? ...?

**Comment by qinezh** [comment]
.NET 452 is enough...

**Comment by richardschneider** [comment]
I changed the target framework version from 4.5 to 4.5.2 and still no love!

**Comment by cameron-elliott** [comment]
Richard, how did you resolve this?

**Comment by richardschneider** [comment]
No I haven't, I'm still getting `invalid cref`.  I've tried numerous hacks with no luck so far.

I take a lot at what you did with LimeVideoSdk, tomorrow (I'm .UTC+1300). 

Your comment on #1097 is greatly appreciated.

**Comment by richardschneider** [comment]
I've been looking at Roslyn, and have determined that invalid cref of `"!:System.String"` is generated when the source is analysed and assembly references are not specified.

Could my problem that the assembly references from the project are not be used?

**Comment by richardschneider** [comment]
When running on appveyor the assembly references are **MISSING**!

I modified `Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.GetProjectMetadataFromCacheAsync` to display all the `documentCache.GetDocuments`.  On my machine it displays the assembly references and the source files for the project.  On appveyor it does NOT display the assembly references only the source files.

@vicancy I need some help here.  The whole generation of metadata and use of Roslyn is very complex and frankly I can't understand it.  Hopefully I'v given you guys enough hints to find a fix.

**Comment by richardschneider** [comment]
The issue was solved by @vicancy 

Do **NOT** use `platform: Any CPU` in  `appveyor.yml`.
