### ISSUE TITLE
API documentation '+' buttons do not work from filesystem

### ISSUE THREAD

**Issue by cameron-elliott** [dotnet/docfx#1080]
### Functional impact
Users are unable to view classes under a namespace when the documentation files are opened from the file-system with a browser

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  
e.g.
1. git clone docfx-seed
2. cd docfx-seed
3. docfx
4. cd _site
5. right click on index.html, and open with Chrome browser
6. Select 'API Documentation' tab at top
7. Clicking the '+' button next to CatLibrary will fail to show classes in namespace.

### Expected result
Clicking the '+' button next to CatLibrary *should* show classes in namespace.

### Actual result
Clicking the '+' button next to CatLibrary will not do anything, and will fail to show classes in namespace.

**Comment by cameron-elliott** [comment]
Again, I think Docfx is an awesome project, and I hope to help polish it a very little bit with feedback, and maybe in the future, PRs. I hope the issue reports are useful. I understand that the main team may not consider filesystem based use important, but I hope outside feedback about this use case will be helpful.

**Comment by vicancy** [comment]
Should be fixed in 2.17.2
