### ISSUE TITLE
Are hashtags supported in @ references?

### ISSUE THREAD

**Issue by cameron-elliott** [dotnet/docfx#1096]
### The documentation says "Hashtag is not supported in @ form."
Documentation says "Hashtag is not supported in @ form."
Found here: [Docs page](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html)
But, @filename#anchor seems to work in 2.9.3

Could someone clarify whether getting this working is a goal?
It may be that some characters are no supported in parsing of the @uid#anchor, form,
but that the @-form will work when these characters are not used.

Please forgive me if I am writing too many issues, I hope the feedback is useful.

**Comment by vicancy** [comment]
We appreciate your feedback @cameron-elliott 😄 Don't hesitate to open it if you find one.
`@filename#anchor` is supported now. Make sure to URL encode `filename` if it contains `?` or `#`, e.g. encode `@ClassA.#ctor#anchor1` to `@ClassA.%23ctor#anchor1`.
We will update the documentation accordingly.

**Comment by chenkennt** [comment]
@cameron-elliott Our documentation does mention how to use hashtags in @ form, you can find it [here](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-hashtag-in-cross-reference).

**Comment by cameron-elliott** [comment]
My question was really because:
1. I discovered @ with hash tag worked in practice.
2. The documentation said it would not work.

Thank you for the updates, everybody.
Thank you for creating DocFx
