### ISSUE TITLE
@ symbol in Markdown breaks generated HTML

### ISSUE THREAD

**Issue by lextm** [dotnet/docfx#113]
```
---
_allowAffix: false
title: Welcome to DockPanel Suite Website!
documentType: index
---
<p>DockPanel Suite is currently maintained by @<a href="https://github.com/roken" class="user-mention">roken</a> and @<a href="https://github.com/lextm" class="user-mention">lextm</a>.</p>
```
Try to put the above to a markdown file, but docfx not only reports a warning, but also generates broken HTML.

The warning is
```
Warning: Missing following definitions of xref:
&lt;a. in phase Build Document
```
The broken HTML is
```
<p>DockPanel Suite is currently maintained by <span class="xref">&lt;a</span> href="https://github.com/roken" class="user-mention"&gt;roken and <span class="xref">&lt;a</span> href="https://github.com/lextm" class="user-mention"&gt;lextm.</p>
```

Note that the below in Markdown also fails,
```
<p>DockPanel Suite is currently maintained by <a href="https://github.com/roken" class="user-mention">@roken</a> and <a href="https://github.com/lextm" class="user-mention">@lextm</a>.</p>
```

I think it is related to #45 .

**Comment by vicancy** [comment]
The behavior is by design.
`@` is a syntax in DFM for [cross reference](http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#cross-reference), and has higher priority than html syntax, so `@<a` is considered as `@uid` and docfx tries to find file with uid `<a`.

If you want to display `@` character, please use `&#64;`

**Comment by vicancy** [comment]
FYI, we introduced a new syntax for cross-reference: `<xref:uid>`. And `@` will no longer transform `<span class='xref'></span> when the cross-reference is not resolved, it will fall back to the original text.

**Comment by lextm** [comment]
@vicancy Thanks. Will try it out.
