### ISSUE TITLE
3rd level of metadata

### ISSUE THREAD

**Issue by ashengilevych** [dotnet/docfx#1141]
Hi, all metadata docfx, we create, we only have 2 levels of metadata nesting. For example:

![caa4398a7d0a49d58cc83286f0b15741](https://cloud.githubusercontent.com/assets/23631040/21810031/d6721170-d752-11e6-960d-eb58ce876c00.png)

But, I need the three levels nesting. Something like this: 

![be19911490e44f33b1cbc12162f057ba](https://cloud.githubusercontent.com/assets/23631040/21810074/f9693ff0-d752-11e6-98ec-6087bf1b8c6f.png)

I know that it is set in toc.yml file. But, this file is always generated automatically when we re-generate our metadata of the project and overwrites it.

How can I create a third nesting level of the metadata from the source code? Is it possible?

I will be glad to your answer. Many thanks!

**Comment by vicancy** [comment]
Currently the easiest way is to restructure toc.yml using your own code between `docfx metadata` and `docfx build`:
call `docfx metadata`
RestructureTocYaml.exe (your exe to do whatever you want with toc)
call `docfx build`

**Comment by ashengilevych** [comment]
@vicancy Thanks for your reply. I understood you.
