### ISSUE TITLE
Show warning if xref is not found

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#1142]
### Functional impact
Using an invalid xref link like `@does-not-exist` in a contextual file does not trigger a warning on build like standard markdown links do. 

### Minimal repro steps
1. Add an invalid xref link to a document, eg. `@does-not-exist`
2. Run `docfx`

### Expected result
I would expect a warning that no xref for `@does-not-exist` was found.

### Actual result
Only a info is shown how many external references are found. Something like:

```
Info: [Build Document.LinkPhaseHandler.UpdateContext]0 external references found in 3 xref maps.
```

**Comment by superyyrrzz** [comment]
Hi @pascalberger , DocFX did give warning for shorthand form xref before. But as `@` is also a common character in text, usually the warning is unexpected for user when just a plain `@` character is needed... So now DocFX only logs a warning for Markdown link and Auto link xref.

**Comment by vicancy** [comment]
Markdown link: `[link_text](xref:uid_of_the_topic)`
Auto link: `<xref:uid_of_the_topic>`

**Comment by pascalberger** [comment]
Thanks, I created a PR to add this to the documentation: #1150
