### ISSUE TITLE
"Improve this Document" link not appearing for Gitlabs.

### ISSUE THREAD

**Issue by d96patel** [dotnet/docfx#1144]
I am working on a documentation project for GitLabs hosted project.
URL format is https://git.companyname.com
How to make the link work?

part of docfx.json is as shown below.

"globalMetadata": {
      "_enableSearch": "true",  
      "_gitContribute": {
        "repo": "https://git.companyname.com/dev/Development.git",
        "branch": "master",
        "path": ""
      },
      "newFileRepository": {
        "branch": "master"
      }
    },

**Comment by superyyrrzz** [comment]
I found GitLab has the same URL pattern with GitHub, you can try adding `"_gitUrlPattern": "github"` in global metadata.
see: https://github.com/dotnet/docfx/issues/677#issuecomment-246961435

**Comment by d96patel** [comment]
@superyyrrzz thanks for the prompt reply. I tried that as well but it does not work.
I am using NuGet version 2.4.0 in VS 2015.

Below is a docfx.json for your reference.

{
  "metadata": [
    {
      "src": [
        {
          "files": [
            "Folder/**.csproj",	
          ],
          "exclude": [
            "**/obj/**",
            "**/bin/**",
            "_site/**",
          ],
          "src": "../"
        }
      ],
      "dest": "api"
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadata": {
      "_enableSearch": "true",
      "_gitContribute": {
        "repo": "https://git.mycompany.com/dev/Development.git",
        "branch": "master",
        "path": ""
      },
      "_gitUrlPattern": "github",
      "newFileRepository": {
        "branch": "master"
      }
    },
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "template": [
      "default"
    ]
  }
}

**Comment by superyyrrzz** [comment]
I think your docfx.json is right, and local branch is also OK. Here're some other steps that may help narrow down the problem.
1. What version of DocFX do you use? `_gitUrlPattern` is supported since 2.5.1
2. Can you try remove `_gitContribute` to see whether the result right?
3. `newFileRepository` is obsolete. You can remove it, although this should not related to this issue.

**Comment by d96patel** [comment]
I am using docfx.msbuild version 2.4.0 
https://www.nuget.org/packages/docfx.msbuild/2.4.0

**Comment by d96patel** [comment]
@superyyrrzz I found out that I was using the docfx.msbuild which was wrong package. I installed docfx.console nuget 2.10.2 and now "Improve this doc" and "View Source" are appearing.
However, when I click "Improve this doc", it leads me to "new page" in the repo. Is it because I am working on a local branch and have not pushed it to the server? 
When I click on "View Source", it leads me to 404 because it builds the link with the local branch name.

**Comment by superyyrrzz** [comment]
For a reference page, if it hasn't an [overwrite document](http://dotnet.github.io/docfx/tutorial/intro_overwrite_files.html), "Improve this doc" will link to a URL that help create a file to overwrite this page. If the remote branch exists, you can see what this URL does, instead of a 404.

**Comment by Konard** [comment]
For me these two settings worked:
```
      "_gitContribute": {
        "branch": "master"
      },
      "_gitUrlPattern": "github"
```
`"_gitUrlPattern": "github"` alone was not enough.
https://github.com/linksplatform/Threading/blob/a7a64f2adb2a8db16a5624a0a59d37d54e5b9791/docfx.json#L28

**Comment by gumbarros** [comment]
In our case, it worked with false as a boolean, not a string.
`
  "globalMetadata": {
      "_appTitle": "JJMasterData",
      "_disableContribution": false,
      "_gitContribute": {
        "branch": "master"
      },
      "_gitUrlPattern": "github"
    },
`
