### ISSUE TITLE
Powershell docs: build warning of xref

### ISSUE THREAD

**Issue by herohua** [dotnet/docfx#115]
@joeyaiello reports this issue when building Powershell docs: https://github.com/PowerShell/PowerShell-Docs

EXEC : warning : Missing following definitions of xref: [C:\Resources\directory\edfe6af575634e3898a09d74e323290c.WorkerRole.wd\u5ozdus5.usg\source\packages\docfx.msbuild.1.2.2\build\docfx.msbuild.targets]
  {
                (. in phase Build Document

**Comment by joeyaiello** [comment]
Please let me know if there's any more info I can provide on this bug. Some other context from the original mail:

we’ve been running into some warnings on OPS builds where the build engine appears to be trying to parse certain characters (like curly braces and parentheses). Right now, the warning emitted is: 

```
EXEC : warning : Missing following definitions of xref: [C:\Resources\directory\edfe6af575634e3898a09d74e323290c.WorkerRole.wd\u5ozdus5.usg\source\packages\docfx.msbuild.1.2.2\build\docfx.msbuild.targets]
  {
                (. in phase Build Document
```

In the past it was spitting out something very similar:

```
EXEC : warning : Missing following definitions of xref: [C:\Resources\directory\edfe6af575634e3898a09d74e323290c.WorkerRole.wd\u5ozdus5.usg\source\packages\docfx.msbuild.1.2.2\build\docfx.msbuild.targets]
  {
                {ModuleName='UserConfigProvider';ModuleVersion='3.0'} in phase Build Document
```

We tracked that string down to a file in one of the docs, and the warning went away when we added a syntax block around that code element.

**Comment by vicancy** [comment]
@joeyaiello there are 
`@{` inside https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/dsc_directaccess.md and https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/dsc_runas.md,
and `@(` inside https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/dsc_runas.md that lead to the warning.
In your scenario, they are powershell code, could you wrap them by code syntax?

We will provide more detailed information, e.g. file path, when reporting the warning in next release coming next week.
