### ISSUE TITLE
Fenced code block inside list rendered wrong

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#1177]
### Functional impact
A fenced code block inside a list is rendered as inline code block, except there are blank lines inside the fenced code block.

### Minimal repro steps
1. Add [this](https://gist.github.com/pascalberger/3a5607c5470ae3d9ae8921b09b8fdf5f) markdown to a page inside a DocFx project.

### Expected result
In both cases I would expect the code block to be rendered as fenced code block.

### Actual result
If the fenced code block doesn't contain a blank line it is rendered as inline code block

### Further technical details
DocFX 2.10.2

**Comment by vwxyzh** [comment]
@pascalberger I test it [here](https://github.com/vwxyzh/mdtest/blob/master/README.md).
And GitHub also render the first one as inline code.

**Comment by vwxyzh** [comment]
And if you want get code for first, you need write md like following:
````md
* Foo (add new line behind)

  ```
  foo
  Bar
  ```
````

**Comment by pascalberger** [comment]
@vwxyzh Your example is also in Gist. But if you see [my comment](https://github.com/dotnet/docfx/issues/1177#issuecomment-272482811) it is rendered differently inside of a GitHub comment.

Adding a line break after the `*` line introduces another problem that the list is ended and the code block starts at the begining of the line instead of getting proper intendation.

**Comment by vwxyzh** [comment]
In GitHub comment there are more differences:
e.g.:  you don't need two new lines to create a paragraph, one new line is enough.

**Comment by pascalberger** [comment]
Another case which doesn't make sense IMHO:

Results in inline code blocks for `Foo`, `Bar` and `FooBar`:
```
    * Foo
      ```
      Foo
      ```    
    * Bar
      ```
      Bar
      ```
    * FooBar
      ```
      FooBar
      ```
```
Results in fenced code blocks for `Foo` and `Bar` and inline code block for `FooBar`:

```
    * Foo
      ```
      Foo
      ```

    * Bar
      ```
      Bar
      ```
    * FooBar
      ```
      FooBar
      ```
```

**Comment by vwxyzh** [comment]
@pascalberger I agree with your option, but GitHub has same behavior.
You can fork our code and modify it [here](https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.MarkdownLite/Basic/BlockRules/MarkdownListBlockRule.cs#L65)

**Comment by pascalberger** [comment]
@vwxyzh You're right. Closing this issue
