### ISSUE TITLE
Build time was increased

### ISSUE THREAD

**Issue by ashengilevych** [dotnet/docfx#1183]
Hello! We updated the docFX to last version (v. 2.10.2.0)

After the update, we have noticed an increase in assembly time (longer than 10%). Have you noticed the same behavior? Than it can be caused and how can we speed up this process? 
I look forward to your response. Thank you.

**Comment by scalarsys** [comment]
We have noticed that same thing on my project. In reviewing the activity with Process Explorer (procexp64.exe) there are many instances of git.exe and where.exe being spawned as child processes. I haven't figured anything out beyond that.

**Comment by qinezh** [comment]
@ashengilevych We generated derived class information in this version, so it maybe a little slower than previous version.

**Comment by qinezh** [comment]
@scalarsys We'll reduce the spawned instances of git.exe and where.exe in next release, thanks your feedback.

**Comment by qinezh** [comment]
There should be only limited spawned instance of git.exe and where.exe in latest release.
