### ISSUE TITLE
Provide a way to remove the "improve this doc" button

### ISSUE THREAD

**Issue by simonmurdock** [dotnet/docfx#120]
Hi, 

When completing the walkthrough, his button (which I believe is for github only) should not be displayed.

I'm not sure if that is a bug, or if I need to specify something in the docfx.json to hide it explicity.

**Comment by DovydasNavickas** [comment]
Actually, it works with Visual Studio online or pretty much any other repository, because it takes links from .git folder, where there are actual links to reach the files :clap:
If the repository does not have web interface, then it is not gonna work, but if it does - it works perfectly :+1:

**Comment by simonmurdock** [comment]
where is it going to find a .git folder in a svn repository?

**Comment by vicancy** [comment]
Hi Simon, it only supports git based repo

**Comment by simonmurdock** [comment]
I know, hehe

**Comment by DovydasNavickas** [comment]
If SVN has same information like git just with .svn folder, you could submit a PR with that capability :clap:  :+1:

**Comment by vicancy** [comment]
v1.4 released and if no git info is found, "improve this doc" button will not show. You can also add `_disableContribution` to `globalMetadata` part of `docfx.json` to always disable this feature.

**Comment by simonmurdock** [comment]
Great!

**Comment by DovydasNavickas** [comment]
`_disableContribution` :+1:

**Comment by Crono1981** [comment]
Unfortunately the `_disableContribution` flag also takes away the `View Source` link. 😕

**Comment by chungleepeople** [comment]
Hi @Crono1981 ,
Add `"_disableContribution": true` to globalMetadata part of docfx.json

**Comment by vivere-dally** [comment]
I think the `View source` and `Improve this doc` should be handled in the `_gitContribute` nested object, and each of them should have a flag.

**Comment by mikernet** [comment]
Although it would be nice if they both had independent flags, you can also throw this into a css file to hide "improve this doc":

```css
article.content span.small.pull-right:nth-child(even) {
    display: none;
}
```
