### ISSUE TITLE
32-bit Unicode fails in XML comment

### ISSUE THREAD

**Issue by richardschneider** [dotnet/docfx#1211]
### Functional impact
The generated output from a XML comment with a 32-bit Unicode code point displays incorrectly.

For example the smile 😄 (U+1F604) displays as "Ø3DÞ04" in the html.

### Minimal repro steps

1. Insert the smile into an XML comment
2. Run docfx
3. Examine the generated html

### Expected result

The html should contain the smile either as an HTML entity `&#x1f604;` or the UTF-8 sequence `F0 9F 98 84`.

### Actual result
The smile is generated as text string ` Ø3DÞ04`.

### Further technical details

I believe the issue is with the Yaml generation of Metadata.  The generated `yml` for the XML comment contains `\xD83D\xDE04` which is the UTF-16 encoding (using high and low surrogate) for the smile. Yaml doesn't support UTF-16 BUT does allow escaping of Unicode, so it should be `\U0001F604`.

It looks like YamlDotNet has fixed this issue in [Handle 32bits Unicode escaped sequences](https://github.com/aaubry/YamlDotNet/commit/6525bb8b74e17a841083c05178192cd6563680ff). Hopefully an upgrade to 4.0.1 wll resolve this issue,

**Comment by vwxyzh** [comment]
@richardschneider Thank you for report this issue.
We will upgrade yamldotnet later.
Because we customize some serialization behaviors, it will take more time to upgrade package.
For now, please modify `😄` to `:smile:`.

**Comment by richardschneider** [comment]
@vwxyzh  thanks for the upgrade.  I'm closing this because the test now works.
