### ISSUE TITLE
Date when .md file was committed

### ISSUE THREAD

**Issue by DovydasNavickas** [dotnet/docfx#122]
It is always convenient to see when the documentation was written to have sense if it is still relevant or not.
It would be nice to have that in the default template.

**Comment by chenkennt** [comment]
Yes, it's in our plan.

**Comment by vicancy** [comment]
Postpone to v1.6

**Comment by vicancy** [comment]
On hold the change as the implementation has perf issue for large repo...

**Comment by DovydasNavickas** [comment]
Any updates? :smile:

**Comment by vicancy** [comment]
Is it possible to move OPS plugin to docfx? @herohua

**Comment by herohua** [comment]
@vicancy It is possible, but we need to take care some issues: 
1. OPS plugin generates push time, not commit time. Current implementation needs update.
2. Shall we consider cross-platform support if we move the plugin into DocFX?

**Comment by yufeih** [comment]
This is addressed in v3

**Comment by BenBo-slc** [comment]
Hi @yufeih, would you have any idea when v3 would be released?
Or at the very least this feature would become available?
Because as far as I can tell this currently hasn't been released yet.
kind regards
