### ISSUE TITLE
API Documentation namespaces get cut off on smaller screen

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/docfx#1222]
### Title
API Documentation does not allow scrolling to the bottom namespaces on smaller screens

### Functional impact
Cannot see docs for all namespaces

### Minimal repro steps
1. Create a documentation project with at least 30 namespaces
2. Generate docs
3. Host the website, on a 1080p screen you will not be able to see the bottom namespaces

### Expected result
Scroll to the bottom namespaces

### Actual result
Bottom namespaces are missing

### Further technical details
My generated doc site can be found here. (http://robotdotnet.github.io/api/index.html)

Here is an example of what the issue looks like on my screen
![screendoesntscroll](https://cloud.githubusercontent.com/assets/7727148/22185102/0e98025e-e094-11e6-8d78-3e32bf0f48d6.PNG)

Doing some testing, it seems like the footer for the site is getting in the way and not being taken into account when determining how far to scroll. If I manually remove the footer from the HTML, everything properly displays.

**Comment by richardschneider** [comment]
Surrounding the `.` (dot) with Unicode U+200B ZERO WIDTH SPACE (HTML &#8203;) will solve the issue.

**Comment by ThadHouse** [comment]
Surrounding what `.` ? Is that something that needs to be changed in the doc generation? Or in my code? My generation repo is here https://github.com/robotdotnet/WPILib-Docs

**Comment by richardschneider** [comment]
@ThadHouse Sorry, it's a suggestion to the docfx team for when the html is generated.

**Comment by ThadHouse** [comment]
I actually think this is a different issue than the `.` thing. It's not about the namespace wrapping (That's another issue I know about because of that first issue.) The actual issue is there are full namespaces hidden  under the footer. Unless the `.` issue is causing the Javascript to calculate the window height wrong, I don't think that's actually the issue.

**Comment by ThadHouse** [comment]
So more debugging, and I think I figured out the issue. Looking through the Javascript, it should be hiding the footer, however specifically on `api/index.html` it does not hide the footer. All other api doc files do properly hide the footer, just not index.html.

**Comment by ThadHouse** [comment]
Just rebuilt my site with 2.12.1, and this issue is fixed. Thanks!
