### ISSUE TITLE
Feature Request: Add way to link to interfaces from doc

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/docfx#1223]
One thing that always bugged me about the msdn documentation was that from a doc, there was no easy access to all the interfaces on a class. There would be the Syntax block, which still exists in docfx, but you couldn't actually click on the interfaces to get to their definition. It would be nice if the generated docs would have a way to do this.

My suggestion would be to add a block below Inherited Members to be something like "Implemented Interfaces", with links to all the implemented interfaces. That way it would be easy to see exactly what an interface definition is.

The other suggestion would be to make the interface and inheritance tree in the Syntax block clickable, so those would be links to their specific interfaces.

**Comment by vwxyzh** [comment]
@ThadHouse , a clickable syntax block seems better, but it takes time, let us trace it in #1620.
For now, we will update default template with "Implemented Interfaces" in next month (v2.18).
