### ISSUE TITLE
Allow circular links when generating metadata

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/docfx#1224]
### Title
When generating metadeta for 2 different projects, allow circular linking to a downstream project

I have an interface defined in a base assembly, and the implementation in another assembly. I want the summary doc for the interface to include a reference to the implementation. However, this is not currently possible. If I build metadata for the base assembly first, it cannot find the docs for the implementation assembly, and if I build for the implementation first, it can't find the docs for the interface. I am building using the metadata tags in my project.json, so it should be able to build them all at the same time.

**Comment by superyyrrzz** [comment]
This should work in DocFX. [Here](https://github.com/superyyrrzz/ReferenceBetweenProject) is a sample project. You can see the reference between [Foo](https://github.com/superyyrrzz/ReferenceBetweenProject/blob/master/src/DownstreamProject/Foo.cs#L6) and [IFoo](https://github.com/superyyrrzz/ReferenceBetweenProject/blob/master/src/BaseProject/IFoo.cs#L4).

**Comment by ThadHouse** [comment]
Interesting. I had all my cross docs inside of <see> tags, which were not working. Switching to using the @ tag worked. I think that's still a bug, since the <see> tag should work for this, but at least I now have a workaround. Thanks!

**Comment by superyyrrzz** [comment]
If you want to use C#'s `<see>` tag to reference a class, you should first reference the project. However,  circular project references are not supported by C# compiler. I think `<see>` tag is not a good choice in your scenario. The sample I provide uses DocFX's [cross reference](http://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-cross-reference) syntax, which avoids the circular project references.

**Comment by ThadHouse** [comment]
Yeah, I'm going through all of my docs making them docfx compatible. I used to use Sandcastle, but the markdown syntax and docs using this is so much nicer. The biggest thing I'm having to remove is all my inheritdoc tags, but that's worth it.

**Comment by superyyrrzz** [comment]
I'd like to mention one more thing: `inheritdoc` is partially supported from DocFX's next release v2.12.
#1178

**Comment by ThadHouse** [comment]
Yeah I saw that. However if I keep them around, I have to keep sandcastle around because it's what I use to fix the xml docs since VS doesn't know how to use inheritdoc. And its a big dependency that keeps breaking and doesn't support core properly, so not worth keeping around, unless VS gets support for understanding inheritdoc.
