### ISSUE TITLE
Improve this doc doesn't work for the docfx documentation

### ISSUE THREAD

**Issue by mairaw** [dotnet/docfx#125]
When I try to click the "Improve this doc" button, nothing happens.

Here is an example of a page where the button is not working: http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html

**Comment by simonmurdock** [comment]
see #120 possibly.

**Comment by vicancy** [comment]
Hi Maria, the "improve this doc" button from http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html link me to https://github.com/dotnet/docfx/blob/master/Documentation/tutorial/docfx_getting_started.md/#L1.

**Comment by vicancy** [comment]
Will fix

**Comment by vicancy** [comment]
fixed in latest dev branch
