### ISSUE TITLE
Is there a way to suppress the `generator` meta tag?

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/docfx#1251]
### Title
Every update of DocFx tooling causes changes in every single generated html file because of the `meta name="generator" content="docfx 2.10.2.0` tag being updated. Is there a way to suppress this tag, so that rebuilding docs with a new version of DocFx wouldn't make changes to every single generated html file?

### Functional impact
When committing docs generated with a new version of DocFx we have to either manually excluded files with no meaningful changes (error prone) or include all files, which adds too much noise to the change history.

### Minimal repro steps
Build docs with DocFx 2.10.1.0.
Change a single line in the source file.
Rebuild docs with DocFx 2.10.2.0
See every single generated html file changed.

### Expected result
A flag of config option to suppress insertion of meta name="generator" content="docfx x.y.z.a` tag to generated html files.

### Actual result
Generator tag with a DocFx version in every single html file.

**Comment by superyyrrzz** [comment]
Hi @sergeybykov , you can overwrite it in `docfx.json`'s global metadata like `"globalMetadata": {"_docfxVersion": "x.y.z.a"}`. But as affected by a bug, this option can only take effect from DocFX's next release v2.12
