### ISSUE TITLE
[Question]How to serve up the generated doc from an internal Confluence based wiki?

### ISSUE THREAD

**Issue by djwork** [dotnet/docfx#1253]
I was able to install the docfx.console package in one of my projects and serve up the generated docs to localhost:8080 via docfx.exe docfx.json --serve without problems.

But I was hoping to use docfx as part of our nightly build process on a build server and then host the generated docs from an internal Confluence based wiki. Not sure how to go about this as the generated static HTML doesn't work when accessed directly.

Any suggestions?

Thanks
Daniel Work

**Comment by superyyrrzz** [comment]
Hi @djwork, you can try importing HTML that DocFX generates into Confluence. I found a [converter](https://confluence.atlassian.com/disc/integration-and-utils/html-to-confluence-converter) in Confluence User Community. Of course, some extra work is needed to automate it on CI.

**Comment by lion92pl** [comment]
@djwork add below line to your `build` section in docfx.json:  
`"template": [ "statictoc" ]`
With this, opening index.html works well.

**Comment by superyyrrzz** [comment]
@djwork @lion92pl Does this solution work well for you?

As we received more and more feature requests to generate different kinds of output formats (mainly Markdown format for different CMS), we are considering this issue as a general solution. Each format should have a tool to generate HTML into their format to support this.
