### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by PompolutZ** [dotnet/docfx#1255]
### Title
*Customizing theme using 'theme' property doesn't work*  
I've tried following documentation of how to change theme using 'theme' property for build, but it doesn't work. I always get: [Apply Theme.ExportResourceFiles]Unable to find matching resource theme/*.css. 

### Minimal repro steps
1. Add main.css under theme folder
2. Specify property theme: "theme/*.css"

### Expected result
I've expected main.css generated by the default template to be replaced with main.css I have specified.

### Actual result
main.css was empty like in the default tempate.

### Further technical details
After some googling I've got an idea, that specifying custom template and putting main.css under styles folder replaces default main.css like it does replace all files in the template with the same name.

But it would be great if someone could provide better explanation of how to edit css using themes

**Comment by superyyrrzz** [comment]
Hi @PompolutZ , the property `theme` could either be a folder or a zip file, but can't be a glob pattern or a single file. You can try putting your `main.css` under `theme/styles` and specifying property `"theme": "theme"`.
More info can be found in user manual: http://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html
