### ISSUE TITLE
Source attribute of <code> node is not considered during API documentation generation

### ISSUE THREAD

**Issue by sebastianlux** [dotnet/docfx#1266]
### Title
Auto generated API Documentation does not display example code added with `<code source="..` syntax.

### Functional impact
Cant migrate from [SHFB](https://github.com/EWSoftware/SHFB) to docfx because API documentation as partially broken.

### Minimal repro steps
1. Create a project in the src folder of your docfx project
2. Add a new folder `BaseClasses` in the vs project
3. Add a class `Class1.cs` within the folder `BaseClasses`
4. Add a method called `Foo()` to class `Class1.cs` and add the following XML Documentation above the method
```
/// <summary>
/// This is Foo.
/// </summary>
/// <example>
/// <list type="number">
/// <item>
/// This example illustrates that docfx is not working as intended
/// <code source="../Examples/UserControl.xaml" region="Example1" language="XAML" />
/// </item>
/// </list>
/// </example>
```
5. Add a new folder in the vs project named `Examples`
6. Add a new WPF user control within the `Examples` folder named `UserControl.xaml`
7. Wrap the content of `UserControl.xaml` in a region named `Example1`
8. Compile the API documentation with docfx

### Expected result
I see the code example within a numbered list.

### Actual result
I see the numbered list, but it has no content at all.

**Comment by vwxyzh** [comment]
#910

**Comment by sebastianlux** [comment]
Hi,

I just tried out the latest version (2.18.4) to verify that this issue has been fixed. 
Unfortunately my specific case (using a **list** inside the **example** node) does still not work. 

Can you please reopen this issue?

![image](https://user-images.githubusercontent.com/6784951/27009645-afdcb692-4e93-11e7-9cae-555cb64b1b59.png)


Thanks

Sebastian
