### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by simonmurdock** [dotnet/docfx#127]
Can you guys provide some information on how to include custom CSS. 
I see you guys are using a hero CSS style for the official docfx page here http://dotnet.github.io/docfx/

I would like to do something similar but I'm not clear on how.

**Comment by vicancy** [comment]
One way is to create a folder `template` in your own project. Inside `template` folder, create a subfolder naming `styles`, with a file `main.css`, and put your own css inside `main.css`. Also change the value for `template` in your `docfx.json` to 
```
"template": [
      "default",
      "template"
    ]
```
Sample from docfx: https://github.com/dotnet/docfx/blob/dev/Documentation/template/styles/main.css and https://github.com/dotnet/docfx/blob/dev/Documentation/docfx.json#L53

**Comment by vicancy** [comment]
We are planning to do some refactor on template customization, so the advanced tutorial on customizing templates may be on hold until then.

**Comment by simonmurdock** [comment]
Ok cool. As long as I can include my own style until then that will be fine

**Comment by vicancy** [comment]
FYI, v1.4 released and there is no need to include `head.tmpl.partial` now.

**Comment by herohua** [comment]
@txwizard You may find the CSS file at https://github.com/dotnet/docfx/blob/200c02e53975d24989fd9957219a9c8e1e88ad60/Documentation/custom_template/styles/main.css

**Comment by LeonardoDaLuz** [comment]
very difficult to customize the doc fx generated site, I've been getting beaten for 1 hour just trying to hide the inherited members with css.
