### ISSUE TITLE
Making file metadata available in ManifestItems

### ISSUE THREAD

**Issue by JeremyTCD** [dotnet/docfx#1294]
### Making file metadata available in `ManifestItem`s
`ManifestItem`s supplied to post processors do not have direct access to file metadata. This can be worked around by manually copying `FileModel.Content` items to `FileModel.ManifestProperties` in a build step.

### Functional impact
This means per file configuration for post processors requires an extra, non-obvious step.

### Minimal repro steps
1. Create a post processor
2. `ManifestItem.Metadata` is always empty unless the above mentioned workaround is utilized.

### Solution
If this is by design, I suggest adding a note to ["How-to: Add a customized post processor"](http://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html). A couple of lines on how to supply file metadata to post processors might benefit plugin writers.  

If it is not by design, perhaps directly copying file metadata to `ManifestItem`s would be an option. I could submit a pull request for either option, let me know which fix is better and if I am missing anything.

**Comment by superyyrrzz** [comment]
Hi @JeremyTCD , post processor aims to process the html generated by file model, so the file model is no longer needed in this step. What about adding your step in [plugin](http://dotnet.github.io/docfx/tutorial/howto_build_your_own_type_of_documentation_with_custom_plug-in.html)'s `Postbuild`?

**Comment by JeremyTCD** [comment]
Hi @superyyrrzz, say someone creates a custom search index generator and would like it to exclude some files from the search index. E.g in the .net documentation, they might want to exclude the [welcome page](https://docs.microsoft.com/en-us/dotnet/articles/welcome) from search results. They could include the following property in welcome.md:
```YAML
# welcome.md
---
_excludeFromSearch: true
...
---
``` 
Then the search index post processor could ignore files with an `_excludeFromSearch` property. I think in general per file metadata can be useful when processing the output html files.

**Comment by JeremyTCD** [comment]
I was building a post processor that sorts and lists articles by date. This could only be done after the html was generated so that snippets of each article could be included in the list. Some conceptual files needed to be excluded. I used a [build step's PostBuild function](https://github.com/JeremyTCD/DocFxPlugins/blob/master/src/DocFxPlugins/ArticleListBuildStep.cs) to copy `FileModel.Content` properties to `FileModel.ManifestProperties` . File metadata is then copied to `ManifestItem.Metadata` by DocFx, making per file metadata available in my post processor. Perhaps this should be documented.

**Comment by superyyrrzz** [comment]
Thanks for your sharing. It's a nice solution to save needed properties in PostBuild in your scenario. Customizing the template to save them in page header meta may be another option.
By the way, we'll update document about post processor.

**Comment by JeremyTCD** [comment]
Ok sure, thanks for all the work on DocFx!
