### ISSUE TITLE
Support for cref in inheritdoc tags

### ISSUE THREAD

**Issue by matkoch** [dotnet/docfx#1306]
Following up on #247.

In regards to [this comment]( https://github.com/dotnet/docfx/commit/a2ba6d52432731a26af11c4f532c011fb7a78fe3#diff-a8bc073a917585e3db210c4032ae314cR253), I would like to refer to my comment in the related [roslyn issue](https://github.com/dotnet/roslyn/issues/67#issuecomment-206877691) again.

**Comment by rymeskar** [comment]
+1, to be more precise.

In fact, I would appreciate an introduction of all the currently [non-supported features from the list](https://dotnet.github.io/docfx/spec/triple_slash_comments_spec.html#inheritdoc).

**Comment by amirebrahimi** [comment]
Any feedback before I create a PR? Here's my proposed solution:
https://github.com/dotnet/docfx/commit/1ae5ba19629a4f444419f86e663d99b4fdd2f3e9

**Comment by rymeskar** [comment]
For completeness, please make sure the [documentation](https://dotnet.github.io/docfx/spec/triple_slash_comments_spec.html#inheritdoc) is updated.

**Comment by superyyrrzz** [comment]
@rymeskar Sure. It will be updated along with docfx release.

**Comment by kygagner** [comment]
As far as I can see from the commits for this PR (https://github.com/dotnet/docfx/pull/5491/commits), none of the commits actually made it onto main. Actually, Github says these commits aren't on any branch. So, is this really fixed, or do we need to merge this change in again?

**Comment by yufeih** [comment]
`<inheritdoc>` implementation was updated to behave the same as Roslyn in #8589, both `<cref>` and `<path>` should be supported in after v2.65.0.

**Comment by kygagner** [comment]
@yufeih I am using version 2.67.1 and the entire inheritdoc feature is not working for me, but I will do some more investigation on my end. Thanks for pointing me to the latest PR.
