### ISSUE TITLE
DocFx fails to load multiple solutions in parallel

### ISSUE THREAD

**Issue by damned1** [dotnet/docfx#1319]
### Title

If "metadata"."files" key instructs to process more than one solution file DocFx fails to do that and process one solution file only.

### Functional impact

There is no possibility to process more than one solution file.

### Repro steps

I have two solutions for which I tried to generate the documentation. My "metadata" section of ```docfx.json``` looks as follow:

```
  "metadata": [
    {
      "src": [
        {
          "files": [
            "Client/**.sln",
            "Server/**.sln"
          ],
          "exclude": [
            "**/obj/**",
            "**/bin/**",
            "_site/**"
          ]
        }
      ],
      "dest": "api"
    }
  ]
```

When I perform "docfx docfx.json --serve" the application reports a warning:
> Warning: Error opening solution .../Server/xxxxxx.sln: Workspace is not empty.. Ignored.

and at the end the documentation is generated for the solution from "Client/" directory only.

It also happens when I use ```**/**.sln``` as source. In this case all solutions except one are reported with the mentioned warning.

### Expected result

All expected solutions are processed.

### Actual result

One solution is processed only. All remaining solutions are reported with warning and ignored.
> Warning: Error opening solution <solution_path> Workspace is not empty.. Ignored.

### Further technical details
I did some static code analysis for DocFx and Roslyn source code. It seems the warning is reported by ```ExtractMetadataWorker``` class (the worker) because ```MSBuildWorkspace``` class  does not support parallelism which is used by the worker in method ```async Task SaveAllMembersFromCacheAsync(...)```.

**Comment by Quethrosar** [comment]
Any work around for this? it's a rather big issue since we have tons of projects/ sln files that need metadata.

**Comment by damned1** [comment]
I would suggest to replace all references to the solution files with the references to the project files included in these solutions. This can be achieved by a custom-written preprocessor script. This is my quick idea. May not be good enough.

**Comment by vicancy** [comment]
Fixed in https://github.com/dotnet/docfx/pull/1728
