### ISSUE TITLE
API docs should contain attributes

### ISSUE THREAD

**Issue by Bomret** [dotnet/docfx#133]
At our company we're interested to use docfx as the main doc generation tool. Great work so far :) We have a quite large project and we'd need it to also include the attributes of classes, methods etc. in the generated api docs. A real world example would be the ObsoleteAttribute.

I'd love to help out, just give me a hint where this would fit best in the code base.

**Comment by simonmurdock** [comment]
This might actually be useful for our web API documentation to detail get/post/routing attributes.

**Comment by simonmurdock** [comment]
In fact now that I think about this @vicancy 
Documenting any kind of MVC-based API will be impossible without documenting method attributes. Particularly for those of us using AttributeRouting.

See my example below:
```
[GET("api/v7/WorkflowUsers/{id}"), HttpGet]
public IList<IWorkflowUser> Users(int id)
{
	return WorkflowUsersRepo.Get(id);
}
```

In this case the developer working against our API would have no idea that `WorkflowUsers()` is actually called via `api/v7/WorkflowUsers/`

**Comment by Lakritzator** [comment]
I second, or rather third, this request!

Although this tool is really good, there is certainly a loss of important information if attributes are not shown.

Attributes are used everywhere, some examples are:
- MEF -> [Import]
- Json / xml with [DataMember( Name = "elementname")]
etc etc

**Comment by vwxyzh** [comment]
for cs: 8728b3c728d8c1aa1a9a2ff0ecf1fd8a6d94d1d2
for vb: 88235db12dab40c79f05398925b6c9c1c2d429fe

attribute sample page: <http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.EntityModel.ViewModels.PageViewModel.html>

**Comment by Lakritzator** [comment]
Looks very good, is there a pre-release I can test to see if it works in all my use-cases?

**Comment by simonmurdock** [comment]
:+1:

**Comment by vicancy** [comment]
Hi @Lakritzator , we published v1.6.1, and this feature is supported now.

**Comment by Lakritzator** [comment]
Just had a little test, the attribute part looks great!
Finally the documentation is starting to get usable :+1: 

I found bug while testing, will create an issue for it.

**Comment by gatapia** [comment]
Looking at documenting attributes at the moment but I cannot for the life of me find how to turn this feature on, using docfx v2.40.2.  Looked through all docs on this site and no luck.

**Comment by superyyrrzz** [comment]
@gatapia  This is on by default. You can see many in this page: https://dotnet.github.io/docfx/api/Microsoft.DocAsCode.DataContracts.ManagedReference.ItemViewModel.html?q=itemviewmodel
