### ISSUE TITLE
Pdf generation

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#1336]
For some of our apps we still use chm files for help inside the app because: 
- It is a simple standalone file.
- It can be structured (i.e. have topics and subtopics).
- From our application we can jump directly to a topic when opening the help file.

Does docfx provide means to to generate chm files?

**Comment by superyyrrzz** [comment]
Which tool do you use to generate chm before? DocFX supports [post processor](http://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html), which can be used to add a step to convert generated html to chm.

**Comment by bitbonk** [comment]
For of our help (both API and conceptual) we use [Sandcastle Help File Builder](https://github.com/EWSoftware/SHFB) which among other formats is also able to generate chm file. I would assume that SHFB is the most commonly used (but not really loved) too to generate help for .NET projects. So I think it would really help and give docfx a lot of traction if there would be a good migration path from SHFB to docfx.

**Comment by bitbonk** [comment]
So to generate chm files I would

1. need to generate html using docfx in a form that can be consumed by a chm generator
2. find a chm generator that can generate chm from html that docfx produced

**Comment by vicancy** [comment]
Plan to support PDF in early April

**Comment by bqstony** [comment]
I would like the implementation from docs.microsoft.com (see https://docs.microsoft.com/en-us/dotnet/articles/welcome)

**Comment by vicancy** [comment]
Update status: resource working on PDF is limited, extend the task to March

**Comment by FSharpCSharp** [comment]
That sounds really great! Is there already an approximate plan, if one can count with a first testable version? This feature would be incredibly important.

**Comment by vicancy** [comment]
A pre-release version of `pdf` is released.
-----
**Please have a try and provide your feedback/suggestions.** 😄 

Steps to generate PDF for docfx-seed project https://github.com/docascode/docfx-seed .
1. Install the pre-release docfx: 
```
nuget.exe install docfx.console -Version 2.18.0-alpha-0605-gfcb705a -Source https://www.myget.org/F/docfx-dev/api/v3/index.json
```
After installation, docfx.exe is under folder *docfx.console/tools/*

2. Current design is that each TOC file generates a corresponding PDF file, TOC is also used as the cover page of the PDF, so we create a `toc.yml` file specially for PDF under a new folder `pdf`, using [TOC Include](http://dotnet.github.io/docfx/tutorial/intro_toc.html?q=toc%20inclu#link-to-another-toc-file) to include content from other TOC files.
```yml
- name: Home
  href: ../index.md
- name: Articles
  href: ../articles/toc.md
  homepage: ../articles/docfx_getting_started.md
- name: API Documentation
  href: ../obj/api/toc.yml
- name: REST API
  href: ../restapi/toc.md

```
3. Add "pdf" section in `docfx.json`, parameters are similar to "build" section, definitely it is using a different template (the builtin template is `pdf.default`), with another output destination. We also exclude TOC files as each TOC file generates a PDF file
```json
...
  "pdf": {
    "content": [
      {
        "files": [ "**/*.yml" ],
        "cwd": "obj/api",
        "dest": "api",
        "exclude": [
          "**/toc.yml"
        ]
      },
      {
        "files": [ "articles/**/*.md", "*.md", "toc.yml", "restapi/**" ],
        "exclude": [
          "**/toc.yml",
          "**/toc.md"
        ]
      },
      {
        "files": [ "pdf/toc.yml"]
      }
    ],
    "resource": [
      {
        "files": [ "articles/images/**"]
      }
    ],
    "overwrite": "specs/*.md",
    "dest": "_site-pdf"
  }
...
```
4. Run `docfx pdf` to generate the PDF file

Some improvements to make:
-----
1. Better PDF file name: could specify through config or command
2. Only generate PDF file in the output folder, currently html files are also generated
3. And more for you to add ...

**Comment by csnemes** [comment]
I can't make it work following the steps described. I've got errors during PDF generation. It seems that somehow docfx adds an extra .tmp to the path (`Convert the file : "c:/Temp/docfx-seed-master/_site-pdf/.tmp/pdf/../api/CatLibrary.Tom.html" - has exception, the details: The system cannot find the file specified`)

**Comment by vicancy** [comment]
@csnemes Looks like a recursive inclusion, files inside `_site-pdf` is included in docfx.json... did you call docfx pdf several times?

**Comment by csnemes** [comment]
I've managed to figure out that a trailing slash used in dest defintion caused the problem. Changing` "dest" : "_site-pdf/"` to `"dest" : "_site-pdf"` fixed the problem.

**Comment by sandersaares** [comment]
Very nice, seems to work quite well for my scenario. The template is super barebones but I imagine that is no surprise at such an early stage. Looking forward to advanced features like page and chapter numbers!

**Comment by vicancy** [comment]
@sandersaares wkhtmltopdf jumps to the *middle* page of the linked topic...

**Comment by bitbonk** [comment]
Today I have looked a bit deeper into PDF generation. The generated PDF looks *very* basic, which is OK since you can change the template yourself. But there are some things you cannot do that are really needed before PDF is a viable solution for technical documentation (for us):

1. support for footers and TOC with page numbers #2003
2. add support for a cover page #2004

**Comment by PascalSl** [comment]
I was playing around with the PDF-generation and I had two questions:

- Is there a way to control the complete layout of the PDF? I've still got to get acquainted with the templating system in DocFX so I might be missing something here, but from what I've gathered generating the PDF's is a bit less flexible that the site generation. For instance, for the PDF generation there is no template that enables you to style the articles themselves, or am I missing something? 

- How to debug your PDFs? It's difficult to figure out what is going wrong when you just get to see the outputted PDF. Is there a way to expose the HTML that is being used to generate the PDF from? Or are there other, better ways to debug the PDF generation?

**Comment by govert** [comment]
I'm interested in the initial topic of this issue, which was the generation of .chm help files. I require these for integration into existing software that links into .chm topics. It would be great to have a modern alternative to Sandcastle for docfx output. 

* Is there some guidance or a solution to making .chm file yet?
* Should I open a new topic for this, since this issue has been ~~highjacked~~ repurposed to discuss .pdfs?

**Comment by superyyrrzz** [comment]
As PDF feature has shipped for a while, I'd suggest to opening new issues for new feedbacks.

Note that you could expect delay response about PDF feature due to current [roadmap](https://github.com/dotnet/docfx/blob/dev/Roadmap.md#v2-strategy)
