### ISSUE TITLE
Files list doesn't appear to support relative paths.

### ISSUE THREAD

**Issue by grokys** [dotnet/docfx#134]
If I put the following in my `docfx.json` it works:

      "src": [
        {
          "cwd":  "../../src/",
          "files": [
            "Perspex.Base/Perspex.Base.csproj"
          ],
          "exclude": [ "**/bin/**", "**/obj/**" ]
        }

However, this doesn't work:

      "src": [
        {
          "files": [
            "../../src/Perspex.Base/Perspex.Base.csproj"
          ],
          "exclude": [ "**/bin/**", "**/obj/**" ]
        }

The two should be equivalent.

**Comment by vicancy** [comment]
inside `files` are glob patterns. `../` is not supported by design to make the glob pattern clean. More accurate message will be added to tell user that `../`  is not supported.

**Comment by simonmurdock** [comment]
Ah, good to know. I wasn't sure why glob wasn't working in files either. Maybe we could include a cwd of "./" from the docfx init output. So people know that option exists.

**Comment by vicancy** [comment]
sounds cool
