### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by petertiedemann** [dotnet/docfx#1346]
### Title
When docfx fails, it is very hard to figure out even what project was the cause and a single failing project will immediately abort the whole process.

### Functional impact
Makes it hard to debug problems.

### Minimal repro steps
Anything that causes docfx to fail to process 

### Expected result
Docfx to catch and log exceptions on problematic projects, indicating clearly what projects failed, but continue processing remaining projects.

### Actual result
See the output from https://github.com/dotnet/docfx/issues/1345 as an example.

**Comment by bitbonk** [comment]
I hade a similar issue when the Microsoft Build Tools for Visual Studio 2015 where not installed. There was nothing in the Exception and the long stack trace that could have given me the hint that this is the cause.

**Comment by vwxyzh** [comment]
#1670

**Comment by vicancy** [comment]
#1738
