### ISSUE TITLE
Support documentation of Cake build scripts

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#1349]
It would be nice if DocFX could be used to generate documentation for [Cake](http://cakebuild.net/) build scripts. Cake is a Roslyn based build automation tool. Cake scripts are C# scripts containing additional pre-processor statement.

Concrete use case is if I have for example a configuration object in my Cake script, which is pure C#, I currently cannot document this with DocFX because of two reasons:

* DocFX restricts meta data generation to files with a certain extension and won't work with `.cake` files.
* Even if I rename the files to `.cs` it wont work, since DocFX would skip them since the classes are not part of a namespace

**Comment by superyyrrzz** [comment]
Is this what you are looking for?
https://github.com/cake-contrib/Cake.DocFx

**Comment by pascalberger** [comment]
@superyyrrzz No this is a Cake addin for running DocFX. I was looking for using DocFX to create API documentation for Cake files.

**Comment by pascalberger** [comment]
An existing Cake addin which does document Cake tasks is [Cake.Graph](https://cake-contrib.github.io/Cake.Graph/)
