### ISSUE TITLE
inheritdoc doesn't copy description from parent interface

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/docfx#1357]
### Title
*A short description of the bug that becomes the issue title*  
The `inheritdoc` element doesn't copy description from parent interface when there are both a base class and an interface.

### Functional impact
*Does the bug result in any actual functional issue, if so, what?*  
The documentation isn't copied from the interface.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.* 

Create a project with two classes and one interface.
The second class uses the first class as base class and implements the interface.
Add the documentation to the interface method.
Implement the method in the second class.
Use `/// <inheritdoc />`.
Start docfx.
The documentation isn't copied from the interface even though there is only one method with the same signature in the project.

### Expected result
*What would you expect to happen if there wasn't a bug?*  
The documentation should've been copied from the interface.

### Actual result
*What is actually happening?*  
The documentation isn't copied.

### Further technical details
*Optional, details of the root cause if known*

**Comment by dermeister0** [comment]
It does not work for me for even simpler case, when class implements a single interface.

```
    public interface ITest
    {
        /// <summary>
        /// Writes 'Moo' to screen.
        /// </summary>
        void WriteMoo();
    }
```

```
    /// <summary>
    /// Basic implementation of ITest.
    /// </summary>
    public class Test : ITest
    {
        /// <inheritdoc />
        public void WriteMoo()
        {
            Console.WriteLine("Moo");
        }
    }
```

https://github.com/dermeister0/InheritdocTest

**Comment by vwxyzh** [comment]
@dermeister0 This bug should be resolve by #1214 , and it is released in 2.12

**Comment by fubar-coder** [comment]
@vwxyzh Can you please explain why a pull request that modifies only MD files is supposed to fix this issue?

**Comment by dermeister0** [comment]
@fubar-coder See https://github.com/dotnet/docfx/pull/1178.

**Comment by fubar-coder** [comment]
@dermeister0 #1178 is the initial implementation, but there are still bugs where inheritdoc isn't respected (which this issue is all about). This issue is definitely **not** fixed. It should be reopened.

**Comment by dermeister0** [comment]
I updated to version 2.16.8.3. The small example works fine, but it still does not work on real project. I'm investigating why. It's not generic interface like in #1516.
Any classes are not inherited. Class and interface are located in different assemblies.

**Comment by dermeister0** [comment]
I see a 'no metadata' warning in output

```
PS C:\Work\cheesecakefactory-configurator> docfx .\docs\docfx.json -f --loglevel verbose
[17-05-03 04:11:07.927]Verbose:Config file ".\docs\docfx.json" is used.
[17-05-03 04:11:09.347]Verbose:Successfully generated metadata C:/Work/Some.Project/src/Some.Project.Domain/obj/xdoc/cache/obj for Some.Project.Domain
[17-05-03 04:11:09.397]Warning:No metadata is generated for Some.Project.
Warning:No metadata is generated for Some.Project.
```

Verbose log does not have details why metadata is absent.

**Comment by vwxyzh** [comment]
@dermeister0 can you give me an example.

**Comment by dermeister0** [comment]
@vwxyzh The 'no metadata generated' issue is resolved in #1628. Thank you. I'm still trying to make a minimal project to reproduce the inheritdoc issue.

@fubar-coder I created example project to test your reported bug. It works correctly if interface is public. It does not copy documentation if interface is internal and that is correct.

1. Clone https://github.com/dermeister0/InheritdocTest repository.
2. Go to \docfx_project directory.
3. Run `docfx --serve` command.

```
    /// <summary>
    /// Interface for processes that could be stopped.
    /// </summary>
    public interface IStoppable
    {
        /// <summary>
        /// Stops the process.
        /// </summary>
        void Stop();
    }
```

```
    /// <summary>
    /// Interface for processes that could be paused.
    /// </summary>
    internal interface IPausable
    {
        /// <summary>
        /// Pauses the process.
        /// </summary>
        void Pause();
    }
```

```
    /// <summary>
    /// Base process.
    /// </summary>
    public class BaseProcess
    {
        /// <summary>
        /// Runs the process.
        /// </summary>
        public void Run()
        {
            Console.WriteLine("RUN");
        }
    }
```

```
    /// <summary>
    /// Inherited process.
    /// </summary>
    public class InheritedProcess : BaseProcess, IStoppable, IPausable
    {
        /// <inheritdoc />
        public void Pause()
        {
            Console.WriteLine("PAUSE");
        }

        /// <inheritdoc />
        public void Stop()
        {
            Console.WriteLine("STOP");
        }
    }
```

![2017-05-04_1516](https://cloud.githubusercontent.com/assets/4054844/25695294/b35cc8a4-30dc-11e7-9f39-ae092758cc18.png)

**Comment by fubar-coder** [comment]
@dermeister0 the strange thing is that it works sometimes... I'll try to find something reproducible.

**Comment by dermeister0** [comment]
I reported new bug: https://github.com/dotnet/docfx/issues/1632

**Comment by JimBobSquarePants** [comment]
> It does not copy documentation if interface is internal and that is correct.

Why is that behavior correct? If someone is implementing a common internal interface and explicitly uses `<inheritdoc/>` then they are expressing clear intent here which I would expect to be respected.

**Comment by thestonefox** [comment]
I'm still getting this issue on version 2.59.2.0

I'm using Inheritdoc and sometimes running docfx it picks up the inheritdoc and works correctly and other times it doesn't, I've not found a reason for it or a workaround either. Any ideas?

**Comment by thestonefox** [comment]
So it seems the first time I install a specific docfx version it works as expected, then when I run again it doesn't work

So I was on 2.59.2.0 and the first time it worked, then it didn't work. I uninstalled docfx and reinstalled 2.59.2.0 and ran it and again inheritdoc didn't work

I downgraded to 2.56.7 (uninstalled then reinstalled), ran docfx and inheritdoc worked, then I ran it again and inheritdoc didn't work again.

It always seems to work first try on install but then every subsequent time it doesn't work. I have to uninstall, install a different version that works once, then uninstall and install a different version again to get it to work

**Comment by thestonefox** [comment]
So i think what is happening is some of the `obj` directories are being left over and not being cleared up, when that happens it seems the cache isn't cleared and it skips the inheritdoc stuff.

I've manually deleted the obj directories when they get left over and it seems to fix the issue.
