### ISSUE TITLE
docfx converts <c> in source to <code> in yaml

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/docfx#1358]
### Title
*A short description of the bug that becomes the issue title*  
docfx converts `<c>` in source to `<code>` in yaml

### Functional impact
*Does the bug result in any actual functional issue, if so, what?*  
The `<c>` element encloses inline-code while `<code>` encloses multi-line code.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  
Create a `<c>` element inside an xmldoc comment.
Run docfx.

### Expected result
*What would you expect to happen if there wasn't a bug?*  
The `<c>` elements should result in inline code in the resulting markdown (or yaml) documents.

### Actual result
*What is actually happening?*  
The `<c>` element is converted to `<code>` which results in multi-line code in the resulting markdown (or yaml) documents.

### Further technical details
*Optional, details of the root cause if known*

**Comment by vicancy** [comment]
Hi @fubar-coder `<code>` is the inline-level code tag, while `<pre><code>` is the block-level code tag. The behavior is similar to markdown rendering, who transforms `` ` ``to `<code>` and ```` ``` ````  to `<pre><code>`.

**Comment by fubar-coder** [comment]
Ok, so this is a difference between xmldoc and what's used inside the yaml.
