### ISSUE TITLE
Minor: Strange wording in output message

### ISSUE THREAD

**Issue by grokys** [dotnet/docfx#136]
This is a really minor one ;)

The output from `docfx.exe` told me:

> There are totally 1 Warning(s), 0 Error(s)

The "totally" in there makes docfx sound like a california surfer dude. Maybe this was intentional (I like it personally, it made me laugh!) but I know that English isn't your team's first language so just giving you a heads up ;)

**Comment by vicancy** [comment]
Thank you @grokys for pointing it out. What wording will you suggest?

**Comment by grokys** [comment]
I'd suggest simply:

> There were 1 Warning(s), 0 Error(s)
