### ISSUE TITLE
Support .NET CLI based projects

### ISSUE THREAD

**Issue by danroth27** [dotnet/docfx#137]
Currently docfx supports DNX projects, which is great, but DNX is getting replaced by the new [.NET CLI](https://github.com/dotnet/cli) for .NET Core. ASP.NET Core is moving off of DNX and onto the new .NET CLI and DNX will be retired. We need to make sure that docfx works with .NET Core based projects.

@blackdwarf

**Comment by danroth27** [comment]
Note that the .NET CLI has a ready made workspace implementation that you can use: https://github.com/dotnet/cli/tree/rel/1.0.0/src/Microsoft.DotNet.ProjectModel.Workspaces

**Comment by MarzinZ** [comment]
Hi @danroth27 , is there an existing nuget package for the workspace implementation?

**Comment by danroth27** [comment]
You can get the latest .NET CLI packages from their dev feed: https://dotnet.myget.org/gallery/dotnet-core
If you want to pick up the candidate packages for rc2 then use their release feed: https://dotnet.myget.org/gallery/dotnet-core-rel

**Comment by MarzinZ** [comment]
Seems Microsoft.DotNet.ProjectModel.Workspaces package not found in above two feeds ? @danroth27

**Comment by danroth27** [comment]
My bad - looks like only the .NET Core packages are on those feeds.

@piotrpMSFT @blackdwarf @pranavkm Where can the docfx folks pick up the project model packages from the .NET CLI?

**Comment by davidfowl** [comment]
```XML
<add key="dotnet-cli" value="https://www.myget.org/F/dotnet-cli/api/v3/index.json" />
```

**Comment by qinezh** [comment]
Hey @danroth27 , docfx supported .NET CLI based projects now, you can try [the pre-release version](https://github.com/dotnet/docfx/releases/tag/1.9.0-alpha-0091-g1c1b291)

**Comment by danroth27** [comment]
Awesome! I will give this a spin tomorrow.

**Comment by qinezh** [comment]
@danroth27 BTW, the framework .NET 4.6.2 is no need to install before using docfx of this version
