### ISSUE TITLE
Add the package ID to the generated metadata documents

### ISSUE THREAD

**Issue by danroth27** [dotnet/docfx#139]
In addition to types, namespaces and assemblies the metadata generated by docfx should include the NuGet package ID of the types if available. The package ID is available in the project.json file for .NET Core based projects.

@blackdwarf

**Comment by blackdwarf** [comment]
@danroth27 when you say types, do you mean types in the code or in the dependencies?

**Comment by danroth27** [comment]
When I go to a page for class `Foo` I want to see which Nuget package it lives in.

**Comment by blackdwarf** [comment]
@danroth27 there are multiple ways we could do this, agreed that it would be useful. But I'm struggling with how docfx would actually do this, since when it scans the sources, is there a way to "know" that the sources being scanned will end up in a certain nuget package?

**Comment by danroth27** [comment]
Docfx understands project.json. The package ID is in the project.json file.

**Comment by vicancy** [comment]
with project.json deprecated, close this issue.
