### ISSUE TITLE
Tag class for multimedia (video / image)

### ISSUE THREAD

**Issue by ashengilevych** [dotnet/docfx#1400]
### Tag class for multimedia (video / image)

Hi, does docfx supports liquid templates like Jekill? I want to create some tag class for images and video. I want add in .md files something like this: 

`{% include image src="www.image.source" width="300" %}` 

and in image file I want use something like this: 

`<img src="{{ include.src }} width="{{ include.width }}"`

For example 

https://eduardoboucas.com/blog/2014/12/07/including-and-managing-images-in-jekyll.html

Can you help me? Can i do this in docfx if I will used liquid templates ?

Looking forward to your reply. Thank you!

**Comment by vicancy** [comment]
For docfx to include images/ videos, you can include the resources in your `docfx.json`:
```
"resource": [
      {
        "files": [ "**/images/**" ],
      }
```

And reference the images in your `.md` files using path relative to your markdown file with Markdown syntax: `![image](images/a.jpg)`

**Comment by ashengilevych** [comment]
@vicancy I am afraid, you don't understand me correctly. I need include not only image, I need include some HTML code, like some blocks with image and parameters. For example, I nee to have file like this:

`<div class="image_wrapper>`
  ` <img `
`            src="inlude.src `
`            {% if include.width %} `
`                  width="{{ include.width }}"`
`            {% endif %}`
` </div>`


and in markdown files - I want to use something like this (Liquid syntax):

`{% include image.html src="some_source" width="500" %}`

All script like at article  https://eduardoboucas.com/blog/2014/12/07/including-and-managing-images-in-jekyll.html

Looking forward to your reply. Thank you!

**Comment by vicancy** [comment]
No, `docfx` does not support Liquid syntax inside Markdown.

For now, your requirement is not supported. 

To implement similar feature, we may extend current [*File Inclusion*](http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#file-inclusion)  syntax to support parameters. `[!include[<title>](<filepath>?src=some_source&width=500)]`

@chenkennt @vwxyzh Any comments?

**Comment by ashengilevych** [comment]
@vicancy It will be very cool if you extend this syntax to support the parameters. This is very scarce for the moment. It would be very convenient to use this feature.
