### ISSUE TITLE
Adding the reference to a project assembly two times in csproj file crashes docfx

### ISSUE THREAD

**Issue by xenux** [dotnet/docfx#1414]
### Title
Adding the reference to a project assembly two times in csproj file crashes docfx during metadata extraction.

### Functional impact
when editing csproj by hand (or with git automatic merge from two branches) it happens that the reference to the same assembly is added two times. when it happens docfx crash during metadata extraction.

### Minimal repro steps
- Create project A.
- Create project B.
- Add reference to project A from project B.
- Save.
- Open B.csproj 
- Duplicate following lines:
 ```
 <ItemGroup>
    <ProjectReference Include="..\A\A.csproj">
      <Project>{046f7d79-105a-4cb1-aa39-5545f82b4b1a}</Project>
      <Name>A</Name>
    </ProjectReference>
  </ItemGroup>
```
- Use one class of A inside B to be sure nothing is optimized out.
- Build metadata on B.
-> crash
[stacktrace.txt](https://github.com/dotnet/docfx/files/833620/stacktrace.txt)

### Expected result
Second reference should be ignored

### Actual result
Argument Exception the same assembly is added two times in a dictionary collection crashing the build
A task was

**Comment by vicancy** [comment]
Thanks for reporting the issue. We will take a look.

**Comment by superyyrrzz** [comment]
It's fixed since v2.14

**Comment by ElanHasson** [comment]
@superyyrrzz this is still an issue, I encountered it with latest version,

**Comment by superyyrrzz** [comment]
@ElanHasson Could you please open an issue with detailed steps to help us reproduce?
