### ISSUE TITLE
Add GitHub integration tutorial please.

### ISSUE THREAD

**Issue by IgnatevSV** [dotnet/docfx#1439]
Please, add some more information, how to use integration with GitHub, because this is really not enough.
I created sample project from quickstart tutorial, but "Improve this Doc" / "View Source" buttons wasn't showed there. Also I tried to create test project(https://github.com/IgnatevSV/ignatev_docfx_example) and use "docfx-seed" project(https://github.com/docascode/docfx-seed), but "Improve this Doc" / "View Source" buttons didn't appear. Also in my project i used already generated HTML-Website by DocFX, but in other people projects like "docfx-seed" it seems it working somehow without it.
I just don't understand, how to correctly create, enable and use it. Add some additional information, please.

DocFX version: 2.13.2

**Comment by vicancy** [comment]
Hi @IgnatevSV, thanks for reporting the issue.

`docfx` fails to get the source file path from source code when your input files are `"files": ["src/**.cs"]`, change it to `"files": ["src/**.sln"]` and have a retry. https://github.com/IgnatevSV/ignatev_docfx_example/pull/1 

For why `docfx` fails to extract the source file info direct from source files, we will investigate.

**Comment by IgnatevSV** [comment]
Hi @vicancy! Thanks for reply!

I used ".cs" decription over ".sln" to avoid long enumeration of inherited members.
Anyway, i tried to change it to ".sln", but "Improve this Doc" / "View Source" buttons still had disabled.
Also, website loaded from master branch still incorrect. I still load github pages files from "docs" folder, which were pre-generated by DocFX.

**Comment by vicancy** [comment]
The output folder is defined in docfx.json, or in command line with `-o` option. Your case the generated website should be in `_site` folder. Please run `docfx --serve` to serve the website by docfx and check the latest result. In my local machine, it works. 

Note that "Improve this Doc" / "View Source" is disabled in namespace pages.

**Comment by IgnatevSV** [comment]
> The output folder is defined in docfx.json, or in command line with -o option. Your case the generated website should be in _site folder.
Yes, i know. I just replaced it manually.
>Please run docfx --serve to serve the website by docfx and check the latest result. In my local machine, it works.
I got the same result as here:
https://ignatevsv.github.io/ignatev_docfx_example/
So there are still no buttons to GitHub.

![image](https://cloud.githubusercontent.com/assets/12615019/24135091/35786f5a-0e19-11e7-8333-73ace32cf7cb.png)

**Comment by hellosnow** [comment]
From [page](https://ignatevsv.github.io/ignatev_docfx_example/articles/user_article.html), source code [affix template](https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/partials/affix.tmpl.partial#L8) and [conceptual.html.primary.js](https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/conceptual.html.primary.js#L12), I think `docurl` is null here, and we will investigate on [common.js](https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/common/common.js#L37) why it's generating null docurl.

**Comment by vicancy** [comment]
How did you generate the page? Your repo works perfectly in my local machine.
How about setting up AppVeyor as similar to https://github.com/docascode/docfx-seed/blob/master/appveyor.yml to see if it works in a clean environment?

**Comment by IgnatevSV** [comment]
>How did you generate the page?

By `docfx ignatev_docfx_example\docfx.json --serve` command.

If this way is wrong, can you describe the correct way, please?

I know about separate-command way like `docfx ignatev_docfx_example\docfx.json` command to build website and `docfx serve ignatev_docfx_example\_site` command to run website. This way gives the same result.

>How about setting up AppVeyor

I have no any experience with this tool, so results probably will be incorrect. My bad, sorry.

Also, i had installed Build Tools 2015 and **_Visual Studio Community 2017_**. There can be a problem in this?

**Comment by vicancy** [comment]
Could you run `docfx -f` with `docfx.json` changes to include the `sln` file? `-f` means no incremental build.

If it does not help, could you provide me a generated `yml` file under `api` folder?

**Comment by IgnatevSV** [comment]
So, i run command `docfx docfx_issue_example\docfx.json -q`
Unfortunately, it didn't help.
https://github.com/IgnatevSV/docfx_issue_example/tree/master/api

**Comment by IgnatevSV** [comment]
So, i run command `docfx docfx_issue_example\docfx.json -q`
Then i run `docfx serve docfx_issue_example\_site`
Unfortunately, it didn't help.
yml files:
https://github.com/IgnatevSV/docfx_issue_example/tree/master/api

**Comment by vicancy** [comment]
what happens when you run `where git` on your OS?
Any 'git' related error message shown when running `docfx`?
Actually currently `docfx` relies on `git` to fetch repo information, it fails when `git` is not globally found.https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Common/CommandUtility.cs#L119

**Comment by IgnatevSV** [comment]
>what happens when you run where git on your OS?

So, here is my mistake. I used "GitHub Desktop"(https://desktop.github.com/), but not installed the Git(https://git-for-windows.github.io/).
So, after git installation it all perfectly works. I'm sorry, my fault.
Thank you very much for your help. On my own I would have been searching for a reason for a long time.

**Comment by vicancy** [comment]
@qinezh As we rely on `git`, is it better for us to 
1. Mention the behavior in our documentation
2. Provide an option for user to config their `git` PATH in `docfx.json`?
