### ISSUE TITLE
Documentation for multible hosted repositories

### ISSUE THREAD

**Issue by jwillmer** [dotnet/docfx#1443]
I like to create a documentation that contains different projects that I host on GitHub. Is it possible to specify GitHub repositories so that they are retrieved on each build? If it is possible, how can I provide GitHub credentials for private repositories?

**Comment by vicancy** [comment]
`docfx` run against local files, and it calls `git.exe` to fetch git information. So as long as you can use `git` you can use `docfx` to get repository information.

**Comment by jwillmer** [comment]
that is perfect but how?

**Comment by vicancy** [comment]
Hi @jwillmer , please follow [Step4. Add another API documentation](https://github.com/dotnet/docfx/blob/dev/Documentation/tutorial/walkthrough/walkthrough_create_a_docfx_project_2.md) to add multiple projects.

**Comment by jwillmer** [comment]
I don't get how this helps me to link remote git projects.

**Comment by vicancy** [comment]
Simply `git clone` your projects to local folder and run docfx.

**Comment by jwillmer** [comment]
Yes but if I use `git clone` the root repository would have no idea of the content in the sub repository. That means that I can't save it. I guess I need to use [`submodules`](https://git-scm.com/book/en/v2/Git-Tools-Submodules) - I will try.

**Comment by jwillmer** [comment]
Works like expected with `submodules`.
