### ISSUE TITLE
Documentation for Default Template? Alternative Templates?

### ISSUE THREAD

**Issue by markolbert** [dotnet/docfx#1454]
This is a very interesting project with a lot of potential currently, IMHO, stymied by both the design of the default template and the lack of documentation for it.

For example, I wanted to replace the default logo with my own. Simple enough, right?

Except...if the image is taller than 50 or 60 pixels (I forget which), the navbar links disappear and are replaced by the hamburger menu. Because the height of the navbar is hard-coded into the javascript which creates the navbar links, which are in turn created via the moustache template language.

Figuring out how all the moving parts of the default template work is challenging because the design spans multiple files and multiple 'languages' (e.g., moustache and javascript). 

The simplicity of moustache is nice. But the fact that there are dozens of javascript functions that are apparently essential to making the pieces all come together correctly makes me think that simplicity in one place was achieved by creating much higher levels of complexity elsewhere. 

Of course, I'm no worse off walking away from docfx than I was before I found it, since acquiring it didn't cost me anything. For which thanx. Sincerely.

But I'd appreciate either better documentation on how this stuff all comes together, or links to places that have some good walk throughs on creating templates (the material on the site is nice but way too limited for something this involved).

Any references you can share?

**Comment by vicancy** [comment]
I totally agree with you.
For one thing, the documentation for default template is not enough, and honestly speaking the design of default template is too complex and dependent much on javascript for rendering.
For another, comparing to other website generators, DocFX lacks a well-formed documentation on themes and templates, and lacks an appealing set of beautiful themes.
It should be our top priority to set up a place for others to easily contribute, show and share their themes/ templates. Really appreciate your feedback @markolbert, we will start working on that soon.
If you have any other suggestions, just let us know.

**Comment by markolbert** [comment]
I would love to see such a place set up. I might even try to contribute something :)

Is there documentation available someplace that describes how the various object values are set before they're processed by the moustache files? I'm trying to piece together the overall flow so I can create my own simple theme, the default one being too complex for me to modify in an intelligent way.

**Comment by vicancy** [comment]
[Template System](http://dotnet.github.io/docfx/tutorial/intro_template.html#the-input-data-model) describes the data model used.
A quick way is to call `docfx build --exportViewModel`, and the `.json` file generated is the data model for applying mustache.

**Comment by vicancy** [comment]
A draft version https://github.com/dotnet/docfx/pull/1500
