### ISSUE TITLE
Support for xproj?

### ISSUE THREAD

**Issue by vivsriaus** [dotnet/docfx#146]
I have a solution that uses xproj instead of csproj. Docfx doesn't seem to support it while building. This is what I have in my config file:
"src": [
        {
          "files": [ "**/*.sln", "**/*.xproj" ],

and the error:
Warning: File A:/newGit6/docfx-seed/src/ARM/Microsoft.Azure.ResourceManager/Microsoft.Azure.ResourceManager.xproj is not supported, supported file extension are: .sln,.csproj,.vbproj,.cs,.vb. The file will be ignored.

Are there plans to support generating documentation from an xproj?

**Comment by vicancy** [comment]
project.json is support. you can use DNX version of `docfx` for `project.json`.

**Comment by vivsriaus** [comment]
@vicancy Thanks for the response. Are there are any steps documented online, that shows how I can generate documentation if I include .xproj in my src folder?

**Comment by vicancy** [comment]
please include `project.json` instead of `.xproj`
@MichaCo has his documentation using `project.json` FYI: https://github.com/MichaCo/CacheManager/blob/master/Documentation/docfx.json

#169 talks about it.
