### ISSUE TITLE
Inappropriate warning when specifying config file

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#1483]
Version 2.14.1 (but it's been like this for as long as I've been using it.)

When specifying a configuration file on the command line, a shouty warning is issued:

> Warning: Config file [...] is found in command line! This file and ONLY this file will be used in generating metadata, other command line parameters will be ignored.

Yes, I know a config file is specified on the command line. I specified it. I don't need to be "warned" about something I did fairly obviously deliberately. This warning obscures *genuine* potential problems - and as far as I know, there's no way to remove just this warning.

Two options:

- Add a command-line *option* for the config file, rather than just using the first argument; you could then warn for the implicit version, but not the explicit version
- Just remove the warning entirely

**Comment by superyyrrzz** [comment]
I found you are using `docfx history/$version/docfx.json metadata -f`. As DocFX only take the first parameter as sub command, the `metadata` here is treated as a config. Can you try `docfx metadata history/$version/docfx.json -f`?

**Comment by jskeet** [comment]
@superyyrrzz: Aha, yes, that works. Thanks, will close this issue...

**Comment by jskeet** [comment]
(And of course if I'd read further into the warning, it would have told me that. I stopped at the "only this file will be used"...)
