### ISSUE TITLE
Generate partial from yml file?

### ISSUE THREAD

**Issue by markolbert** [dotnet/docfx#1484]
I'm creating my own template because, frankly, the default one is way too sophisticated to learn how to use docfx.

I would like to be able to generate a partial block of html from a yml file and then insert it at the appropriate point in my primary conceptual template. But I'm not sure how to do this.

Since there's already a toc.html.tmpl file in the default template, do I need to delete it so that toc files will be handled by the partial that I write?

BTW, if I'm understanding the default template correctly, generating an html fragment from a yml file is not the way the default template works. It appears to take the approach of generating an html file and then pulls out the desired table of contents fragment from that file. 

Since that seems like a lot more work than what I was thinking of doing, it may be that what I'd like to do (yml -> partial html -> embedded via moustache in conceptual.html) isn't possible. In which case, please let me know that :)

**Comment by vicancy** [comment]
Clarify the question: Do you want to share data inside one specify yml file with all the other templates? For example, you want to get the TOC model inside the toc.yml file, and in conceptual template, using that TOC model?

**Comment by markolbert** [comment]
Yes, that's an example of what I'd like to do. I'd like to add/merge the data from the toc.yml file to what's coming in from a separate conceptual file, and use both sources of data to generate a single html file.

**Comment by vicancy** [comment]
`statictoc` provides a sample to share toc model, https://github.com/dotnet/docfx/blob/master/src/docfx.website.themes/statictoc/toc.tmpl.js , if the model is marked as `isShared`, the model will be stored in http://dotnet.github.io/docfx/tutorial/intro_template.html#globally-shared-properties, and can be consumed later in `transform`, e.g. https://github.com/dotnet/docfx/blob/master/src/docfx.website.themes/statictoc/conceptual.html.primary.js#L14
