### ISSUE TITLE
Use Razor Engine to Generate html?

### ISSUE THREAD

**Issue by markolbert** [dotnet/docfx#1485]
Was consideration given to using the AspNet Core Razor engine to generate html output? In other words, focus docfx on assembling all the metadata from the source files and standalone markdown files, but leave the actual creation of html to the Razor engine? 

It seems to me that would leverage the significant investment in Razor, and take advantage of its built-in programming features, which provide both dotnet and javascript capabilities.

I'm not sure how to handle markdown files in such an approach. But I suspect someone has written a markdown to html converter that could be incorporated relatively easily.

**Comment by vicancy** [comment]
We support `liquid` syntax, if you'd like programming features. http://dotnet.github.io/docfx/tutorial/intro_template.html#renderer-in-liquid-syntax

**Comment by markolbert** [comment]
Thanx. I'd seen that, but hadn't looked into it.
