### ISSUE TITLE
only triple-slash comment in output

### ISSUE THREAD

**Issue by iwhp** [dotnet/docfx#149]
I would like to only output the triple-slash comments, no C# API.
How would that be possible?
Thankx, Harry

**Comment by vicancy** [comment]
VS IDE supports generating triple-slash comments as XML files. Is that what you want?

**Comment by iwhp** [comment]
Thankx, vacancy... yes that is true. But my understanding is, that DocFx does not use them (or at least I do not have to configure this, since DocFx uses Roslyn and I guess DocFx takes everything from that).

I would just like to have my triple-slash comments in the output of DocFx, non of the auto API C# (like Class, Properties, etc.) comments.

**Comment by vicancy** [comment]
Hi iwhp, could you tell us more about the user scenario? why do you want such output with only triple-slash comments? What for?

**Comment by iwhp** [comment]
Hi vicancy. We put lots of business related documentation (specially in the domain layer) into our triple-slash comments. The comments are a big help for developers as well as super-end-users. We could use the output for our super-end-users. I could imagine that even some end-users could benefit from it. But they would be overwhelmed with the API stuff.

Could I just change the templates and so get rid of all the API documentation?

**Comment by vicancy** [comment]
So you wanna extract the comment out from the projects however don't want a documentation website generated? A simple way to do this is to use `docfx metadata` to generate the the `YAML` files and create your own program to de-serialize that and filter out not used properties. The metadata format follows http://dotnet.github.io/docfx/spec/metadata_dotnet_spec.html

**Comment by iwhp** [comment]
Not exactly, but this could be another route to go. Thankx!

What I am looking for:
Imagine the following. A developer writes many trible-slash comments, uses the docfx tools and only gets back a documentation in the form of today (with toc, etc), but only containing the comments written and not the other stuff extracted by Roslyn.

Lets say we have a class with no triple-slash comments, this class should not be in the documentation, since there are not comments written by the dev.

Lets say we have a class where only one properties does have a triple-slash comment, only this property should be in the output.

Lets say we have a class where only the class itself does have a triple-slash comment, only this class is in the documentation, but non of the properties since they do not have any triple-slach comments. etc.

So if we have a class with triple-slash comments, either on top of the class or on the properties, all the comments should be in the output of docx.

**Comment by simonmurdock** [comment]
I think he wants the same website etc, but only for elements with triple-slash comments

**Comment by iwhp** [comment]
yap... thankx for this easy one ;-)

**Comment by chenkennt** [comment]
Hi @iwhp, from your description, seems you're looking for a way to exclude elements which are "less" important. How about we have a functionality to allow you filter some of the elements that you don't want to document (through an attribute or a whitelist)? I don't really like the idea to auto exclude the elements that doesn't have comments, some of them may still be useful even without comments.

**Comment by simonmurdock** [comment]
@chenkennt namespace globs?

**Comment by iwhp** [comment]
Hi chenkennt... yes your suggestion would help a lot. Thankx Harry

**Comment by chenkennt** [comment]
@simonmurdock yes something like that. @iwhp we plan to implement this later, will keep you posted.

**Comment by tungnt185** [comment]
Hi all,

I think I have the same request like this guy. I'm using SandCastle sometimes and it has Visibility function help us can choose which API you want to generate.

Do you have any plan to support this @chenkennt ?

Thanks

**Comment by chenkennt** [comment]
@tungnt185 yes that's in our plan, though it won't be using the same syntax as Sandcastle.

**Comment by ansyral** [comment]
this is implemented in ddd677a3155a8f80d2ace9fab0f7cc5f805a04d5, ad79f304313d1bd55c011425a809b7fe4a4bbf60
