### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by jpelouse** [dotnet/docfx#150]
Hello! The default template provides the ability to search the navigation tree. Is there any support for full text search possible so far? 
Thanks, Jörg

**Comment by vicancy** [comment]
We plan to add a full-text client-side search to default template, targeting early April.

**Comment by MarzinZ** [comment]
2f4aa676cf657f94fe795eb3ca633e969e2161f5

**Comment by MarzinZ** [comment]
Hi @jpelouse , full text search is already supported in latest release, thanks
