### ISSUE TITLE
The look of tables in the default template is a bit too basic and not readable

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#1506]
This is a reiteration of [this stackoverflow question](http://stackoverflow.com/questions/35916505/docfx-format-tables-using-markdown-without-changing-the-template).

The following table is not very good readable, because of the spacing between the columns. Event there is no alternating row color:

    | Property | Description |
    |---|---|
    | URL | `/api/<version>/auth/login` |
    | Method | `post` |
    | Success | Http status *200* |
    | Failure | Http-status *400/500* |
    | Content/Media-Type | `application/json` |
    | Authorization | *no* |
    | Roles | - |

That is how it is looking in `doxfx`:

[![MD-Table][1]][1]

Some kind of expected behaviour:

[![Expected][2]][2]

The tables in the default templates should look like in the screenshot, because it is much more readable and that's the way to look at various other places too (like github).

  [1]: http://i.stack.imgur.com/EvGtN.png
  [2]: http://i.stack.imgur.com/rADU7.png

**Comment by superyyrrzz** [comment]
Are you using DocFX 2.6.2? This should have been fixed in #957. You can try the latest DocFX.

**Comment by bitbonk** [comment]
Yes I am using 2.6.2
> c:\> docfx --help
> docfx 2.6.2.0

**Comment by bitbonk** [comment]
I am terribly sorry. I am pretty sure chocolaty did show an update for docfx when I checked yesterday. Everything works fine with the current version (2.15.3.0). This issue can be closed,
