### ISSUE TITLE
TOC CSS for small screens

### ISSUE THREAD

**Issue by CarsonTolleshaug** [dotnet/docfx#1510]
## Problem
The CSS that styles the table of contents seems to break for small screens. Random commas and weird spacing as well as overlapping text in some areas.

## Repro Steps
View any docfx page with a side toc on a browser (I used edge) with a screen width of <768 px. Open the toc by clicking the "Show / Hide Table of Contents" link at the top of the page. You'll see that level 2 headers are spaced in a  way that is very strange and there are random commas all over the place. Oddly, level 3 headers seems to display *okay*, though they force the list to be displayed vertically when I'm pretty sure the intention was horizontal.

I noticed this while experimenting with edge's emulation feature, so it stands to reason that mobile browsers would display this way as well.

I've actually fixed this issue for myself by overriding the CSS with some of my own, but I thought I should notify you since this even shows up on **[the main docfx website](http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html)**

Cheers!
-Carson

PS: Also the headers remain text-align: centered if you view the toc on a smaller width and then expand the screen to normal browsing size.

**Comment by vicancy** [comment]
Thanks for reporting the issue.
