### ISSUE TITLE
How can I refer to a UID with a hash in it from a Markdown xref?

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#1512]
I'm generating an API difference between different versions - you can see an example at
http://nodatime.org/2.0.x/api/changes.html

I link to newly-introduced members... but any member with a `#` in the UID fails.  For example, in my Markdown I have:

```text
- [NodaTime.Interval.ctor(System.Nullable{NodaTime.Instant},System.Nullable{NodaTime.Instant})](xref:NodaTime.Interval.#ctor(System.Nullable{NodaTime.Instant},System.Nullable{NodaTime.Instant})) (Constructor)
```

... but the reference can't be resolved. Is there something I need to do to escape the `#`?

**Comment by superyyrrzz** [comment]
Replace `#` with `%23` can work. `#` is considered a hashtag in the target page. See: http://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-hashtag-in-cross-reference

**Comment by jskeet** [comment]
Excellent - could I suggest adding that information to http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html, or maybe just add to the bit starting "You can use one of the following syntax to cross reference a topic with UID defined:" something along the lines of "the UID must be URL encoded"?

(I'd looked at the *start* of the "links and cross references" documentation, but hadn't got that far.)

**Comment by superyyrrzz** [comment]
Thanks for your suggestion. Agree that this message should be in a more significant place. I've added it.

**Comment by jskeet** [comment]
Great, thanks :) Closing the issue now as I don't think there's anything else that needs doing.
