### ISSUE TITLE
Inheritdoc doesn't copy from generic interfaces

### ISSUE THREAD

**Issue by MichaCo** [dotnet/docfx#1516]
### Title
For simple cases, <inheritdoc /> comments get copied just fine from an interface a class implements.
But if the interface is a generic type, e.g.

    public interface IInterface<TSomething>

it does not work.

### Functional impact
The result is, the documentation summary does not get copied from the interface to the actual implementation

### Minimal repro steps
* create an interface which has a generic type, 
* implement it in a class, 
* document a method of the interface
* add <inheritdoc /> to the implementation

### Expected result
Summary should be copied over to the implementation

### Actual result
Nothing shows up in the generated doc for the implemented class.

### Further technical details
After digging into the code, the issue is that when you iterate the "Implements" collection, the IDs used  are generated slightly differently than the ones compared against (when trying to find the interface's documentation data).

`VisitorHelper.GetCommentId(symbol)` generates IDs like **ClassName´1**
but 
for the implementation lookup, `SpecIdHelper.GetSpecId(symbol, typeGenericParameters, methodGenericParameters);` is used, which generates IDs which look like **ClassName{{T}}**

That's why `context.Members.TryGetValue` [right here](https://github.com/dotnet/docfx/blob/master/src/Microsoft.DocAsCode.Metadata.ManagedReference/Resolvers/CopyInheritedDocumentation.cs#L109) never returns anything.

Hope that makes sense

**Comment by kwaclaw** [comment]
It seems the same happens when deriving from a generic base class while binding the type parameter:
```
public abstract class Base<T>
{
    /// <summary>Does something.</summary>
    public abstract T DoSomething();
}

public class Derived: Base<int>
{
    /// <inheritdoc />
    public override int DoSomething() {
        return 0;
    }
}
```

**Comment by tobiasbunyan** [comment]
Interestingly, if your base class inherits an interface, the derived class will get the interface documentation.  This caused me a problem as the Interface had no documentation, meaning that it looked like inheritdoc simply wasn't working.

The example below results in Class2 having 'this is interface1' as its class summary, and no documentation at all for the overridden 'SomeMethod'.

```
namespace ClassLibrary1
{
    /// <summary>
    /// this is interface 1
    /// </summary>
    public interface Interface1
    {

    }

    /// <summary>
    /// this is Class1
    /// </summary>
    public class Class1<T> : Interface1
    {
        /// <summary>
        /// Class1.SomeMethod
        /// </summary>
        public virtual void SomeMethod()
        {

        }
    }

    /// <inheritdoc></inheritdoc>
    public class Class2 : Class1<int>
    {
        public override void SomeMethod()
        {
            base.SomeMethod();
        }
    }
}
```

**Comment by amirebrahimi** [comment]
Any feedback before I create a PR? Here's my proposed solution:
https://github.com/amirebrahimi/docfx/commit/1ae5ba19629a4f444419f86e663d99b4fdd2f3e9#diff-ee9366b2becf35903f8c7d23a3f8c471R141
