### ISSUE TITLE
Support specific build configurations for metadata

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#1518]
As far as I can tell, the `docfx metadata` command configuration doesn't specify which project configuration or target framework to extract metadata for. In Noda Time we have some members which are present in one build but not another, and I'd really like to make this clear in the documentation... is there any way to either tell docfx which project configuration / tfm to build, or at least specify C# preprocessor symbols to define?

**Comment by MichaCo** [comment]
Not sure if that's the same request @jskeet but I'd also love to see some indication in the docs of e.g. classes, for which target frameworks the code is available/visible..

At least IF you have multitarget projects, like NET40, NET45, netstandard14... and you ifdef parts of the code away, it would make sense to indicate that.

Advanced version could be something like the version switch at the top of the screen (MSDN docs).
The minimal solution could be an additional field near namespace and assembly? like:

    Namespace:MyNameSapce
    Assembly:Awesome.dll
    Target:.NET45, .netstandard1.3

**Comment by jskeet** [comment]
@MichaCo: Yes, that's basically what I was intending to achieve, but I'd expected to have to do that with my own tooling, based on the results of running docfx twice. If docfx could do it itself, that would be even better :)

(I have something similar for which version a member was introduced in - see http://nodatime.org/2.0.x/api/NodaTime.Duration.html for example, and look at the "Since" point in each member.)
