### ISSUE TITLE
Generate a restapi page with submenu to navigate different page, no scrolling

### ISSUE THREAD

**Issue by vverrastro** [dotnet/docfx#1527]
Hi all,
I'm trying to generate a personal template with mustache.
I'm using the start project "docfx-seed-master" to do some test.

I would like to get a page "Api Reference" like this (this is my page now):

![restapi](https://cloud.githubusercontent.com/assets/20859623/24745679/c8822134-1ab6-11e7-95bc-8052c737e4d4.jpg)

without "right affix" / "right menu", i read that it uses <h1-h2-h3....> tag from current document.
But have a submenu under every left item, like this: (with different page for heach tag h1-h2-h3)

![apidoc](https://cloud.githubusercontent.com/assets/20859623/24747485/c955044a-1abc-11e7-822d-8aa6db7343ec.jpg)

For example:

Left Menu 
Search....

PetStoreAPI
      - AddPet
      - UpdatePet
      - FindPetsByTags
      - DeletePet
      ........
ContactsAPI
      - Get Contacts
      - Get Contact By Id
      .........

For heach submenu (Addpet, UpdatePet etc ...)  a different page.
I studied so much the system for creating a custom template, but it's really difficult.
I hope that someone could help me please, I don't know how to solve alone.
Kind regards,
Vito

**Comment by hellosnow** [comment]
Hi @vverrastro , in current design ([sample page](http://docascode.github.io/docfx-seed/api/CatLibrary.Cat-2.html)), left navigation is to navigate to different pages, right navigation is to navigate to in-page h1-h3 tags. Do you mean to move h1-h3 tag navigation from right affix into left affix?

**Comment by vverrastro** [comment]
Hi @hellosnow, yes. But I need to create a different page for heach item menu (h1.h2.h3) instead of scrooling.

**Comment by hellosnow** [comment]
Is it expected to split member level pages to separate pages, so that each method is in one page? If yes, nuget package [memberpage](https://www.myget.org/feed/docfx/package/nuget/memberpage) may help you on this. @vicancy would know more details.

**Comment by vverrastro** [comment]
Hi @hellosnow, I tested the package that you have shown me.
It works good with api documentation, but in Restapi it not works, i don't know why.
Here the exemple: (Without memberpage - API Documentation)

![prima](https://cloud.githubusercontent.com/assets/20859623/24854003/188605c8-1ddd-11e7-9227-a82f4d0e52f7.jpg)

(With memberpage package - API Documentation)

![dopo](https://cloud.githubusercontent.com/assets/20859623/24854024/2db8dc04-1ddd-11e7-8d63-4ebfe6e3616c.jpg)


This is my Restapi page with no package memberpage effect

![restapi](https://cloud.githubusercontent.com/assets/20859623/24854100/73357ec2-1ddd-11e7-8da9-c887f5ae0342.jpg)

**Comment by hellosnow** [comment]
Yes Rest doesn't support split by operations now, one swagger file is generated as one html currently...

**Comment by vverrastro** [comment]
I understood. You were kind and helpful.
Thank you.

**Comment by hellosnow** [comment]
@vverrastro we will consider to add such option for REST to be more flexible, will let you know our schedule if it's decided.

**Comment by vverrastro** [comment]
Great! I will follow all the news about this.

**Comment by hellosnow** [comment]
@vverrastro we plan to split the rest api into operation groups by `Tag` rule first, take [this rest page ](http://docascode.github.io/docfx-seed/restapi/petstore.html#petstore_swagger_io_v2_Swagger_Petstore_1_0_0_tag_pet) as an example, the overall API will be grouped into `Pet`, `Store`,`Users` and `Other Apis`(not grouped), and we will modify these 4 tags into left navigation, the inner operations such as `addPet` and `updatePet` will be kept in right navigation. Is this scenario meet your requirement?

**Comment by vverrastro** [comment]
Hi @hellosnow, 
in your exemple I don't see any change change from the initial sample project.
My scenario is (like api documentation with memberspage package):

Left Navigation exemple:
(Without big one page with scroll)
- Petstore Api
        AddPet (single page) 
        DeletePet (single page)
        GetPet (single page)

Maybe I dont' understeand your plan :)

**Comment by hellosnow** [comment]
@vverrastro I didn't update the referred rest page, just to provide some information. If you read the right navigation of the [this rest page ](http://docascode.github.io/docfx-seed/restapi/petstore.html#petstore_swagger_io_v2_Swagger_Petstore_1_0_0_tag_pet), you'll find all operations are not in flat, but group by tags, refer to docfx document [Tags to organize the sections of apis](http://dotnet.github.io/docfx/tutorial/intro_rest_api_documentation.html#tags-to-organize-the-sections-of-apis).

For splitting the pages, we will move `tags` group in left toc, and keep each operation inside the tag group in right navigation in first step.

**Comment by hellosnow** [comment]
We deliver the split logic via #1827 and #1872 , and the documentation #1895 . Please have a try on it:

1. With `rest.tagpage` plugin enabled, operations with the same tag are grouped into one page.
2. With `rest.operationpage` plugin enabled, each operation is splitted into single page.
3. With both `rest.tagpage` and `rest.operationpage` plugins enabled, the *REST* model will be splitted to tag level first, then split to operation level.

Refer [Plugins dashboard](http://dotnet.github.io/docfx/templates-and-plugins/plugins-dashboard.html) for more details (It will be refreshed after docfx version upgraded)
