### ISSUE TITLE
Have It support "CodeContracts"?

### ISSUE THREAD

**Issue by yaochangyu** [dotnet/docfx#1529]
### Have It support "CodeContracts"
I via Sandcastle can generate "CodeContracts" of document
https://marketplace.visualstudio.com/items?itemName=RiSEResearchinSoftwareEngineering.CodeContractsforNET

How to via docfx can generate "CodeContracts" of document?

**Comment by hellosnow** [comment]
Reading [code contract spec](https://github.com/Microsoft/CodeContracts/blob/master/Documentation/User%20Documentation/userdoc.pdf), docfx can reflect related attributes but not support generating `CodeContracts` of document yet? @vwxyzh @vicancy

**Comment by yaochangyu** [comment]
Hi hellosnow,
I can not generate "CodeContracts" of document.
I don't know docfx have support "CodeContracts"?

**Comment by hellosnow** [comment]
Docfx doesn't support `CodeContracts` yet, I will play on Sandcastle to try generating `CodeContracts` first, then try to run docfx to check whether we have reflected related attribute like `ContractInvariantMethod`. Our attributes in yaml file is like [Attribute sample in Yaml](https://github.com/qinezh/op-docfx-seed/blob/master/api_ref/CatLibrary.Cat-2.yml#L81).

Have you tried to run your project by docfx? If possible, could you share with us the yaml files? 

One more, could you share with us the links about Sandcastle generated html files? We're interested on what information is needed in the final page.

**Comment by hellosnow** [comment]
I tried to generate code contracts:
- source code: https://github.com/hellosnow/ForCodeContract/tree/master/TestCodeContracts
- generated yaml files: https://github.com/hellosnow/ForCodeContract/tree/master/yaml
- generated html file snapshot: ![code contracts in docfx](https://github.com/hellosnow/ForCodeContract/raw/master/snapshot.png)



@yaochangyu from your blog post [使用 Sandcastle 自動產生 Code Contract 說明文件](https://dotblogs.com.tw/yc421206/2017/04/06/tfs_2017_build_vnext_generate_live_contract_document), we found a snapshot to describe how it looks like using Sandcastle: ![sandcastle with code contracts](https://az787680.vo.msecnd.net/user/余小章/77f024a6-0019-46f6-af7d-45d35e46d020/1491552571_9161.png)


From the above, we can come into conclusion that docfx haven't support generating section for `code contracts`, but already generated the attributes via [ContractInvariantMethodAttribute](https://github.com/hellosnow/ForCodeContract/blob/master/yaml/TestCodeContracts.Program.yml#L82).

If we need to support `code contracts`, need to update the template such as [class template](https://github.com/dotnet/docfx/blob/master/src/docfx.website.themes/default/partials/class.tmpl.partial#L167), much similar as exception section. @yaochangyu if you're interested in it, welcome contribute on that.

**Comment by yaochangyu** [comment]
Hi hellosnow：
That's it, You got it

**Comment by yaochangyu** [comment]
@hellosnow Hi hellosnow
[使用 Sandcastle 自動產生 Code Contract 說明文件](https://dotblogs.com.tw/yc421206/2017/04/06/tfs_2017_build_vnext_generate_live_contract_document)，That's my blog.

**Comment by hellosnow** [comment]
@yaochangyu yes i found it from your blog.

**Comment by yufeih** [comment]
> Code contracts aren't supported in .NET 5+ (including .NET Core versions). Consider using [Nullable reference types](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references) instead.
