### ISSUE TITLE
Invalid View Source link generated for namespaces

### ISSUE THREAD

**Issue by wieslawsoltes** [dotnet/docfx#153]
When building static site using default template the View Source link generated for namespaces is invalid:

Example output:
http://xamlbehaviors.github.io/api/Perspex.Xaml.Interactions.Core.html

Link:
https://github.com/XamlBehaviors/XamlBehaviors/blob/master/src/Perspex.Xaml.Interactions/Core/TypeConverterHelper.cs/#L7

docfx project:
https://github.com/XamlBehaviors/XamlBehaviors/tree/master/Documentation

**Comment by vicancy** [comment]
Hi, this link https://github.com/XamlBehaviors/XamlBehaviors/blob/master/src/Perspex.Xaml.Interactions/Core/TypeConverterHelper.cs#L7 does contain the definition for the namespace: `namespace Perspex.Xaml.Interactions.Core`.

**Comment by wieslawsoltes** [comment]
I was surprised that after clicking on `View Source` button to get redirected to some arbitrary class from that namespace.

More intuitive would be to get redirected to the folder that contains all class definition for this namespace if project is following the convention to place classes in folders according to namespace naming, like `Perspex.Xaml.Interactions.Core` is for the `Perspex.Xaml.Interactions` assembly and `Core` is target folder for class definitions so the resulting `View Source` would lead to this link: https://github.com/XamlBehaviors/XamlBehaviors/blob/master/src/Perspex.Xaml.Interactions/Core/.

**Comment by vicancy** [comment]
Hi @wieslawsoltes, agree that `View Source` for namespace looks strange. However we cannot guarantee that people use the convention you mentioned. So I will remove `View Source` for namespace by default. And the way to customize the `View Source` URL for a particular namespace would be to provide the accurate path in an override document.

**Comment by wieslawsoltes** [comment]
Hi @vicancy , I agree with the solution you have proposed. Out of curiosity, would be possible to add option to enable `View Source` to be based on convention I have described?

**Comment by vicancy** [comment]
Hi @wieslawsoltes, considering that .NET code does not necessarily follow the convention you described and it is pretty hard for `docfx` to tell, we currently have no plan to add this option.

**Comment by wieslawsoltes** [comment]
Hi @vicancy, I think we can close this issue. The disabled by default `View Source` will suffice.
