### ISSUE TITLE
View Source Link not working as configured

### ISSUE THREAD

**Issue by theiwaz** [dotnet/docfx#1544]
### Title
When I configure the GIT repo stuff in the DocFx.Json it still generates incorrect links

### Functional impact
We're not able to do 'view source' while browsing our DocFx site

### Minimal repro steps
1. Configure your VSTS Git repo to access it via SSH  
2. Add following config to your DocFx.json

<pre>
    "globalMetadata": {
      "_appTitle": "PlekChecker API website",
      "_appFooter": "PlekChecker API website",
     <b> "_gitContribute": {
        "repo": "https://eti-git.visualstudio.com/_git/WC",
        "branch": "develop",
        "path": ""
      },</b>
      "_gitUrlPattern": <b>"vso"</b>,
      "newFileRepository": {
        "branch": "develop"
      }
</pre>
3. Now do a `> DocFx Build`

### Expected result
The `view source` links are constructed using the supplied`https://eti-git.visualstudio.com/_git/WC` as configured in:

```
"_gitContribute": {
        "repo": "https://eti-git.visualstudio.com/_git/WC",
```

### Actual result
The `view source` links seem to be divined from the actual configuration in my `.git`. 

### Further technical details
Removing:

```
      "_gitUrlPattern": "vso",
      "newFileRepository": {
        "branch": "develop"
      }
```

From the DocFx.json results in the `view source` link not appearing anywhere.

**Comment by superyyrrzz** [comment]
Can you try `git remote -v` in your repo and provide the output? I suspect that the regex in DocFX's code doesn't consider VSO's SSH case.

**Comment by theiwaz** [comment]
I did and it returned the following:

```
origin  ssh://eti-git@eti-git.visualstudio.com:22/_git/WC (fetch)
origin  ssh://eti-git@eti-git.visualstudio.com:22/_git/WC (push)
```

**Comment by qinezh** [comment]
I think the port `:22` breaks the regex [here](https://github.com/dotnet/docfx/blob/master/src/docfx.website.themes/common/common.js#L86), @theiwaz  Could you help to explain why there need a port number?

**Comment by superyyrrzz** [comment]
DocFX supports source code and document in different repos. `_gitContribute` now affects only the "Edit Button", as we still can't find a scenario where the source's repo need to be overwritten.
In your case, it can work without extra config after the fix is applied.

**Comment by theiwaz** [comment]
I see there have been some mods in the dev branch that should solve my problem.

**Comment by Sunzhuokai** [comment]
View Source Link can config the url scheme ?  default is `https` ,but our gitlab host use `http`

**Comment by tig** [comment]
> @Sunzhuokai "View Source" value is always fetched by running 'git config --get remote.origin.url'

This breaks our workflow where `remote` is a developer's personal fork and `origin` is the original.

In addition, we use SSH and not HTTPS, so even if docfx usedc `git config --get origin` View Source would not work.

I tried finding an Issue for this; should I create a new one?
