### ISSUE TITLE
Connection refused by server on Mono/Ubuntu.

### ISSUE THREAD

**Issue by kaby76** [dotnet/docfx#1554]
### Title
docfx is unreachable in Ubuntu 16.x due to the call to self-hosting OWIN "WebApp.Start("localhost",...). I would recommend using "*:port" instead of "localhost:port" for the URL in the method call. (I have written a self-hosting NancyFX server, and it doesn't have the same problem.)

### Functional impact
I can execute "wget localhost:8080" from sh, but "wget actual-ip-addr:8080" on the server machine outputs a "connection refused". I also cannot talk to the server from another machine.

### Steps to reproduce
1) Create a vanilla Ubuntu 16.04.2 desktop in Virtualbox. Or you can use DigitalOcean and create a droplet with the same version.

2) Install Mono on the new box:
a)  sudo apt-get update
b)  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
c)  echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
d)  sudo apt-get install mono-complete

3) Install current version of docfx.exe (Version 2.15.5)
a) sudo apt-get install zip unzip
b) cd
c) wget https://github.com/dotnet/docfx/releases/download/v2.15.5/docfx.zip
d) mkdir docfx; cd !$; mv ~/docfx.zip .; unzip docfx.zip

4) Get a complete BUILT source project. You can use my example, so you do not need VS C++ Build Tools:
a) cd; git clone https://github.com/kaby76/swigged-llvm-docfx.git

5) Run:
a) cd ~/docfx;
b) sudo mono docfx.exe serve -p 9000  ~/swigged-llvm-docfx/_site/

6) In a new terminal shell, try:
a) wget localhost:9000
-----> This works fine.
b) wget what-ever-the-ip-addr-si:9000     (substituting the IP of the machine into the command)
-----> Connecting to 192.168.1.11:9000... failed: Connection refused.

Connecting from another box gives the same problem. No firewalls enabled.

### Further technical details
I read somewhere that for OWIN one should use "*" for the URL instead of "localhost". In a local build, I changed the two occurrences in the source of docfx of "localhost" to "*" on the current version of the master branch, rebuilt, and all works fine as expected. I double checked that the problem exists in the current version of master before making the change. There may be way to twiddle with the settings in Ubuntu, but I don't know what they may be. If there is a way, it should be well documented in the tutorials.

I've verified the problem on a VPS droplet in DigitalOcean. After I've copied my updated docfx executables to the VPS, and all works perfect.

**Comment by qinezh** [comment]
Hi @kaby76 , `docfx serve` is only a simple tool to preview the static website in local, not for production...You can try other tool to host the website once the preview result meets your requirement. :)

**Comment by vicancy** [comment]
Thanks @kaby76 for the info and investigation. you also provides a very detailed instruction on installing docfx under Ubuntu... We will add it to our documentation..

**Comment by vicancy** [comment]
@kaby76 Could you send a PR with your `In a local build, I changed the two occurrences in the source of docfx of "localhost" to "" `?
