### ISSUE TITLE
VscPreviewExtension does not allow scrolling down long documents

### ISSUE THREAD

**Issue by JimDaly** [dotnet/docfx#1555]
### Title
VscPreviewExtension does not allow scrolling down long documents.

### Functional impact
This isn't usable if scrolling doesn't work

### Minimal repro steps
1. Install and enable the extension from the marketplace [DfmPreview](https://marketplace.visualstudio.com/items?itemName=928pjy.DfmPreview) using the instructions there.
2. View the preview of a long document where all the contents are not visible.
3. Attempt to scroll down in the preview

### Expected result
I can scroll down to view contents not visible at the top.

### Actual result
I can **not** scroll down to view contents not visible at the top.

### Further technical details
There are other issues with this extension which are outside the scope of this issue, such as the fact that the Toggle functionality throws an error, but I could work around those if this scrolling issue was fixed.

**Comment by hellosnow** [comment]
@928PJY is refactoring the code via #1547. @928PJY could you try on our updates to test whether we can repro this issue?

**Comment by 928PJY** [comment]
@JimDaly Thanks for trying our extension, we have fixed this bug, please move to [DocfxPreview](https://marketplace.visualstudio.com/items?itemName=docfxsvc.DocFXPreview), [DfmPreview](https://marketplace.visualstudio.com/items?itemName=928pjy.DfmPreview) is no longer being maintained

**Comment by JimDaly** [comment]
Seems to be working now. There was some time after installing where the preview showed nothing. But as I went to double-check my repro steps, it started working.
Thank you!
