### ISSUE TITLE
add support for footnotes

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#1564]
Github flavored markdown (GFM) does not support footnotes. I think docfx flavored markdown (DFM) should support them even if this means that there is yet another difference between GFM and DFM. 
We use docfx heavily for conceptual documents where footnotes often are very handy. 

A typical use of footnotes is inside tables:

```
|Type|.NET 1.1|.NET 4.5|.NET 4.6.1|.NET 4.7|
|-----|---------|---------|-----------|---------|
|System.ValueTuple|-|✓[^1]|✓[^1]|✓|

[^1]: available via a [nuget package](https://www.nuget.org/packages/System.ValueTuple/)
```
Which should render like this:

|Type|.NET 1.1|.NET 4.5|.NET 4.6.1|.NET 4.7|
|-----|---------|---------|-----------|---------|
|System.ValueTuple|-|✓<sup>[1]()</sup>|✓<sup>[1]()</sup>|✓|

<sup>[1]()</sup>available via a [nuget package](https://www.nuget.org/packages/System.ValueTuple/)

**Comment by superyyrrzz** [comment]
Keep track in #3387 for Markdig footnotes extension support
