### ISSUE TITLE
Search does not work in windows 10 creator's update on Edge browser

### ISSUE THREAD

**Issue by lidermanrony** [dotnet/docfx#1581]
### Title
Search does not work in windows 10 creator's update on Edge browser

### Functional impact
Search does not work

### Minimal repro steps
1. install windows 10 creators update (specifically I'm using windows 10 enterprise version 1703 15063.138)
2. Edge version 40.15063.0.0 
3. EdgeHTML version 15.15063
4. browse to
[https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html)
5. Try to search

### Expected result
Search is working
### Actual result
Search isn't working

**Comment by CarsonTolleshaug** [comment]
I just encountered this as well. I was going to create an issue for it, but it seems you beat me to the punch. Hopefully this is fixed soon, a majority of our documentation users use Edge.

**Comment by CarsonTolleshaug** [comment]
A colleague of mine discovered a workaround for this issue. By including the following in a web.config file the problem is resolved:

```
<configuration>
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension=".json" mimeType="application/html" />
     </staticContent>
    </system.webServer>
</configuration>
```

Hope this helps some others out there.

**Comment by lidermanrony** [comment]
@CarsonTolleshaug tried it thanks! unfortunately this workaround doesn't work for me (for some users it does, for some it doesn't).

**Comment by vicancy** [comment]
Latest finding: on Edge the web worker crashes. A similar issue is found here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9243268/, will check to see if it can be work around
