### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by ploeh** [dotnet/docfx#159]
The [Getting Started with docfx](http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html) page states:

> currently support C# and VB

Why not F#? Is it planned?

Why does the language even matter? Couldn't it work with any Visual-Studio-generated documentation XML file, regardless of origin language?

**Comment by simonmurdock** [comment]
The tool uses Roslyn & reflection for most of the work as far as I know. I do not _think_ it uses the `XML` file at all.

**Comment by chenkennt** [comment]
DocFX uses Roslyn to get language metadata, like method syntax, which only supports C# and VB for now. F# is in our list, but it's not our top priority right now..

**Comment by surban** [comment]
#2392
