### ISSUE TITLE
VS2017 Win 10 Doesn't Build Documentation  2.16.7

### ISSUE THREAD

**Issue by mboutros1** [dotnet/docfx#1615]
### Title
*VS2017 Win 10 Doesn't Build Documentation* 
Trying to build documentation with vs 2017 project on win 10 with version 2.16.7.

### Functional impact
Doesn't build documentation 

### Minimal repro steps
Try to run the unit tests or build the docfx seed project after saving it in vs 2017

### Expected result
Build the documentation.

### Actual result
*What is actually happening?*  
it log "no metadata is generated"
when i debug the unit tests the OpenProjectAsync doesn't return any documents or members.

**Comment by superyyrrzz** [comment]
Does the solution builds successfully in VS2017?

**Comment by mboutros1** [comment]
It build the main projects, however the unit tests are failing.

**Comment by superyyrrzz** [comment]
Can you try also installing VS2015? I've done some investigation before, seems VS2015 is required to generate doc for an VS2015 solution, even VS2017 already exists. I know it's not a clean solution, but it should work as far as I know.

**Comment by mboutros1** [comment]
Thank you superyyrrzz  after installing VS2015 it worked as expected.

**Comment by superyyrrzz** [comment]
minimal requirement should be [build tool 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159). See https://github.com/dotnet/docfx/issues/1628#issuecomment-299105738
