### ISSUE TITLE
No metadata is generated for simple project

### ISSUE THREAD

**Issue by dermeister0** [dotnet/docfx#1628]
### Title
No metadata is generated for simple project

### Functional impact
Metadata is not generated, API documentation is empty.

### Minimal repro steps
1. Clone https://github.com/dermeister0/InheritdocTest repository.
2. Open repository root directory.
3. Execute `docfx metadata docfx_project\docfx.json -f` command.

```
PS C:\Work\InheritdocTest> docfx metadata docfx_project\docfx.json -f
[17-05-04 04:27:49.263]Warning:No metadata is generated for InheritdocTest,Domain.
[17-05-04 04:27:49.265]Info:Completed executing in 1220.2209 milliseconds.


Build succeeded with warning.
[17-05-04 04:27:49.274]Warning:No metadata is generated for InheritdocTest,Domain.
        1 Warning(s)
        0 Error(s)
```

Simpler steps:
1. Clone https://github.com/dermeister0/InheritdocTest repository.
2. Open \src\Domain directory.
3. Execute `docfx metadata Domain.csproj -f` command.

```
PS C:\Work\InheritdocTest\src\Domain> docfx metadata Domain.csproj -f
[17-05-04 04:29:49.774]Warning:No metadata is generated for Domain.
[17-05-04 04:29:49.776]Info:Completed executing in 1477.5072 milliseconds.


Build succeeded with warning.
[17-05-04 04:29:49.783]Warning:No metadata is generated for Domain.
        1 Warning(s)
        0 Error(s)
```

### Expected result
Metadata is generated.

### Actual result
'No metadata is generated' warning is displayed.

### Further technical details
The project is .NET 4.5.2 class library. It contains 2 source files: ILogger.cs and Properties/AssemblyInfo.cs.

It's strange, but `project.Documents` collection is empty after `var project = await GetProjectAsync(path);` call in SaveAllMembersFromCacheAsync method. Looks like Roslyn can't find source files.

**Comment by vicancy** [comment]
I cloned the repo and `InheritdocTest>docfx metadata docfx_project\docfx.json` succeeds without error... Have you installed 'vs 2017 with dotnet core toolset'?

**Comment by vwxyzh** [comment]
@vicancy one machine can repo this bug.

**Comment by vwxyzh** [comment]
@dermeister0 @vicancy after installing [build tool 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159), that machine can build now.

**Comment by ThadHouse** [comment]
I'm getting this same error even with both VS 2015 and the 2015 Build Tools explicitly installed. Happens with both the test project in this issue originally and my own project.  Is there any way to double check and make sure it can access the right files needed to make docfx work.

**Comment by roji** [comment]
Just ran into this, installing 2015 build tools solved it for me. Note that the docfx site still does not list this as a prerequisite (https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html).

It really seems strange for the 2015 build tools to still be a prerequisite, I hope you guys remove it soon.
