### ISSUE TITLE
Metadata being left behind

### ISSUE THREAD

**Issue by wekempf** [dotnet/docfx#164]
I'm a little confused by the metadata Yaml files generated into the api folder. First, this is generated code, for the most part, so I thought I could add this folder to .gitignore and/or delete it safely. However, at least index.md seems like it's necessary to keep in source control. Is there anything else in this directory that's not generated?

The real issue here, though, is that if you remove a class from the project, for instance, and regenerate the metadata the old YML file for that class isn't removed. That won't be as big of an issue if I can figure out what I can exclude from source control here, but it still seems like a bad thing.

BTW, what would a good .gitignore list be for docfx?

**Comment by vicancy** [comment]
I agree, it is confusing to mix the generated `*.yml` files with `index.md` hand-written files.
As a temp workaround, I added default `.gitignore` files when `docfx init`.
As a long term solution, we will put the generated `*.yml` files into `obj` folder later so that it would be much clearer that these files are generated.

**Comment by wekempf** [comment]
That's great, but this doesn't address the issue with generated metadata being left behind, at least not directly. With the .gitignore information it's possible to manually "clean" the metadata before generating it, which works but isn't a very friendly way of managing this. It would be much better for metadata generation to remove any no longer valid metadata files.

**Comment by vicancy** [comment]
Thanks @wekempf  for the suggestion. Cleaning up the old generated metadata files are also in our plan, forgot to mention that.

**Comment by vicancy** [comment]
https://github.com/dotnet/docfx/pull/1777
