### ISSUE TITLE
Hard-to-diagnose "No metadata is generated" error when code has no namespace

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#165]
### Title

Hard-to-diagnose "No metadata is generated" error when code has no namespace

### Functional impact

Friction when trying to reproduce a trivial issue, or when getting started from scratch for tiny simple demo purposes.

### Minimal repro steps

Step 1. Create a `project.json` file of:

```json
{
  "version": "1.0.0",
  "frameworks": {
      "net451": { }
  }
}
```

Step 2. Create a `DocfxTest.cs` file of:

```csharp
/// <summary>Just a demo</summary>
public class DocfxTest
{
}
```

Step 3. Ensure it builds:

```text
dnu restore
dnu build
```

Step 4. Create a `docfx.json` file of:

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [ "project.json" ],
          "cwd": "."
        }
      ],
      "dest": "obj/api"
    }
  ],
  "build": {
    "content": [
      {
        "files": [ "**/*.yml" ],
        "cwd": "obj/api",
        "dest": "api"
      }],
    "dest": "_site"
  }
}
```

Step 5. Try to generate the metadata:

```text
docfx metadata
```

### Expected result

Metadata should be generated, *or* if this restriction is deliberate, it should give a more detailed warning.

### Actual result

Result from step 5:

```text
Info: Config file docfx.json found, start generating metadata...
Warning: No metadata is generated for docfxbug2.


Build succeeded with warning.
Warning: No metadata is generated for docfxbug2.


There are totally 1 Warning(s), 0 Error(s)
```

### Further technical details

On the off-chance, I added a namespace to the code in step 2. Regenerate the metadata (with `-f`) and bingo - it all works. 

I can now submit the bug I was actually trying to reproduce to start with...

**Comment by jskeet** [comment]
Great - thanks for the swift resolution :)

**Comment by matkoch** [comment]
First part of this problem is still actual.
