### ISSUE TITLE
<term> and <description> of <list> are concatenated without space inbetween

### ISSUE THREAD

**Issue by glenthomas** [dotnet/docfx#1651]
### Title
`<term>` and `<description>` of `<list>` are concatenated without space inbetween

### Functional impact
The resulting doc content is not as readable as could be. Words joined together

### Minimal repro steps
Simple example:
```
/// <summary>
/// Pricing models are used to calculate theoretical option values
/// <list type="bullet">
/// <item><term>1</term><description>Black Scholes</description></item>
/// <item><term>2</term><description>Black76</description></item>
/// <item><term>3</term><description>Black76Fut</description></item>
/// <item><term>4</term><description>Equity Tree</description></item>
/// <item><term>5</term><description>Variance Swap</description></item>
/// <item><term>6</term><description>Dividend Forecast</description></item>
/// </list>
/// </summary>
```

### Expected result
There should at least be some space between the two values in the generated content

### Actual result
The values of term and description tags are joined together without spacing inbetween
e.g.
- 1Black Scholes
- 2Black76
- 3Black76Fut
- 4Equity Tree
- 5Variance Swap
- 6Dividend Forecast

### Further technical details
N/A

**Comment by kemeril** [comment]
Also delemetier shall be added between the rendered term and description like Visual Studio does:
The expected result regarding the example:

- **1** - Black Scholes
- **2** - Black76
- **3** - Black76Fut
- **4** - Equity Tree
- **5** - Variance Swap
- **6** - Dividend Forecast
