### ISSUE TITLE
Using hashtag in cross reference broken with xref downloaded from URL

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#1655]
### Title
Using an anchor in a cross reference link, as described [here](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-hashtag-in-cross-reference) seems to be broken.

### Functional impact
It's not possible to link to an anchor in a cross reference link.

### Minimal repro steps
1. Add the following link: `[Some Text](xref:my-uid-from-another-xrefmap#some-anchor)`

### Expected result
The link should go to the file associated with the UID `my-uid-from-another-xrefmap` and add the anchor `some-anchor` to the file.

### Actual result
Only the file associated with the UID `my-uid-from-another-xrefmap` is opened.

### Further technical details
DocFx version 2.17.0.572

**Comment by vicancy** [comment]
I can't repro the issue. I created 2 md files as follows:
a.md:
```markdown
---
uid: a
---
# title
blaaa
```

b.md:
```markdown
Cross [ReferenceA](xref:a#title)
```
Running `docfx build --content *.md` succeeds with correct bookmark.

 Is there any warning such as *Illegal link: .... - invalid bookmark* in your case? Can you provide your minimum repro step?

**Comment by pascalberger** [comment]
@vicancy Is seems to be related to loading the `xrefmap.yml` from an URL.

So having `a.md`:
```
[Foo](xref:some-uid#some-anchor)
```

And `docfx.json`
```
"xref": [
  "linked-xrefmap.yml"
]
```

The above works, but as soon as I change the `docfx.json` to the following it misses the anchor in the link:
```
"xref": [
  "https://myserver/linked-xrefmap.yml"
]
```
