### ISSUE TITLE
Markdown extension: tabbed content

### ISSUE THREAD

**Issue by vwxyzh** [dotnet/docfx#1659]
Allow user to create a tabbed content.

* [x] design
* [x] markdown extension
* [x] default template supporting
* [x] documentation

Markdown Syntax:
```md
# [Tab Name](#tab/tab-id-1)
Content1 ...
# [Tab Name](#tab/tab-id-2)
Content2 ...
---
```

**Comment by vwxyzh** [comment]
`default template supporting` will delay to 2.19.

**Comment by pascalberger** [comment]
Do you plan to implement this like other stuff with client side / javascript code or server side? IMHO it would be nice to have this processed as far as possible by DocFx and with as less as possible with client side code (which is the reason for a static site generator at all 😄). Would also provide better theming support.

See also #958

**Comment by vwxyzh** [comment]
@pascalberger for current design, DocFX + template generate HTML, CSS and JavaScript code. Browser requirement: Enable JavaScript.

**Comment by vwxyzh** [comment]
### Markdown Syntax
* Tab group or tab item must start with a heading (`# ...`, `## ...`, ... `###### ...`).
* Heading content must be a link `[tab name](#tab/tab-id/tab-condition)`.
* Link target must start with `#tab/`
* Tab-id is required, it is a part of unique key, `a-z`, `0-9` and `-` only.
* Tab-condition is optional, it is a part of unique key, `a-z`, `0-9` and `-` only.
* Tab group stop by a horizontal ruler `---`
* Tab item stop by another tab item or tab group ending.
* Tab group cannot be nested.

### Sample Markdown
```md
# [Tab1](#tab/id1/condition1)
Foo
# [Tab1](#tab/id2)
Bar
---
```

### Sample Output Html
```html
<div class="tabGroup" id="tabgroup_{generated-group-id}">
    <ul role="tablist">
        <li role="presentation">
            <a href="#tabpanel_{generated-group-id}_id1_condition1" tabindex="0" role="tab" aria-controls="tabpanel_{generated-group-id}_id1_condition1" data-tab="id1" data-condition="condition1" aria-selected="true">Tab1</a>
        </li>
        <li role="presentation">
            <a href="#tabpanel_{generated-group-id}_id2" tabindex="-1" role="tab" aria-controls="tabpanel_{generated-group-id}_id2" data-tab="id2">Tab2</a>
        </li>
    </ul>
    <section id="#tabpanel_{generated-group-id}_id1_condition1" role="tabpanel" data-tab="Tab1"  data-condition="condition1">
        <p>Foo</p>
    </section>
    <section id="tabpanel_{generated-group-id}_id2" role="tabpanel" data-tab="id2" aria-hidden="true" hidden>
        <p>Bar</p>
    </section>
</div>
```

**Comment by vicancy** [comment]
Pending: styles for default template to support it

**Comment by brianlagunas** [comment]
Any update on when the Tab support is coming?

**Comment by vicancy** [comment]
@brianlagunas  I am working on the template support. Hopefully will be available on the next release
![image](https://user-images.githubusercontent.com/668244/31651162-24be1780-b34d-11e7-9da4-d337e2688b4b.png)

**Comment by vicancy** [comment]
@vwxyzh The remaing work is providing documentation and samples 😄

**Comment by vwxyzh** [comment]
Document updated 😄

**Comment by brianlagunas** [comment]
Whoot whoot!  Party time!
