### ISSUE TITLE
Markdown with XML comments "sort of works"

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#166]
### Title
Markdown with XML comments "sort of works"

### Functional impact

Can't really use Markdown in XML comments, but the impression is given that you can. Maybe. Ish.
That means I don't know whether or not to change my codegen which is currently copying Markdown comments verbatim into XML comments (which I never expected to work, particularly) or leave it as-is with the expectation that it will be fine eventually.

### Minimal repro steps

Step 1. Create a `project.json` file of:

```json
{
  "version": "1.0.0",
  "frameworks": {
      "net451": { }
  }
}
```

Step 2. Create a `DocfxTest.cs` file of:

```csharp
namespace Bug
{
    /// <summary>
    /// This is just a demo for docfx bugs.
    /// 
    /// Code in backticks:
    /// 
    /// ```csharp
    /// if (foo > 10)
    /// {
    ///    Console.WriteLine("In backticks");
    /// }
    /// ```
    /// 
    /// Code not in backticks, but indented:
    /// 
    ///     if (foo > 10)
    ///     {
    ///         Console.WriteLine("Just indented");
    ///     }
    /// 
    /// End of doc.
    /// </summary>
    public class DocfxTest
    {
    }
}
```

Step 3. Create a `docfx.json` file of:

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [ "project.json" ],
          "cwd": "."
        }
      ],
      "dest": "obj/api"
    }
  ],
  "build": {
    "content": [
      {
        "files": [ "**/*.yml" ],
        "cwd": "obj/api",
        "dest": "api"
      }],
    "dest": "_site"
  }
}
```

Step 4. Build the metadata, the site, and then serve:

```text
docfx metadata
docfx build
docfx serve _site -p 12345
```

Step 5. Browse to the relevant page, e.g. http://localhost:12345/api/Bug.DocfxTest.html

### Expected result

Either no Markdown support, or full Markdown support with indentation.

### Actual result

The first snippet (in backticks) is formatted as code, but without indentation.

The second snippet (just indented) is not formatted as code at all. See [screenshot](https://cloud.githubusercontent.com/assets/17011/13142364/69316c16-d634-11e5-9923-b90e05c110d7.png).

**Comment by vicancy** [comment]
Thanks for reporting the issue. Will fix
