### ISSUE TITLE
overwrite of Example comments not working. (throws exception on build)

### ISSUE THREAD

**Issue by roel4ez** [dotnet/docfx#1685]
### Overwrite of Example is not working.

It is not possible to overwrite the `example` comments of a class. I've attached a small example project which reproduces the problem. I am using the latest version available via chocolatey (`2.17.6` at the time of writing)

### Minimal repro steps
1. Create a class with an `<example>` comment tag
2. Run `docfx build` and view the generated documentation. The `Examples` section will be shown correctly.
3. Add an overwrite file for the class type, specifying `example: *content`. 
4. Run `docfx build` again
5.  Error: `Error:Unable to deserialize YAML header from "apidoc/Foo.Bar.md" Line 7 to TYPE ItemViewModel: (Line: 6, Col: 10, Idx: 97) - (Line: 6, Col: 20, Idx: 107): Exception duri
ng deserialization`

### Expected result
The `Examples` section should be correctly overwritten with the content from the overwrite file.

### Actual result
Error during `build`.  
When using `examples: *content`, no build error is thrown, but the result is not correct (still showing examples from code comments).  

[docfx_project.zip](https://github.com/dotnet/docfx/files/1022142/docfx_project.zip)

**Comment by vicancy** [comment]
examples is a List<string> https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.DataContracts.ManagedReference/ItemViewModel.cs#L261

Try using
```
example:
   - markdown content
```

`*content` is not currently supported in list, you have to put the markdown content in YAML header

**Comment by vwxyzh** [comment]
#375

**Comment by roel4ez** [comment]
@vicancy Off course, it's a list! That explains everything.
Thanks a lot for your reply, it works very nicely, and supports my scenario exactly.
