### ISSUE TITLE
Are crefs to external types supported?

### ISSUE THREAD

**Issue by MichaCo** [dotnet/docfx#169]
Hi,
This is a question regarding cref attributes within /// comments

I have something like...

    /// <see cref="System.Runtime.Caching.MemoryCache"/>

...in my comments in code, `docfx metadata` will give me warnings that there is an invalid cref value and it will be ignored.

The output html then contains invalid markup, e.g.:

    <see cref="!:System.Runtime.Caching.MemoryCache"></see>

1. Why is this getting ignored? 
I did include the `msdn.4.5.2` nuget and referenced it correctly (it is working for resolving clr return types for example). So, I was expecting the same would help to resolve those references, too?

2. Why the invalid markup?
Wouldn't it be better to convert the cref to a string as a fallback? So that the code comment doesn't get invalid? Because having the invalid markup, the comment doesn't make any sense anymore because it doesn't display the cref value of course.

:edit:
I figured that mscorlib types are actually showing up in the comments, `<see cref="System.String"/>` for example works just fine and gets generated as a link to the msdn docs.

Do I have to do something apart from adding 

    "externalReference": [
      {
        "files": "msdn.4.5.2/content/*.rpk"
      }
    ],

to get all rpks loaded? (Because there is clearly one for System.Runtime.Caching)

**Comment by chenkennt** [comment]
Hi @MichaCo , to make an external be recognized, you need to reference this type first (in this case, add reference to System.Runtime.Caching), just like how you use a type in code.

**Comment by MichaCo** [comment]
@chenkennt well, of course I **am** using that type ;)

But I figured it out. 
Problem was, that I have only xproj/project.json based projects and I first tried to build my doc with the downloadable docfx.exe. That didn't work, it says it doesn't support those file formats...
Therefore I just included all `**.cs` files, which worked actually pretty good, just that all externals were broken...

Now, I fixed my [docfx.json](https://github.com/MichaCo/CacheManager/blob/master/Documentation/docfx.json) to include only the `project.json` files under `../src`, instead of the `.cs` files - and it finally works :>

Overall we can close this issue, but the point is, the documentation seems to be missing for xproj/project.json based solutions! (I know, it will change again with the dotnet/cli stuff, anyways...)

You have to download the **docfx** NuGet, **not the msbuild** one nor the release zip, and then run the tools from there...

I'm also using a custom [build.cmd](https://github.com/MichaCo/CacheManager/blob/master/Documentation/build.cmd) to run the build in case someone is interested of (one way) how to set things up. 

Works great now!

**Comment by chenkennt** [comment]
Yes, you need to include .csproj or project.json as the reference information is the project file. Actually we have the [documentation](http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#4-use-docfx-under-dnx) about using DocFX in DNX. But we should mention project.json is only supported in DNX version. Will update documentation later.

**Comment by MichaCo** [comment]
Ok seems I totally missed that part of the docs ;) But still, the part that the two versions of docfx behave differently can be slightly confusing. Was totally my fault though, thanks again

**Comment by chenkennt** [comment]
There is some limitation in DNX so we can only support project.json in DNX version. I've updated the documentation in #171
