### ISSUE TITLE
Search Doesn't Work on Azure Websites

### ISSUE THREAD

**Issue by Hydrosis** [dotnet/docfx#1697]
### Search won't work on Azure Websites
I've compiled the seed project locally and ran it using `docfx --serve` and was able to successfully use the search function there. I took the contents of the `_site` folder and uploaded to Azure Websites and the search function doesn't return anything.

### Functional impact
I'm unable to use the search function throughout the entire site.

### Minimal repro steps
1. Build the seed project with `docfx build`
2. Upload the contents of the `_site` folder to Azure Websites via FTP.
3. Attempt to search the website for any word or phrase. Let's use `docfx` as an example.

Live demo: [http://docfxseed.azurewebsites.net](http://docfxseed.azurewebsites.net)

### Expected result
I expected a page of results for the phrase `docfx` to show up.

### Actual result
The search only displays the following message:
> Search Results for "docfx"

### Further technical details
The Azure Website I'm uploading the contents to doesn't have any extra configurations. I simply created a Web App, downloaded the FTP information, and uploaded the contents of the `_site` folder.

**Comment by vwxyzh** [comment]
Cannot download <https://docfxseed.azurewebsites.net/index.json>, you need add web.config, see [How to serve static .json files from a Windows Azure Website](https://blogs.msdn.microsoft.com/africaapps/2013/06/07/how-to-serve-static-json-files-from-a-windows-azure-website/)

**Comment by Hydrosis** [comment]
Thanks, that solved my problem 😄
