### ISSUE TITLE
Cannot reference a markdown article from doc comments

### ISSUE THREAD

**Issue by amsk1982** [dotnet/docfx#1698]
### Cannot reference a markdown article from doc comments

I'd like to reference a conceptual article written in markdown from doc comments. Is this possible.

### Minimal repro steps

**Class**

```c#
public class Example
{
        /// <summary>
        /// A property
        /// </summary>
        /// <seealso cref="@my_article_uid" />
        public string PropetyName { get; set; }
}
```

**Document**

```markdown
---
uid: my_article_uid
---

# My Article
```

### Expected result

The output documentation should include a link tot the article

### Actual result

A warning is printed and the link isn't included in the generated documentation

```
[17-05-25 04:12:07.168]Warning:Invalid cref value "!:my_article_uid" found in triple-slash-comments for Example defined in '<path>' Line 22, ignored
```

**Comment by vwxyzh** [comment]
try
```xml
<seealso href="xref:my_article_uid" />
```

**Comment by amsk1982** [comment]
Yep that works
