### ISSUE TITLE
Crefs to framework types not working

### ISSUE THREAD

**Issue by jdh28** [dotnet/docfx#1706]
I'm trying to generate API docs for a .NET framework project. I've referenced msdn.4.5.2.zip and if a type derives from object, then object is correctly hyperlinked to msdn.

However, any external type in a triple slash comment causes a warning:

    Warning:Invalid cref value "!:IDisposable" found in triple-slash-comments for Runner defined in ../../../src/XJRunnerIntegration/Runner.cs Line 55, ignored.

Looking at the output further, however, no base types other than object are being recognised. For example, I have a class that derives from EventArgs, but EventArgs is not hyperlinked and the inheritance hierarchy is just displayed as object.

**Comment by vicancy** [comment]
Could you paste your xml comment in `src/XJRunnerIntegration/Runner.cs` here, looks like the comment has syntax error and is not resolved correctly

**Comment by jdh28** [comment]
The full xml docs for that method are below. The ms-its URLs will obviously need to be changed at some point, I'm just evaluating docfx at the moment to see what kind of HTML I can generate with it.

```c#
	/// <summary>
	/// A class that allows XJEase test functions in a project to be run.
	/// </summary>
	/// <remarks>
	/// <para>
	/// A Runner instance is obtained by calling <a href="ms-its:integrationxml.chm::/html/Overload_XJTAG_XJRunner_Integration_Project_GetRunner.htm">GetRunner</a>
	/// on a <see cref="Project"/> instance. 
	/// </para>
	/// <para>
	/// The Runner object provides the means to run XJEase functions that are part of your project. Call
	/// <a href="ms-its:integrationxml.chm::/html/Overload_XJTAG_XJRunner_Integration_Runner_StartTesting.htm">StartTesting</a> or either
	/// <see cref="RunTest"/> or <see cref="RunTests"/> to run tests.
	/// </para>
	/// <para>
	/// Multiple Runner instances can be created per class, although each instance must be associated with a
	/// different <see cref="XJLink"/>.
	/// </para>
	/// <para>
	/// This class implements the <see cref="IDisposable"/> interface. The XJLink will be unavailable for further use
	/// until this class is disposed.
	/// </para>
	/// </remarks>
```

**Comment by vicancy** [comment]
could you provide a minimum repro step? I am unable to repro the issue in my local machine with a simple project.

**Comment by vwxyzh** [comment]
> !:IDisposable
A type start with `!` means Roslyn failed to resolve the type correctly, and it generated an error type.

**Comment by jdh28** [comment]
I've cut my project down to isolate the issue and it is due to some custom build steps that are imported into the project. The custom tasks are in an x86 assembly and I guess that docfx is x64. If I comment out the msbuild target that references the x86 assembly, then the errors go away. It is not clear why this causes the errors that I see, however.

**Comment by MariusVolkhart** [comment]
Is there any way to figure out why Roslyn failed to resolve the type? I have this problem for `object.Equals(object)`, `System.IObservable<T>`, `string.Empty`, `System.Environment.MachineName`, and `object.GetHashCode()` but have no way of seeing what requests are being made to `https://xref.docs.microsoft.com/query?uid={uid}`

**Comment by vicancy** [comment]
@MariusVolkhart a minimum repro step can be helpful for us to identify the issue.

**Comment by MariusVolkhart** [comment]
@vicancy a more detailed writeup of my scenario w/ steps to reproduce and sample project is filed at https://github.com/dotnet/docfx/issues/2448

Thanks for looking into this 😃

**Comment by superyyrrzz** [comment]
Close for now as not be able to reproduce.

**Comment by damieng** [comment]
For anyone else coming to this issue that might be running into this error and wants to try a fix here's what worked for me:

Changed the `*.cs` match to `*.csproj`

e.g.

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [ "**/*.cs" ],
```

to

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [ "**/*.csproj" ],
```

I guess it could not resolve external refs using the *.cs mechanism perhaps because my project was targetting multiple frameworks (net452 and netstandard2_0)
