### ISSUE TITLE
How to generate API documentation for multiple projects using dotfx?

### ISSUE THREAD

**Issue by jagadeesan123** [dotnet/docfx#1711]
I am using the **dotfx** tool to publish API documentation support. In my project contains the following folder structure. In the src folder contains the various project files for different platform. I need to publish the API documentation for each project differently. So I need to generate the html files in different folders for each project.

Project
----------Src
------------------project_WPF.csproj
------------------project_Windows.csproj
------------------project_UWP.csproj

In this within the source folder contains the different projects for each platforms. For this case, I need to generate the API's in following structures,

API
--------- project_WPF (new folder)
----------------- _site(inside the above folder)
--------- project_Windows(new folder)
----------------- _site(inside the above folder)
----------project_UWP(new folder)
------------------_site(inside the above folder) 

By using the dotfx, it is possible to generate the API's for different project in different folder?. Can you please suggest how to achieve this?

Regards,
Jagadeesan

**Comment by vicancy** [comment]
Hi @jagadeesan123 , is it that for each project generate a new website or for each project generate a navbar tab?

**Comment by jagadeesan123** [comment]
Hi Vicancy,

For all the project we will include in single website alone, each project we will include in different pages in one website.

As per our requirement, we need to generate the _site files for each project in different folder. We will use that _site information to load it into the website. 

Regards,
Jagadeesan

**Comment by vicancy** [comment]
one `docfx.json` generates one website, so in your case, you need 3 docfx.json config file and call `docfx` 3 times to generate 3 website.

If you'd like one website containing multiple projects, you can follow the tutorial http://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project_2.html#step4-add-another-api-documentation

**Comment by jagadeesan123** [comment]
Hi vicancy,

Thanks for your response.

If I want to publish the API documentation for multiple websites, you updated "you need 3 docfx.json config file and call docfx 3 times to generate 3 website". Any reference or example for this?

Regards,
Jagadeesan

**Comment by vwxyzh** [comment]
@jagadeesan123 in docfx.json:
* "metadata" is an array, that means you can generate metadata per project.
* for "build", you can use multi-version.

**Comment by vwxyzh** [comment]
@jagadeesan123 one more solution is creating a multi-platform page (e.g. [ADAL](https://docs.microsoft.com/en-us/active-directory/adal/v2/microsoft.identitymodel.clients.activedirectory)):
* Metadata for each platform.
* Merge yaml files into one set.
* Build (require custom template).

**Comment by vicancy** [comment]
What kind of example do you want @jagadeesan123  Here is walkthrough for how to write a docfx.json file http://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project_2.html. In your case, you can have `docfx1.json`, `docfx2.json`, `docfx3.json`, each containing one project, and have your own `build.cmd` to call docfx 3 times:
```batch
docfx docfx1.json
docfx docfx2.json
docfx docfx3.json
```

**Comment by xavierjohn** [comment]
This tutorial has been deleted. 

How do we do it now?
