### ISSUE TITLE
Publishing API documentation for project with dependency projects using docfx

### ISSUE THREAD

**Issue by jagadeesan123** [dotnet/docfx#1713]
**Publishing API documentation for project with dependency projects using docfx.**
I have one project with dependency project. For example the project contains the dependency projects called project1, project2, project3 and project4.

Project <- project1, project2, project3, project4.

Now I need to publish the API documentation for the project with its dependency project. For example, any dependency class object is used in main project, we need to provide link for the dependency class from the main project in API location. For example, 

`/// <summary>
/// Gets or sets the name of the <see cref="dependency class name"/> theme.
/// </summary>
Dependency_Project_ClassName ActiveThemeName { get; set; }
`

For example, when declaring any property in main project with dependency project class. We need to provide support to hyperlink to navigate the dependency project class name from main project API.

Can you please suggest me how to achieve the above support using the docfx?

**Comment by vicancy** [comment]
Please include the dependent projects in "metadata" section

**Comment by jagadeesan123** [comment]
Hi vicancy,

Thanks for your immediate response.

Can you please share me any example or any reference to "include the dependent projects in metadata section.

Regards,
Jagadeesan

**Comment by vicancy** [comment]
Take the tutorial http://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project_2.html#step2-generate-metadata-for-the-c-project for example, in the metadata section, all the csproj projects under src folder will be included. If your dependent projects are also under the src folder, no change is needed.
```json
"metadata": [
    {
      "src": [
        {
          "files": [
            "src/**.csproj"
          ],
          "exclude": [
            "**/bin/**",
            "**/obj/**",
            "_site/**"
          ]
        }
      ],
      "dest": "api"
    }
  ]
```
