### ISSUE TITLE
How to execute the dotfx.exe in cake file?

### ISSUE THREAD

**Issue by jagadeesan123** [dotnet/docfx#1714]
I have added the .json file in our source location properly. Now I tested with command prompt by using the commandline to prepare the html files. 

docfx.exe docfx.json --build.

The above command properly generates the html files for the source. Now I need to include the above code in cake file. How can I integrate the code to cake file in the project. Can you please suggest how to implement the docfx command lines in cake file?

**Comment by pascalberger** [comment]
@jagadeesan123 You can use the [Cake.DocFx addin](http://cakebuild.net/dsl/docfx/)
