### ISSUE TITLE
Improve release notes

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#1715]
It would be nice to have useable release notes. The notes from either [Release page](https://github.com/dotnet/docfx/releases) or [RELEASENOTES.md](https://github.com/dotnet/docfx/blob/dev/RELEASENOTE.md) seem to be a arbitrarily selection of stuff included in a release (eg. [2.18.1](https://github.com/dotnet/docfx/releases/tag/v2.18.1) mentiones only two bug fixes, but also contains major features like PDF generation).

**Comment by pascalberger** [comment]
@vicancy My issue was actually more on a general level with the PDF sample just being a sample. Honestly I rarely found the release notes useful in the past and needed to find out about important changes by monitoring PRs and commits, and I think it would be really useful for others too to have release notes with a clear policy what is included in there and what not.

**Comment by vicancy** [comment]
Thank you @pascalberger for raise it up.
