### ISSUE TITLE
Facing an isssues with Version 2.18.2

### ISSUE THREAD

**Issue by Smilefounder** [dotnet/docfx#1719]
### Title
Error occur on run "docfx" command.
[error.txt](https://github.com/dotnet/docfx/files/1044439/error.txt)

Please help advise.

**Comment by superyyrrzz** [comment]
Seems there's some error when processing TOC. Can you provide your toc.md/toc.yml?

**Comment by Smilefounder** [comment]
@superyyrrzz Please see from the file below:
[toc.yml.txt](https://github.com/dotnet/docfx/files/1045381/toc.yml.txt)

**Comment by vicancy** [comment]
Hi @Smilefounder How did you install docfx 2.18.2?

**Comment by vicancy** [comment]
Looks like the configuration file is corrupted. Hi @Smilefounder  could you provide delete the file `docfx.exe.config` in the same folder as `docfx.exe` and have a retry?

**Comment by Smilefounder** [comment]
@vicancy : Thanks for your support, still got the same issue after deleted the config file in the same folder as docfx.exe

**Comment by vicancy** [comment]
Hi @Smilefounder  According to the error.txt:
```
Unrecognized configuration section runtime. (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config line 13)
```

Could you share what L13 of `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config` is? Looks like the config is corrupted...

**Comment by Smilefounder** [comment]
Hi @vicancy : please see the machine.config from the attachment below. Thanks a lot for your support so far.
[machine.zip](https://github.com/dotnet/docfx/files/1056857/machine.zip)

**Comment by Smilefounder** [comment]
I'm trying to reinstall windows and everything. Look like the .net framework from my computer is broken...
Will let the team posted on the result.

Thanks.

**Comment by Smilefounder** [comment]
The issue fixed by reinstall windows and .net frameworks... :|
