### ISSUE TITLE
Mixing up .NETFramework and .NETStandard Projects

### ISSUE THREAD

**Issue by FranklinTimmy** [dotnet/docfx#1729]
This is more of a question than an Issue.

I have 2 class library projects (ProjectA and ProjectB) targeting .NET Framework 4.5 and .NET Standard (Multiple Platforms) respectively. I have been messing around the `docfx.json` file to see if I can get API docs generated for both of em for the same portal.

```json
"metadata": [
{
  "src": [
	{
	  "files": [
		"ProjectA/**.csproj",
		"ProjectB/**.csproj",
	  ],
	  "src": "D:/GitHub/"
	}
  ],
  "dest": "api"
}
],
```

No matter what approach I take I either get a metadata corruption error or API is only generated for ProjectB if I specify `TargetFramework`.

Is this mix-up currently supported?

**Comment by vicancy** [comment]
https://github.com/dotnet/docfx/issues/1254#issuecomment-294080535
