### ISSUE TITLE
Link to Microsoft Visual Studio 2015 build tools is broken

### ISSUE THREAD

**Issue by dlech** [dotnet/docfx#1733]
on the page, http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html

in the note "Prerequisites: .NET Core, .NET Framework 4.6, and Microsoft Build Tools 2015(No need if you install VS 2015)"

the link https://www.microsoft.com/en-us/download/details.aspx?id=48159 is broken (says download is no longer available).

**Comment by vicancy** [comment]
The dep is removed.
