### ISSUE TITLE
Possible to add note blocks to comments in `.cs` files?

### ISSUE THREAD

**Issue by mfaux** [dotnet/docfx#1737]
### Is it possible to add note blocks to comments in `.cs` files?

I've tried:
```
/// > [!NOTE]
/// > This property is unsupported by SAP products.
```

Which renders as:

![image](https://user-images.githubusercontent.com/1324114/26869470-dd12aad8-4b6c-11e7-9f40-20be78df5556.png)

I was hoping for:
![image](https://user-images.githubusercontent.com/1324114/26869613-4fa42766-4b6d-11e7-9880-85242c6341f5.png)

Applies to docfx version 2.18.2.0.

**Comment by vicancy** [comment]
Should be supported.
