### ISSUE TITLE
"DocFX" needs to be capitalized in some locations.

### ISSUE THREAD

**Issue by seandebutts** [dotnet/docfx#174]
Certain files need to have "docfx" and "Docfx" changed to "DocFX" in some places.

For example, on the site for docfx (https://dotnet.github.io/docfx/), the footer displays "Generated by docfx". On https://dotnet.github.io/docfx/, the tab's title currently is "Welcome to Docfx website".

These files need changes in certain places:

docfx.exe_user_manual.md
index.md
docfx.json
test.js (there are at least five files by this name)

**Comment by vicancy** [comment]
Should be fixed now. Thanks.
