### ISSUE TITLE
Support for overwriting <see cref> link text

### ISSUE THREAD

**Issue by mfaux** [dotnet/docfx#1745]
### Feature request: Support for overwriting \<see cref\> link text
I'd like to be able to overwrite the link text generated by `<see cref>`s.

For example, I would like:
```C#
/// If the animal <see cref:AnimalType.IsDog>is a dog</see>...
```
To render as:
* "If the animal [is a dog]()..."

**Comment by superyyrrzz** [comment]
IMO I do not want to extend the [syntax as defined in documentation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/see). By the way, you can use DFM's syntax like `[is a dog](xref:AnimalType.IsDog)`.

**Comment by mfaux** [comment]
Thanks for the update.

I'm trying to write comments that work well in both Visual Studio's IntelliSense as well as web output. Although DFM's `xref` renders poorly in Intellsense when used in `<summary>` tags, it's nice to know the option exists.  

![image](https://user-images.githubusercontent.com/1324114/54133663-c2d1a800-4416-11e9-8348-f1a80313cc3e.png)


Perhaps if I limit usage to outside to e.g. `<remarks>`...anyways, thanks.

**Comment by superyyrrzz** [comment]
You are right of the limitation in Intellisense. [Overwrite files](https://dotnet.github.io/docfx/tutorial/intro_overwrite_files.html) may be another option for you.

**Comment by batbaille** [comment]
I begin with DoxFX. I have the issue with the content of cref in my project. 
I use it for all summary of classes in my big project (>2000 classes). 
Example : 
```
/// <summary>
/// Business class used to manage the <see cref="Product">products</see>
/// </summary>
```
Must I rewrite all summaries of my classes ?
I don't understand the answer with "Overwrite files". Is it possible to explain ?

**Comment by superyyrrzz** [comment]
@batbaille you could open another issue as this is not the same issue with main thread.

In short, DocFX will change cref to the link you expect automatically. It should work without any change needed from you. You could open another issue for more details to help reproduce this issue.

**Comment by batbaille** [comment]
Sorry, I created the issue #4160
