### ISSUE TITLE
Metadata generation for class libraries with dependencies

### ISSUE THREAD

**Issue by leopignataro** [dotnet/docfx#1753]
Suppose I have two class libraries `Contoso.LibA` and `Contoso.LibB`, each published to Nuget, and `Contoso.LibB` depends on `Contoso.LibA`. Furthermore, I have the following classes:

On `Contoso.LibA`:

    namespace Contoso.LibA {
        public class ClassA {
            ...
        }
    }

On `Contoso.LibB`:

    namespace Contoso.LibB {
        public class ClassB : Contoso.LibA.ClassA {
            ...
        }
    }

During metadata generation for `Contoso.LibB`, metadata for `ClassB` is generated like this:

    inheritance:
        - System.Object

Am I missing something? I even generated with `--logLevel Diagnostic`, but no errors where logged.

Both csprojs have `<TargetFrameworks>`, perhaps this makes things harder?

EDIT: I have the xrefmap for `Contoso.LibA` on the `docfx.json` of `Contoso.LibB`, but that doesn't seem to affect metadata generation, right?

**Comment by vicancy** [comment]
Looks like your project is successfully loaded however ClassA is not correctly resolved. Did you specify `TargetFramework` for the project as similar to the sample docfx.json in https://github.com/dotnet/docfx/blob/dev/Documentation/tutorial/docfx.exe_user_manual.md#31-properties-for-metadata? Could you provide your `Contoso.LibA` so that I can try to repro the issue.

**Comment by leopignataro** [comment]
Thank you for your answer, @vicancy !

I was able to pinpoint the root cause of my issue. The metadata is only built correctly if I do a `dotnet restore` on my projects before running `docfx metadata`. Since I was getting a lot of "invalid cache" warnings from docfx because of my changes to docfx.json, I was constantly removing the `bin` and `obj` folders of my projects, which pretty much undoes what `dotnet restore` does.

What is weird is that docfx never issued any warnings related to not being able to resolve references.

Using `<TargetFrameworks>` had nothing to do with the issue, I was able to reproduce it even with a single target framework.

Please let me know if you still want a sample project to reproduce this issue.

**Comment by vicancy** [comment]
Oh yes, `dotnet restore` is needed before `docfx metadata`, as similar to `dotnet build`... `invalid cache` warnings are false warnings that you can temporarily ignore.
