### ISSUE TITLE
Enhancement - Search to index also comments and present them in results

### ISSUE THREAD

**Issue by AlthalusDGr8** [dotnet/docfx#1755]
### Title
Search to index also comments and present them in results

### Functional impact
Sometimes you happen to remember keywords but not exactly sure in which library it falls into
### Minimal repro steps
1. Add some text in the comments which are distinctive (such as 'dragons')
2. type dragons in search after rebuilding
3. No results are found

### Expected result
I would like to have the results which also match with the comments
### Actual result
Nothing is being shown

**Comment by vicancy** [comment]
what does *comments* mean here? The default website docfx generates does not have comment system...

**Comment by vwxyzh** [comment]
Comment in html?

**Comment by AlthalusDGr8** [comment]
by comments I meant comments created in code which are part of the output of the XML documentation file

**Comment by vicancy** [comment]
Comments in code should be indexed already.
