### ISSUE TITLE
How to generate static HTML files?

### ISSUE THREAD

**Issue by skch** [dotnet/docfx#1762]
### Need options to generate static HTML files instead of "serving"

There are many scenarios when the documentation needs to be added to an existing web application that is not running on .NET

```docfx.exe project\docfx.json --static --out: web\docfx-static

**Comment by vicancy** [comment]
the generated HTML files are static already...no server side logic, only AJAX calls from client side JS for loading navbar and TOC. If you want a pure static HTML files without even AJAX calls, you can use `statictoc` template.
