### ISSUE TITLE
Support syntax highlight in PDF

### ISSUE THREAD

**Issue by vicancy** [dotnet/docfx#1766]

**Comment by vwxyzh** [comment]
I think it should base on #1620.

**Comment by vicancy** [comment]
@vwxyzh Highlight is much simpler than that....

**Comment by vwxyzh** [comment]
Yes, but same thing is you need to know which is keyword, which is identify, which is type.

**Comment by vicancy** [comment]
I suppose #1620 is for .net only? for this PDF highlight, the simplest way is to add client side javascript library, e.g. highlight.js, the concern is that it may slow down the PDF render.

**Comment by vwxyzh** [comment]
Yes, can we render it in build time?

**Comment by vicancy** [comment]
keep it client side for now https://github.com/dotnet/docfx/pull/1800 does not seen obvious perf downgrade when adding js to PDF

**Comment by vicancy** [comment]
https://github.com/dotnet/docfx/pull/1800
