### ISSUE TITLE
Problems with generating PDF from HTML (please help!)

### ISSUE THREAD

**Issue by istvanbalog** [dotnet/docfx#1772]
### Problems with generating PDF from HTML (please help!)
When Docfx tries to generate PDF files it says several times:
`Convert failed, will retry in 00:00:05seconds`
and then:
`Convert the file : ".../.tmp/pdf/../... - has exception, the details: The system cannot find the file specified ` 
(full path not included)

I see that the .tmp and pdf folders are created and then they disappear in the Windows Explorer window.
The issue is probably because of one of these things:
1. Docfx removes the folders or files before they could find them.
2. Docfx can't copy the files to the appropriate folders so they are not there. (anyway Docfx has full rights to do that)
3. Other thing

I'm not sure why the temporary (.tmp) folder is needed, is it really necessary?

What can I do to fix this?

### Minimal repro steps
1. Install docfx and wkhtmltopdf, create a new docfx project with init or use existing project (folder). You'll need some documentation files.
2. Add pdf section according to this:
https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_generate_pdf.html
3. Run docfx command (generate metadata, build, generating pdf). Maybe you need to use **docfx pdf**
4. See the result

### Expected result
It should generate a pdf file containing table of contents and all the documentations without exceptions.

### Actual result
Now it can't find the specified files, can't generate appropriate pdf file (corrupted).

**Comment by vicancy** [comment]
The warning message is not meaningful. The message usually shows when `wkhtmltopdf` is not set to %PATH%....

Could you save the executable folder path to %PATH% by: `set PATH=%PATH%;E:\Program Files\wkhtmltopdf\bin`, or save to global environment PATH by `setx PATH "%PATH%;E:\Program Files\wkhtmltopdf\bin"` and have a retry?

As an alternative, you can install it through  `choco install wkhtmltopdf`
