### ISSUE TITLE
the command docfx template list does not show the pdf template

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#1797]
### Title
The command `docfx template list` does not include the default template used for PDF generation

### Functional impact
It is hard to figure out how to customize the PDF template if I can't export it. And I can't export it because I don't know how it is called. (I am hoping that if it would be listed I will recognize it as the template that is most likely the one hat is used for the  `docfx pdf` command.)

### Minimal repro steps
Run `docfx template list`

Resulting output:

> Existing embedded templates are:
>         default
>         iframe.html
>         statictoc
> [17-06-23 08:05:16.925]Info:Completed executing in 4,031 milliseconds.

**Comment by vicancy** [comment]
https://github.com/dotnet/docfx/pull/1802
