### ISSUE TITLE
Overriding example with *content in same file as other overrides doesn't work

### ISSUE THREAD

**Issue by jasonjoh** [dotnet/docfx#1803]
Overriding `example` with the `*content` anchor in the same file that overrides another field (also with the `*content` anchor) causes the `example` value to be ignored.

For example, using the following override file:

<pre><code>
---
uid: MyApp.MyService
remarks: *content
---

Here are some remarks about `MyService`.

---
uid: MyApp.MyService
example: [*content]
---

This is an example.

```csharp
var service = new MyService();

service.DoSomethingCool()
```
</code></pre>

The result is that the remarks show up, but the example does not.

I've verified that I can override multiple sections with the `*content` anchor in the same file, as long as one of them is not `example`. (For example, I've done both `remarks` and `summary`).

I tried putting `example` first in the file, but that did not change the result.

The only thing that worked was to create a separate file for just the `example`. This is less than ideal though because of how the *Improve this Doc* link works.

**Comment by vicancy** [comment]
Hi @jasonjoh  I could not repro the issue:
1. Use a file `Microsoft.DevDiv.ExplicitLayoutClass.yml` generated by `docfx metadata` for https://github.com/docascode/docfx-seed
2. Copy your content to `ow.md` and change uid to `Microsoft.DevDiv.ExplicitLayoutClass`
```markdown
---
uid: Microsoft.DevDiv.ExplicitLayoutClass
remarks: *content
---

Here are some remarks about `MyService`.

---
uid: Microsoft.DevDiv.ExplicitLayoutClass
example: [*content]
---

This is an example.

```csharp
var service = new MyService();

service.DoSomethingCool()
```
```

3. run `docfx build --content Microsoft.DevDiv.ExplicitLayoutClass.yml --overwrite ow.md -o _site`
4. the generated html file contains the example section.

Input files attached:

[Microsoft.DevDiv.ExplicitLayoutClass.zip](https://github.com/dotnet/docfx/files/1107432/Microsoft.DevDiv.ExplicitLayoutClass.zip)

Output file attached:

[Microsoft.DevDiv.ExplicitLayoutClass.zip](https://github.com/dotnet/docfx/files/1107435/Microsoft.DevDiv.ExplicitLayoutClass.zip)

**Comment by jasonjoh** [comment]
Hmm ok. If I pull the YML for this one class and the overwrite into an empty directory and do the build as you describe, I get the Examples section. However if I do it in place with the rest of my project, it gets ignored. So it's either something with my docfx.json or something else in my project. Is there some way for me to troubleshoot the build and figure out where I'm going wrong?

**Comment by jasonjoh** [comment]
Ah ok. I ran the build with the `-f` flag, and that seems to have resolved it. I guess there was something being cached that was causing it to not pick up the example.

**Comment by vicancy** [comment]
Then it should be a bug for incremental build....
