### ISSUE TITLE
Problematic instructions for setting PATH in PDF instructions

### ISSUE THREAD

**Issue by sandersaares** [dotnet/docfx#1805]
The instructions in the following paragraph of https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_generate_pdf.html are problematic:

> E:\Program Files\wkhtmltopdf\, and save the executable folder path to %PATH% by: set PATH=%PATH%;E:\Program Files\wkhtmltopdf\bin, or save to global environment PATH by setx PATH "%PATH%;E:\Program Files\wkhtmltopdf\bin".

The problem is that `%PATH%` by default is a merged list of the user-scoped PATH and the global-scoped PATH. However, these instructions overwrite a *single* PATH variable (I forget which one both it's bad in both cases) with the merged PATH list from both variable scopes, ending up with duplication, and in the worst case, conflicts and maintenance headaches.

You should always operate with a specifically-scoped PATH variable, not the merged `%PATH%` expansion. Here is an example of how to do it safely:

```
$path = [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine)
$path = $path + ";C:\Docker"
[Environment]::SetEnvironmentVariable("Path", $path, [EnvironmentVariableTarget]::Machine)
```

**Comment by vicancy** [comment]
Thanks for pointing it out @sandersaares Yes, totally agree with you
