### ISSUE TITLE
XREF link to API doc with wildcard UID not getting generated

### ISSUE THREAD

**Issue by cgillum** [dotnet/docfx#1807]
### Title
XREF links from markdown files to auto-generated API documentation UIDs with wildcards (*) stopped working when I migrated from .NET Framework to new VS2017 project file format + GitHub repo.

### Functional impact
These API documentation links don't get rendered in markdown documentation files.  This breaks an existing documentation project which used to work for the same source code.

### Minimal repro steps
1. Auto-generate metadata from VS2017-style csproj source code within a local GitHub repo clone
2. Copy UID with wildcard from generated yml file and reference it from markdown documentation using xref syntax. For example: `<xref:Namespace.Class.Method*>`
3. Build

### Expected result
Generates a HTML link to the appropriate generated API documentation page.

### Actual result
The build step produces a warning:

`Warning:[Build Document.LinkPhaseHandlerWithIncremental.Apply Templates](articles/topics/external-events.md)Invalid cross reference "&lt;xref:Namespace.Class.Method*&gt;".`

And no link is generated in the HTML output.

### Further technical details
The XREF feature I'm referring to is documented here: https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-cross-reference

This XREF syntax worked fine with the exact same source code when used outside of a Git repository and when using the VS2015 csproj file format. The problem began after I refactored the project to use the new VS2017 csproj format and after I put the code into a local GitHub repo.  I'm not sure which of the two (or both) are the important difference. The C# files in the working and non-working cases are exactly the same. The generated yml files are only marginally different due to the new repository metadata.

Note that XREFs for UIDs that don't end with a wildcard work fine. Only the wildcard UIDs seem to be problematic.

I'm using docfx 2.19.1.0.

**Comment by cgillum** [comment]
I found a workaround for this.  If I specify the `-f` flag in my `docfx` command, then the wildcard method links get generated properly in my `xrefmap.yml`.  My XREFs then are correctly converted into links in my content HTML. However, if I run the command a second time and do *not* include `-f`, then all the wildcard references in `xrefmap.yml` are removed and my links stop getting rendered.

In that light, it may not be strictly related to the csproj file format or the use of Git. However, it's not clear to me why the old copy of my project never had this problem but the new one does.

**Comment by vicancy** [comment]
If `-f` works, it should be an incremental bug...will take a look, thanks for reporting the issue.

**Comment by vicancy** [comment]
Hi @cgillum  which version of docfx are you using?
