### ISSUE TITLE
Error creating pdf with exported template

### ISSUE THREAD

**Issue by RobDaPraia** [dotnet/docfx#1819]
### Error creating pdf with exported template
When creating a pdf with an exported default template or custom template, you get an error
### Functional impact
Not able to create pdf output from DocFx with custom template

### Minimal repro steps
Use attached project, with the pdf reference in docfx-pdf.json

```
docfx template export default
docfx docfx-pdf.json -t _exported_templates\default
```

### Expected result
Pdf of the markdowns

### Actual result
Error:
```
[17-07-02 08:08:47.346]Error:System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Invalid manifest item: Microsoft.DocAsCode.Plugins.ManifestItem
Parameter name: manifestItem
   at Microsoft.DocAsCode.HtmlToPdf.ManifestUtility.GetAssetId(ManifestItem manifestItem)
....
```

### Further technical details
You can use the attached project [DocFx.zip](https://github.com/dotnet/docfx/files/1117678/DocFx.zip)

>Note:  the following works as expected, html documents, no errors (no pdf definition in docfx.json)

```
docfx template export default
docfx -t _exported_templates\default
```

**Comment by vicancy** [comment]
`pdf.default` is for pdf

**Comment by RobDaPraia** [comment]
Thanks for the quick reply. Does this mean you always have to run separate DocFx for html and separate DocFx for pdf when you are using a custom template for the html?

Because I now have a docfx.json with definition for the html and the pdf and when I run this definition to generate the Html and the pdf in one command with custom template for html, like "docfx docfx-pdf.json -t _exported_templates\default",  I get the error. 

And I cannot use pdf.default since the custom template is for the html

**Comment by vicancy** [comment]
Actually when generating PDF, it generates temp html files and calls `wkhtmltopdf` to generate PDF file based on these html files, that's why we are using 2 different template.

if you want one command to generate both website and pdf, you have to specify the template inside docfx.json, as similar to:
```json
"build": {
  "template": [
    "default",
   "custom_template_folder",
]
},
"pdf":{
"template": [
    "pdf.default",
   "custom_template_for_pdf",
]
}
```
And then call `docfx docfx.json` to generate both website and pdf.

**Comment by RobDaPraia** [comment]
Thanks for the answer. Yest that works :)
