### ISSUE TITLE
Layout rendering mismatch with tables on mobile

### ISSUE THREAD

**Issue by RobDaPraia** [dotnet/docfx#1820]
### Layout rendering mismatch with tables on mobile
When using tables with long content, the rendering on mobile is mismatched. The navbar is shrinked to show the full table width, see attached screenshot. On Desktop the effect is not so dramatic, you get a horizontal scrollbar on the bottom of the page

### Functional impact
Page looks 'not good' on mobile when using tables

### Minimal repro steps
Create DocFx from attached project and open site on mobile

[DocFx.zip](https://github.com/dotnet/docfx/files/1117682/DocFx.zip)

### Expected result
Navbar full width on mobile, responsive table on mobile

### Actual result
Screen is resized to accommodate the full width of the table

### Further technical details
An option would be to make the tables responsive by the following html code. 

Or can we easily add the  "div class="table-responsive"" by a custom template?

```
<div class="table-responsive">
<table>
...
</table>
  </div>
```
In the attached screenshots you can see how the responsive table looks (the lower table)

![tableonmobile](https://user-images.githubusercontent.com/3207395/27768353-b5b004be-5f11-11e7-9954-3281d948bc9d.PNG)

![tabelondesktop](https://user-images.githubusercontent.com/3207395/27768345-505ab294-5f11-11e7-97d0-76f3a9314d96.png)

**Comment by superyyrrzz** [comment]
Same with #2024. Resolved in #2084 since v2.25.
![image](https://user-images.githubusercontent.com/3831744/31529617-e9b9690c-b00c-11e7-909b-7f99ae6e5e48.png)
