### ISSUE TITLE
Custom template not applied when specified in docfx.json

### ISSUE THREAD

**Issue by RobDaPraia** [dotnet/docfx#1821]
### Custom template not applied when specified in docfx.json
Applying a custom template works when used a parameter from command line, but does not work when specified in docfx.json configuration file.

### Functional impact
In automatic build have to specify command line parameters instead of using the configuration file

### Minimal repro steps
See attached docfx project, we try to add the Application Insights JavaScript snipped to the head of the html.

[DocFx.zip](https://github.com/dotnet/docfx/files/1117685/DocFx.zip)

OK
```
docfx -t default,templates\mytemplate
```

NOK
```
docfx docfx-custom-template.json
```
### Expected result
The JavaScript snippet  from templates\mytemplate\partials\head.tmpl.partial  to be included in the html

### Actual result
Custom template is not applied when setting the template in the docfx configuration file

### Further technical details
the custom template is specified in the docfx-custom-template.json as follow, see attached docfx project:

```
  "build": {
  "template": [
        "default",
        "templates/mytemplate"
    ],
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md",
          "api-vb/**.yml"
        ]
      },
...
```

**Comment by vicancy** [comment]
Unable to repro the issue. 
I downloaded your zip file attached, and add
```json
,
"templates/mytemplate"
```
to the `template` section, and the generated html page applies your `head.tmpl.partial`.

**Comment by vicancy** [comment]
![image](https://user-images.githubusercontent.com/668244/27775294-5ad19af4-5fd3-11e7-9f7a-62be42e3d6a8.png)

**Comment by RobDaPraia** [comment]
Thanks for the quick reply,

I still have this issue with the following command:

```
docfx docfx-custom-template.json
```

I read from your comments that you updated the docfx.json file and succeeded in creating the html with javascript

Then I must do something wrong in my docfx-custom-template.json.

Can you maybe post the docfx.json config file you used to make sure I did not make a typo in my config file?

**Comment by vicancy** [comment]
I noticed that in your docfx-custom-template.json in defined two `template` section, one as the first property for `build` section, one as the last property for `build` section. Remove one and have a retry. 
![image](https://user-images.githubusercontent.com/668244/27780336-efd5e2aRemve.png)

**Comment by RobDaPraia** [comment]
:)

Thanks a lot! Totally overlooked that second setting. Works now.

**Comment by txwizard** [comment]
One thing that the documentation doesn't make clear is that the templates directory goes off the root of the project, rather than the DocFX application root directory.
