### ISSUE TITLE
Feature request: multi-line, stable .manifest file

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#1824]
### Title

Feature request: multi-line, stable `.manifest` file

### Functional impact

I'd hope there'd be no functional impact in this reformatting

### Usage impact

Currently, each `.manifest` file is a single giant line, and I *think* the order is unstable (although it's hard to tell). This means any time a `.manifest` file lives in source control, any change ends up being shown as a giant diff, which is distracting.

While the diff information may not be *terribly* useful for humans anyway, it would be much easier to sanity-check it if the `.manifest` file were generated as a formatted JSON file, with a stable ordering.

If there's a fear that this could break clients, it could potentially be an option in the metadata section of the docfx.json file.

**Comment by vicancy** [comment]
Do you mean `.manifest` file?

**Comment by jskeet** [comment]
@vicancy: Sorry, yes, I do - edited. Not sure why I had that small braino!
