### ISSUE TITLE
Feature request: add support for inheriting non-public commments

### ISSUE THREAD

**Issue by mfaux** [dotnet/docfx#1832]
### Title
Add support for `<inheritdoc>` to inherit non-public triple-slash comments.

### Use case
I have an `internal` interface that a `public` class inherits.  I don't want to expose the internal interface to my API consumers, but I want to reuse the triple slash comments from that interface.

**Comment by vicancy** [comment]
It is not supported and not easy to support in current design. `internal` members are filtered out at the very beginning, while `inheritdoc` is processed when all the members are fetched out.
