### ISSUE TITLE
inheritance not processed properly across namespaces

### ISSUE THREAD

**Issue by AyrA** [dotnet/docfx#1844]
### Title
Class inheritance is not processed correctly if the classes reside in different namespaces

### Functional impact
Documentation is incomplete. Some classes lack the inherited classes in the inheritance tree on the top of the documentation files

### Minimal repro steps
1. create console C# project with namespace `A`
1. add class `public class Child : Intermediate { public string FromChild; }` in namespace `A`
1. add class `public  class Intermediate : Base { public string FromIntermediate; }`  in namespace `A.B`
1. add class `public class Base { public string FromBase; }` in namespace `A.B`
1. generate documentation

### Expected result
- The document for `Child` shows that it inherits from `Intermediate` and it should show the inherited members
- The document for `Intermediate` shows that it inherits from `Base` and it should show the inherited members. It should also show the children (in this case `Child`)
- The documentation for `Base` shows the children (`Intermediate`)

### Actual result
- The documentation for `Child` lacks any content regarding `Intermediate`.
- The documentation for `Intermediate` lacks any content regarding `Child`.
- The documentation for `Base` is correct.

### Further technical details
The issue seems to be purely based on namespaces. Inheritance across namespaces is completely ignored, even though the class definitions in the documentation show it. If all classes are moved to the same namespace, it works as expected.

**Comment by AyrA** [comment]
This is still an issue in version 2.55. Are there any plans on fixing this?

**Comment by lukasdragon** [comment]
Have there been any updates on this issue?

**Comment by yufeih** [comment]
Does not seem to repro with this code snippet. `public class Child : Intermediate` should be become `public class Child : B.Intermediate`?

```csharp
namespace A
{
    public class Child : B.Intermediate { public string FromChild; }

    namespace B
    {
        public class Intermediate : Base { public string FromIntermediate; }

        public class Base { public string FromBase; }
    }
}
```
