### ISSUE TITLE
Question: Change storage location of resources

### ISSUE THREAD

**Issue by xxcuratorxx** [dotnet/docfx#1845]
My docfx.json is in the root folder of our project. There are many projects inside, of which some have to be documented. 
   \Project1\SubProjectA\SubSubProjectX // To be documented
   \Project2\SubProjectB // Not to be documented
    ... // Many other projects

In docfx.json, I now include in "build", "content"
```
{
    "files": "*.{md,yml}",
    "src": "Project1\SubProjectA\SubSubProjectX",
   "dest": "p1"
},
```
The generated html file are stored in `p1` as expected

If I add resources
```
{
    "files": "Project1\SubProjectA\SubSubProjectX\images\**",
    "dest": "p1_resource"
},
```
the resources are copied to `p1_resource\Project1\SubProjectA\SubSubProjectX\images\`. However, they are linked in the html files correctly. 

Is it possible to get rid of `\Project1\SubProjectA\SubSubProjectX\images` part?

If I add the `src` part as for the `content`, the files are copied to a resonable place, but the hrefs in html are wrong

**Comment by superyyrrzz** [comment]
Using `src` in `resources` should work. How do you link to the resource file? You should use the path in original form, like `[xxx](Project1\SubProjectA\SubSubProjectX\images\a.jpg)`.

**Comment by vwxyzh** [comment]
> If I add the src part as for the content, the files are copied to a resonable place, but the hrefs in html are wrong

Looks like a bug.
@xxcuratorxx can you provide a mini repro?

**Comment by 928PJY** [comment]
@xxcuratorxx  Any updates? If not, we will close the issue
