### ISSUE TITLE
XRefMaps not working for generic types

### ISSUE THREAD

**Issue by matkoch** [dotnet/docfx#1846]
I have an [xrefmap.yml](https://github.com/nuke-build/git/blob/master/specs/xrefmap.yml) which defines missing `uid` along with their `href`. For simple parameter types like [`SecureUsernamePasswordCredentials`](http://www.nuke.build/api/Nuke.Git.GitTasks.html#Nuke_Git_GitTasks_GitCredentials) it works. But I also have some generic parameter types, where it doesn't. Like for [`Configure<LibGit2Sharp.CloneOptions>`](http://www.nuke.build/api/Nuke.Git.GitTasks.html#Nuke_Git_GitTasks_GitClone_System_String_System_String_Nuke_Core_Tooling_Configure_LibGit2Sharp_CloneOptions__). In this case, no link is created, and the fullName is left as simple text. What I'm expecting are two links, one for `Configure` and one inside for the generic argument `CloneOptions`.

For BCL types I'm also providing the xref's, and it works as expected. Anything I'm doing wrong?

**Comment by vicancy** [comment]
Hi @matkoch  I noticed that your website is generated from docfx 2.19 however the website is using an old version of `docfx.js` which contains a bug https://github.com/dotnet/docfx/commit/5e4683c07d42f5440ec354831a9dcd036f2dcdf4#diff-e6f7d7f7beddac78dee419420b540cd7R129 that it uses local search always and thus slows the page load....

**Comment by matkoch** [comment]
@vicancy alright, will check that... but it's not related to the problem described, isn't it?

**Comment by vicancy** [comment]
@matkoch not at all.. @vwxyzh is investigating the issue...

**Comment by matkoch** [comment]
Also noticed that for primitive types with `Nullable<T>`.

**Comment by vwxyzh** [comment]
Looks like template issue, what template do you use?

For example, in [this page](http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.MarkdownLite.InlineContent.html#property-value) you can find this type: `System.​Collections.​Immutable.​Immutable​Array<IMarkdown​Token>`
The source html is:
```html
<td><span class="xref text-break">System.Collections.Immutable.ImmutableArray</span>&lt;<a class="xref text-break" href="Microsoft.DocAsCode.MarkdownLite.IMarkdownToken.html">IMarkdownToken</a>&gt;</td>
```

But in [your page](http://www.nuke.build/api/Nuke.Git.GitTasks.html#parameters) `Nuke.Core.Tooling.Configure<LibGit2Sharp.CloneOptions>`
The source html is:
```html
<td><span class="xref">Nuke.Core.Tooling.Configure&lt;LibGit2Sharp.CloneOptions&gt;</span></td>
```

**Comment by matkoch** [comment]
Okay, this is strange. I tried to investigate a little more. Building locally, everything works - generics, xrefmaps, etc...

But the website is published from CI server, and there basically all 'non trivial types' (generics, arrays), won't have a proper link generated.

However, I'm invoking the exact same docfx executable... so I'm really lost what could possibly be wrong... Is docfx loading some external files which might differ on the CI ?

**Comment by matkoch** [comment]
This seems like a non-deterministic issue. The CI has a scheduled build every morning, and currently the yref links are generated correctly.

Any idea how to track this down? As an attempt, let me explain the project structure a little:

- There is a "Core" repository cloned, along with its "Addin" repositories
- Addin projects reference the core project; not necessarily in the same version (currently they are different in fact)
- All cloned repositories are restored (NuGet) prior to the metadata task
- I'm generating a custom toc.yml; but it doesn't seem related
- I have the sidetoc template customized; but also this doesn't seem to be it

**Comment by 928PJY** [comment]
Hi @matkoch Any other repro to the issue from then on? If not, we'd like to close the issue.

**Comment by matkoch** [comment]
@928PJY https://github.com/dotnet/docfx/issues/1846#issuecomment-317173928

**Comment by vicancy** [comment]
Hi @matkoch Could you provide the metadata .yml file, in this case, `Nuke.Git.GitTasks.yml` when the link is not generated correctly? I am also not able to repro the issue locally.

**Comment by matkoch** [comment]
Didn't happen for a long time, will re-open if necessary.
