### ISSUE TITLE
langword not supported

### ISSUE THREAD

**Issue by wekempf** [dotnet/docfx#185]
My XML Documentation includes heavy use of <see langword="null"/> and other langwords (true, false, etc.). DocFX just strips these out entirely.

**Comment by vicancy** [comment]
Could you provide more details on the issue, for example, repo steps.

**Comment by wekempf** [comment]
Sorry for the late reply. I've been very busy.

Sandcastle supports a 'see' tag in the form <see langword="null"/>, which is transformed into the usual MSDN "null (Nothing in VisualBasic)" or something like that. You can use other langword values as well, such as true and false, which resulted in bolded text under Sandcastle. This formulation is pretty widely used, as even GhostDoc supports generating comments with langword references.

When I used docfx to generate documentation with these tags, docfx just ignored them, resulting in text with missing words. This can be seen at http://wekempf.github.io/testify/api/Testify.AnonymousBool.html where the Exception documentation reads "anon is ." The actual documentation comment was "<paramref name="anon"/> is <see langword="null"/>."

Is that enough additional information for you. Do you need a repo other than this project?

**Comment by wekempf** [comment]
Just to let you know, the URL I provided to my site and the project source no longer illustrate the problem. I've (hopefully temporarily) switched to `<c>null</c>` in my source, so that I get valid generated documentation. I'd much prefer to see DocFX handle langword properly (probably producing `<span class='langword'>null</span>`, for instance), and when it does I'll go back to langword in my source.

**Comment by vicancy** [comment]
Thanks @wekempf . We plan to improve the support for triple-slash-comments in the upcoming weeks. Will keep you updated.

**Comment by vwxyzh** [comment]
add it to default behavior.
80f2cccd7d945fcf0003aacef514796d0fdab66a
