### ISSUE TITLE
Create a material style theme

### ISSUE THREAD

**Issue by vicancy** [dotnet/docfx#1862]
the layout of Google API theme looks quite similar to docfx's
![image](https://user-images.githubusercontent.com/668244/28101079-bc87d4a8-66f8-11e7-8373-43e28fb6a83a.png)

**Comment by shyamal890** [comment]
+1

**Comment by ovasquez** [comment]
The Material Theme for MkDocs could be used as the base for the docfx theme
https://squidfunk.github.io/mkdocs-material/

There are already a couple of ports of that theme to other generators:
- https://themes.gohugo.io/theme/material-docs/getting-started/
- https://github.com/jonas/paradox-material-theme

**Comment by JimBobSquarePants** [comment]
Creating a theme here shouldn't be a concern of the core project, rather simplifying the creation of themes should be. 

There are serious markup, css styling and accessibility issues with the default templates and I would suggest getting someone with UX/frontend skills involved to help clean it up.

I've noted in an attempt to style the default output:

- Removal of outline styles. 
- Lack of aria attribution for menu items
- Over specificity of css selectors
- Floating items without clearing containers 
- Absolute and fixed positioning where it simply isn't required.
- Over complication of markup for iconography
- Tiny clickable areas (side nav)
- No use of sections/articles. 
- Very limited use of Html5 roles
- Old JQuery library inclusion

And that's just scratching the surface.

This work would require a major version as it would introduce breaking changes. 

I'm more than a little disappointed that MS didn't strive to make the output more inclusive.

**Comment by JimBobSquarePants** [comment]
Hey @yufeih long time no chat! 😄 

When you get around to making plans for vnext more concrete I'd love to help so please let me know.

**Comment by superyyrrzz** [comment]
#4002
