### ISSUE TITLE
DocFX throws System.NotImplementedException

### ISSUE THREAD

**Issue by Dids** [dotnet/docfx#1863]
### Title
Supposedly a parsing issue with `docfx.json` throws `System.NotImplementedException`.

### Functional impact
This breaks DocFX due to the exception being thrown.

### Minimal repro steps
1. Create a .NET Standard 1.6/2.0 library (Mono 5, Visual Studio for Mac)
2. Create `docfx.json` with `globalMetadataFiles` referencing another JSON config file containing at least the `_gitContribute` object
3. Run DocFX

### Expected result
This should compile and generate the documentation just fine.

### Actual result
Doesn't finish running and throws the following JSON .NET exception instead:

```
Error: System.AggregateException: One or more errors occurred.
---> System.NotImplementedException: The method or operation is not implemented.
  at Newtonsoft.Json.Linq.JObject.System.Collections.Generic.IDictionary<System.String,Newtonsoft.Json.Linq.JToken>.get_Values () [0x00000] in <607e95f78559498690f968784b884761>:0 
```

### Further technical details
Removing the `_gitContribute` object from my metadata configuration fixes this, so it's very likely related to that.

In my case I'm storing my global metadata in a separate JSON file, referencing it like this:

```
"globalMetadataFiles": [
  "docfx.global.json"
]
```

Here's the "offending" object:

```
"_gitContribute": {
  "repo": "https://github.com/<user>/<repo>.git",
  "branch": "master",
  "path": "Docs/specs"
}
```

**Comment by Dids** [comment]
Here's my folder structure, in case it matters:

```
(root)
- Project.sln
  - Project
    - Project.csproj
    - *.cs
  - Docs
    - docfx.json
    - docfx.global.json
    - _site
```

**Comment by Dids** [comment]
I'd additionally like to point out that I had to use `globalMetadataFiles` instead of `globalMetadata` because the latter didn't work at all. No errors, but none of the settings/overrides were being applied.

**Comment by superyyrrzz** [comment]
@Dids I tried your steps but cannot repro. Can you provide a sample project?
Note that I'm testing under Windows, not Mac. Not sure whether the platform matters.

**Comment by Dids** [comment]
@superyyrrzz I just tried to create a minimal sample project, but couldn't seem to replicate it. I can, however, still replicate it in a single "real" project.

Would it be possible to email you a zipped copy of the project? Since it's a private/client project, I'd rather not post a link to it publicly here.

**Comment by superyyrrzz** [comment]
It's fine for me. You can email to renzeyu@microsoft.com

**Comment by Dids** [comment]
Sorry for the delay. Just sent the email.

**Comment by superyyrrzz** [comment]
It's a bug in DocFX. `_gitContribute` is of `Dictionary` when set in `globalMetadata`, while it's `JObject` when set in `globalMetadataFile`, which breaks the following steps.
I've create a PR to fix this. For now, A quick workaround for your project is to move `_gitContribute` to `docfx.json`'s `globalMetadata` section.

**Comment by Dids** [comment]
Thank you very much! The workaround sounds fine too, just glad it turned out to be a bug, so I know I’m not going crazy.

--
Pauli Jokela, Didstopia
