### ISSUE TITLE
PDF generation does not work

### ISSUE THREAD

**Issue by fsdthnk** [dotnet/docfx#1866]
### Title
PDF generation does not work

### Functional impact
PDF documents cannot be generated.

### Minimal repro steps
1. Set up a project as described in section *Getting Started with DocFX*
2. Install wkhtmltopdf as described in section *Walkthrough Part III: Generate PDF Documentation*
3. Check environment variable PATH whether it contains the path to wkhtmltopdf\bin
3. Confirm that wkhtmltopdf is available and running with e.g. *wkhtmltopdf _site\index.html output.pdf*
=> no error occured and pdf *output.pdf* has been created
4. Run the command *docfx pdf*

### Expected result
a pdf is created

### Actual result
No pdf is created and the following error message is shown:
Error:wkhtmltopdf is a prerequisite when generating PDF. Please install it from https://wkhtmltopdf.org/downloads.html and save the executable folder to %PATH% first. Alternatively you can install it from https://chocolatey.org with `choco install wkhtmltopdf`.

### Further technical details
None

**Comment by fsdthnk** [comment]
The bug reported is probably due to an incorrect configuration in the pdf section of the config file. When running the command *docfx docfx.json* a JsonSerializationException is generated, see
[error_message.txt](https://github.com/dotnet/docfx/files/1142050/error_message.txt)
See also the config file: 
[docfx_pdf.json.txt](https://github.com/dotnet/docfx/files/1142060/docfx_pdf.json.txt)

**Comment by vicancy** [comment]
Hi @fsdthnk your docfx_pdf.json is not in validate JSON format, remove content inside the red region and call `docfx pdf` again.
![image](https://user-images.githubusercontent.com/668244/28148404-13336c98-67b9-11e7-8557-bb854df28d4a.png)

**Comment by fsdthnk** [comment]
Hi vicancy, just did the correction as you proposed, even checked the syntax using this website
(https://jsonformatter.curiousconcept.com/)
However, I got the same error message when executing `docfx pdf docfx.json`
> Error:wkhtmltopdf is a prerequisite when generating PDF. Please install it from https://wkhtmltopdf.org/downloads.html and save the executable folder to %PATH% first. Alternatively you can install it from https://chocolatey.org with `choco install wkhtmltopdf`.

`docfx metadata` runs without errors.
Any advice?

**Comment by vicancy** [comment]
What happens when you type "where wkhtmltopdf" in the same command line you call "docfx pdf"? @fsdthnk

**Comment by fsdthnk** [comment]
Thanks for the hint. There was an error in the path variable. We are one step forward, however there is still a warning message and no pdf is generated, see attached file.
[message.txt](https://github.com/dotnet/docfx/files/1148338/message.txt)

**Comment by vicancy** [comment]
According to the message, "Warning:[PDF]No TOC file is included, no PDF file will be generated.", do you have file `toc.yml` under folder `pdf`?

**Comment by fsdthnk** [comment]
@vicancy Now it works :-)  Thanks for the hint. Find attached the config file used. 
However, the pdf itself looks very plain. It makes sense to follow advises proposed in issue #1882 by FSharpCSharp.
[docfx.json.txt](https://github.com/dotnet/docfx/files/1152908/docfx.json.txt)
