### ISSUE TITLE
Wrong sideaffix-item gets active upon sideaffix-item click

### ISSUE THREAD

**Issue by oyshan** [dotnet/docfx#1875]
### Title
The wrong sideaffix-item gets visually selected/active compared with the sideaffix-item clicked. This usually happens on one of the last sideaffix items when the sideaffix list is of sufficient size.

### Functional impact
The wrong side affix point gets visually selected/active compared with the one clicked. However, the correct sideaffix-item is selected in the url (after hashtag #)

### Minimal repro steps
This can be demonstrated on the official DocFX documentation page.
1. Open https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html
2. Click sideaffix-item '6. A seed project to play with DocFX'

### Expected result
Point 6 in the side affix will be active/visually selected (bold)

### Actual result
Point 7 gets visually active/selected (bold) instead

**Comment by vicancy** [comment]
This is caused by: when 6 is clicked, page scrolls to the bottom. **bottom** means the last one is selected. This is the general behavior of affix, I agree that it can be improved.
