### ISSUE TITLE
DocFX issue with absolute path for json file

### ISSUE THREAD

**Issue by mikemadeja** [dotnet/docfx#1879]
### DocFX issue with absolute path for json file
*It seems you cannot run DocFX from the absolute path*  
I cannot get the absolute path to be executed for docFX, it seems you need to be in the docfx root directory where docfx.exe is located and ensure you have a subfolder in there for the project.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  
1. Setup docfx on E:\docfx or C:\docfx
2. Go to root of the drive, IE E:\
3. Run "E:\docfx\docfx.exe" "E:\docfx\docfx_project\docfx.json" or replace E:\ with C:\

Build failed.
[17-07-15 01:48:21.677]Warning:[ExtractMetadata]No source project or file to process, exiting...
[17-07-15 01:48:21.677]Error:System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '*docfx_project*\obj\.cache\build\1dqtcddp.zjx\1l5hrbl4.opg'.

### Expected result
*What would you expect to happen if there wasn't a bug?*  
DocFX should build

### Actual result
*What is actually happening?*  
DocFX fails to build the site due to not being able to use the absolute path

**Comment by vicancy** [comment]
Unable to repro. Which version of docfx are you using?

**Comment by vicancy** [comment]
Possible duplication with #1951
