### ISSUE TITLE
Swagger Support - Examples do not contain whitespace

### ISSUE THREAD

**Issue by dmccaffery** [dotnet/docfx#188]
@vicancy @hellosnow 

I'm really intrigued by the work being done to support swagger/swagger2 within DocFX and it seems to work well with one exception: The example request/response payloads are emitted without whitespace. It appears as though the examples are encoded and whitespace is stripped. Is this what you're seeing at this point? Is this expected? I realize this is a work-in-progress, but I wanted to make sure I wasn't doing something wrong.

I'm used both 1.5 and the latest dev build 1.6.0-alpha-0053-gf1f2c02 to try this out using the test data you're already using (contacts_swagger2.json).

<img width="1017" alt="swagger-response" src="https://cloud.githubusercontent.com/assets/1803684/13503696/b95b4ca6-e125-11e5-828a-44230f568db0.png">

**Comment by vicancy** [comment]
Oh @dmccaffery , it is expected for now.... We are still working on improving the template for RestAPI.
