### ISSUE TITLE
Missing PDF functions in docFX and a few suggestions from current projects.

### ISSUE THREAD

**Issue by FSharpCSharp** [dotnet/docfx#1882]
The possibilities available so far in doxFX with regard to the PDF generation are, unfortunately, very lean. For the PDF generation to be useful, the following features should be added in any case:

- [x] **1. Logo in header other than first page**

This should be possible with the help of a PDF background template. Then you could easily combine the documentation with the rest. To do this, simply set the background template in the background of the generated PDFs. This can be done with iTextSharp very simply, and without much effort.

- [x] **2. Side numbering at the bottom right or left or centered**

Should be done, if possible, per area (toc), or for the whole document.

- [x] **3. Document title in footer left / center or right**

Possibly also with a PDF background template solvable. Should always be in the same place.

- [x] **4. Page margins: top, bottom, left, right freely definable**

This is very important if the user wants to print the document. The margins, which have been standard so far, are simply too narrow.

- [x] **5. Download link on the homepage, or any underside of the online documentation (cross-reference to the generated PDFs within other templates)**

This would be very cool, if one could refer directly to the generated PDF documentation. Thus, one would not have to merge the documentations in the following, and still adapt manually.

- [x] **6. Table of contents with page numbers.**

The links in the table of contents are clickable, but when you print the generated document, navigation is not really easy.

- [x] **7. Merge the articles into a large one**

An extra page has been created per markdown file. However, not all articles are a whole page long. This means that there may be a lot of void space. Especially when printing, this can be very annoying, because too much paper is consumed. Would here possibly a merge of the Markdown files to a large conceivable?

**Comment by bitbonk** [comment]
> 6. Table of contents with page numbers.

Yes please!

**Comment by yufeih** [comment]
Most of the requests are supported as part of #9343
