### ISSUE TITLE
Differences in html output

### ISSUE THREAD

**Issue by fsdthnk** [dotnet/docfx#1885]
I noticed that there are differences between these two export variants:
(1) Run the command `docfx serve _site`, then in the browser go to 
`http://localhost:8080/api/index.html`
(2) Just double click on `_site/api/index.html`
As one can see in the screenshot below, links marked in red are missed when following variant (2). Any comments about the reason for that?

![api1](https://user-images.githubusercontent.com/30116834/28275608-a8070970-6b14-11e7-9ce2-fe86cd055b93.jpg)

**Comment by vicancy** [comment]
Navbars are Ajax loaded from toc.html in `default` template, you can use template `statictoc` through `docfx build -t statictoc` if you want local file explore behaves exactly the same with hosted webpage.

**Comment by fsdthnk** [comment]
@vicancy That solved the issue. Thank you!
