### ISSUE TITLE
Nothing rendered for invalid cref

### ISSUE THREAD

**Issue by kwaclaw** [dotnet/docfx#1887]
**DocFX Version Used**:  2.21.1

**Steps to Reproduce**:
Build a library project using this class:
```
using Microsoft.Extensions.Configuration;

namespace KdSoft.Configuration.AspNet
{
    /// <summary>
    /// <see cref="IConfiguration"/> related helper and extension routines.
    /// </summary>
    public static class ConfigurationHelpers
    {

    }
}
```

**Expected Behavior**:  Since `cref="IConfiguration"` won't be resolved I would expect the same behaviour as in SandCastle, that is, the summary should read:
  *"IConfiguration related helper and extension routines."*
with the cref value simply rendered as text instead of a link.

**Actual Behavior**:
However, DocFx produces:
  *"related helper and extension routines."*
rendering the unresolved cref as an empty string.

**Comment by roji** [comment]
+1. It's OK to have crefs to unknown external libraries, and these should at least render as normal, unlinked test (but consider style to make it clear it's a code ref). The current behavior generates completely broken text.
