### ISSUE TITLE
Add code snippet features to match features from sphinx literalinclude directive

### ISSUE THREAD

**Issue by danroth27** [dotnet/docfx#189]
When using [Sphinx](https://sphinx-doc.org) to build documentation you can use the [literalinclude](http://www.sphinx-doc.org/en/stable/markup/code.html#includes) directive to include code snippets from a separate file. DocFX flavored markdown supports something similar with [code snippets](http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#code-snippet), but it looks like it is missing a few features that we use heavily in the ASP.NET docs:
- Ability to specify multiple line number ranges and to skip lines:

```rst
.. literalinclude:: example.py
   :lines: 1,3,5-10,20-
```

- Options to display line numbers when the code is rendered and to emphasize specific lines when the code rendered:

```rst
.. literalinclude:: example.rb
   :language: ruby
   :emphasize-lines: 12,15-18
   :linenos:
```

- Ability to dedent the rendered code so that it is correctly aligned with the rest of the content instead of having extra leading whitespace:

```rst
.. literalinclude:: example.rb
   :language: ruby
   :dedent: 4
   :lines: 10-15
```

**Comment by superyyrrzz** [comment]
Support highlight lines in code snippet in 27e88f3ba5bbed7b826325a021aa0cb747f6e9da
