### ISSUE TITLE
Add support for specifying cross references for a specific section or location in a topic

### ISSUE THREAD

**Issue by danroth27** [dotnet/docfx#190]
With the DocFX [cross reference](http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#cross-reference) support it looks like you can easily define links to different docs in your project, which is great! 

We also need to be ability to define cross references to specific places in a doc, like a specific section or a specific label. In [Sphinx](https://sphinx-doc.org) we use the [``:ref:`label-name` ``](http://www.sphinx-doc.org/en/stable/markup/inline.html#cross-referencing-arbitrary-locations) syntax to define these references:

```rst
.. _my-reference-label:

Section to cross-reference
--------------------------

This is the text of the section.

It refers to the section itself, see :ref:`my-reference-label`.
```

We need something similar in DocFX. It would be great if there was even a shorthand for referencing a specific section heading without having to define an explicit label, which is something Sphinx does not have.

**Comment by chenkennt** [comment]
It's already supported. For a heading, you can reference it using its name:

```markdown
# This is a heading

[link](#this-is-a-heading)
```

If you need anchor in other places, use HTML:

```markdown
<a name="this-is-an-anchor"></a>

[link](#this-is-an-anchor)
```

**Comment by danroth27** [comment]
Right, but I was specifically referring to cross referencing a location in a separate doc. The `:ref:` syntax can point to any label in any doc in the set of docs being built.

**Comment by chenkennt** [comment]
You can also cross reference in DocFX, like this:

```markdown
<xref:topic_id#anchor_name>
```

**Comment by danroth27** [comment]
Ah, that sounds like just what we need. I'll try it out, but it sounds like you guys can close this issue.

**Comment by chenkennt** [comment]
Currently doesn't work, need some fix.

**Comment by danroth27** [comment]
@shirhatti

**Comment by superyyrrzz** [comment]
Hi @danroth27 , `<xref:topic_id#anchor_name>` is now supported in DocFX prerelease version. You can try it.
