### ISSUE TITLE
Files not found when referencing the config file with a relative path

### ISSUE THREAD

**Issue by arxae** [dotnet/docfx#1905]
**DocFX Version Used**:  2.21.1.0

**Template used**: Default

**Steps to Reproduce**:

1. docfx init (use defaults values for everything)
2. cd docfx_project
3. docfx docfx.json (gives some warnings)
4. cd ..
5. docfx .\docfx_project\docfx.json <- Exceptions happen here

**Expected Behavior**: Documentation builds

**Actual Behavior**: Various exceptions are thrown

I have attached a output of all the stuff i have done in powershell. Also did a docfx --version at the end for good measure.
[output.txt](https://github.com/dotnet/docfx/files/1168628/output.txt)

**Comment by vicancy** [comment]
Thanks for reporting the issue, repro-ed.
