### ISSUE TITLE
ImproveThisDoc path wrong

### ISSUE THREAD

**Issue by MHDante** [dotnet/docfx#1909]
**DocFX Version Used**: 
2.21.2.0
**Template used**: (`default` or `statictoc` or contain custom template)
default

The `path` property on the `_gitContribute` object in `globalMetadata` doesn't work. 
I had to use `apiSpecFolder`

perhaps this is desired, if so, please update the docs:

http://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html?q=_gitcontribu#32-properties-for-build

**Comment by superyyrrzz** [comment]
Thanks @MHDante , you are right. `path` should be `apiSpecFolder`. It's a bug in document.
