### ISSUE TITLE
Emojis in Markdown do not show up correctly in the generated html

### ISSUE THREAD

**Issue by muqeet-khan** [dotnet/docfx#191]
I am trying to use a simple `:wrench:` :wrench: emoji in a markdown and the generated html does not show the emoji and shows the literal `:wrench:` 

I was essentially trying to use the `not completed` like wrench that docfx uses on its site.

**Comment by chenkennt** [comment]
We do not support emoji in markdown, for this wrench icon, you can use unicode: `&#128295;` -> 	&#128295;
