### ISSUE TITLE
Flawed Navbar with long titles

### ISSUE THREAD

**Issue by xxcuratorxx** [dotnet/docfx#1914]
**DocFX Version Used**: 2.21.2

**Template used**: statictoc

**Steps to Reproduce**:
Create website with docfx.json

```
{  
  "build": {
    "content": [
      {
        "files": [ "*.{md,yml}"]
      }
    ],
    "dest": "_site",
    "template": [
      "statictoc"
    ]
  }
}
```
test.md
```
Hello world
```

and 

toc.yml
```
- name: VeryLongVeryLongEntry1
  href: test.md
- name: VeryLongVeryLongEntry2
  href: test.md
- name: VeryLongVeryLongEntry3
  href: test.md
- name: VeryLongVeryLongEntry4
  href: test.md
```
All in the same path.

**Expected Behavior**: Nice Navbar in each responsive design

**Actual Behavior**: Flawed navbar in medium design (emptry line)

**Comment by Benzelona** [comment]
push.

**Comment by xxcuratorxx** [comment]
Hi again,
are there any updates planed for this bug? The same occurs when there are some more entries, where their names are not very long.

That makes the html unusable, since the empty line overwrites the navigation bar of programming references

**Comment by xxcuratorxx** [comment]
However, since this seems not to be fixed that early: Are there any plans to have a 2nd level navbar?

**Comment by xxcuratorxx** [comment]
Any Update on the?

**Comment by yufeih** [comment]
The navbar experience has been improved in the new modern template.
