### ISSUE TITLE
Included code snippets end up indented too far

### ISSUE THREAD

**Issue by godefroi** [dotnet/docfx#192]
### Title
Included code snippets end up indented too far

### Functional impact
When code is imported from code files into DFM files using the `[!code-...` syntax,  no indenting is removed from the beginning of the line. This results in code snippets that can potentially be shifted far to the right in the rendered output.

### Minimal repro steps
Create a code file with normally-indented code:
```
using System;

namespace mynamespace
{
    class myclass
    {
        public void Main()
        {
            // <mytag>
            Console.WriteLine("information");
            // </mytag>
        }
    }
}
````
Include a snippet of this file into a DFM file:
````
[!code-csharp[mysection](mycodefile.cs?name=mytag)]
````

### Expected result
Ideally, this inclusion would result in a nice, left-aligned code snippet:
````
Console.WriteLine("information");
````

### Actual result
Instead, the snippet is rendered at the same level of indent as the original code:
````
            Console.WriteLine("information");
````
When the original code was highly indented and/or includes long lines, the rendered output is far from ideal, and can be quite difficult to understand.

**Comment by Huachao** [comment]
Hi @godefroi , thanks so much for your suggestion and fix. We have fixed this issue in commit 2077f527486d8963384db4a2217347c048e9fae7.
