### ISSUE TITLE
New VSCode extension

### ISSUE THREAD

**Issue by tintoy** [dotnet/docfx#1928]
Hi.

To scratch my own itch, I built an [extension for VS Code](https://github.com/tintoy/docfx-assistant#readme) to provide pick-lists of available topic UIDs for insertion while authoring Markdown content. I am working towards making it available on the VS Marketplace (it's free in case that wasn't obvious), but I wanted to first check with you guys that I'm not stepping on anybody's toes by doing so :-)

I'm open to making changes if required, or am happy to contribute my work if you guys are already working on your own extension, BTW.

**Comment by hellosnow** [comment]
@tintoy we have [DocFXPreview vs code extension](https://marketplace.visualstudio.com/items?itemName=docfxsvc.DocFXPreview) to preview docfx, and we have plan to remove `preview` in the title of the extension, to make it as docfx extension. Therefore, we suggest to contribute your cool functionality on the extension code base https://github.com/dotnet/docfx/tree/dev/tools/VscPreviewExtension. 😄

**Comment by hellosnow** [comment]
@tintoy I just went through the issues, for the todo item https://github.com/tintoy/docfx-assistant/issues/4, I think @hechaochao is delivering the xref service and extension, which may help to resolve the xref.

**Comment by tintoy** [comment]
Thanks! That'll be pretty useful I think.

The extension needs a little refactoring before I contribute it (will need to move the DocFX-specific stuff out into a separate package that doesn't depend on VSCode) so I will track that in tintoy/docfx-assistant#6 and keep you posted on the progress :)

If you have any comments on extension design or other implementation details, feel free to chime in on that issue so we can discuss.

**Comment by vicancy** [comment]
Opened 2 issues to track the followup plan.
https://github.com/dotnet/docfx/issues/1932
https://github.com/dotnet/docfx/issues/1933

**Comment by tintoy** [comment]
FYI, I'm building an NPM package for parsing a DocFX project:

```typescript
import { DocFXProject, TopicMetadata, readContentMetadata } from 'docfx-project';

const project: DocFXProject = DocFXProject.load(projectFile);

// Respects include / exclude.
const contentFiles: string[] = await project.getContentFiles('.md', '.yml');

const contentMetadata: TopicMetadata[] = [];
for (const contentFile of contentFiles) {
    const fileMetadata: TopicMetadata[] = await readContentMetadata(contentFile);
    contentMetadata.push(...fileMetadata);
}
```

Most of this already exists as components in my extension but figured it was reusable enough to be useful.
