### ISSUE TITLE
Error extracting metadata for...: Object not set to an instance of an object.

### ISSUE THREAD

**Issue by fraguada** [dotnet/docfx#1944]
**DocFX Version Used**: 2.22.1

**Template used**: `default`

**Steps to Reproduce**:

1. Clone the [Rhino3dmIO_docfx](https://github.com/mcneel/rhinocommon/tree/rhino3dmio_docfx) branch.
2. Open [Rhino3dmIO.csproj](https://github.com/mcneel/rhinocommon/blob/rhino3dmio_docfx/dotnet/Rhino3dmIO.csproj) in Visual Studio 2017. Ensure docfx.console NuGet 2.22.1 package is restored.
3. Build Rhino3dmIO.csproj. Error will be logged.

**Expected Behavior**:
The .csproj builds and docfx builds documentation

**Actual Behavior**:
.csproj builds without docfx. With docfx .csproj does not build, docfx doesn't generate anything, and am getting an error related to metadata extraction with a message saying 

> Object reference not set to an instance of an object

Here is the log:

`{"message":"Config file \"C:\\dev\\github\\mcneel\\RhinoCommonPublic\\dotnet/docfx.json\" is used.","date_time":"2017-08-10T11:33:02.9761644Z","message_severity":"verbose"}
{"message":"Loading project C:/dev/github/mcneel/RhinoCommonPublic/dotnet/Rhino3dmIO.csproj","source":"MetadataCommand.ExtractMetadata","file":"C:/dev/github/mcneel/RhinoCommonPublic/dotnet/Rhino3dmIO.csproj","date_time":"2017-08-10T11:33:03.2421879Z","message_severity":"verbose","correlation_id":"8B277620-A634-4D4A-AF2E-B09DC7DB6EB3.1.1.1"}
{"message":"Completed Scope:MetadataCommand in 7431.5706 milliseconds.","source":"MetadataCommand","date_time":"2017-08-10T11:33:10.5679949Z","message_severity":"info","correlation_id":"8B277620-A634-4D4A-AF2E-B09DC7DB6EB3.1.2"}
{"message":"Error extracting metadata for C:/dev/github/mcneel/RhinoCommonPublic/dotnet/Rhino3dmIO.csproj: Object reference not set to an instance of an object.","date_time":"2017-08-10T11:33:10.5689535Z","message_severity":"error","correlation_id":"8B277620-A634-4D4A-AF2E-B09DC7DB6EB3.2"}
{"message":"Completed in 7436.4121 milliseconds","date_time":"2017-08-10T11:33:10.5698447Z","message_severity":"info","correlation_id":"8B277620-A634-4D4A-AF2E-B09DC7DB6EB3.3"}
`
Any better way to debug this? I guess I could debug docfx and run this project through it?

**Comment by vicancy** [comment]
This error is definitely a bug that we should fix. Thanks for reporting the issue. I will try to repro it later.

**Comment by kgehmlich** [comment]
Any progress on this? I'm getting the same error on my project and have no clue what the cause might be.
