### ISSUE TITLE
Running DocFX from outside the folder that contains `docfx.json` fails

### ISSUE THREAD

**Issue by samangh** [dotnet/docfx#1951]
**DocFX Version Used**: 2.22.2.0

**Template used**: default

**Steps to Reproduce**:

1. Download docfx into `docfx/`
2. `git clone --depth 1 https://github.com/docascode/docfx-seed`
3. Run `docfx/docfx.exe docfx-seed/docfx.json`

**Expected Behavior**:
It should compile cleanly.

**Actual Behavior**:
Running `docfx/docfx.exe docfx-seed/docfx.json` fails with
```
[17-08-12 09:51:12.620]Error:System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: obj/.cache/build/xcoolrhj.hwn/qkff5jed.u7f does not exist
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x000b6] in <a546545b1dc14846b8449241b79b9e7e>:0 
...
```

However, running ` cd docfx-seed; ../docfx/docfx.exe docfx.json` works as expected.

It seems that DocFX is using relative paths in a mismatched way. I think in some  part of the code,  paths are relative to `docfx.json` whilst in other parts the paths are relative to `docfx.json`.

Possibly related to #1879. Build log file attached.

[build-log.txt](https://github.com/dotnet/docfx/files/1220098/build-log.txt)

**Comment by vicancy** [comment]
Code fixed, https://github.com/dotnet/docfx/issues/1905. Will be released on 21th, v2.23
