### ISSUE TITLE
YamlDotNet.Core.SyntaxErrorException

### ISSUE THREAD

**Issue by keydon** [dotnet/docfx#196]
Hey there,

i am getting an error after having generated the metadata but before serving.
Seems like an intermediate yaml-File cannot be parsed.
To bad it doesnt say which one -.-

Running docfx 1.5.2.0

> Info: [Build Document]5 plug-in(s) loaded.
Info: No files are found with glob pattern apidoc/**.md, excluding obj/**,_site/**, under directory "c:\Projekte\shared\branches\release\dlls\4.5.146\docs"
Info: No files are found with glob pattern images/**, excluding obj/**,_site/**, under directory "c:\Projekte\shared\branches\release\dlls\4.5.146\docs"
Error: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> YamlDotNet.Core.SyntaxErrorException: (Line: 85, Col: 14, Idx: 2869) - (Line: 85, Col: 15, Idx: 2870): While scanning for the next token, find character that cannot start any token.
   bei YamlDotNet.Core.Scanner.FetchNextToken()
   bei YamlDotNet.Core.Scanner.FetchMoreTokens()
   bei YamlDotNet.Core.Scanner.InternalMoveNext()
   bei YamlDotNet.Core.Parser.GetCurrentToken()
   bei YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   bei YamlDotNet.Core.Parser.MoveNext()
   bei YamlDotNet.Core.EventReader.Allow[T]()
   bei YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.DeserializeHelper[TItem](EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, ICollection`1 result)
   bei (EventReader , Type , Func`3 , Object )
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(EventReader reader, Type type)
   bei Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input)
   bei Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
   bei Microsoft.DocAsCode.EntityModel.Plugins.ManagedReferenceDocumentProcessor.Load(FileAndType file, ImmutableDictionary`2 metadata)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.Load(IDocumentProcessor processor, ImmutableDictionary`2 metadata, FileMetadata fileMetadata, FileAndType file)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   bei System.Collections.Immutable.ImmutableList`1.FillFromEmpty(IEnumerable`1 items)
   bei Microsoft.DocAsCode.EntityModel.Builders.HostService.LoadCore(IEnumerable`1 models)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.<>c__DisplayClass26_0.<GetInnerContexts>b__11(IGrouping`2 item)
   bei System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   bei System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   bei System.Linq.Parallel.SpoolingTaskBase.Work()
   bei System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelberwachung ---
   bei System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   bei System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   bei System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.Build(DocumentBuildParameters parameters)
   bei Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory)
   bei Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
   bei Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
   bei Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   bei Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Interne Ausnahme #0) YamlDotNet.Core.SyntaxErrorException: (Line: 85, Col: 14, Idx: 2869) - (Line: 85, Col: 15, Idx: 2870): While scanning for the next token, find character that cannot start any token.
   bei YamlDotNet.Core.Scanner.FetchNextToken()
   bei YamlDotNet.Core.Scanner.FetchMoreTokens()
   bei YamlDotNet.Core.Scanner.InternalMoveNext()
   bei YamlDotNet.Core.Parser.GetCurrentToken()
   bei YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   bei YamlDotNet.Core.Parser.MoveNext()
   bei YamlDotNet.Core.EventReader.Allow[T]()
   bei YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.DeserializeHelper[TItem](EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, ICollection`1 result)
   bei (EventReader , Type , Func`3 , Object )
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(EventReader reader, Type type)
   bei Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input)
   bei Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
   bei Microsoft.DocAsCode.EntityModel.Plugins.ManagedReferenceDocumentProcessor.Load(FileAndType file, ImmutableDictionary`2 metadata)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.Load(IDocumentProcessor processor, ImmutableDictionary`2 metadata, FileMetadata fileMetadata, FileAndType file)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   bei System.Collections.Immutable.ImmutableList`1.FillFromEmpty(IEnumerable`1 items)
   bei Microsoft.DocAsCode.EntityModel.Builders.HostService.LoadCore(IEnumerable`1 models)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.<>c__DisplayClass26_0.<GetInnerContexts>b__11(IGrouping`2 item)
   bei System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   bei System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   bei System.Linq.Parallel.SpoolingTaskBase.Work()
   bei System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   bei System.Threading.Tasks.Task.Execute()<---

Build failed.
Error: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> YamlDotNet.Core.SyntaxErrorException: (Line: 85, Col: 14, Idx: 2869) - (Line: 85, Col: 15, Idx: 2870): While scanning for the next token, find character that cannot start any token.
   bei YamlDotNet.Core.Scanner.FetchNextToken()
   bei YamlDotNet.Core.Scanner.FetchMoreTokens()
   bei YamlDotNet.Core.Scanner.InternalMoveNext()
   bei YamlDotNet.Core.Parser.GetCurrentToken()
   bei YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   bei YamlDotNet.Core.Parser.MoveNext()
   bei YamlDotNet.Core.EventReader.Allow[T]()
   bei YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.DeserializeHelper[TItem](EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, ICollection`1 result)
   bei (EventReader , Type , Func`3 , Object )
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(EventReader reader, Type type)
   bei Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input)
   bei Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
   bei Microsoft.DocAsCode.EntityModel.Plugins.ManagedReferenceDocumentProcessor.Load(FileAndType file, ImmutableDictionary`2 metadata)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.Load(IDocumentProcessor processor, ImmutableDictionary`2 metadata, FileMetadata fileMetadata, FileAndType file)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   bei System.Collections.Immutable.ImmutableList`1.FillFromEmpty(IEnumerable`1 items)
   bei Microsoft.DocAsCode.EntityModel.Builders.HostService.LoadCore(IEnumerable`1 models)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.<>c__DisplayClass26_0.<GetInnerContexts>b__11(IGrouping`2 item)
   bei System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   bei System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   bei System.Linq.Parallel.SpoolingTaskBase.Work()
   bei System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelberwachung ---
   bei System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   bei System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   bei System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.Build(DocumentBuildParameters parameters)
   bei Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory)
   bei Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
   bei Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
   bei Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   bei Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Interne Ausnahme #0) YamlDotNet.Core.SyntaxErrorException: (Line: 85, Col: 14, Idx: 2869) - (Line: 85, Col: 15, Idx: 2870): While scanning for the next token, find character that cannot start any token.
   bei YamlDotNet.Core.Scanner.FetchNextToken()
   bei YamlDotNet.Core.Scanner.FetchMoreTokens()
   bei YamlDotNet.Core.Scanner.InternalMoveNext()
   bei YamlDotNet.Core.Parser.GetCurrentToken()
   bei YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   bei YamlDotNet.Core.Parser.MoveNext()
   bei YamlDotNet.Core.EventReader.Allow[T]()
   bei YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.DeserializeHelper[TItem](EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, ICollection`1 result)
   bei (EventReader , Type , Func`3 , Object )
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
   bei Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(EventReader reader, Type type)
   bei Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input)
   bei Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
   bei Microsoft.DocAsCode.EntityModel.Plugins.ManagedReferenceDocumentProcessor.Load(FileAndType file, ImmutableDictionary`2 metadata)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.Load(IDocumentProcessor processor, ImmutableDictionary`2 metadata, FileMetadata fileMetadata, FileAndType file)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   bei System.Collections.Immutable.ImmutableList`1.FillFromEmpty(IEnumerable`1 items)
   bei Microsoft.DocAsCode.EntityModel.Builders.HostService.LoadCore(IEnumerable`1 models)
   bei Microsoft.DocAsCode.EntityModel.Builders.DocumentBuilder.<>c__DisplayClass26_0.<GetInnerContexts>b__11(IGrouping`2 item)
   bei System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   bei System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   bei System.Linq.Parallel.SpoolingTaskBase.Work()
   bei System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   bei System.Threading.Tasks.Task.Execute()<---

There are totally 0 Warning(s), 1 Error(s)

**Comment by simonmurdock** [comment]
Are you using the latest DocFX? That error message looks old.

**Comment by keydon** [comment]
just edited my initial report with the version-info: docfx 1.5.2.0
Should be the latest, right?

**Comment by vicancy** [comment]
Hi @keydon , could you provide the generated metadata files?

**Comment by jozefizso** [comment]
I ran docfx 1.5.2.0 against Lucene.Net project.  `build` command ended with the same error `YamlDotNet.Core.SyntaxErrorException: (Line: 23, Col: 14, Idx: 733) - (Line: 23, Col: 15, Idx: 734): While scanning for the next token, find character that cannot start any token.`.

https://gist.github.com/jozefizso/ce846e4180fa2f2a0686

**Comment by jozefizso** [comment]
The issue is with a NULL character in the YAML file [Lucene.Net.Analysis.Tokenattributes.IFlagsAttribute.yml](https://gist.github.com/jozefizso/ce846e4180fa2f2a0686#file-lucene-net-analysis-tokenattributes-iflagsattribute-yml)

![screenshot_031116_105918_pm](https://cloud.githubusercontent.com/assets/287778/13716687/e200577e-e7dc-11e5-8ee8-742283224477.jpg)

**Comment by jozefizso** [comment]
It was fixed in YamlDotNet on Mar 7, 2016 so it's not release yet in v3.8.0 https://github.com/aaubry/YamlDotNet/pull/169/files

**Comment by vicancy** [comment]
Should have been fixed in latest version v1.6.1. Hi @jozefizso  and @keydon ,could you have a retry?

**Comment by jozefizso** [comment]
The `summary` attribute is generated in a different format now, so there are no `NUL` characters in yaml files generated from lucenenet source code.

This solved the issue for me.

**Comment by keydon** [comment]
Sorry it took me so long for retest.
Issue ist fixed for me too now. (tested with version 1.6.2)
But i am getting another error now. i will open another issue for that.
