### ISSUE TITLE
Migrating our projects from net46 to netstandard 2.0

### ISSUE THREAD

**Issue by vicancy** [dotnet/docfx#1963]
https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md
https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7
Steps:

- [ ] 1. Upgrade projects to `net461`
- [ ] 2. Update documentation that VS 2017 Preview Update 3 is required
- [ ] 3. Upgrade base projects to `netstardard2.0` one by one

Blockers:
- [ ] 1. `CallContext`
http://www.cazzulino.com/callcontext-netstandard-netcore.html
- [ ] 2. `AppDomain`
https://github.com/dotnet/docfx/issues/138#issuecomment-332336247
- [ ] 3. `Nustache` to .NET standard

**Comment by vwxyzh** [comment]
v3.0?

**Comment by tintoy** [comment]
Hi @vicancy, do you have any particular place you'd prefer that I start? Otherwise, I'm happy to just dive in at the deep end and see where I get up to :)

**Comment by tintoy** [comment]
Work starting [here](https://github.com/tintoy/docfx/tree/feature/netstandard).

**Comment by vicancy** [comment]
@tintoy Looks cool!

**Comment by tintoy** [comment]
A couple of tests are failing, but I'm just checking to see if they actually succeed without these changes :)

**Comment by vicancy** [comment]
@tintoy If you are using VS 15.3 and the tests are Metadata related, it is possibly an env issue with MSBuild, opening All.sln from VS2017 Developer Command can fix it.

**Comment by tintoy** [comment]
Ah yes, thanks - those are the ones that are failing :)
I can probably fix that in another PR, I think (ran into a similar problem on another project).

**Comment by tintoy** [comment]
All good, with your suggested workaround, all tests pass so far. I'll keep going.

**Comment by tintoy** [comment]
Ok, bit of a blocker - all dependencies except Nustache support .NET Standard (project seems to be somewhat dead - jdiamond/Nustache#121). I will see if I can find a compatible alternative (the project owner suggests [stubble](https://github.com/StubbleOrg/Stubble)).

**Comment by tintoy** [comment]
Wow, OK, yak-shaving time. There is _no_ Mustache implementation currently compatible with .NET Standard (any version!). Looks like I'll have to create a .NET Standard port of Nustache (or similar).

Anyone else who'd like to help - now's the time to pitch in :)

**Comment by tintoy** [comment]
Actually, let me see if it'll still run on .NET Standard 2.0 first (I get the usual `NU1701` but it may still work correctly).

**Comment by tintoy** [comment]
Ok, a more serious blocker: dotnet/roslyn#17968. There's currently no `MSBuildWorkspace` for .NET Standard. I might have another poke around the OmniSharp source code to see how hard it would be to create an interim workaround for this.

**Comment by tintoy** [comment]
Have ported everything except CLI, tests, and `Microsoft.DocAsCode.Metadata.ManagedReference` for now. Will have a think about what it would take to make `Microsoft.DocAsCode.Metadata.ManagedReference` work on .NET Standard but it sounds like this library in particular may be a bit trickier to port.

**Comment by tintoy** [comment]
Probably have a solution for `Microsoft.DocAsCode.Metadata.ManagedReference`:

https://gist.github.com/tintoy/76b48591e2a34429c1f5c02556b8b4d2

Essentially, we can use an `AdhocWorkspace` and populate it using the MSBuild engine to examine the project's properties and items; a slightly-less-sophisticated version of what `MSBuildWorkspace` does.

This may not work for _every single_ project out there (e.g. if a project has `<Compile>` items that are added by custom tasks that can only run on the full .NET framework because they're AppDomain-isolated) but it should be fine for 95% of use-cases (chances are, it doesn't work for 100% of projects right now anyway).

@vicancy - before I go any further on this can I get some feedback from you on whether you find this approach acceptable?

**Comment by vicancy** [comment]
@tintoy Sorry for late response. I was on vacation and am back now. I will take a look at it today.

**Comment by tintoy** [comment]
@vicancy no problem, take your time - I've got plenty of other stuff to keep me busy :)

**Comment by vicancy** [comment]
@tintoy Thinking of changing from Mustache to Handlebars, https://www.nuget.org/packages/Handlebars.Net/ suports `.NET standard`

**Comment by tintoy** [comment]
Nice - I totally forgot about Handlebars; how compatible is the syntax between the 2? It's been ages since I used Handlebars, but I seem to remember it's basically a superset of Mustache...

**Comment by vicancy** [comment]
@tintoy It generally compatible with Mustache, the main difference is that it does not search up when context does not found, which is exactly what we expect. There may be other differences that leads to a breaking change (which is my main concern) so I need more time to test before switching. 😢

**Comment by tintoy** [comment]
Yeah, see what you mean, and it looks like there are only a couple of tests for the template processor at the moment. Still, that's the great thing about Xunit theories - write 1 test and then just keep adding test data 😎

**Comment by vicancy** [comment]
@tintoy with the 95% support, is this `<Comiple` case the only case that the AdhocWorkspace does not support?

**Comment by tintoy** [comment]
It can support it, we just have to use `Microsoft.Build.Evaluation`to evaluate the `Compile` item group :) I can whip up an example if you like

**Comment by tintoy** [comment]
(just may not work for _every_ project e.g. the exceptions listed above)

**Comment by tintoy** [comment]
@vicancy - [this](https://gist.github.com/tintoy/76b48591e2a34429c1f5c02556b8b4d2#file-program-cs-L75-L92) demonstrates evaluating the `<Compile/>` items and adding them to the workspace.

**Comment by vicancy** [comment]
Hi @tintoy 

* Do you think it would be better to add a comprehensive test suites to docfx project before we moving to `AdhocWorkspace`, so that we can have a thorough idea what it supports and what is not, as similar to the test cases in Omnisharp? https://github.com/OmniSharp/omnisharp-roslyn/tree/master/test-assets/test-projects

* Another thing I am doing is investigating the possibility to migrate to `Handlebars` however blocked, as `Handlebars.Net` does not support such syntax as Mustache do, and does not implement what `handlebars.js` claims to support as configurable to *look context up*. https://stackoverflow.com/questions/10555820/what-are-the-differences-between-mustache-js-and-handlebars-js
```
{{#summary}}
{{summary}}
{{/summary}}
```
So I don't have a decent solution for Nustache project migrating to `netstardard` .. 😿 any idea?

cc @vwxyzh @superyyrrzz

**Comment by tintoy** [comment]
> Do you think it would be better to add a comprehensive test suites to docfx project before we moving to `AdhocWorkspace`

Yep, I agree this would be very worthwhile :)

As for Nustache, we might need to wind up working (or working with someone) to port an existing implementation?

**Comment by tintoy** [comment]
(I have a couple of projects I use for testing MSBuild Project Tools that we can use as well)

**Comment by tintoy** [comment]
Nustache looks like it would be pretty easy to port, BTW.

**Comment by tintoy** [comment]
@vicancy - which bits of Nustache are used by DocFX? I just ported `Nustache.Core`, `Nustache.Compilation`, and `Nustache.Core.Tests` to `netstandard2.0` / `netcoreapp2.0` in less than 15 minutes and they're fine apart from a small fraction of the unit tests that rely on a library ([DynamicExpresso](https://github.com/davideicardi/DynamicExpresso/issues/48)) that itself has not been ported to `netstandard`.

**Comment by tintoy** [comment]
No code changes required, BTW, except to the unit tests (upgraded to NUnit 3, so some attribute / property names in the NUnit framework have changed).

**Comment by tintoy** [comment]
BTW, around 4 (out of 285) of the Nustache unit tests don't pass, **but** they don't pass in the original project either. I had to disable one test because it alters a static global that breaks around 20 other tests.

If I can get you a set of packages or a copy of the ported code would you be able to see if it works when plugged into existing DocFX tests?

**Comment by vicancy** [comment]
@tintoy we are using `Nustache.Core`. I created a https://github.com/jdiamond/Nustache/issues/129 asking them about the plan, looks like that project is silent since Oct 10, 2016

**Comment by vicancy** [comment]
We can test it with a package of ported Nustache.Core

**Comment by tintoy** [comment]
Ok I'll create a myget feed with packages you can use to test.

**Comment by tintoy** [comment]
@vicancy - you can pull from https://www.myget.org/F/nustache-netstandard/api/v3/index.json (built against netstandard2.0).

**Comment by Romanx** [comment]
@tintoy If you'd like to open a pull request on Nustache with your changes i'd be happy to look them over and get an official release out

**Comment by tintoy** [comment]
Thanks @Romanx :)

I may need to first submit a PR to an upstream project ([DynamicExpresso](https://github.com/davideicardi/DynamicExpresso/issues/48)) used by some of your tests since that doesn't support .NET Standard yet either. But as soon as I can get that done I'll submit the PR. In the meanwhile I can at least fork the original repo for Nustache and apply my changes there (at the moment it's all in a local repo only).

**Comment by tintoy** [comment]
Ok - initial port is sitting in https://github.com/tintoy/Nustache/tree/feature/netstandard. Would you mind having a poke-around the project to see what you think before I open a PR, @Romanx?

There are a couple of tests (around Sections) that fail, but as far as I can tell, they failed before the port, too (had to upgrade to a more recent version of NUnit, among other changes).

**Comment by Romanx** [comment]
@tintoy I'll have a look later today and see whats up with those tests.

**Comment by Romanx** [comment]
@tintoy I just checked out the repo. Seemed to work when I ran all the tests. Which are you finding don't seem to work?

**Comment by tintoy** [comment]
@Romanx - was that on the `feature/netstandard` branch? These ones fail or are inconclusive / skipped for me:

![failing tests](https://user-images.githubusercontent.com/1646284/32394000-c5650d52-c12f-11e7-98c9-4db77d7df805.jpg)

**Comment by Romanx** [comment]
@tintoy it's quite probably I derped and wasn't on the right branch. Let me confirm again 👍

**Comment by Romanx** [comment]
@tintoy I've worked out what the change was that caused the test failures. One is that the changing to use Json.Net returns the object in a different format to the `JavascriptSerializer` and the other is that originally it was pulling the data from the submodule specs. After refactoring the folder structure the pathing was off so you added the specs to the repo which are now different to the submodule which is where the "new" failure come from as the submodule hasn't been updated in awhile.

I'm pretty sure i've got a fix for the object format and i'm just working on regenerating the strongly typed objects from the spec, Would you like me to open a pull request to your repo when i'm done?

**Comment by tintoy** [comment]
@Romanx - thanks, that'd be awesome!

**Comment by vicancy** [comment]
Hi @Romanx Any progress 😄 ?

**Comment by vicancy** [comment]
Hi @tintoy I'd like to move forward with the `AdhocWorkspace` approach. Theoretically it can resolve #1752 & #138 if I am understanding correctly, is it? And after this approach, I plan to setup some CI to test it under different environment. 
It would be fantastic if you could create an PR with this approach. 😄

**Comment by tintoy** [comment]
Ok - I'm about to go camping for the weekend but I'll get onto it early next week :)

**Comment by Romanx** [comment]
@vicancy We're having issues with the changed tests not working on @tintoy's environment and working on mine. Hoping to find some time this weekend to get to it

**Comment by tintoy** [comment]
@vicancy have a look at 6864ff239daac7bbc54c545a07811c112df182da - that should give you an idea of the scope of changes I have to make (it compiles but I haven't tried any of the tests yet).

**Comment by tintoy** [comment]
Actually, I'm thinking I might create extension methods for `AdhocWorkspace` to emulate the old OpenProjectAsync APIs. What do you reckon?

**Comment by tintoy** [comment]
Turns out `AdhocWorkspace` is mutable and therefore may not be thread-safe. Will investigate :)

**Comment by tintoy** [comment]
Ok turns out it's thread-safe.

**Comment by tintoy** [comment]
@vicancy would you mind pulling down the latest code from my fork and running the tests? There are a couple I don't understand well enough to work out why they are failing... It's the `feature/netstandard` branch.

**Comment by vicancy** [comment]
@tintoy Sure, I will take a look

**Comment by vicancy** [comment]
Hi @tintoy Can build pass with the `feature/netstandard` branch? Mine can't pass build, looks like `System.Runtime.Remoting.Lifetime;` is not available in `netstandard`.
![image](https://user-images.githubusercontent.com/668244/33367600-22ba5c24-d52a-11e7-9b4d-303eeb7b4cb3.png)

**Comment by tintoy** [comment]
Which project was that? I didn't see any build errors but I was just running tests from within VS. I'll have a look at that first thing tomorrow, should be easy to fix either way.

**Comment by tintoy** [comment]
I haven't tried porting the main executable yet, only the libraries it depends on. The exe will take some more work because it currently relies on Appdomain but I do have a proposed design that will work cross-platform. In the meanwhile, would you mind trying to run the unit tests ignoring that executable build error?

**Comment by tintoy** [comment]
BTW, am I correct in assuming that use of Appdomains is mainly to control base path for loading assemblies? If so, `AssemblyLoadContext` is the replacement.

**Comment by vicancy** [comment]
@tintoy `AppDomain` is to isolate assemblies loaded from `plugins`. We are thinking of creating a new process instead.

**Comment by tintoy** [comment]
Yep that'd be the way :)

They can communicate over STDOUT / STDIN (have code that does this in an
LSP language service that might be helpful). Were you able to run the tests
if you ignore the build error in that project?

**Comment by vicancy** [comment]
@tintoy I changed `docfx` and `docfx.test` projects back to use `base.props` and can pass build now. I am running test and meet some runtime assembly loading errors. I am looking into it.

**Comment by tintoy** [comment]
BTW, here is one way to use an external process to handle assembly loading:

https://github.com/tintoy/msbuild-project-tools-server/tree/master/src/LanguageServer.TaskReflection

Called from here:
https://github.com/tintoy/msbuild-project-tools-server/blob/master/src/LanguageServer.SemanticModel.MSBuild/MSBuildTaskScanner.cs

**Comment by vicancy** [comment]
Hi @tintoy I also meet several kind of ut failures with your changes. However that branch is quite behind the latest branch and contains a lot of changes. I'd like to make small moves step by step for easy debugging and code review, so I am cherry-picking your changes and sending out PR for every commit.

**Comment by tintoy** [comment]
@vicancy - I recently stumbled across [Buildalyzer](https://github.com/daveaglick/Buildalyzer), which seems to have fairly full-featured [support](https://github.com/daveaglick/Buildalyzer#roslyn-workspaces) for building a Roslyn `AdhocWorkspace` from project files in most formats:

![image](https://user-images.githubusercontent.com/1646284/34549429-abfc6ede-f15c-11e7-81ff-1afb1b9c4d06.png)

Might be worth considering?

**Comment by vicancy** [comment]
Hi @tintoy thank you for the info, I will take a look. With a first glance, it looks like also dependent on `msbuild.dll` to load and parse the project, so I am now a little confused why we not use `MSBuildWorkspace`, it is from https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.Common/ and has a netstardard1.3 version...

**Comment by tintoy** [comment]
I think `MSBuildWorkspace` is in the package `Microsoft.CodeAnalysis.Workspaces.Desktop`, which does not target .NET standard (yet)?

**Comment by tintoy** [comment]
`AdhocWorkspace` is in `Microsoft.CodeAnalysis.Workspaces.Common` though.

**Comment by vicancy** [comment]
@tintoy Oh yes, `netstardard1.3` does not contain `Microsoft.CodeAnalysis.Workspaces.Desktop` assembly

**Comment by superyyrrzz** [comment]
Close as v2 is not likely to support it. v3 will.
