### ISSUE TITLE
docfx metadata fails after installing Visual Studio 2017 Update 15.3

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#1969]
I just installed  Visual Studio 2017 15.3 and now I cannot run `docfx metadata` anymore because I get the following error:

> [17-08-16 12:22:20.437]Warning:[ExtractMetadata]Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\foo\bar\bar.csproj' with message: The tools version "15.0" is unrecognized. Available tools versions are "14.0", "2.0", "3.5", "4.0".  C:\foo\bar\bar.csproj

The interseting part here is that my csproj file does not even speficy version 15:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
```

If I change it to `ToolsVersion="14.0` it works, but I can't change the tools version for now. And if I were to change it, I would like to change it to 15, wich does not work due to the above error.

**DocFX Version Used**:  2.22.2.0

**Comment by bitbonk** [comment]
He seems to have the same probem: http://www.michalkomorowski.com/2017/04/why-i-hate-roslyn-even-more.html

**Comment by vicancy** [comment]
I think I should revert https://github.com/dotnet/docfx/pull/1735, It is not a good idea to contain a compiler inside docfx... otherwise every time VS updates, docfx has to update the compiler accordingly.

**Comment by vicancy** [comment]
Hi @bitbonk does the error only happen to **empty** project or every project?

**Comment by Sunzhuokai** [comment]
@vicancy every project

**Comment by vicancy** [comment]
@Sunzhuokai Thanks, only `Visual Studio 2017 15.3` installed or other versions are also installed?

**Comment by Sunzhuokai** [comment]
`14.0` is available if  `Visual Studio 2015`  installed，if only `Visual Studio 2017 15.3` installed,the avaliable values are ` "2.0", "3.5", "4.0"`. may be it is related to this https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0

**Comment by vicancy** [comment]
Hi @Sunzhuokai Could you try 2.22.3 to see if it solves the issue, I updated Compiler to 2.3.1

**Comment by Sunzhuokai** [comment]
@vicancy  not work

**Comment by vicancy** [comment]
Hi @Sunzhuokai what does `works in vs` mean?

**Comment by Sunzhuokai** [comment]
@vicancy `docfx.console`

**Comment by Sunzhuokai** [comment]
just work once, then fail

**Comment by bitbonk** [comment]
2.22.3 fixes this problem! Thank you for the quick fix!

Still this problem was totally weird:
- I have VS 2010 and VS2017 installed.
- Toolversion in the csproj is 12, which is VS 2013, which I do not have installed
- docfx/msbuild wants to use 15, which is VS2017 which I *do* have installed, but it fails to build
- when I set it Toolversion in csproj 14, which is VS 2015, which I do *not* have it installed, it works

What a clusterf**** 😱

**Comment by bitbonk** [comment]
@vicancy 
> I think I should revert #1735, It is not a good idea to contain a compiler inside docfx... otherwise every time VS updates, docfx has to update the compiler accordingly.

Can you explain a bit more?

Generally it would be desireable to have a compiler embedded in docfx. But AFAIK that would be only useful if  if it is fully sefcontained and does not induce additional external depdencies/prerequisits.

It seems that even though you have a compiler inside docfx, it is still required to have Visual Studio installed (in the right version).

Looking at #1735, all you did is upgrade `Microsoft.CodeAnalysis.*` to 2.2. Why did this change "remove the build tool dependency"?

**Comment by bitbonk** [comment]
Just some wild guesses here:
The nuget pakage Microsoft.Net.Compilers.2.3.1 comes with `Microsoft.CodeAnalysis*` in version *2.3.1-beta1-6191-13*
But afer the upgrade to docfx *2.22.3* `c:\ProgramData\chocolatey\lib\docfx\tools\` contains `Microsoft.CodeAnalysis*`  in version *2.2.0-beta1-61624-04*

Is that the way it supposed to be?

**Comment by vicancy** [comment]
No @bitbonk I did an uncomplete fix 😢 BTW your issue solved? looks like @Sunzhuokai still has the issue

**Comment by vicancy** [comment]
@bitbonk Actually the change is adding *Microsoft.Net.Compillers* package, it is the C# and VB compiler. Yes you are right, our intention is to make docfx selfcontained, but looks like we still dependents on msbuild to resolve projects.

**Comment by bitbonk** [comment]
I still do have the issue (I changed the [text of my comment] (https://github.com/dotnet/docfx/issues/1969#issuecomment-322990069). I accidentally had changed the toolvesion to 14 in my project.

**Comment by vicancy** [comment]
@bitbonk The issue is related to Microsoft/msbuild#2427 DocFX uses MSBuildWorkspace to open projects, which still tries to read the registry for toolversions, however with 15.3 registry entry is removed. I am still looking into the issue and I reproed it locally when I update to 15.3 😢 I update Microsoft.Build packages to 15.3 however does not solve the issue..

**Comment by bitbonk** [comment]
@vicancy https://github.com/Microsoft/msbuild/issues/2427#issuecomment-323051221
> To be clear, you should NOT need to ship MSBuild yourself.

To me that sounds like it might be right to  revert #1735 ??

**Comment by vicancy** [comment]
Gladly we have an easy workaround here before https://github.com/Microsoft/msbuild/issues/2369 is resolved. 
@bitbonk @Sunzhuokai 
Set the following env before calling `docfx metadata`:
```cmd
SET VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
SET VisualStudioVersion=15.0
```
VSINSTALLDIR to where your VS locates

**Comment by Sunzhuokai** [comment]
@vicancy thanks,greate!

**Comment by bitbonk** [comment]
@vicancy *option 2* does not work for, only *option 1*
Can anyone confirm that *option 1* works?
This is the content of my batch file
```batch
SET PATH=%PATH%;%ProgramData%\chocolatey\bin

SET VSINSTALLDIR="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"

SET VisualStudioVersion=15.0

docfx metadata "%~dp0Docs\docfx.json"
```

**Comment by Gallimathias** [comment]
@vicancy Thanks, Option 1 works for me :)

**Comment by fejames** [comment]
So it seems I have the opposite problem.  DocFx 2.23.1.0 gives me the following error when using VS2015 and works with VS2017.

[17-08-30 01:16:39.462]Warning:[MetadataCommand.ExtractMetadata]Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\CMICWORK\FileWorks\DocFx\FileWorks\FileWorks.csproj' with message: The tools version "15.0" is unrecognized. Available tools versions are "14.0", "2.0", "3.5", "4.0".  C:\CMICWORK \FileWorks\DocFx\FileWorks\FileWorks.csproj

Thanks

**Comment by ChristophLindemann** [comment]
Here is a quickfix for TFS OnPrem related to comment [323235324](https://github.com/dotnet/docfx/issues/1969#issuecomment-323235324)

> `SET VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise`
> `SET VisualStudioVersion=15.0`

On TFS OnPrem you can set variables in the build definition, corresponding to the above environment variables.

**Comment by andreycha** [comment]
I'm experiencing the same issue again after [latest upgrade of VS2017 (15.5.0)](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#15.5.0). DocFx version is 2.28.0.

If I use 2.28.1, I get different error:

> [17-12-05 01:30:58.877]Warning:[MetadataCommand.ExtractMetadata]Workspace failed with: [Failure] Msbuild failed when processing the file 'D:\Test\Test.csproj' with message: The imported project "C:\docfx\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\Test\Test.csproj

**Comment by JimBobSquarePants** [comment]
I'm trying to use docfx v2.28.1.0 against Visual Studio Enterprise 15.5 and hitting the following error. Is this related?

```
Build succeeded with warning.
[17-12-08 12:03:54.681]Warning:[MetadataCommand.ExtractMetadata]Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\development\github\ImageSharp\src\ImageSharp\ImageSharp.csproj' with message: Invalid static method invocation syntax: "[MSBuild]::IsRunningFromVisualStudio()". Method '[MSBuild]::IsRunningFromVisualStudio' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CrossTargeting.targets
[17-12-08 12:03:54.682]Warning:[MetadataCommand.ExtractMetadata]Project 'C:\development\github\ImageSharp\src\ImageSharp\ImageSharp.csproj' does not contain any documents.
[17-12-08 12:03:54.683]Warning:[MetadataCommand.ExtractMetadata]No metadata is generated for ImageSharp.
[17-12-08 12:03:54.684]Warning:[BuildCommand.BuildCore.Build Document.CompilePhaseHandlerWithIncremental.TocDocumentProcessor.Prebuild.BuildTocDocument](api/toc.yml)TOC item (Href:index.md ) with empty name found. Missing a name?
        4 Warning(s)
        0 Error(s)

C:\development\github\ImageSharp>docfx -v
docfx 2.28.1.0
```

**Comment by vicancy** [comment]
@JimBobSquarePants Yes, please update to 2.28.2

**Comment by JimBobSquarePants** [comment]
Thanks @vicancy FYI Chocolatey  was installing 2.28.1 3 hours ago.
