### ISSUE TITLE
"Reference Items in Markdown" section in specification is confusing

### ISSUE THREAD

**Issue by svick** [dotnet/docfx#197]
[The section *3.2 Reference Items in Markdown* in the specfication](http://dotnet.github.io/docfx/spec/metadata_format_spec.html#3-2-reference-items-in-markdown) talks about referencing using quotes, but then the note and the example use braces. I don't know which one is correct, but I think it should be consistent.

Also, I'm pretty sure the "Will be rendered to" part is not rendered as intended.

**Comment by chenkennt** [comment]
Fixed in #202

**Comment by svick** [comment]
The "Will be rendered to" part still looks the same as the source.
