### ISSUE TITLE
PDF generation fails with QWin32PrintEngine::initialize: OpenPrinter failed (Access is denied.)

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#1974]
When we run the powershell script that builds a PDF as part of of our CI build in a powershell build task (using TFS 2017 Update 1 on Windows Server 2012 R2). We get the below error that probably comes from wkhtmltopdf:

> 2017-08-17T16:34:27.9078532Z [17-08-17 04:34:27.907]Info:[PDF]Start generating PDF files...
> 2017-08-17T16:35:20.5590973Z ##[error]QWin32PrintEngine::initialize: OpenPrinter failed (Access is denied.)
> 2017-08-17T16:34:27.9078532Z [17-08-17 04:34:27.907]Info:[PDF]Start generating PDF files...
> 2017-08-17T16:35:20.5590973Z ##[error]QWin32PrintEngine::initialize: OpenPrinter failed (Access is denied.)
> 2017-08-17T16:35:20.5590973Z ##[error]QWin32PrintEngine::initialize: OpenPrinter failed (Access is denied.)
> 2017-08-17T16:35:20.5590973Z ##[error]QWin32PrintEngine::initialize: OpenPrinter failed (Access is denied.)
> 2017-08-17T16:35:20.5590973Z ##[error]QWin32PrintEngine::initialize: OpenPrinter failed (Access is denied.)
> ...
> 2017-08-17T16:35:20.6056705Z ##[error]QWin32PrintEngine::initialize: OpenPrinter failed (Access is denied.)
> 2017-08-17T16:35:20.6056705Z [17-08-17 04:35:20.559]Info:[PDF]Docs_pdf.pdf is generated based on pdf/toc.json under folder D:\_work\14\s\Docs\_site_pdf
> 2017-08-17T16:35:20.6056705Z [17-08-17 04:35:20.590]Info:[PDF]Completed Scope:PDF in 52675.0284 milliseconds.
> 2017-08-17T16:35:20.6056705Z [17-08-17 04:35:20.590]Info:Completed in 61662.141 milliseconds
> 2017-08-17T16:35:20.6056705Z Build succeeded with warning.
> ...
> 2017-08-17T16:35:20.6056705Z 	2 Warning(s)
> 2017-08-17T16:35:20.6056705Z 	0 Error(s)
> 2017-08-17T16:35:20.7150409Z ##[error]Process completed with exit code 0 and had 1 error(s) written to the error stream.

The funny thing is that when I run the same script in a powershell window on the server manually, using remote dektop (logged in with same accout under wich the build runs), the pdf is generated correctly. The account runs has full admin rights.

It is a pretty big issue for us if we can't build the PDFs as part of the CI builds.

**DocFX Version Used**:  2.22.3.0
**Template used**: pdf

**Comment by bitbonk** [comment]
For future reference, this is what I did to resolve the issue (I don't now which one of them actually did it):

1. Install wkhtmltopdf using [the official installer](https://wkhtmltopdf.org/downloads.html). Previously I had only installed it via docfx.
2. Reboot the build server
3. rewrote the powershell script to .cmd file and used that instead

**Comment by GuillermoReyesC** [comment]
im a little late, i have this problem :

```
Cannot generate PDF: QWin32PrintEngine::initialize: OpenPrinter failed (El servidor RPC no est? disponible.) (exit code: -1073740791)

   en NReco.PdfGenerator.HtmlToPdfConverter.GeneratePdfInternal(WkHtmlInput[] htmlFiles, String inputContent, String coverHtml, String outputPdfFilePath, Stream outputStream)
   en NReco.PdfGenerator.HtmlToPdfConverter.GeneratePdf(String htmlContent, String coverHtml, Stream output)
   en NReco.PdfGenerator.HtmlToPdfConverter.GeneratePdf(String htmlContent, String coverHtml)
   en NReco.PdfGenerator.HtmlToPdfConverter.GeneratePdf(String htmlContent)
   en Api.......................... línea 65
```
   
   
   mi line 65 is:
   
`var pdfBytes = htmlToPdf.GeneratePdf(Html);`

sometimes make the pdf document and other don't.

i asqued gpt and says:

El error que estás enfrentando parece estar relacionado con la generación de PDF utilizando la biblioteca NReco.PdfGenerator. El mensaje de error indica que no se puede inicializar el motor de impresión QWin32PrintEngine debido a un problema con el servidor RPC.

so i restarted the spool service  :

`C:/ net start spooler`

and now always work, in local
maybe this could help somebody
