### ISSUE TITLE
Investigate removing dependency to msbuild.exe

### ISSUE THREAD

**Issue by vicancy** [dotnet/docfx#1976]
msbuild is used in docfx to parse projects and solutions into `Workspace` for roslyn. Currently we uses `MSBuildWorkspace` which seems fragile and depends on Build Tools to run correctly.

- [ ] 1. Investigate how Omnisharp https://github.com/OmniSharp/omnisharp-roslyn handle projects, is it possible to leverage it
- [ ] 2. Investigate msbuild https://github.com/Microsoft/msbuild/ to see if it is possible to get rid of the local dependencies
- [ ] 3. Enough test case for each env: win, mono, as similar to what omnisharp does https://github.com/OmniSharp/omnisharp-roslyn/tree/master/test-assets

**Comment by tintoy** [comment]
If it helps, I have some code for bundling the MSBuild engine and hosting it inside your own executable. Omnisharp does something similar from memory.

**Comment by vicancy** [comment]
@tintoy Could I take a look at the code?

**Comment by tintoy** [comment]
@vicancy  - sure:

https://github.com/tintoy/msbuild-project-tools-vscode/blob/master/src/LanguageServer.Common/Utilities/MSBuildHelper.cs#L62

You might need to customise it slightly if you're not targeting .NET Core (just change the DotNetInfo bit and use the global MSBuild extensions directory instead).

The important thing is to reference _both_ of these packages in your `.exe` project:

https://github.com/tintoy/msbuild-project-tools-vscode/blob/f9ce78c0c16f6b626c45fed8b279128dec5b1d79/src/LanguageServer/LanguageServer.csproj#L15-L16

(the second one is needed to make MSBuild actually work in-process at runtime)

**Comment by tintoy** [comment]
Also, note the bit about setting environment variables - you have to do this if you want to also be able to load the new-style projects (i.e. ones with `Sdk="Microsoft.NET.SDK"`).

**Comment by vicancy** [comment]
Is the code specific for "15.0" tools version or it applies to all versions of project files? It would be cool if the latter, the code is much simpler than I expected.

**Comment by tintoy** [comment]
It'd need to be customised slightly (but only slightly, you can inspect / register available tools versions on the project collection from memory) - I have an extension that's happy to load both project types and use the tools version as specified in the project.

**Comment by daveaglick** [comment]
@vicancy I also started down this path for [Wyam](https://wyam.io) and ended up writing [Buildalyzer](https://github.com/daveaglick/Buildalyzer). Does something similar to what @tintoy is describing. Maybe between both those projects you'll get some good ideas how to proceed.
