### ISSUE TITLE
Need to add sitemap.xml support

### ISSUE THREAD

**Issue by Aaronontheweb** [dotnet/docfx#1979]
**DocFX Version Used**: any

**Template used**: default

DocFx should really support the ability to produce an XML sitemap; we recently migrated to DocFx on getakka.net and Google is picking up none of our URLs and links.

**Comment by vicancy** [comment]
According to https://www.sitemaps.org/protocol.html, This URL for `loc` must begin with the protocol (such as http). Need to provide the host name when `docfx build` for generating `sitemap.xml`

**Comment by vicancy** [comment]
This feature will release in v2.25.
To enable this feature, in "build" section of "docfx.json", at least specify the following:
```json
"sitemap": {
  "baseUrl": "https://yourhostname.com/"
}
```
To customize more properties, follow https://github.com/dotnet/docfx/blob/dev/Documentation/tutorial/docfx.exe_user_manual.md#324-sitemapoptions

**Comment by Aaronontheweb** [comment]
@vicancy I never followed up on this, but __thank you__ for adding this feature! I really appreciate it.
