### ISSUE TITLE
UTF-8 BOM in markdown file causes failure to parse YAML header

### ISSUE THREAD

**Issue by godefroi** [dotnet/docfx#199]
In a markdown file (say, in articles/), we have the option of having a YAML header to set properties such as uid, title, etc. If the markdown file is saved with a UTF-8 byte order mark (BOM, or "signature"), the YAML header is not parsed, which will cause (for example) cross-references to fail (because the uid is unknown).

**Comment by vicancy** [comment]
Looks good now.
