### ISSUE TITLE
Formating warnings doesent create a error in CI Build tool

### ISSUE THREAD

**Issue by bqstony** [dotnet/docfx#1991]
**DocFX Version Used**: docfx 2.22.0.0

**Template used**: default

**Steps to Reproduce**:

1. create missing link
2. docfx build
3. show output

**Actual Behavior**:
Build succeeded with warning.
[17-08-22 09:41:30.148]Warning:[Build Document.LinkPhaseHandlerWithIncremental.Apply Templates]There is no template processing document type(s): index
        1 Warning(s)
        0 Error(s)

**Expected Behavior**:
I wana check my correct documentation in a CI build. My Team writes the documentation and add it to the pulrequest. Wenn somthing is wrong in the Markdown Doku, showing in the Warning messages, i would prevere a Error. (I use Microsoft Team Foundation Server with a command line call)

I have also tryed to use
```
docfx build --logLevel Warning -l output.log
```
but then i have to evaluate this content of the file.

Some better ideas?

**Comment by vicancy** [comment]
docfx returns with exit code 1 only when error happens.
For your case, how about using `findstr`, for example,
```
docfx build --logLevel Warning | findstr /C:"Build succeeded."
```

%ErrorLevel% is 1 when Error or Warning occurs.

**Comment by bqstony** [comment]
thx. is a possible solution. In Powershell i find the result in $?. True or False :)

**Comment by pascalberger** [comment]
@bqstony If you're willing to use [Cake](http://cakebuild.net/) as build tool, you can use the [DocFx Issue Provider](https://cake-contrib.github.io/Cake.Prca.Website/docs/issue-provider/docfx/examples) for parsing the log file written by DocFx for warnings, and even have them [written to the TFS pull request as comments](https://cake-contrib.github.io/Cake.Prca.Website/docs/usage/basic-usage).

**Comment by pascalberger** [comment]
@lextm Yes, the Cake addin parses the log file, which is error prone. It would also help if there would be a more structured log file format better suited for processing
