### ISSUE TITLE
Unable to convert file extension md to html

### ISSUE THREAD

**Issue by mjangid** [dotnet/docfx#1992]
**DocFX Version Used**: *docfx 2.22.2.0*

**Template used**: *default*

**Steps to Reproduce**:
I have following contents in my md file after build the project below links still in md format

Operation Guide
	[ ustomer] (..\corebanking\customer.md)
	[ ccounts] (..\corebanking\accounts.md)
	[ sers] (..\corebanking\users.md)
	[ unds Transfer] (..\corebanking\fundstransfer.md)

**Expected Behavior**:
these link must converted into html
```
<ul>
<li><a href="..\corebanking\customer.html">Customer</a></li>
<li><a href="..\corebanking\accounts.html">Accounts</a></li>
<li><a href="..\corebanking\users.html">Users</a></li>
<li><a href="..\corebanking\fundstransfer.html">Funds Transfer</a></li>
</ul>

```

**Actual Behavior**:
links are in md format after build the project
```
<ul>
<li><a href="..\corebanking\customer.md">Customer</a></li>
<li><a href="..\corebanking\accounts.md">Accounts</a></li>
<li><a href="..\corebanking\users.md">Users</a></li>
<li><a href="..\corebanking\fundstransfer.md">Funds Transfer</a></li>
</ul>

```

**Comment by vwxyzh** [comment]
@mjangid are these files in your `content` glob?
If not, we will give some warnings like `invalid file link`, and keep the reference unmodified.

**Comment by mjangid** [comment]
@vwxyzh Yes they are and I am not getting any warning.

Build succeeded.
        0 Warning(s)
        0 Error(s)
