### ISSUE TITLE
PDF: add support for a cover page

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#2004]
It would really helpful if there way any way to define custom html for a cover page (that is not the TOC).
It should be put before the TOC and not be included in the page count.
`wkhtmltopdf` supports this with the `cover` object.

**Comment by vicancy** [comment]
Current idea: use naming convention to find cover page `cover.html` in template. Change logic in https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.HtmlToPdf/ConvertWrapper.cs#L133

**Comment by bitbonk** [comment]
Looks good to me. It woould be cool if we could define custom margins just for the cover page. Not sure if wkhtmltopdf support this (https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3635) .

**Comment by bitbonk** [comment]
If (once) wkthmltopdf supports custom margins for the cover page, the easiest way to support this in docfx is to set the magines for the cover page to 0. This would allow the user to fully control the margins via CSS.

**Comment by PredictiveBear** [comment]
Hello there, 

Currently working on a documentation using DocFx and PDF generator. The feature here asked for would be helpful to me. Was it implemented yet ? I see the topic is still set to "open". 

Kind regards.

**Comment by superyyrrzz** [comment]
FYI @partychen

**Comment by icnocop** [comment]
I created PR https://github.com/dotnet/docfx/pull/4342 which implements this feature request.

Basically, if `cover.md` is found in a folder (included as a `Content` file in `docfx.json`), it will be rendered as the cover page.

**Comment by bitbonk** [comment]
Usually (for us) a cover page does not contain a lot of text but is more of a page with special layout, e.g.  A *big* title centered in the middle, a smaller subtitle, a company logo, no footers no headers, maybe a date and copyright notice in a small special font.

So the markdown is not really the problem. The bigger problem is: How can I define that special layout for the cover page alone? How can I have footers or headers with page numbering on all of my pages but not on the cover page (and the ToC pages)?

Does this PR make those things easier or even posible?

**Comment by icnocop** [comment]
PR https://github.com/dotnet/docfx/pull/4342 was merged and so I think this issue should be closed.

`cover.html.primary.tmpl` was added to the default pdf template which is simplistic but can easily be customized.

To use the default cover template, here's a sample `cover.md` that needs to be placed alongside `toc.yml`:
```
---
documentType: cover
---
# My custom cover page title
```

The generated `cover.html' doesn't get passed to wkhtmltopdf using the `cover` parameter.

For new feature requests like having custom margins only for the cover page, it would be best to create a new issue.
