### ISSUE TITLE
Broken @shorthand links do not generate a warning

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#2010]
Broken `@shorthand` links do not generate a warning about an invalid cross reference in the log output of the `docfx` commands.
You think everything built fine, but actually the rendered HTML and PDF have unresolved URLs with the @ sign all over the place.

**DocFX Version Used**:  2.23

**Steps to Reproduce**:

1.  run `docx init` in an empty folder
2. add the following to one of the markdown files
```markdown
please see @Foo.Bar
please see [Baz](xref:Bar.Baz)
```
3. run `docfx`

**Expected Behavior**:
A warning about an invalid cross reference is generated for both links `Foo.Bar` and `Bar.Baz`.
**Actual Behavior**:
Only a warning for `Bar.Baz` is generated.

**Comment by superyyrrzz** [comment]
related issue: #113
As `@` is also widely used in plain text, users experienced a lot of unexpected warnings for `@` in DocFX's early versions. So now we change the behavior to fall back to the original text silently if shorthand xref unresolved.

**Comment by bitbonk** [comment]
It's even [documented](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#shorthand-form).

How about introducing a configuration flag `warnAboutUnresolvedShortLinks` (that defaults to `false`)?

Because in our case we use @ for shorthand links *way* more than in plain text. In fact I couldn't find a single place in our documentation where @ is used in a form that is a valid shorthand syntax and at the same time should not be rendered as such.

**Comment by superyyrrzz** [comment]
Sounds nice. Will add it.

**Comment by bitbonk** [comment]
Any idea when? We constantly get bitten by thinking everything went fine during the build, only to discover some unresolved links on the actual site later.

**Comment by superyyrrzz** [comment]
Sorry, it's not on the priority list for now... A contribution is also welcomed.

**Comment by yufeih** [comment]
Added a dedicated error code `at-uid-not-found` in v3 that controls the log message for `@shorthand`, it is an _info_ message by default, but can be configured as _warning_, _error_, _info_ or _off_ like other error codes
