### ISSUE TITLE
Error extracting metadata. A task was canceled

### ISSUE THREAD

**Issue by novasirius** [dotnet/docfx#2015]
**DocFX Version Used**:  2.23.1
**Visual Studio**: 2017 Version 15.2
**Steps to Reproduce**:

I have added the docfx nuget package to an existing project. DocFX fails to generate metadata for some of the projects and fails with the following error:

2>  Build failed.
2>  [17-08-30 01:20:42.951]Error:Error extracting metadata for E:/TFS/myproject.csproj: Error extracting metadata for project "E:/TFS/myproject.csproj": A task was canceled.
2>  	0 Warning(s)
2>  	1 Error(s)

I downloaded the docfx source and found where it fails:

ExtractMetadataWorker.cs

        private static async Task<ConcurrentDictionary<string, Compilation>> GetProjectCompilationAsync(ConcurrentDictionary<string, Project> projectCache)
{
...
        var compilation = await project.Value.GetCompilationAsync(); // This throws an exception - e = {"A task was canceled."}
....
}

I don't know why this happens but it looks like it is related to the project references. I have tried to isolate and reproduce the problem in another solution that I can share, but until now I've not been able to reproduce it.

**Comment by vicancy** [comment]
Is the project large?

**Comment by novasirius** [comment]
Originally, the solution had 59 projects, but while debugging this issue I removed everything except 4 projects. I now have a DocFX builder project which is configured to generate metadata for ProjectA. ProjectA refers to ProjectB. ProjectB refers to projectC. If i remove the ProjectB->ProjectC reference, the error goes away. While experimenting, I have also tried to remove almost all the functionality of these projects, but still the error is there. This got me to think that there's something fishy in the project files, but until now, I've not seen any obvious reason.

The projects are originally created using VS2010, but my testing is on VS2017.

**Comment by vicancy** [comment]
Is it consistently repro-ed with projectA refers to ProjectB and ProjectB refers to ProjectC? A mimimum repro step would be appreciated.

**Comment by superyyrrzz** [comment]
Seems this is same as #1414. We also have a [test](https://github.com/dotnet/docfx/pull/1420/files#diff-7e88386b73108579509157174d147bb3R37) to cover this case. Does this cover your case?

**Comment by novasirius** [comment]
The bug is similar, but the difference is that it does not throw any exception except a general "A task was canceled" with no innerexception or logging other than "Error extracting metadata".

I even added the following code to check for duplicate project references, which it didn't hit:

`                var dedupedProjectReferences = project.Value.ProjectReferences.Select(x => x.ProjectId).Distinct().ToList();
                if (dedupedProjectReferences.Count != project.Value.ProjectReferences.Count())
                {
                    throw new Exception($"Project {project} cannot be compiled because it contains duplicate project references: {string.Join("|", project.Value.ProjectReferences.Select(x => x.ProjectId))}");
                }
`
