### ISSUE TITLE
No metadata is generated for vb.temp.dll

### ISSUE THREAD

**Issue by PhilipCotan** [dotnet/docfx#2029]
**DocFX 2.23.1.0**: 

**Template used**: `default`

**Steps to Reproduce**:

1. Create a new DocFX project
2. Add a simple VB file in src folder
3. Run `docfx metadata FileName.vb` command under src folder.

**Expected Behavior**:
Generate yml file for the FileName source code
**Actual Behavior**:
Get `Warning:[ExtractMetadata]No metadata is generated for vb.temp.dll` warning message and no YML file.

**Comment by vicancy** [comment]
Hi @PhilipCotan Is there any `public` class in your VB code? only public ones will have metadata generated.

**Comment by PhilipCotan** [comment]
Hi @vicancy Yes, there's one public class in the mentioned file. Anyway, I included the file in a solution, I generated metadata for the *.vbproj file and it worked. It didn't work for the *.vb file only tho.
