### ISSUE TITLE
Document cross reference syntax using file path

### ISSUE THREAD

**Issue by danroth27** [dotnet/docfx#203]
It seems like docfx supports generating links based on file paths like this:

```md
[Another doc](foo/bar/another-doc.md)
```

I couldn't find this documented anywhere though.

@shirhatti

**Comment by chenkennt** [comment]
This is a standard markdown syntax, you can refer to standard [markdown spec](https://daringfireball.net/projects/markdown/syntax#link).

**Comment by danroth27** [comment]
The markdown spec talk about relative links, but I don't see anything out taking a path to a markdown file and turning it into a relative link. I would have expected `[Another doc](foo/bar/another-doc.md)` to go to another-doc.md, not another-doc.html.

**Comment by danroth27** [comment]
It's a nice feature btw. I just think it would be good to document it so folks know about it.

**Comment by chenkennt** [comment]
Makes sense. I'll add something to our markdown spec.

**Comment by chenkennt** [comment]
Added doc in #304.
