### ISSUE TITLE
msdn nuget package not installing msdn.4.5.2.zip

### ISSUE THREAD

**Issue by srottem** [dotnet/docfx#2032]
**DocFX Version Used**: 
docfx.console 2.23.1

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:
I'm using the .NET Standard project type:

1.  Install docfx.console nuget package 
2.  Install msdn 4.6.1 nuget package 0.1.0-alpha-1611021200
3.  Run docfx --serve
4.  Open help in browser at localhost:8080

**Expected Behavior**:
BCL types should appear as links to MSDN documentation.  I assume the msdn.4.5.2.zip file should be somewhere in the project file structure and the docfx.json should have been modified to include the 'xref' member.

**Actual Behavior**:
BCL types DO NOT appear as links to MSDN documentation.  No evidence of the msdn.4.5.2.zip in the nuget package appears anywhere under the project directory and the docfx.json file does not contain the 'xref' member.

**Comment by bitbonk** [comment]
I hink you will have to edit your docs.json config manually, add
```json
    "xref": [
      "your/relative/path/to/msdn.4.5.2.zip"
   ]
```
to your `"build"` config. See also https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-cross-reference-map

**Comment by srottem** [comment]
The problem is that the nugget package doesn't appear to have installed the
zip file anywhere so I don't have a path to point the xref to.

**Comment by bitbonk** [comment]
You are right, it should actually modify the docfx.json file, but it doesn't. Here is my log from a simple .NET 4.6.1 class libary that I created from scratch:

```text


Attempting to gather dependency information for package 'msdn.4.5.2.0.1.0-alpha-1611021200' with respect to project 'ClassLibrary1', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 485.33 ms
Attempting to resolve dependencies for package 'msdn.4.5.2.0.1.0-alpha-1611021200' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'msdn.4.5.2.0.1.0-alpha-1611021200'
Resolved actions to install package 'msdn.4.5.2.0.1.0-alpha-1611021200'
Retrieving package 'msdn.4.5.2 0.1.0-alpha-1611021200' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/msdn.4.5.2/0.1.0-alpha-1611021200/msdn.4.5.2.0.1.0-alpha-1611021200.nupkg
  OK https://api.nuget.org/v3-flatcontainer/msdn.4.5.2/0.1.0-alpha-1611021200/msdn.4.5.2.0.1.0-alpha-1611021200.nupkg 724ms
Installing msdn.4.5.2 0.1.0-alpha-1611021200.
Adding package 'msdn.4.5.2.0.1.0-alpha-1611021200' to folder 'c:\users\bitbonk\documents\visual studio 2017\Projects\ClassLibrary1\packages'
Added package 'msdn.4.5.2.0.1.0-alpha-1611021200' to folder 'c:\users\bitbonk\documents\visual studio 2017\Projects\ClassLibrary1\packages'
Added package 'msdn.4.5.2.0.1.0-alpha-1611021200' to 'packages.config'
Executing script file 'c:\users\bitbonk\documents\visual studio 2017\Projects\ClassLibrary1\packages\msdn.4.5.2.0.1.0-alpha-1611021200\tools\install.ps1'...
c:\users\bitbonk\documents\visual studio 2017\Projects\ClassLibrary1\packages\msdn.4.5.2.0.1.0-alpha-1611021200
c:\users\bitbonk\documents\visual studio 2017\Projects\ClassLibrary1\packages\msdn.4.5.2.0.1.0-alpha-1611021200\tools
Creating 'xref' : ['../packages/msdn.4.5.2.0.1.0-alpha-1611021200/content/msdn.4.5.2.zip'] to 'xref' section of 'c:\users\bitbonk\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1/docfx.json'
Successfully installed 'msdn.4.5.2 0.1.0-alpha-1611021200' to ClassLibrary1
Executing nuget actions took 12.98 sec
Time Elapsed: 00:00:13.6375414
========== Finished ==========
```
Although the output says: `Creating 'xref' : ['../packages/msdn.4.5.2.0.1.0-alpha-1611021200/content/msdn.4.5.2.zip'] to 'xref'`, docfx.json actually stays unmodified. But what if you add it manually, does it work for you.

**Comment by srottem** [comment]
If I manually download the nugent file, unzip it, extract the
msdn.4.5.2.zip file from it and put it on the filesystem then modify the
docfx.json to add the xref with the path to it, yes. But it defeats the
purpose of the msdn nuget package if it doesn't extract itself...

**Comment by bitbonk** [comment]
https://github.com/bitbonk/docfx/commit/fd3a13bf3db0d55d7f2fe5a5441eadaeb38bcbe9 might fix the problem that docfx.json was not updated. But I really have no clue why your package can't be found anywhere.

**Comment by srottem** [comment]
OK, the zip file is extracted if the project is a .NET Classic (4.6.1)
class library project.  The problem appears to be when the project type is
.NET Standard class library.

**Comment by bitbonk** [comment]
In the new world packages are installed and cached in `%UserProfile%\.nuget\packages`  (on windows), e.g. `c:\Users\{username}\.nuget\packages\`

**Comment by srottem** [comment]
The package is downloaded correctly but does not appear to be extracted
anywhere in the project directory like it is with a .NET Classic project.
Is the expectation that the xref should point to the
%USER_HOME%\.nuget\packages\msdn.4.5.2\0.1.0-alpha-1611021200\content\msdn.4.5.2.zip?
This would be problematic for upgrades since the path would change
unexpectedly.

**Comment by bitbonk** [comment]
Yes I think this the expectation, hence my pull request https://github.com/bitbonk/docfx/commit/fd3a13bf3db0d55d7f2fe5a5441eadaeb38bcbe9

After an upgrade it is the (my) expectation that the docfx.json is upadeted accordingly.

**Comment by srottem** [comment]
Gotcha - thanks for the clarification and all your help!

**Comment by vwxyzh** [comment]
@srottem, @bitbonk We are preparing xref service, it will resolve framework APIs to [docs.microsoft.com](http://docs.microsoft.com/), it will coming soon.

**Comment by srottem** [comment]
Cool!

**Comment by bitbonk** [comment]
@vwxyzh I will still need an onprem solution that allows me to build the docs without internet. So this bug should be fixed anyway, I guess.

**Comment by vwxyzh** [comment]
@bitbonk yes.

**Comment by srottem** [comment]
The new package that includes the commit doesn't appear to have solved the problem on my system - it's like the Powershell script doesn't execute at all as there is no output in the docfx.json nor the messages on the console from the catch block.
