### ISSUE TITLE
Question: is possible to highlight SQL in <code> tag?

### ISSUE THREAD

**Issue by mcurros** [dotnet/docfx#2034]
Hi,

I'm trying to include some vb files that include XML comments with example code in SQL. Is possible to give some sort of hint that the example is in SQL language?

Thanks for the help.

**Comment by vwxyzh** [comment]
@mcurros
* try following (untest):
  ```cs
  /// <example>
  /// <code language="lang-sql">sql</code>
  /// </example>
  ```
* use overwrite markdown file:
  ````md
  ---
  uid: YourAPI
  example: [*content]
  ---
  ```sql
  sql
  ```
  ````

**Comment by mcurros** [comment]
The `/// <code language="lang-sql">sql</code>` worked.

Thanks.
