### ISSUE TITLE
Feature request: Include highlighting for Microsoft Transact SQL.

### ISSUE THREAD

**Issue by mcurros** [dotnet/docfx#2050]
DocFX uses highlight.js. It supports SQL highlighting, but when creating a code tag with a stored procedure for SQL Server the highlighting is incorrect.

I have found a fork from highlight.js [red-gate highlight.js](https://github.com/red-gate/highlight.js), but I think Microsoft should already done it?

Are you planning to include highlighting support for MS TSQL?

**Comment by vwxyzh** [comment]
@adkinn Any idea?

**Comment by adkinn** [comment]
I don't know of any plans to support something beyond 'SQL' is a highlighting language.

**Comment by mcurros** [comment]
I just checked [docs.microsoft.com](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql) and verified that it is not done. The highlighting is incorrect there two...

It looks that the latest version of highlight.js should include it. [Here is the link for the merge that includes T-SQL](https://github.com/isagalaev/highlight.js/pull/1524), I can't figure out what version are you using...

**Comment by vwxyzh** [comment]
@mcurros the source of you mentioned in docs site is [here](https://github.com/MicrosoftDocs/sql-docs/edit/live/docs/t-sql/statements/create-procedure-transact-sql.md)
And we can find out there is no language hint after <code>```</code> at line 75.

**Comment by mcurros** [comment]
@vwxyzh  yes I noticed it's not used everywhere, from line 336  and beyond ```sql is used and you can check that the highlighting is missing keywords. Maybe it's not used everywhere because of the missing keywords.

**Comment by mcurros** [comment]
Bad news, it appears that [https://github.com/isagalaev/highlight.js](https://github.com/isagalaev/highlight.js) is abandoned, as you can read [here](https://github.com/isagalaev/highlight.js/pull/1526#issuecomment-315559099). So transact SQL will not be merged any time soon.

**Comment by yufeih** [comment]
Switching or adding additional syntax highlighting stack introduces complexity that I'm not sure we want to take unless there is significant demand.
