### ISSUE TITLE
Document use docs.microsoft.com/dotnet/xrefmap.yml

### ISSUE THREAD

**Issue by NZSmartie** [dotnet/docfx#2062]
In [Cross reference .NET BCL types](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-net-bcl-types), A link is provided for using [msdn.4.5.2](https://www.nuget.org/packages/msdn.4.5.2) Nuget package for referencing external .Net APIs through xref config. 

Being discouraged by the package name "4.5.2" as it implies an older .Net Framework, I set out to see if a xrefmap.yml existed for their docs.microsoft.com, 

And well... Found https://docs.microsoft.com/dotnet/xrefmap.yml Although it's >100MiB in size, It works when supplying it in `docfx.json`
```json
{
  "build": {
    "xref": [
     "https://docs.microsoft.com/dotnet/xrefmap.yml"
   ]
  }
}

**Comment by NZSmartie** [comment]
Woops, hit enter too soon.

Would it be okay with adding this to the documentation as an alternative source for xrefs.yml?

**Comment by vwxyzh** [comment]
@NZSmartie we are working on xref service, when it ready, you can simply config a xref service address in `docfx.json` like following:
```json
{
  "build": {
    "xrefservice": [
      "https://hostname/query/{uid}?tags=tag1,tag2"
    ]
  }
}
```

**Comment by NZSmartie** [comment]
That's awesome~!

**Comment by vwxyzh** [comment]
The address will be `https://xref.docs.microsoft.com/query/{uid}`, the data is not ready by now.
