### ISSUE TITLE
Continuous integration with Chocolatey

### ISSUE THREAD

**Issue by jozefizso** [dotnet/docfx#207]
DocFX package on Chocolatey is only available in 1.4 release. The docfx 1.5 should be put on Chocolatey as well.

**Comment by ferventcoder** [comment]
And the next versions as well.

**Comment by ferventcoder** [comment]
@vicancy ping

**Comment by ferventcoder** [comment]
@vicancy Are you looking for help with this? I was under the assumption that I was helping get you set up and you would be pushing future versions up to dot org. Was that an incorrect assumption?

**Comment by vicancy** [comment]
Hi @ferventcoder , thanks for the reminder. Definitely we will be responsible for the releases and updates.
One question by the way, what's your recommendation if we want to publish 2 versions of `docfx.exe` at the same time, e.g. one targeting for .NET framework 4.5 and one targeting for .NET framework 4.62(which is now still in preview stage)

**Comment by ferventcoder** [comment]
> What's your recommendation if we want to publish 2 versions of docfx.exe at the same time, e.g. one targeting for .NET framework 4.5 and one targeting for .NET framework 4.62(which is now still in preview stage).

Quick question - what's the difference? It's an interesting question, usually folks only separate by architecture. In this case it may need to be a second package.

Right now I would go for just the stable one as the main package.

Adding in the preview one - you can do a secondary package or if the DocFX package is just downloading from GitHub releases, you can add in package parameters to let folks choose which one they want installed. Another thing you could also do is inspect the system to see what version of the .NET framework they have installed and adjust accordingly.

For parsing package params, see https://github.com/chocolatey/choco/wiki/How-To-Parse-PackageParameters-Argument

HTH

**Comment by trydis** [comment]
Any progress? 1.4 is still the latest on Chocolatey :crying_cat_face:

**Comment by jozefizso** [comment]
It's great to see so many new releases of DocFX, but without any option for referencing it from build system (no official NuGet package and outdated Chocolatey package) it's hard to use it.

**Comment by jozefizso** [comment]
@vicancy it's impossible to use DocFX when it's not available officially on any of the packaging sources (NuGet, Chocolatey).

**Comment by qinezh** [comment]
@jozefizso @trydis DocFX 2.1 is available on [Chocolatey](https://chocolatey.org/packages/docfx/2.1) now

**Comment by trydis** [comment]
Great, thanks :+1:
