### ISSUE TITLE
Feature request: Add swagger type definitions to REST API documentation

### ISSUE THREAD

**Issue by Mangepange** [dotnet/docfx#2072]
When generating a REST API documentation from a swagger-file I would expect that the types from the "definitions" section would be included in the documentation, especially if the type is used as a method parameter.

**Comment by vicancy** [comment]
https://github.com/dotnet/docfx/issues/465 describes the same feature. It is actually expanded in code however needs template support

**Comment by sirjeppe** [comment]
Hi! Any update on this issue?

**Comment by rebrovoleksii** [comment]
Could you please advise what template I should modify to get definitions into generated documentation? I've exported default.pdf template. Is it _exported_templates\pdf.default\partials\rest.child.tmpl.partial file? If yes what  variables should I use from RestApi.common.js ?

**Comment by hellosnow** [comment]
@rebrovoleksii it should be _exported_templates\pdf.default\partials\rest.child.tmpl.partial we need to update for, the "definition" object is defined in child of RestApi.common.js. @vicancy to confirm.

**Comment by vicancy** [comment]
Hi @rebrovoleksii yes, it is the `rest.child.tmpl.partial` file. And to render complex type, for complex type, the type is actually inside the model however not rendered. You can use `docfx build --exportViewModel` to view the model waiting for applying template. Take `body` from [updatePet](http://docascode.github.io/docfx-seed/restapi/petstore.html#petstore_swagger_io_v2_Swagger_Petstore_1_0_0_updatePet) for example, the detailed type for `body` is: 
![image](https://user-images.githubusercontent.com/668244/33867046-fb191f60-df34-11e7-8859-eb2a83914034.png)

**Comment by ipanin** [comment]
Without support of Definitions swagger-generated documentation isn't usable. I'm waiting for its implementation. Also OpenAPI support required since it is more handy for REST API specification. For the present I am obliged to use ReDoc for the OpenAPI part of documentation.

**Comment by mattwoberts** [comment]
Hi - just wondered if this is planned at all? I too need the swagger generated docs to include the definitions, without this I'll have to find an alternative solution.

**Comment by mcm-ham** [comment]
Just curious how is current Microsoft docs getting this to work without this feature?
https://docs.microsoft.com/en-us/rest/api/appservice/appservicecertificateorders/list#definitions

**Comment by mcm-ham** [comment]
Thanks for the pointer vicancy, I've had a go at modifying the default template to add swagger type definitions support similar to what Microsoft [already use](https://docs.microsoft.com/en-us/rest/api/appservice/appservicecertificateorders/list#definitions).

https://mcm-ham.github.io/docfx-seed/restapi/petstore.html
https://github.com/mcm-ham/docfx-seed/commit/81151ef0a52da8cf07cf4b38061478d1b7c05ef1

**Comment by ipanin** [comment]
@mcm-ham, thanks a lot.
@vicancy, do you have any plans to embed this change to the default template?

**Comment by ipanin** [comment]
Any updates?

**Comment by superyyrrzz** [comment]
@mcm-ham @ipanin We are happy to merge pull requests for this.

**Comment by vad710** [comment]
Thank you, @mcm-ham - your solution worked for me. I just added the new files onto my existing template. It would be great to have this included in the default template.

**Comment by sbaeurle** [comment]
hello guys, even though this issue ist 3 years old, I wanted to ask about the current status? 
Is the template adjustment still working and can it be added to docfx via PR? :)

**Comment by sbaeurle** [comment]
thanks @yufeih :)
