### ISSUE TITLE
"Improve this document" with TFVC?

### ISSUE THREAD

**Issue by Larswa** [dotnet/docfx#2073]
Hi, love this project. 

We are using on prem Team Foundation Version Control (TFVC) instead of Git.  How do I get the "Improve this document" functionality to work with with TFVC?  I gathered from old issues filed, that the code here looks at the .git/config file and grabs a repo url from there?  

**DocFX Version Used**: 
2.24

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Comment by superyyrrzz** [comment]
Yes, DocFX fetches info from git.exe and generate the URL. TFVC is not supported for now.

**Comment by roel4ez** [comment]
Hi can you give me some more information on this functionality?
I've scanned through the docs, but could not find any reference. However it might just be what i am looking for...!

**Comment by superyyrrzz** [comment]
@roel4ez You will see "Improve this Doc" on every generated page's right section, for easy contribution. Is this what you want?

**Comment by vicancy** [comment]
@superyyrrzz is changing https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/common/common.js#L65 enough to support TFVC?

**Comment by superyyrrzz** [comment]
@vicancy This can support git host sites other than github, but can't support non git based repository like TFVC, unless a custome plugin insert the needed data to models.

**Comment by roel4ez** [comment]
@superyyrrzz Aha, we are talking about _improving_ the document... OP talks about _approving_ 
If that is the case, then never mind, just a misunderstanding 😄

**Comment by Larswa** [comment]
Argghh ...sorry bout that guys. I meant "improve" as in ... give me that bleeding link to where the docs are.  Should not post issues that late at night.

**Comment by superyyrrzz** [comment]
http://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html mentions `_gitContribute` and `_gitUrlPattern`, but all is git based...

**Comment by Larswa** [comment]
@superyyrrzz Yeah got that. Lets go ahead and close this then.
