### ISSUE TITLE
Displayed inheritance format is broken in default template?

### ISSUE THREAD

**Issue by mcurros** [dotnet/docfx#2074]
**DocFX Version Used**:  
2.24.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Create api documentation

**Expected Behavior**:
Items should be indented and displayed correctly as in DocFX api documentation.

**Actual Behavior**:
As seen in image...
![bug](https://user-images.githubusercontent.com/13538023/30723195-0497d0ea-9f0c-11e7-8dff-a5d6ddc58d71.jpg)

**Comment by superyyrrzz** [comment]
DocFX now only apply CSS up to the 6th inheritance... Will improve it.

**Comment by mcurros** [comment]
OK, thank you!
