### ISSUE TITLE
[Question] DocFX + VB Inline Comments

### ISSUE THREAD

**Issue by cropper1991** [dotnet/docfx#2089]
I couldn't find anywhere else to ask this, so I thought I'd ask it here. Is there any support for VB.net inline comments as part of the metadata + build processes? If not, is there any way to include this information as part of the process.

I realise it may require a pre or post-processor to pull it off.

**Comment by mcurros** [comment]
Hi, I'm using it to document our VB .Net projects. You should install the nugget package docfx-console and the follow up the documentation. I will take comments like:
```vb
    ''' <summary>
    ''' Class summary...
    ''' </summary>
```
Regards

**Comment by cropper1991** [comment]
Unfortunately, this doesn't fit our needs in certain areas (such as enums). I am now evaluating whether I can modify the source code to account for this scenario.

**Comment by cropper1991** [comment]
I think what I'll end up doing is modifying the yml file post process, obtaining the comments where applicable

**Comment by mcurros** [comment]
OK, but we document enums out of the box. Just add a summary comment for each value, as well as the enum declaration. DocFX does a lot out of the box.

Good luck!

**Comment by vwxyzh** [comment]
@mcurros vb `'''` comment is supported in DocFX.
If you cannot find it in document:
1. Please ensure your xml document has the value.
   (You can find it in the properties of project, compile, Generate XML document file
   this is not necessary for DocFX, but we can test your comment is correct.)
2. Open an issue with a same project, then we can identify the problem.

**Comment by cropper1991** [comment]
Okay guys, thank you all for your input, right now I will have to customise the yml files to include additional data such as tags and standard vb comments (where applicable).

Moving forward, I will hopefully migrate us to using summary comments in the appropriate places, reducing the amount of customization of the yml model files required.
