### ISSUE TITLE
Feature request: Article Navigation

### ISSUE THREAD

**Issue by willnode** [dotnet/docfx#2101]
**DocFX Version Used**: 
2.24

**Template used**: (`default` or `statictoc` or contain custom template)
custom

**Steps to Reproduce**:
N/A

**Expected Behavior**:
N/A

**Actual Behavior**:

Navigating between articles can be easier if I have something like this in the end of articles.
![next and previous button](https://user-images.githubusercontent.com/20214420/31160878-0e96e436-a8fe-11e7-9273-bdbfd4c36829.png)

If I click the next button, the article jumps either to next page or inside (Assuming the TOC hierarchy is  flattened here). The same thing also applies when I click the other button.

Unfortunately, I haven't found something like that mentioned in documentation.

**Comment by vicancy** [comment]
A cool feature I have thought for a while

**Comment by icnocop** [comment]
For reference, also see [Feature proposal #26: Insert a "Next topic" button at the bottom of web pages to jump to the next topic and/or the next section](https://feathub.com/docascode/docfx-feature-proposals/+26)

**Comment by DmitriyYukhanov** [comment]
Meanwhile, it's 2022 👀
Would be really great to have it out of the box.
