### ISSUE TITLE
Verbose Logging Level - Dependency Graph Reports Failure to Match System Types

### ISSUE THREAD

**Issue by cropper1991** [dotnet/docfx#2107]
**DocFX Version Used**: 2.5.1

**Template used**: 'statictoc' with customizations

**Steps to Reproduce**:

1. Use a sample project to produce metadata via the metadata command (containing system types such as System.Int32)
2. Then, run the build command, with the command line switch --loglevel verbose

As an example

**Expected Behavior**:
Dependency Graph code to understand System + Array Types and therefore not report unresolved references

**Actual Behavior**:
Dependency Graph reports that it failed to resolve references, such as System. or System.Int32 in my particular case. This is in addition to Array Types, such as a structure named A and therefore failing to resolve A[]

**Comment by vicancy** [comment]
Could you provide the sample project and the build output message ?

**Comment by cropper1991** [comment]
Of course vicancy, hopefully you'll agree this is one of the simplest projects I could have put together. Attached is a zip folder containing the source files and vbproj, along with a text file which contains the output from docfx with the verbose logging switched on. I hope this is sufficient for what you need to investigate further.

[Test Project - Issue 2107.zip](https://github.com/dotnet/docfx/files/1371018/Test.Project.-.Issue.2107.zip)
[Output - Issue 2107.txt](https://github.com/dotnet/docfx/files/1371017/Output.-.Issue.2107.txt)

**Comment by cropper1991** [comment]
This may be to do with imported namespaces, as when I remove these from the sample project it appears as if graph resolution functions as expected.

**Comment by cropper1991** [comment]
Sorry to bombard you with examples, but I've also found another combination which seems to also illustrate this issue. This is a sample layout of how we've setup a WCF based layer. Again as previously asked for I've also attached the output from verbose logging. The reason for using verbose logging in our case, is we are running this in an unattended fashion, and so we want to have in depth details on how the process is going, such as internal timings of each operation. I also found this the only way to report issues, such as the Graph Reference Resolution failing.

[WCF Example - Issue 2107.zip](https://github.com/dotnet/docfx/files/1371197/WCF.Example.-.Issue.2107.zip)
[WCF Output - Issue 2107.txt](https://github.com/dotnet/docfx/files/1371207/WCF.Output.-.Issue.2107.txt)

**Comment by vicancy** [comment]
Hi @cropper1991 Dependency graph reports unresolved references to System.* type values because these are not inside your code, docfx will consider it as external references instead internal reference. I would suggest you ignore verbose level messages, they are generally messages for debugging purpose.

**Comment by cropper1991** [comment]
What about the array types? Surely it shouldn't be reporting these as unresovlable?

**Comment by vicancy** [comment]
@cropper1991 They are reported as unresovable by the "dependency graph" as they are not internal types your solution defines. Actually they will be resolved as "external" reference types. "dependency graph" is used by docfx incremental build and not the final output. So I suggest you just ignore the message if there is no unexpected behavior for the output html files.

**Comment by cropper1991** [comment]
Right okay, thank you for this clarification
