### ISSUE TITLE
Child process Error ... DfmHttpService.exe: Permission denied

### ISSUE THREAD

**Issue by nonno** [dotnet/docfx#2110]
**DocFX Version Used**: 0.1.0

** VSC Versione Used**: 1.17.0 (MacOS Sierra 10.12.6 (16G29))

**Template used**: `default`

**Steps to Reproduce**:

1. Installed the plugin
2. Restarted VSC
3. Opened the preview of a .md

![screen shot 2017-10-10 at 09 46 28](https://user-images.githubusercontent.com/4105325/31375248-3073bf0a-ada1-11e7-9711-4f80ec319db0.png)

**Comment by 928PJY** [comment]
Hi, @nonno, Right now, we just support this extension on Windows OS, Cross-platform is coming soon!

**Comment by superyyrrzz** [comment]
Moved to https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-markdown
