### ISSUE TITLE
Sidebar search doesn't ignore zero width spaces

### ISSUE THREAD

**Issue by Onots** [dotnet/docfx#2112]
**DocFX Version Used**: 2.24

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Copy a class name with at least two part (ie. FooBar) from a documentation site (note: this will include a zero width space between Foo and Bar)
2. Past into the side bar search

**Expected Behavior**:
The FooBar class shows up as a search result

**Actual Behavior**:
No results found.

The zero width spaces are useful but they are completely invisible to the user. Search should ignore them.

**Comment by superyyrrzz** [comment]
Can you try v2.25? Now we use `<wbr>` instead of zero width spaces.

**Comment by Onots** [comment]
That does make it work. I've upgraded to 2.25.2.

Thanks!
