### ISSUE TITLE
Nuget version of DocFX doesn't run on Mono

### ISSUE THREAD

**Issue by joelmartinez** [dotnet/docfx#2115]
I'm on a mac, with mono `v5.4.0.201` and `make` installed locally, and I'm trying to run docfx.

**DocFX Version Used**:  2.25.1

**Steps to Reproduce**:

1. Create a `packages.config` file with the following content:

    ```xml
    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="Microsoft.DocAsCode.Common" version="2.25.1"  />
      <package id="Microsoft.DocAsCode.Plugins" version="2.25.1"  />
      <package id="docfx" version="2.25.1"  />
    </packages>
    ````
    Please note, the common and plugins dependencies are only added due to #2114 ... ideally it the packages file would have only a single entry for docfx
2. Create a `Makefile` with the following contents (only using make to simplify the repro steps ... you can just type these commands by hand if you don't want to install `make`

    ```make
    DOCFX-PATH = packages/docfx.2.25.1/lib/net461
    DOCFX.EXE = mono $(DOCFX-PATH)/docfx.exe
    
    MICROSOFT.DOCASCODE.COMMON.DLL = packages/Microsoft.DocAsCode.Common.2.25.1/lib/net461/Microsoft.DocAsCode.Common.dll
    MICROSOFT.DOCASCODE.PLUGINS.DLL = packages/Microsoft.DocAsCode.Plugins.2.25.1/lib/net461/Microsoft.DocAsCode.Plugins.dll
    
    all: docfx-init
    
    # fetch the docfx packages
    restore:
    	nuget restore -PackagesDirectory packages
    	cp $(MICROSOFT.DOCASCODE.COMMON.DLL) $(DOCFX-PATH)/
    	cp $(MICROSOFT.DOCASCODE.PLUGINS.DLL) $(DOCFX-PATH)/
    
	
    # init the docfx walkthrough
    docfx-init: restore
    	$(DOCFX.EXE) init -q
    
    .PHONY: restore docfx-init
    ```

    The workaround for #2114 is the only reason I'm copying the .dlls around in the `restore` target. It's not _really_ important to this particular issue.
3. run `make all` in _terminal_.

**Expected Behavior**:

That it would generate a sample/walkthrough site, per [documentation](http://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project.html?q=init#step2-init-a-docfx-project)

**Actual Behavior**:

The program throws an unhandled exception:

```
Unhandled Exception:
System.TypeLoadException: Failure has occurred while loading a type.
  at Microsoft.DocAsCode.Program.Main (System.String[] args) [0x00000] in <66ae8b0e69cf47919c7177e07f7fcbce>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Failure has occurred while loading a type.
  at Microsoft.DocAsCode.Program.Main (System.String[] args) [0x00000] in <66ae8b0e69cf47919c7177e07f7fcbce>:0
```

Inspecting the .exe using the Visual Studio for Mac assembly browser verifies that it does not contain a type called `Microsoft.DocAsCode.Program`.

**Comment by vicancy** [comment]
Hi @joelmartinez please try `docfx.console` nuget package which contains `docfx.exe` under `tools` folder, using `nuget install docfx.console` and `mono tools/docfx.exe init`

**Comment by joelmartinez** [comment]
Ahh, excellent news ... thank you for the information @vicancy! yes it works as described :) 

This would make an excellent topic of documentation ;)
