### ISSUE TITLE
[Question] Is it possible to files classes, e.g., by reflection

### ISSUE THREAD

**Issue by xxcuratorxx** [dotnet/docfx#2117]
Hi,

I know it is possible to filter the files of which html documentation is created by folder etc.

However, I need to generate documentation only for, e.g., static classes. Is there any extension point to write some code to decide for every class (e.g. by reflection) whether it should be included or not?

Thanks,
curator

**Comment by cropper1991** [comment]
Your best bet is to use the inbuilt filtering mechanism, for more information see here:
https://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html

**Comment by xxcuratorxx** [comment]
Hi,

I tried to implement my request with the upper link. This solved my first problems.

However, additionally I have an csproj with many files that are distributed among different folders in the project, but have the same namespace. No I want to include only files of one subdirectory.

I havn't found a way to do so with the api rules, but one way is to refer to *.cs files rather that *.csproj files

`
"metadata": [
        {
            "src": [
                {
                    "files": "*.cs",
                    "cwd": "Project/Subfolder"
                }
            ]
        }       
    ],
`
instead of 
`
"metadata": [
        {
            "src": [
                {
                    "files": "*.csproj",
                    "cwd": "Project"
                }
            ]
        }       
    ],
`

That works so far, but docfx is not able to read be assembly name, such that the html contain an entry like

> Assembly: cs.temp.dll.dll

Which seems to be kind of a fall back.

Any suggestions to overcome this?

**Comment by superyyrrzz** [comment]
A quick workaround is to [customize template](https://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html) to remove extra `.dll`.
