### ISSUE TITLE
Code Snippet from GitHub link

### ISSUE THREAD

**Issue by brianlagunas** [dotnet/docfx#2120]
Currently, you can only provide a code snippet with a local code file.  I would like the ability to provide a link to the code file as my docs are not in the same repo or location as the actual code.

`[!code-csharp[My Snippet](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs?range=2-8)]`

I see that the MS docs uses this syntax in various MD files, but I cannot find the plugin used in the docs source code.

If this is not added to DocFX, is there a work-around I can use to achieve my goal?

**Comment by superyyrrzz** [comment]
It's not supported to reference a code snippet link for now.
In MS docs pipeline, the referenced repo is cloned before docfx build. Then all code referenced becomes local files. Will this work for you?

**Comment by brianlagunas** [comment]
While technically possible, it is not the desired approach.  We have an existing repo with hundreds of samples in a different repo.  The work required to identify the files and copy them over would not be worth the time, money, and resources.  It would be better if we could just point to the GitHub URI instead.

Is this possible?  Can a plugin be written to achieve this?

**Comment by vwxyzh** [comment]
@brianlagunas it is possible, but we cannot detect the change from a remote url, that means you need always use force build (-f) for any changes in sample repo.

**Comment by vwxyzh** [comment]
@brianlagunas one more limitation is you should give the raw file url, not GitHub page url.
e.g.:
https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs
=>
https://raw.githubusercontent.com/PrismLibrary/Prism/master/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs

**Comment by brianlagunas** [comment]
That would be great.  Using the raw file link is no problem.  Is there an example of a plugin that I could modify to achieve this?  I doubt many people require this so adding it directly to the docfx system probably isn't required.

**Comment by vwxyzh** [comment]
The document of customizing DFM renderer is [here](http://dotnet.github.io/docfx/tutorial/howto_customize_docfx_flavored_markdown.html#customize-renderer).
The core code of rendering DFM-code is [here](http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.Dfm.DfmCodeRenderer.html).

**Comment by brianlagunas** [comment]
Thanks!

**Comment by S-Nakib** [comment]
Hi, the link above doesn't work. I want to add code on my markdown file from a public git repo. Is there any proper way?
