### ISSUE TITLE
[!Video] block doesn't display video

### ISSUE THREAD

**Issue by brianlagunas** [dotnet/docfx#2122]
**DocFX Version Used**: 2.25.2

**Template used**: `statictoc`

**Steps to Reproduce**:

1. Use the following MD
`> [!Video https://youtu.be/DYRLcqG2BAY]`

**Expected Behavior**:
The video should be displayed

**Actual Behavior**:
Browser error (Chrome and Edge)

> This content can't be shown in a frame. There is supposed to be some content here, but the publisher doesn't allow it to be displayed in a frame. This is to help protect the security of any information you might enter into this site.

**Comment by superyyrrzz** [comment]
Choose the embed video link should work: `> [!Video https://www.youtube.com/embed/DYRLcqG2BAY]`

https://stackoverflow.com/questions/9934944/embedding-youtube-video-refused-to-display-document-because-display-forbidden-b

**Comment by brianlagunas** [comment]
Perfect!  Thanks a lot.
