### ISSUE TITLE
Carriage Returns in Summary Tags - Not Converted to Br in Final Output

### ISSUE THREAD

**Issue by cropper1991** [dotnet/docfx#2126]
**DocFX Version Used**: 2.25.1

**Template used**: statictoc with customizations

**Steps to Reproduce**:

1. Run docfx on a project, whereby at least one method or class has a summary tag spanning multiple lines

**Expected Behavior**:
'\n' characters within the metadata files should be converted to br tags, and therefore match how it was laid out in the code

**Actual Behavior**:
Multi-line summaries are instead condensed into a single paragraph, rather than being broken up by br tags

**Comment by vwxyzh** [comment]
@cropper1991 Same behavior in vs2017.

If you want to add `<br/>` in line end, you need following markdown rules:
* add two or more space before '\n'.
* add '\\' before '\n' (only for dfm-latest)
* add `<br/>`

**Comment by cropper1991** [comment]
So, what your saying, is in the case of encountering the following XML comments:

''' <summary>
''' This is a sample comment. 
''' <b>Note:</b> Test note

That this wouldn't be translated into a multi line summary and instead be rendered as followed:
This is a sample comment. **Note:** Test Note?

**Comment by vwxyzh** [comment]
<img width="357" alt="pic1" src="https://user-images.githubusercontent.com/2705828/31643834-674b53e2-b325-11e7-8d48-177616d4a3ec.png">

**Comment by cropper1991** [comment]
Okay vwxyzh, thanks for this clarification, I will now close this issue.
