### ISSUE TITLE
StaticToc - Custom App Logo (Cross Origin Request Rejected)

### ISSUE THREAD

**Issue by cropper1991** [dotnet/docfx#2128]
**DocFX Version Used**: 2.25.1

**Template used**: 'statictoc' with memberpage plugin

**Steps to Reproduce**:

1. Create a website using the static toc template, ensuring to set _appLogoPath to a custom logo, such as Logo.png
2. Navigate to the Index Page that it's produced, open up developer tools (in this case my browser is Google Chrome)
3. You will notice an error message within the console stating that "Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https". 

**Expected Behavior**:
For the logo to have been included in a form whereby the webpage is fully functional when navigating to it via browser

**Actual Behavior**:
Unable to see App Logo because of Cross Origin Violation

**Comment by superyyrrzz** [comment]
The error occurs when scripts try to resolve the svg file. If you are using a png file, although the resolve will fail, the png should show and link can work.
Of course, I agree the logic to resolve svg isn't needed here. It can be improved to eliminate the eror.

**Comment by cropper1991** [comment]
Ah okay, this makes more sense, I can confirm the png works as expected, but thought it worth mentioning either way.
