### ISSUE TITLE
[Question] Multi-repo doc guidance

### ISSUE THREAD

**Issue by brianlagunas** [dotnet/docfx#2129]
I have a single site that just serves up documentation from multiple document repos, very similar to how MS has their docs separated by product.  For example:

- Repo for project 1
- Repo for project 2
- Repo for project 3

None of these repo's will have any API documentation.  Only "Articles" in the form of MD files.

There will not be a landing page for the documentation site.  Instead, each product's documentation will be provided via a direct link.  The URI's will look like : `http://somesite.com/docs/productName`.  That URI will then contain all the topics for only that product.  They will all use the same theme.

What is the guidance to configure docfx to handle this structure?  Since running the docfx command line command will build an entire site run on each repo, how do I instruct that we only want the articles created and nothing else?

Thanks,

**Comment by vicancy** [comment]
Hi @brianlagunas do you want these repo to share the same navbar? One idea is to use absolute path as link to other projects, for example, for project 1, the root toc.yml would be:
```yml
[Project 1] (articles/)
[Project 2](http://somesite.com/docs/product2)
[Project 3](http://somesite.com/docs/product3)
```
for project 2, the root toc.yml would be:
```yml
[Project 1] (http://somesite.com/docs/product1)
[Project 2](articles/)
[Project 3](http://somesite.com/docs/product3)
```

**Comment by brianlagunas** [comment]
Thanks, I'll give that a try.  Since a site is generated for each repo, I'll just copy out the contents within the "articles" folder and put them in the main site's structure.

**Comment by bitbonk** [comment]
This is a general problem with DocFX I think. It is kind of hard to find a good path on how to build something like docs.microsoft.com where independent project contribute to the same docs site. These kind of question are coming up quite often.
