### ISSUE TITLE
Code examples in XML documentation

### ISSUE THREAD

**Issue by cesarsouza** [dotnet/docfx#2131]
Can DocFx handle ```<code source="someclass.cs" region="some_region" />``` tags in XML documentation?

In Sandcastle and a few other tools it is possible to specify that the contents of a ```<code></code>``` tag should be fetched from a ```#region``` from inside an arbitrary file in the project, e.g.:

```csharp
namespace SomeNamespace
{
    /// <summary>
    /// Some class
    /// </summary>
    /// <example>
    /// <code source="unit tests/class1test.cs" region="some_region" />
    /// </example>
    /// 
    public class SomeClass 
    {
    }
}
```

My question is, can DocFx handle this as well? 

I am trying to replace Sancastle by DocFx in a project, but got stuck trying to get this working.

**Comment by superyyrrzz** [comment]
http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#code-snippet

**Comment by vicancy** [comment]
Yes, it is supported as described by https://github.com/dotnet/docfx/issues/910

**Comment by cesarsouza** [comment]
Many thanks for the quick answers!

@superyyrrzz thanks, I had seen that page, but understood it applied only to markdown. There is no mention about how to accomplish the same as the ```[!code-<language>[<name>](<codepath><queryoption><queryoptionvalue> "<title>")]``` tag using triple slash XML comments.

@vicancy thanks, but I couldn't get it working yet. How do I tell DocFx where the root directory where the files with the ```#region``` tags is located? 

For example, let's say my repository has the following structure:

```markdown
- Root
  - Unit Tests
    - UnitTestsProject1
       - SomeClassTest.cs (this file contains the code snippets in #region tags) 
  - Sources
     - Project1
        - Namespace1
           - SomeClass.cs (this file contains XML documentation referring to SomeClassTests.cs)
     - Docs
        - DocFx
           - docfx.json
```

The SomeClass.cs file looks like this:
```csharp
namespace SomeNamespace
{
    /// <summary>
    /// Some class
    /// </summary>
    /// <example>
    /// <code source="Unit Tests/UnitTestsProject1/SomeClassTest.cs" region="some_region" />
    /// </example>
    /// 
    public class SomeClass 
    {
    }
}
```

As you can see, the relative paths for the ```source``` attributes should refer to the root of the repository. However, I wasn't able to instruct DocFx to look for them there. Observing how DocFx deals with image paths, I've tried putting the following in the "metadata/build/content" section of my docfx.json file:
```yml
{
    "files": [
      "Unit Tests/**/*Test.cs",
      "Unit Tests/**/*Test.vb"
    ],
    "exclude": [
      "**/obj/**",
      "**/bin/**"
    ],
    "src": "../../../" // start from the project's root folder
}
```
but it obviously didn't work, as probably the process for including images and code snippets is quite different. 

The above scenario is supported by Sandcastle/SHFB.

Regards,
Cesar

**Comment by vicancy** [comment]
Hi @cesarsouza the file path for `source` should be relative to the location of that source code containing that comment, in your example, it is `SomeClass.cs`

**Comment by cesarsouza** [comment]
Hi @vicancy thanks for the answer!

Is there any chance that DocFx could make this configurable?

If we always assume that the file path for ```source``` should be relative to the location of the source code containing the comment, it means that the documentation will break if we move the file to a parent or child directory, and all ```source``` attributes will need  to be updated. In addition, if we have even just a couple nested directories in the project, the paths will already start to look quite confusing with series of ```../../../../``` that make it hard to track to where the attribute is actually pointing to.

And it turns out, that this is actually supported in Sandcastle projects. The example I've posted actually corresponds exactly the current layout of a repository where Sandcastle correctly identifies the file paths for ```source``` even though they are relative to the root of the project. This is possible because SHFB's Code Block component allows the base path for the ```source``` attribute in ```code``` tags to be configurable. In my case, I've made it point to the project's root directory to avoid the problems I've mentioned above.

Regards,
Cesar

**Comment by vicancy** [comment]
Is it helpful to have such syntax `~/a.cs`, where `~` stands for the root folder of `docfx.json`? `~` is a syntax for markdown files supported by docfx, we can support that in this case also.

**Comment by cesarsouza** [comment]
Thanks for the answer. I am afraid it wouldn't be that much helpful to me, as it would still be necessary to change all the existing documentation placing a ```~``` at the beginning of the value specification of all ```source``` attributes in the codebase, and I wouldn't be able to generate Sandcastle docs anymore (I still intended to keep both for some time until I manage to add redirects to DocFx's version). However, it is true it might solve some of the problems I had outlined above, so I guess this might be up to DocFx's team decision.

What about something alongside the lines of what I had first tried a few comments above? e.g.
```yml
{
    "files": [
      "Unit Tests/**/*Test.cs",
      "Unit Tests/**/*Test.vb"
    ],
    "exclude": [
      "**/obj/**",
      "**/bin/**"
    ],
    "src": "../../../" // (the root for all documentation files could be set by adjusting this)
}
```

Regards,
Cesar

**Comment by vicancy** [comment]
Hi @cesarsouza, could you share the way to config it in Sandcastle? Maybe that would give us some hint how to support that specific feature in docfx... `src` is used for other purpose.. maybe call it `codeSnippetRoot` ...? (just brainstorming..) cc @vwxyzh @superyyrrzz

**Comment by cesarsouza** [comment]
Hi @vicancy, sorry for the delay in answering. The base path for the relative paths for code source attributes can be configured in the configuration options for the Code Block Component in SHFB:

![image](https://user-images.githubusercontent.com/528455/32139138-896c254e-bc41-11e7-9534-108703c928f4.png)

Those property pages shown above can be accessed by right clicking the SHFB project in VS and clicking "Properties". But the dialog can also be accessed from the standalone SHFB GUI as well:

![image](https://user-images.githubusercontent.com/528455/32139167-2315171e-bc42-11e7-957e-ca3cbe790a00.png)

**Comment by jeikabu** [comment]
Chiming in that we'd love to see this as well.
We use this feature with Sandcastle pretty heavily and is probably the main thing keeping us from moving the documentation for our C# API to docfx.

**Comment by m-ringler** [comment]
As far as I see, you can now set the base path via $.metadata.sourceCodeBasePath in docfx,json. So shouldn't the issue be closed?
