### ISSUE TITLE
Microsoft.DocAsCode.Dfm (or any) is not depending on System.Composition.AttributedModel

### ISSUE THREAD

**Issue by willnode** [dotnet/docfx#2139]
**DocFX Version Used**: 2.24

**Template used**: Any

**Steps to Reproduce**:

[Same steps with tutorial on documentation](https://dotnet.github.io/docfx/tutorial/howto_customize_docfx_flavored_markdown.html)

**Expected Behavior**:
The plugin should builds.

**Actual Behavior**:
`ExportAttribute` is missing. More info:

```c#
[Export(typeof(IDfmEngineCustomizer))]
```
I got stuck in step 7, the `ExportAttribute` is missing. After hours of searching I found it was a class in another [NuGet](https://www.nuget.org/packages/System.Composition.AttributedModel/) named `System.Composition.AttributedModel` version `1.0.31` (It still won't compile if latest stable version `1.1.0` is used).

And then I take a quick look on the dfm depedencies and found this screenshot confirms my hypothesis:

![screenshot 71](https://user-images.githubusercontent.com/20214420/31797132-f20fb256-b556-11e7-9d4f-71d0923cbd5c.png)

**Comment by superyyrrzz** [comment]
Thank you for raising this! Fixed in the document.
