### ISSUE TITLE
IN THIS ARTICLE does not scroll when there is more items than available page height

### ISSUE THREAD

**Issue by wieslawsoltes** [dotnet/docfx#214]
Page to reproduce the issue:

http://core2d.github.io/api/Core2D.Wpf.Properties.Resources.html#properties

Screenshot of the issue:

![docfx_in_this_article_does_not_scroll](https://cloud.githubusercontent.com/assets/2297442/13828822/f1e48eb8-ebc3-11e5-84ee-c030ba52f2b0.PNG)

**Comment by sergey-vershinin** [comment]
This is also true for the left side, where namespaces are listed

**Comment by chenkennt** [comment]
someone also reported the same issue for .NET Core doc:
https://github.com/dotnet/core-docs/issues/321

**Comment by chenkennt** [comment]
@sergey-vershinin left TOC should be scrollable, could you give me a sample where you see this issue?

**Comment by sergey-vershinin** [comment]
@chenkennt You can navigate to the url proided by @wieslawsoltes, then scroll all the page down (I mean right scroller). As a result the page footer will show up and start to hide the list of namespaces.

**Comment by simonmurdock** [comment]
The side TOC does scroll for me, but it is overlapped by the footer, so you cant see the last item

**Comment by devel0** [comment]
still not work,
example https://devel0.github.io/netcore-util/api/SearchAThing.UtilExt.html
generated with docfx 2.56.2.0 with [this config](https://github.com/devel0/netcore-util/tree/master/docfx)

**Comment by Crazydog974** [comment]
Hi, we have the same problem : with V2.58.3.12155
![image](https://user-images.githubusercontent.com/6754619/133041118-fd0a3f79-7996-42f2-997d-eb57805275b1.png)

**Comment by sidgrouse** [comment]
Is there a workaround for the issue? It is still appearing up to the current version 3.0.0-beta1.1154

**Comment by bitbonk** [comment]
Same problem here. Did anyone find a workaround? Maybe by changing the template?
