### ISSUE TITLE
Bug: docfx.json is not generated for dotnet core project

### ISSUE THREAD

**Issue by jobubo** [dotnet/docfx#2142]
**DocFX Version Used**:  2.26.0

**Template used**: default

**Steps to Reproduce**:

1. Visual Studio > File > New > Projects... ->Viusal C# > .NET Core > ASP.NET Core Web Application
2. Select .NET Core and ASP.NET Core 2.0 in drop down menu, Application Type Web Application -> OK 
3. Add docfx.console project via nuget

**Expected Behavior**:
Package is installed, docfx.json created in project root

**Actual Behavior**:
Package is installed, docfx.json not in project root

**Comment by jhermsen** [comment]
This is related to some changes in NuGet where content is replaced by contentFiles and requires changes in nuspec.
Here I found related specification.
https://github.com/NuGet/Home/wiki/%5BSpec%5D-Content-v2-for-project.json

**Comment by jhermsen** [comment]
Did some testing and this new structure isn't going to work. NuGet stopped supporting untracked files, meaning files are only referenced in the project adding the package.

Tried looking for some solution, but it looks like the only way would be to use the msbuild targets to run a script prebuild to copy the files if docfx is missing.

**Comment by vicancy** [comment]
Hi @jhermsen Thanks for the investigation, I am going to call `docfx init` first if `docfx.json` is not detected in the project... `docfx init` need to be enhanced to allow parameters to specify the input projects and output folder

**Comment by jobubo** [comment]
@vicancy Thank you for fixing this bug!
