### ISSUE TITLE
References between projects

### ISSUE THREAD

**Issue by oliverangermueller** [dotnet/docfx#2148]
[Files.zip](https://github.com/dotnet/docfx/files/1414643/Files.zip)
**DocFX Version Used**: docfx 2.22.2.4

**Template used**: default

Hello,

I have a question concerning references between different solutions. It seems that the cref attributes are not resolved.

The attached sample contains two solutions. ClassLibrary1 defines an Interface. ClassLibrary2 contains an implementation of that interface with cref attributes pointing to the interface in ClassLibrary1.

First I built the documentation based on the cs files. This results in html files for interface and the implementation. But the crefs of ClassLibrary2 are not resolved:
The comment 
**Base implementation of the interface &lt;see cref="ClassLibrary1.IExporter"/&gt;.**
is shown in the html page as 
**Base implementation of the interface .**

Then I built the documentation based on the dll and xml files. In that case only the html files for ClassLibrary1 were created and none for ClassLibrary2.

I attached all source files, templates and logs.

Maybe you have an idea how I can resolve our problem.

Best regards,
Oliver

**Comment by superyyrrzz** [comment]
I cannot reproduce this issue. Just have some test, the link works fine, both from source code and assembly files.

![image](https://user-images.githubusercontent.com/3831744/55223588-7c1ee300-5249-11e9-9565-aac4cfcf705f.png)

Can you confirm the issue still happening?
