### ISSUE TITLE
Docfx Comment API generated not support some advantage tag like bullet

### ISSUE THREAD

**Issue by tungnt185** [dotnet/docfx#215]
Hi all,

I've generated api help using Docfx but it not support some tag in .NET comment like: list, bullet, typeparam, para, dictionary&lt;int&gt;. SandCastle support this.
Do you have any plan to add these tags in next version?

Regards
Tung

**Comment by ansyral** [comment]
@tungnt185 it is already supported in dev.

**Comment by odalet** [comment]
I wonder if an improvement to list handling could be implemented:

The following C# xml comment:

```xml
<list type="bullet">
<item>This method is for testing purpose</item>
<item>It's useless to call it</item>
</list>
```

generates this yaml:
```yaml
remarks: "\n<ul><li></li><li></li></ul>\n"
```

I know I should enclose my text in `<description>` tags. However I think it would be useful to also support the form with only the `<item>` tag.
