### ISSUE TITLE
Removing excess information in search results [Question]

### ISSUE THREAD

**Issue by ashengilevych** [dotnet/docfx#2154]
Can I customize the search results by removing certain information from there? For example, there is a [page](https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_generate_pdf.html)

As a result of the search, there is a block 

![screen_1](https://user-images.githubusercontent.com/23631040/32050654-4fe80042-ba5a-11e7-8f2d-5c6677456f40.png)

which corresponds to the following: 

![screen_2](https://user-images.githubusercontent.com/23631040/32050657-5704ec28-ba5a-11e7-8f65-4cab3bcd07ef.png)

but I don't want to show it.

Is there a way to remove it?

Thanks. Waiting for your reply.

**Comment by superyyrrzz** [comment]
You can update the template to filter out some content:

https://github.com/dotnet/docfx/blob/3258bcd90c99993501c4e05732b3830b77167a99/src/docfx.website.themes/default/styles/docfx.js#L290
