### ISSUE TITLE
SerializationException if memberpage template is used

### ISSUE THREAD

**Issue by takerukoushirou** [dotnet/docfx#2155]
**DocFX Version Used**:
2.26.3 on macOS 10.12, installed via Homebrew (which uses the official release Zip from GitHub and runs DocFX using `mono`).

**Template Used**:
1. `default`
2. `memberpage.2.26.3/content`

**Steps to Reproduce**:
1. Create empty test directory, add new documentation sub-directory.
1. Navigate to documentation directory and run:
  `nuget install memberpage -OutputDirectory obj/ -Version 2.26.3`
1. Download DocFX configuration from [GitHub Gist](https://gist.github.com/takerukoushirou/a4b1c7cdedf6c274bb253e566b6144ab) and place DocFX.json in the documentation directory.
1. As compilation with .NET Core on macOS isn't available yet, assemblies are referenced instead. Replace the example assembly file in the configuration by another assembly of choice or download the corresponding NuGet package. In the example configuration, the assembly is located in a project directory that is a sibling to the documentation directory.
1. Navigate to the documentation directory and run `docfx DocFX.json`.

**Expected Behavior**:
DocFX successfully renders documentation.
_Last successful run was on version 2.24.0 with the exact same configuration._

**Actual Behavior**:
DocFX fails with error: `System.Runtime.Serialization.SerializationException: Type 'Microsoft.DocAsCode.Plugins.SitemapOptions' in Assembly 'Microsoft.DocAsCode.Plugins, Version=2.26.3.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.`
See previously mentioned Gist for the full output.

If the `memberpage` template is removed from the configuration, the error does not occur.

**Comment by takerukoushirou** [comment]
**Update**: I tested all previous versions released for `docfx.console` on NuGet, up to 2.24.0, which is the last version where the problem does not occur. The issue appears from version 2.25.0 onwards.

**Comment by vicancy** [comment]
Thank you for reporting the issue @takerukoushirou Should be introduced by https://github.com/dotnet/docfx/pull/2070, will fix.
