### ISSUE TITLE
DocFx VS Code extension preview doesn't show line breaks within a table cell

### ISSUE THREAD

**Issue by icnocop** [dotnet/docfx#2167]
**DocFX Version Used**: 
Visual Studio Code 1.17.2
DocFX Extension 0.1.0

**Steps to Reproduce**:

1. Create a new markdown file.
2. Insert the following
```
test 1  
test 2  

<table>
<tr>
<td>
test a  
test b
</td>
</tr>
</table>  
```
3. Preview the file

**Expected Behavior**:
I expected that "test a" and "test b" appear on separate lines.

**Actual Behavior**:
"test a" and "test b" appear on the same line.

Side note: Even though the preview displays them on the same line, the generated HTML using the default template will display them on separate lines as expected.

Thank you.

**Comment by 928PJY** [comment]
hi, @icnocop this issue has been fixed, please upgrade your VS Code extension to [v0.1.1](https://marketplace.visualstudio.com/items?itemName=ms-docfx.DocFX)
