### ISSUE TITLE
Register and report dependency type, is there full example?

### ISSUE THREAD

**Issue by nstvsn** [dotnet/docfx#2169]
Hi!
I'm sorry for that, let me ask you please about custom dependency type?
I could not understand how to work with it. Existing example shows how to register a custom type, but what is the next step? Maybe you have some full examples which can help me (or maybe others) to get it work?

Sorry and thank you in advance.

**Comment by superyyrrzz** [comment]
This is some implementation details of docfx's incremental build architecture. What is your scenario to add a new one?
