### ISSUE TITLE
Navbar takes up all space on page

### ISSUE THREAD

**Issue by jahav** [dotnet/docfx#2182]
I wanted to fix a few typos in the docs so I forked project, created branch and then tried to build docs using DocFX. The resulting documentation is unusable for browsing in localhost:8080.

I followed directions from 
https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md#windows-instructions

**DocFX Version Used**: 
docfx 2.27.0.0

**Template used**: (`default` or `statictoc` or contain custom template)

default

**Steps to Reproduce**:

1. Make a fresh checkout (in my case c:\Users\Honza\Projects\docs\)
2. Install docfx (using zip, not chocolatey)
3. Add it to path (mine was c:\Users\Honza\progz\docfx\, so no spaces)
4. Go to the docs directory (mine is C:\Users\Honza\Projects\docs)
5. run "docfx -t default --serve" in cmd.exe (without admin, I tried with admin, no change)

**Expected Behavior**:
I would be able to browse the build docs website.

**Actual Behavior**:
It churns files for quite a while, writes thousands of warnings and ends with 
Serving "C:\Users\Honza\Projects\docs\_site" on http://localhost:8080

The site is unusable - the front page can't scroll (I always see what is on the top of the page despite scrollbar moving). When I try to click on any link that I can see, I get an error This localhost page can't be found. It turned out that if I decrease width of browser, I get a mobile site where it is possible to scroll. 

I though that by "navigate to the docs directory" you might mean docs directory in the repo, alas running docfx in that directory fails because of missing docfx.json:
[17-11-09 11:57:04.566]Error:Config file docfx.json does not exist!
Build failed.
[17-11-09 11:57:04.566]Error:Config file docfx.json does not exist!
        0 Warning(s)
        1 Error(s)

The website didn't work in Chrome, nor Firefox, nor IExplore 11. I am using Windows 7.

Am I missing something obvious?

![docs - front page](https://user-images.githubusercontent.com/7634052/32635829-37149996-c5b2-11e7-8c27-30414f8ce7ff.PNG)
![docs - link](https://user-images.githubusercontent.com/7634052/32635837-3c7cf3ce-c5b2-11e7-8a21-28da6bc44796.PNG)
[docfx-log.zip](https://github.com/dotnet/docfx/files/1459588/docfx-log.zip)

**Comment by vicancy** [comment]
Hi @jahav, for `docs` repo, the general suggestion is to run `powershell openpublishing.build.ps1` for local build. For docfx's `default` template, it takes the first level `toc.yml` as the navbar which makes it unreadable. `openpublishing.build.ps1` will do some configuration for you so that it uses `docs` specific template to render the page.

**Comment by jahav** [comment]
Thanks for the advice about openpublishing.build.ps1, unfortunately it ends up with an error (possibly private repo).

> [20:52:31.248856Z]: Start to clone https://github.com/Microsoft/templates.docs.msft repository to folder C:\Users\Honza\Projects\docs\_themes.
> Clone https://github.com/Microsoft/templates.docs.msft to folder C:\Users\Honza\Projects\docs\_themes failed. 
> Error: Cloning into 'C:\Users\Honza\Projects\docs\_themes'... remote: Repository not found. fatal: repository 'https://github.com/Microsoft/templates.docs.msft/' not found

That is an issue for dotnet/docs repo, fixing navbar is this issue (most of front page links are still 404, but when I navigate to areas I am interested, it works there).

**Comment by KargWare** [comment]
I have exactly the same issue. I am able to run docfx, but I only see the navbar (inbetween I can see the rendered md-file for round about a second, then the navbar covers everything). When I am using the ps1 script, like suggested above, I get an error that I cannot access the templates from github.

How should we see the changes locally before we start a Pull Request? Is there any example how-to-build the documentation on a local system?

I am working on Windows 10.

**Comment by vicancy** [comment]
cc @herohua

**Comment by KargWare** [comment]
What does cc ... mean?

**Comment by superyyrrzz** [comment]
@KargWare Although you can see `docfx.json` in this repo, you can not build it using DocFX directly. docs.microsoft.com site uses a DocFX with many internal plugins to build, which makes it almost impossible to get the same result locally.

If you'd like to preview the change before creating PR, [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack) can help.

**Comment by Gabriel-RABHI** [comment]
Same problem...
