### ISSUE TITLE
generate different file extension than HTML for the generated documentation

### ISSUE THREAD

**Issue by estoeva** [dotnet/docfx#2211]
**DocFX Version Used**: 
The newest version
**Template used**: (`default` or `statictoc` or contain custom template)
default
**Steps to Reproduce**:
-----

**Expected Behavior**:
Generate files with aspx extension instead of html

**Actual Behavior**:

**Comment by vicancy** [comment]
May I ask the background for using `aspx` for static html files? @estoeva

**Comment by estoeva** [comment]
Hello, 
we want to put our documentation site directly on share point. If we use html extension, when the files is opened it is not displayed as web page, instead, a source is displayed. If the extension is aspx, the page is displayed as in a web browser.
Meanwhile  I successeded to change the extension using templates, just changing the name of the template file from html to aspx, BUT links is not changed this way. 
I am still looking for a solution.
Thank you

**Comment by vicancy** [comment]
Is https://stackoverflow.com/questions/11501462/static-html-page-as-sharepoint-page an alternative approach? 
Currently there seems no easy way to change the extension, as we only resolve links when extension is html, yeah, that's an issue, and we have to design a way to solve that.

**Comment by Code-DJ** [comment]
Hi, How is it done on docs.microsoft.com where none of their pages have a .html extension? If it a special website, is that code also available? Thanks!
