### ISSUE TITLE
Consolidating languages support to UniversalDocumentProcessor

### ISSUE THREAD

**Issue by vicancy** [dotnet/docfx#2220]
We are consolidating different languages into going through one UniversalDocumentProcessor, including TypeScript(https://github.com/docascode/type2docfx), JavaScript(https://github.com/docascode/Node2DocFX), and Python(https://github.com/docascode/sphinx-docfx-yaml)... 
* [x] 1. A template for UniversalDocumentProcessor
* [ ] 2. Intuitive tutorial/guidance on how to enable the feature
  * [x] JavaScript
  * [x] TypeScript
  * [ ] Python

Related issues: #2218, #157, #915

**Comment by crazyfx1** [comment]
When is this going to be released? I'm eager to try out the typescript documentation ;)

**Comment by superyyrrzz** [comment]
@crazyfx1 2.29 will contains JavaScript support. We will consider add TypeScript support in 2.30.

**Comment by crazyfx1** [comment]
What is missing for typescript support? I thought I just can use the type2docfx tool to generate yml files and use them the same way as the javascript yml files.

**Comment by superyyrrzz** [comment]
I'm afraid the current template isn't general enough for type2docfx YAMLs. Still need some test to confirm it works.

**Comment by leopignataro** [comment]
@superyyrrzz does 2.29+ really support JavaScript? If so, were can we find documentation on how to use it? A few questions already come to mind:

1. On the metadata/src/files array of our docfx.json, we have the path for csproj files. What will be the case for JS files?
2. What is the syntax for the comments on the JS code?

We're excited with this update, we've been wanting this for quite a while!

**Comment by crazyfx1** [comment]
@leopignataro The documentation can be found here, but I don't know why it's not visible from the TOC ;)
https://dotnet.github.io/docfx/tutorial/universalreference/gen_doc_for_js.html

**Comment by superyyrrzz** [comment]
@leopignataro As in JavaScript, the comments should use [JSDoc](http://usejsdoc.org/) sytnax
@crazyfx1 My fault... forgot changing the TOC...

**Comment by ovasquez** [comment]
Is there any way to help speeding up the support for typescript?

**Comment by superyyrrzz** [comment]
@ovasquez We still have some template issue to handle generic types of typescript, which will lead to missing link for them in html. We are now lack of resource to support this as typescript support is more complicate than expected.

**Comment by superyyrrzz** [comment]
v2.33 supports TypeScript: http://dotnet.github.io/docfx/tutorial/universalreference/gen_doc_for_ts.html

**Comment by crazyfx1** [comment]
Great news.

Is there some additional documentation for the `ts-reference-ci-scripts` tool? It seems like it is checked in on a private vsts. I always get the message `No source file for mypackage`.
