### ISSUE TITLE
No Artifacts folder generated on build

### ISSUE THREAD

**Issue by JeremyTCD** [dotnet/docfx#2235]
**DocFX Version Used**: v2.27

**Steps to Reproduce**:

1. Clone docfx
2. Checkout v2.27
3. Run build.cmd (following instructions [here]( https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#5-build-from-source-code))

**Expected Behavior**: Artifacts folder generated.

**Actual Behavior**: No artifacts folder generated.

**Comment by vicancy** [comment]
Hi @JeremyTCD I can't repro locally and CI is also running well. Could you run `build.cmd > log.txt` and provide me the log.txt?

**Comment by JeremyTCD** [comment]
Hmm I cloned a fresh copy and ran build.cmd again, still no artifacts folder. This is my log:
[log.txt](https://github.com/dotnet/docfx/files/1512567/log.txt). Thanks

**Comment by vicancy** [comment]
Took a look at the log.txt, the test failures are caused by https://github.com/dotnet/docfx/issues/1969 , run `build.cmd` from *Developer Command Prompt for VS2017* can probably workaround the test failure.
