### ISSUE TITLE
Feature proposals link in readme goes to error page

### ISSUE THREAD

**Issue by sandersaares** [dotnet/docfx#2258]
Clicking the "Feature Requests" link in the readme takes me to the following error page:

![image](https://user-images.githubusercontent.com/9914262/33506990-19d49c9a-d6a7-11e7-9277-af02522ea1bd.png)

**Comment by superyyrrzz** [comment]
Seems feathub is not available at that time and it's fine now. Can you have another try?

**Comment by sandersaares** [comment]
Yep looks like it works fine now.
