### ISSUE TITLE
[Question] docfx project with git under tfs

### ISSUE THREAD

**Issue by aktzbn** [dotnet/docfx#2270]
I'm trying to create `docfx` project. Sources are hosted on `TFS` server in `GIT` repository.

Everything is ok except absence of __Improve this Doc__ link.

Is there way to make this link appear and work for such configuration?

**Comment by superyyrrzz** [comment]
@aktzbn Can you give a sample of what the URL of a specific file on TFS server looks like?

If the URL is like github or vsts, `_gitUrlPattern` config will work for you. If not, this will be a feature request.

**Comment by aktzbn** [comment]
Something like this http://HOST:8080/tfs/COLLECTION_NAME/PROJECT_NAME/_git/REPO_NAME.

**Comment by aktzbn** [comment]
It seems that I'm not alone https://stackoverflow.com/a/47712589/2064680.

Any news on this?

**Comment by superyyrrzz** [comment]
As TFS is somehow like self hosted VSTS, their URL looks in same pattern. You can try add the following section into `docfx.json`:
``` json
    "globalMetadata": {
      "_gitUrlPattern": "vso"
    },
```

**Comment by aktzbn** [comment]
Did not help.

**Comment by aktzbn** [comment]
It works now. Thank you.

**Comment by tuga1975** [comment]
The information about what and how to populate these properties should be on documentation.

**Comment by superyyrrzz** [comment]
@tuga1975 Maybe not obvious, but the [user manual](http://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#322-reserved-metadata) mentioned the usage of `_gitUrlPattern`.
