### ISSUE TITLE
Improve this Doc Button Issue

### ISSUE THREAD

**Issue by scirneanu** [dotnet/docfx#2278]
I have a project developed using the DocFX framework. The project is hosted in GitHub: one branch for the DocFX specific files and second branch for the generated files after building the project. The second branch is connected with GitHub Pages which is used to host the project.

The issue is that when I access the project from my custom domain, the button Improve this Doc is opening an undefined link https://github.com/{organization_name}/{repository_name}/blob/origin/master/{path_to_the_page} in which the **origin** word is added.

On the other hand, if I build the project in my local machine, the button opens the correct link(without the origin word).

**Comment by superyyrrzz** [comment]
Do you mean, if you build the site from different machines, the link is different? DocFX will try fetch the current git information when building document. Before build document, you can try the following command to see whether configs are the same:
```
git config --get remote.origin.url
git rev-parse --abbrev-ref @{u}
```
