### ISSUE TITLE
xrefService for .NET BCL

### ISSUE THREAD

**Issue by Jjagg** [dotnet/docfx#2283]
If I understood the docs right, it should be possible to use the xrefService element to look up .NET library classes by adding the following to `build` in `docfx.json`.
```
"xrefService": [
  "https://xref.docs.microsoft.com/query?uid={uid}"
],
```

docfx manages to build the project without any errors/warnings, but in my API reference .NET types do not link to their respective reference pages. Am I missing someting or is this an actual bug?

**DocFX Version Used**: 2.28.2.0

**Template used**: default

**Comment by vwxyzh** [comment]
@Jjagg I think the config is correct.
Can you give me a reproduce repo?

**Comment by Jjagg** [comment]
Yes, I'll set one up :)

**Comment by Jjagg** [comment]
@vwxyzh Reopening because it's definitely a bug, rather than me messing up.

Here's a repro-repo: https://github.com/Jjagg/docfx-xrefService
This seems like a very specific issue. When I override `Equals(object)`, `System.Object` is not properly linked. In the reproduction, if you comment out the `Equals(object)` method from the Class1.cs file it will work as it should and link to the `System.Object` reference page.

**Comment by vwxyzh** [comment]
@Jjagg Something wrong in metadata step:
you can found the comment id is an error type: `!:System.Object`
```yaml
- uid: System.Object
  commentId: '!:System.Object'
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
```

**Comment by Jjagg** [comment]
I'll have a stab at fixing this. If anyone can give me some pointers as to where the issue might be and maybe about the general structure of docfx, that would be much appreciated :)

**Comment by Jjagg** [comment]
Further experimentation indicates the `System.Object` item is put in the metadata file for `Class1` whenever it is present in its public API (except for the inheritance). In the succesful case, there is no `System.Object` item in the metadata file. 

Seems like it tries to resolve the `System.Object` reference locally in the metadata step while it shouldn't. Because this leaves an item in the metadata, the reference won't be resolved using the xrefService in the build step.

**Comment by vwxyzh** [comment]
@Jjagg it is a bug.

**Comment by Jjagg** [comment]
I forgot to close this issue, but this is working great now! Thanks! :)
