### ISSUE TITLE
Create more attractive themes as similar to other static website generator

### ISSUE THREAD

**Issue by vicancy** [dotnet/docfx#2298]
[Gain 30 upvotes from feathub feature request dashboard.]
For example: 
hexo: https://hexo.io/themes/

Related: https://github.com/dotnet/docfx/issues/1862

- [x] Typescript and scss
- [x] Visual regressing testing
- [x] Clean scripts and stylesheets
- [x] Bootstrap 5
- [x] Dark theme
- [x] Update docs to use modern template
- [x] .NET API affix
- [x] Tabbed conceptual dark mode
- [x] ~~Scrollspy~~ https://github.com/twbs/bootstrap/issues/36431
- [x] Text-break
- [x] Polish modern template

**Comment by mozts2005** [comment]
hey based on my read of the code the current themes are based on bootstrap with very little work a Sass compiler could be added to the current build. Once that is done with very little extra work the current default thems could be tooled to support any bootstrap theme. 

this would allow themes from themes.getbootstrap.com and https://bootswatch.com/ to be used with little to no work.

**Comment by superyyrrzz** [comment]
@mozts2005 Sounds cool! Looking forward to it.

**Comment by perlun** [comment]
I agree, adding support for SASS would be _incredibly_ nice indeed. :+1: :+1: :+1:

**Comment by yufeih** [comment]
The new template shipped in [v2.63.0](https://github.com/dotnet/docfx/releases/tag/v2.63.0).

**Comment by iadonkey** [comment]
is there a way to combine the modern theme with statictoc if I want to have beautiful pages that I can preview locally? I tried to put statictoc + modern in the the template section of the config file, but then the toc was missing when viewing locally
