### ISSUE TITLE
Do not show Parameters and Returns if there are no corresponding tags in comments

### ISSUE THREAD

**Issue by andreycha** [dotnet/docfx#2305]
**DocFX Version Used**: 2.28.2

**Template used**: default

I have following code:

```
/// <summary>
/// See <see cref="Fixture.FindTag(int, TagType)"/> for detailed information.
/// </summary>
public FixtureTag FindTag(int value, TagType type)
{
    ...
}
```

Here is what generated and displayed in API docs:

![image](https://user-images.githubusercontent.com/1696046/33886722-cc76e12a-df47-11e7-8904-c6fd6a295f04.png)

The thing is that I deliberately omitted `<param>` and `<returns>` tags, and I'd expect them not showing in docs as well.

Please consider removing these data from metadata/UI if there are no corresponding tags in comments. E.g. there is no Exceptions section if there are no `<exception>` tags.

**Comment by vicancy** [comment]
I agree that if there is no `exception` tag in comment there should not be Exception section in UI. 
But in the `param` and `returns` case, it not only contains descriptions from comment, but also `Type` that links to some other pages, in your case, `FixtureTag` is clickable. So I doubt if this is a general request.

There is a feature to make the syntax clickable. When that feature is implemented, we can for sure remove these sections when comment does not exist.

For now, there is a quick way to achieve this though, to custom the partial template `class.tmpl.partial` by adding `{{description}}` existence check....

What's your idea @andreycha ? Please feel free to let me know your suggestions and concerns.

**Comment by andreycha** [comment]
Changing `class.tmpl.partial` is fine for me, thanks for the hint!

And yes, I agree that when syntax becomes clickable, hiding empty sections can be made a general behavior.

**Comment by suzdalnitski** [comment]
@vicancy 
@andreycha 

Can you please provide me with a sample `class.tmpl.partial` template to exclude empty `{{description}}` blocks? I'm just getting started with docfx, and this is way over my head...

Thank you!

**Comment by andreycha** [comment]
@suzdalnitski for example here is `return` block from `class.tmpl.partial`:

```
{{#return}}
<h5 class="returns">{{__global.returns}}</h5>
<table class="table table-bordered table-striped table-condensed">
  <thead>
    <tr>
      <th>{{__global.type}}</th>
      <th>{{__global.description}}</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{{type.specName.0.value}}}</td>
      <td>{{{description}}}</td>
    </tr>
  </tbody>
</table>
{{/return}}
```

all you need is to wrap its content into `{{#description}}{{/description}}`, where `#` means that the block will not be generated if `description` is empty:

```
{{#return}}
{{#description}}
...
{{/description}}
{{/return}}
```
