### ISSUE TITLE
Cross-reference from REST (Swagger) docs to C# API docs?

### ISSUE THREAD

**Issue by prochnowc** [dotnet/docfx#2311]
Question: Is it possible to have cross-references from REST API docs to the C# API docs?

We have generation of C# and REST API docs in one DocFX project. Currently in the REST docs, when some C# type is referenced in the swagger spec we can only see "T:namespace.some.typename" in the docs.

Might it be possible to add support for cross-references from REST to the C# api?

**Comment by superyyrrzz** [comment]
Cross reference is determined by **uid**, which is uniform across C# reference and REST API document. So I think your scenario should work by default.

Some questions:
* Which part of the spec do you write the cross reference in?
* How do you use the cross reference? Like `@namespace.some.typename`?

**Comment by prochnowc** [comment]
Currently i do not add explicit cross reference. My swagger spec contains eg.: 

```
"responses": {
          "202": {
            "description": "List of T:Validation.ValidationResult."
          },
```

The swagger spec is generated from source code using NSwag. The descripton for the response contains <see cref="Validation.ValidationResult" /> in the xml doc.

I would like to automatically have cross-reference from REST API doc to the C# API doc.

**Comment by prochnowc** [comment]
@rsuter what do you think?

**Comment by RSuter** [comment]
In the latest version of NSwag your description is no longer generated as

    "List of T:Validation.ValidationResult."

but is now

    "List of ValidationResult."

In the long term I'd like to add custom properties to types/schemas to link them to the generated client/DTO classes.

**Comment by prochnowc** [comment]
@superyyrrzz So what would be my option to have cross-reference generated from xml docs? Using `@namespace.some.type.name` in the xml descriptions? I think NSwag should simply put this into the schema and then it would be visible to DocFx.

**Comment by RSuter** [comment]
Ok let's assume that NSwag reads "List of <see cref="Validation.ValidationResult" />.". Most users expect to just use "List of ValidationResult." as description, they don't want to leak internal implementation details out of their API... If we add for example an option to generate directly "List of <see cref="Validation.ValidationResult" />." as description, how would this be linked to docfx page? How are you rendering/displaying the swagger spec?

**Comment by prochnowc** [comment]
You are right when saying that the C# model is an implementation detail. So it might be not feasible to have cross-reference from REST doc to C# doc.

Unfortunately DocFx does not even show the swagger spec models in the REST doc. Neither for parameters nor for responses :(

**Comment by vicancy** [comment]
@prochnowc One way to achieve this is that change the descripton for the response contains `<see cref="Validation.ValidationResult" />` in the xml doc into `<xref uid="Validation.ValidationResult">`, this is a special syntax supported in DocFX, and it can avoid NSwag from processing it and meanwhile let DocFX resolve it from C# projects, if C# and REST files are built together.
