### ISSUE TITLE
XSS security flaw in Docs

### ISSUE THREAD

**Issue by LordMike** [dotnet/docfx#2318]
**DocFX Version Used**: 
The live one, at docs.microsoft.com, see below.

**Template used**: (`default` or `statictoc` or contain custom template)
N/A

**Steps to Reproduce**:

1. Write HTML in API documentation
2. Wait for docs to be regenerated
3. ... profit

**Expected Behavior**:
User-content emitted to HTML should be HTML-encoded.

**Actual Behavior**:
User-content emitted to HTML is not HTML-encoded.

----

Hello,

I believe there is an XSS vulnerability in Microsoft Docs. This example page shows the flaw:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.razor.taghelpers.tagstructure?view=aspnetcore-2.0

The docs for the `NormalOrSelfClosing` enum element should have read:
Element can be written as `<my-tag-helper></my-tag-helper>` or `<my-tag-helper />`.

But instead the HTML in the explanation is rendered verbatim [A1, A2] leading to a persistent XSS.

The original source documentation for `NormalOrSelfClosing` is found here:
https://github.com/aspnet/Razor/blob/bdbb854bdbde260b3c70f565a93ebbb185a7c5a7/src/Microsoft.AspNetCore.Razor/TagHelpers/TagStructure.cs#L17-L20

From that, we can gather that the documentation generator has re-printed the documentation on the enum member (and probably everything else) verbatim in the output, leading to a persistent XSS for users with write-access to the respective repositories. As the docs are HTML-encoded to begin with, it can be hard for reviewers to decipher a potential XSS in a length documentation snippet in a PR from a contributor.

Pictures:
* [A1](https://user-images.githubusercontent.com/1027111/34082927-92f9d686-e367-11e7-90c1-e9e43a3fbd9a.PNG) -- the output on the website is missing the two tag-helper HTML snippets.
* [A2](https://user-images.githubusercontent.com/1027111/34082928-9313d8d8-e367-11e7-8fc6-5bf8c9efbcef.PNG) -- in the source of the webpage, we can see the parts of the docs interpreted as HTML.

---

Disclaimer: I reported this to secure@microsoft.com, but was informed that it "_[..] wouldn't meet the bar_" for a security vulnerability.

**Comment by vicancy** [comment]
Thanks @LordMike for reporting the issue. I will redirect the issue to the right guys and update you with any updates from them.
