### ISSUE TITLE
word "class" in a md file is excluded

### ISSUE THREAD

**Issue by estoeva** [dotnet/docfx#2324]
**DocFX Version Used**: latest

**Template used**: custom template

**Steps to Reproduce**:

1. Set in a MD file a link to a file which name contains the word Class. In the generated file the word class and 4 simbols after are excluded.

**Comment by vicancy** [comment]
Hi @estoeva I can't repro it locally. Could you provide that MD file with detailed content?

**Comment by yufeih** [comment]
Closing this one due to lack of details.
