### ISSUE TITLE
DocFx Template hierarchy customization output 

### ISSUE THREAD

**Issue by ahmeturganci** [dotnet/docfx#2329]
**DocFX Version Used**: 2.28.0

**Template used**: `default` 

**Steps to Reproduce**:

1. ` docfx docfx.json -o C:/sDoc --serve `
Gives me this output
![output-docfx](https://user-images.githubusercontent.com/13600735/34297081-f81f9196-e726-11e7-9161-580736b1f2fd.png)
2. output hierarchy
`     -namespace 
          -class - assembly
           -method` 
**Expected Behavior**:
but I need this hierarchy
     `-assembly 
       -namespace
          -class
            -method`
**Actual Behavior**:
Gives output on the 2nd item

[Config file](https://ybin.me/p/e1dba60436a662ba#CxNtMwHXtyj/bKj5Nu5Ap8JbtAFdn4ifElkdXHxOZfU=)

**Comment by emre-aki** [comment]
I have the same issue.

**Comment by ahmeturganci** [comment]
Is there any update on this?

**Comment by superyyrrzz** [comment]
@ahmeturganci Sorry I still can't get your ideas. DocFX has namespace page listing all the including classes, and class page listing including methods. Do you mean you need a assembly page listing all the including namespace?

**Comment by ahmeturganci** [comment]
Thanks for answer question 
Yes, I need a assembly page listing all the including namespace.
my project hierarchy [this](https://ibb.co/hVtzqG)
I need a document 
-A
--A.Apps
--- A.App1
---- . . . other Project 
-B
--B.Apps
--- B.App
---- . . . other Project
-C
--C.Apps
--- C.App
---- . . . other Project

**Comment by vwxyzh** [comment]
@ahmeturganci 
You can config a set of `metadata` items in the `docfx.json`, and each one only contain one project.
Then manual write a root toc, reference all toc of projects.

**Comment by ahmeturganci** [comment]
I have no idea about root toc writing. Do you give me an idea?

**Comment by vwxyzh** [comment]
@ahmeturganci the root toc likes following:
```md
# A
## A.Apps
### [A.App1](yours/A.App1/yaml files folder/)
### other projects...
# B
...
```
