### ISSUE TITLE
Suppress warning about duplicate members when source files are identical

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/docfx#2330]
**DocFX Version Used**: 2.29.0.0

**Template used**: `default`

**Steps to Reproduce**:

Create two projects that both link the same file from somewhere else.

    ProjectA
    - linked: ../Shared/Foo.cs
    ProjectB
    - linked: ../Shared/Foo.cs

Run docfx over both projects

**Expected Behavior**:

Shouldn't offer any warnings. These should appear as they do in the binary: two separate classes, even if in the same namespace.

**Actual Behavior**:

Receive a (slightly humorous) warning:

> Warning:[MetadataCommand.ExtractMetadata]Duplicate member `Foo.Bar` is found from `../Shared/Foo.cs` and `../Shared/Foo.cs`, use the one in `../Shared/Foo.cs` and ignore the one from `../Shared/Foo.cs`

Given they're the same source paths, I would expect the warning to be suppressed.

**NOTE** I believe this to be a special case of issue to #2320 that likely has a simpler resolution.

**Comment by vwxyzh** [comment]
@drewnoakes 
1. metadata project A then B (in docfx.json, `metadata` is an array).
2. use merge two output files.
3. build documents.
