### ISSUE TITLE
Document APIs using Reflection

### ISSUE THREAD

**Issue by KenCox** [dotnet/docfx#2335]
I may have missed it but is there a way for DocFx to document assemblies using reflection? My client doesn't provide the source code - just compiled assemblies.

I currently use Sandcastle (https://github.com/EWSoftware/SHFB).

Thanks,

Ken

**Comment by vicancy** [comment]
Yes it does. Simply take assemblies as a kind of source code, put it to `"files": ["**/*.dll"]`. You can also put xml files with the same file name along with the dll and DocFX will automatically load the xml to get the comments.
