### ISSUE TITLE
Error extracting metadata for D:/MySolution.sln: Unable to generate spec reference for !:IFormTest

### ISSUE THREAD

**Issue by JackJCSN** [dotnet/docfx#2336]
**DocFX Version Used**: 
docfx.console 2.28.3
**Template used**: (`default` or `statictoc` or contain custom template)
default
**Steps to Reproduce**:

1. The is two projects in my Solution
   one of them is a csproj and the other one is vbproj
   in csharp I declarat a interface like this 

using System.Windows.Forms;

namespace Lib.Forms.Test
{
    public interface IFormTest
    {
        bool BeforeClick(Control ClickedControl);
    }
}

And I used it in the vbproj

Imports Lib.Forms.Test

Partial Public Class DemoSearchForm
    Implements IFormTest

End Class

2.  I was using follwing docfx.json to build then I got an error.
`{
  "metadata": [
    {
      "src": [
        {
          "src":"../",
          "files": [
            "**/MySolution.sln"
          ],
          "exclude": [
            "**/obj/**",
            "**/bin/**",
            "_site/**"
          ]
        }
      ],
      "dest": "api"
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [
      "default"
    ],
    "postProcessors": [],
    "noLangKeyword": false
  }
}`

**Expected Behavior**:
   Build without error.
**Actual Behavior**:
build with an error like this.
`{"message":"Error extracting metadata for D:/MySolution.sln: Unable to generate spec reference for !:IFormTest","date_time":"2017-12-27T12:22:20.1796942Z","message_severity":"error","correlation_id":"1DE93A24-A4E8-4F6D-85DA-25A1134F7219.2"}
`

**Comment by vicancy** [comment]
Type is not correctly resolved. did you run `dotnet restore` before running docfx?

**Comment by JackJCSN** [comment]
Thank you for your help.  I am trying to run `dotnet restore`  and it returns following message.
"Nothing to do. None of the projects specified contain packages to restore."
Is there any other options to help me to location the unresolved types?
The solution is build and run successfully so that should not have unresolved types.
"IFormTest" in the error message was an interface in my project so it also should be resolved.

**Comment by vicancy** [comment]
@JackJCSN could you provide a simple test project that can repro the issue so that I can take a look?

**Comment by superyyrrzz** [comment]
repro repo: https://github.com/superyyrrzz/TestCsWithVb

**Comment by JackJCSN** [comment]
This problem was fixed with Version 2.48.1
