### ISSUE TITLE
Using xrefmap.yml from another project

### ISSUE THREAD

**Issue by JohnSL** [dotnet/docfx#2346]
**DocFX Version Used**: docfx.console 2.28.3

**Template used**: (`default` or `statictoc` or contain custom template): default

I'm trying to figure out how to use an xrefmap.yml from another project. For security reasons, we can't download the file during build time, so we have to use a static file. How do we let DocFx know the URL for the web site that is hosting the output of that xrefmap.yml file?

**Comment by superyyrrzz** [comment]
It's also supported to point to a local file. See: https://github.com/dotnet/docfx/blob/3290c9835adefeff39a861578b20f57d739b43cd/Documentation/docfx.json#L41

**Comment by vwxyzh** [comment]
@JohnSL 
1. download xrefmap by command `docfx download your_archive.zip -x http://some.live.site`
2. copy xrefmap to your repo or prepare it before your build document.
3. modify `docfx.json`, add xref configuration to your local achieve file.

**Comment by JohnSL** [comment]
@superyyrrzz, yes, I know. That still doesn't answer the question about how DocFx will know the base URL to use for the references. The `xrefmap.yml` file doesn't seem to contain the URL.

@vwxyzh, that doesn't work because authorization is done via Azure Active Directory, so I get the following:

[18-01-05 05:17:58.698]Error:[Archive](map.zip)Unable to create archive: The remote server returned an error: (401) Unauthorized.

**Comment by vwxyzh** [comment]
@JohnSL please manual download xrefmap.yml file.
Then open the file by editor, add one line:
```yaml
baseUrl: http://your.base.url/
```

**Comment by JohnSL** [comment]
It's resolving the reference, but not creating the correct URL. Here's what I did:

* Added a reference to the xrefmap.yml that I retrieved from the site:

```json
"xref": [
  "xref/root/xrefmap.yml"
],
```
* Edited the xrefmap.yml so the top looks like this (actual site name replaces with xxxx):
```yml
### YamlMime:XRefMap
baseUrl: https://xxxx.azurewebsites.net/
sorted: true
references:
```
The URL that was generated for the link does not contain the URL above--it was created relative to the project I'm building. Is there some other step required?

**Comment by vwxyzh** [comment]
@JohnSL it is a code bug.

**Comment by JohnSL** [comment]
@vwxyzh , thanks. Can you give me an idea of when an updated NuGet package will be available with this fix? I'm using the docfx.console NuGet package.

**Comment by vwxyzh** [comment]
@JohnSL we will release it in next Monday, is it so urgent?
Or you can try our [dev feed](https://myget.org/gallery/docfx-dev)

**Comment by vwxyzh** [comment]
@JohnSL v2.30 released.
