### ISSUE TITLE
Support for PlantUML in Markdown

### ISSUE THREAD

**Issue by dbeuchler** [dotnet/docfx#2347]
**DocFX Version Used**: 2.29.1
**Template used**: default (`default` or `statictoc` or contain custom template)

In [GitLab it is possible to add PlantUML](https://docs.gitlab.com/ee/administration/integration/plantuml.html) Code to markdown files with: 

\```plantuml
Bob -> Alice : hello
Alice -> Bob : Go Away
\```

The result looks as in the following image:

![image](https://user-images.githubusercontent.com/920832/34613677-e4c44778-f22e-11e7-94d0-043c9b462a11.png)

For us it would be a big benefit to remove all our commited binaries (jpgs exported from Enterprise Architect) in our repositories.

For docfx it would mean that it needs some kind of pre processor which posts the data to a public or self hosted [PlantUML Server](https://github.com/plantuml/plantuml-server), save the image to a defined folder and replace markdown code with the resulting image. 

Gitlab posts the image to the PlantUML Server and uses the image link in the markdown file which is not a good option for offline documentation. 

Is some kind of feature planned or what would be the best way to implement it?

**Comment by vwxyzh** [comment]
1. PlantUML Server is required.
2. Markdown code render should be overwritten.

**Comment by vicancy** [comment]
I would say a pure frontend solution, e.g. https://mermaidjs.github.io/ is more acceptable. @dbeuchler do you think https://mermaidjs.github.io/ is a good way to go?

**Comment by dbeuchler** [comment]
A pure frontend solution (but "offline") is acceptable but currently mermaidjs dos not support several diagram types. In our application we have a lot of `StateMachine` and `Component` Diagrams which are currently not supported but as far as I see, these diagram types can be covered by generic `squares`, `circles` and `arrows`.

**Comment by shadow-cs** [comment]
PlantUML **server** is not generally required since PlantUML may be executed as standalone app (via Java) and supplied externally as an argument. It also requires graphviz to be installed and visible though the search path.

PlantUML does support SVG output which is ideal for web presentation (GitLab uses PNGs which offer better compatibility but worse visuals).

Recently I enjoyed using [vscode-markdown-preview-enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced) for writing documentation, it would be great if some of its features were integrated to docfx (diagramming being the primary one ;-)).

**Comment by KevReed** [comment]
I just created https://github.com/KevReed/DocFx.Plugins.PlantUml, hopefully this will be useful

**Comment by superyyrrzz** [comment]
@KevReed Looks great. Can you add your plugin to dashboard? https://github.com/dotnet/docfx/blob/dev/Documentation/templates-and-plugins/templates-dashboard.yml

**Comment by cjlotz** [comment]
Would be great to have this supported in V3 as well

**Comment by hollowdrutt** [comment]
[Extend Markdown/Wiki to support mermaid & plantuml plugins, enabling UML sequence, class, flowchart diagrams](https://developercommunity.visualstudio.com/idea/365751/wiki-mermaid-plantuml-support.html) has been added to the roadmap for Azure Devops Wiki.

If that gets implemented and if docfx gets support for [Markdown as output](https://github.com/dotnet/docfx/issues/684) then it would be possible to use docfx to build documentation including diagrams, code snippets etc and generate markdown output to be published in [Azure Devops Wiki](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops)

**Comment by hollowdrutt** [comment]
[Mermaid diagram support in Azure Devops Wiki is rolling out](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-158-update#mermaid-diagram-support-in-wiki).
[Azure Devops Wiki will not get support for PlantUML at this time](https://developercommunity.visualstudio.com/comments/747069/view.html)

**Comment by cilerler** [comment]
I don't think Mermaid can match up with PlantUML, please use your votes here https://developercommunity.visualstudio.com/idea/747577/add-support-for-plantuml.html

**Comment by mwwhited** [comment]
Not a fan of the GPL license on plantuml but the features are much nicer than mermaid (though mermaid is a bit nicer to look at.)

**Comment by KevReed** [comment]
PlantUML is available under [MIT licence](https://plantuml.com/download#mit) among others, with a few features removed which depend on GPL software. See https://plantuml.com/faq.
