### ISSUE TITLE
Kramdown support?

### ISSUE THREAD

**Issue by ChrisChinchilla** [dotnet/docfx#2348]
**DocFX Version Used**: 2.29.1.0
**Template used**: `default` with some small customisations.

I'm converting a Jekyll site to DocFx and have my own custom code tabs that use JavaScript and HTML, for example:

<img width="1126" alt="screen shot 2018-01-08 at 16 50 57" src="https://user-images.githubusercontent.com/42080/34678678-21b2d8f4-f494-11e7-85de-2d946ddd7134.png">

But I think because DocFX doesn't use Kramdown, the markdown inside isn't rendered quite right (see image).

<img width="536" alt="screen shot 2018-01-08 at 16 48 22" src="https://user-images.githubusercontent.com/42080/34678578-d290b412-f493-11e7-903f-974981abd186.png">

Can I somehow use a different converter? Or is there another way to get this to work? As far as I know, Liquid uses a markdownify filter to make this work, is that accessible in DocFX?

**Comment by vicancy** [comment]
Is tabbed content http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a#tabbed-content what you are looking for?

**Comment by ChrisChinchilla** [comment]
@vicancy Huh, strange, I found the tabs somewhere else and it had different syntax and said that it would only work on MSDN, but this works perfectly. Thanks!
