### ISSUE TITLE
1500+ articles

### ISSUE THREAD

**Issue by mscommunities** [dotnet/docfx#235]
We are attempting to use docfx for all of our 1500+ tutorials and are wondering if the system was ever intended to support so many documents. For example, we are using table of contents sidebar that is driven from a single toc.md file. This means that on every article page we are downloading the entire table of contents which is wasteful and slow. Ideally only the nodes visible should be downloaded and the rest loaded as needed. Also, the index.json file we have is currently 15mb and too large for clients to download. Any thoughts?

**Comment by chenkennt** [comment]
Our default template is a static web site, which builds the one toc into one static file. It's your choice to split files into small ones, or keep them in one toc. Personally I don't think the size of toc of 1500 files is an issue, and consider browser has cache, toc won't get downloaded for every article. But if the number of files is even bigger, it's recommended to split large toc into small ones.

The `index.json` is used for on site search, this is a client side search which is not really designed for large site. So if you really have large amount of content, it's recommended to disable client side search and implement a server side one.
