### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by ndenkha** [dotnet/docfx#2357]
This might not be the right place to post this question, but this is where the link from here brings me.

https://www.nuget.org/packages/Microsoft.DocAsCode.HtmlToPdf/

I'm trying to install Microsoft.DocAsCode.HtmlToPdf, and it gives me the below error. Any help is appreciated.

Could not install package 'Microsoft.DocAsCode.Common 2.30.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by vicancy** [comment]
Hi @ndenkha are you using the latest visual studio? Microsoft.DocAsCode.Common is now targeting `netstandard2.0`, which, in the latest visual studio, should be compatible with `net461`.

**Comment by ndenkha** [comment]
No I'm using VS2015, I'll try VS2017 tomorrow. Just curious, will or is there an HtmlToPdf version for .NET 4.0 framework?

**Comment by herohua** [comment]
@ndenkha Any update with VS2017?
