### ISSUE TITLE
docfx output includes protected members 

### ISSUE THREAD

**Issue by avspeed** [dotnet/docfx#2367]
**DocFX Version Used**: 
2.30
**Template used**: (`default` or `statictoc` or contain custom template)
default
**Steps to Reproduce**:
I have generated documentation for a project and the output contains some protected members..
What would cause that ? I thought that only public were included 

**Expected Behavior**:
only public members in the output
**Actual Behavior**:
protected members are included

**Comment by vwxyzh** [comment]
@avspeed 
It is as design.
The reason is: when inheriting the class, you can find the protected members.
Hint: protected members in sealed class will be removed.

**Comment by avspeed** [comment]
@vwxyzh  ok thank you.
