### ISSUE TITLE
Wide screen support

### ISSUE THREAD

**Issue by tzachshabtay** [dotnet/docfx#2374]
**DocFX Version Used**: 2.30

**Template used**: `default`

**Steps to Reproduce**:

1. Look at any of the generated documentation websites using the default template on a wide-screen monitor. Here's a good example of a page that would have benefited greatly from wide screen support: https://tzachshabtay.github.io/MonoAGS/articles/ags-cheat-sheet.html

**Expected Behavior**:

The layout should take advantage of the existing space on the wide-screen monitor: the "in this article" should go all the way to right (with minimal padding), the toc all the way to the left (with minimal padding), and the article should take the rest of the space.

**Actual Behavior**:

A lot of unused space on the left and right sides, means the article is unnecessary crammed into a small space.

**Comment by cbenea** [comment]
Hi @vicancy! Is it possible to help me and @tzachshabtay with this issue? I really need to enable this feature on my site. Where and what do I need to configure in order to make a widescreen site?
Thank you!

**Comment by vicancy** [comment]
@cbenea the easiest way to do it is to add css for widescreen cases in your own `main.css`

**Comment by cbenea** [comment]
Hi, @vicancy. Thank you very much for your reply. I tried different configurations, but I dont really know what to put in order to change the layout. What I did it just moves the side-toc menu to the left and the rest of the content is somehow uncentered and looks weird. Do you have any code that I can use in order to make everything wider and clean? Thanks again!

**Comment by mozts2005** [comment]
I would like to help with this issue.  @vicancy  I was thinking of setting it up to inherit from the default theme. 

so that the config would look like this

```json
{
    "build": {
        "template": [
            "default",
            "default-widescreen"
        ]
    }
}
```
 How about that?

**Comment by vicancy** [comment]
@mozts2005 yes it looks the right way to go

**Comment by cbenea** [comment]
Hi, @vicancy! Sorry for not replying earlier, I was on vacation. The solution works great. Thank you!
