### ISSUE TITLE
Fix Chocolatey package

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#2381]
DocFx 2.30 wasn't successfully submitted to the Chocolatey gallery due to [failing checksum](https://gist.github.com/choco-bot/0a55043d2cb751dbff58e825d1a7398e#file-install-txt-L340).

It would be nice if you could change the Chocolatey package to contain the actual binaries instead of relying on downloading them from GitHub as this would result in a much more stable package.

**Comment by vicancy** [comment]
Yes I agree @pascalberger

**Comment by yufeih** [comment]
We are switching to [.NET core global tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) for distribution in v3, it makes cross platform distribution a lot easier.
