### ISSUE TITLE
VSC Extension cannot run if whitespace is in path

### ISSUE THREAD

**Issue by Xarkam** [dotnet/docfx#2383]
VSC: 1.19.3 / Extension version 0.1.1
Windows 10.
DocFx 2.30

I try to test the extension for visual studio code but the preview cannot run because my username in path contain whitespace:
![image](https://user-images.githubusercontent.com/331816/35436751-f2dc5aaa-028f-11e8-902d-dfd9f05b1c45.png)
after 'Benjamin' I have a whitespace.
So the command line is cut at this point

Thanks

**Comment by 928PJY** [comment]
hi, @Xarkam this issue has been fixed and new extension(v0.1.2) has been released. please update your extension

**Comment by Xarkam** [comment]
Hi, thanks :)
