### ISSUE TITLE
C# 7.2 "private protected" bug

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/docfx#2401]
**Summary**:

`private protected` members are included in the HTML output as a `public` member, when they instead should not be included at all. I've cleaned caches, and the issue is still present.

**DocFX Version Used**: 2.29.1.0

**Template used**: `default`

**Steps to Reproduce**:

```C#
private protected void ShouldNotBeInDocs()
{ }
```

**Expected Behavior**:

`ShouldNotBeInDocs` should not be included in docfx output since `private protected` equates to  `protected` **AND** `internal`.

**Actual Behavior**:

`ShouldNotBeInDocs` is included in HTML output as a `public` member:

```HTML
<div class="codewrapper">
  | <pre><code class="lang-csharp hljs">public void ShouldNotBeInDocs()</code></pre>
  | </div>
 ```

**Comment by vicancy** [comment]
Should be fixed in v2.31, let me know if there are any other issues.
