### ISSUE TITLE
`<seealso>` not working with `enum`

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/docfx#2402]
**DocFX Version Used**: 2.29.1.0

**Template used**: `default`

**Steps to Reproduce**:

```C#
    /// <summary>
    /// </summary>
    /// <seealso cref="MyEnum"/>
    public class MyClass
    {
    }

    /// <summary>
    /// </summary>
    /// <seealso cref="MyClass"/>
    public enum MyEnum
    {
        Default
    }
```

**Expected Behavior**:

Both `MyEnum` and `MyClass` have "See Also" sections with a reference to the other.

**Actual Behavior**:

`MyClass` have "See Also" section with a reference to `MyEnum` (as expected), but `MyEnum` has no "See Also" section and no reference to `MyClass`.

**Comment by vicancy** [comment]
A template bug
