### ISSUE TITLE
Inconsistent formatting of "Syntax" with inheritance and type constraint 

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/docfx#2410]
**DocFX Version Used**: 2.31.0.0

**Template used**: `default`

**Steps to Reproduce**:
```C#
public interface ITester
{ }

public class TesterA<R, S>
    where R : class
    where S : IComparable
{ }

public class TesterB<R, S>
    : TesterA<R, S>, ITester
    where R : class
    where S : IComparable
{
    public T TestOne<T>(T arg)
    where T : class
    {
        return arg;
    }

    public T TestTwo<T, U>(T arg1, U arg2)
        where T : class
        where U : IComparable
    {
        return arg1;
    }
}
```

**Expected Behavior**:
In the "Syntax"/"Declaration" section:
- Each inherited class/interface displayed on their own line (this is best since many generic classes/interfaces have very long names):
```C#
    : TesterA<R, S>, 
    ITester
```
- Each class _and_ method type constraints displayed on their own line, and with keywords highlighted: 
  - `where` R : `class`
  - `where` S : IComparable

**Actual Behavior**:

For _class_ type constraints _without_ inheritance:
- Constraints are on their own line (good), but multiple constraints are concatenated on one line. It would be easier to read if they were on separate lines.
- Keywords `where` and `class` are not highlighted on both Chrome and Firefox (I'm guessing it's CSS that should have done that?)

```HTML
<div class="codewrapper">
    <pre><code class="lang-csharp hljs">public class TesterA&lt;R, S&gt;
    where R : class where S : IComparable</code></pre>
    </div>
```

For _class_ type constraints _with_ inheritance:
- Inherited classes/interfaces and constraints are concatenated on the same line as the class itself. It would be _much_ easier to read if inherited classes/interfaces and constraints each were on separate lines.
- Keywords `where` and `class` are not highlighted on both Chrome and Firefox

```HTML
<div class="codewrapper">
    <pre><code class="lang-csharp hljs">public class TesterB&lt;R, S&gt; : TesterA&lt;R, S&gt;, ITester where R : class where S : IComparable</code></pre>
    </div>
```

For _method_ type constraints:
- Constraints are concatenated on the same line as the method name, and the space before `where` is missing. It would be much easier to read if each constraint was on a separate line.
- Keyword `where` and `class` are highlighted on the _first_ constraint, but not on the _second_ constraint  on both Chrome and Firefox

```HTML
<div class="codewrapper">
    <pre><code class="lang-csharp hljs">public T TestTwo&lt;T, U&gt;(T arg1, U arg2)where T : class where U : IComparable</code></pre>
    </div>
```

**Comment by bitfringe** [comment]
Encountered same issues. Readability is a bit impaired when reading declaration syntax containing generic type constraints.

**Code example**:
```csharp
public interface IEvent {}

public class Whatever {
    void DoSomething<TEvent>(TEvent @event) where TEvent : IEvent;
}
```

**Expected** declaration syntax for method `DoSomething` in generated docs:
```csharp
void DoSomething<TEvent>(TEvent @event) where TEvent : IEvent;
```

**Actual result:**
```csharp
void DoSomething<TEvent>(TEvent @event)where TEvent : IEvent;
```

Note the ***missing space*** between **)** and **where**.

**Solution**

Update *Microsoft.CodeAnalysis.CSharp* from *2.6.1* to *2.7.0*.



Issue is related to `SyntaxFactory.MethodDeclaration` and similar methods in *Microsoft.CodeAnalysis.CSharp*. It seems it does not correctly indent stuff even when it has the default parameters to insert line-breaks and spaces. 

Wrote a simple test, dumped the results, and the new version produces:
```csharp
void DoSomething<TEvent>(TEvent @event)
    where TEvent : IEvent;
```

It adds a line break and 4 spaces by **default*. But that is customizable when docfx calls into those apis.

*Note: I didnt experiment with other declaration examples. *

**Comment by vwxyzh** [comment]
@bitfringe thank you for your investigation, we will update package next release.

**Comment by superyyrrzz** [comment]
The following issue is created for highlight issue:
https://github.com/isagalaev/highlight.js/issues/1714

**Comment by bitfringe** [comment]
Disclaimer: I'm not familiar with how Roslyn works at all and that was just my first glance and I might be wrong. @vwxyzh @superyyrrzz guys please do your own investigation. 

There are a couple other things that might be of interest and I am not entirely sure if you already use them:
- `Microsoft.CodeAnalysis.Formatting.Formatter.Format` seems to be the "preferred" solution for formatting the source code
- `SyntaxNode.NormalizeWhitespace` seems to be the manual way to do some formatting on specific syntax tree nodes (DocFx seems to be using this).

Cheers.

**Comment by KristianWedberg** [comment]
So far (in docfx 2.40.10), only the missing space has been fixed, all the other line break and syntax highlight issues and feature requests have not been addressed. Any chance this will at least be scheduled?

**Comment by superyyrrzz** [comment]
@KristianWedberg I marked this as bug and it depends on a third party library. Sorry for lacking resource to look into this issue currently.

**Comment by yufeih** [comment]
Random whitespace issues have been fixed.

Newline insertion worth more discussion, multiple factors like signature length and screen width affects whether or not and where to insert a newline. Docfx today displays signatures in a single line, the same way as https://learn.microsoft.com/en-us/dotnet/api/ , and probably the default visual studio format.
