### ISSUE TITLE
Overload resolution bug

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/docfx#2411]
**DocFX Version Used**: 2.31.0.0

**Template used**: `default`

**Steps to Reproduce**:
```C#
        private void Method(bool a)
        { }

        public void Method()
        { }

        /// <summary>
        /// See <see cref="Method"/>.
        /// </summary>
        public void OtherMethod()
        { }
```

**Expected Behavior**:
`<see cref="Method"/>` resolves to `public void Method()`.

**Actual Behavior**:
`<see cref="Method"/>` resolves to `private void Method(bool a)`.

```HTML
<div class="markdown level1 summary"><p>See <span class="xref">actionETL.ADb.ADbParameter.Method(System.Boolean)</span>.</p>
</div>
```

**Comment by KristianWedberg** [comment]
This bug (resolving reference to a `private` overload instead of the `public` overload) is still present in docfx 2.4.10. Any chance it will be scheduled for fixing?

**Comment by superyyrrzz** [comment]
This look like a [roslyn issue](https://github.com/dotnet/roslyn/issues/45), and still [an open issue for csharp](https://github.com/dotnet/csharplang/issues/320).
![image](https://user-images.githubusercontent.com/3831744/54210587-be8eb300-451a-11e9-9682-0dcd29089a05.png)
