### ISSUE TITLE
Consecutive blockquotes in markdown being rendered as a single blockquote

### ISSUE THREAD

**Issue by JeremyTCD** [dotnet/docfx#2424]
**DocFX Version Used**: 2.31.0.0

**Template used**: default

**Steps to Reproduce**:

1. Enter the following into any markdown file:
  ```
  > Blockquote 1

  > Blockquote 2
  ```
**Expected Behavior**:
  > Blockquote 1

  > Blockquote 2

**Actual Behavior**:
  > Blockquote 1
  > Blockquote 2

## Notes
I'm not sure if this is by design, however, the expected behavior is [consistent with GFM](https://github.github.com/gfm/#example-213) while the actual behavior is not. Moreover, there is no intuitive way to create two consecutive blockquotes with the current behaviour.

### Cause
The root cause is the regex for MarkdownBlockquoteBlockRule. `\n*)+` at the end of the following line allows for unlimited empty lines between lines starting with `>`:
https://github.com/dotnet/docfx/blob/ea0b9cc9a4b06348e794a0f5a89d10e0da2a9062/src/Microsoft.DocAsCode.MarkdownLite/Regexes.cs#L27  

Edit: After some testing, I've found that the new MarkdownBlockquoteRule `Matcher` works fine. Just realized that both my chocolatey package for version 2.31.0 and my locally built checkout of the same tag run with legacy mode set to true though. Is this expected and is non legacy mode ready for use? If it is ready then this issue can be closed. Thanks.

**Comment by vwxyzh** [comment]
@JeremyTCD please switch `markdownEngineName` to `margdig`/`dfm-latest`, default is `dfm`.
See document [here](http://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#32-properties-for-build)

**Comment by JeremyTCD** [comment]
Thanks!
