### ISSUE TITLE
Document breadcrumb_path

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#2425]
The [ASP.NET documentation](https://github.com/aspnet/Docs/blob/c3aba78729951e56ae8335094ffcd800d4fdb786/aspnet/docfx.json#L39) uses a ´breadcrumb_path´ property, which also appears in a few tests in this repository. Is this a feature of DocFx or something specific to the template used by ASP.NET? 

It would be nice to have documentation how to use it and if the breadcrumb TOC file can be generated somehow.

My use case is that I want to prefix the breadcrumb with a root entry (see #968).

**Comment by superyyrrzz** [comment]
This feature is specific to the template used by docs.msft.com, of course includeing ASP.NET. It has a different logic to compose the TOC.

In DocFX's default template, breadcrumb's left part is from top navbar, and the right part is from left toc. `bread_crumb` is not used in DocFX, although it exists in some UT...

In DOCS' template, all the breadcrumb's node is from another virtual TOC. Left toc is not used in breadcrumb. The metadata `breadcrumb_path` is used for a page to locate this virtual TOC. There's still no plan in near future to open source DOCS' template, so you can customize the rendering part in DocFX's template: https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/styles/docfx.js#L511

**Comment by superyyrrzz** [comment]
Close as this is not DocFX feature to document

**Comment by awakecoding** [comment]
Is there any chance of seeing a similar breadcrumb feature documented? How exactly is this handled in the Microsoft template, and how could an open source equivalent be made? This is the kind of thing that really makes docs.microsoft.com so awesome, it's a bummer that it is not part of docfx.
