### ISSUE TITLE
Move temporary plugin folder to and AppData directory

### ISSUE THREAD

**Issue by sandorfr** [dotnet/docfx#2426]
# Bug
**DocFX Version Used**: 
2.31.0.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Install docfx with chocolatey as an administrator
2. Run docfx in a normal shell

**Expected Behavior**:
It should work.

**Actual Behavior**:
It fails with a permission error on the temporary plugin folder.

**Workaround**
Give modify permissions to the users on the folder `C:\ProgramData\chocolatey\lib\docfx`

# Fix suggestion

Looging at the logs We can see that it's writing temporary plugins in a subfolder of docfx assuming the user will have permissions on it `Cleaning up temporary plugin folder "C:\ProgramData\chocolatey\lib\docfx\tools\plugins_1bmq5irw.2j0"`

It should a user temp directory instead such as `AppData\Local\Temp\plugins_1bmq5irw.2j0`.

**Comment by lwchkg** [comment]
+1

**Comment by sandorfr** [comment]
this stale bot does not make any sense

**Comment by superyyrrzz** [comment]
@sandorfr  We just set up the bot, so sorry for the disturbing `stale` mark.

Back to the issue, I agree your suggestion makes sense. This is a valid enhancement in vCurrent. In vNext, we already save intermediate files into `%UserPofile%` folder.
