### ISSUE TITLE
Documentation: Can't figure out how to enable plugins for pdf

### ISSUE THREAD

**Issue by sandorfr** [dotnet/docfx#2427]
I can't figure out how to enable the plugins for pdf as well. I'm probably missing something but [the documentation](https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_generate_pdf.html) does not contain any pdf specfic information on that matter.

**DocFX Version Used**: 
2.31.0.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1.  Add a plugin to "template" such as `plugins/rest.tagpage.2.31.0/content`
2.  Follows steps to enable pdf: https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_generate_pdf.html
3. **Variation* : Add the plugin to template inside the pdf section.

**Expected Behavior**:
Have the plugin running and do their job

**Actual Behavior**:
The result is the sames as without any plugin as if thety were completely ignored.

**Comment by vicancy** [comment]
assemblies inside plugins has a flattened folder structure. and pdf template `default.pdf` is embedded in docfx, so you don't need any plugin to run pdf. You can also use `docfx template export default.pdf` to see what's inside the pdf template.

**Comment by sandorfr** [comment]
I'm a bit more confused now.

> you don't need any plugin to run pdf

The plugin are not to run pdf but to get what I want inside the pdf, such as markdown extensions (see #2292), or properly splitted swagger API. 

> default.pdf is embedded in docfx,

That's not my top priority at the moment but does that mean that there won't be to make it look good by customizing it?

**Comment by vicancy** [comment]
Hi @sandorfr I get your point now. 
> Add a plugin to "template" such as `plugins/rest.tagpage.2.31.0/content`
Plugin folder structure is flattened. Try moving items inside `plugins/rest.tagpage.2.31.0/content` to `plugins`. Alternatively, you can `nuget install rest.tagpage -OutputDirectory <output>` and in `docfx.json`, change template config to `template: ["default.pdf", "<output>/rest.tagpage.<version>/content"]`

> does that mean that there won't be to make it look good by customizing it?
Yes, you can make it look better by customizing it use `template: ["default.pdf", "custom_template"]. Template files from the latter one overwrites files with the same file name frome the former one. Details please refer to http://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html#merge-template-with-default-template

**Comment by sandorfr** [comment]
Hooray !
![image](https://user-images.githubusercontent.com/2660262/36085445-f1778378-1019-11e8-90a6-771cd17a6bcc.png)

`plugins` was my actual `<output>`, but I renamed it to pluginsPackages for clarity. The part I was missing was the pdf template which is `pdf.default` and not `default.pdf` ;):

```json
 "template": [
      "pdf.default",
      "pluginsPackages/mermaid",
      "pluginsPackages/graphviz",
      "pluginsPackages/rest.tagpage.2.31.0/content" 
    ],
```

and the export command is indeed `docfx template export pdf.default`

You put me on the right path though.

Thanks, I'll make a PR against the documentation to include those tips, if you like.

**Comment by vicancy** [comment]
@sandorfr this is cool, I'd like to have it merged into docfx. Please send out the PR when its ready to share. 👍
