### ISSUE TITLE
docfx.console forces init unconditionally on all builds

### ISSUE THREAD

**Issue by smaillet** [dotnet/docfx#2434]
**DocFX Version Used**: 
2.31.0
**Template used**: (`default` or `statictoc` or contain custom template)
N/A
**Steps to Reproduce**:

1.  Update docfx console via nuget for a project with previous version
2. Build

**Expected Behavior**:
Docs build and no new unwanted project files created.

**Actual Behavior**:
Generate is now unconditionally running the init command before generating the docs (due to PR# #2396). This creates a number of directories and adds a set of .gitignore files that are not desired or part of the project. Init should not be performed on EVERY build automatically. At most it should be a distinct target so you can run it manually or conditional run If and only if there is no docfx.json.

**Comment by vicancy** [comment]
Yes absolutely. Should be a bug and need fix.
