### ISSUE TITLE
Symantec blocked the docfx.exe --> Security risk detected: WS.Reputation.1

### ISSUE THREAD

**Issue by mjangid** [dotnet/docfx#2439]
**DocFX Version Used**:  2.31.0.0

**Template used**: `default`

**Steps to Reproduce**:
>SET PATH=c:\tools\docfx;%PATH%
>docfx init

**Expected Behavior**:
Should create default project

**Actual Behavior**:

Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: c:\tools\docfx\docfx.exe
Location: Deleted or access blocked
Computer: LP-2JNK4M2
User: manoj.jangid
Action taken: Leave Alone succeeded
Date found: 12 February 2018  16:39:50

**Comment by sandorfr** [comment]
You got me worried so I did a quick google search:
https://community.norton.com/en/forums/clarification-wsreputation1-detection

I think it's just a false positive, you should submit it to symantec as a false positive https://submit.symantec.com/whitelist/

**Comment by vicancy** [comment]
Thanks for reporting the issue, I reported a false positive to Symantec.

**Comment by vicancy** [comment]
In relation to submission 73786.

Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:

    File name: docfx.exe
    MD5: af23d83dc3ce3eba7777f7c5794d4dac
    SHA256: 4a37ef10c971a7b6799fdf8d7950c65ac8bf077afbce3fef7eca842c86dea014
    Note: Whitelisting may take up to 24 hours to take effect via Live Update
