### ISSUE TITLE
Question: How are GitHub Issues supported?

### ISSUE THREAD

**Issue by richorama** [dotnet/docfx#2445]
**DocFX Version Used**: docfx 2.31.0.0

**Template used**: `default`

**Steps to Reproduce**:

1. Add the following configuration to `globalMetadata` :
```
"feedback_system": "GitHub",
"feedback_github_repo": "dotnet/orleans",
"feedback_product_url": "https://github.com/orleans",
```
2. build docs
3. pages do not have GitHub Issues feedback

**Expected Behavior**: Expected to see GitHub Issues enabled for feedback

**Actual Behavior**: No change

Hi, I'm attempting to add the new [GitHub based feedback](https://docs.microsoft.com/en-gb/teamblog/a-new-feedback-system-is-coming-to-docs) to the Orleans repo, but I'm failing to understand how. I copied the config changes from the [Azure CLI repo](https://github.com/Azure/azure-docs-cli-python/commit/8089ed88b4ea8ad9a2ebf8d0f11d69b63449e939) and tried running the latest version of DocFX, but nothing changed. Am I missing some templates?

Many thanks.

**Comment by vwxyzh** [comment]
@richorama DocFX do not support this feature.
This feature is based on web site, it do not open source yet.
