### ISSUE TITLE
XRefService lookup of generic classes doesn't work

### ISSUE THREAD

**Issue by MariusVolkhart** [dotnet/docfx#2448]
**DocFX Version Used**: 2.31.0.0

**Template used**: `default`

**Steps to Reproduce**:

1. Add the Microsoft xref service to the `docfx.json`: `"xrefService": [ "https://xref.docs.microsoft.com/query?uid={uid}" ]`
2. Create a class with a return type of a class with generics, such as `IList` or `IObservable`
3. Serve docs using docfx `docfx docfx.json --serve`

**Expected Behavior**:
The generated docs link the generic type to the MS docs. For example, for the type `IObservable` I expect a call to ``https://xref.docs.microsoft.com/query?uid=System.IObservable`1``, and for this xref to be used to link the type in the generated docs.
**Actual Behavior**:
Generated docs only link non-generic BCL types. Generic types from the same class library as the target file do get linked.

A sample project, based on `docfx-seed` is available here: https://github.com/mariusvolkhart/docfx-seed/tree/mv/IObservableBug. Be sure to use the `mv/IObservableBug` branch.

In this project, you will find that `CatLibrary.Tom.TomMethod` links the type `CatLibrary.Complex` but does not link `System.Tuple`

![capture](https://user-images.githubusercontent.com/1709517/36342685-cac1e7a0-13cf-11e8-8484-cc0be8319af4.PNG)

**Comment by Herrmel** [comment]
Hi there,
I have exact the same issue with similar setup. I wanted to mention tought that for me additionally methods also do not get linked. So for example if I overwrite the Method *toString()* it detects and prints the full name *System.Object.ToString()* but it does not create a link. This apllies to any area I think.

**Comment by vwxyzh** [comment]
@MariusVolkhart please try `dotnet restore`, then run `docfx`.

**Comment by Herrmel** [comment]
I dont have dot net core installed but I dont use any projects with dotnet core for my documentation so I dont think this would help me(correct me if Im wrong). I also noticed that this issue seems to apply to docfx own API documentation as well ([example](http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.CascadableOptions.html#Microsoft_DocAsCode_CascadableOptions_Templates)).

**Comment by MariusVolkhart** [comment]
When I run `dotnet restore` on the `SampleClass1.sln` from `docfx-seed` (which i'm using to demonstrate the problem I receive the message `Nothing to do. None of the projects specified contain packages to restore.`

**Comment by vwxyzh** [comment]
@superyyrrzz @Herrmel it is a bug in DocFX.
