### ISSUE TITLE
No metadata is generated for <project>

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/docfx#2453]
**DocFX Version Used**: 2.31.0

**Template used**:  `default`

**Steps to Reproduce**:

1. Clone repo https://github.com/FakeItEasy/FakeItEasy/
2. `cd` into repo directory
3. `docfx init -q`
4. Change metadata as follows in docfx.json:
    ```json
    "metadata": [
      {
        "src": [
          {
            "files": [
              "src/FakeItEasy/FakeItEasy.csproj"
            ],
            "src": "..",
            "properties": {
              "TargetFramework": "net45"
            }
          }
        ],
        "dest": "api",
        "disableGitFeatures": false
      }
    ],
    ```
5. `docfx docfx_project\docfx.json --force --logLevel Verbose`

**Expected Behavior**:

Should generate metadata for FakeItEasy.csproj

**Actual Behavior**:

Log says:

> [18-02-22 03:17:06.903]Info:[MetadataCommand.ExtractMetadata]Generating metadata for each project...
> [18-02-22 03:17:08.040]Verbose:[MetadataCommand.ExtractMetadata]Successfully generated metadata C:/Users/ThomasLEVESQUE/Documents/Perso/Projects/FakeItEasy/src/FakeItEasy/obj/xdoc/cache/obj for FakeItEasy
> [18-02-22 03:17:08.067]Verbose:[MetadataCommand.ExtractMetadata]Completed MergeMetadata in 3,6025 milliseconds.
> [18-02-22 03:17:08.071]Verbose:[MetadataCommand.ExtractMetadata]Completed MergeReference in 1,4459 milliseconds.
> [18-02-22 03:17:08.073]Warning:[MetadataCommand.ExtractMetadata]No metadata is generated for FakeItEasy.

**Comment by thomaslevesque** [comment]
OK, I had the `properties` at the wrong level... I no longer have this warning. But I still can't see any API documentation generated in _site; I have a bunch of .yml files in api, though.

**Comment by superyyrrzz** [comment]
@thomaslevesque Can you provide the `build` section of your `docfx.json`?

**Comment by thomaslevesque** [comment]
@superyyrrzz, I recreated it from scratch and now it works. Not sure what I did wrong the first time...
Sorry about this, I'll close the issue now.
