### ISSUE TITLE
Inherited methods are not linked

### ISSUE THREAD

**Issue by gix** [dotnet/docfx#2458]
**DocFX Version Used**:  2.31

**Template used**: default

**Steps to Reproduce**:

1. Create a new class library with any non-static class.
2. Run docfx for that library.

**Expected Behavior**: All inherited members are linked.

**Actual Behavior**: Inherited methods from System.Object, like ToString or GetHashCode, are not linked. Inherited properties or events are properly linked ([example](https://gix.github.io/PresentationTheme.Aero/api/PresentationTheme.Aero.Win10.ButtonChrome.html)).

**Comment by superyyrrzz** [comment]
May be the same issue with #2448. Looks like when uid contains not letter characters like `(`, `)`, `` ` ``, xref service doesn't work.
