### ISSUE TITLE
Add support for <inheritdoc />

### ISSUE THREAD

**Issue by matkoch** [dotnet/docfx#247]
This was already supported in sandcastle. 

As described on [microsoft uservoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/3745102-add-intellisense-support-for-the-inheritdoc-ta). Related issue for [Roslyn](https://github.com/dotnet/roslyn/issues/67).

**Comment by fschmied** [comment]
See https://ewsoftware.github.io/XMLCommentsGuide/html/86453FFB-B978-4A2A-9EB5-70E118CA8073.htm for how the feature works with Sandcastle.
