### ISSUE TITLE
Remove "Copyright (c) Microsoft" from footer of default template

### ISSUE THREAD

**Issue by surban** [dotnet/docfx#2471]
**DocFX Version Used**: 2.31.0

**Template used**: `default`

The default template contains the footer text `Copyright (c) 2015-2017 Microsoft` which suggests that the generated content is copyright by Microsoft. Since this is not the case, this text should be removed.

![image](https://user-images.githubusercontent.com/1213857/36738943-0739feea-1bdf-11e8-882b-872977e2b68f.png)

**Comment by superyyrrzz** [comment]
fixed in v2.33
