### ISSUE TITLE
Bug: summary text is generated to HTML as source code markdown

### ISSUE THREAD

**Issue by aienabled** [dotnet/docfx#248]
Hello!
I've a problem with documentation generated for my project: summary text generated to HTML as source code markdown. Screenshot: http://screencloud.net/v/rqyX (as you can see only summary for ILogicObject appears properly).
The code from Firefox and Chrome is identical (for `IGameObject` from screenshot):
```html
<section>
    <pre>
        <code class="hljs actionscript">
            Game object. All game objects are
            <span class="hljs-keyword">implements</span>
            <span class="hljs-keyword">this</span>
            <span class="hljs-class">
                <span class="hljs-keyword">interface</span>
                .
            </span>
        </code>
    </pre>
</section>
```
The code from HTML page at disk is different and also incorrect (why there is a `<code>` attribute?):
```html
<section><pre><code>Game object. All game objects are implements this interface.
</code></pre></section>
```
Proper code (for `ILogicObject` from screenshot):
```html
<section><p>Script object - is a special scriptable GameObject which don&#39;t have any world representation.</p>
```

I'm using a fresh-generated docfx project ("docfx init -q"). I'm not using any template.
There are 178 MD files total, most of them has generics definitions - with a lot of < > chars. Could this affect HTML generation?

I've tried generating documentation for https://github.com/docascode/docfx-seed/ and it works fine (exactly the same as hosted there http://docascode.github.io/docfx-seed/index.html ). So the issue is reproducible only with documentation for my project.

Regards!

**Comment by vicancy** [comment]
Hi @aienabled , thanks for reporting the issue.
What version of `docfx` are you using? You can type `docfx --help`  to fetch the version number.
Also, could you provide a sample source code that generates the wrong summary, e.g. `IGameObject`?

**Comment by aienabled** [comment]
I'm using latest available version - 1.7.1.
I've uploaded whole docfx project with full metadata (but without src) on Google Drive https://drive.google.com/file/d/0B4-tSq-u4CreRzFoRDN1Uk01SkU/view?usp=sharing (it should be shared with your e-mail).
I've checked YML files and there are no issue with summary. The issue appears only in generated HTML. So you can try building HTML from provided project and check for the issues.

Regards!

**Comment by vwxyzh** [comment]
There are four spaces in your summaries.
And we will apply markdown rule for summary, e.g. *text* will generate <em>text</em>
In md, leading with four spaces means code.

I guest your summary is write like following:
```xml
<summary>
    your summary.
</summary>
```

**Comment by aienabled** [comment]
[b]vwxyzh[/b], exactly! And this is how ReSharper usually format XML-comments.
And this explains why ILogicObject is displayed properly - there are no spaces (I forgot to use auto-format before saving the file).

**Comment by aienabled** [comment]
So, this is by design, you will not fix this and there are no workaround with docfx tool? Do I need to find the way to configure ReSharper to not use any indent for XML comments?

**Comment by vicancy** [comment]
Hi @aienabled , this is by design that `docfx` renders `summary`, `remark`s, `description`s for `parameter`s as Markdown content. There is no workaround in `docfx` to disable the feature for now. We'd suggest you configure ReSharper to workaround the issue.

**Comment by aienabled** [comment]
Hello,
thank you!

For anybody who have the same issue: open ReSharper Options ->Code Editing -> XML Doc Comments and change these settings:
* Indent inside element that doesn't contain text
* Indent inside element that contain text

to **"No indent from parent"**.

Regards!
