### ISSUE TITLE
ignore namespaces that do not get the application and also ignore classes that do not contain the summary

### ISSUE THREAD

**Issue by gabrielimmich** [dotnet/docfx#2483]
**DocFX Version Used**:  2.32.0.0

**Template used**: `default`

**Questions**:

1) I would like to know if it has the possibility to only bring the namespaces of the application itself ignoring the namespaces of the system and other namespace that do not belong to the application?

2) Is it possible to bypass Inherited Members that do not belong to my namespaces?

3) I would also like to ignore all classes that do not contain ///, could anyone help me?

**Comment by superyyrrzz** [comment]
Looks like you can achieve 1 and 2 through [API filter](https://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html). 

DocFX does not support 3. Although an API has no summary, the signature is also informative.
