### ISSUE TITLE
Add support for Visual C++ (native) projects

### ISSUE THREAD

**Issue by MKlimenko** [dotnet/docfx#2484]
Visual Studio supports triple-slash comments for Visual C++ as well, so it would be extremly great to be able to parse C++ code files to extract API documentation. 
Is there any way to make it possible?

**Comment by superyyrrzz** [comment]
We have a tool supporting generate YAML for C++ and Java, which can be feeded to DocFX to generate API documentation. As there is no users actually using it for C++, I'm not sure whether it can work, but you can try this out: 
https://github.com/docascode/code2yaml

**Comment by nawabahmadreshi** [comment]
@superyyrrzz I tweaked the code2yaml for C, but how can I use the generated.Yaml file in DocFx. 
Kindly guide for the process.

**Comment by ogxd** [comment]
Has anyone tried code2yaml in this context ?

**Comment by gltgithub** [comment]
Having DocFX support for C++ seems like a "no-brainer".  Does anyone know why MS hasn't done that?

**Comment by yufeih** [comment]
Docfx does not natively support C++, but provides an [extension mechanism to support additional languages](https://dotnet.github.io/docfx/docs/additional-languages.html).
