### ISSUE TITLE
Support _gitContribute on a per file level

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#2490]
The "Improve this Doc" link should link to different respositories, for different sub-paths of the documentation (to avoid having to manage Git submodules). I tried to define metadata like this:

```
    "globalMetadata": {
      "_gitUrlPattern": "vso"
    },
    "fileMetadata": {
      "_gitContribute": {
        "some-subfolder/**": {
          "repo": "https://git.mycompany.com/dev/Development.git",
          "branch": "master",
          "path": ""
        }
      }
    }
```
**DocFX Version Used**: 
2.32.0.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Add above configuration to docfx.json
2. Build documentation
3. Check "Improve this Doc" links

**Expected Behavior**:

"Improve this Doc"  should link to different repos for different sub-paths.

**Actual Behavior**:
The above example won't render an "Improve this Doc" link for everything in `some-subfolder`

**Comment by pascalberger** [comment]
I managed to get the part of different `_gitContribute` settings per folder working if I define a `path`.

My remaining issue is now that I need to rewrite paths: For example `/some-subfolder/foo/bar.md` should link to  `https://git.mycompany.com/dev/Development.git/docs/foo/bar.md`. Is it possible to define a dynamic path for `_gitContribute.path`? So that I can use a fileMetadata setting and define for a specific glob that everything below a directory should go to a different Git repository, and there the file exists below a specific path, while the structure below is kept intact.

**Comment by superyyrrzz** [comment]
Hi @pascalberger, if you leave path unset instead of aissigning `""`, it can link to your specified `repo` and `branch`. The limitation is that the path in target repo should be the same as in original repo. Path rewriter is not supported now. Can this work for you?

**Comment by pascalberger** [comment]
@superyyrrzz Unfortunately not. One of the advantages of copying files together in a build script instead of using submodules is that I can rewrite paths. So they wont be the same in both repos. With submodules I would end with the whole path of the sub repository in the URL of the documentation.

We use this approach to aggregate documentation from different repositories which contain code and accompanying documentation in a `docs` folder. In the aggregation repositories we won't end with URLs like `https://mydoc/sub-folder/docs/index.html` but instead something like `https://mydoc/sub-folder/index.html`.

**Comment by superyyrrzz** [comment]
DocFX supports rewriting path by adding `"src":"sub-folder/docs", "dest":"subfolder"` in docfx.json. Will submodule work for you with this setting? The advantage of submodule is that the git info can be extracted by DocFX automatically.

**Comment by pascalberger** [comment]
It's one of the disadvantages of submodules .Another one is that submodules always link to a specific commit. This can be useful in some situation, but in my case I always want to include the latest version of the documentation. Which means that for every change done in a sub repository, I also need to update the submodule in the aggregate repository, to have the change included in the documentation.

**Comment by pascalberger** [comment]
Also I'm not sure the `src`/`dest` pattern works in my case. My struture might look like this:

- topic-folder
  - index.md
  - sub-repo-folder1
    - docs
      - index.md
  - sub-repo-folder2
    - docs
      - index.md
- sub-repo-folder3
  - docs
    - index.md

The aggregate repository itself also contains documentation (the `topic-folder\index.md`) which should be included without any path rewriting, while the part of the submodules below should be rewritten (remove the `docs` from the path)

**Comment by superyyrrzz** [comment]
Totally agree it's the pain point of sub module, which makes us abandon it...

Here's a sample:
```json
   "content": [
      {
        "files": [ "index.md" ],
        "src": "topic-folder",
      },
      {
        "files": [ "index.md" ],
        "src": "topic-folder/sub-repo-folder1/docs",
        "dest": "sub-repo-folder1"
      },
      {
        "files": [ "index.md" ],
        "src": "topic-folder/sub-repo-folder2/docs",
        "dest": "sub-repo-folder2"
      },
      {
        "files": [ "index.md" ],
        "src": "sub-repo-folder3/docs",
        "dest": "sub-repo-folder3"
      }
```

**Comment by pascalberger** [comment]
I'm not sure I can write globs for the specific entries. In your sample you list individual files, which is not practicable (or in which case I also could define specific _gitContribute metadata for each file). In my case I would like to say that `**\*.md` should be included, except for specific folders somewhere in the tree, which should be redirected.

As I understand from [here](http://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#43-glob-pattern) your Glob syntax doesn't support excludes.

**Comment by superyyrrzz** [comment]
Then it's like:
```json
   "content": [
      {
        "files": [ "**/*.md" ],
        "src": "topic-folder",
        "exclude": ["sub-repo-folder1/**", "sub-repo-folder2/**"]
      },
      {
        "files": [ "**/*.md" ],
        "src": "topic-folder/sub-repo-folder1/docs",
        "dest": "sub-repo-folder1"
      },
      {
        "files": [ "**/*.md" ],
        "src": "topic-folder/sub-repo-folder2/docs",
        "dest": "sub-repo-folder2"
      },
      {
        "files": [ "**/*.md" ],
        "src": "sub-repo-folder3/docs",
        "dest": "sub-repo-folder3"
      }
  ]
```

**Comment by pascalberger** [comment]
@superyyrrzz Many thanks! Yes this solves the path rewriting case with sub modules.

Would still be nice to have path rewrite capabilities for `fileMetadata` / `_gitContribute` to get completely rid of submodules.

**Comment by pascalberger** [comment]
The files would still coming from other repositories, but I would do the clone myself and copy the relevant files into the folder structure of the parent repository.

Or would it be possible to copy the whole cloned Git repository inside the parent Git repository and have DocFx detect correct links?

**Comment by superyyrrzz** [comment]
> Or would it be possible to copy the whole cloned Git repository inside the parent Git repository and have DocFx detect correct links?

Yes, DocFX can do it!

**Comment by pascalberger** [comment]
@superyyrrzz Thanks! Copying the whole repository inside the parent repository works fine.

**Comment by superyyrrzz** [comment]
Close as this feature seems not required as DocFX can extract proper git information from cascase git repo.
