### ISSUE TITLE
docfx service giving 404 error while accessing through my local ip e.g. 172.16.2.170:8080

### ISSUE THREAD

**Issue by rahulkushwaha12** [dotnet/docfx#2495]
![issue](https://user-images.githubusercontent.com/29196710/37088396-3914a024-2223-11e8-8334-8a5a21036843.PNG)

**Comment by superyyrrzz** [comment]
Can `http://localhost:8080` work? What's DocFX's output in your console?

**Comment by rahulkushwaha12** [comment]
Yes http://localhost:8080 is working fine and there is nothing printed on browser console. But when i changed the url to http://172.16.2.170:8080 i m getting below thing printed on browser console

> GET http://172.16.2.170:8080/favicon.ico 400 (Bad Request)

**Comment by superyyrrzz** [comment]
You can use `docfx.exe serve _site -n 127.0.0.1`.

With administrator privilege, you can also use `docfx.exe serve _site -n 172.16.2.170`.
