### ISSUE TITLE
Invalid link for Improve this doc

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#2504]
**DocFX Version Used**: 
2.32.1

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Create two repositories on TFS 2018 RTM
2. Add one as a submodule to the other (Commit linked to in the examples below is `048f13d15f2288c8806a81d0be4eca48a6566315`)
3. Create documentation in the repository containing the submodule
4. Check "Improve this doc" link of one of the pages from the submodule

**Expected Behavior**:

Generated link should link to commit as version:

https://tfs.mycompany.com/Default/MyProject/_git/myrepo?path=%2Fdocs%2Findex.md&version=GC048f13d15f2288c8806a81d0be4eca48a6566315&line=1&_a=preview

**Actual Behavior**:
Generated link expects a branch as version:

https://tfs.mycompany.com/Default/MyProject/_git/myrepo?path=%2Fdocs%2Findex.md&version=GB048f13d15f2288c8806a81d0be4eca48a6566315&line=1&_a=preview

Note the `GB` instead of the `GC`, but there's a commit SHA passed and not a branch name.

**Comment by pascalberger** [comment]
Problem seems to be that [here](https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/common/common.js#L98) always it is assumed that links always should go to a specific branch, which is not the case for submodules, which link to commits. So depending on whether an actual branch name or a SHA is passed, the link should go to `version=GB` or `version=GC`.

**Comment by superyyrrzz** [comment]
For github, branch and detached HEAD are identical when composing a URL. However, it's not the same for VSTS...

**Comment by superyyrrzz** [comment]
fixed in 2.33
