### ISSUE TITLE
yml uid missing BCL namespace

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/docfx#2507]
**Template used**: `default`

A number of my xref links involving BCL types started raising "invalid cross reference" warnings (and the web page shows the xref text instead of a link) after upgrading from:
- docfx 2.31 to 2.32.1
- VS 2017 15.5 to 15.6.1

Likely unrelated, but I use "xrefservice" to get BCL links:
```
"xrefservice": [
    "http://xref.docs.microsoft.com/query?uid={uid}"
    ]	
```
One symptom is that the related uid in the yml files are missing their namespace part.
Some are OK and don't raise warnings, e.g.:
- `System.Int32`
- `System.String`

Others lack namespace, and raise warnings (because my xref include the namespace):
- `DbType`
- `IList{MyNS.MyClass.MyClass}@`
- `Action{MyNS.MyClass})`

**Steps to Reproduce**:

1. Use xref links to methods that take BCL types like `System.Data.DbType` as parameter, e.g.:
- `<xref:MyNS.MyClass.MyFunc(System.Data.DbType,System.Int32)>`
- `<xref:MyNS.MyClass.MyFunc(MyNS.MyClass.MyInterface,System.Collections.Generic.IList{MyNS.MyClass.MyClass}@)>`
- `<xref:MyNS.MyClass.MyFunc(System.Action{MyNS.MyClass})>`
2. Build docfx documentation 

**Expected yml file content**:
```
- MyNS.MyClass.MyFunc(System.Data.DbType,System.Int32)
- MyNS.MyClass.MyFunc(MyNS.MyClass.MyInterface,System.Collections.Generic.IList{MyNS.MyClass.MyClass}@)
- MyNS.MyClass.MyFunc(System.Action{MyNS.MyClass})
```

**Actual yml file content**:
```
- MyNS.MyClass.MyFunc(DbType,System.Int32)
- MyNS.MyClass.MyFunc(MyNS.MyClass.MyInterface,IList{MyNS.MyClass.MyClass}@)
- MyNS.MyClass.MyFunc(Action{MyNS.MyClass})
```

**Comment by superyyrrzz** [comment]
I still not quite understand your input and output. Can you give a minimal reproduce step?

**Comment by KristianWedberg** [comment]
One of the methods that had the warning and faulty-looking yml file looked like below. 

Now though I can't replicate the issue, might e.g. have been an oddity related to the upgrade, that went away when I did a thorough cache clean. I'll close it for now.

Cheers!
Kristian

```C#
namespace MyNS
{
    using System.Data;

    public class MyClass
    {
        /// <summary>Triple-slash doc.</summary>
        /// <param name="dbType"></param>        
        /// <param name="count"></param>
        public void MyFunc(DbType dbType, int count)
        {
        }
    }
}
```
