### ISSUE TITLE
h*::before CSS produces weird hovering behaviour

### ISSUE THREAD

**Issue by benjamin-hodgson** [dotnet/docfx#2508]
**DocFX Version Used**: 2.32.2, tested in Chrome 64 on OSX

**Template used**: `default`

**Steps to Reproduce**:

1. Generate some API docs and open them in a browser
2. Hover over some of the section headings
3. Look at the heading tags in the inspector

**Expected Behavior**:
Heading anchor links should appear when hovering over the heading.
Headings should not overlap each other.

**Actual Behavior**:
Anchor links appear when hovering somewhere above the heading.
Headings are much taller than they should be and overlap each other.

![gif](https://i.imgur.com/Ie0bnrc.gif)

This appears to be due to [this chunk of CSS](https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/styles/docfx.css#L26-L38), which gives all the `h` tags a `before` with a large height, artificially blowing up the height of the `h` itself. Do you know what it's for? The comment is a little bit cryptic, and removing it doesn't appear to have any ill effects.

Would you accept a pull request fixing this?

**Comment by vicancy** [comment]
Yes this does feel wired. The css is to workaround https://stackoverflow.com/questions/4086107/fixed-page-header-overlaps-in-page-anchors. It is really tricky, and we are very welcome PRs to fix it.

**Comment by benjamin-hodgson** [comment]
Ah, thanks, I understand what it's for now. Perhaps it'd be better to do the fixed-header workaround in JS (ie, add some code which says "scroll up 100px" to an `onhashchange` handler), rather than by messing with the height of the elements in CSS. I'll try that out and throw up a PR for review if I get it working.
