### ISSUE TITLE
YML generation for C# 6.0 auto-property produces excess spaces

### ISSUE THREAD

**Issue by aienabled** [dotnet/docfx#251]
Hello!

I'm using docfx version 1.7.1 with default template.

Example:
```c#
public bool Test => true;
```

Result (YML):
```yml
syntax:
    content: >-
      public bool Test

      {

          get;

      }
    content.vb: Public ReadOnly Property Test As Boolean
```

(it appears the same in resulting HTML)

Regards!

**Comment by vwxyzh** [comment]
This is Roslyn's behavior.

**Comment by vwxyzh** [comment]
And I don't think document should export any implement details.
For document, following implements should be same.
```c#
public bool Test => true;
```
```c#
public bool Test { get { return true; } }
```
```c#
public bool Test
{
   get
   {
       // a long story.
       return true;
   }
}
```

**Comment by aienabled** [comment]
@vwxyzh, I agree that these three example implementations should produce exactly the same code for documentation:
```c#
public bool Test { get; }
```

I think this is only possible if you generate appropriate C# code for properties manually using Roslyn metadata.

**Comment by vwxyzh** [comment]
Before we generate attributes in syntax, we generate syntax just as you mentioned, we replace all `\s+` to a space.
But if the property has several attributes like following code:
```c#
[Test1]
[Test2]
public bool Test
{
  [Test3]
  [Test4]
  get { ... }
  [Test5]
  [Test6]
  set { ... }
}
```
we will generate the syntax like:
```c#
[Test1]
[Test2]
public bool Test
{
  [Test3, Test4]
  get;
  [Test5, Test6]
  set;
}
```
The replacement is worse, so we remove the replacement.

**Comment by aienabled** [comment]
Yes, in that case it will be better to keep all the whitespaces and new lines intact.

**Comment by aienabled** [comment]
Will be this fixed in the next version?

**Comment by vwxyzh** [comment]
fixed in dev branch.

**Comment by aienabled** [comment]
The fix confirmed. Thank you!
