### ISSUE TITLE
A few project not generate document

### ISSUE THREAD

**Issue by John0King** [dotnet/docfx#2513]
**DocFX Version Used**: 2.32.2

**Template used**: `default` 

**Steps to Reproduce**:

1. doxfx init  and change  `metadata:src:files[0]` to `src/**/*.csproj`
2.  copy my project to `src` folder (there are 15+ project in `src`,`test`,`usedLib` and `server` folder)
3. doxfx
3. doxfx serve

**Expected Behavior**:
My project  has the document for my `xxx.Models.csproj`
**Actual Behavior**:
There not document generate for my `xxx.Models.csproj`

**Comment by vicancy** [comment]
Questions:
1. Does the project xxx.Models.csproj contains public classes?
2. Is the project multi-targeted? If yes, you have to specify the `TargetFramework` as https://github.com/dotnet/docfx/issues/1254#issuecomment-294080535 indicates
3. Any warnings when generating document for that project?

You can also attach your minimum-repro project for us to take a look.

**Comment by John0King** [comment]
@vicancy  Thanks, It work now after I specify the TargetFramework.
