### ISSUE TITLE
crefs to built-in types don't show up properly

### ISSUE THREAD

**Issue by benjamin-hodgson** [dotnet/docfx#2518]
**DocFX Version Used**: 2.32.2

**Template used**: `default`

**Steps to Reproduce**:

1. Set up `docfx.json` for BCL xrefs (ie `"xrefService": [ "https://xref.docs.microsoft.com/query?uid={uid}" ]`)
2. Write an xmldoc containing a reference to a built in type (eg `<see cref="System.Int64"/>`). [Real-world example](https://github.com/benjamin-hodgson/Pidgin/blob/b2cad35c2cc80a6dbe15d1abbb921bf3882af434/Pidgin/Parser.Number.cs#L66-L71)
3. Generate the HTML and look at the website

**Expected Behavior**:

The cref shows up correctly, with the correct hyperlink, either under its full name `System.Int64` or (preferably) as `long`

**Actual Behavior**:

The cref is not visible on the page. It shows up in the HTML, but it appears as a `see` tag (`<see cref="!:System.Int64"></see>`), which of course is not valid HTML. [Real-world example](https://github.com/benjamin-hodgson/Pidgin/blob/92ed3ae1d98af9e9ea83579ee4ab22d6780b0967/master/api/Pidgin.Parser.html#L1224).

It appears to function correctly for xrefs to other types - eg, `see` to `IHtmlString` did show up correctly in my testing. Also, if you use a built-in type as a parameter or a return type it does get correctly hyperlinked - it seems to only affect `cref`s which appear directly in the xmldocs.

**Comment by vicancy** [comment]
`!:System.Int64` means that the class is not correctly resolved. Is it netcore project? did you try `dotnet restore` before `docfx metadata`?

**Comment by benjamin-hodgson** [comment]
Yes, it's a .NET Standard library with a new-style csproj. I am restoring packages at the start of my build process, and crefs to other BCL types do seem to be resolved properly. I think it's just the built-in ones that this affects.

**Comment by vicancy** [comment]
Unable to repro it locally. Could you provide a minimum project that repro this issue? for me, I create a simple `netcore2.0` project with:
```cs
using System;

namespace ConsoleApp4
{
    public class Program
    {
        /// <summary>
        /// The resulting <see cref="System.Int64" /> is not checked for overflow.
        /// </summary>
        /// <param name="args"></param>
        public static void Main(string[] args)
        {
        }
    }
}
```
And when running `docfx metadata` it produces yml file inside `_api/ConsoleApp4.Program.yml` containing:
```yml
summary: "\nThe resulting <xref href=\"System.Int64\" data-throw-if-not-resolved=\"false\"></xref> is not checked for overflow.\n"
```
This `xref` tag will then be resolved through xref service.
