### ISSUE TITLE
Problems with <code source=""> and paths

### ISSUE THREAD

**Issue by JuanZamudioGBM** [dotnet/docfx#2523]
**DocFX Version Used**:  
docfx 2.32.2.0 and nuget package docfx.console 2.32.2 in windows 10 with VS2017 15.6.2

**Template used**: default

**Steps to Reproduce**:
I'm getting warnings like this `Warning:[MetadataCommand.ExtractMetadata]Source file  not found.` when in my classes I use this:

```
/// <summary>
/// true if defined
/// </summary>
/// <example>
/// <code source="Example.cs" region="region" language="c#"/>
/// </example>
public static bool IsDefined()
{
}
```

At first my examples were in another project but at the end I copied the example class to the main project to see if the problem were my paths.

The nuget package generated the docfx.json (also happens from the command line), the metadata part of the json its this 

```
"metadata": [
        {
            "src": [
                {
                    "files": [
                        "**.csproj"
                    ],
                    "src": "C:\\Repos\\repo-name\\src\\Code\\Core"
                }
            ],
            "dest": "api",
            "disableGitFeatures": false
        }
    ],
```
My folder structure its like this
repo-name
&ensp;&ensp;src
&ensp;&ensp;&ensp;&ensp;Code
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Core
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp; .csproj
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp; Class.cs
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp; Example.cs
&ensp;&ensp;&ensp;&ensp;Tests
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Core.Tests
 &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp; .csproj

Whenever I build the project I see this in the output window

### 
```
Task "Exec"
1>        "C:\Users\XXX\.nuget\packages\docfx.console\2.32.2\build\..\tools\docfx.exe" "C:\Repos\repo-name\src\Code\Core/docfx.json" -o "" -l "log.txt" --logLevel "Verbose" -f
1>        [18-03-15 01:05:16.726]Verbose:Config file "C:\Repos\repo-name\src\Code\Core/docfx.json" is used.
1>        [18-03-15 01:05:16.947]Info:[MetadataCommand.ExtractMetadata]Using msbuild C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin as inner compiler.
1>        [18-03-15 01:05:17.060]Info:[MetadataCommand.ExtractMetadata]Loading projects...
1>        [18-03-15 01:05:17.063]Verbose:[MetadataCommand.ExtractMetadata](C:\Repos\repo-name\src\Code\Core/Core.csproj)Loading project...
1>        [18-03-15 01:05:20.531]Verbose:[MetadataCommand.ExtractMetadata](C:\Repos\repo-name\src\Code\Core/Core.csproj)Project C:\Repos\repo-name\src\Code\Core\Core.csproj loaded.
1>        [18-03-15 01:05:20.561]Info:[MetadataCommand.ExtractMetadata]Generating metadata for each project...
1>        [18-03-15 01:05:23.706]Warning:[MetadataCommand.ExtractMetadata]Source file 'C:\Repos\repo-name\src\Code\Core\src\Code\Core\Example.cs' not found.
```
### 

The weird thing its that appears that somehow part of the path is being duplicated.

**Expected Behavior**:
Read the class and generate the code example 

**Actual Behavior**:
warning Source file 'C:\\Repos\\repo-name\src\Code\Core\src\Code\Core\Examples.cs' not found.

**Comment by JuanZamudioGBM** [comment]
It has something to do with the path of my project, I tried to create a repo but there were no errors, so I copied my solution to another folder, deleted the docfx and everyting went well.
  
The original path of my solution was 
C:\TSGit\Repos\common-libraries-core\src

The folder when it succeeded was
C:\pocs\docfx-pdf

Maybe its choking in the double hyphen in the folder name?

**Comment by paillave** [comment]
I am facing the same issue:

Here is what I commented in the file `CrossApplyEnumerable.StreamEx.cs`

```
/// <example>
/// <code title="Nested code elements example" language="cs">
/// <code source="CrossApplyEnumerable.StreamEx.cs"/>
/// </code>
/// </example>
```
This example doesn't make sense, but I did it for simplicity purpose to see if I was mistaking somewhere else.
It should include the file in the output documentation, but the following warning is raised:
```
[18-10-22 09:17:41.971]Warning:[MetadataCommand.ExtractMetadata]Unable to get source file path for <code source="CrossApplyEnumerable.StreamEx.cs"></code>
```

**Comment by yufeih** [comment]
We now show the full path to help you diagnose where the problem is.
