### ISSUE TITLE
Tabbed content switch doesn't work if Tab name contains not plain text

### ISSUE THREAD

**Issue by Skudnoff** [dotnet/docfx#2538]
**DocFX Version Used**:  2.31

**Template used**: default

**Steps to Reproduce**:

1.  Add a markdown document with text like this in the project
```
# [**Tab Name**](#tab/tab-id-1)
Content1 ...
# [**Tab Name**](#tab/tab-id-2)
Content2 ...
---
```

> Note that "Tab Name" is bold

2. Build the docfx project
3. Open result document in a browser

**Expected Behavior**: Page with tabbed content that can be switched

**Actual Behavior**: Tabbed content can't be switched

Click event handling doesn't work if you click something other than HTMLAnchorElement

**Comment by vicancy** [comment]
Hi @Skudnoff we will release the version on April 6th as the usual release plan, if you'd like a hotfix for it, please call out.
