### ISSUE TITLE
Version Not Updated in v1.7.1

### ISSUE THREAD

**Issue by blachniet** [dotnet/docfx#254]
The version printed by `docfx -h` for the binary download of [v1.7.1](https://github.com/dotnet/docfx/releases/tag/v1.7.1) prints `docfx 1.7.0.0`.

### Functional impact
None

### Minimal repro steps

1. Download the `docfx.zip` from https://github.com/dotnet/docfx/releases/tag/v1.7.1
2. Unzip the archive
3. Open a command prompt in the unzipped folder
4. `docfx.exe -h`

### Expected result
Prints `docfx 1.7.1.0` followed by copyright, usage, etc.

### Actual result
Prints `docfx 1.7.0.0` followed by copyright, usage, etc.

### Further technical details
I don't think this is a big deal, but I would prefer that it didn't happen in future releases.

**Comment by qinezh** [comment]
Thanks for reporting the issue, I'll fix it ASAP

**Comment by qinezh** [comment]
Hi @blachniet, the release is already updated.
Thanks.
