### ISSUE TITLE
Is it possible to render Project-Version-Number?

### ISSUE THREAD

**Issue by IgorAtDigi** [dotnet/docfx#2542]
**DocFX Version Used**:  Current

**Template used**: `default`

Hi, my Company is using Docfx for documentationen and everything works fine, but the question we've got is: Our Projects safe their current Version-Number in the AssemblyInfo, so we were curious, if it's possible for docfx to take that Version-Number and render it to the Documentationen. Like with an Placeholder on the Index-site or a little Textbox somewhere.

p.s. Great Project

**Comment by superyyrrzz** [comment]
Thanks for supporting!

Do you want DocFX to extract the version info from assembly? DocFX doesn't support this by default, but you can [create an plugin](http://dotnet.github.io/docfx/tutorial/howto_build_your_own_type_of_documentation_with_custom_plug-in.html) to extract the info into model, then [customize the template](http://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html) to render it on page.

**Comment by bitfringe** [comment]
I have the same requirement. Quick and dirty solution I used:
- Get the build version in my build scripts (either from project file, CI worker thats doing the build, env variable, whatever really)
- Use regex to inject/replace that version number as custom json property ("_docsVersion" on my case) into either docfx.json -> globalMetadata node, or use globalMetadataFiles and inject the version number into separate metadata file
- Use the metadata property inside template partial as ` <span>Version: {{{_docsVersion}}}</span>`

Just an idea.

**Comment by macrogreg** [comment]
Hi @superyyrrzz

I have the same requirement. :)

> Do you want DocFX to extract the version info from assembly? DocFX doesn't support this by default, but you can [create an plugin](http://dotnet.github.io/docfx/tutorial/howto_build_your_own_type_of_documentation_with_custom_plug-in.html) to extract the info into model, then [customize the template](http://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html) to render it on page.

The linked article shows how to make a plugin dealing with conceptual documents.
I found close to nothing in terms of documentation on how to write a plugin that would act during metadata generation and add to the metadata generated by the system.

Would you please have any pointers?

Thank you!

**Comment by tig** [comment]
This was closed "as completed" but I don't see how to do it. Help please.

**Comment by paulushub** [comment]
@tig 
> This was closed "as completed" but I don't see how to do it. Help please.

Can you show an example of what you need? A sketch or a screenshot of a use in other docs output, or simply modify a sample output HTML to show what you need.

@macrogreg 
> The linked article shows how to make a plugin dealing with conceptual documents.

The link is to the first top on plugin, [How to add a customized post processor](https://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html) is perhaps what you need.

**Comment by tig** [comment]
> @tig
> 
> > This was closed "as completed" but I don't see how to do it. Help please.
> 
> Can you show an example of what you need? A sketch or a screenshot of a use in other docs output, or simply modify a sample output HTML to show what you need.
> 

Sure. This is what the site looks like now.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/585482/181388297-24d96541-4084-4236-b212-a604cd4fcc32.png">

I'd like to have something like this:

![image](https://user-images.githubusercontent.com/585482/181388439-2e4785e6-dc0c-434c-84cd-25dc37d70d39.png)
