### ISSUE TITLE
XML syntax-highlighting in markdown does not work as intended

### ISSUE THREAD

**Issue by Herrmel** [dotnet/docfx#2553]
**DocFX Version Used**: 2.33

**Template used**: `default`

**Steps to Reproduce**:

1. Create Markdownfile with xml code highlighting
2. Build in Docfx
3. Look result on website

**Expected Behavior**:Rendered like in Github:
```xml
...
<resources>
    <style targetType="ellipse"/>
    <style targetType="rectangle"/>
</resources>
...
```
```xml
...
<rectangle>
	<fill>
		<solidColorBrush color="#FFEAECEF">
	</fill>
</rectangle>
...
```

**Actual Behavior**: Sometimes its just wierd: (example1)
![image](https://user-images.githubusercontent.com/36636591/37969492-30f8f544-31d1-11e8-99e8-f4bcd395a38f.png)

Sometimes its just plain: (example2)
![image](https://user-images.githubusercontent.com/36636591/37969385-dab608a2-31d0-11e8-85b0-bce40023a8fb.png)

Btw: the dots dont change the outcome it still renders the same way as before
![image](https://user-images.githubusercontent.com/36636591/37969852-2b1b34d8-31d2-11e8-8495-99afb295b657.png)

**Comment by vicancy** [comment]
What dos * xml code highlighting* mean? I don't think docfx supports it.
As you mentioned *Expected Behavior:Rendered like in Github:*, do you mean that GitHub supports this syntax? Could you explain how does GitHub support this? I am not aware of that.

**Comment by vicancy** [comment]
Get what you mean. Should be a `highlight` bug.

**Comment by superyyrrzz** [comment]
the latest version 9.12 of highlight.js fixed this issue.

**Comment by Herrmel** [comment]
Thank you
