### ISSUE TITLE
Model transform with default.js

### ISSUE THREAD

**Issue by aienabled** [dotnet/docfx#257]
Hello!

I'm using the latest version 1.7.1.

The documentation https://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html (paragraph 3) says that if you place `default.js` near the template file it will be evaluated and `transform()` function will be called.

However, I have no luck with it. It simply doesn't work for me wherever I place "default.js". Might you clarify how to use this functionality properly please?

Regards!

**Comment by vicancy** [comment]
The doc is out of date.
We are refactoring template system, and meanwhile updating the doc.`
