### ISSUE TITLE
visual studio c# console application outside DocFX src folder does not create documentation

### ISSUE THREAD

**Issue by iglezos** [dotnet/docfx#2576]
**DocFX Version Used**: 2.33.1.3 

**Template used**: `default`

**Steps to Reproduce**:

1. I have downloaded and unzip DocFX to a folder
2. I have created a dummy .net4.0 console application
3. I have created DocFX default project with ..\docfx\docfx init -q in the console application folder
4. I have changed default src to 
"src": [
        {
          "files": [
            "**.csproj"
          ],
          "src": ".."
        }
      ],
      "dest": "api",
      "disableGitFeatures": false
5 I execute ..\docfx\docfx docfx_project\docfx.json 

**Actual Behavior**:
the console application has been found by docfx and has been build successfully but the following message is shown
Warning:[MetadataCommand.ExtractMetadata]No metadata is generated for ConsoleApp2
and the site is not showing the expected results
[ConsoleApp2.zip](https://github.com/dotnet/docfx/files/1865762/ConsoleApp2.zip)

**Comment by vicancy** [comment]
Hi @iglezos is there any `public` classes in your console app? Only `public` ones are extracted to generate docs.

**Comment by iglezos** [comment]
As you can see from attached zip file there is a public class
public class Math {
...
}

**Comment by iglezos** [comment]
hello,
the actual problem was that the public class was outside the namespace of the .cs file.
Thank you.
