### ISSUE TITLE
Support for example tag in default template

### ISSUE THREAD

**Issue by aienabled** [dotnet/docfx#258]
Hello!
I'm using the latest version - 1.7.1.

I've noticed that the code like this:
```c#
///<summary>
///Some text.
///</summary>
///<example>
///<code language="c#">
///	SomeStaticClass.Foo();
///</code>
///</example>
public static void Foo() { }
```

is producing `example` data to the YML, but default template doesn't output this into the HTML.

In the seed documentation there are also no HTML output for `example` tag:
source
https://github.com/docascode/docfx-seed/blob/12139e36b2546c4c50db59025bc94dae5f09aa8e/src/SampleClass1/CatLibrary/Class1.cs
page
http://docascode.github.io/docfx-seed/api/CatLibrary.Cat%602.html

Will you provide support for this in the future versions?

Regards!

**Comment by ansyral** [comment]
viewmodel aleady contains such info, seems that our templates don't handle example part

**Comment by jskeet** [comment]
Given that examples can be quite long (and we're showing the details for all the members in a class at once), I think it would make sense for them to be collapsible in the template. But yes, please include them in the default template ASAP... this is currently a blocker for me :(

**Comment by ansyral** [comment]
pull request #264

**Comment by ansyral** [comment]
@aienabled @jskeet it is fixed in dev

**Comment by aienabled** [comment]
@ansyral, the template generates example documentation, but only for `<example>` tag defined in the class declaration. But what about the members? According to [MSDN](https://msdn.microsoft.com/en-us/library/9w4cf933.aspx):
> The <example> tag lets you specify an example of how to use a method or other library member. This commonly involves using the <code> tag.

Regards!

**Comment by aienabled** [comment]
So, will you provide the support for `<example>` tag for methods documentation in the default template?

**Comment by aienabled** [comment]
Thanks, it works now!
However, it contains extra padding in that case:

```
/// <example>
/// <code language="c#">
/// ClientToServerProxy.Call(() => ServerRemote_DoSomethingOnServer(someArgument1, someArgument2);
/// </code>
/// </example>
```

Result screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/865384/15180036/719e5a10-17a9-11e6-8a20-e4253b2c8390.png)

Might you add trimming for extra spaces/tabs/newlines?

**Comment by ansyral** [comment]
Thanks @aienabled for pointing this out. These comments are transformed from xml fragments and we should trim the extra spaces/tabs//newlines

**Comment by ansyral** [comment]
pull request #315

**Comment by ansyral** [comment]
@aienabled the fix is in dev branch

**Comment by aienabled** [comment]
@ansyral, great job, it works perfect now!
