### ISSUE TITLE
Logging, progress and telemetry

### ISSUE THREAD

**Issue by vicancy** [dotnet/docfx#2586]
We need:

- [x] Report to show errors and warnings to end users (output to `stderr`)
- [x] Log to help us diagnostics issues (output to `stdout`)
- [x] Progress to show build status
- [ ] ~~Telemetry connected to application insights to track usage~~

@OsmondJiang @herohua

**Comment by yufeih** [comment]
We need:

- [x] Report to show errors and warnings to end uers
- [ ] Log to help us diagnostics issues
- [ ] Progress to show build status
- [ ] Telemetry connected to application insights to track usage
