### ISSUE TITLE
Can not generate metadata on my colleague machine.

### ISSUE THREAD

**Issue by tungnt185** [dotnet/docfx#259]
Hi all,

I'm using DocFx lastest version 7.1 on my computer everything work fine.
My machine install Visual Studio 2013 and Visual Studio 2015.

But when it run on my colleague machine with only VS2013 Docfx didn't generate metadata for my project. It's show warning for each project "Could not load file or assembly System.Threading.Task.DataFlow.dll 4.5.24..."

I cannot resolve this because I don't know why I received this error because my project doesn't reference it.

Please help me.
Thanks in advance.
Tung

**Comment by sergey-vershinin** [comment]
@tungnt185, do you have .net framework 4.5.2 installed on this machine? Also, [.net framework 4.5.2 developer pack](https://support.microsoft.com/ru-ru/kb/2901951) may help.

**Comment by tungnt185** [comment]
Hi @sergey-vershinin ,

I've try install .net 4.5.2 but no success then I've installed VS2015 on this machine and it works like a charm. So I think VS2015 is prerequisite to use DocFX, it's right?

Thanks and best regards.
Tung

**Comment by sergey-vershinin** [comment]
@tungnt185, It sounds strange if I need VS2015 only to run docfx from the command line. I think that VS2015 installs something that contains System.Threading.Task.DataFlow.dll 4.5.24. The question is what is that "something". Think that this is a doc issue.

**Comment by simonmurdock** [comment]
It is a prerequisite, see this doc: http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html

**Comment by sergey-vershinin** [comment]
@simonmurdock, only when one uses docfx in Visual Studio, according to http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#3-use-docfx-in-visual-studio

**Comment by simonmurdock** [comment]
Yes. I've used it on the command line without issue

**Comment by sergey-vershinin** [comment]
I tried to run `docfx metadata` on a machine with only VS 2013 installed and the error with *System.Threading.Task.DataFlow.dll 4.5.24* occured. Then I installed the *.Net Framework 4.5.2 Developer Pack* - this didn't help. The solution was to install [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/confirmation.aspx?id=48159) which added *System.Threading.Task.DataFlow.dll 4.5.24* to the GAC.

**Comment by simax** [comment]
I had exactly the same issue. @svver is correct, If you only have VS2013 installed you simply need to install [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/confirmation.aspx?id=48159).

This is only mentioned in the docs if you want to build from source code. I just carried out step **2. Use DocFX as a command-line tool.** It should be stated in step 2 also that if you only have VS2013 installed you will need to install [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/confirmation.aspx?id=48159). This will prevent the **System.Threading.Task.DataFlow.dll** error message from appearing.
