### ISSUE TITLE
Feature: Generate Documentation From Tests

### ISSUE THREAD

**Issue by jaredcnance** [dotnet/docfx#2594]
I would like to be able to generate HTTP API documentation from end-to-end acceptance tests. Prior art exists for other frameworks/languages:

- (Ruby | Rails) [dox](https://github.com/infinum/dox)
- (Ruby | Rails) [rspec_api_documentation](https://github.com/zipmark/rspec_api_documentation)
- (Elixir | Phoenix) [bureaucrat](https://github.com/api-hogs/bureaucrat)
- (Java | Spring) [Spring REST Docs](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api)

I believe that dotnet needs a similar story for automated API generation using tests. There are a few benefits to this approach over using something like Swagger:

- maintain a true separation between application code and documentation, no decorators or middleware
- just write tests and that functionality will be documented
- application does not have to be running, documentation can be static

I don't think that such a tool **needs** to be built into docfx itself, but since it looks like docfx is attempting to be the de facto documentation generator for dotnet, I think it should at least integrate nicely with docfx.

I wanted to open this issue to begin a discussion on:

- what are the best ways to approach such a project?
- has any work like this already been done?
- what kinds of artifacts would the testing wrappers need to produce? is markdown sufficient?
- are there any showstoppers at this time?

**Comment by yufeih** [comment]
Docfx does not natively support generating docs out of tests, but provides an [extension mechanism to support additional languages](https://dotnet.github.io/docfx/docs/additional-languages.html).
