### ISSUE TITLE
DocFX extract metadata exception 

### ISSUE THREAD

**Issue by tungnt185** [dotnet/docfx#260]
Hi all,

I'm using Docfx with a solution have many project but some project cannot generate metadata.
Detail error: "Extract metadata exception: error extracting metadata for ... System InvalidOperationException: Unexpected membertype...Add reference symbol..."

I don't have any clue to solve this, please help me.

Thanks.
Tung

**Comment by vicancy** [comment]
Anywhere for us to take a look at the project that repros the issue?

**Comment by tungnt185** [comment]
Hi @vicancy 

At the moment I can't extract my project to create a reproduce sample for you because my company security policy.

Do you have any suggestion for me to overcome this?

Regards
Tung

**Comment by tungnt185** [comment]
Hi @vicancy,

After debug with code, I've realized error from `VisitorHelper.GetMemberTypeFromTypeKind`
We have VB.NET project and have many Module but this function doesn't have Module in case so we have exception.

I've edit to include Module in case Class and have success. I don't know it has any side effec with the rest of code but it work for me now.
`switch (typeKind)
            {
                case TypeKind.Class:
                case TypeKind.Module:
                    return MemberType.Class;`

Hope it help someone.

Thanks and best regards.
Tung
