### ISSUE TITLE
Can I provide Markdown references in one central place?

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#261]
I have a lot of Markdown which uses references without explicitly defining them, expecting that definition to come elsewhere. For example:

> This uses a [foo][foo].

I'd like to be able to provide a single file which provides all these references, e.g.

```
---
uid: xrefs
---

[foo]: xref:Something.Foo
```

It's possible this is what the `externalReferences` part of `docfx.json` is meant to be for, but the documentation isn't clear about that yet (and it's not clear whether or not it's implemented).

**Comment by chenkennt** [comment]
`externalReferences` is for resolving cross reference. If you write `[foo](xref:foo)` or `<xref:foo>` in markdown, DocFX will search cross reference definition and find one with id `foo`. `externalReferences` allows you to specify a place for all markdown files in the project. Its format is different from markdown reference, here is an [example](http://dotnet.github.io/docfx/xrefmap.yml). @jskeet , does this meet you need?

**Comment by jskeet** [comment]
Yes, I *think* that will be absolutely fine, thanks.
Is that already implemented, or still in progress?

**Comment by chenkennt** [comment]
It's already implemented, we're working on documentation.

**Comment by jskeet** [comment]
Great. Will close this issue, at least for now, and reopen or raise another one if I find problems.
