### ISSUE TITLE
Fulltext search error when index.json large

### ISSUE THREAD

**Issue by tungnt185** [dotnet/docfx#262]
Hi all,

When using DocFx generate large project so large file index.json I've received javascript error when use fulltext search:
"Uncaught RangeException: Maximum call stack size exceeded" from lunr.min.js
My index.json about 16MB. Are there anyway to resolve this?

Thanks and best regards.
Tung.

**Comment by vwxyzh** [comment]
you can disable client search by following command:
```
docfx --globalMetadata "{_enableSearch: false}"
```

**Comment by qinezh** [comment]
@tungnt185  The size of your index.json is too large for full text search in client side. Does the index.json contain too much invalid information? Or just because your website is too large?

**Comment by joelmartinez** [comment]
Maybe there should be an extensibility point so that we can use a different indexing strategy for larger sites ... for example, a lucene search index that we can expose through other means.

**Comment by qinezh** [comment]
@joelmartinez You can transform `index.json` into different index format that other full text search library support.

**Comment by joelmartinez** [comment]
Yes, that is true :) However, it doesn't really solve @tungnt185's problem in that they are having to disable the search ... thus they wouldn't have an index.json to work from.

**Comment by tungnt185** [comment]
@qinezh I think is's because of my index.json file is too large.

**Comment by qinezh** [comment]
So the key point is that you want docfx to generate index.json even if you disable the full text search? @joelmartinez

**Comment by qinezh** [comment]
Yes, I know that. Several possible reasons may lead to that. The first one could be that index.json contains too much invalid information for full text search. The second one could be that the website you want to generate is too large. So, which reason do you think makes index.json too large? @tungnt185

**Comment by joelmartinez** [comment]
@Qinezh no I'm sorry, no that's not what I meant :) I'm suggesting that there be a way, similar to writing a custom document processor, to swap out the document indexing. That way, one could write a Lucene indexing routine, for example :)

**Comment by qinezh** [comment]
@joelmartinez you can customize the `index.json` with [post processor](http://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html) in latest DocFx. Hope this would help you.
