### ISSUE TITLE
Single-letter namespace aliases cause resolution failures

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#2620]
**DocFX Version Used**: 2.32.1

**Template used**: n/a

**Steps to Reproduce**:

Three files:

`Aliases.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
</Project>
```

`Class1.cs`:

```csharp
using x = System;
using xy = System;

namespace Aliases
{
    /// <summary>Fails: <see cref="x::ArgumentException" /></summary>
    /// <remarks>Works: <see cref="xy::ArgumentException" /></remarks>
    public class Class1
    {
    }
}
```

`docfx.json`:

```json
{
  "metadata": [
    {
      "src": [ { "files": [ "Aliases.csproj" ] } ],
      "dest": "obj/api"
    }
  ]
}
```

Then just run `docfx metadata -f`

**Expected Behavior**:

No warnings or errors.

**Actual Behavior**:

```text
Warning:[ExtractMetadata]Invalid cref value "x::ArgumentException" found in triple-slash-comments for Class1 defined in Class1.cs Line 7, ignored.
```

This appears to happen for any single-letter namespace alias. Notice how the alias of `xy` doesn't cause a problem.

**Comment by jskeet** [comment]
As noted on Twitter, single-letter-followed-by-colon has a meaning within the transformed XML, and it looks like VS treats it differently too, although I can't see anything in the language specification to indicate that it should do so. So this may not be a bug in docfx particularly, but just an unspecified oddity of the C# compiler :(

**Comment by superyyrrzz** [comment]
I am not sure of the root cause, but it should mistake it as some comment id like `T:...`, `M:...`. It is like a bug but not too harmful.

**Comment by KalleOlaviNiemitalo** [comment]
As Class1.cs does not declare `extern alias x;`, I'd expect it to use `cref="x.ArgumentException"` rather than `cref="x::ArgumentException"`.

**Comment by yufeih** [comment]
Close as VS shares the same behavior.
