### ISSUE TITLE
Can't install nuget package to class lib project in .Net 4.6.1

### ISSUE THREAD

**Issue by justcoding121** [dotnet/docfx#2622]
**DocFX Version Used**: 2.33.2 (latest) in VS 2017 for a class lib project (.Net 4.6.1)

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1. Install nuget package and it fails with message 
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependency 'Microsoft.DocAsCode.Build.OverwriteDocuments'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.			0	

Below dependency install fails because it depends on **Microsoft.DocAsCode.Build.OverwriteDocuments** which is not available anymore.
https://www.nuget.org/packages/Microsoft.DocAsCode.Build.SchemaDriven/
https://www.nuget.org/packages/Microsoft.DocAsCode.Build.OverwriteDocuments/

**Expected Behavior**:

**Actual Behavior**:

**Comment by vicancy** [comment]
Thanks for reporting the issue @justcoding121 Please use feed https://www.myget.org/F/docfx/api/v3/index.json to temporarily workaround the issue.

Curious about which package are you using? In theory you only need `docfx.console` package for running docfx in IDE.

**Comment by justcoding121** [comment]
Okay.  I was trying to use this to generate documentation for [one of our projects](https://github.com/justcoding121/Titanium-Web-Proxy) following the instructions in docfx website.
