### ISSUE TITLE
Code in fenced code blocks not properly indented

### ISSUE THREAD

**Issue by ryansburgoyne** [dotnet/docfx#2623]
**DocFX Version Used**: `docfx 2.33.1.0`

**Template used**: `default`

**Steps to Reproduce**:

1. Include the following file as source in a docfx build:

```csharp
namespace MyNamespace
{
    /// <summary>
    /// A really important class.
    /// </summary>
    /// <example>
    /// ```csharp
    /// MyClass myClass = new MyClass();
    ///
    /// void Update()
    /// {
    ///     myClass.Execute();
    /// }
    /// ```
    /// </example>
    public class MyClass
    {

        /// <summary>Execute.</summary>
        public void Execute()
        {
        }
    }
}
```

2. Kick off a docfx build
3. Serve the site and view the API Documentation

**Expected Behavior**: The code block within the comment is properly indented.

**Actual Behavior**: The code block is left-aligned with no indentation. If the fences are replaced with `<code></code>` tags, it works as expected.

**Comment by superyyrrzz** [comment]
Related: #4017

**Comment by brianlagunas** [comment]
This is still an issue. Any updates? Possibly a v3 effort?
