### ISSUE TITLE
Preview issue in VSCode with DocFX v0.1.1

### ISSUE THREAD

**Issue by hqywork** [dotnet/docfx#2633]
**DocFX Version Used**: v2.34
> v2.34
**Template used**: (`default` or `statictoc` or contain custom template) 
> default
**Steps to Reproduce**:

1. Write `> [!Important]` fragment
2. Use VSCode with DocFX v0.1.1 preview (DocFx: Open DocFX preview to the side (Only support DocFX 2.17+))

**Expected Behavior**:

**Actual Behavior**:
> Not properly displayed

**Comment by 928PJY** [comment]
hi @hqywork  we have fixed this problem in v-0.1.3
![image](https://user-images.githubusercontent.com/17958546/38846637-03bddd28-4230-11e8-853a-e6225a7189ea.png)
please have a try, contact us if you have any more questions
