### ISSUE TITLE
DocFx does not parse description metadata

### ISSUE THREAD

**Issue by Still34** [dotnet/docfx#2638]
**DocFX Version Used**: 
 2.34.0.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Add `_description` with a description string under `globalMetadata`
2. Build the documents

**Expected Behavior**:
DocFx would generate each webpage containing the description metadata, essentially filling in `<meta name="description" content="{{_description}}">`

**Actual Behavior**:
DocFx does not recognize this tag, despite description being mentioned throughout all partial files.

**Comment by Still34** [comment]
Bump

**Comment by superyyrrzz** [comment]
Hi @Still34 , sorry for late response. I have a try and find it can work:
![image](https://user-images.githubusercontent.com/3831744/54737823-a7bc2080-4bec-11e9-888c-5c3db08da0fc.png)
![image](https://user-images.githubusercontent.com/3831744/54737849-b99dc380-4bec-11e9-8ca5-f5ccff7c2519.png)

**Comment by Still34** [comment]
Got it, will try to repro later.
