### ISSUE TITLE
Tabbed Content in Markdown is broken

### ISSUE THREAD

**Issue by Herrmel** [dotnet/docfx#2645]
**DocFX Version Used**:  2.34

**Template used**: `default`

**Steps to Reproduce**:
follow the toturial:
http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#tabbed-content 

**Expected Behavior**: Tabbed content changes correctly all the time and position is fix

**Actual Behavior**: Tabbed Content doesnt change after first click on second tab even though second tab is marked. But if you click back to first and then back again on 2nd tab it shows the content. Also the site changes positions very awkwardly throughout all of this.

Example: Your own Documentation has the same issue:
http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#tabbed-content

Previous Version did not have this issue i think.

**Comment by Still34** [comment]
I believe it's been broken for several versions now, but I'm also experiencing this issue.

**Comment by vicancy** [comment]
Looks like the URL is messed up. Will take a look. Thanks for reporting the issue.
