### ISSUE TITLE
"You have reached the include limit of 1024" error when applying toc template in docfx 1.7.1

### ISSUE THREAD

**Issue by sergey-vershinin** [dotnet/docfx#266]
After upgrading docfx to 1.7.1 version `docfx build` results in the following error: 

*Error: Error applying template "toc.html.tmpl" to view model "obj\viewmodel\api\toc.html.view.json" generated from "C:\MyProjectPath\api\toc.yml": You have reached the include limit of 1024. Are you trying to render infinitely recursive templates or data?*

The codebase is quite large (~2500 .yml files in api folder), but everything worked fine with docfx 1.6.2.

**Comment by vicancy** [comment]
Hi @sergey-vershinin , thanks for reporting the issue. Is it possible for you to provide me the generated **"obj\viewmodel\api\toc.html.view.json"** file? It's root folder is the same folder with your `docfx.json` file

**Comment by sergey-vershinin** [comment]
Hi @vicancy! I've truncated the codebase, now there is one small project but the error still exists. Here is the view model - https://github.com/sergey-vershinin/docfx-issues/blob/master/include%20limit/toc.html.view.json.

**Comment by sergey-vershinin** [comment]
@vicancy, It seems that the problem is with my custom template. I've removed it from docfx.json and the error has gone. This is strange because I didn't change anything related to toc templates. 
I'll try to fix my template or reproduce the error on a new sample project.

**Comment by vicancy** [comment]
Toc template calls `partials/li.tmpl.partial`, and `partials/li.tmpl.partial` recursively calls itself, any chance `partials/li.tmpl.partial` is changed?

**Comment by sergey-vershinin** [comment]
@vicancy, no I didn't change `li.tmpl.partial`. But I exported the default template with docfx 1.6.2. Then I renamed the containing folder, made changes and added the resulting template to `docfx.json`. And then I upgraded docfx to 1.7.1 version but didn't touch my template. 

I've just repeated the steps above using 1.7.1 version and everything works now. Sorry for bothering!
