### ISSUE TITLE
triple-slash comments seealso will not link by uid xref

### ISSUE THREAD

**Issue by rhessinger** [dotnet/docfx#2664]
**DocFX Version Used**:  2.34.0.0

**Template used**: default

**Steps to Reproduce**:

1. Setup a new docfx project that has multiple solutions in the src directory
2.  Add a triple slash see also with a namespaced class from another solution `/// <seealso cref="namespace.className" />`
3. `docfx.exe metadata`
4. `docfx.exe build`

**Expected Behavior**:

Since __namespace.className__ is the unique uid on another class in another solution within the same docfx project, it should show in the 'see also' section with an xref link to the uid __namespace.className__.

**Actual Behavior**:

The see also section does not create.

**Other Notes**

If markdown is enabled inside of the triple-slash comments using `[namespace.className](xref:namespace.className)`

**Comment by vwxyzh** [comment]
#2646

**Comment by yufeih** [comment]
Closed as duplicate
