### ISSUE TITLE
Can I generate HTML documentation from already-generated XML?

### ISSUE THREAD

**Issue by gusennan** [dotnet/docfx#2670]
Can docfx be used to generate a webpage from already-extracted XML documentation?  My use case is that I have some compiled, close-source assemblies, and the corresponding XML documentation for those assemblies that allow me to read documentation in editors like VS or Rider.  I'd like to turn these XML files directly into HTML documentation, so I can read the documentation outside of VS.  

I took a look at docfx's documentation and couldn't find a way to do this.

**Comment by vwxyzh** [comment]
@gusennan source can be dll files, and we will look up the xml files in the same folder.
e.g.:
```json
{
  "metadata": [
    {
      "src": "your_folder/*.dll",
      "dest": "metadata_output_folder"
    }
  ]
}
```

**Comment by atodkar** [comment]
I tried exact steps with my .Net 5 project but getting below error-

`
[21-01-26 11:23:51.262]Warning:[MetadataCommand.ExtractMetadata]No metadata is generated for ProjectName.
`

I see the XML file is available in location.

**Comment by bernmuel** [comment]
I also got a similar message
