### ISSUE TITLE
Question about generating html pages for methods/fields/constructors/etc

### ISSUE THREAD

**Issue by jalley3** [dotnet/docfx#2671]
Where is it that I specify to create a separate file for these entities? Right now it is just throwing the contents into each class page, but I would like them split out into their own page, so i can use tables in the class files to reference them (similar to how it is done on msdn). I have the table working, but the href just points to the same class page, which is to be expected, as in the manifest, they are mapped to the class.html

**Comment by Herrmel** [comment]
There is a plugin for this called memberpage:
https://dotnet.github.io/docfx/templates-and-plugins/plugins-dashboard.html
but take note that for me in very big projects the toc becomes very large so that the page loaded for a pretty long time.

**Comment by jalley3** [comment]
Thanks, I tried this plugin but it doesnt create the member pages at all =-/  (yes I updated the docfx.json)

**Comment by superyyrrzz** [comment]
@Herrmel You can try `statictoc` template

**Comment by herohua** [comment]
@jalley3 Have you tried the solutions above?
