### ISSUE TITLE
Specify status codes for redirected/removed content

### ISSUE THREAD

**Issue by guardrex** [dotnet/docfx#2672]
When a topic is removed on purpose, we should be sending back a *410 Gone* response.

I don't see an issue or documentation on whether or not this is possible outside of a **\<meta>** tag kept in a dummy document for the requested file. For example:

*nano-server.md*

```html
<html>
<head>
    <title>Resource removed</title>
    <meta http-equiv="Status" content="410 Gone">
</head>
<body>
</body>
</html>
```
Is it possible to configure DocFX to respond with a *410 Gone* in such cases so that we don't need to use that approach?

**Comment by vicancy** [comment]
We can have such config to auto generate a dummy html. @superyyrrzz @vwxyzh any idea?

**Comment by guardrex** [comment]
So something similar to how the redirection file exists today.

*.openpublishing.removed.json*

```json
{ 
  "removed": [ 
    {   
        "source_path": "aspnetcore/publishing/vsts-continuous-deployment.md"
    }
  ]
}
```

... or incorporate the `removed` list into the current *.openpublishing.redirection.json* file ...

```json
{
  "redirections": [ 
    {   
      "source_path": "aspnetcore/performance/measuring.md", 
      "redirect_url": "/aspnet/core/performance/", 
      "redirect_document_id": false 
    }
  ],
  "removed": [ 
    {   
        "source_path": "aspnetcore/publishing/vsts-continuous-deployment.md"
    }
  ]
}
```

... and then for URL ...

`http://docs.microsoft.com/en-us/aspnet/core/publishing/vsts-continuous-deployment`

... the response is ...

```html
<html>
<head>
    <title>Resource removed</title>
    <meta http-equiv="Status" content="410 Gone">
</head>
<body>
</body>
</html>
```

**Comment by yufeih** [comment]
Does `401 Gone` have any advantage over `404 Page not found` in this case?

**Comment by guardrex** [comment]
Yes, it reports to the requesting system that the resource was removed on purpose and that there is no replacement or alternate content for the address (i.e., something to redirect to). If the requesting system is a search engine bot, the search engine should delist the address. It would also confirm to a casual visitor that the page was removed on purpose and not that they have the wrong address.

**Comment by yufeih** [comment]
cc @cillroy

**Comment by guardrex** [comment]
Just want to add on here in case this goes forward. I think the system defaults redirects to 302. Whatever the case tho, it would be nice for redirects (and removed) if the maintainer can specify what status code that they would like returned. Something like ...

```json
{
  "redirections": [ 
    {   
      "source_path": "aspnetcore/someplace/example1.md", 
      "redirect_url": "/aspnet/core/someplace-else/example1", 
      "redirect_document_id": false,
      "status_code": 301
    },
    {   
      "source_path": "aspnetcore/someplace/example2.md", 
      "redirect_url": "/aspnet/core/someplace-else/example2", 
      "redirect_document_id": false,
      "status_code": 302
    }
  ],
  "removed": [ 
    {   
        "source_path": "aspnetcore/publishing/vsts-continuous-deployment.md",
        "status_code": 410
    }
  ]
}
```

**Comment by superyyrrzz** [comment]
@guardrex The config looks good. Based on the config, DocFX may generate a `.htaccess` for `Apache`, or `web.config` for IIS user.

However, [GitHub Pages will not support this for security reasons](https://help.github.com/en/articles/redirects-on-github-pages)

**Comment by guardrex** [comment]
@superyyrrzz Side Question for you ... Is it ok today to add a date to these entries?

I ask because we're in a situation with some topics that need a temporary redirect. We might want to note a date to ourselves (just for our own human use) so that we can manually go in later and delete some redirection rules. Can the system that processes the file handle something like this today without :boom: ...

```json
{
    "redirections": [
        {
            "source_path": "aspnetcore/fundamentals/host/index.md",
            "redirect_url": "/aspnet/core/fundamentals/index#host",
            "redirect_document_id": false,
            "added": "10/10/2018"
        },
        {
            "source_path": "aspnetcore/tutorials/first-mvc-app-xplat/index.md",
            "redirect_url": "/aspnet/core/tutorials/first-mvc-app",
            "redirect_document_id": false,
            "added": "1/15/2019"
        },

        ... continued ...
```

**Comment by superyyrrzz** [comment]
@guardrex It's ok 😄 They will just be ignored.

**Comment by yufeih** [comment]
Close as this is a mslearn specific ask.

**Comment by guardrex** [comment]
@yufeih ... Who is your supervisor?
