### ISSUE TITLE
Exception when using [MyAttribute(typeof(GenericClass<>))]

### ISSUE THREAD

**Issue by xen2** [dotnet/docfx#268]
Repro project:
[DocfxAttributeIssue.zip](https://github.com/dotnet/docfx/files/223993/DocfxAttributeIssue.zip) (just run docfx.exe with root folder as working directory)

`CSharpNameVisitor.VisitNamedType` is called with a `symbol` argument of type `UnboundArgumentErrorTypeSymbol` whose `ContainingNamespace` is null, resulting in a `NullReferenceException`.

symbol.ErrorInfo is: `error CS7003: Unexpected use of an unbound generic name`

**Comment by vwxyzh** [comment]
released in v1.8
