### ISSUE TITLE
Is the feature for Multiversioning still supported?

### ISSUE THREAD

**Issue by Herrmel** [dotnet/docfx#2680]
I was experimenting a little bit with my documentation and found #396. So I tried that but I got a lot of Errors in the build section. So I was wondering if this feature is still supported since I cant find anything in the offical documentation. In case it is heres my Issue;

**DocFX Version Used**:  2.34

**Template used**: `default`

**Steps to Reproduce**:
1. Setup Json like in [sample](https://github.com/dotnet/docfx/pull/477#issue-164260549)
2. Create 2 Metadata
3. Build

**Expected Behavior**: Build MultiVersionApi-Website

**Actual Behavior**: Fails to build with multiple similar Errors like: 
```Error:[BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply Templates](api/Something.yml)Error transforming model "{FilepathOfSomething}.raw.json" generated from "api/Something.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor:```

**Comment by superyyrrzz** [comment]
It is still supported. From the error message you provide, I think it meets some issue when template handles the raw model. Does it work if you build just single version?

**Comment by superyyrrzz** [comment]
Could you provide the repoduce steps for this? I cannot tell what happened from the message provided.
