### ISSUE TITLE
Links to other Markdown documents in project with spaces in filenames do not render correctly in preview

### ISSUE THREAD

**Issue by joshuaalm** [dotnet/docfx#2681]
**DocFX Version Used**: 
v0.1.3
**Template used**: (`default` or `statictoc` or contain custom template)
none/default
**Steps to Reproduce**:

1. Create a second document with a space in the filename (e.g. "Outlook Macro.md")
2. Create a link to that document in first document: [macro](Outlook Macro.md)
3. Observe link in preview

**Expected Behavior**:
As in the same documents when viewed on internal Gitlab site, text in square braces is link and document with filename indicated is loaded when clicked.
**Actual Behavior**:
Only the last word of the filename and the .md extension ('Macro.md', in the example above) is presented as a link, which opens a browser tab to that URL (http://macro.md).  All of the remaining characters of the link - square braces, link text, parentheses, and the remainder of the file name are presented as unformatted text.

**Comment by vwxyzh** [comment]
For CommonMark, `[macro](Outlook Macro.md)` is not a valid link.
For DFM, current output `<a href="Outlook Macro.md">macro</a>` do not make sense, at least it should `<a href="Outlook%20Macro.md">macro</a>`, or just follow CommonMark output a plain text.
