### ISSUE TITLE
Broken dependency in nuget package Microsoft.DocAsCode.Metadata.ManagedReference

### ISSUE THREAD

**Issue by SavchenkoAlexander** [dotnet/docfx#2682]
**DocFX Version Used**: 
2.34

**Steps to Reproduce**:

1. Create new ClassLibrary (.Net Framework) project in Visual Studio.
2. Try to add nuget package 'Microsoft.DocAsCode.Metadata.ManagedReference.2.34.0' (or 2.33.0).

**Expected Behavior**:
nuget package added to project references
**Actual Behavior**:
Errror: Unable to resolve dependency 'Microsoft.DocAsCode.Metadata.ManagedReference.FSharp'.

**Comment by SavchenkoAlexander** [comment]
The same for 2.36.0:

![notfound](https://user-images.githubusercontent.com/32193978/40296227-b6a122d2-5ce4-11e8-8979-d38c416300c0.png)

**Comment by 928PJY** [comment]
hi, @SavchenkoAlexander, this issues has been fixed and new version NuGet packages(v2.36.1) has been published. please have a try.
