### ISSUE TITLE
DocFx preview doesn't properly handle tabbed conceptual

### ISSUE THREAD

**Issue by jamarw** [dotnet/docfx#2683]
Information copied from[ issue](https://github.com/Microsoft/vscode-docs-authoring/issues/23) in another repo.

File used to reproduce: https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md

That topic has two tabs, "Visual Studio" and "Any editor", with "Visual Studio" appearing first in the file. The second tab's contents don't render at all in the preview. The tabs themselves render as a bulleted list of links, but clicking the links does nothing.

![image](https://user-images.githubusercontent.com/8966342/38735581-2bc98f4c-3ef7-11e8-867f-4f8c551b6733.png)

**Comment by 928PJY** [comment]
hi @jamarw, thanks for using the extension, but please move to the [docs-markdown](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-markdown), `Docfx` will not be supported anymore.
