### ISSUE TITLE
YAML front matter renders in DocFx preview

### ISSUE THREAD

**Issue by jamarw** [dotnet/docfx#2684]
Information copied from [issue](https://github.com/Microsoft/vscode-docs-authoring/issues/22) in another repo.

Opening the DocFx preview of a topic with CTRL+K, Q displays the YAML header. That should be hidden.

File used to reproduce: https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md

![image](https://user-images.githubusercontent.com/8966342/38735314-72f28a28-3ef6-11e8-8e11-397befe6081e.png)

**Comment by superyyrrzz** [comment]
ping @928PJY

**Comment by 928PJY** [comment]
hi @jamarw, thanks for using this extension, but please move to the [docs-markdown](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-markdown), `Docfx` will not be supported anymore.
