### ISSUE TITLE
.csproj with NuGet makes docfx fails, should docfx detect project/compile errors or handle this gracefully?

### ISSUE THREAD

**Issue by xen2** [dotnet/docfx#269]
I have a .csproj that doesn't compile properly (because of EnsureNuGetPackageBuildImports needs $(SolutionDir) defined). As a result, mscorlib is not properly referenced.

With older version, this assembly was still working fine (lot of unresolved symbols) but since attribute support was added, it fails because of a `NullReferenceException` when accessing `attr.AttributeConstructor` (since `Attribute` class from mscorlib is unresolved).

My question is, which way should we go?

- should docfx still be able to process this properly even though there is errors, just like older versions (roslyn can still extract most symbols anyway, it just need a few additional null checks)
- should the project be error-free to be processed? (in which case it should display project/compile errors and likely fail if there is any, and either give a way to override SolutionDir or some other variables, or I should provide a proper .sln with only the project I want to generate doc for -- note that many projects are likely to be in this state due to the fact .csproj are rarely opened as is and often contain nuget targets).

**Comment by vwxyzh** [comment]
We found this bug serval days ago.
And we ignore all error type in attributes in dev branch.
The fix is here: 601b478cfa4d96489ee4c99f45d43ac8d79b7ab4

**Comment by xen2** [comment]
Thanks, I consider it fixed then!
