### ISSUE TITLE
Handle href resolution

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#2699]
- [x] resolve basic markdown links
- [x] resolve html links inside markdown
- [ ] resolve TOC links
- [x] show warnings when resolve failed
- [x] handle escape
- [x] Handle dependencies
- [x] Handle output URL conflict
- [x] Handle output file path conflict
- [x] Handle files outside initial build scope

**Comment by yufeih** [comment]
One of the goal is to switch between platforms without friction, here is the proposal:

- Require path to be case sensitive
- Support both forward slash and back slash
- Do not allow two files with same name but difference casing

**Comment by OsmondJiang** [comment]
just add one item to cover, resolve on dependencies

**Comment by OsmondJiang** [comment]
#2752

**Comment by OsmondJiang** [comment]
one open question need to be discussed:

What's the resolved link in the published page? is it relative path or absolute path?

@yufeih , @herohua

**Comment by herohua** [comment]
article
 in docset: [build] relative
            [dynamic rendering] append moniker
			[frontend js] continue context? (what in context)
 out docset (uid): [build] absolute (no locale, no host), or with host
            [dynamic rendering] don't append moniker
resource
 in docset: [build] absolute with locale (no host) -> TODO: confirm with hosting why?
            [dynamic rendering] append moniker

**Comment by OsmondJiang** [comment]
i will follow up and give the update later.

**Comment by OsmondJiang** [comment]
Original | Data link type | Build | Template without moniker | Template with moniker
-- | -- | -- | -- | --
relative path | relative Path | no change | no change | append moniker query string
absolute path start with https/http | external | no change | no change | no change
absolute path start with / | absolute path | appends locale if missing | no change | no change
UID(self contains) | relative path | resolve to relative path | no change | append moniker query string
UID(XREF Query) | absolute path | resolve to absolute path, got from Xref service | no change | no change

**Comment by yufeih** [comment]
Ideally, *appends locale if missing* could be done in template just like *moniker*, because they are all for browser navigation right?

**Comment by OsmondJiang** [comment]
yes, just list the existing behaviors here, will give out ideal behaviors for docfx v3 later
