### ISSUE TITLE
Accessing specific Docfx pages only by logged users

### ISSUE THREAD

**Issue by cbenea** [dotnet/docfx#2700]
DocFX Version Used: 2.21.1.1

Template used: custom template

Steps to Reproduce:
- user login access

Expected Behavior:
Type of users: 
- Registered User – enable login so that registered users can see all public content + content behind paywall (restrict access to some pages for public, enable for logged users)

Actual Behavior:
- No login button

**Comment by superyyrrzz** [comment]
This seems not a common feature for static site generator. Some authentication logic is needed on server side, not a pure static site can achieve.

**Comment by cbenea** [comment]
Hi, 
Thank you for replying. 
Could you please suggest some Docfx compatible authentication plugin?
Or what are the options to achieve this feature? It is really needed for my site.
Thanks!

**Comment by superyyrrzz** [comment]
Sorry I don't know much about this. Maybe you need a CMS to support this, with DocFx's output as its input.

**Comment by herohua** [comment]
@cbenea I'm afraid the experience you asked for is not in the scope of DocFX. It is more like a behavior controlled by hosting service that host the documents. Where are you hosting the documents?
