### ISSUE TITLE
Error "TypedConstant is an array. Use Values property" when using attributes that have a string[] property.

### ISSUE THREAD

**Issue by RowlandBanks** [dotnet/docfx#2704]
**DocFX Version Used**: 
2.33.2 (from https://www.nuget.org/packages/docfx/2.33.2)

**Steps to Reproduce**:

1. Open the attached solution.
[DocFxTest.zip](https://github.com/dotnet/docfx/files/1958035/DocFxTest.zip)

2. Build it.
3. Note that an error occurs.

**Expected Behavior**:
The project should build successfully, and generate documentation.

**Actual Behavior**:
The project fails to build. The following error is reported:

`1>[18-04-28 06:28:56.611]Error:Error extracting metadata for 
c:/src/DocFxTest/DocFxTest/DocFxTest.csproj: TypedConstant is an array. Use Values property.`

**Notes**
The issue is caused because I have an attribute that takes a string[] as a property. 

`[BrokenAttribute(ThisPropertyBreaksIt = new string[] {"a", "b"})]`

If you removed this line, the issue would not occur.

**Comment by vicancy** [comment]
Should've fixed in https://github.com/dotnet/docfx/pull/2602 and latest release contained the fix
