### ISSUE TITLE
Custom Markdig Extensions

### ISSUE THREAD

**Issue by JeremyTCD** [dotnet/docfx#2705]
Hello, are you guys planning to allow for custom Markdig extensions? Would it be possible to expose `MarkdownPipelineBuilder` to plugins?

**Comment by JeremyTCD** [comment]
Figured out how to use custom plugins - just need to create a custom `MarkdownEngine`. Closing this issue.

**Comment by Shazwazza** [comment]
@JeremyTCD So to do this did you have to re-implement the entire `MarkdigMarkdownService`?

**Comment by JeremyTCD** [comment]
I'm not sure if there is an alternative. But if you implement `IMarkdownService` ([default markdig service](https://github.com/dotnet/docfx/blob/378b8c40d318f4350fa02bd54f698e2707fcd79f/src/Microsoft.DocAsCode.MarkdigEngine/MarkdigMarkdownService.cs) for reference), you can def use custom extensions.
