### ISSUE TITLE
Show a page enables always second tab, but first is shown

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/docfx#2706]
**DocFX Version Used**: 

2.35.2.0

**Template used**: (`default` or `statictoc` or contain custom template)

default

**Steps to Reproduce**:

1. Open the main index.md file
2. Create two tabs
3. Build
4. Serve with docfx

**Expected Behavior**:

* First tab shown (happens)
* Second tab shown when selecting it (not happening)

**Actual Behavior**:

* First tab shown
* First tab remains shown when selecting the second

**Probable Cause**

In the URL, the second tab gets automatically selected when the page is loaded without a specified tab, but the second tab isn't shown. Instead, the first tab is shown.

**Environment**

* Firefox 59.0.2, Win x64
* Edge 41.16299.371.0
* Chrome 65.0.3325.181

**Comment by vicancy** [comment]
Resolved in 2.35.4
