### ISSUE TITLE
Opening DFM preview fails

### ISSUE THREAD

**Issue by jamarw** [dotnet/docfx#2707]
Information copied from [issue](https://github.com/Microsoft/vscode-docs-authoring/issues/31) in another repo.

OS: MacOS High Sierra
VS Code Version: 1.22.2
DocFX Extension version: 0.1.3

While working with files in https://github.com/MicrosoftDocs/sandbox, when I open try to view a DFM preview the extension fails with the follow error message
```
[Child process Error]: usage: chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a [i][# [ n]]] mode|entry file ... chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...
```

I tried opening it via the command palette DocFx: Open DFM Preview

**Comment by herohua** [comment]
@928PJY as FYI

**Comment by Robo210** [comment]
It appears at least on macOS everything after /bin/sh -c needs to be inside quotes in order for it to work.

```ts
        else {
            file = '/bin/sh';
            args = ['-c', 'chmod 777 ', command];
        }
        return childProcess.spawn(file, args, options);
```

Fails
```bash
≻ /bin/sh -c chmod 777 /Users/robo210/test.txt
usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
	chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...
```

Works
```bash
≻ /bin/sh -c "chmod 777 /Users/robo210/test.txt"
```

**Comment by cecilphillip** [comment]
Any updates on this? This issue makes macOS usage pretty annoying

**Comment by Robo210** [comment]
If you fix this issue with quoting, the command it's trying to run doesn't work on macOS anyway.

```
[Child process Error]: /bin/sh: chmod 777 /Users/robo210/.vscode/extensions/ms-docfx.docfx-0.1.3/DfmHttpService/DfmHttpService.exe -w /Users/robo210/windows-driver-docs -p 62151: No such file or directory
```

**Comment by cecilphillip** [comment]
This issue is still occurring and leaves this plugin unusable for me on MacOS

**Comment by superyyrrzz** [comment]
ping @928PJY

**Comment by 928PJY** [comment]
Thanks for using the extension, but please move to the [docs-markdown](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-markdown), `Docfx` will not be supported anymore.
