### ISSUE TITLE
Capture inheritance when two classes are located in different dll

### ISSUE THREAD

**Issue by rahuldutta90** [dotnet/docfx#2714]
**DocFX Version Used**: 2.34.4.5

**Template used**: (`default` or `statictoc` or contain custom template)
"metadata": [
    {
      "src": [
        {
          "files": [
            "src/**.dll"
          ]
        }
      ],
      "dest": "api",
      "disableGitFeatures": false
    }
  ],
**Steps to Reproduce**:
This might not be an issue, I created this because I do not know whether there exists a way to do this: 

So I have two dlls A.dll, B.dll. 
I have a class ClassA in A.dll and class ClassB in B.dll. 
Class ClassB in B.dll inherits from class ClassA in A.dll.
Above I have put A.dll, B.dll, A.xml, B.xml in the src directory and run "docfx docfx_project\docfx.json"

**Expected Behavior**:
I tried generating docs using the Sandcastle help builder before using docfx and it gave me the results expected: Inheritance showed ClassB inherits from ClassA and ClassB had the methods of ClassA. So I think there is a way in docfx which I do not know.

**Actual Behavior**:
Documentation of Class CLassB does not show the inheritance relationship (It shows it inherits from System.Object) and also does not show the methods of class ClassA

**Comment by vicancy** [comment]
This is probably a bug if the inheritance is not resolved.

**Comment by rahuldutta90** [comment]
@vicancy Do we have a timeline when this will be fixed (provided this is a bug)?

**Comment by rahuldutta90** [comment]
@vicancy Do you have an idea what is the issue here and do we know when will it be fixed?

**Comment by vicancy** [comment]
@vwxyzh will take a look

**Comment by vwxyzh** [comment]
@rahuldutta90 I cannot repro the bug, can you provide a sample project or dll files?

**Comment by rahuldutta90** [comment]
Sorry, I think the problem was on my side. Two dlls were different versions and one was signed so somehow it was not able to work the dependency. Thanks for verifying it.
