### ISSUE TITLE
"&lt;" does not properly resolve into the unescaped string

### ISSUE THREAD

**Issue by Still34** [dotnet/docfx#2723]
**DocFX Version Used**: 2.35.4.0

**Template used**: custom

**Steps to Reproduce**:

1. Add `&lt;` inside an XML documentation.
2. Build and serve the docs.
3. View the member containing the said XML.

**Expected Behavior**:
`&lt;` resolves to `<`

**Actual Behavior**:
`&lt;` resolves to `&lt;`

**Comment by Still34** [comment]
This seems to be resolved in one of the recent builds, closing.

**Comment by jskeet** [comment]
Four years after being reported, this is still an issue :(
