### ISSUE TITLE
Questions around multiversioning

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/docfx#2729]
**DocFX Version Used**:  2.35.4.0

**Template used**: `default`

# My questions

1. Is there a documentation for multiversioning?
2. Is it correct that a xref across groups isn't possible?
   - When a xref across groups isn't possible, what can I do instead? Do I have to reference the produced html directly?
3. How can I set the "_gitContribute" for a group?

**Comment by superyyrrzz** [comment]
Hi @fubar-coder 
1. No, as we still not have a full support like version selector in the default template.
2. No. You are right, you can only reference the produced HTML.
3. You can add "_gitContribute" in "fileMetadata" instead of "globalMetadata", to specify different value for different file.

**Comment by fubar-coder** [comment]
Bump, to get this issue out of "stale" status.

**Comment by superyyrrzz** [comment]
Hi @fubar-coder , does my previous answers help? I know the multi-version scenario is not well supported now, but if you have no other questions, I'd suggest to close this issue and track the full feature support in #2299.

**Comment by fubar-coder** [comment]
Oh, ok. I'll track the other issue than. Thanks
