### ISSUE TITLE
Support for nested namespaces

### ISSUE THREAD

**Issue by InariTheFox** [dotnet/docfx#274]
I believe a very useful feature for DocFX is to support nested namespaces, I realize that this in itself can be quite a challenge, but having the option to turn this feature on would help to generate less confusing and a more compact TOC, especially in much larger projects.

**Comment by aienabled** [comment]
+1. And proper "tree view" for nested namespaces.
![screenshot](https://cloud.githubusercontent.com/assets/865384/15135798/af53a104-16a4-11e6-9a4a-6e6135e16b93.png)

On the screenshot the font size for entries was decreased, so `AtomicTorch.CBND.GameAPI.` fits exactly to the width of column, otherwise it wraps really weird: 
![screenshot (wrapped)](https://cloud.githubusercontent.com/assets/865384/15135863/617a6d4a-16a5-11e6-811c-919b7799be37.png)

I hope it will be addressed soon...

Regards!

**Comment by joshuaavalon** [comment]
Is there any news on this?

**Comment by vicancy** [comment]
Looks like this only relates to TOC structure. A quick work around for this is to re-format TOC.yml before `docfx build`, using a custom script.

**Comment by BernsteinA** [comment]
> Looks like this only relates to TOC structure. A quick work around for this is to re-format TOC.yml before `docfx build`, using a custom script.

try this:
```
var fs = require('fs');
var yaml = require('js-yaml');
var toc = yaml.safeLoad(fs.readFileSync('./api/toc.yml'));

var namespaces = {};

for(var i=0; i<toc.length; i++) {
    var fullnamespace = toc[i].uid;
    var splitnamespace = fullnamespace.split('.');

    var parent = namespaces;

    for(var j = 0; j < splitnamespace.length; j++) {
        var partialnamespace = splitnamespace[j];

        if(parent[partialnamespace] == undefined) {
            parent[partialnamespace] = {};
        }
        parent = parent[partialnamespace];
    }

    if(parent.items == undefined) {
        parent.items = toc[i].items;
    }
    else {
        parent.items.push(toc[i]);
    }
}

var newToc = [];

function recurse(obj, path="") {
    var items = [];
    Object.keys(obj).forEach((e, i)=>{
        if(e!="items") {
            var newPath;
            if(path=="") {
                newPath = e;
            }
            else {
                newPath = path + '.' + e;
            }
            var newObj = {uid: newPath, name: newPath, items: obj[e].items || []}
            newObj.items.push(...recurse(obj[e], newPath));
            items.push(newObj);
        }
    });
    return items;
}

var items = recurse(namespaces);

fs.writeFileSync('./api/toc.yml', yaml.safeDump(items));
```

**Comment by Onnno** [comment]
Hello BernsteinA,
thanks a lot for this script... really a pity not to have nested namespaces...
Maybe you can help me to quickly find where this script is hooked into DocFx.
I'm a little confused by the different hook/plugin options DocFx offers.
Can you tell me which DocFx howto is the right one for this??

Greetings and thanks for your script again!

**Comment by BernsteinA** [comment]
@Onnno I'm not using any of the docfx hooks. There probably is a way to do it automatically, but I just run that script manually after `docfx metadata` (and before `docfx build`)

**Comment by Onnno** [comment]
Ok, thanks :-).

**Comment by RobSmyth** [comment]
This would be an enabler feature for me. Currently the TOC is useless as our namespaces are just too long. This in turn makes the output difficult for user to use.

Raise cost of use mean acceptance never gained.

**Comment by Onnno** [comment]
I scripted the whole thing and it finally works :-).
If you push me again I'll try to find some time to publish it.
It is a little hacky approach - however, it was the only way I could do it and it works fine.
I had to modify docFx code slightly due to a bug and a small missing feature.
I also had to add scripts in some places.
I could push the project online if I clean it from stuff proprietary to the company I work for.
Vote for it if you like so it will push me to do so soon.

A quick publish should be possible.

**Comment by RobSmyth** [comment]
LOL

> If you push me again I'll try to find some time to publish it.

Push!

**Comment by Sternerson** [comment]
Go @Onnno, go @Onnno! PUSH!

**Comment by Onnno** [comment]
Ok, I talked to my boss and got the go :-)
I'll have to cleanup/prepare it for you before publish.
I think I'll get it done within this or next week.
I'll link to it from here...
You may consider it as a christmas present
though I cannot prevent you from unpacking it before christmas :-P

**Comment by aggarwalpulkit** [comment]
was this ever finished? @Onnno did you ever get to push this?

**Comment by valadas** [comment]
I use @BernsteinA script with a very small modification, in the `name` I pass `e` instead of `newPath` and now it really short. My first 3 levels in the namespace have no code (my root namespace is along the lines of MyCompany.Modules.MyModule ) so it really made it look nice now:

![image](https://user-images.githubusercontent.com/6371568/107597968-5fe08100-6bea-11eb-8eaf-66f38478f7c3.png)

**Comment by JamesHurburgh** [comment]
> I scripted the whole thing and it finally works :-).
> If you push me again I'll try to find some time to publish it.
> It is a little hacky approach - however, it was the only way I could do it and it works fine.
> I had to modify docFx code slightly due to a bug and a small missing feature.
> I also had to add scripts in some places.
> I could push the project online if I clean it from stuff proprietary to the company I work for.
> Vote for it if you like so it will push me to do so soon.
> 
> A quick publish should be possible.

Has this been published anywhere?

**Comment by wcoder** [comment]
Past, I worked on the solution via a custom template script:
WIP: https://gist.github.com/wcoder/1ffaae564978d048357c32652e3f84c7

**Comment by gumbarros** [comment]
> > Looks like this only relates to TOC structure. A quick work around for this is to re-format TOC.yml before `docfx build`, using a custom script.
> 
> try this:
> 
> ```
> var fs = require('fs');
> var yaml = require('js-yaml');
> var toc = yaml.safeLoad(fs.readFileSync('./api/toc.yml'));
> 
> var namespaces = {};
> 
> for(var i=0; i<toc.length; i++) {
>     var fullnamespace = toc[i].uid;
>     var splitnamespace = fullnamespace.split('.');
> 
>     var parent = namespaces;
> 
>     for(var j = 0; j < splitnamespace.length; j++) {
>         var partialnamespace = splitnamespace[j];
> 
>         if(parent[partialnamespace] == undefined) {
>             parent[partialnamespace] = {};
>         }
>         parent = parent[partialnamespace];
>     }
> 
>     if(parent.items == undefined) {
>         parent.items = toc[i].items;
>     }
>     else {
>         parent.items.push(toc[i]);
>     }
> }
> 
> var newToc = [];
> 
> function recurse(obj, path="") {
>     var items = [];
>     Object.keys(obj).forEach((e, i)=>{
>         if(e!="items") {
>             var newPath;
>             if(path=="") {
>                 newPath = e;
>             }
>             else {
>                 newPath = path + '.' + e;
>             }
>             var newObj = {uid: newPath, name: newPath, items: obj[e].items || []}
>             newObj.items.push(...recurse(obj[e], newPath));
>             items.push(newObj);
>         }
>     });
>     return items;
> }
> 
> var items = recurse(namespaces);
> 
> fs.writeFileSync('./api/toc.yml', yaml.safeDump(items));
> ```

How to use this script before build?

**Comment by gumbarros** [comment]
Workaround:

1. Install NodeJS
2. Create a .js file on docfx project
3. Run docfx metada

**Comment by BernsteinA** [comment]
@gumbarros 
> How to use this script before build?

I run that script manually after `docfx metadata` (and before `docfx build`)

**Comment by Arlodotexe** [comment]
## PowerShell Script
[unflatten-namespaces.ps1](https://gist.github.com/Arlodotexe/a35f87380205ebfd79cfe969c0226eeb)
I've taken the liberty to port @BernsteinA's NodeJS script to PowerShell.
No NodeJS dependencies, cross platform, and copy-paste for Azure DevOps pipelines. 

Works like a charm. I'll probably update it with some nice-to-haves, like putting folders at the top instead of the bottom and hiding the root namespace when there's only one item.
![image](https://user-images.githubusercontent.com/9384894/150049108-e5b13453-f9e5-43ed-8bc2-04f73fdd035b.png)
![image](https://user-images.githubusercontent.com/9384894/150049001-33632c29-7a1c-428a-8adf-58c8adb55254.png)

**Comment by deriglazoff** [comment]
I made an extension for toc.js, it can be used in a template, but it is raw and bugs are possible.

https://github.com/deriglazoff/documentation/blob/main/templates/darkfx/toc.extension.js
![image](https://user-images.githubusercontent.com/99898300/166110157-017d171d-3fc2-4f65-b222-889f20b69392.png)=>
![image](https://user-images.githubusercontent.com/99898300/166109990-12a807ed-db7d-4ae7-a676-fb23d19d46d8.png)

**Comment by EliseJoffreIUT** [comment]
I have the same problem ... what can i use ?

**Comment by gumbarros** [comment]
> I have the same problem ... what can i use ?

You can use like us 

nested_namespaces.js implementation
https://github.com/JJConsulting/JJMasterData/blob/main/doc/JJMasterData.Documentation/server.bat

Result
https://portal.jjconsulting.tech/jjdoc/

**Comment by EliseJoffreIUT** [comment]
I's work ! Thanks :)

**Comment by NanoBob** [comment]
I've created a pull request that will add an option for this in the docfx.json.

**Comment by MiTschMR** [comment]
How do we use it now? I went through the PR code and it adds the option "tocNamespaceStyle" to the docfx.json. However, when trying to use it, nothing happens. As for the values that can be used, I assume it is "Flattened" and "Nested", as per definition in the enum. There is no error / warning message that anything is wrong, so I don't know what I am doing wrong.

**Comment by wcoder** [comment]
@MiTschMR use `namespaceLayout` in metadata section of your docfx.json:
```json
{
  "metadata": [
    {
      "src":  ...,
      "dest": "...",
      "namespaceLayout": "nested"
    }
  ],
```

**Comment by MiTschMR** [comment]
Thanks a lot, the nesting doesn't yet work, but at least it shows it in the log that it is in experimental state. Most likely I am doing something wrong, or it may be my filter config, will have to check.

**Comment by MiTschMR** [comment]
v2.62.2 fixes the bug with the nesting not shown, no config change (except adding the "namespaceLayout" key) required. 

Thanks again @wcoder for the help with getting it to run!

**Comment by terminal-cs** [comment]
Hello. I know this issue is currently closed but this is related to it, i tried using the new option within docfx to enable this, however i get these errors:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/76945439/232587040-98233b87-8677-4a39-83fb-0841077790d8.png">

Does anyone know why this is happening? When i switch back to the default "flattened" setting it builds just fine.

**Comment by gumbarros** [comment]
> Hello. I know this issue is currently closed but this is related to it, i tried using the new option within docfx to enable this, however i get these errors: <img alt="image" width="494" src="https://user-images.githubusercontent.com/76945439/232587040-98233b87-8677-4a39-83fb-0841077790d8.png">
> 
> Does anyone know why this is happening? When i switch back to the default "flattened" setting it builds just fine.

Also happened on my machine but not on our GitHub actions pipeline. Try cleaning your cache (`_site`) and running `docfx metadata `and `docfx build --serve` again.

**Comment by terminal-cs** [comment]
> > Hello. I know this issue is currently closed but this is related to it, i tried using the new option within docfx to enable this, however i get these errors: <img alt="image" width="494" src="https://user-images.githubusercontent.com/76945439/232587040-98233b87-8677-4a39-83fb-0841077790d8.png">
> > Does anyone know why this is happening? When i switch back to the default "flattened" setting it builds just fine.
> 
> Also happened on my machine but not on our GitHub actions pipeline. Try cleaning your cache (`_site`) and running `docfx metadata `and `docfx build --serve` again.

I'm running it via github actions so it's all clean automatically. I haven't tested it locally but it should be the same

**Comment by terminal-cs** [comment]
> > Hello. I know this issue is currently closed but this is related to it, i tried using the new option within docfx to enable this, however i get these errors: <img alt="image" width="494" src="https://user-images.githubusercontent.com/76945439/232587040-98233b87-8677-4a39-83fb-0841077790d8.png">
> > Does anyone know why this is happening? When i switch back to the default "flattened" setting it builds just fine.
> 
> Also happened on my machine but not on our GitHub actions pipeline. Try cleaning your cache (`_site`) and running `docfx metadata `and `docfx build --serve` again.

I don't mean to bother, but i'm pinging you again just incase you missed this.

**Comment by gumbarros** [comment]
> > > Hello. I know this issue is currently closed but this is related to it, i tried using the new option within docfx to enable this, however i get these errors: <img alt="image" width="494" src="https://user-images.githubusercontent.com/76945439/232587040-98233b87-8677-4a39-83fb-0841077790d8.png">
> > > Does anyone know why this is happening? When i switch back to the default "flattened" setting it builds just fine.
> > 
> > Also happened on my machine but not on our GitHub actions pipeline. Try cleaning your cache (`_site`) and running `docfx metadata `and `docfx build --serve` again.
> 
> I don't mean to bother, but i'm pinging you again just incase you missed this.

Sorry, I'm on vacation , remember me again in 2 weeks

**Comment by terminal-cs** [comment]
> > > > Hello. I know this issue is currently closed but this is related to it, i tried using the new option within docfx to enable this, however i get these errors: <img alt="image" width="494" src="https://user-images.githubusercontent.com/76945439/232587040-98233b87-8677-4a39-83fb-0841077790d8.png">
> > > > Does anyone know why this is happening? When i switch back to the default "flattened" setting it builds just fine.
> > > 
> > > 
> > > Also happened on my machine but not on our GitHub actions pipeline. Try cleaning your cache (`_site`) and running `docfx metadata `and `docfx build --serve` again.
> > 
> > 
> > I don't mean to bother, but i'm pinging you again just incase you missed this.
> 
> Sorry, I'm on vacation , remember me again in 2 weeks

Reminder: 2 weeks
