### ISSUE TITLE
Method in Microsoft.DocAsCode.Build.Engine.dll

### ISSUE THREAD

**Issue by cbenea** [dotnet/docfx#2740]
**DocFX Version Used**: 2.22.2.4 

**Template used**: custom

**Steps to Reproduce**:

- I tried to disable the search option for specific pages by following steps mentioned here: https://github.com/dotnet/docfx/issues/1818 .
- The only step I couldn’t done was  to update the https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Build.Engine/PostProcessors/ExtractSearchIndex.cs method ... this is actually part of a dll that I cannot change manually (\docfx\MarketPlace\tools\docfx\Microsoft.DocAsCode.Build.Engine.dll to be more precisely) .
- Note: I have an html page that contains into the head section something like “<meta name="searchOption" content="noindex">” but when I’m doing a search it is still returning me that particular page…this should be covered by the ExtractSearchIndex.cs method.

**Expected Behavior**:  specific page with “meta name="searchOption" content="noindex" should NOT come up on search

**Actual Behavior**:  specific page with “meta name="searchOption" content="noindex" still comes up on search

**Comment by cbenea** [comment]
Any answers on this issue, please?

**Comment by superyyrrzz** [comment]
Hi @cbenea , you only need to change `docfx.json`'s `fileMatadata` section. No code change or template custom is needed.

**Comment by cbenea** [comment]
Hi @superyyrrzz, thanks for replying. I tried to change previously the docfx.json file but still not working. 
Can you kindly take a look on what I did? Maybe something it's not correct.
This is the json:
![docfxjson](https://user-images.githubusercontent.com/28356429/39860808-330dc1fa-542e-11e8-886a-e1c3736715c9.png)

And this is what I put in the file that I want **not** to come up on search

**Comment by superyyrrzz** [comment]
Sorry I cannot reproduce the error. It may be related to your custom template. Can you help confirm:
1. Does the key "obj/api/..." appear in `_site/index.json`?
2. Does `<meta name="searchOption" content="noindex">` appear in the output HTML?

**Comment by cbenea** [comment]
Hi, @superyyrrzz , 
Again thanks for trying to help. 
I'll share all the changes I did recently. I still have the issue, the specific page appears on search:

docfx.json: (I also added the page that I want to restrict from search)

![2](https://user-images.githubusercontent.com/28356429/39913480-83ab53e8-54f1-11e8-9089-15f9127c65ac.png)

head.liquid (in my custom template):
![head liquid](https://user-images.githubusercontent.com/28356429/39913539-c4e7f992-54f1-11e8-8f67-3f57a3357f77.png)

head.tmpl.partial (in my custome template):
![head partial](https://user-images.githubusercontent.com/28356429/39913565-d7594b8a-54f1-11e8-820b-9544e208da3f.png)

result: <meta name="searchOption" content="noindex"> do appear in the output HTML 

![1](https://user-images.githubusercontent.com/28356429/39913785-a54cdbba-54f2-11e8-9e0f-54cec5b601bc.png)


but: **there isn't any obj/api in _site/index.json and my page appears on search**.

Is there anything else I need to modify or maybe something wrong in above configs?
Thanks a lot!

**Comment by superyyrrzz** [comment]
Thank you for your information. The `index.json` is an object keyed with the **output** file name. I think my formal suggestion is not accurate, as `obj/api` is the **input** file name. Can you help confirm that, does the output filename, that you don't want it to be indexed, appear as a key in `index.json`? If not, it should neither appear in the search result.

I have another guess: can you try update your template to change "searchoption" to "search**O**ption"? This may be the root cause: https://github.com/dotnet/docfx/blob/c396f49963a2971954f407d3184dbf3f3ec0ab02/src/Microsoft.DocAsCode.Build.Engine/PostProcessors/ExtractSearchIndex.cs#L104

**Comment by cbenea** [comment]
Hi @superyyrrzz... I had tried before both ways with searchOption and searchoption :smile: Now I put back search**O**ption everywhere (including the metadata of the file that I don't want to be indexed), but it  is loaded in index.json and of course appears on search. :
What can I do for it in order not to be loaded in index.json? What other solution there is to solve this issue? Thank you very much again for your support!

**Comment by superyyrrzz** [comment]
If you can confirm it's `<meta name="searchOption" content="noindex">` in your output html, I cannot think of other possibilities... Can you help provide minimal reproduce steps?

**Comment by cbenea** [comment]
Hi @superyyrrzz. Me again! 
I try to reproduce the steps: 

1. Setting in docfx.json
![1](https://user-images.githubusercontent.com/28356429/40007762-59a15fae-57a6-11e8-88a1-545f77fa6736.png)

2. This is what I put in the header of the file that I dont want to be indexed
![2](https://user-images.githubusercontent.com/28356429/40007837-85052b58-57a6-11e8-8c5e-bd360e8fe01d.png)

3. This is the HTML output of my file (so it's ok):
![3](https://user-images.githubusercontent.com/28356429/40007881-9ac72626-57a6-11e8-8e8a-415fd14ef248.png)

4. After having all these configs, under _site folder, in index.json I can still find my page loaded
5. Page appears on search

Why is still showing up? What can I change? Thank you so much for your support!

**Comment by superyyrrzz** [comment]
Still cannot repro... Could you help provide a repo to reproduce it?

**Comment by cbenea** [comment]
Hi! I have **manually** deleted my page from index.json just to test the result and it's not showing me that specific page on search. Can we try to make something in order to make the page not to be loaded in index.json? Thank you, Renze Yu!

**Comment by superyyrrzz** [comment]
As you are customizing plugins, do you have change on `ExtractSearchIndex` post processor?
Back to your question, a dirty workaround is to make what you manually do as a post step after running docfx...

**Comment by cbenea** [comment]
I only have added this into docfx.json in order to make search button work. And it does:
![4](https://user-images.githubusercontent.com/28356429/40049046-58231c80-583c-11e8-903d-6f87c15eb4aa.png)
I dont know what else to do. :-) Thanks!
