### ISSUE TITLE
Navigation not rendered in IE 11 after building with 2.35

### ISSUE THREAD

**Issue by Larswa** [dotnet/docfx#2741]
**DocFX Version Used**: 
2.35.4

**Template used**: (`default` or `statictoc` or contain custom template)
Default

**Steps to Reproduce**:

Build a site with Default template with version 2.35.4

**Expected Behavior**:
Works across browsers (IE version 11 and Chrome (v66) are used here

**Actual Behavior**:
Site builds without warnings and works fine in Chrome. Browser console is showing no errors.
In IE navigation (sidebar and topbar) is missing and the console is throwing this error:

The issue could be reproduced with an empty site created by docfx init.
Old site build with 2.33 does not contain this issue.
```
SCRIPT1002: Syntax error
File: docfx.js, Line: 547, Column: 32
```

**Comment by Larswa** [comment]
A colleague of mine pointed out that Lambda expressions are not supported in IE11.

![udklip](https://user-images.githubusercontent.com/1431240/39760129-e058192e-52d4-11e8-8cee-4a5dd0c3026c.PNG)

**Comment by herohua** [comment]
@Larswa , the fix is available in the latest version of DocFX, https://github.com/dotnet/docfx/releases/tag/v2.36.1

Can you verify from your end? Thanks!

@superyyrrzz as FYI
