### ISSUE TITLE
Question, inherited properties

### ISSUE THREAD

**Issue by Riuujin** [dotnet/docfx#275]
Is it possible to show the inherited  properties on the a class.

So if I have 
```
class A{
 public string Foo {get;set;}
}

class B : A  {
 public string OtherFoo {get;set;}
}
```

The page of class B will display the `OtherFoo` property and the `Foo` property.

**Comment by sergey-vershinin** [comment]
Hi, @Riuujin! You can do this by creating a custom template. Look at [this issue] (https://github.com/dotnet/docfx/issues/276), please.

**Comment by Riuujin** [comment]
thank you
