### ISSUE TITLE
Initial content scope and dynamic scope definition

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#2755]

**Comment by OsmondJiang** [comment]
we need clearly define the content scope:
1. the initial content scope
2. the dynamic scope

**Comment by yufeih** [comment]
In docfx 3, we'd like to improve resource handling and treat *resources* like *inclusions*:

- `content` is defined as a file whose build result is an html page, everything else is `resource`
- `content` config defines a **fixed** `build scope` using `include` and `exclude` glob patterns.
- `content` referenced by links outside `build scope` **won't** be build, they cause invalid link warnings,
- `resource` referenced by links will be build or copied regardless of their location.
- `resource` embedded inside `content` like *tokens* and *code snippets* will always be embedded regardless of their location.

**Comment by OsmondJiang** [comment]
great! finally we got a agreement 👍

**Comment by yufeih** [comment]
Using the above `content` definition, TOC is a resource instead of a content because its output is a json file consumed by javascript. But because we define `build` as a transformation process, `TOC` will still be build.

**Comment by vwxyzh** [comment]
@yufeih one question:
> `content` is defined as a file whose build result is an html page, everything else is `resource`

Then if use static toc template in v2, TOC will be changed to `content`?

**Comment by yufeih** [comment]
@vwxyzh , I've updated the wording a little bit. 
- Static TOC is still treated as resource, it is embedded as an html section, not the master html content. 
- Build result is changed to rendering result, thus we only care what it intends to be, not the physical format.

**Comment by vwxyzh** [comment]
@yufeih output a model, like quiz
