### ISSUE TITLE
Document private methods/variables.

### ISSUE THREAD

**Issue by jmherrer** [dotnet/docfx#2764]
**DocFX Version Used**:  2.35.2.0

**Template used**:default

**Steps to Reproduce**: I created a simple c# class and im trying to configure docfx to document private methods.

    /// <summary>
    /// class1 docfx demo documentation.
    /// </summary>
    public class Class1
    {
        /// <summary>
        /// Count privated method.
        /// </summary>
        /// <returns>Number of members in a group.</returns>
        private int countMembers()
        {
            return 0;
        }
    }

**Expected Behavior**: 

**Actual Behavior**: I dont know if possible make it work with filters options or if it's impossible on docfx.

Thanks in advance for your help!

**Comment by vwxyzh** [comment]
@jmherrer it is not possible by now, we are hard code to generate public and protected member only.

**Comment by vwxyzh** [comment]
#2561

**Comment by superyyrrzz** [comment]
close for duplication.
