### ISSUE TITLE
Design build output format for dynamic rendering

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#2765]
This is to track the desired output file formats for dynamic rendering in v3.

- Can we change the filename, directory layout of output files
- Do we still need `.raw.json`, `.page.json` and `html` as 3 separate files
- Need to lookup build output from url for local rendering, what is the output path when locale, moniker range, branch is involved (aka, where to put these context info)

**Comment by fenxu** [comment]
We have a [documentation](https://github.com/MicrosoftDocs/openpublishing-docs/blob/master/openpublishing/docs/engdocs/open-publish-build-tools-output.md) describe the output things. @yufeih

**Comment by superyyrrzz** [comment]
> Need to lookup build output from url for local rendering, what is the output path when local, moniker range, branch is involved (aka, where to put these context info)

This [spec](https://github.com/dotnet/docfx/blob/v3/docs/designs/versioning.md#532-local-implementation) covers this. Details maybe be further discussed.

**Comment by yufeih** [comment]
We could have a dedicated output mode for compatibility with ops, preferably through an *undocumented* command line switch `--ops`

Running `docfx build --ops` produces the exact same output as ops
Running `docfx build` produces an ideal format that:
  - contains all the information to generate ops output
  - is the format our spec tests expects
  - ideally maps directly to what is stored in hosting

We can have a dedicated procedure to convert *ideal format* to *ops format* after `docfx build` when `--ops` is supplied.
