### ISSUE TITLE
Non-API Docs With DocFX

### ISSUE THREAD

**Issue by SeaDude** [dotnet/docfx#2789]
I'd like to create end-user docs similar to those found here: https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/quickstarts/create-publish-knowledge-base. What is the workflow for creating these in Markdown from VS Code (not visual studio)? 

I'd like to keep things as simple as possible. It seems all the DocFX instructions are too complex and aimed at auto-building docs from code. What are the instructions for a simpler deployment?

Thank you

**Comment by superyyrrzz** [comment]
Of course, VS is not needed. You can start from `docfx init -q` to generate a sample project, negelecting `src` folder as you needn't API docs.

You can use whatever editor to edit Markdown files. You can setup a repo, put your Markdown files on master branch, then setup a CI job to use DocFX to build them into html, and upload them to gh-phages branch. It will be hosted on GitHub.

(Copied from disqus)

**Comment by superyyrrzz** [comment]
@herohua `docfx init` has a question for user to confirm the usage. If "no" is chosen, `docfx.json` will not have the `metadata` section.
> Does the website contain API documentation from source code? (Default: Yes)

**Comment by SeaDude** [comment]
I'd like to suggest this link as a "quickstart" for non-api docs: http://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project.html. This got me started a whole lot faster once I found it. Thanks
