### ISSUE TITLE
Search result not so great on DocFX

### ISSUE THREAD

**Issue by iamnancy07** [dotnet/docfx#279]
Before Kusto onboard to DocFX,  its search results were pretty good; however, the search experience is not so good on DocFX.
https://kusto.azurewebsites.net/docs/index.html

For example, when I tried to search for “let”, it shows no result…….
I have to search for “let statement” to find what I am looking for…..

**Comment by qinezh** [comment]
It seems that the word 'let' belongs to stop words(words that are very common and are not useful in differentiating between documents) defined by lunr.js
