### ISSUE TITLE
DocFX NullReferenceException

### ISSUE THREAD

**Issue by fiddymaster** [dotnet/docfx#2791]
**DocFX Version Used**: 2.33.2 and 2.35.4

I have setup about 20 projects (c# and vb) with DocFX that all work, but i have one vb project that just does not want to work for some reason.

When i build the project i get the normal messages in log, but then there is the error line.
{"message":"Error extracting metadata for <path>/<projectname>/<projectname>.vbproj: Waarde kan niet null zijn.\r\nParameternaam: text","date_time":"2018-05-20T22:21:15.3850495Z","message_severity":"error","correlation_id":"D538821F-5704-4A19-8E78-3E5B8348F33B.2"}

It is in dutch, but if I translate it, it is a NullReference Exception.\r\nParametername: text

Do you know what this could be?

**Template used**: default
{
  "metadata": [
    {
      "src": [
        {
          "files": [
            "*.vbproj"
          ],
          "cwd": ".",
          "exclude": [
            "**/obj/**",
            "**/bin/**",
            "_site/**"
          ],
          "src": "../<projectname>"
        }
      ],
      "dest": "obj/api"
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml"
        ],
        "cwd": "obj"
      },
      {
        "files": [
          "api/*.md",
          "articles/**.md",
          "toc.yml",
          "*.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "template": [
      "default"
    ]
  }
}

**Comment by herohua** [comment]
@fiddymaster Can you provide a minimal project that can repro the issue?
