### ISSUE TITLE
Installation and usage for non-developers

### ISSUE THREAD

**Issue by SeaDude** [dotnet/docfx#2792]
**DocFX Version Used**: Latest

**Template used**: (`default` or `statictoc` or contain custom template): N/A

**Steps to Reproduce**:

1. Download latest .zip from Releases. 
2. Extract .zip
3. Click DocFX.exe

**Expected Behavior**:

The DocFX program to open, specify a folder full of .md files, browser opens set to localhost displaying a static site of all the .md files. 

**Actual Behavior**:

I get an "Open With" dialog. Choose VS Code. VS Code opens with a DocFX config file in xml (or JSON?). I'm by no means a dummy but I want to use DocFX as a static site generator not an automatic API generator. Please clearly show me how to render a folder of .md files! I can't seem to figure this out. 

Thank you

**Comment by superyyrrzz** [comment]
You can start from `docfx init -q` to see how this sample project works.

**Comment by SeaDude** [comment]
Hi @superyyrrzz . I was able to run the command (actually `./docfx init -q` using PowerShell) and it generated a nice directory of files and folders. None of the files are HTML. How do I get docfx to generate a static site for me?

**Comment by SeaDude** [comment]
I just found this http://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project.html while going through the docfx manual. This is what I was looking for.
