### ISSUE TITLE
Can I use .Net Framework Project with docfx.console to generate documentation for .Net Core Project?

### ISSUE THREAD

**Issue by mgolois** [dotnet/docfx#2797]
Can I use .Net Framework Project with docfx.console to generate documentation for .Net Core Project?

if so, I'm not sure what I am missing. docfx.console generated all the files and folder needed including docfx.json; I updated it to point to my source  code, but when I build it does not generate a "_site" folder.

**Comment by sxul** [comment]
try rollback docfx.console to version 2.35.4 or replace all `Condition="'$BuildDocFx'` to `Condition="'$(BuildDocFx)'` in packages\docfx.console.2.36.0\build\docfx.console.targets

**Comment by mgolois** [comment]
Thank you so much!

**Comment by superyyrrzz** [comment]
This issues has been fixed and new version NuGet packages(v2.36.1) has been published.
