### ISSUE TITLE
ToC build improvements

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#2807]
- [x] Reference Folder behavior is not correct
- [x] Reference no-existing files should throw warnings
~~- [ ] Navigation Bar support for community~~
- [x] Breadcrumb support for docs

cc @yufeih @herohua @superyyrrzz

**Comment by OsmondJiang** [comment]
@herohua , you are right, modify the issue.

**Comment by yufeih** [comment]
Close this issue as community navigation bar depend on template.
