### ISSUE TITLE
Disable contribution removes all buttons: 

### ISSUE THREAD

**Issue by cbenea** [dotnet/docfx#2810]
**DocFX Version Used**: 2.21.1.1

**Template used**: custom template

**Steps to Reproduce**:

1.  Added in docfx.json the following:
"globalMetadata": 
	{
      "_disableContribution": true
    },

**Expected Behavior**:
- Remove 'Improve this doc' button, keep 'Edit' and 'Share buttons'

**Actual Behavior**:
- This setting removes actually all buttons: edit, share, improve this doc etc. How can I keep only the buttons I need? Thank you!

**Comment by superyyrrzz** [comment]
Hi @cbenea , DocFX only has 'Improve this doc' button. I think you see 'Edit' and 'Share buttons' on docs.microsoft.com, but should not exist in DocFX's default template.

**Comment by thanasiskaragiorgisrc** [comment]
Hi @superyyrrzz 

Is there a way to hide the "Improve this doc" but keep displaying the "View source" button?

**Comment by superyyrrzz** [comment]
@thanasiskaragiorgisrc No existing switch supporting this. `_disableContribution` will disable both button: https://github.com/dotnet/docfx/blob/0341b6c0e4ec999da8cef6ac50ab720160d09c35/src/docfx.website.themes/default/partials/affix.tmpl.partial#L5-L20

You can contributor another switch to docfx, or customize your own template to achieve it.

**Comment by thanasiskaragiorgisrc** [comment]
Happy to do so.
Should I go for a positive metadata property, ie. `enableViewSource` or stick to the negative ones?

Let's say that I add the following ones:

|    Attribute                  | Default Value |
|-------------------------|----------------|
| `_disableContribution` |        false       |
| `_enableViewSource`   |        true        |
| `_enableImproveDoc`   |       true        |

If `_disableContribution` is present global metadata, it trumps all.
If any of the others is present, the respective value will be used.

How does that sound @superyyrrzz ?

**Comment by superyyrrzz** [comment]
@thanasiskaragiorgisrc I'd prefer keep using `_disableXXX` ones. This is more consistent with other existing switches: https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#322-reserved-metadata
