### ISSUE TITLE
generate required metadata

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#2813]
|    Metadata      |   Assignee  |    Comment    |
|---------------   |-------------|---------------|
|_op_allContributorsStr | | #2940  |
|~_op_canonicalUrl~ | | Generated by template |
|~_op_canonicalUrlPrefix~ | | Input |
|~_op_displayDate~ | | Generated by template |
|_op_feedback_github_repo | | Template |
|_op_feedback_product_url | | Template |
|_op_feedback_system | | Template |
| ~_op_gitCommitHistory~ | @superyyrrzz | for intermediate use
| ~_op_gitContributionCommitHistory~ | @superyyrrzz | for intermediate use
|_op_gitContributorInformation | @superyyrrzz | #2912 
|_op_ogTitle | | **Investigate** |
|_op_openToPublicContributors | @superyyrrzz
|_op_pdfUrlPrefixTemplate | | Used by Pdf tool |
|_op_rawTitle | @928PJY |
|_op_searchScope | @fenxu | **Investigate** where add \_op_ prefix |
|_op_wordCount | @fenxu | **Investigate** where add \_op_ prefix |
| author           | @superyyrrzz| #2951 handle user profile cache #2812 |
| ~canonical_url~    | @928PJY  | Generated by template |
| content_git_url  | @superyyrrzz| #2957
| depot_name       | @928PJY |
| document_id      | | #2821 |
| document_version_independent_id | | #2821 |
| gitcommit        | @superyyrrzz| #2876 #2944 |
| is_dynamic_rendering | @928PJY |
| layout           | @928PJY |
| locale           | @928PJY |
| open_to_public_contributors | @superyyrrzz  | #2948
| original_content_git_url | @superyyrrzz | #2876 |
| ~page_type~        | @928PJY  | Generated by template | 
| pdf_url_template | | Generate by Pdf tool |
| redirect_document_id | | #2822 | 
| redirect_url     | | #2822 | 
| search.ms_docsetname | @fenxu | **Investigate** |
| search.ms_product | @fenxu | **Investigate** |
| search.ms_sitename | @fenxu | **Investigate** |
| site_name        | @928PJY |
| ~toc_asset_id~     | | Can be removed |
| toc_rel          | @928PJY |
| updated_at       | @superyyrrzz | #2962 #2969
| version          | @928PJY |
| word_count       | @928PJY  |

**Comment by OsmondJiang** [comment]
#2882
