### ISSUE TITLE
Upgrade msdn external reference package to xrefmap format

### ISSUE THREAD

**Issue by chenkennt** [dotnet/docfx#282]
1. Support zip format for xrefmap
2. Upgrade msdn external reference package to new format
3. Support absolute path in xrefmap
4. Support download xrefmap file

**Comment by vwxyzh** [comment]
status:

1. Support zip format for xrefmap:
    *format defined, read/write completed, query by `uid` not ready.*
2. Upgrade msdn external reference package to new format:
    *pending.*
3. Support absolute path in xrefmap:
    *ready.*
4. Support download xrefmap file:
    *pending.*

**Comment by chenkennt** [comment]
Update MSDN package is not done yet, create another issue to track
