### ISSUE TITLE
Plugins not being detected

### ISSUE THREAD

**Issue by rjgotten** [dotnet/docfx#2837]
**DocFX Version Used**:
2.36.1

**Template used**: (`default` or `statictoc` or contain custom template)
`default` extended with custom template containing plugins.

**Steps to Reproduce**:
1. Set up `docfx.json` with a cascade of two templates; `default` and a template holding custom plugins.
2. Implement the `CustomBlockCodeRendererPart` from the [tutorials](https://dotnet.github.io/docfx/tutorial/howto_customize_docfx_flavored_markdown.html):
    - Build with Visual Studio 2017, using .NET 4.6.1 as target
    - Using version 1.0.31 of the `Microsoft.Composition` package
    - Using version 2.36.1 of the `Microsoft.DocAsCode.Dfm` package
3. Write a ` ```cs` code block somewhere in the documentation, following the tutorial.
4. Execute `docfx` to build the documentation.

**Expected Behavior**:
The custom plugin is used to render the code block, demonstrating that the plugin works correctly.

**Actual Behavior**:
The custom plugin is **not** used to render the code block.

The plugins inside the DLL are not being detected by DocFX at all. It always reports similar to the following:
```[18-06-04 02:34:01.438]Info:[ImportPlugins]Searching custom plugins in directory D:\docfx\plugins_11u0qld0.5m1\plugins...
[18-06-04 02:34:01.757]Info:6 plug-in(s) loaded.
```

Whether the plugins DLL is present within the template or not, it always shows 6 plug-in(s) loaded. (I assume those are part of the `default` template.)

The template folder itself _is_ being found and used. And using file-system activity monitoring tools I can verify that DocFX is infact copying the DLL file over to the temporary folder structure below its root folder. DocFX just ends up not finding any usable plugins inside of the DLL, it seems.

**Comment by superyyrrzz** [comment]
Do you put DLLs inside `custom_template_folder/plugins/`?

**Comment by rjgotten** [comment]
@superyyrrzz 
Yes.

And if I enable verbose logging (`docfx build --logLevel verbose`) then I can see that the DLL in question actually _is_ being scanned for plugins, but DocFX simply finds none.

**Comment by zhuyadong** [comment]
@superyyrrzz 
Make sure 
```json
"markdownEngineName":"markdig"
```
is not in your docfx.json . I have same problem here, and it resolved if I delete "markdownEngineName" from docfx.json.

**Comment by rjgotten** [comment]
@zhuyadong 
Oh wow. Yep. That actually causes the plugin to work.
Well; that will work around the issue for the short term.


Funny thing is: if I look at the log output; it still claims only 6 plug-ins were loaded. Whether the plugin DLL is present in the used template or not.

So, it looks like there are a few different bugs happening here simultaneously.

One being that `IDfmCustomizedRendererPartProvider` plugins don't work with the markdig engine.
And one that these plugins are not counted in the number of loaded plugins reported in the log output as `Info: <n> plug-in(s) loaded.`

**Comment by herohua** [comment]
@qinezh @928PJY

**Comment by qinezh** [comment]
There're two markdown engines in DocFX: dfm engine and markdig engine currently. And `IDfmCustomizedRendererPartProvider` is designed to customize dfm engine, so it doesn't work with the markdig engine.

**Comment by fleed** [comment]
@qinezh is there a way to customize the markdig engine with a plugin?

**Comment by qinezh** [comment]
Currently it's not supported, however, you could add an issue as a feature request. cc @herohua
