### ISSUE TITLE
YAML and JSON validation

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#2838]
Some invalid inputs to consider:
- [x] If a dict has duplicate keys: log warning, continue/fail?
  - log error to output and continue
    - [x] YAML
    - ~~Json~~
- [x] If an array contains null element: log warning, remove null element
  - [x] YAML
  - [x] Json
- ~~If a key is not found or type mismatch in c# model, log warning~~

@OsmondJiang @yufeih

**Comment by yufeih** [comment]
We could warning and de-null all null inputs, yaml parse result should never contain null value.

**Comment by yufeih** [comment]
To encourage the use of non-null reference, the strategy here is:

- On **de-serialization**, remove nulls from arrays and property values: 
  `[null, 1, null]` --> `[1]`, `{a: null}` --> `{}`
- Models properties are initialized with a non-null default value
- On **serialization**, do not output empty strings/arrays/objects to reduce size
  `{a: ""}` --> `{}`, `{a: []}` --> `{}`, `{a: {}} ` --> `{}`

**Comment by yufeih** [comment]
[yaml spec](http://yaml.org/spec/1.2/spec.html) does allow duplicated keys, if we follow that, it should be a warning and de-serialization should continue.

But I **DO** want to support just the [strict subset of YAML](http://hitchdev.com/strictyaml/), which we already did like dropping object keys, multiple documents, custom tags... One thing we support now but is cut in that spec is anchors and references.

If we use strict yaml, we should just error out on duplicated keys.
