### ISSUE TITLE
DocFX styling hides content

### ISSUE THREAD

**Issue by Powerhelmsman** [dotnet/docfx#2842]
Original GitHub issue: dotnet/docs#5779
From @florinciubotariu:
The website that DocFX is serving is not showing the content correctly.
For example, if I navigate to:
http://localhost:8080/standard/choosing-core-framework-server.html
the following page is displayed.
If I delete the <div> that is having the container class, then the content is displayed correctly, as you can see here.

**Comment by superyyrrzz** [comment]
dotnet/docs need some private template, which is not compatible with DocFX default template. This extension might help if you are finding some tools to improve authoring experience: https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack
