### ISSUE TITLE
Where is the emphasis/italics guidance?

### ISSUE THREAD

**Issue by guardrex** [dotnet/docfx#2843]
Hello,

Can you point me to the emphasis/italics documentation guidance? Specifically, I'd like to confirm that the underscore (`_`) has the same effect as the asterisk (`*`) for italic text rendering. I don't see any mention of either in your docs, but I'm probably just looking in the wrong spot. Thanks.

**Comment by vwxyzh** [comment]
@guardrex you can find markdown documentation in [Common Mark](https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis).
