### ISSUE TITLE
Search not working if the title contains a dot "."

### ISSUE THREAD

**Issue by fleed** [dotnet/docfx#2877]
**DocFX Version Used**: 2.33.2

**Template used**: `default`

**Steps to Reproduce**:

1. Create a document that contains a dot "." in the title (e.g.: `.NET repositories`)
2. Type ".net" in the search form

**Expected Behavior**:

The `.NET repositories` document appears in the search results

**Actual Behavior**:

No results found

**Comment by qinezh** [comment]
Sorry for the late response. DocFX uses lunr.js for full-text search, and lunr will do stemming step while building the index. By default, lunr uses the algorithm-based stemming way, so `.NET` will be `net` in lunr's index. We could also use dictionary-based stemming, but it requires a complete dictionary, which must be maintained and large in size. 

cc @herohua
