### ISSUE TITLE
Autocollapse don't collapse

### ISSUE THREAD

**Issue by Jedarc** [dotnet/docfx#2878]
**DocFX Version Used**:  2.36.1

**Template used**: `default`

**Steps to Reproduce**:

1. `git clone https://github.com/dotnet/docs.git`
2. `cd docs`
3. `docfx -t default --serve`

**Expected Behavior**:
I would like to see the content of the page and have the menu available for navigation.

![image](https://user-images.githubusercontent.com/10923617/41293437-a083c40c-6e2b-11e8-80d8-d66b3eba6732.png)

**Actual Behavior**:
The `#autocollapse` div covers the entire page, making it impossible to see the content.
![image](https://user-images.githubusercontent.com/10923617/41293481-bd3a27d0-6e2b-11e8-9d9f-5373638a36ea.png)

I noticed that in the `docfx.js` file the `relHref` variable is set to `undefined` during execution, and it does not execute the `renderSearchBox()` function, and consequently does not execute the `autoCollapse()` function.

![image](https://user-images.githubusercontent.com/10923617/41293621-30f79072-6e2c-11e8-9ed1-3466e2132e99.png)

**Comment by herohua** [comment]
@qinenzh Do you know what `relHref` means here and how to fix the `undefined` issue?

**Comment by herohua** [comment]
The `#autocollapse` mentioned above is designed for search box, not for TOC navigation.

We did not envision such large TOC when working on default template. This is a new feature request to allow some kind of navigation in large TOC.

**Comment by vsi-hvarma** [comment]
Added a PR to fix this. It's a simple JS update
