### ISSUE TITLE
Stackoverflow Exception when processing ManagedReferenceDocuments

### ISSUE THREAD

**Issue by josullivan** [dotnet/docfx#289]
Unable to build the doc site for a single project even though YAML files are being generated

Minimal repro steps:
1. Download, install and initialize Docfx 1.8 (but also happens with 1.7.x)
2. Point at single project in local Git repo in docfx.json
3. Run docfx spagent/docfx.json --serve

Expected to see the documentation site available at http://localhost:8080

Instead see a Stackoverflow Exception when building:
Info: [Build Document.TocDocumentProcessor]Building 3 file(s) in TocDocumentProcessor(BuildTocDocument)...
Info: [Build Document.ManagedReferenceDocumentProcessor]Building 134 file(s) in ManagedReferenceDocumentProcessor(BuildM
anagedReferenceDocument=>ApplyOverwriteDocumentForMref=>FillReferenceInformation)...

Process is terminated due to StackOverflowException in mscorlib.

A significant number of YAML docs are created in the api folder but no html docs generated

**Comment by vicancy** [comment]
Any chance for us to take a look at a repo that can repro the issue?

**Comment by josullivan** [comment]
Took us a while to get minimal repro as below where circular <seealso> references cause this StackOverflowException.
`    
   
      public class Program
      {
            static void Main(string[] args)
           {

           }

           /// <seealso cref="Program.B"/>
           public int A()
           {
              return 0;
           }

           /// <seealso cref="Program.A"/>
           public int B()
           {
               return 0;
           }
      }
`

**Comment by superyyrrzz** [comment]
@josullivan It has been fixed in DocFX 1.9.
