### ISSUE TITLE
Attribute with passed in property value : DocfxException when type of value cannot be resolved

### ISSUE THREAD

**Issue by JorisSpriet** [dotnet/docfx#2894]
**DocFX Version Used**:  2.36.2.0

**Template used**: default

**Steps to Reproduce**:

1. compile the solution - it will fail
2. run docfx
it fails with error: Unable to generate spec reference for !:

Source in zip in att. - solely for demonstrating/reproducing
In reality compilation of source to binaries is on build server and this succeeds.

The running of docfx is done separately (it takes >1.5 hours to complete) and during this
* AttributesModel is available only as binary
* DemoModel is available only in source form
* no source or binary where SomeEnum is defined (of course it exists)
So we run docfx separately from the compilation of the source.

**Expected Behavior**:
Succeed OR produce meaningful error.  Now I had to resolve to running docfx in debug to diagnose the cause.

**Actual Behavior**:
It fails and the error message does not help.

[DocFXProblem.zip](https://github.com/dotnet/docfx/files/2111261/DocFXProblem.zip)

**Comment by vwxyzh** [comment]
@TianqiZhang

**Comment by TianqiZhang** [comment]
@JorisSpriet I'll investigate this issue, thanks for reporting it. In the meanwhile, as a workaround, could you please try [version 2.35](https://github.com/dotnet/docfx/releases/tag/v2.35), which does not throw this error?

**Comment by JorisSpriet** [comment]
Actually got this error (by this I mean the message) while using 2.35; so I moved to 2.36, got the same message, and then looked into the code to find where the exception was thrown.

So I don't know if in 2.35 it is the same exception, but nevertheless it fails just the same.

Meanwhile, I could change the source code being documented - it turned out the attribute was superfluous - and so the problem kind of "went away".
