### ISSUE TITLE
Set svg class for logo only if logo is an SVG file

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#2899]
**DocFX Version Used**:  

2.36.1

**Template used**: (`default` or `statictoc` or contain custom template)

default

**Steps to Reproduce**:

1. Set `_appLogoPath` to a PNG file
2.  Open rendered site in Firefox (60.0.2)

**Expected Behavior**:

If logo is an PNG the SVG rendering code should not be executed.

**Actual Behavior**:

The `svg` class [is applied to the logo img tag](https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/partials/logo.tmpl.partial#L4), independently of the actual file extension, triggering the [JavaScript code for SVG logo handling](https://github.com/dotnet/docfx/blob/d84b56fda40063a7d816a8be8d4c8af327e32225/src/docfx.website.themes/default/styles/docfx.js#L696-L722), resulting in a `XML Parsing Error: not well-formed` error in the console in Firefox (60.0.2).

**Comment by yufeih** [comment]
javascript code for SVG logo handling is dropped.
