### ISSUE TITLE
Feature request: breadcrumbs in PDF header/footer

### ISSUE THREAD

**Issue by sandersaares** [dotnet/docfx#2907]
I would like to see the navigation breadcrumbs in my PDF output header (e.g. `Foo -> Bar`), just like it shows them in the website variant. Right now PDFs are a bit hard to navigate if they are structured after the hierarchical website. Breadcrumbs would preserve some context and help with understandability.

**Comment by herohua** [comment]
@sandersaares

The built PDF has TOC to facilitate navigation. The breadcrumb is basically another mapping of the TOC. Would you agree that the TOC in PDF is good enough for navigation?

**Comment by sandersaares** [comment]
I do not consider the TOC to be sufficient, no. I would like to have breadcrumbs in the header of each page to ensure that my readers have sufficient context to easily navigate the document.

**Comment by icnocop** [comment]
Another way to navigate the PDF is by using the outline (bookmarks) generated in the PDF.
It's based on the TOC, hierarchical, and can be displayed without having to navigate to the top of the PDF.
The user can also select to find the bookmark corresponding to the current page.

**Comment by icnocop** [comment]
According to https://wkhtmltopdf.org/usage/wkhtmltopdf.txt, wkhtmltopdf supports the following relevant variables in the header and footer:
`[section]` `[subsection]`

If you specify those values in one of the header/footer command line options and put it in the `additionalArguments` property in docfx.json, does that resolve the issue?

There's also an undocumented variable `[subsubsection]`.

**Comment by yufeih** [comment]
#9343
