### ISSUE TITLE
VSCode plugin not working: command 'DocFX.showDfmPreview' not found

### ISSUE THREAD

**Issue by fancyoung** [dotnet/docfx#2909]
**VSCode Plugin DocFX Version**: 0.1.3
**VSCode Version**: 1.24.1
**System**: Ubuntu 18.04

1. Open a *.md file
2. Press Ctrl + Shift + q
3. Preview not show, and warrning with popup `command 'DocFX.showDfmPreview' not found`
4. Preview to side also not working with error `command 'DocFX.showDfmPreviewToSide' not found`

**Comment by 928PJY** [comment]
please move to [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack)
