### ISSUE TITLE
Tabs not working as expected in Internet Explorer 11

### ISSUE THREAD

**Issue by ThomasMPorter** [dotnet/docfx#2910]
**DocFX Version Used**: 2.36.2.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Open example [here](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a#example) in Internet Explorer 11
2. Click the second tab on any of the examples

**Expected Behavior**:
Second tab's content is displayed

**Actual Behavior**:
Page scrolls to another part of the page, but does not show second tab's content

**Comment by herohua** [comment]
@ThomasMPorter

Thanks for raising this issue. We are aware that the `default` and `statictoc` template do not support tabbed syntax yet. We will put this into backlog.

**Comment by superyyrrzz** [comment]
Looks like a bug. Default template already supports this.

**Comment by xxcuratorxx** [comment]
Any Update here? We need to add Tabs in our Docs but cannot due to this bug

**Comment by inmy4head** [comment]
I'm facing the same Problem with IE11. Is there a bug-fix or workaround available yet?

**Comment by yufeih** [comment]
IE11 has reached end of support.
