### ISSUE TITLE
Can't resolve autolink, throw file-not-found error

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#2921]
Below content will throw **file-not-found** -> Cannot find file 'http://*.windowsupdate.microsoft.com' relative to 'xxxx'
```
#### Restrict Access to Specific Domains 
If your organization does not allow the ports and protocols to be open to all addresses on the firewall between the active software update point and the Internet, you can restrict access to the following domains, so that WSUS and Automatic Updates can communicate with Microsoft Update: 

- http://windowsupdate.microsoft.com

- http://*.windowsupdate.microsoft.com 

- https://*.windowsupdate.microsoft.com 

- http://*.update.microsoft.com 

- https://*.update.microsoft.com 
```

**Comment by yufeih** [comment]
@yishengjin1413 @qinezh 

Markdig treats `http://*.windowsupdate.microsoft.com` as a valid URL and turn it into an autolink. This is wrong. It should be treated as plain text like DFM and GitHub.

Example article: https://docs.microsoft.com/en-us/sccm/sum/plan-design/plan-for-software-updates

**Comment by yishengjin1413** [comment]
This is a know issue for markdig. Autolink in markdig followed the rule in the github spec here: https://github.github.com/gfm/#autolinks-extension .  But the spec is not updated for a long time, I will try to find the spec owner and let him update the spec first.

**Comment by yufeih** [comment]
meanwhile, I can hide the warning by relax URL detection in our end.
