### ISSUE TITLE
Unable to stop/quit docfx server to free up port

### ISSUE THREAD

**Issue by tnavda** [dotnet/docfx#2945]
**DocFX Version Used**: 
docfx 2.36.2.0
**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1.  Run docfx server .\_site -p 9090 in Package Manager Console
2. Ctrl+X or Ctrl+Z
3. 

**Expected Behavior**:

You can stop docfx web server

**Actual Behavior**:

You can't stop the docfx web server.  Ctrl+X nor Ctrl+Z, stop it from inside Package Manager Console .  It's running with PID 4, and there is no discernible process to kill or service to stop.  Closing VS doesn't free up the port and there is no documentation about stopping it.  Looks like a full restart is required to free up the port.

**Comment by tnavda** [comment]
Looks like I overlooked it, but you must manually kill docfx executable from task manager.  Seems like there should be an easier way?

**Comment by superyyrrzz** [comment]
try `Ctrl`+`C`

**Comment by tnavda** [comment]
ctrl+c doesn't work

The best method is to click the "Stop" button in the Package Manager toolbar.

**Comment by superyyrrzz** [comment]
@tnavda Thank you for the feedback. Just find you are running it in Package Manager Console...
