### ISSUE TITLE
Setup impact test for legacy output

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#2949]
- [x] delete old comparing test branch
- [ ] ~~comparing ideal output, not only legacy.~~ (#3059)
- [x] integration with docfx CD
  - merge PR to v3
  - impact test run and create impact change PR
  - review the PR and merge into master
  - trigger docfx CD

**Comment by yufeih** [comment]
Run impact again _azure_ and see how fast is it. If it is too slow (> 2~5 min), we may want to rewrite it in c# (parallel) ?

**Comment by OsmondJiang** [comment]
@yufeih, yes, if the impact script is too slow, we may want to improve it, we can check that when on-board the azure repo
