### ISSUE TITLE
DXN project does not include external packages documentation

### ISSUE THREAD

**Issue by ivaylokenov** [dotnet/docfx#296]
### Title
I try to build documentation API from source code in a DNX based project and all external packages links produce warnings.

### Minimal repro steps
In the `docfx.json` I put the following:

```json
"files": [
    "src/**/project.json"
],
```

And in the `project.json` file from the source project, I have the following dependencies:

```json
"dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Session": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.TestHost": "1.0.0-rc2-*"
  },
```

### Expected result
For this documentation summary (using directives are correct and `BadRequestResult` is visible and recognised in the code)

```xml
/// <typeparam name="THttpBadRequestResult">
/// Type of bad request result - <see cref="BadRequestResult"/>
/// or <see cref="BadRequestObjectResult"/>.
/// </typeparam>
```

I expect either generated links or at least plain text like 
`Type of bad request result - BadRequestResult or BadRequestObjectResult.`

### Actual result
I receive empty strings in the final output.
`Type of bad request result - or.`

Any suggestions how can I overcome this or what I need to do in order to include external types from the referenced dependencies? I could not find anything in the docfx documentation site.

**Comment by qinezh** [comment]
Hi @ivaylokenov , can you try [this prerelease version of docfx](https://github.com/dotnet/docfx/releases/tag/1.9.0-alpha-0091-g1c1b291)?

BTW, you need to restore the project dependent package before running docfx.

**Comment by ivaylokenov** [comment]
@qinezh I updated the project to .NET CLI and with the provided prerelease version I am now receiving correct text and not empty strings. There are no links generated but I guess this is normal. I am closing the issue now. 

Do you plan to generate links from external documentation not just plain text?

**Comment by qinezh** [comment]
It depends on ASP NET Core team, we need the xref map generated with docfx in their code...
