### ISSUE TITLE
Release notes 2.37

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#2983]
The Release Notes on the [Release Page](https://github.com/dotnet/docfx/releases/tag/v2.37) and in [RELEASENOTE.md](https://github.com/dotnet/docfx/blob/dev/RELEASENOTE.md) are missing for 2.37. 

It would be nice to have release notes to know what has changed in this version.

Also in the RELEASENOTE.md 2.37 is marked as pre-release while on the release page it is marked as latest release.

**Comment by superyyrrzz** [comment]
Thanks for reminding :) Now it's updated to 2.38 prerelease.

Just added some markdown engine features in 2.37 to support docs.ms.com, without major feature or bug fixes for external users. It may be more clear to increase the patch version.
