### ISSUE TITLE
support restore lock file

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#2987]
- [x]  support to restore to different place
- [x]  avoid site effects caused by another repo
- [x]  clean up unused restore work trees
- [x] clarify using `RestoreLockFile` and `FileMutex`
- [ ]  ~pass auth token instead of using git auth manager~

cc @fenxu  @superyyrrzz @yufeih

**Comment by fenxu** [comment]
@OsmondJiang One proposal way is like current server logic: copy dependent repositories to repository root and pull there.

**Comment by yufeih** [comment]
After enabling parallel e2e, restore may fail due to parallel execution: https://travis-ci.org/dotnet/docfx/builds/399431858?utm_source=github_status&utm_medium=notification

**Comment by OsmondJiang** [comment]
@yufeih , i will take a look

**Comment by OsmondJiang** [comment]
@yufeih , i can reproduce it locally, seems FileStream's Share option doesn't work on linux, i will try more and update later.

**Comment by OsmondJiang** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=38201

**Comment by OsmondJiang** [comment]
http://0pointer.de/blog/projects/locking.html

**Comment by OsmondJiang** [comment]
@fenxu , now docfx v3 support restore to a different place and using work trees to avoid noisy neighbor issue. You can set "DOCFX_APPDATA_PATH" environment to reset the restore root dir. 

The document will be added later.
