### ISSUE TITLE
FSharp tests are failing

### ISSUE THREAD

**Issue by herohua** [dotnet/docfx#2989]
Unit tests under "Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests" are failing under test explorer.

System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\current\docfx\test\Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests\bin\Debug\net461\TestData\NetCoreProject\obj\NetCoreProject.fsproj.proj-info.targets'.

It seems like the output folder was not generated during the test run.
And CI build did not run these tests.

**Comment by superyyrrzz** [comment]
It works now on my machine.
