### ISSUE TITLE
The TOC for PDF does not allow as many levels as the default website TOC

### ISSUE THREAD

**Issue by MrBenMyster** [dotnet/docfx#3015]
**DocFX Version Used**: 2.36.2

**Template used**: `pdf.default`

**Steps to Reproduce**:

1. Specify a toc.yml which loads a markdown file that has ATX headers at level three or greater, for example:
The toc.yml:
```
  - name: Articles
    href: ../Articles/toc.md
    topicHref: ../Articles/toc.md
```

The toc.md:
```
# Operations
## Authoring
### [How to Author a Resource](Author_a_resource.md)
```
2. Using default docfx.json settings for generating a pdf, build the docfx, which outputs a PDF file.

**Expected Behavior**:

1. The PDF Table of Contents should allow up to H6 using the ATX specification (https://daringfireball.net/projects/markdown/syntax)

**Actual Behavior**:
The `How to Author a Resource` markdown document was not displayed in the PDF TOC. 

**Notes**
I was able to get this scenario functional by modifying the toc.html.tmpl file and loading a custom template based on pdf.default.

**Comment by herohua** [comment]
I guess we don't have such limitations on TOC level. @partychen , can you confirm?

**Comment by icnocop** [comment]
How was `toc.html.tmpl` file modified to work-around this issue?

**Comment by MrBenMyster** [comment]
By inserting the following:
```            
<a class="normal slidedown" href="javascript:void(0)">{{ name }}</a> {{/ href }} {{# items.0 }}
<ul class="tocLevel{{level}}">
      {{/ items.0 }} {{#items}}
<li>
      {{# href }}
      <a class="normal" href="{{ href }}">{{ name }}</a> {{/ href }} {{^ href }}
```

See original on left, modified toc.html.tmpl on right:
![snip_20190403140903](https://user-images.githubusercontent.com/16561584/55509884-3df33c00-561a-11e9-8ec4-618103c2618e.png)

**Comment by superyyrrzz** [comment]
Or add a partial template to include recursively. Similar to https://github.com/dotnet/docfx/blob/27f06c5bbbf21aa8f1fcf7b11822221136a486e0/src/docfx.website.themes/default/partials/li.tmpl.partial#L17
