### ISSUE TITLE
Git Not Found shouldn't be thrown when the cwd is not found

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3028]
as title.

@yufeih

**Comment by yufeih** [comment]
Did you have a repro? We should assert `cwd` exists when calling `GitUtility.Execute<T>`. Besides cwd was accidentally removed by other processes, is there a case where we cannot have this assumption?

**Comment by OsmondJiang** [comment]
There are many cases that the cwd may not exist, even we had a bug that the cwd is not created before executing git command, we shouldn't tell user the git is not install, please install git...
