### ISSUE TITLE
Multiple language site with DocFX?

### ISSUE THREAD

**Issue by anrenz** [dotnet/docfx#3033]
**DocFX Version Used**: 2.24.0.892

**Template used**: custom template adapted to German at the moment

**Expected Behavior**: I would like to create a multiple language site with conceptual articles using DocFX. Ideally the user can go to other topics like here Pull requests, Issues, Marketplace and Explore and the site adapts automatically not only the articles in the proper language, but also all other texts written on the site. As I am relatively new in the field, any kind of suggestion is helpful. I am sure two templates are needed to generate it but would like an elegant solution.

**Actual Behavior**: At the moment we have a site in German only. For this purpose I adapted the template to german (Search to Suche etc).

**Comment by OsmondJiang** [comment]
closed as it's duplicated with #803, and now it's implemented in V3, @anrenz
