### ISSUE TITLE
setup `azure-docs-pr` for impact testing

### ISSUE THREAD

**Issue by herohua** [dotnet/docfx#3047]

**Comment by 928PJY** [comment]
1. Missing metadata:
    1. - [ ] _op_brand
    2. - [ ] _op_documentIdPathDepotMapping
    3. - [ ] _op_pdfUrlPrefixTemplate
    4. - [ ] _op_searchScope
    5. - [ ] breadcrumb_path
    6. - [ ] contributors_to_exclude
    7. - [ ] pdf_url_template
2. Error metadata:
    1. - [ ] _op_canonicalUrl
    2. - [ ] _op_canonicalUrlPrefix
    3. - [ ] _op_feedback_github_repo
    4. - [ ] _op_feedback_product_url
    5. - [ ] _op_feedback_system
    6. - [ ] _op_openToPublicContributors
    7. - [ ] canonical_url
    8. - [ ] document_version_independent_id
