### ISSUE TITLE
incremental publish improvement: keep HASH unchanged between branches

### ISSUE THREAD

**Issue by herohua** [dotnet/docfx#3049]
- ~~[ ] docfx put repo/branch to manifest~~
- ~~[x] docfx outputs git url templates~~
- ~~[ ] build service uploads document metadata~~
- ~~[ ] hosting exposes these metadata to template~~
- ~~[ ] template expand git url templates~~

**Comment by yufeih** [comment]
This seems to be [solved in v2](https://github.com/dotnet/docfx/commit/89fae9485cd856bcf9c8e7d4a34b04e091b5a7ea) using the `DOCFX_SOURCE_BRANCH_NAME` environment variable.

@fenxu , can we set an environment variable like `DOCFX_SOURCE_BRANCH_NAME` to the target branch name during PR build?

**Comment by fenxu** [comment]
@yufeih I prefer to use a command parameter other than environment variable.

**Comment by fenxu** [comment]
Besides, it should be a full source repository url. Branch name is not enough.

**Comment by yufeih** [comment]
Here is the solution we came up with from offline discussion:
- move branch, repo from output JSON file to manifest
- publish every document with branch, repo embeded as DHS document metadata
- publish every output JSON file using incremental publish
- turn editUrl, gitContentUrl, gitCommitUrl into string template

**Comment by yufeih** [comment]
This needs further discussion. right now I'm putting repo/branch back to git urls, but does not allow overrides. This means for PR, the edit link always points to the PR target branch.

**Comment by yufeih** [comment]
If we suppress loading git commits on review, `update_at` will fallback to file LastModified date which is un-deterministic.

**Comment by OsmondJiang** [comment]
@yufeih , do we need this issue anymore?

**Comment by yufeih** [comment]
yes

**Comment by yufeih** [comment]
After #3780, we could leverage the input change list to filter determine edit button target repo.

**Comment by yufeih** [comment]
Edit button is tracked by #3791 , all the other outputs produces consistent hash, so close this one.
