### ISSUE TITLE
port SDP to v3

### ISSUE THREAD

**Issue by herohua** [dotnet/docfx#3050]
- [x] deserialize yaml/json into c# model with error handling
- [x] generate page model
- [x] model `LandingData`
- [x] ~~run jint and mustache in legacy mode~~
- [x] CI to generate JSON schema from c# model
- [x] support data annotation
- [x] support markdown, inline markdown
- [ ] support xref/uid
- [x] potential merge with markdown pipeline
- [ ] support external xref
- [x] filter out files referenced by config
- [x] export description to json schema
- [x] support JsonExtensionData and JToken in create json schema
- [x] determine output type (page or json) based on DataSchema or PageSchema ~~whether template (cshtml) exists~~

**Comment by yufeih** [comment]
index.yml page is not using SDP, it also depend on Mustache

**Comment by yufeih** [comment]
SDP in v3 is designed to work with razor templates, here is the transformation process:

```
        deserialize         razor
JSON/YAML ------> C# class  ------> Html

```

There are the goals for the de-serialization process:

- Report errors and warnings with precise line info
    - Report syntax errors with line info
    - Preserve line info from `JToken.Parse` and `YamlDocument.Load`
    - Report and remove null values with line info
    - Handle markdown embedded inside YAML
    - Handle YAML header inside markdown
    - Propagate line info into data validation library
    - Preserve line info when calling `JToken.ToObject` to validate:
           - Property type mismatches
           - JSON/YAML keys that does not exit in c# model
- ~~Support case sensitive member names~~
