### ISSUE TITLE
Config should not require a trailing / to indicate folders

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3077]
This config does not work for azure because _articles_ does not have a trailing `/`. This is not intuitive for most people. We should not have this constraint.

Don't work:
```yaml
routes:
   articles: azure
```

Works

```yaml
routes:
   articles/: azure
```

**Comment by superyyrrzz** [comment]
Agree it's not intuitive to config... while I also don't want to make the meaning of the config dependent on the folder structure of the repo. I'd like to know what the config means by only looking at it.

I think we can also support 2 forms:

- `articles: azure`: this targets a file by default. It can fallback to a folder if file doesn't exist and folder exists.
- `articles: azure/`: this targets a folder for sure.
