### ISSUE TITLE
Support tags in swagger

### ISSUE THREAD

**Issue by chenkennt** [dotnet/docfx#310]

**Comment by hellosnow** [comment]
refactor rest api view model into root and child #334  #336 
Implement [f98c2a662d1b8e210c9ff149be0054bcda966c32](https://github.com/dotnet/docfx/commit/f98c2a662d1b8e210c9ff149be0054bcda966c32)

---
Task description:
Support separate sections by tags in swagger.json:
Previously, rest **API** page is organized by sections, and description for each section is handled by footer. We improved this logic by reusing "Tags" in swagger.json. Some guideline:

- If you want to add bookmark to the section, you could add "x-bookmark-id" into tag in swagger.json:
```json
"tags": [{
   "description": "Access to Petstore orders",
   "x-bookmark-id": "bookmark2",
   "name": "store"
}]
```

- If one **API** is tagged with multiple tags, it will show in multiple tag sections.

- If tags are defined in swagger.json while some **API** is not tagged, we will add "Other apis" as default to organize these **API**s.

**Comment by hellosnow** [comment]
Update #346 
- Implement uid and Conceptual for tag:
  - Tag's uid format is like "graph.windows.net/myorganization/Contacts/1.0/**tag**/pet store"
  - Writer can overwrite conceptual or description in overwrite document.
- In tag, if no **x-bookmark-id** is provided, get html id from **name**.
- Remove sort by section logic, only sort by tags and its original sequence in json.

**Comment by hellosnow** [comment]
Add doc #349
