### ISSUE TITLE
[Question] UID/Xref-Links in Plugin

### ISSUE THREAD

**Issue by Herrmel** [dotnet/docfx#3107]
**DocFX Version Used**: 2.37

**Template used**: custom template

I try to adapt the [PlantUML Plugin](https://github.com/KevReed/DocFx.Plugins.PlantUml)(wich is a customized Markdown Renderer) for docfx so that I can Link to classes by Uid in the resulting SVG's. Since I don't get any response on the Plugin specific Github I'll try asking here. I already adapted it so it doesnt fail to generate the whole documentation when plantUml fails to generate a diagramm(basicly just some try catch with Logger Output) and some other irrelevant additions. PlantUml already supports Links but I would need to give it the resulting link to the path of the Uid or somehow adapt the Link of the output SVG afterwards. So I would like to know how I could do this since I dont find a way myself. Also where can I find the destination of the md-file I'm rendering? token.SourceInfo.File gives me a part of it(relative path from docfx.json) and token.SourceInfo.File.FormatPath(System.UriKind.Absolute) gives me the workdestination of my console and it just appends the relative path of the markdown even though that folder does not exist. I cant find a attribute where the destination of docfx.json is given so I could get the resulting path that way. Thank you.

**Comment by Herrmel** [comment]
I'll just explain my problem further since I guess nobody is getting what I want to do here and instead of telling me I just get ignored. 
The PlantUmlPlugin is just a [Markdown Renderer](https://dotnet.github.io/docfx/tutorial/howto_customize_docfx_flavored_markdown.html) that renders codeblocks just like in your Documentation only with languagespecification "plantuml". It passes plantUml (a open source java programm) the text inside the block and returns the resulting svg text (something like <svg>svg content</svg>).
PlantUml also supports Links: text inside double '[' is considered a Link and will be converted to an a-Element in the svg like following:
`[[http://plantuml.com This label is printed]]`
will result in:
`<a href="http://plantuml.com">This label is printed<a>`
For more infos see [here](http://plantuml.com/link)

So what I want to support is that you can write docfx's crosslink Syntax inside these brackets. I can easily get the substring with regexmatches. But then I have a substring like **"@uid"** or **"<xref:uid>"** and want to change it to "linkToUid" before passing it to plantUml. 

I hope that docfx can somehow provide the `DfmCustomizedRendererPartBase<IMarkdownRenderer, MarkdownCodeBlockToken, MarkdownBlockContext>`-class with the possibilty to convert my substring to a Link to the correct page either within my Project or with Xref-Service.

I'm really frustrated cause it should be something already implemented in docfx but i cant find where.
I hope you can help me.

**Comment by superyyrrzz** [comment]
Sorry for the late response. Let me first explain how DocFX resolves cross reference:
1. The Markdown parser will transform `@uid` or `<xref:uid>` to HTML `<xref href="uid"/>`
2. A post-process will resolve the `xref` tag in HTML to `<a href="uid_dest.html"/>`

As your `@uid` is in original Markdown's code block, and is processed by the PlantUML plugin, I believe the first step doesn't finish. Here are 2 other ways to achieve this transformation:
1. Write `<xref href="uid"/>` in Markdown directly. 
2. Modifying PlantUML's code to achieve this transformation. This should be more complicated.

As long as the first step finishes, the second step should work by default, as it will find all the `<xref>` tags in HTML to resolve.

I will not guarantee the options mentioned above can work, as this feature request is a bit complicated in current DocFX's architecture. Hope this can help and we can further disscuss it if you have any other findings.

**Comment by Herrmel** [comment]
Thank you it finally works pretty good when docfx can resolve the uids. I just replace the links in the svg-string I get back from plantuml with xref-elements (when its href doesn't equal something like http:/...) and docfx resolves them later. 

But if docfx cant resolve the path to the uid, the resulting <span> element, all of its childnodes  and all nodes following are placed outside of the <svg> by browsers and so completely break the diagramm. The reason for this is svg doesnt support spans. 
I guess the only way is a postpostprocessor or a script afterwards to resolve this issue.

**Comment by superyyrrzz** [comment]
> I guess the only way is a postpostprocessor or a script afterwards to resolve this issue.

DocFX's custom [post-processor](http://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html) can be this "postpostprocessor".

**Comment by Herrmel** [comment]
I guess I'll give it a try
I'm just wondering why it creates a span because every link I see that was unable to resolve is a simple link element with a href like `<a href="xref:Uid">Text</a>`.
Example: [your MarkdownLite API Documentation seems missing so most links in this article dont work](https://dotnet.github.io/docfx/tutorial/intro_markdown_lite.html)

Are the multiple Childnodes the reason for this?

**Comment by superyyrrzz** [comment]
If the xref is of form `[Text](xref:Uid)`, the unresolved result would be like `<a href="xref:Uid">Text</a>`. If it's of form `@Uid` or `<xref:Uid>`, the unresolved result would be a span.

BTW, it is really strange why these links in the article you mentioned is unresolved, as the referenced uid does exist... We need to further investigate this.

**Comment by Herrmel** [comment]
Can I add a Group or LogCode to the outputfile when my renderer renders the plantuml svg so I can find it more easy in the PostProcessor? Also why does the LogCode-Collection not contain a "UidNotFound" for the unresolved xref in the Svg? Does it only Log xrefs like [text](xref:uid)?

For the unresolved Links on your website: I cant find the namespaces for `Microsoft.DocAsCode.MarkdownLite` and `Microsoft.DocAsCode.Plugins` in [your API Documentation](https://dotnet.github.io/docfx/api/Microsoft.DocAsCode.html)

**Comment by superyyrrzz** [comment]
Sorry for the extremely late response... Yes, you can call `Logger.LogWarning`.

It will not log warning when referencing UID using `@`. All the other form will.
