### ISSUE TITLE
Search results to open on a new tab 

### ISSUE THREAD

**Issue by cbenea** [dotnet/docfx#3111]
**DocFX Version Used**: 2.21.1.1

**Template used**: custom template

**Steps to Reproduce**:

1. I have .attr("target", "_blank") set on [this line](https://github.com/dotnet/docfx/blob/0213400ab3cfc4193548ed4c1bea3b760b7e1395/src/docfx.website.themes/default/styles/docfx.js#L243) as explained in this issue: https://github.com/dotnet/docfx/issues/227
2. docfx.js file from style folder is unchanged (as per default template), with above configuration **.attr("target", "_blank")**

**Expected Behavior**: 
Search results should open in a **new tab**

**Actual Behavior**:
Search results are opening on the same page

**Comment by cbenea** [comment]
Hi @herohua, 
Could you kindly tell me if there is another configuration that I need to make in order to display the search results in a new tab? Because currently is displaying on the same page, which is fine but I need to open a new page for the search results. The reason is that my home page is with dark blue background and the results are with black fonts and its hard to be read.
Thanks again for your help!

**Comment by superyyrrzz** [comment]
Could you share more details about how you apply your change? Do you follow this document? https://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html#merge-template-with-default-template
