### ISSUE TITLE
DocFX Flavored Markdown Preview - File inclusion not previewing...

### ISSUE THREAD

**Issue by MasaMune692** [dotnet/docfx#3152]
**DocFX in Visual code 1.25.1**: 

**Steps to Reproduce**:

1. Create a file named demo.md and fileincluded on the same root folder
2. place this content in demo.md:
`# This is the **HOMEPAGE**.`
`Refer to [Markdown](http://daringfireball.net/projects/markdown/) for how to write markdown files.`
`## Quick Start Notes:`
`Add images to *images* folder if the file is referencing an image.`

`[!include[test](fileincluded.md)]`

3. place this content in fileincluded.md:
File content included here.

**Expected Behavior**:
This is the HOMEPAGE.
Refer to Markdown for how to write markdown files.

Quick Start Notes:
Add images to images folder if the file is referencing an image.
**File content included here.**

**Actual Behavior**:
This is the HOMEPAGE.
Refer to Markdown for how to write markdown files.

Quick Start Notes:
Add images to images folder if the file is referencing an image.
`[!include[test](articles/fileincluded.md)]`

As you can see, the file inclusion is not parsed/transformed. I tested this in Visual Studio 2017 using docfx.console and it works like a charm.

**Comment by herohua** [comment]
@MasaMune692 , could you double confirm the existence of `fileincluded.md` in the same folder as `demo.md`? Could you also attach your `docfx.json` for us to analyze?

**Comment by MasaMune692** [comment]
DocFX Flavored Markdown Preview is not requiring docfx.json but attached is what I used for VS and it works fine in VS just not Visual Code for preview.
[docfx_vs_test.zip](https://github.com/dotnet/docfx/files/2264936/docfx_vs_test.zip)

**Comment by superyyrrzz** [comment]
@928PJY Do you have any comment on this issue?

**Comment by 928PJY** [comment]
hi @MasaMune692 please move to the [docs-markdown](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-markdown), `Docfx` will not be supported anymore.
