### ISSUE TITLE
Ignoring project.json file

### ISSUE THREAD

**Issue by jerriep** [dotnet/docfx#316]
![image](https://cloud.githubusercontent.com/assets/1006420/15350438/a0d54500-1d03-11e6-91d3-22cb7b1870c1.png)

### My Project.json file is being ignore
I have an ASP.NET Core RC2 project and I am using the latest docfx (1.9.1.0) which I downloaded from the releases page. When I try and generate metadata for my RC2 project I am getting a warning stating that the project.json file is not supported and will be ignored.

Why is this?

**Comment by qinezh** [comment]
`project.json` based project is not supported in docfx of release version currently, but you could try the [CLI supported pre-release version](https://github.com/dotnet/docfx/releases/tag/1.10.0-alpha)

**Comment by jerriep** [comment]
Thanks! Will download that one :)
