### ISSUE TITLE
String truncation in the 'IN THIS ARTICLE' section when window width exceed the max. content width.

### ISSUE THREAD

**Issue by tatsufu** [dotnet/docfx#3166]
**DocFX Version Used**: 
2.37.2.0
2.37.1.0

**Template used**: (`default` or `statictoc` or contain custom template)
Unknown

**Steps to Reproduce**:

1. Go to http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html
2. Maximize the browser window so that there is no text wrapping in the 'IN THIS ARTICLE' section
3. Observe the truncation on the #3 topic (3. Use DocFX integrated with Visual Studio)
4. Resize the window width so that the text wrapping happens in the 'IN THIS ARTICLE' section
5. Above mentioned string is wrapped properly, and there is no truncation any more

This issue repros both in Edge and Chrome

**Expected Behavior**:
There is no string truncation regardless of the window width.

**Actual Behavior**:
There is a string truncation when window width exceed the max. content width.

**Comment by tomaustin700** [comment]
This is still an issue in 2.40.12

**Comment by superyyrrzz** [comment]
related: #3038

**Comment by jsellares** [comment]
It still happens with version 2.41.0 in both `default` and `statictoc` templates.
Is there any update about this issue? Do you think this can be fixed in the templates easily? any clue for the newbies?

**Comment by superyyrrzz** [comment]
@jsellares Sorry for not give enough information about this. I think it will not need too much knowledge into DocFX. All you can do is to modify these 2 files in your output folder:
https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/styles/docfx.js
https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/styles/docfx.css
