### ISSUE TITLE
使用谷歌浏览器预览网站时，点击锚点，页面内容定位不准确

### ISSUE THREAD

**Issue by XzMitsui** [dotnet/docfx#3174]
**DocFX Version Used**: 最新

**Template used**: (`default` or `statictoc` or contain custom template)默认

**Steps to Reproduce**:

1. 编写md文档
2. 使用docfx生成网站
3. 点击右侧以文档中 ###XX 标题生成的锚点

**Expected Behavior**:当点击任何一个锚点时，页面内容会转移到对应处且锚点标题应该在屏幕最上面完整显示。

**Actual Behavior**:点击锚点时，转移到对应内容的中部，锚点标题被顶上去，定位不准确（此问题我使用谷歌浏览器时会出现，ie和edg是正常的）

**Comment by superyyrrzz** [comment]
Does this issue duplicate with #3133 ?

**Comment by XzMitsui** [comment]
@superyyrrzz  我之前看过这个问题，他与我描述的不是同一个。他那边是点击文档中标题（##XX这样的），而我是点击右侧锚点出现的问题，而且在IE浏览器中ok，咋谷歌浏览器中就会出现。

**Comment by XzMitsui** [comment]
@superyyrrzz 好吧，我是第一次点击有偏移，第二次没反应。看来应该是我这里的设置出现什么问题，那请问下，它是根据 `#` 的标题来生成锚点的吧，那么锚点跟标题中`#`的个数有严格的关系么，我最开始使用的`##`而且没有偏移，后来改为`###`，可我无法确定，因为我改回来后也有偏差，谷歌浏览器清除缓存运行网站仍然存在，微软的浏览器都ok。

**Comment by superyyrrzz** [comment]
和个数应该没关系的。确认下你是用`docfx serve`吗？访问 dotnet.github.io/docfx 上的页面有相同问题吗？

**Comment by XzMitsui** [comment]
@superyyrrzz  是的。访问该页面没有问题，只是我本地访问自己的网站时会出现。

**Comment by superyyrrzz** [comment]
确认下你docfx使用的版本，是不是这个问题？ #2741

**Comment by XzMitsui** [comment]
@superyyrrzz 我这里是2.37.0.0的版本。正如上面那个问题里面所说，点击锚点调试后会报错 e is not defind，可奇怪的是，2.36.1版本是五月出的吧，我是在七月下旬下载的docfx，所以应该是此版本之后了，按道理来说应该不会出现这个问题啊。
