### ISSUE TITLE
behavior differences between DocFX v2 and DocFX v3

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3185]
1. 👀New errors/warnings/suggestion

    1. Reserved Metadata for `document_id` and `redirection_url`
    **In DocFx v2**, `document_id` and `redirection_url` is supported in metadata section
    **In DocFx v3**, `document_id` and `redirection_url` is reserved metadata

    2. Multiple hashtag bookmarks
    **In DocFx v2**, bookmarks starts multiple hashtags are supported, like `##bookmark`
    **In DocFx v3**, it will be treated as invalid bookmark.

    3. invalid path chars in link file name `*`, `:` e.g. 
        ```text
             [`ResolveUsing`](Xamarin.Forms.Internals.DependencyResolver.ResolveUsing*)
        ```

        **In DocFx v2**, these link won't be treated as relative path
        **In DocFx v3**, treat as relative path, report `file-not-found`, require content change
    4. redirection url did not exist when the redirectin_with_id is true
       ```yml
        redirections:
            docs/a.md: "/docs/non-exsited"
            docs/c.md: "/docs/non-exsited#bookmark"
            docs/b.md: "http://hostname/test"
       ```

        **In DocFx v2**, the document id of source file won't be taken to the dest, but no suggestion/warning will be reported.
        **In DocFx v3**, the document id of source file won't be taken to the dest, but a suggestion with code `redirection-url-not-existed` will be reported.

2. 👀Customer 404

    **In DocFx v2**, it's supported
    **In DocFx v3**, it's NOT supported.

3. 👀Duplicated TOC files(`toc.yml` and `toc.md`) at same folder

    **In DocFX v2**, warning will be reported and `toc_rel` will use `toc.yml`.
    **In DocFX v3**, error will be reported, both toc files will not be processed and used.

4. 👀 Redirection File
    1. 👀Redirection rules in yaml-header
        **In DocFx v2**, we support adding redirection rule in yaml-header.
        sample *a.md*:
        ```markdown
        ---
        redirect_url: /b
        ---
        ```
        that means there is a redirection rule: `a.md: /b`
        **In DocFx v3**, we don't support this syntax, you have to mannully add this rule in docfx.yml.
        > So there will be some task for migration tool:
        > 1. Add those yaml-header redirection to docfx.yml
        > 2. Remove those files

    2. 👀Document id of index.yml which have been redirected from index.md with document_id
        **In DocFx v2**, `index.yml` and `index.md` are in the different processor, so they don't have the redirection info, which caused they have different document id.
        **In DocFx v3**, the redirection info is global, so according to the redirection rule, this two file have the same document id.

5. Link
    1. 👀Resolve link defined in HTML block
        **In DocFX v2 (Markdig engine)**, no resolve, no validation, all links keep unchanged in HTML block.
        **In DocFX v3**, resolve and validate.
    2. 👀SDP page document_id diff
        **In DocFX v2**, the redirection rule **isn't** properly applied to SDP page (*.yml)
        **In Docfx V3**, the redirection rule **is** properly applied to SDP page (*.yml)

6. 👀Xref resolve
    While use refer to xref within a link with empty text:
    ```
    [](xref:uid_of_another_file?displayProperty=fullName)
    ```
    **In DocFx v2**, it will be resolved to
    ```
    <a href="path_of_another_file">fullName</a>
    ```
    **In DocFx v3**, the text will be left empty
    ```
    <a href="path_of_another_file"></a>
    ```

7. 👀 `homepage` support
    `homepage` is marked as deprecated in v2, but still supported. It's not supported in v3.
     Migration CI will check this difference, once we found that, we can manually fix the content, or change the migration tool to fix it. 

8. 👀 Bookmark validation on toc file
    **In DocFx v2**, there is no bookmark validation on toc file.
    **In DocFx v3**, there is bookmark validation on toc file.

9. 👀 Link resolved logic in included file
    **In DocFx v2**, the link in the included file will be resolved related to the referencing file
    **In DocFx v3**, the link in the included file will be resolved related to the included file.
to fix the diff, we can use `~/` instead of relative path in the included file.

10. 👀 Diagnostics involved by global metadata/filemetadata.
    **In DocFx v2**, the diagnostics will be reported on the corresponding file which matches the metadata glob.
    **In DocFx v3**, the diagnostics will be reported on `docfx.json` once.

11.  👀 Include a redirection file(corner case, only 8 files in ASPNetCore, and it has been fixed).
    **In DocFx v2**, no warning reported and the empty string will be included.
    **In DocFx v3**, report a `include-not-found` warning.

12. Link
    1. ToLower Case
        **In DocFx v2**, some links are turned lowercase
        **In DocFx v3**, all relative links are turned lowercase.

    2. `./` prefix will be removed
    3. Invalid link
        Sample *a.md*
        ```markdown
        [B](b.md)
        ```
        if the b.md is not existed.
        **In DocFx v2**, href point to source path without file extension.
        ```html
        <a data-linktype="relative-path" href="b">B</a>
        ```
        **In DocFx v3**, href point to source path.
        ```html
        <a data-linktype="relative-path" href="b.md">B</a>
        ```
    4. Encode output link
        **In DocFX v2**, all links in output files will be encoded like ` ` -> `%20`
        **In Docfx V3**, all links in output files will NOT be encoded

13. ~~Glob config~~

    1. ~~👀`***` support~~

        ~~**In DocFx v2**, file glob support triple wildcard(`***`), which is same as `**`:
        `**/readme.md` and `***/readme.md` can match `readme.md`, `a/readme.md` and `a/b/readme.md`
        `**readme.md` and `***readme.md` can match `readme.md`, `a/readme.md`, `a/b/readme.md` and `testreadme.md`~~

        ~~**In DocFx v3**,  triple wildcard(`***`) is not supported,
        `**/readme.md` can match `readme.md`, `a/readme.md` and `a/b/readme.md`
        `**readme.md` can match `readme.md` `testreadme.md`, but cannot match `a/readme.md`~~

    2.~~`**.xxx` support~~
        ~~**In DocFx v2**, `**.xxx` means `**\*.xxx`~~
        ~~**In DocFx v3**, `**.xxx` is treated as `*.xxx`~~

14. 👀~Error Level changes~
    
    1. ~`invalid-yaml-header`~
    ~**In DocFx v2**, it's warning~
    ~**In DocFx v3**, it's error.~

15. 👀~Contributor display name~

    ~**In DocFx v2**, the contributor display name is resolved from github, which will be same with their github user name~
    ~**In DocFx v3**, the contributor display name is resolved from commit information, which will be different with their github user name.~

16. Redirection

    1. Metadata
        **In DocFx v2**, we keep all metadata for redirection file
        **In DocFx v3**, we only keep redirect_url and locale metadata for redirection file
        Sample:
        *.raw.page.json* in DocFX v2:
        ```json
        {
            "outputRootRelativePath": "./",
            "rawMetadata": {
                "_op_brand": "azure",
                ...(more than 20 properties)
                "locale": "en-us",
                "page_type": "conceptual",
                "pdf_url_template": "https://docs.microsoft.com/pdfstore/en-us/Azure.azure-documents/{branchName}{pdfName}",
                "redirect_url": "/azure/monitoring-and-diagnostics/azure-diagnostics",
                "search.ms_docsetname": "azure-documents",
                "search.ms_product": "Azure",
                "search.ms_sitename": "Docs",
                "site_name": "Docs",
                "title": " | Microsoft Docs",
                "version": 0
            },
            "themesRelativePathToOutputRoot": "_themes/"
        }
        ```
        *.raw.page.json* in DocFX v3:
        ```json
        {
            "outputRootRelativePath": "./",
            "rawMetadata": {
                "locale": "en-us",
                "redirect_url": "/azure/monitoring-and-diagnostics/azure-diagnostics"
            },
            "themesRelativePathToOutputRoot": "_themes/"
        }
        ```
    4. ~relative redirect to~
        ~**In DocFx v2**, the relative path is applied to redirectTo for calculating document_id~
        ~**In DocFx v3**, an `invalid-redirect-to` warning will be thrown~

17. Html Escape

    1. `name` and `content` attribute in [*metadata.html*](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3535?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fazure-stack%2Fuser%2Fazure-stack-version-profiles-python.metadata.html)

    2. Href attribute of Link in [*.pagehtml](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3535?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Findex.page.html)

18. [Content escape](https://github.com/MicrosoftDocs/azure-docs-pr/blob/markdig-migration-v3/articles/cognitive-services/Bing-Custom-Search/index.yml#L30) for LandingData
    **In DocFx v2**, `text` will just append `<p>` tag and keep the content, so the user has to encode the content.
    **In DocFx v3**, `text` will be passed to the razor and encoded, so the user doesn't need to encode the content.

19. Removed Matadata:

    1. [pdf_name from toc.json](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3562?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Factive-directory%2Fconnect%2FTOC.json)

    2. [expanded default value from toc.json](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3561?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fsecurity%2FTOC.json)

👀: behavior difference that is visible to users

**Comment by yufeih** [comment]
@OsmondJiang , we should keep the `expanded` property in TOC

**Comment by OsmondJiang** [comment]
@yufeih , we already exposed `expanded` property

**Comment by OsmondJiang** [comment]
I've updated this issue as currently we fixed a lot of differences during migration test, @live1206  @mingwli  @herohua  @yufeih  @928PJY

**Comment by OsmondJiang** [comment]
# Loc Pipeline changes in docfx v3

## TOC

- TOC will not be copied to loc repo before building
   
   **v2** will always copy all missing toc files to loc repo before building, these copied source toc files will be built and published
   **v3** will not, only the source toc files which is not localized but including localized toc file(s) will be built and published

## Errors

- Build report contains source repo file errors

  **v2** will not show source repo files' errors even these files are referenced by localized files and involved in the build.

   **v3** will show the source repos files' errors if these files are involved in localization repo build.

- Fallback to deleted resource will not report warnings

   **v2** will report warning if the image can't be found(it was deleted) in source repo, but actually fallback to delete resource are supported by DHS(dhs never delete resources)

   **v3** will support to fallback to deleted images just like fallback to deleted token/code snippets, no warnings will be reported.

## Fallback

- Image/Page fallback for non-live branches

   **v2** will always fallback to source master branch(using file-map)

   **v3** will first fallback to source corresponding branch(same branch with current loc branch), if it doesn't exists, then fallback to master.(not using file-map)

- Token/Code snippet fallback for non-live branches

   **v2** will always fallback to source corresponding branch(configured in ops config).

   **v3** will first fallback to source corresponding branch(same branch with current loc branch), if it doesn't exists, then fallback to master

**Comment by superyyrrzz** [comment]
# v2 defect in SDP when output JSON instead of HTML

V2 has some post steps that are based on HTML. In this case, if a certain schema choose output type as JSON instead of HTML, all these steps are missing. The markdown content in model can missing some processing and in an intermediate state. V3 improved this by finishing all these steps when markup.

Here is some unexpected behavior in v2:

## `<xref>` unresolved

v2 has a post step to resolve intermediate `<xref>` tags to final `<a>` links, which is based on HTML. If a  schema outputs to JSON, it misses this step, which makes the intermediate `<xref>` tag keep in output.

Related bugs:
* https://dev.azure.com/ceapex/Engineering/_workitems/edit/111037?src=WorkItemMention&src-action=artifact_link
