### ISSUE TITLE
azure-docs-pr issue: toc_rel not same with v2

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3186]
for not-in-TOC files, do not fall back to find the closest TOC file in their sub-folder, just consider TOC file in their parent folders

**Comment by mingwli** [comment]
Tried the following: 
1. with latest fix in [azure-docs-pr PR](https://github.com/MicrosoftDocs/azure-docs-pr/pull/49256/files)
 * `azure-docs-pr\articles\application-gateway\toc.yml line:112`
 * `azure-docs-pr\articles\iot-central\TOC.yml line:42`
2. only build these two folders 
 * `articles/application-gateway/**/*.{md,yml}`
 * `articles/iot-central/**/*.{md,yml}`
3. output `toc_rel` remain consistent
