### ISSUE TITLE
Performance impact of string.Equals with OrdinalIgnoreCase

### ISSUE THREAD

**Issue by matkoch** [dotnet/docfx#3207]
https://github.com/dotnet/docfx/blob/75967052d9fbe3be19d277933ac55a5757b16348/src/Microsoft.DocAsCode.Metadata.ManagedReference/MergeComments/MergeCommentsHelper.cs#L98

This line causes approx. 38% of execution time. Can't you do a normal equality check?

**Comment by yufeih** [comment]
Ignore case check is one part of the problem, another perf problem is we iterate through the list one by one instead of using hash lookup. @TianqiZhang @superyyrrzz

**Comment by matkoch** [comment]
![image](https://user-images.githubusercontent.com/5005566/44185816-15afdf00-a116-11e8-9f33-d720a2a9a117.png)

**Comment by matkoch** [comment]
I’m a bit confused how you use milestones.

**Comment by herohua** [comment]
@matkoch , sorry this task must have been lost of tracking when the team started to focus more on v3. We apologize for the inconvenience and confusion to you.

I've made an attempt fix on this in #3936 . If everything is good, we will ship it in recent release (on 1/28).

**Comment by matkoch** [comment]
@herohua

**Comment by superyyrrzz** [comment]
@matkoch As @herohua updated, this issue should already be fixed. Have you tried the latest version again?

**Comment by matkoch** [comment]
@superyyrrzz sorry i missed that. Thanks!
