### ISSUE TITLE
Setup impact CI for azure-docs-pr

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3220]
- [x] Setup a CI machine which has enough space
- [x] Setup CI build definition

**Comment by yufeih** [comment]
make sure we use the same hardware configuration as production build servers to monitor the performance.

**Comment by OsmondJiang** [comment]
@yufeih we don't have and need so powerful machine like OPS build...

**Comment by OsmondJiang** [comment]
@herohua  is going to apply a more powerful machine for CI.
current build run result: https://ceapex.visualstudio.com/Engineering/All/_build/results?buildId=10162&_a=summary

current change pr: https://ceapex.visualstudio.com/Engineering/All/_git/Docs.DocFX.Impact/pullrequest/2597?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Factive-directory%2Factive-directory-azure-ad-controls-manage-guest-access-with-access-reviews.metadata.html

**Comment by yufeih** [comment]
@928PJY @OsmondJiang , `git submodule -b` does not auto checkout the target branch, you can see a lot of diffs of `original_content_git_url`. We need a way to checkout to a branch as part of the impact test.
