### ISSUE TITLE
Syntax highlighting with string interpolation

### ISSUE THREAD

**Issue by guardrex** [dotnet/docfx#3226]
Is there any plan to introduce highlighting for interpolated strings in code?

For example, consider the following line in a markdown code block ...

```csharp
Console.WriteLine($"option2 = {Configuration["option1"]}");
```

It's rendered as ...

<img width="350" alt="capture" src="https://user-images.githubusercontent.com/1622880/44294081-87dc0d00-a257-11e8-930e-9385c7ceffe1.PNG">

... but appears in the Visual Studio Code UI as ...

<img width="413" alt="capture1" src="https://user-images.githubusercontent.com/1622880/44294128-0b95f980-a258-11e8-9ca1-8be090389830.PNG">

... and appears in the Visual Studio UI as ...

<img width="330" alt="capture2" src="https://user-images.githubusercontent.com/1622880/44294131-0df85380-a258-11e8-8ccd-408d188ab4bf.PNG">

... so the editors are distinguishing the string parts (red) from the code parts (blue or black), but DocFX is just treating the whole thing as a string (all red).

cc: @mozts2005 https://github.com/aspnet/Docs/issues/7207

**Comment by yufeih** [comment]
Syntax highlighting on [docs](https://docs.microsoft.com) is done by [highlight.js](https://highlightjs.org/), tracked by [internal bug 35765](https://ceapex.visualstudio.com/Engineering/_workitems/edit/35765)
