### ISSUE TITLE
Splitting api into logical metadata sections fails by duplicating link

### ISSUE THREAD

**Issue by pardeike** [dotnet/docfx#3227]
**DocFX Version Used**: 2.38.1

**Template used**: `default`

**Steps to Reproduce**:

Given a docfx.json
```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [
            "CodeMatcher.cs"
          ],
			 "src": "../Harmony"
        }
      ],
      "dest": "api/public"
    },
	 {
      "src": [
        {
          "files": [
            "MethodPatcher.cs"
          ],
			 "src": "../Harmony"
        }
      ],
      "dest": "api/internal"
    }
  ],
  "build": {
    "content": [
		{
        "files": [
           "index.md",
          "toc.yml"
        ]
      },
		{
        "files": [
          "articles/**.md",
          "articles/**/toc.yml"
        ]
      },
      {
        "files": [
          "api/**/**.yml",
          "api/**/index.md"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [
      "default"
    ],
    "postProcessors": [],
    "markdownEngineName": "markdig",
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": true,
    "disableGitFeatures": false
  }
}
```

and a top level toc.yml
```yml
- name: Home
  href: index.md
- name: Articles
  href: articles/
- name: Public API
  href: api/public/
- name: Internal API
  href: api/internal/
```
the navigation menu is wrong.

**Expected Behavior**:

I would like to see two tabs
- Public API (./api/public/Harmony.html)
- Internal API (./api/internal/Harmony.html)

**Actual Behavior**:

- Public API (./api/internal/Harmony.html)
- Internal API (./api/internal/Harmony.html)

Both links go to the same url.

The log shows
`
Build succeeded with warning.
[18-08-18 11:50:34.590]Warning:[BuildCommand.BuildCore.Build Document.Load.TocDocumentProcessor](articles/toc.yml)Skipping GetFileDetail. Exception found: System.InvalidOperationException, Message: Process has exited, so the requested information is not available.
[18-08-18 11:50:34.591]Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ManagedReferenceDocumentProcessor.Save](api/public/Harmony.yml)Uid(Harmony) has already been defined in api/internal/Harmony.yml.
	2 Warning(s)
	0 Error(s)
`

**Comment by pardeike** [comment]
Just for clarification: public/internal are arbitrary choices here. The more general question is:
Can I split my API into several sections/groups/folders that are shown as separate tabs in the navigation?

**Comment by superyyrrzz** [comment]
@pardeike It's not supported in config. You can achieve this by splitting you running `docfx.exe` into `docfx.exe metadata` and `docfx.exe build`, while changing the `docfx metadata` generated `toc.yml` in between to the grouping you want.

**Comment by superyyrrzz** [comment]
This might be related to #396
