### ISSUE TITLE
azure-docs-pr issue: contributor name resolves differently

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3238]
active-directory/active-directory-conditional-access-azure-authenticator-app.md
![image](https://user-images.githubusercontent.com/17958546/44330495-bea16580-a499-11e8-9a7e-0116b244dc48.png)

**Comment by yufeih** [comment]
Should be related to #3218

**Comment by 928PJY** [comment]
no, this issue is caused by that there are two user profiles with the same email in the user_profile.json

**Comment by superyyrrzz** [comment]
This issue mainly affects the impact test. Given the user profile cache is mutable in each build, we have several ways to fix this:

1. Add logic to build service to store the user profile cache on blob for the current build, which is for impact test use.
2. Get the cache remotely from the server when building.
3. Fix output in the impact tool: remove these duplicate users.

Consider the effort, we currently prefered choice 1

**Comment by yufeih** [comment]
Close this issue as patching the impact tool is has the cheapest cost
