### ISSUE TITLE
Make copyright configurable

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#324]
The [footer partial](https://github.com/dotnet/docfx/blob/master/src/docfx.website.themes/default/partials/footer.tmpl.partial) includes:

```html
<span>Copyright © 2015-2016 Microsoft<br>Generated by <strong>DocFX</strong></span>
```

Of course, most people won't be generating content that is copyright Microsoft... can we make this configurable via global metadata? Either the whole span, or just the copyright part.

**Comment by superyyrrzz** [comment]
Hi @jskeet , you can use `_appFooter` in global metadata to customize the whole span. It's been implemented in dev branch.

**Comment by jskeet** [comment]
Great, thanks. Will wait until it's in a release then pick it up.
