### ISSUE TITLE
azure-docs-pr issue: contributors error

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3241]
media-services/previous/media-services-castlabs-integration.md
![image](https://user-images.githubusercontent.com/17958546/44349629-0511b700-a4d0-11e8-9a4d-dc3ca12fe39d.png)
![image](https://user-images.githubusercontent.com/17958546/44349642-0d69f200-a4d0-11e8-90cc-afdea8f05944.png)

**Comment by yufeih** [comment]
can we use the same issue to track the same type of errors? #3238

**Comment by yufeih** [comment]
#3218

**Comment by 928PJY** [comment]
they are not the same issue

**Comment by yufeih** [comment]
dup of #3218 , they share the same root cause
