### ISSUE TITLE
do not autolink malformed links

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3272]
articles\cortana-analytics-technical-guide-demand-forecast.md
![image](https://user-images.githubusercontent.com/17958546/44559772-ae7dd480-a77e-11e8-826e-b437cb76d595.png)

![image](https://user-images.githubusercontent.com/17958546/44559759-9c9c3180-a77e-11e8-83e0-ac8a62ddad3b.png)

**Comment by yufeih** [comment]
Can we lowercase all links during impact HTML normalization? Than docfx can leave all links as is. @928PJY @herohua @OsmondJiang

**Comment by MihaZupan** [comment]
I think https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/AutoLinks.md#valid-domain-tests should cover this case
