### ISSUE TITLE
azure-docs-pr: query string encoding

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3280]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2696?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fanalysis-services%2FTOC.json&_a=files

**Comment by yufeih** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2696?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fapi-management%2FTOC.json&_a=files

**Comment by yufeih** [comment]
Let's not touch any user written URL, including casing and encoding.

**Comment by OsmondJiang** [comment]
agree, just merge it as expected, @herohua  what do you think?
