### ISSUE TITLE
azure-docs-pr: code-xml is not rendered correctly

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3281]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2696?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fapi-management%2Fpolicies%2Fset-header-to-enable-backend-to-construct-urls.page.html&_a=files

![image](https://user-images.githubusercontent.com/19990166/44574755-dd1aa000-a7bc-11e8-808c-e08bd20f07ae.png)

**Comment by yufeih** [comment]
`azure-docs-pr.docfx.yml` does not have a dependency entry for `api-management-policy-samples`, @928PJY @OsmondJiang is it a bug in import tool?

**Comment by OsmondJiang** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2729?_a=overview
