### ISSUE TITLE
Improve look and feel of default theme

### ISSUE THREAD

**Issue by JamesNK** [dotnet/docfx#3283]
I feel like the default theme for docfx 2.x is plain, and content feels small and rather cramped. Compared to the template used by docs.microsoft.com it is narrow and the text is small. I think the product can benefit from involving a designer to make it more attractive. Same with your [website](https://dotnet.github.io/docfx/).

[docs.microsoft.com](https://docs.microsoft.com/en-us/nuget/what-is-nuget) vs [docfx](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html)

All my subjective opinion of course. Disclaimer: I am also a developer with no sense of design 😄

**Comment by yufeih** [comment]
We are trying to bring docs.microsoft.com theme to docfx in v3, it is a large amount of work, but stay tuned 😄

**Comment by nvisionative** [comment]
@yufeih thanks for the response - so are we correct in interpreting that the current repo here (pre v3 release) has some variation of the MS Docs template built in?  If ao, this is FANTASTIC news!

**Comment by TheReaLee** [comment]
Just stumbled here... any news?

**Comment by superyyrrzz** [comment]
@TheReaLee See v3 roadmap for the progress: https://github.com/dotnet/docfx/blob/v3/docs/roadmap.md

**Comment by douglasg14b** [comment]
From the current state of the roadmap, the theme looks usable? If so, how can we utilize it as it currently is?

**Comment by yufeih** [comment]
A new template has been shipped in [v2.63.0](https://github.com/dotnet/docfx/releases/tag/v2.63.0). The [docfx official site](https://dotnet.github.io/docfx/) has been updated for people to see what the new template looks like.
