### ISSUE TITLE
Support UID in TOC for SDP pipeline

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3288]
as title

**Comment by yufeih** [comment]
Track xref/uid support in #3050, this include everything from TOC to markdown to SDP to config. Close as dup.

**Comment by OsmondJiang** [comment]
seems SDP pipeline doesn't cover this case, @yufeih  and @live1206 , i am reopening this issue and do it now. 

Find some example in MicrosoftDocs, seems all reference content toc using uid.

**Comment by OsmondJiang** [comment]
example here: https://github.com/MicrosoftDocs/dynamics365-docs-odata-apis/blob/master/WebAPI-reference/dynamics-ce-odata-9/toc.yml
