### ISSUE TITLE
Check out submodule to specified branch during impact test

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3289]
like azure-docs-pr submodule defined in our impact repo, we should always checkout to master branch before running impact test

git submodule -b doesn't work, @928PJY

**Comment by mingwli** [comment]
TODOs:
after pull
1. git config -f .gitmodules to read branch info;
2. git git ls-tree master <submodule worktree path> to read commit-hash;
3. git checkout branch in <submodule worktree path>;
4. git reset --hard commit-hash in <submodule worktree path> to ensure branch pointing to the right commit hash;

**Comment by mingwli** [comment]
[Impact PR](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3341?_a=overview)
