### ISSUE TITLE
azure-docs-pr: external -> relative path

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3293]
/source/azure-docs-pr.output/azure/active-directory/fundamentals/whats-new.page.html

![image](https://user-images.githubusercontent.com/19990166/44650871-5ebb3980-aa1a-11e8-82e1-a908ff72c827.png)

**Comment by yufeih** [comment]
It is a source error. It is technically correct not to treat it as an external link. Treating it as a relative path gives us a way to report the warning during build. 

The original content has been [fixed](https://github.com/MicrosoftDocs/azure-docs-pr/commit/7306b06a3d5c7dbb294c9897e001d57cfa4b0413#diff-85d02739e00d63c5b3d381c8bac06373R552)
