### ISSUE TITLE
azure-docs-pr: contributor count  are different

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3295]
![image](https://user-images.githubusercontent.com/19990166/44651062-e99c3400-aa1a-11e8-8134-3d4a98af51fa.png)

/source/azure-docs-pr.output/azure/backup/backup-azure-file-folder-backup-faq.raw.page.json

**Comment by OsmondJiang** [comment]
/source/azure-docs-pr.output/azure/backup/backup-azure-manage-vms.raw.page.json

**Comment by yufeih** [comment]
dup of #3238, [trinadhk](https://github.com/trinadhk) and [trinadhkotturu](https://github.com/trinadhkotturu) is the same guy
