### ISSUE TITLE
Preserve source HTML structure when mutating HTML

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3305]
![image](https://user-images.githubusercontent.com/19990166/44759599-b0280d80-ab6d-11e8-9a1b-7620d722b0db.png)

/source/azure-docs-pr.output/azure/active-directory/connect-health/active-directory-aadconnect-health-alert-catalog.page.html

**Comment by yufeih** [comment]
This is likely caused by impact HTML normalization. There are also files with a lot of misplaced `<br />` tags

**Comment by OsmondJiang** [comment]
/source/azure-docs-pr.output/azure/backup/backup-azure-vms-troubleshoot.page.html

**Comment by yufeih** [comment]
Furthure investigation shows this is due to different HtmlAgilityPack OuterHtml behavior. We could modify input HTML without mutating tags using string slicing. It is already done in markdown href transform, this way we keep the source html as is.

**Comment by mingwli** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3343?_a=overview  
mal-formatted source checked-ind
