### ISSUE TITLE
azure-docs-pr: normalize-json doesn't lower all TOC hrefs 

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3307]
![image](https://user-images.githubusercontent.com/19990166/44760078-ca62eb00-ab6f-11e8-8481-06f0f89721f3.png)

/source/azure-docs-pr.output/azure/marketplace/cloud-partner-portal/TOC.json

**Comment by OsmondJiang** [comment]
/source/azure-docs-pr.output/azure/media-services/previous/TOC.json

**Comment by 928PJY** [comment]
cause it is upper-case.
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact?path=%2Fscripts%2Fnormalize-json.js&version=GBmaster&line=122&lineStyle=plain&lineEnd=123&lineStartColumn=1&lineEndColumn=1
