### ISSUE TITLE
azure-docs-pr: relative-path with query string

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3308]
![image](https://user-images.githubusercontent.com/19990166/44760140-1b72df00-ab70-11e8-81d1-1d0d2e9b2e3c.png)

https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2816?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fsecurity%2Fblueprints%2Ffedramp-iaaswa-overview.page.html

**Comment by OsmondJiang** [comment]
under this folder: https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2816?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fsecurity%2Fblueprints

**Comment by yufeih** [comment]
These are expected changes. v3 left URLs intact. v2 trims query string from image URLs. @928PJY can you help update html normalization to strip query string from image src?

**Comment by mingwli** [comment]
[img tag src's querystring/bookmark chopped](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2861?_a=overview)
