### ISSUE TITLE
Metadata cleanup and validation

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3313]
cleanup global metadata:
  - [ ] know what's the purpose of each global metadata
  - [ ] validate known metadata
  - [ ] move them out to like theme options

**Comment by yufeih** [comment]
This is a list of know [Metadata](https://microsoft.sharepoint.com/:x:/r/teams/Visual_Studio_China/ALPS/_layouts/15/WopiFrame2.aspx?sourcedoc=%7bCFA26869-F6FA-43B2-BDED-8B0DE8417C5B%7d&file=OPS%20Metadata%20all.xlsx&action=default)
