### ISSUE TITLE
azure-docs-pr: _op_rawTitle is empty for index.yml

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3319]
![image](https://user-images.githubusercontent.com/19990166/44773746-ed0ef700-aba3-11e8-9cb7-acd85989b25a.png)

https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2871?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fcontainer-service%2Findex.raw.page.json&_a=files

**Comment by yufeih** [comment]
Fixed here: https://github.com/dotnet/docfx/pull/3316

**Comment by yufeih** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2931?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fjenkins%2Findex.raw.page.json&_a=files
