### ISSUE TITLE
azure-docs-pr: toc title is different

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3320]
![image](https://user-images.githubusercontent.com/19990166/44774052-b685ac00-aba4-11e8-9834-2428283537cf.png)

https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2871?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fstorsimple%2FTOC.json&_a=files

**Comment by mingwli** [comment]
the toc document is mal-formatted 
>`#### [From other storage devices](http://download.microsoft.com/download/9/4/A/94AB8165-CCC4-430B-801B-9FD40C8DA340/Migrating Data to StorSimple Volumes_09-02-15.pdf)`

**Comment by OsmondJiang** [comment]
I believe it's expected behavior, we can fix the content

**Comment by mingwli** [comment]
[azure-docs-pr PR](https://github.com/MicrosoftDocs/azure-docs-pr/pull/50581/files)
[impact PR](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2976?_a=files)
