### ISSUE TITLE
Improve toc_rel mapping when doc referenced by multiple TOCs

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#3322]
is lexicographical sort the best solution?  (for discussion)
[PR](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2868?_a=files)

**Comment by yufeih** [comment]
lexicographical sort always picks the first TOC, in azure's case, it is almost always _active_directory_ ...

**Comment by OsmondJiang** [comment]
@yufeih , no, it's also related to the toc folder

**Comment by yufeih** [comment]
git is using [levenshtein distance](https://github.com/git/git/blob/53f9a3e157dbbc901a02ac2c73346d375e24978c/levenshtein.c) to caculate similarities between words.

#3201

**Comment by mingwli** [comment]
[Latest changes preview](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3394?_a=files)

**Comment by mingwli** [comment]
Output the TOC map file and check if word-level levenshtein is reasonable.  

Consider switch on/off configuration.

**Comment by mingwli** [comment]
azure-docs-pr, Documents that have more than one TOCs referencing to itself.
[toc_map.json.txt](https://github.com/dotnet/docfx/files/2387323/toc_map.json.txt)

**Comment by mingwli** [comment]
Files that have more than one candidates after ordering by parent/sub directory count.  
[to_discuss.toc_map.json.txt](https://github.com/dotnet/docfx/files/2387343/to_discuss.toc_map.json.txt)
