### ISSUE TITLE
azure-docs-pr: toc_title doesn't match

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#3323]
[Ref](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2871?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fstorsimple%2FTOC.json&_a=files) 
![image](https://user-images.githubusercontent.com/42199316/44774177-02d0ec00-aba5-11e8-8d33-572549cbbdef.png)

**Comment by yufeih** [comment]
dup of https://github.com/dotnet/docfx/issues/3320
