### ISSUE TITLE
azure-docs-pr issue: log warning and don't build this file when redirection file is not in build scope

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3326]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2816?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fiot-suite-v1-gateway-kit-get-started-sensortag.raw.page.json

**Comment by yufeih** [comment]
@OsmondJiang , some redirections files are not inside build scope. This is likely a mistake. We should log a warning and don't build the redirection file.
