### ISSUE TITLE
duplicated query string & bookmarks in TOC

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#3327]
1. [multiple query string](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2871?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fguides%2Foperations%2FTOC.json&_a=files)
![image](https://user-images.githubusercontent.com/42199316/44828393-3ade3a80-ac4a-11e8-894e-05475dce6fbc.png)
2. [bookmark 1](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2871?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fload-balancer%2FTOC.json&_a=files)
![image](https://user-images.githubusercontent.com/42199316/44828427-724ce700-ac4a-11e8-9da4-02d8309bde0e.png)
3. [bookmark 2](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2871?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fansible%2Ftoc.json&_a=files)
![image](https://user-images.githubusercontent.com/42199316/44828500-c6f06200-ac4a-11e8-8dfc-95494b7f7a74.png)

**Comment by yufeih** [comment]
looks like v3 results are better 😄
