### ISSUE TITLE
azure-docs-pr: conceptual content raw title is different

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3332]
![image](https://user-images.githubusercontent.com/19990166/44835203-0ed0b280-ac66-11e8-9bcf-814a439b9a4a.png)

https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2912?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fapp-service-mobile%2Fapp-service-mobile-value-prop-migration-from-mobile-services.raw.page.json

**Comment by 928PJY** [comment]
a bug of v2, fixed in v3
