### ISSUE TITLE
azure-docs-pr: server build issues

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3359]
- [x] OPS build doesn't need restore CRR info again (Server)
- [x] A lot of Github API Rate Limit Warnnings
- [x] OPS schema validation doesn't need to be executed again(4 minutes) (Pending DHS metadata schama)
- [ ] Although incremental publishing works, but still takes 70+s (DHS)
- [x] Don't need full clone azure-docs-pr for every time build(4.5 minutes), sometimes it takes 10 minutes [report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C9%5C3%5C0c07d4eb-0562-6512-9227-12dbf89d9a0f%5CCommit%5C201809030500558121-docfx-v3-with-fix%5Crawlog.txt?sv=2015-02-21&sr=b&sig=qycyOf5FsY4SDKHyigkKxe7GyPLwH7khtllRVjxfSD8%3D&st=2018-09-03T05%3A33%3A52Z&se=2018-10-04T05%3A38%3A52Z&sp=r) (Server improvment v3)
- [x] Decouple docfx deployment from OPS build deployment:
    - OPS should use the latest docfx package (Server)
    - Staging environments uses staging docfx package feed (Server)
- [x] Decouple git commits time. OPS exposes a GET API to retrieve the commits time for a repo. (Server)
- [x] Manifest seems incorrect [report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C9%5C4%5C0c07d4eb-0562-6512-9227-12dbf89d9a0f%5CCommit%5C201809040206223857-docfx-v3-with-fix%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EFB9%2BdTyz3FsUO36nEpGn6nX2hsJH5POXXVrWzmoi1c%3D&st=2018-09-04T02%3A49%3A24Z&se=2018-10-05T02%3A54%3A24Z&sp=r)
- [x] Support 60min timeout (Server, taking v2 + v3 into consideration)
- [x] When a file has error, should publish other files? (Loc only)

**Comment by OsmondJiang** [comment]
https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C9%5C3%5C0c07d4eb-0562-6512-9227-12dbf89d9a0f%5CCommit%5C201809030500477692-docfx-v3-with-fix%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=r%2FnJ%2FpPsN34ZfGkyU2edpP9NhwOqyHtfWA7u56xkOyQ%3D&st=2018-09-04T04%3A38%3A47Z&se=2018-10-05T04%3A43%3A47Z&sp=r

**Comment by OsmondJiang** [comment]
https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C9%5C6%5C0c07d4eb-0562-6512-9227-12dbf89d9a0f%5CCommit%5C201809062137146499-docfx-v3-with-fix%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KMx3udCLw6gz81TBw2j84o1BmvQKZv%2Fq6E7vCvtuAJg%3D&st=2018-09-06T21%3A57%3A16Z&se=2018-10-07T22%3A02%3A16Z&sp=r

**Comment by herohua** [comment]
also tracked by https://ceapex.visualstudio.com/Engineering/_workitems/edit/38892
