### ISSUE TITLE
azure-docs-pr: code is not resolved correctly

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3364]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3081?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fcognitive-services%2FLUIS%2Fluis-get-started-cs-add-utterance.page.html&_a=files

**Comment by yufeih** [comment]
This is because the dependency repo has been updated.
