### ISSUE TITLE
ArgumentNullException when extracting metadata

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#3374]
**DocFX Version Used**: 2.39.1

**Steps to Reproduce**:

1.  Have the following metadata section in docfx.json

```
  "metadata": [
    {
      "src": [
        {
          "cwd":"..",
          "files": [
            "packages/Foo.Bar.ObjectDevelopment.*/lib/netstandard2.0/Foo.Bar.ObjectDevelopment.dll",
            "packages/Foo.Bar.AccessControl.*/lib/net461/Foo.Bar.AccessControl.dll",
            "packages/Foo.Bar.ResourceManagement.*/lib/net461/Foo.Bar.ResourceManagement.dll",
            "System/Bla/Bla.csproj"
          ],
          "exclude": [
            "**/obj/**",
            "**/bin/**",
            "_site*/**",
            "**Tests.csproj"
          ]
        }
      ],
      "dest": "obj/api",
      "filter": "apifilter.yml"
    }
  ],
```
2. run `docfx metadata`

**Expected Behavior**:

Metadata should correctly be built.

**Actual Behavior**:

An exception occurs:

> [18-09-05 02:43:10.935]Info:Config file docfx.json found, start generating metadata...
> [18-09-05 02:43:11.012]Info:[ExtractMetadata]Using msbuild C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin as inner compiler.
> [18-09-05 02:43:11.370]Info:[ExtractMetadata]Loading projects...
> [18-09-05 02:43:15.919]Info:[ExtractMetadata]Generating metadata for each project...
> [18-09-05 02:43:21.580]Error:Error extracting metadata for C:/tfs/vac/dev/packages/Foo.Bar.AccessControl.1.1.0/lib/net461/Foo.Bar.AccessControl.dll,C:/tfs/foo/dev/packages/Foo.Bar.ObjectDevelopment.1.0.0-beta10/lib/netstandard2.0/AIS.VAC.Extensibility.ObjectDevelopment.dll,C:/tfs/vac/foo/packages/Foo.Bar.ResourceManagement.1.3.0/lib/net461/Foo.Bar.ResourceManagement.dll,C:/tfs/vac/foo/System/Bla/Bla.csproj: System.ArgumentNullException: Value cannot be null.
> Parameter name: second
>    at System.Linq.Enumerable.Concat[TSource](IEnumerable`1 first, IEnumerable`1 second)
>    at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
> [18-09-05 02:43:21.583]Info:Completed in 10601,179 milliseconds

When I add the line `"references":[]` the metadata section in docfx.sjon, everything works fine:

 ```
  "metadata": [
    {
       ....
      "dest": "obj/api",
      "filter": "apifilter.yml",
      "references" : []
    }
  ],
```

On another note: that `"references"` config section [is not even documented](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#31-properties-for-metadata). What is it for?

**Comment by bitbonk** [comment]
@werwolfby @superyyrrzz I think [this commit](https://github.com/dotnet/docfx/commit/2f424aac516ec883732f1a23ff8d60ef05eb515f) broke it. At least that's when `references` was introduced.

**Comment by werwolfby** [comment]
@bitbonk yes, this is my fault, I'm sorry.
I was pretty sure, that this collection will never be null. It should be always empty at least.
But looks like next commit broke this 😞

**Comment by werwolfby** [comment]
According to the documentation, I'm bad technical writer 😏 , but `references` allow to have additional references when try to create documentation from some assembly. Otherwise roslyn can't recognize some types if it is not located in the same directory.

Real use case was next [next](https://github.com/nuke-build/nuke/issues/117):
* We have some library that reference `System.ValueTuple`
* `System.ValueTuple` is not located in the same directory
* We can download `System.ValueTuple` from NuGet
* Not to generate documentation we should specify additional reference to this `NuGet` from `packages` folder
* `references` property allow us to do it
