### ISSUE TITLE
PDF is not generated under VS 2017 build

### ISSUE THREAD

**Issue by GennadiiSvichinskyi** [dotnet/docfx#3379]
**DocFX Version Used**: 2.39.0

**Template used**: `default`

**Steps to Reproduce**:

1.  Create console project in VS 2017 version 15.7.5
2.  Install docfx and docfx.console
3.  Update docfx.json according projects in my solution
4. Run Build console application
5. Yml files are generated correctly and local site is working and dispalying documentation
6. Install wkhtmltopdf and update PATH variable accordingly. 
7. Add 'pdf' section to the docfx.json
8. Add pdf folder with toc.yml file
9. Rebuild console application

**Expected Behavior**:
pdf files are created under _site_pdf folder

**Actual Behavior**:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Users\gennadii.svichinskyi\.nuget\packages\docfx.console\2.39.0\build\..\tools\docfx.exe" "C:\Work\Thor\src\Hci.LossEvents.ConsUtil/docfx.json" -o "" -l "log.txt" --logLevel "Verbose" -f" exited with code 1.	Hci.LossEvents.ConsUtil	C:\Users\gennadii.svichinskyi\.nuget\packages\docfx.console\2.39.0\build\docfx.console.targets	57	

**log.txt** : {"message":"wkhtmltopdf is a prerequisite when generating PDF. Please install it from https://wkhtmltopdf.org/downloads.html and save the executable folder to %PATH% first. Alternatively you can install it from https://chocolatey.org with `choco install wkhtmltopdf`.","date_time":"2018-09-06T10:05:19.7109117Z","message_severity":"error"}

**Comment by GennadiiSvichinskyi** [comment]
my pdf section
 "pdf": {
    "content": [
      {
        "files": [
          "docfx_web/**.md",
          "docfx_web/**.yml",
          "toc.yml",
          "*.md"
        ],
        "exclude": [
            "**/toc.yml",
            "**/toc.md"
        ]
      },
          {
            "files": [
              "docfx_service/**.md",
              "docfx_service/**.yml",
              "toc.yml",
              "*.md"
            ],
            "exclude": [
                "**/toc.yml",
                "**/toc.md"
            ]
          },
          {
            "files": [
              "docfx_model/**.md",
              "docfx_model/**.yml",
              "toc.yml",
              "*.md"
            ],
            "exclude": [
                "**/toc.yml",
                "**/toc.md"
            ]
          },
          {
            "files": [
              "toc.yml",
              "*.md",
              "docfx_pdf/*"
            ],
            "exclude": [
              "bin/**",
              "obj/**",
              "_site_pdf/**"
            ]
          },
          {
            "files": ["docfx_pdf/toc.yml"]
          }
        ],
        "overwrite": [
          {
            "files": [
              "docfx_web/apidoc/**.md"
            ],
            "exclude": [
              "bin/**",
              "obj/**",
              "_site_pdf/**"
            ]
          }
    ],
    "template": [
      "pdf.default"
    ],
    "dest": "_site_pdf"
  }

**Comment by herohua** [comment]
@GennadiiSvichinskyi, is it possible that you share the repo with us to repro?
