### ISSUE TITLE
azure-docs-pr issue: href resolved to source path

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3397]
![image](https://user-images.githubusercontent.com/17958546/45334523-aced4280-b5ad-11e8-83f4-51056937fc83.png)

**Comment by 928PJY** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2931?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fapp-service-mobile%2Fapp-service-mobile-xamarin-android-get-started-offline-data.page.html

**Comment by 928PJY** [comment]
this is caused by the content issue.
https://raw.githubusercontent.com/MicrosoftDocs/azure-docs-pr/markdig-migration-v3/articles/app-service-mobile/app-service-mobile-xamarin-android-get-started-offline-data.md?token=ARIGkgh95aWXh7Uhm6xpuhSDmzdSy-Vlks5boGiJwA%3D%3D
there are two definitions with the same key, according to the [commonmark spec](https://spec.commonmark.org/0.28/#example-169), we will take the first one, but the first one is not correct, so in v3, the link will be resolved to the source path.
@yishengjin1413 should we report a warning to user?

**Comment by 928PJY** [comment]
same with this issue #3345 
@yufeih, please check-in the by-design changes before closing the issue.
BTW, v2 and v3 use the same Markdig engine, why they have different output?

**Comment by herohua** [comment]
@928PJY , this could be due to some code on service side. Please sync with @fenxu for more details.

**Comment by yufeih** [comment]
@928PJY right, that is also something I suspect

**Comment by yufeih** [comment]
@928PJY accurately detect duplicated reference definitions require some contract changes to Markdig, this change may not have enough justification. 
We already show a link resolve warning in this case, that should be enough for now.
