### ISSUE TITLE
azure-docs-pr issue: link has been escape

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3398]
![image](https://user-images.githubusercontent.com/17958546/45336091-a44c3a80-b5b4-11e8-98e2-025d7ab66fe1.png)

**Comment by herohua** [comment]
v3 behavior is expected. let's just merge the change into impact tool.

**Comment by mingwli** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3535?_a=files
