### ISSUE TITLE
azure-docs-pr: empty index.page.html

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#3399]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3364?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fvirtual-machines%2Fwindows%2Fclassic%2Findex.page.html

There is no content in "articles\virtual-machines\windows\classic\index.md", v2 doesn't output the index.page.html file, v3 does.

Should the empty HTML file be outputted?

**Comment by herohua** [comment]
v3 behavior is expected. Let's just merge the difference into impact tool.
