### ISSUE TITLE
azure-docs-pr: index page handling

### ISSUE THREAD

**Issue by herohua** [dotnet/docfx#3401]
1. Remove "index" in canonical url
2. Replace "index" by "." or remove "index" in resolved link

**Comment by mingwli** [comment]
[Impact PR](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3349?_a=overview)  
The index is trimmed in [TryResolveHref](https://github.com/dotnet/docfx/blob/v3/src/docfx/build/resolve/Resolve.cs#LC70), [PathToRelativeUrl](https://github.com/dotnet/docfx/blob/v3/src/docfx/docset/Document.cs#LC322)  
![image](https://user-images.githubusercontent.com/42199316/45352502-4129ca80-b5eb-11e8-84b8-1375db56107a.png)
`#` is resolved as `self-bookmark`. [AddLinkType](https://github.com/dotnet/docfx/blob/v3/src/docfx/lib/HtmlUtility.cs#LC165)
