### ISSUE TITLE
azure-docs-pr issue: comments in yaml

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3407]
![image](https://user-images.githubusercontent.com/17958546/45400198-cbbb0a00-b67d-11e8-9a63-8886d4b02bf0.png)

![image](https://user-images.githubusercontent.com/17958546/45400238-eee5b980-b67d-11e8-9700-4f1a493114a0.png)

**Comment by yufeih** [comment]
It is technically a valid yaml. I don't see anything to warn here.

**Comment by mingwli** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3535?_a=overview
