### ISSUE TITLE
TableOfContentsInputItem Expanded nullable

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#3412]
bool with `DefaultValueHandling = DefaultValueHandling.Ignore` will lead to missing expanded field on serialization.  
change it to nullable.  
https://review.docs.microsoft.com/en-us/new-hope/specs/ops/toc_schema_validation?branch=master  
![image](https://user-images.githubusercontent.com/42199316/45414258-80205480-b6ad-11e8-8d3b-f405e0d53b75.png)

**Comment by yufeih** [comment]
This should be as design. `{ expanded: false }` should be equivalent to `{ }`
