### ISSUE TITLE
Example main.css Has Vanished

### ISSUE THREAD

**Issue by txwizard** [dotnet/docfx#3416]
**DocFX Version Used**:  N/A

**Template used**: (`default` or `statictoc` or contain custom template) N/A

**Steps to Reproduce**:

1. Navigate to https://github.com/dotnet/docfx/blob/dev/Documentation/template/styles/main.css.

**Expected Behavior**: Display the main.css sample mentioned in #127.

**Actual Behavior**: The GitHub 404 page is returned.

**Comment by superyyrrzz** [comment]
Thank you for reporting this. The URL in the comment need update to:

Sample from docfx: https://github.com/dotnet/docfx/blob/200c02e53975d24989fd9957219a9c8e1e88ad60/Documentation/custom_template/styles/main.css
and https://github.com/dotnet/docfx/blob/200c02e53975d24989fd9957219a9c8e1e88ad60/Documentation/docfx.json#L68
