### ISSUE TITLE
Build PDF version

### ISSUE THREAD

**Issue by YTsalko** [dotnet/docfx#342]
Hi,
Is there any plans when PDF building will be supported?

**Comment by FlorianRappl** [comment]
I hope that this will be addressed. However, currently I see no interaction going on here. #416 is in my opinion a generalized version of this topic (once you can provide a custom renderer, you could build a PDF renderer; or at least output TeX which produces beautiful documents).

**Comment by ikourfaln** [comment]
Yeh, we need this feature, sometimes client needs docs as PDF.

**Comment by bitbonk** [comment]
A PDF or any standalone document that does not require a webserver is highly needed.

**Comment by sandorfr** [comment]
There's hope : https://github.com/dotnet/docfx/issues/1336#issuecomment-290350575

**Comment by vicancy** [comment]
Please refer to https://github.com/dotnet/docfx/issues/1336#issuecomment-302007379 to test the new feature
