### ISSUE TITLE
Automatically redirect from index.html to another file in documentation.

### ISSUE THREAD

**Issue by ElektroMech** [dotnet/docfx#3421]
I don`t want to use main homepage(index.html). 
Is it possible to redirect the user to a specific documentation page?

**Comment by igregr** [comment]
I am also interested if it's possible.

**Comment by herohua** [comment]
@ElektroMech , @igregr , have you tried [this technique](https://www.w3.org/TR/WCAG20-TECHS/H76.html)?

FYI @superyyrrzz @928PJY

**Comment by igregr** [comment]
@herohua : I solved it via a mod_rewrite in .htaccess file, which is a similar approach to your proposed technique. I was more interested in a configuration option in docfx.json file (it seems to be a cleaner solution for me - docfx serves a custom homepage and it's not necessary to send a redirect back to the user), but your technique or rewriting works as well. Hence, a proper solution woud be "nice to have" but I am ok with your technique or mod_rewrite.

**Comment by rahul7720** [comment]
You can place the below code on the main index page.

```
---
redirect_url: /articles/documentation/introduction  
---
```

**Comment by CaseyHofland** [comment]
Quick note for everyone, make sure you've updated your docfx version.

Run:
```cli
dotnet tools update -g docfx
where docfx
// delete any docfx.exe from your PC that aren't under *\.dotnet\tools\
```
