### ISSUE TITLE
Impact of migrating from v2 to v3

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3439]
1. Files changed:

~~- *docfx.json*: every *docfx.json* in each docset will be removed. In replace, there will be *docfx.yml* in the repository root.~~ (removed as we will temporarily keep docfx.json)
- *.openpublishing.publish.config.json*: a new config `"use_docfxv3": true`.
> some configs in the *.openpublishing.publish.config.json* is included in the `docfx.yml`, we can remove them.
- *file with `redirect_url` yam-header*: migration tool will pick those files up and convert them to redirection rules, and those files will be removed.

2. More build warnings/errors: see https://github.com/dotnet/docfx/issues/3838

**Comment by yufeih** [comment]
@928PJY , should we use a document to track these differences over an issue?

**Comment by herohua** [comment]
@928PJY : echoing @yufeih 's point, a documentation would be better and it could as well serve as a reference to content team when they are (or after) onboarding to v3.

**Comment by herohua** [comment]
I've created a wiki in our teams channel to cover all this info.
