### ISSUE TITLE
 System.ArgumentNullException

### ISSUE THREAD

**Issue by keydon** [dotnet/docfx#344]
### Functional impact

Generating the docs fails
### Minimal repro steps

I am running it against our huge codebase, no idea which file it does not like. 
The error message does not provide enough information to tailor you guys a minimal demo.
### Expected result

No hard errors.
### Actual result

`System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: symbol
   bei Microsoft.DocAsCode.Metadata.ManagedReference.DefaultFilterVisitor.CanVisitAttribute(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.GetAttributeInfo(ImmutableArray`1 attributes)
   bei Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
### Further technical details

Full Log available here: http://pastebin.com/i7gatA0W
docfx-version: 1.9.4.60519

**Comment by chenkennt** [comment]
Hi @keydon , if your code base is a public repo, could you share it with us so we can try to repro

**Comment by keydon** [comment]
Hi @chenkennt, sorry, it's not public. But I could send you the troublemaker if we can narrow it down.

**Comment by vwxyzh** [comment]
related code:
```c#
from attr in attributes
where !(attr.AttributeClass is IErrorTypeSymbol)
where FilterVisitor.CanVisitAttribute(attr.AttributeConstructor)
```
But I can't understand why there is an attribute with null constructor.

**Comment by vicancy** [comment]
Hey @keydon any updates on the troublemaker?
