### ISSUE TITLE
Feature Request: Live Reload

### ISSUE THREAD

**Issue by jaredcnance** [dotnet/docfx#3440]
**DocFX Version Used**: 2.38.1.0

It would be awesome if live reload were supported during development. This would require spinning up a live-reload server similar to webpack-dev-server, ember-cli and many others. For a first iteration, it would be great if the page would reload when one of the content files changes. Eventually, I think it should be able to also reload on changes to the actual source files that build the metadata.

**Comment by yufeih** [comment]
Looks like `docfx watch` #2297. Our current scope is live-reload on conceptual documents. Live reload on source files may not scale well for a large codebase.

**Comment by jaredcnance** [comment]
Awesome, thanks. I’ll go ahead and close this since it’s a duplicate.
