### ISSUE TITLE
docfx legacy configuration clean up

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3449]
1. legacy configuration like `source base path`, `site base path`
2. server configuration like `product name`
3. legacy switch like 'follow redirection', `pdf template`

**Comment by mingwli** [comment]
put `source base path` & `site base path` into `legacy config`, since they appear duplicated in `Config` & `DocumentIdConfig`.  
Currently we only deal with single-docset repo, so `product` and `name` stay as `Config`'s immediate children.
