### ISSUE TITLE
Special characters mess up nav bar and header but no errors in build

### ISSUE THREAD

**Issue by Aory88** [dotnet/docfx#3454]
**DocFX Version Used**: 2.35.0.0

**Template used**: (`default` or `statictoc` or contain custom template)
custom

**Steps to Reproduce**:

1.  Create a page
2.  Have this exact special character '…' within the content
3.  Do a build and serve

**Expected Behavior**:
Should display the page with left/right nav, header populated or show an error during build

**Actual Behavior**:
Does not show error during build, but the specific page is not populated or shown for left/right nav + header.

**Comment by herohua** [comment]
@Aory88 , can you give us a sample page, or a sample repo to repro the issue?
