### ISSUE TITLE
Support multiple uid within one SDP

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#3457]
https://docs.microsoft.com/en-us/dotnet/api/system.string.endswith?view=netframework-4.7.2 https://docs.microsoft.com/en-us/javascript/api/@azure/cosmos/?view=azure-node-latest

**Comment by yufeih** [comment]
Right now SDP only has one root level uid. In the above example, method overload shares the same `uid`, node sdk is an aggregation page, each type has its own sub page.

**Comment by superyyrrzz** [comment]
For overload, they have different uid like `System.String.EndsWith(System.String)`, `System.String.EndsWith(System.String,System.StringComparison)` in the same page.

For the node sdk, you can scroll down to the end of page, and see "Function Details" who has its own definition there.
