### ISSUE TITLE
docfx support bilingual

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3465]
The bilingual content are totally not same with loc content, they should not be exposed to contributor, but we still need them to be used for building and publishing.

- [x] 1. Put bilingual content in one specified folder/branch
- [x] 2. One configuration switch to enable/disable  bilingual
- [x] 3. Make sure the bilingual content should not be exposed to public repo and contributor(repo syncer)
- [x] 4. Resolve sxs content contributor with non-sxs files' commits

**Comment by OsmondJiang** [comment]
I am waiting for @yufeih 's git commit changes for point 4

**Comment by OsmondJiang** [comment]
And also loc repo markdig migration

**Comment by yufeih** [comment]
Working on it
