### ISSUE TITLE
Add generation datetime

### ISSUE THREAD

**Issue by fidou** [dotnet/docfx#3468]
Hi,

this is just a question: I would like to run the metadata and build process everyday and would be nice to display the datetime of the generation on the footer or header or the site. is there an easy way to achieve this without having to export the template and change it? 

**DocFX Version Used**: 2.39.2
**Template used**: default

**Comment by yufeih** [comment]
Is this datetime intended for users visiting your site, or is it just for debugging, tracking purposes.

If the latter, you can simply generate a dedicated page or file (like `/update-time.html`) without updating docfx and serve them as a static file.

**Comment by fidou** [comment]
Hi
thanks. It would be for users visiting the site. 
how would generating a dedicated page work? does this require a postprocessor?

**Comment by fidou** [comment]
this issue can be closed. I will add a step to change the global.json as part of the build

**Comment by yufeih** [comment]
Glad you solved your problem
