### ISSUE TITLE
Missing enum values

### ISSUE THREAD

**Issue by Franki1986** [dotnet/docfx#3472]
hello,

I am trying to get the numeric values of enumerations listed in the documentation but I cannot find how to do this.

**Comment by superyyrrzz** [comment]
Seems like some template custom work on [enum partial template](https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/partials/enum.tmpl.partial). Here is some document: https://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html

**Comment by Franki1986** [comment]
I will have a look, thanks!

**Comment by manuc66** [comment]
@Franki1986 did you manage to configure it, if yes could you share part of your solution ?

Thanks
