### ISSUE TITLE
Fix docfx deployment process

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3473]
The deployment process is broken:

- [x] No notification on deployment failure
- [x] Too many pipelines: _docfx-impact-ci_, _docfx-impact-cd_, _docfx-cd_
- [x] Some ad-hoc powershell deployment scripts are not checked into repo, they are changed without PR and PR validation
- [x] Impact tests not using a service account
- [x] ~~Checkins to impact test repo does not have PR validation~~

---

<img width="454" alt="screen shot 2018-10-08 at 10 07 06 am" src="https://user-images.githubusercontent.com/511355/46589941-fa43cd80-cae1-11e8-994c-719487f43467.png">

**Comment by mingwli** [comment]
Added in VSTS docfx-deploy Build CI, related PRs below: 
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/5372?_a=overview
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/5381?_a=overview
