### ISSUE TITLE
Error in Styling of XML

### ISSUE THREAD

**Issue by xxcuratorxx** [dotnet/docfx#3478]
**DocFX Version Used**:  2.36

**Template used**: (`default` or `statictoc` or contain custom template)
statictoc and default
**Steps to Reproduce**:

1. Docfx init
2. Add two code snippets, e.g., by "```" to index.md
3. build and open index.html

**Expected Behavior**:
Both XML Code Snippets are colored correctly
**Actual Behavior**:
Second XML Code Snippets in colored strange
Xml One

```
<?xml version="1.0" encoding="utf-16" standalone="yes"?>
<level version="1.0">
  <sublevel>
    <subsublevel name="FieldValue 1" dtype="Text" mandatory="false" readonly="false" visible="true" />
    <subsublevel name="FieldValue 2" dtype="Text" mandatory="false" readonly="false" visible="true" />
    <subsublevel name="FieldValue 3" dtype="Text" mandatory="false" readonly="false" visible="true" />
  </sublevel>
</level>
```

Xml Two

```
<?xml version="1.0" encoding="utf-16" standalone="yes"?>
<level version="1.0">
  <sublevel>
    <subsublevel name="FieldValue 1" dtype="Text" mandatory="false" readonly="false" visible="true" />
    <subsublevel name="FieldValue 2" dtype="Text" mandatory="false" readonly="false" visible="true" />
    <subsublevel name="FieldValue 3" dtype="Text" mandatory="false" readonly="false" visible="true" />
    <subsublevel name="FieldValue 4" dtype="Text" mandatory="false" readonly="false" visible="true" />
  </sublevel>
</level>
```

**Comment by superyyrrzz** [comment]
It's a rendering issue. DocFX's theme uses [highlight.js](https://highlightjs.org/) to colorize code, which first infers from content what language the code is, then colorize the code using the language's rule. The prolblem is, the infered language is not accurate, depending on the actual code content. To solve this, you can explicitly specify what language your code is:
````
``` xml
<level> ... your xml cod here ... </level>
```
````

**Comment by xxcuratorxx** [comment]
Thanks very much, that worked for me!
