### ISSUE TITLE
Merge multiple xrefmap.json under the same public share base path

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#3487]
Background:
 - Docfx v3 build would like to consume xrefmap.json instead of xref service due to performance improvement.
 - There would be multiple depots under the same public share base path, which means multiple xrefmap.json files, but we can only get the highest priority xrefmap.json back. So we need to merge the multiple xrefmap.json together somewhere for docfx build to consume.

Decision:
 - The merge is based on shared base path basis. We do NOT consider the case users want to access XRef map for a particular product (ASP.NET for example) at this time.

Short-term solution:
 - Do NOT support local build scenario.

 - In a build, OPS would gather all the xrefmap.json with the same share base path, download them to local disk, merge them and then pass the merged file into DocFX v3.

 - There will be NO upload of the merged file.

Long-term solution:
 - If we'd like to support local build scenario, we may need to set up a URL for end users to download the merged XRef map to their local machine before local build.
  - ~~The download step will be part of `docfx restore`(it is part of restore already)~~
  - The URL needs to support auth (e.g. unauthorized users cannot access internal version of XRef map), the performance of accessing the URL should be good enough.
    - An idea is to build a scheduled job merging all the xrefmap.json for the same share base path and store it somewhere. Need further discussion to decide where the job should be located (DHS? XrefService?).

**Comment by herohua** [comment]
We now track the remaining work here: https://dev.azure.com/ceapex/Engineering/_workitems/edit/107151
