### ISSUE TITLE
Dependency map with detailed classification

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#3492]
v2 has several dependency types in generated dependency map, see: https://dotnet.github.io/docfx/tutorial/incrementalbuild/advanced_report_dependency.html#reserved-dependency-types Some consumer of the dependency map need to know detailed dependency type. e.g. For `include`, we cannot tell whether it's `file inclusion` or `code snippet` for now.

v3 should consider a more detailed dependency type.

**Comment by yufeih** [comment]
Consider supporting dependency map in v3 non-legacy

**Comment by OsmondJiang** [comment]
Where will the non-legacy dependency map be used to? @superyyrrzz ?

**Comment by superyyrrzz** [comment]
@OsmondJiang  A requirement from triple crown loc need to hand off/hand back files with dependencies at the same time. They don't want partially translated token or path/module.

PR preview should also want the dependency map, while it doesn't care about the classification.

**Comment by yufeih** [comment]
For PR comments I'd like to have a dedicated contract other than dependency map. Something similar to publish reports. Like you mentioned, it does not care about classification.

For triple crown loc, It is still too early for v3 to have a design on that. But it should also be something that is specifically for loc, other than just giving them dependency map.
