### ISSUE TITLE
Contributors calculation logic

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#3500]
The logic to extract author from contributors is wrong from impact test. e.g. For commit history:
- userA
- userB
- userA

The contributors is [userA, userB]. The expect author should be userA, but the actual author is userB. The current logic to fetch the last contributor as author is wrong: https://github.com/dotnet/docfx/blob/v3/src/docfx/build/metadata/ContributionInfo.cs#L98

@yufeih Can you help fix this? I can contribute a [test case](https://github.com/dotnet/docfx/commit/9aca06029500cb4a66c65a7de59cc426460a6444) but cannot find a elegant way to fix it on current logic...

**Comment by yufeih** [comment]
sure
