### ISSUE TITLE
Cannot find build (and others) in docfx.yml

### ISSUE THREAD

**Issue by Foxtrek64** [dotnet/docfx#3524]
**DocFX Version Used**: '3.0.0-alpha-00414-994b9fb69'

**Template used**: `default`

Going to break from the default form. When building my site against V3, my CI spits out the following:
```
unknown-field docfx.yml(0,0): Could not find member 'build' on object of type 'Config'.
unknown-field docfx.yml(0,0): Could not find member 'dest' on object of type 'Config'.
unknown-field docfx.yml(0,0): Could not find member 'markdownEngineName' on object of type 'Config'.
unknown-field docfx.yml(0,0): Could not find member 'template' on object of type 'Config'.
Done in 1.36s
```
This is echoed in my `gh-pages` branch in the build.log file:
```
["warning","unknown-field","Could not find member 'build' on object of type 'Config'.","docfx.yml","build"]
["warning","unknown-field","Could not find member 'dest' on object of type 'Config'.","docfx.yml","dest"]
["warning","unknown-field","Could not find member 'markdownEngineName' on object of type 'Config'.","docfx.yml","markdownEngineName"]
["warning","unknown-field","Could not find member 'template' on object of type 'Config'.","docfx.yml","template"]
```

**Steps to reproduce**
[My docfx.yml](https://github.com/LuzFaltex/docs/blob/master/docs/docfx.yml) file was built by manually converting the existing .json version to yaml format. You can see the [original json config](https://github.com/LuzFaltex/docs/blob/master/docs/docfx.json) in the repository.

**Brief aside (what I tried to fix it)**
When I first saw the error, I took it to mean that I needed an entry called `config` in docfx.yml, so I made that and put those four items underneath it. However, this resulted in the same error.

**Re-rail**
I've dug around but I cannot find any docfx.yml samples and the documentation hasn't yet been updated to V3 (which makes sense, it's not a release build). What do I need to change in my docfx.yml file to make this work?

**Comment by Foxtrek64** [comment]
docfx is spitting out empty html pages. I'm wondering if this is to do with the lack of defining a default template. What is the new way of defining templates (so I can implement the light-dark-theme template at the least), and what should I look at for diagnosing the empty document issue?

The output from build.log is rather unhelpful. Is there a debug switch I can add to the build command to get more verbose logging?

Don't mind the microsoft references. I took the contribution guide and dropped it in so I could have some sample content.
```
["warning","heading-not-found","The first visible block is not a heading block with `#`","contribute/includes/contribute-how-to-pull-requests-apex-automation.md"]
["info","at-uid-not-found","Cannot find uid 'microsoft.com' using xref '@microsoft.com'","contribute/index.md"]
["info","at-uid-not-found","Cannot find uid 'microsoft.com' using xref '@microsoft.com'","contribute/how-to-write-workflows-major.md"]
["warning","heading-not-found","The first visible block is not a heading block with `#`","contribute/includes/contribute-how-to-write-workflows-major-change-definition.md"]
["warning","heading-not-found","The first visible block is not a heading block with `#`","contribute/includes/contribute-how-to-write-workflows-pull-request-processing.md"]
["warning","bookmark-not-found","Cannot find bookmark '#table-wrapping' in 'contribute/how-to-write-use-markdown.md'","contribute/how-to-write-use-markdown.md"]
```

**Comment by yufeih** [comment]
Just to set expectation here, docfx 3 pre-release is currently a work in progress, and it is a release with some breaking changes around config and template. Right now the team is busy working on conceptual document feature parity with https://docs.microsoft.com, the current output is raw JSON without any template applied.

**Comment by yufeih** [comment]
Close this as we are still in early development.
