### ISSUE TITLE
Inheritance and Syntax implied inheritance don't match

### ISSUE THREAD

**Issue by StewMcc** [dotnet/docfx#3525]
**DocFX Version Used**: 
v2.40.0
**Template used**: (`default` or `statictoc` or contain custom template)
`statictoc`
**Steps to Reproduce**:
Unsure keeps changing...
1. ` docfx --serve` using source *.cs files
2.  clean everything up and run command again, out put is different.

**Expected Behavior**:
syntax of `public class AutoLoader : MonoBehaviour` will show inheritance as `MonoBehaviour` every time.
**Actual Behavior**:
Shows inheritance as `System.Object` sometimes, and as `MonoBehaviour` others

**notes**

The `MonoBehaviour` class is not an included `.cs` file class. I am mainly confused as to how it works sometimes, falls back to syntax inherited class, whereas other times it falls back to `System.Object`. 

Mainly curious as to what the expected result would be?

**Comment by herohua** [comment]
@StewMcc could you provide a minimum project to repro the issue?
