### ISSUE TITLE
TOC broken with duplicate level2/3 titles

### ISSUE THREAD

**Issue by xen2** [dotnet/docfx#356]
If I create a document with titles such as
```
# Release note
## Version 1.6
### Enhancements
### Issues fixed
## Version 1.5
### Enhancements
### Issues fixed
```

The TOC on the right side will mix up links with similar titles.
They will all be "highlighted" together, and clicking any of them will point to the same version.

This is because it generates the same anchor/hashtag (in thise case, #issues-fixed)

Example:
http://doc.xenko.com/latest/ReleaseNotes.html#issues-fixed

Somehow, it should generate unique anchor names if there are duplicate level2/3 titles within the same page.

**Comment by qinezh** [comment]
Do you use the latest version of docfx? It should be fixed now....

**Comment by xen2** [comment]
Sorry my bad, I will try. Closing for now and will reopen if it happens again.
