### ISSUE TITLE
Update docfx deploy to test against published docfx.exe

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3561]
Our deployment test currently test against source code using `dotnet run`, it should test against `docfx.exe` using:

```powershell
dotnet pack $PATH_PATH
dotnet tool install -g docfx --add-source $PACK_PATH --tool-path $TOOL_PATH

$env:PATH = $TOOL_PATH
docfx build
```

**Comment by mingwli** [comment]
[VSTS PR](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/6047?_a=overview)
