### ISSUE TITLE
Emit meta tags in docfx output

### ISSUE THREAD

**Issue by shirhatti** [dotnet/docfx#3579]
Is there a way in docfx (conceivably through yaml headers and/or docfx.json) to emit additional meta tags in generated output?

Specifically, we have some content in our docset- https://github.com/microsoftdocs/iis-docs that we want to prevent indexing from search engines
```html
<meta name="robots" content="noindex">
```

**Comment by yufeih** [comment]
You can put it in yaml header, it is a feature of https://docs.microsoft.com, currently not in docfx.
```
---
ROBOTS: NOINDEX,NOFOLLOW
---
```
