### ISSUE TITLE
Cannot use cross reference services (xrefService) behind Proxy Server

### ISSUE THREAD

**Issue by tibel** [dotnet/docfx#3597]
**DocFX Version Used**: 2.40.1

**Template used**: `statictoc`

**Steps to Reproduce**:

1. build machine is behind corporate proxy server
2. add `"xrefService": [ "https://xref.docs.microsoft.com/query?uid={uid}" ]` to `doxfx.json`
3. build documentation

**Expected Behavior**:
Cross references should be resolved.

**Actual Behavior**:

[18-11-08 03:02:35.900]Info:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.UpdateContext]Unable to resolve uid (System.AttributeUsageAttribute) from https://xref.docs.microsoft.com/query?uid={uid}, details: An error occurred while sending the request.

Is there something I can do to get a more detailed error message?

**Comment by herohua** [comment]
@superyyrrzz , can you help reply possible workarounds here?

**Comment by superyyrrzz** [comment]
@tibel DocFX does not support proxy server configuration for now. Could you try some proxy client software to forward local machine network globally to proxy server? e.g. https://www.proxifier.com/ (I just googled it and have not used it).

**Comment by tibel** [comment]
@superyyrrzz Thanks for the hint. I used https://www.telerik.com/fiddler to track it down. Our company proxy requires authentication, so DocFX gets a http 407 response.

Maybe the console logging output of DocFX can be extended to show more info on what went wrong.
