### ISSUE TITLE
Update to dotnet RTM (was RC2)

### ISSUE THREAD

**Issue by stuartleeks** [dotnet/docfx#361]
### Title

Update to dotnet RC2
### Functional impact

To stay current, this project should be updated to the dotnet RC2 bits. I noticed that the [Getting Started](https://docs.asp.net/en/latest/getting-started.html#install-the-net-version-manager-dnvm) page on the ASP.NET site that is linked to from the README now only refers to the RC2 bits for dotnet with the new CLI, rather than the dnvm-based RC1 bits.

**Comment by FancyAwesomeRichard** [comment]
Bump, though it'd be dotnet core RTM now.

**Comment by jskeet** [comment]
Or better yet now, the preview 2 dotnet CLI (.NET Core RTM) bits...

**Comment by jskeet** [comment]
Any updates on this? The requirement to install DNVM feels worrying.
Presumably this is because dotnet cli doesn't have the equivalent of "installing a tool"?

**Comment by chenkennt** [comment]
We do have an experimental build of CLI version (in cli branch), the main reason we haven't retire DNX is as @jskeet said, there is no equivalent of "dnx command" in CLI right now. We'll keep an eye on the status of CLI and keep you updated once we decide a date to upgrade.

**Comment by stuartleeks** [comment]
Can you give more details on what functionality it is that you're missing from dnx in the RTM bits?

**Comment by qinezh** [comment]
@stuartleeks Such like `dnu commands install docfx`

**Comment by adrienjt** [comment]
Is it possible to build docfx.exe and its DLL's from source without DNVM? If yes, how? Could the README be updated?
I was using the 2.3 release, but I need to build dev to address my issue #604.

**Comment by qinezh** [comment]
@adrienjt you can run `build nondnx` in command line,or open NonDNX.sln in Visual Studio and build it.

**Comment by vicancy** [comment]
using dotnet now...
