### ISSUE TITLE
locale is appended to absolute url during resolve in loc docset build

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3620]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/6060?_a=files&path=%2Fsource%2Fazure-docs-pr.ja-jp.output%2Fazure%2Faks%2Fingress-internal-ip.page.html

**Comment by OsmondJiang** [comment]
@fenxu  and @herohua , seems that's a bug in v2, if it's a absolute path, we should append locale to it?

**Comment by fenxu** [comment]
@OsmondJiang @herohua I can't remember the details. However, it seems like by design. Otherwise, the link on hosting will jump to other locale set by browser.

**Comment by OsmondJiang** [comment]
it should be by design, so close this issue now.
