### ISSUE TITLE
Generated documentation's summary is missing 

### ISSUE THREAD

**Issue by dquilong** [dotnet/docfx#3634]
At the first moment I was generating the documentation from a project and everything was working. Now, I have moved this project to a dll ( to a nuget package) and the generated documentation is fine except for the summary, which is missing.

**DocFX Version Used**:  docfx console 2.40.2

**Template used**: `default`

**Steps to Reproduce**:

1. Generate a dll documentation

**Expected Behavior**:
Methods' summary should be desplayed

**Actual Behavior**:
Methods' summary is missing

**Comment by herohua** [comment]
@qinezh , if we generate doc from DLL, do we also need the XML files to output description?

FYI @superyyrrzz

**Comment by qinezh** [comment]
@herohua Yes we need the XML files.

**Comment by herohua** [comment]
Hi @dquilong , in order to generate summary from DLL, DocFX also needs XML files that are also produced by compiler (because DLL strips out the summary and other stuffs).

**Comment by dquilong** [comment]
Thank you very much! it worked!
