### ISSUE TITLE
Fix Chocolatey Package

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#3636]
[Chocolatey Package for 2.40.2](https://chocolatey.org/packages/docfx/2.40.2) has failed validation:

> * Binary files (.exe, .msi, .zip, etc) have been included without including a LICENSE.txt file. This file is required when including binaries [More...](https://github.com/chocolatey/package-validator/wiki/LicenseFileMissing)
> * Tags (tags) are space separated values for referencing categories for software. Please include tags in the nuspec as space separated values. [More...](https://github.com/chocolatey/package-validator/wiki/TagsNotEmpty)
> * Binary files (.exe, .msi, .zip) have been included without including a VERIFICATION.txt file. This file is required when including binaries [More...](https://github.com/chocolatey/package-validator/wiki/VerificationFileMissing)

**Comment by herohua** [comment]
@928PJY to check with Chocolatey

**Comment by 928PJY** [comment]
please reference to v2.40.4
