### ISSUE TITLE
Node module resolution 

### ISSUE THREAD

**Issue by dinoreborn** [dotnet/docfx#3642]
There isnt a Node module resolution algorithm should be able to correctly resolve inter-module references.

Suppose my folder structure should be as follows:

<some_path_from_root (optional)>

              node_modules

                           @packagename

                                         table

                                                       table.d.ts

                                         matrix

                                                       matrix.d.ts

Assuming DocFx uses TS to parse the comments and obtain typings then this behavior should be controlled by the some TS option:

"moduleResolution": "node"

Is there something to handle this?

**Comment by superyyrrzz** [comment]
Are you follow this document to generate document? https://dotnet.github.io/docfx/tutorial/universalreference/gen_doc_for_ts.html

If so, I might transfer this issue to https://github.com/docascode/type2docfx.
