### ISSUE TITLE
Task List Support?

### ISSUE THREAD

**Issue by reecebradley** [dotnet/docfx#3643]
**DocFX Version Used**: v3

**Template used**: default

**Steps to Reproduce**:

using syntax 
```
1. [X] Step one
1. [ ] Step two
```

**Expected Behavior**:
Should render out task list

**Actual Behavior**:
does not

**Question**

Will this get supported?
[TaskListSpecs](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/TaskListSpecs.md)

**Comment by yufeih** [comment]
This is unlikely to be supported. Task list is a stateful control to be useful, when you toggle the completion state of an item, the state needs to be persisted somewhere.

**Comment by superyyrrzz** [comment]
Keep track in #3387 for task lists extension support.
