### ISSUE TITLE
Project could not be lodaded (unicode)

### ISSUE THREAD

**Issue by MeikelLP** [dotnet/docfx#3651]
I'm using Unity3D 2018.3.0b10 and it's generating the .sln & .csproj files. Docfx somehow can not load these generated files due a unicode issue?

I have Visual Studio Enterprise 2017 + .NET Core installed.

**DocFX Version Used**: 2.40.1.0 (via chocolatey)

**Template used**: `default`

**Steps to Reproduce (probably)**:

1. Create a new Project with Unity.
2. Maybe create a script or two
3. Let unity generate the .sln and .csproj files
4. Try to load them via `docfx` or `docfx metadata`

**Expected Behavior**:
* Generates api docs

**Actual Behavior**:
* Generates nothing

```
[18-11-20 08:46:00.711]Warning:[ExtractMetadata](xyz.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'xyz.csproj' with message: The project file could not be loaded. Keine Unicodebyte-Reihenfolgemarkierung. Es kann nicht zu Unicode gewechselt werden.
```

(sorry the message is partialy german)

**Comment by superyyrrzz** [comment]
@MeikelLP Could you provide a sample project to help reproduce this issue?

**Comment by MeikelLP** [comment]
Sadly I cannot any longer as I switched the language of the OS to English to avoid any issues with Unicode, which seems to still be a valid problem with many programs...

**Comment by superyyrrzz** [comment]
@MeikelLP I do some tests with my small Chinese project, but all works fine... Close this for now. We can reopen this if it happens again.
