### ISSUE TITLE
DocFX Documentation Missing for Event Parameters

### ISSUE THREAD

**Issue by nabeelriaz1001** [dotnet/docfx#3664]
**DocFX Version Used**: 
I am using the nuget package, docfx.console 2.40.1
**Template used**: (`default` or `statictoc` or contain custom template)
default

I'm using DocFX framework to generate documentation for my .NET DLL. It gives a great experience with customization. However I'm just stuck with the fact that my public VB Events are included in documentation but the information related to parameters is missing.

For example for a method the documentation looks like:

MethodName

Some Description...

Declaration

Declaration Information

Parameters

A table listing all parameters, with type, name and description columns

Any solution or workaround would be highly appreciated.

**Expected Behavior**:
For events with parameters, the table listing all parameters should be showing. 
**Actual Behavior**:
For events with parameters, the table listing all parameters along with information is missing.

**Comment by azazlhr** [comment]
Following is equivalent post on SO. Though it's not answered yet.

https://stackoverflow.com/questions/53427834/docfx-documentation-missing-for-event-parameters

**Comment by superyyrrzz** [comment]
@nabeelriaz1001 Actually this information is shown, but not in the same page. For example, you can see `eat` event in [this page](http://docascode.github.io/docfx-seed/api/CatLibrary.ICat.html?q=event). Although parameters don't show, you can click on the Type `EventHandler` to see the parameters in this delegate page, where you can know its parameters are `object sender, EventArgs e`.
