### ISSUE TITLE
Improve docs configuration migration tool 

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3675]
For docs configuration migration tool, we still need to:
  - [x] make sure the configuration generated by migration tool consistent with docfx latest configuration schema, @mingwli is going to add this tool to impact CI.
  - [x] cover the case that the redirection defined in file's yml header?
  - [x] how to do localization configuration migration?
  - [x] route/monikers config feasibility (gather cases)

cc @yufeih

**Comment by mingwli** [comment]
1. [integration into impact](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/6606?path=%2Fscripts%2Fdocfx-config%2Fdocset-config-provider.js&discussionId=44930&_a=overview)
2. [resolve redirection from yaml header](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.MigrationTool/pullrequest/6692?_a=files)

**Comment by mingwli** [comment]
4. [implement moniker range migrator](https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.MigrationTool/pullrequest/6926?_a=overview)

**Comment by OsmondJiang** [comment]
for now, localization config is migrated based on localization configuration, so need extra steps, so close this issue now.
