### ISSUE TITLE
Lack of support F# v4.5 language features (such as match! keyword) - dependency on the old FSharp.Compiler.Services version

### ISSUE THREAD

**Issue by ArtemyB** [dotnet/docfx#3679]
**DocFX Version Used**: 2.40.4

**Template used**: `default`

**Steps to Reproduce**:

1. Create (or find) an F# library project (using F# 4.5 language version) which contains computation expression with `match! ... with ...` construct in its' source code.
I guess, [this repo](https://github.com/surban/docfx-fsproj) could be used as the foundation for the project. It remains only to add somewhere to its sources this code snippet:
```fsharp
let a1 = async {
        printfn "Async 1"
        return 1
    }

do
    async {
        printfn "Async 2"
        match! a1 with
        | 1 ->
            printfn "Call Async 1 from Async 2"
        | _ -> ()
            return ()
    } |> Async.Start
``` 
2. Generate DocFx-documentation for this project.
3. Watch the result. 

**Expected Behavior**:

DocFx documentation should compile successfully.

**Actual Behavior**:

An error occurs during documentation generation:
```
System.Exception: F# compiler reported errors in <Source-project-name>.fsproj:
<Source-file-name>.fs(<number-of-line-with-match!-keyword>): Identifiers followed by '!' are reserved for future use
```
__________________

As I understand, the problem is in using by [Microsoft.DocAsCode.Metadata.ManagedReference.FSharp](https://github.com/dotnet/docfx/tree/dev/src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp) an old version of [F# Compiler Services](http://fsharp.github.io/FSharp.Compiler.Service/index.html), which doesn't support F# 4.5 features (such as `match!` keyword).

**Comment by superyyrrzz** [comment]
F# feature is from community contribution. Mark this as `help-wanted` first.
