### ISSUE TITLE
Document how to setup xrefService with generated output

### ISSUE THREAD

**Issue by StephenHodgson** [dotnet/docfx#3681]
**DocFX Version Used**:  Version 2.40.4

**Template used**: default

I really like the xrefService that `docs.microsoft.com` has for adding references for the BCL data types via `"https://xref.docs.microsoft.com/query?uid={uid}"`

I was wondering if the generated docfx output already has that service built in, and if so, what would be the url for it?

I tried a few different paths to try and access it, but no luck.

The [docs didn't help much here either](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#324-xref-service-url-pattern).

Just a side note, I am using github pages to publish the generated docs and output.

**Comment by superyyrrzz** [comment]
Hi @StephenHodgson , the document you referenced to is about how to configure `xrefService` in docfx.json with some advance usage. Not about how to set up an xref service. So I am also confused about your proposed PR. Could you please share more information about how you use it and what `.htaccess` is used for?

**Comment by StephenHodgson** [comment]
[`htaccess` is short for Hypertext Access](http://httpd.apache.org/docs/2.2/configuring.html#htaccess), and is a configuration file used by Apache-based web servers that controls the directory that it "lives" in--as well as all the subdirectories underneath that directory.  Since `.htaccess` files are read on every request, changes made in these files take immediate effect.

The section in the docs describe how to setup the `.htaccess` to properly serve up the xref service by modifying the file with the described pattern, which it wasn't immediately obvious what it was describing.

**Comment by superyyrrzz** [comment]
> The section in the docs describe how to setup the .htaccess to properly serve up the xref service by modifying the file with the described pattern. It wasn't immediately obvious what it was describing.

Actually not, it is about how to configure docfx.json, like:
```json
"build": {
    ...
    "xrefService": "http://{%test%}.contoso.com/?uid={uid}|> removeHost"
    ...
  }
```
Currently, the main usage of this is for docs.microsoft.com site. This is a client side configure, instead of how to serve up xref service. I am not sure whether you get its usage correctly.

**Comment by StephenHodgson** [comment]
Where would `test` be defined?

**Comment by superyyrrzz** [comment]
@StephenHodgson From environment variables.
