### ISSUE TITLE
Support branch level localization repository

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3688]
Lets starts with two conventions to lookup localized content: __locale per repo__ and __locale per branch__. The config is a simple enum stored in source (English) repo.

There might be need to group locales in multiple repos using a `locale` --> `repo+branch` map in the future, but we don't do it for now.

**Comment by OsmondJiang** [comment]
@yufeih , here are some questions:
 - is `locale per branch`  in the same repo with source or another localization repo?
- if the loc content are in another localization repo, does it follow our conventions?
- what's the branch conventions, like the document using {locale}-{branch} like `zh-cn-live` or {locale}/{branch} like `zh-cn/live`?

**Comment by yufeih** [comment]
naming convention is:

__Small repo, all langs in one repo__
repo: `{source-repo}.loc`, branch `{branch}.{locale}`

__Large repo, one lang per repo__
repo: `{source-repo}.{locale}`, branch `{branch}` 
> loc team could migrate existing repos that do not follow this convention

**Comment by OsmondJiang** [comment]
based on @herohua  and @yufeih 's information, this issue has lower priority, right now we will focus on implementing the repo-mapping localization which is backward compatible with docfx/ops v2

**Comment by herohua** [comment]
We'd like to revisit whether we should keep the code in code base that partially supports this scenario.

**Comment by herohua** [comment]
We don't need this issue as we are not going to support branch level localization contents.
