### ISSUE TITLE
/// <inheritdoc />

### ISSUE THREAD

**Issue by richardschneider** [dotnet/docfx#3699]
**DocFX Version Used**: 
docfx 2.36.1.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1.  git clone https://github.com/richardschneider/net-ipfs-api.git
2.  docfx doc\docfx.json

**Expected Behavior**:

The documentation for `Block` should inherit the documentation from [IDataBlock](https://richardschneider.github.io/net-ipfs-core/api/Ipfs.IDataBlock.html) interface.

**Actual Behavior**:

No documentation is inherited.

**Other**:

The [docfx.json](https://github.com/richardschneider/net-ipfs-api/blob/master/doc/docfx.json) is fairly standard. It uses a [xref](https://richardschneider.github.io/net-ipfs-core/xrefmap.yml) to get the `IDataBlock` documentation.

Here's the links to the generated documentation for [Block](https://richardschneider.github.io/net-ipfs-api/api/Ipfs.Api.Block.html) and [IDataBlock](https://richardschneider.github.io/net-ipfs-core/api/Ipfs.IDataBlock.html)  and the source code for [Block.cs](https://github.com/richardschneider/net-ipfs-api/blob/master/src/Block.cs) and [IDataBlock.cs](https://github.com/richardschneider/net-ipfs-core/blob/master/src/IDataBlock.cs).

**Comment by superyyrrzz** [comment]
I find you are referencing `IDataBlock` through `xref`. If so, `<inheritdoc />` will not work in this case. It requires `IDataBlock` to be built together with `Block` to work. You can see the `xrefmap.yml` doesn't contain `IDataBlock`'s summary, so that DocFX cannot get this information in this case.

**Comment by richardschneider** [comment]
Are you saying that it is not possible to use `<inheritdoc />`  on another assembly?

Could you explain how I can get this to work.  How can I tell DocFX to get the summary for `IDataBlock`?

`IDataBlock` is defined in the `Ipfs.Core` nuget package, which ships with `.xml` documentation file .

**Comment by superyyrrzz** [comment]
This is not supported now. `<inheritdoc />` is a feature contributed from community with only basic support (#1178). This should be an improve to look into XML file for summary.

**Comment by rymeskar** [comment]
Hi @superyyrrzz ,
I noticed that recently you had been grouping some of the issues regarding xmldoc comments into a specific area.

Could you please share whether we could expect extended support of inheritdoc (including cref and other more granular features)? We are right now considering whether to make some workarounds around this in our code? (mostly revolving around copy-pasting :( )

**Comment by superyyrrzz** [comment]
Hi @rymeskar , I am grouping them as there are too many issues under label `Area-Metadata`.

Regarding inheritdoc, it is a syntax from Sandcastle. DocFX does not guarantee to support all Sandcastle syntax, but we are open to community contribution for these.

**Comment by rymeskar** [comment]
Thank you for the explanation. It does make sense having in mind the official VS/Roslyn state of inheritdoc is 'unsupported'.

On the other hand, I would like to let you know that there is quite a lively discussion around Roslyn/VS to add the inheritdoc support natively. 
* [Deprecated User Voice suggestion with 2800 votes](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/3745102-add-intellisense-support-for-the-inheritdoc-ta)
* [Developer Community](https://developercommunity.visualstudio.com/idea/412325/add-intellisense-support-for-the-tag-in-xml-docume.html)
* [csharplang](https://github.com/dotnet/csharplang/issues/313)
* [roslyn](https://github.com/dotnet/roslyn/issues/7862)

**Comment by dotMorten** [comment]
> Regarding inheritdoc, it is a syntax from Sandcastle

Not any more. It's not becoming a 1st class feature in Visual Studio's Intellisense as well:
https://www.youtube.com/watch?v=mg2aocZA9Pc&feature=youtu.be&t=1540

**Comment by glennawatson** [comment]
It is a first class citizen as of Visual Studio 16.4.

**Comment by muhmuhhum** [comment]
Are there any updates regarding <inheritdoc> support in docfx ?

**Comment by dotMorten** [comment]
This is a big of a showstopper for us. Any update here?

**Comment by yevgeni-zolotko** [comment]
Any updates on this one?

**Comment by alexhelms** [comment]
It has been a few months, any update on this?

**Comment by dougclutter** [comment]
This is something our Team uses too.  Any plans to add support for inheritdoc?

**Comment by Crauzer** [comment]
Would be great to have support for this

**Comment by dougclutter** [comment]
Any updates on this?  Thanks!

**Comment by dougclutter** [comment]
Thanks for implementing this! In what release number will it be available?

**Comment by yufeih** [comment]
It is available in v2.65.0 released todayl
