### ISSUE TITLE
Uid not found because it got encoded

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#3703]
```
{"code":"uid-not-found","file":"aspnetcore/fundamentals/logging/index.md","line":0,"
message":"Cannot find uid 'Microsoft.AspNetCore.WebHost.CreateDefaultBuilder%2A' using xref '<xref:Microsoft.AspNetCore.WebHost.CreateDefaultBuilder%2A>'",
"message_severity":"warning"}
```
The uid exists as 
```json
{
            "uid": "Microsoft.AspNetCore.WebHost.CreateDefaultBuilder*",
            "href": "/dotnet/api/microsoft.aspnetcore.webhost.createdefaultbuilder",
            "name": "CreateDefaultBuilder",
            "commentId": "Overload:Microsoft.AspNetCore.WebHost.CreateDefaultBuilder",
            "fullName": "Microsoft.AspNetCore.WebHost.CreateDefaultBuilder",
            "nameWithType": "WebHost.CreateDefaultBuilder"
        }
```
In V2, we are getting xrefSpec from xref service, url will decode the uid as
```
https://xref.docs.microsoft.com/query?uid=Microsoft.AspNetCore.WebHost.CreateDefaultBuilder%2A
```
Shall we decode the uid in V3 as well, or is this a content issue?

**Comment by yufeih** [comment]
The source file is using `<xref:Microsoft.AspNetCore.WebHost.CreateDefaultBuilder%2A>` to reference the method. It is not a content issue and we need to decode `Microsoft.AspNetCore.WebHost.CreateDefaultBuilder%2A` into `Microsoft.AspNetCore.WebHost.CreateDefaultBuilder*` for `<xref:{encoded_uid}>` references.

The thing I want to know is the behavior for `@` references. I suspect we don't need to decode `@` references. Can you help try and confirm the behavior for:

`@"Microsoft.AspNetCore.WebHost.CreateDefaultBuilder*"`, `@"Microsoft.AspNetCore.WebHost.CreateDefaultBuilder%2A"`,
`@Microsoft.AspNetCore.WebHost.CreateDefaultBuilder*`
`@Microsoft.AspNetCore.WebHost.CreateDefaultBuilder%2A`

**Comment by live1206** [comment]
@yufeih thanks for the clarification

**Comment by superyyrrzz** [comment]
As xref supports `#` to specify bookmark and `?` to specify querystring, it follow URI standard to encode these characters. Otherwise, DocFX cannot know whether `#` is part of the file name or a separator for bookmark.
