### ISSUE TITLE
Navigation in Navbar broken with statictoc (fix included)

### ISSUE THREAD

**Issue by xxcuratorxx** [dotnet/docfx#3716]
I am very sorry to come back to this, but unfortunately the navbar ist still broken.

My startpage is on a different level than the other pages reachable by navbar (navigation in header).
After navigating to a page different to the start page, no back navigation by hitting the start button is possible.

After having a look at the dropdown fix followed by the navigation fix, same different code is at place now.
The navbar-li contains without dropdown somethin like

`<li>
        {{^leaf}}
          <span class="expand-stub"></span>
        {{/leaf}}
        {{#topicHref}}
          <a href="{{topicHref}}" name="{{tocHref}}" title="{{name}}">{{name}}</a>
        {{/topicHref}}
        {{^topicHref}}
          <a>{{{name}}}</a>
        {{/topicHref}}
        {{^leaf}}
          {{>partials/navbar-li}}
        {{/leaf}}
      </li>`

wheras it reads `<li class="{{#active}}active{{/active}}">
	{{#href}}
	<a href="{{href}}" title="{{name}}" class="{{#active}}active{{/active}}">{{name}}</a>
	{{/href}}
	{{^href}}
	<a class="{{#active}}active{{/active}}">{{{name}}}</a>
	{{/href}}
	</li>`

in the former version. I replaces the code and everything works as expected now, but I wanted to allow other users using statictoc to benefit of that.

**Comment by superyyrrzz** [comment]
Sorry I do not quite get your ideas. Maybe some link or screenshot can help. Seems you have solved this, then a PR is also welcomed.

**Comment by xxcuratorxx** [comment]
Sorry to be unclear...

Steps to reproduce are:
* docfx.exe init
* docfx.exe docfx_project\docfx.json --template static_toc
* navigate to Api Documentation (in Header)
* navigate to Startpage => File not found

I have never made a pull request before, but i could try. However, I am not sure of any side effects.

**Comment by superyyrrzz** [comment]
@xxcuratorxx 2.40.7 fixed this issue.
