### ISSUE TITLE
Big variables like GitCommitProvider are not released after build

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3720]
cc @live1206

**Comment by yufeih** [comment]
This is not related to `ParallelUtility`, changing `Parallel` to sync does not affect GC result.

**Comment by yufeih** [comment]
Should be related to https://github.com/dotnet/roslyn/issues/437, local variables are promoted to heap allocated state machine and are never eligible for garbage collection.

**Comment by yufeih** [comment]
Close this because there is no leak, and it does not affect build performance at the time being,
