### ISSUE TITLE
Support xrefmap.yml as input

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#3727]
When community user migrates docset from v2 to v3, it's hard to ensure that the referenced `xrefmap.yml` already has been migrated to `xrefmap.json`. This can be a obstacle to adopt v3.

Come up with this as recently I find [a user case](https://github.com/richardschneider/net-ipfs-http-client/blob/master/doc/docfx.json#L69) using this to reference cross docset. [After some search](https://github.com/search?utf8=%E2%9C%93&q=%22xref%22+%22xrefmap.yml%22+filename%3Adocfx.json+-org%3AMicrosoftDocs+-org%3AOpenLocalizationTestOrg+-org%3Aaspnet+-org%3Akilla1218+-org%3Abetterliyu+-org%3Asuperyyrrzz+-org%3Ayannanwang1&type=), I find this is not a rare case among conmunity users. There should be more cases if users don't put their `docfx.json` on GitHub.

@live1206 @yufeih

**Comment by yufeih** [comment]
Do you want to support zip files as well? `https://github.com/richardschneider/net-ipfs-http-client/blob/master/doc/docfx.json#L68`

**Comment by superyyrrzz** [comment]
This is optional. It is kind of an old way to reference BCL, which can migrate to xrefService or `xrefmap.json` easily.
