### ISSUE TITLE
Nested Markdown lists do not get rendered correctly

### ISSUE THREAD

**Issue by ollie-nye** [dotnet/docfx#3736]
**DocFX Version Used**: 2.38.1.0

**Template used**: `default`

**Steps to Reproduce**:

1. `docfx init -q`
2. In `docfx_project/articles/intro.md`, append
    ```
     - Item 1

       - Item 2

       - Item 3

         - Item 4

       - Item 5

     - Item 6

       - Item 7
     ```
3. `docfx build docfx.json -s`

**Expected Behavior**:
The list will get rendered with `<p>/</p>` tags on each `<li>`
```
<ul>
  <li><p>Item 1</p>
    <ul>
      <li><p>Item 2</p></li>
      <li><p>Item 3</p>
        <ul>
          <li><p>Item 4</p></li>
        </ul>
      </li>
      <li><p>Item 5</p></li>
    </ul>
  </li>
  <li><p>Item 6</p>
    <ul>
      <li><p>Item 7</p></li>
    </ul>
  </li>
</ul>
```

**Actual Behavior**:
The list misses `<p>` tags off the lowest level of list nesting
```
<ul>
  <li><p>Item 1</p>
    <ul>
      <li><p>Item 2</p></li>
      <li><p>Item 3</p>
        <ul>
          <li>Item 4</li>
        </ul>
      </li>
      <li><p>Item 5</p></li>
    </ul>
  </li>
  <li><p>Item 6</p>
    <ul>
      <li>Item 7</li>
    </ul>
  </li>
</ul>
```

**Comment by yufeih** [comment]
Is it using markdig engine or DFM markdown engine. Does adding `{ "markdownEngineName": "markdig" }` to `docfx.json` fixes your problem?

**Comment by superyyrrzz** [comment]
Close as this is by design.
