### ISSUE TITLE
Filter Out Unwanted APIs - while using DocFX with visual studio

### ISSUE THREAD

**Issue by saanandan** [dotnet/docfx#374]
### Title
While specifying the "filter configuration file" in metadata file, when using docFX with visual studio, results in the following error

Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'metadata[0].dest', line 18, position 4.	

### Minimal repro steps
Please look at the docfx.json file in the form of text file. Use this as part of visual studio, and try to build the project. You will see the error. If you remove line 18, the project builds fine.  

[docfx.txt](https://github.com/dotnet/docfx/files/307712/docfx.txt)

**Comment by vwxyzh** [comment]
It is an invalid json, pls. add a `,` in the end of line 17.

**Comment by saanandan** [comment]
Thanks. Now my code compiles in visual studio.
