### ISSUE TITLE
Missing TOC inside PDF when building using Linux and Mono

### ISSUE THREAD

**Issue by vasicvuk** [dotnet/docfx#3759]
**DocFX Version Used**: 
docfx 2.40.4.0
**Template used**: (`default` or `statictoc` or contain custom template)
default
**Steps to Reproduce**:

1. Create sample project
2. Add PDF capability
3. Build project with Mono in Linux

**Expected Behavior**:
Having PDF with Table of contents
Having same structure of PDF directory

**Actual Behavior**:
Not having Table of contents inside PDF.
Not having same structure of PDF directory

Windows:
![image](https://user-images.githubusercontent.com/5639877/49875276-e473c100-fe20-11e8-8796-e8cb817df98c.png)

Linux:
![image](https://user-images.githubusercontent.com/5639877/49875300-f48ba080-fe20-11e8-9ea7-d8a24b8bebd1.png)

Linux used: Debian GNU/Linux 8
Mono used: Mono JIT compiler version 5.16.0.179
Versions of wkhtmltopdf on both systems is: 0.12.5 (with patched qt)

**Comment by icnocop** [comment]
See https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3953

**Comment by icnocop** [comment]
Can you provide a minimum reproducible example project?

I'm wondering if you tested it on Windows?
