### ISSUE TITLE
Error:Config file docfx.json does not exist!

### ISSUE THREAD

**Issue by mkamoski** [dotnet/docfx#3760]
**DocFX Version Used**: 
2.40.4

**Template used**: (`default` or `statictoc` or contain custom template)
unknown

**Steps to Reproduce**:

1. Go to https://github.com/dotnet/docfx/ and download the ZIP.
2. Unzip and run docfx.exe
3. See the error... Error:Config file docfx.json does not exist!

**Expected Behavior**:
One should expect no error.

**Actual Behavior**:
There is an error.

Sorry, but I do not know what else to say, this is my first look at the project, so I have to say that it does not "run out of the box" or anything like that, so I just thought you would want to know.

HTH.

Thanks.

-- Mark Kamoski

**Comment by vasicvuk** [comment]
You first need to use `docfx init -q` to init project. Then you should navigate to created directory docfx_project. After that you should use `docfx docfx.json` or  `docfx docfx.json --serve` if you want web server to open with generated documentation.
