### ISSUE TITLE
Generate ideal output for report for PR comments

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3780]
The current dependency map approach is too fragile. We need to support generating reports for PR comments within docfx:

- [ ] Input change list
- [ ] Output PR comment report
- [ ] Remove dependency map from output

cc @fenxu

**Comment by yufeih** [comment]
Current dependency map consumer: PR comment, significant change, localization. What PR comment and significant change really want is to find the files to preview for a given file change.

**Comment by OsmondJiang** [comment]
Assign to @mingwli , talked offline with @yufeih
