### ISSUE TITLE
Edit link for PR build

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3791]
We need to keep the `branch` info in `edit link` which points to pr branch for PR build, but this can cause  full publishing issue, there are several options:
1. Points all links to source branch using a template metadata **require changes across the pipeline*
2. Points only changed links to source branch **require taking changeset as input*
3. ~~hide the `edit link` in pr build~~
4. ~~points to target branch always~~

**Comment by yufeih** [comment]
Prefer letting `git_content_url` in metadata pointing to source branch, and setting `git_content_url` in content pointing to target branch. This way, content will have consistent hash.

**Comment by yufeih** [comment]
Finalized the spec [here](https://github.com/MicrosoftDocs/engineering/pull/270)
