### ISSUE TITLE
Setup E2E test against to PPE/Review repo which is enabled docfx V3

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3793]
Seems PPE azure-docs-pr repo for docfx V3 is not monitored, it's keeping failed for one or two weeks but no one knows. We need setup E2E test against to this repo to make sure:
1. Our integration with Docfx V3 and Build service is working
2. Any Docs Experiences E2E test should passed against this repo.

@herohua , @yufeih , @mingwli

**Comment by OsmondJiang** [comment]
talked with E2E team offline, there are two kinds of E2E test:

  - Regression test(3) against existing docs repo, check build report/time/outputs
  - E2E tests(200+) against manual prepared data in some test repo branch, check all kinds of build functions like CRR changing/cancel build/pr outputs

For regression test, we need rewrite a new test for v3 because our comparing base line is different with v3.

For E2E tests, i believe most of the test cases are suitable for V3, so we need find a easy way to apply all existing e2e tests to V3 build:

  - Re-prepare all tests data using config which enabled v3
  - Or provide a API to trigger build with v3, no need re-prepare all test data 

cc @yufeih @herohua  @wh-alice

**Comment by OsmondJiang** [comment]
@wh-alice  suggests to manually go through all E2E tests before automatic them(because it may take too much time), we then can get all passed/failed/missing support scenarios and start the fix, what do you think @yufeih  @herohua ?

**Comment by wh-alice** [comment]
@OsmondJiang , as we discussed offline, the key point at here is the target expectation for test complete. @herohua , please update me this time information. I am asking test team to provide current feature list with related cases for the review. If something need tob e added, please notify us. And I will ask team team to go through the scenario and unblock your continous work. If case can run smoothly, we will use automation case, if not, manual work will be the first step. Then automation will catch up step by step. cc @herohua, @OsmondJiang, @yufeih

**Comment by OsmondJiang** [comment]
offline talked, we are going to:
1. Firstly setup azure regression test, which monitor the perf/report, run after the ops build deployment.
2. Move p0 e2e tests to v3, need change the test data(fork new test repo)
3. Moce other tests to v3, but no hurry
4. Go through the all existing e2e tests moved to v3.

**Comment by OsmondJiang** [comment]
After running the regression test against PPE environment, we found two issues:
1. The regression test is always full build and publish, which can't represent most of the real usages.
2. The regression test is running on PPE, which has limited resource, making the perf testing not stable.

We are going to
1. Create an new regression test(Create PR and build)
2. Running regression test on review environment.

**Comment by yufeih** [comment]
This should resolve #4021

**Comment by OsmondJiang** [comment]
Currently some tests are testing against UI, which can only run locally, talked offline with @wh-alice , we want to continue convert these tests to test against API(calling DHS), I will work with Yajun to:

- [ ] List all the UI tests 
- [ ] Firstly convert all UI tests which running in v3 to API model.
- [ ] Then convert the reset UI test to API model.

cc @herohua  @yufeih  @fenxu
