### ISSUE TITLE
Design and setup migration tool/CI for docfx-v3 migration 

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3831]
Migration team has a tool to compare the docfx output(DFM vs Markdig), I believe we can use this tool to compare the V3 build outputs(HTML) with V2 and generate the impact report.

0. Setup CI to run against corresponding repo to be migrated.
1. Run build locally, enable v3 vs disable v3
2. Compare the outputs(HTML) and generate the report
3. Send the report to customer

cc @yufeih , @herohua , @wh-alice  @daxianji007

**Comment by OsmondJiang** [comment]
The `markdig` migration tool seems not suitable for docfxv3 migration, and also we have our own `impact` tool already, so maybe we can take the advantage of `impact` tool to setup an new docfxv3 migration tool:

1. The tool‘s target users are developers and vendors, not writer/repo owners, help us to identify if the repo is ready for enabling docfx v3
2. It need:
    - Import v2 build package automatically, and run some `import` script to prepare the input build package
    - Run the build with docfx v3 enabled, generate the outputs for comparing
    - Compaing the outputs, generate the different report.

**Comment by OsmondJiang** [comment]
The `markdig` migration tool maybe not suitable for `docfxv3` migration, but we will follow the same process:

- CI template setup via OPS portal
- Create new branch for testing
- Generate output different for vendors/developer
- Generate migration report(check list) for repository owners

The docfx v3 migration tool can take the advantage of `impact` tool:

- Create test branch in repo to be migrated
- Automatically import v2 build(test branch) outputs for comparing
- Run `import` scripts to get ride of expected differences
- Run build with docfx v3 enabled, generate outputs for comparing
- Normalize and Generate PR/Diff reports for developers/vendors
- [Optional] Analysis the diff reports to generate migration report(check list) to repository owners

**Comment by OsmondJiang** [comment]
There are some things we need finalized:
- The purpose of the migration tool
- What need to be compared, or what's the input for this tool
- What kinds of reports need to be generated for vendor/developer
- What kinds of reports need to be generated for content writer
- What expected actions need to be take for the report receiver

**Comment by OsmondJiang** [comment]
Migration CI steps:

- Create new branch(migration branch) for migration in source repo
- Run `migration tool` against `migration branch` to fix necessary content and v2 configuration
  - If there are any changes in `migration branch`,  create a PR from `migration branch` to `master` branch, mark CI failed , involve content repo owner.
  - If there are NO changes at all, go to next step.
- **Import** v2 build package of `migration branch`, including normalizing for comparing.
- Change the configuration to `usedocfxv3` to true in `migration branch`, trigger and wait for the build, **import** v3 build package, including normalizing for comparing.
- **Comparing** v2 and v3 outputs, generate diff result to one diff file and push it to one VSTS repo for tracking.
  - If there are any differences, make CI failed, involve developers.
  - If there is NO diff at all, create PR from `migration branch` to `master` branch, mark CI successful.


There are some major works:

- Migration tool:
  - Fix redirections
  - Fix document id metadata
  - ….
- Import tool:
  - Trigger v2/v3 build, change configuration to enable v3, if necessary.
  - Download and import v2/v3 package
  - Normalizing input for comparing, get rid of expected differences
- Diff tool:
  - Comparing v2/v3 output files, generate differences report
  - Check-in difference report to VSTS repository
- CI template:
  - Setup CI template
  - Integration with OPS Portal
  - Permission control.

**Comment by OsmondJiang** [comment]
please make sure we have a way to tracking down the changes for diff tool like:
- which metadata properties are ignored(deleted before comparing) for diff
- which metadata properties are modified before comparing and reason,
- which files are ignored for diff and reason
- which files are modified before comparing and reason.
...

**Comment by 928PJY** [comment]
Migration CI Tasks:
- [x] Migration CI pipeline implementation
- [x] Setup CI template
- [x] Integrate with portal
- [x] Split the scripts from Impact repository
- [ ] [Setup migration rolling test](https://github.com/dotnet/docfx/issues/4085)

Pending Work:
- [ ] Output diff to CI log, blocked by this [issue](https://github.com/Microsoft/azure-pipelines-tasks/issues/9677)


Migration process open questions:
- For now, if there are some diff between the v2 and v3 build result, I will delete the migration branch, so there is no branch for the author to use docfx v3.
- Continue to compare the build package only when the all builds are succeeded[withWarning], how about the failed case:
1. V2 failed - corner case, not ready to migration
2. V3 failed - Avoid in the content fix step?
