### ISSUE TITLE
Xref map output

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#3835]
- [x] Href in `xrefmap.json` is an absolute path in v3, but it is an external link(with hostname) in v2
       fundamentals/routing.md
       ![image](https://user-images.githubusercontent.com/5196139/50807977-6b8c5a00-1337-11e9-8a1c-ed729054bde4.png)
- [x] Add `xrefmap.json` to `items_to_publish` in `manifest` file

**Comment by live1206** [comment]
`xrefmap.json` is added to `items_to_publish` during OPS build. So if we have a new pipeline for v3, the new pipeline will handle this as well?
Does docfx still need to provide the location of `xrefmap.json`  as below?
```json
  "default_version_info": {
    "name": "",
    "version_folder": "",
    "xref_map": "xrefmap.yml"
  }
```
Similar to `filemap.json`?
@fenxu @928PJY

**Comment by OsmondJiang** [comment]
https://github.com/dotnet/docfx/blob/v3/docs/designs/output.md
