### ISSUE TITLE
dfm does not recognize a link label that contains backslash-escaped brackets

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docfx#3836]
**DocFX Version Used**: 2.39.2

**Template used**: default

**Steps to Reproduce**:

1. `docfx init` and accept all defaults
2. Edit `docfx_project\docfx.json` so it says `"markdownEngineName": "dfm"` rather than `"markdownEngineName": "markdig"`
3. Append a blank line and the following to `docfx_project\index.md`:
   ```markdown
   See [\[link\]]
   
   [\[link\]]: https://example.org/
   ```
4. `docfx docfx_project\docfx.json --serve`
5. Open `http://localhost:8080` in a browser.

**Expected Behavior**:

DocFX recognizes the shortcut reference link:

```html
<p>See <a href="https://example.org/">[link]</a></p>
```

**Actual Behavior**:

DocFX does not recognize the shortcut reference link:

```html
<p>See [[link]]</p>
<p>[[link]]: <a href="https://example.org/">https://example.org/</a></p>
```

**Notes**:

I think https://spec.commonmark.org/0.28/#link-label means that the link label can contain backslash-escaped brackets. It works OK with "markdig", but not with "dfm" or "gfm".

**Comment by KalleOlaviNiemitalo** [comment]
I built our documentation set with "dfm" and "markdig" and compared the HTML. "dfm" also has a problem with link reference definitions in which the link title contains backslash-escaped quotation marks; it copies the backslashes to the `title` attribute, whereas "markdig" correctly removes the backslashes. Should I file that as a separate bug, or are problems like these no longer being fixed in "dfm"?

**Comment by yufeih** [comment]
Our recommendation is to switch to markdig for better spec conformance. Bugs in *dfm* are rarely picked up by our team due to our shift to markdig.
