### ISSUE TITLE
refine error code/message/level before first release

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#3838]
#### level change: ** need work, change level **
  - [x] circular-reference: add 'error' in config migration-tool(for the ones thrown by markdig)
  - [ ] merge-conflict: suggestion
  - [x] include-is-redirection: error

#### split into more specific errors
  - [x] null-value: keep v2 behavior; scalar null value: info & null array value: warning
  - [x] *bookmark-not-found*: internal(suggestion) & external(warning)

#### minor modification 
  - [x] *git-log-error*: shadow => shallow
  - [x] invalid-yaml-header: remove (never used)

#### others
  - [x] absolute-file-path: don't resolve as `link<a>`
  - [x] invalid-redirect-to: #3943
  - [x] reserved-metadata: keep current behavior(throw warning and publish as redirection file)
  - [x] redirection-out-of-scope: throw warning and don't auto add
  - [x] heading-not-found: info, and resolve from h1-h3(follow h2 behavior to be prudent)

#### for backlog(don't need change)
  - [ ] invalid include type: currently we only throw exception when it's redirection, and it could be anything
  - [ ] **internal**: download-failed: more details using http response status code
  - [ ] **internal**: git-clone-failed: addWorkTree / clone failed? need check
  - [ ] **?**: moniker-config-missing: how to handle monikerDefinition & monikerRange conflict
  - [ ] **internal**: upload-failed: alert and monitor
  - [ ] **?**: link-is-dependency: better error code, may need to merge 
  - [ ] **?**: empty-monikers: file / zone level
  - [ ] **?**: *invalid-toc-level/invalid-toc-syntax/missing-toc-head*: only happens in markdown toc
  - [ ] *file-not-found*: inclusion => error(already thrown by markdig); ?link => warning; user_profile (url) => system error
  - [x] unknown-field: update landingData schema?

**Comment by yufeih** [comment]
`invalid-redirection`, `include-is-redirection` are all taking about the same **link type mismatch** problem, that is, you can only reference a set of allowed types. Otherwise we could have `include-is-resource`, `include-is-config` and the list goes on and on.

**Comment by yufeih** [comment]
With #3784, we only have `null-inside-array` now.

**Comment by OsmondJiang** [comment]
bookmark-not-found suggest to be spited into `self-bookmark-not-found`(info) and `bookmark-not-found`(warning)?

**Comment by mingwli** [comment]
I've added these items to [teams](https://teams.microsoft.com/_#/files/%F0%9F%90%A8%20DocFX%20v3%20-%20error%20code%20and%20message?threadId=19%3A22aff63434ff4345bc5627fa74b9145b%40thread.skype&ctx=channel)

**Comment by mingwli** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.MigrationTool/pullrequest/9546?_a=overview
