### ISSUE TITLE
Documentation of markdownEngineName does not mention "markdig"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docfx#3841]
**DocFX Version Used**: 2.40.6

**Template used**: N/A

**Steps to Reproduce**:

1. View the documentation of `markdownEngineName` under ["Properties for build" in docfx.exe User Manual](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#32-properties-for-build).

**Expected Behavior**:

The documentation says that the "markdig" engine is available and should be preferred in new projects.

**Actual Behavior**:

The documentation does not mention the "markdig" engine:

> Key | Description
> -- | --
> markdownEngineName | Set the name of markdown engine, default is dfm, and another build-in engine is gfm.

**Notes**:

Because "markdig" is not listed there, I got the impression that "markdig" is a legacy engine and "dfm" should be preferred. Actually, "markdig" seems to comply better with the Markdown spec than "dfm" (e.g. #3836). I now see that #2661 made `docfx init` add `"markdownEngineName": "markdig"` to `docfx.json`, but #2650 says that compatibility requires keeping "dfm" as the default if "markdownEngineName" is not specified.

**Comment by yufeih** [comment]
Thank you for reporting this documentation issue. I've [updated the docs](https://github.com/dotnet/docfx/commit/5199cc630e8eb004bc8505a22d20745f9b25b269), the webpage should be updated momentarily.
