### ISSUE TITLE
Publish without --legacy

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3856]
To publish directly from `docfx build` result:

- [x] Finalize publish spec
- [x] Move jint outside `--legacy`
- [x] Add file metadata to publish manifest
- [x] Add output file hash (SHA1).
- [x] ~~Add content type: (This is done in publish step)~~
    - Json files: `application/json`
    - Html files: `text/html`
    - Fallback to aspnet core `FileExtensionContentTypeProvider`
    - Fallback to `application/octet-stream`
- [x] Run jint for TOC
- [x] ~~Remove `--legacy` ??~~

**Comment by OsmondJiang** [comment]
what's the definition of manifest, seems we put too much things into manifest file....
