### ISSUE TITLE
docfx installation via dotnet tool install -g

### ISSUE THREAD

**Issue by dotChris90** [dotnet/docfx#3858]
Hello docfx team, 

Wish you a happy new year. 

I was asking myself if there is a specific reason why docfx can not be installed as dotnet tool - via command
"dotnet tool install -g dotnet-docfx" or something in this way. :)

From your website the official way is chocolatey package or zip file download on windows. 
But I think docfx as **global dotnet tool** would be the most easy for everybody. :)

Are there any plans to ship like this? Is it already possible and I did not see it? ;)

Thanks for your time and have a good week.

**Comment by yufeih** [comment]
_dotnet global tool_ is the default installation behavior in v3. For the current version, it is not on .NET core yet.

**Comment by dotChris90** [comment]
cool thanks for fast reply. :)
