### ISSUE TITLE
Unable to stop DocFx server on MacOS

### ISSUE THREAD

**Issue by bryancostanich** [dotnet/docfx#3870]
**DocFX Version Used**:  2.40.7

**Template used**: default

**Steps to Reproduce**:

1.  launch docfx server: `docfx docfx/docfx.json --serve`
2. try to quit (ctrl-c)
3. no happenings

**Expected Behavior**: docfx terminates it's serve process and i go about my life.

**Actual Behavior**: nothing happens.

**Comment by bryancostanich** [comment]
Even terminating the terminal process that hosts that doesn't kill it. And I can't figure out the name of the process to kill it via the process list. is it one of the monos?

**Comment by bryancostanich** [comment]
Not any of the mono processes...

**Comment by bryancostanich** [comment]
Can we get this added to V3? It's kind of a major bug.

**Comment by Nathan-Devery** [comment]
Same issue but windows - can't stop serving on 8080

**Comment by ericljiang** [comment]
Are there any workarounds for this besides closing the terminal?
