### ISSUE TITLE
More then 6 `#` in the TOC heading block

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3874]
https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C1%5C4%5Ce2344c78-2e2d-592e-9f3d-af54656882a1%5CCommit%5C201901040858245275-live%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1CzR7TXi%2FFJojWcxlDwhyhKFKZkUUq5X8Pv3jn2QUWk%3D&st=2019-01-04T10%3A38%3A03Z&se=2019-02-04T10%3A43%3A03Z&sp=r

cc @mingwli 

![image](https://user-images.githubusercontent.com/19990166/50752171-11808b80-1288-11e9-8f48-9a71129b4e21.png)

**Comment by OsmondJiang** [comment]
This [TOC](https://github.com/MicrosoftDocs/VBA-Docs/commits/master/api/TOC.md) file is really huge, maintained by human, not CI.

There are two ways to fix that issue, one is migrate it to TOC.yml during migration, another one is we supporting that scenario, break the ATX heading rules, what do you think?

@yufeih, @herohua , @fenxu

**Comment by yufeih** [comment]
Having a custom heading rule is more user friendly, let me ask if this can be a configurable option in markdig.

**Comment by fenxu** [comment]
I agree that supporting more than 6 level TOC of md is user friendly. Because we have TOC include case, my concern is that it's hard to explain to others that some included toc is broken even all TOCs are not more than 6 level.

**Comment by OsmondJiang** [comment]
included TOC is not worried, becase the level is relative to current TOC file.

**Comment by herohua** [comment]
@OsmondJiang , @yufeih , @fenxu , it is really great to see that we are taking the approach to contribute to Markdig repo to solve our issues. 👍
