### ISSUE TITLE
resolve XRef for conceptuals

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3882]
Docfx has done the generate xref map file and uploding xref map file part, missing the import/restore xref map feature.

**Comment by live1206** [comment]
https://github.com/dotnet/docfx/blob/70b9bfd98f9f2c1325655184d17345d8aada8486/docs/specs/xref.yml#L42
Is this scenario same as this test?

**Comment by OsmondJiang** [comment]
Maybe we need config migration tool support?  @mingwli

**Comment by yufeih** [comment]
Should compare external xref url with current host name, remove host name if they are the same.

**Comment by OsmondJiang** [comment]
@yufeih, may we know why? seems it's totally different with what we talked in this issue #3885

**Comment by live1206** [comment]
> Should compare external xref url with current host name, remove host name if they are the same.

will handle it in #3885

**Comment by herohua** [comment]
we need to consider #3487 together with this issue

**Comment by live1206** [comment]
## Restore related `xrefmap.json` to resolve external `uid`
With this, it would save all the network traffic to xref service, which would be much faster for build and authoring.
The main concern here is how to config where to get `xrefmap.json`, which depot/product name/share base path? For new repos, we assume the user should know where to get the uids. 

 - [ ] Needs to confirm with PM if it is OK for users to do so
 - [ ] For existing repos, we need to set up the configuration during migration, some thoughts:
      - [ ] v3 adds `depots` to the config file, which points where `xrefmap.json` locates
      - [ ] v2 helps to output the external uids referenced in the current repo during the build
      - [ ] migration tool calls xref service to somehow get the `depots` of the previous external uids, then add them into v3 config file
 - [ ] Given a `depot`, there could be multiple `xrefmap.json`, they need to be merged somewhere #3487 
      - [ ] short term: merge them during OP build, send the urls to docFX v3 config, the merging is already implemented [OP.Build](https://ceapex.visualstudio.com/Engineering/All/_git/OpenPublishing.Build?path=%2FLibraries%2FWorkflowTasks%2FXRefMap%2FXrefMapRestorer.cs&version=GBdevelop&line=36&lineStyle=plain&lineEnd=37&lineStartColumn=1&lineEndColumn=1), which is based on the shared base path, adjust it to use the config `depots`
      - [ ] long term: merge them in xref service, we had a discussion before but needs more confirmation

**Comment by live1206** [comment]
https://github.com/MicrosoftDocs/engineering/pull/430
