### ISSUE TITLE
Customized 404 page is not supported

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3884]
if we don't want to support customized 404 page, do we need throw errors/warning if someone is using it?

@yufeih , @herohua , @fenxu

**Comment by fenxu** [comment]
Info at first and then change severity to warning in someday. Does that make sense?

@herohua @OsmondJiang @yufeih

**Comment by OsmondJiang** [comment]
we just need do nothing, treat it as normal page for building, since docsroot is using 404 page now.

@yufeih  is creating a PR to update the metadata for 404 page at DocsRoot, so we either NO need to add the default value to 404 page anymore.

<meta  name="ROBOTS" content="NOINDEX, NOFOLLOW">

**Comment by yufeih** [comment]
We'll treat 404 pages are ordinary content pages and remove any special logic around it.
