### ISSUE TITLE
Remove hostname while resolving uid

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#3885]
In v2, OPS will inform docfx while calling xref service need to remove some specific hostname.

We need to figure out when we should remove the hostname, for instance:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2

Check the page source to see the href of `IRouter`, even they are sharing the same hostname, the hostname has not been removed. 

So, when should v3 remove hostname while resolving uid?

**Comment by yufeih** [comment]
I'd say never.

**Comment by OsmondJiang** [comment]
it's depends on the difference of host name of different environment?

**Comment by yufeih** [comment]
Close this as docfx should treat urls as opaque data.

**Comment by OsmondJiang** [comment]
just a reminder, we need import different xref files for different branch in prod environment, because different branch using the different host name.

**Comment by live1206** [comment]
https://review.docs.microsoft.com/en-us/engineering/projects/ops/build-service/host-url-usage?branch=master#open-issue
