### ISSUE TITLE
URL decode before link to or include a file

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#3887]
For a file `a b.md`, it should use `[sample](a%20b.md)` to link to it, or use `[!include[](a%20b.md)` to include it. The decode logic is in Markdig's `ReadFile` or `GetLink` delegate or by post processing `MarkupResult`. 

Currently URL decode support:

| syntax | v2 | v3 |
|-|-|-|
| link |  ✅ | ❎   |
| include | ❎ | ❎  |

TODO:

- [ ] URL Decode in v2's `ReadFile` @daxianji007 
- [ ] URL Decode in v3's `ReadFile`
- [x] URL Decode in v3's `GetLink` (needs Q1)

/cc @928PJY

**Comment by herohua** [comment]
This seems like a question we could get PM's input.

**Comment by yufeih** [comment]
Related https://ceapex.visualstudio.com/Engineering/_workitems/edit/66496

**Comment by yufeih** [comment]
What is canonical URL and url in publish manifest for file `a b.md` ?  `a b` or `a%20b`

**Comment by herohua** [comment]
@yufeih to double confirm v3 behavior first
