### ISSUE TITLE
implict and etag may affect the LastWriteTime of file/worktree

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3891]
these two flags may have affects to the LstWriteTime of downloaded files and restored worktree and GC may delete the wrong files/worktrees.

@yufeih , @mingwli

**Comment by yufeih** [comment]
Will this problem disappear say when we use `.lock.json` to track dependency version?

**Comment by OsmondJiang** [comment]
I don't think so, as we talked offline yesterday, GC should not use lock files as input, still need check the last last write time, to avoid the dead lock.

**Comment by OsmondJiang** [comment]
#3888

**Comment by OsmondJiang** [comment]
let's consider more:
- In real production environment, the restored file version count or git repo's size/version count would be very large.
- We also need consider the restore worktree checkout speed limited by the worktree size.
