### ISSUE TITLE
Missing Azure Pipelines CI docs

### ISSUE THREAD

**Issue by StephenHodgson** [dotnet/docfx#3912]
It would be helpful to understand how to setup and use docfx in azure pipelines

Maybe adding documentation to the [existing CI sections](https://github.com/dotnet/docfx/blob/dev/Documentation/tutorial/docfx_getting_started.md/#4-use-docfx-with-a-build-server)?

**Comment by superyyrrzz** [comment]
The document you mentioned is specific to the issue about how to get the right branch for contribution link. It is not related to "how to setup CI".

Back to your question, we have not an existing sample or document about this. Generally, it need a tiny script to do the following things:
* clone repo
* `choco install docfx`
* `docfx {docsetPath}`
* publish your site, e.g. push all the content in `docsetPath/_site` to `gh-pages` branch

**Comment by StephenHodgson** [comment]
> The document you mentioned is specific to the issue about how to get the right branch for contribution link

No... The header specifically says "Use DocFX with a Build Server"

In either case, thanks for the info that's pretty much what I was looking for.

Only suggestion is to add instructions to change the output folder to be a relative folder named "/docs" that lives on the top level of the repository for GitHub pages.

**Comment by superyyrrzz** [comment]
> No... The header specifically says "Use DocFX with a Build Server"

I agree that the content and the title do not match. I created a PR to update it. Welcome to comment 😄 

> It's probably easier just to push those changes back to master, no?

You can change `"dest": "_site"` to `"dest": "../docs"` in `docfx.json`.
