### ISSUE TITLE
"in this article" hard coded

### ISSUE THREAD

**Issue by timcromarty** [dotnet/docfx#3923]
**DocFX Version Used**: 
Latest 

**Template used**: (`default` or `statictoc` or contain custom template)
Default

**Steps to Reproduce**:

1. Appears on all DocFx Pages 
2. 
3. 

**Expected Behavior**:
The affix title "In This Article" is hard coded and can only be changed within javascript.  I don't want to use the term "article", I would prefer "Document" or something else.  Can this value be configured in the docfx.json metadata?

**Actual Behavior**:

**Comment by herohua** [comment]
@superyyrrzz , can you help reply to this thread? thanks!

**Comment by superyyrrzz** [comment]
There are no existing metadata supporting this. Of course, you can custom template to support this.

Code to custom: https://github.com/dotnet/docfx/blob/3258bcd90c99993501c4e05732b3830b77167a99/src/docfx.website.themes/default/styles/docfx.js#L543
Document: https://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html#merge-template-with-default-template
