### ISSUE TITLE
macos support

### ISSUE THREAD

**Issue by bryancostanich** [dotnet/docfx#3924]
Hey folks; after two weeks of hacking on DocFX on macos, it's pretty clear that it's basically untested and barely working on mac. I see that it's supposed to be "cross-platform," but can you tell me, specifically, what the V3 mac plan is?

We'd love to use DocFX, it has a lot of potential for us, but right now, the struggles we're running into trying to work on it via mac are making us think we might just use MonoDoc + GitHub Pages/Jekyll, to handle our API docs and conceptual docs, respectively.

**Comment by superyyrrzz** [comment]
@BrennanConroy  I will close this first. You can create another issue for your specific problem met on macos. Thank you.

**Comment by BrennanConroy** [comment]
??

**Comment by superyyrrzz** [comment]
@BrennanConroy Close as this is supported. You can open another issue for the bug you met. 

One tip is to [download mono from mono website, instead from homebrew](https://github.com/dotnet/docfx/issues/2491#issuecomment-414041674)

**Comment by BrennanConroy** [comment]
... I didn't open this

**Comment by 0xced** [comment]
> docfx in v3 works on mac and is **tested**.

For the record, you can install `docfx` v3 as a [.NET Core global tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) by running the following command:

```
dotnet tool install -g docfx --version "3.0.0-*" --add-source https://docfx.pkgs.visualstudio.com/docfx/_packaging/docs-public-packages/nuget/v3/index.json
```

You can read more about docfx v3 in the [v3 branch](https://github.com/dotnet/docfx/tree/v3).
