### ISSUE TITLE
Urls in Redirections must start with '/'

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3943]
To remove the logic of host name, docfx needs to check that urls in `Redirections` **MUST** start with '/',

**Comment by OsmondJiang** [comment]
The invalid redirection reports `info/warning`, but no output generated.

We can just set the document_id to false in configuration migration if the `redirect_to` is not start with `/` or 'docs.microsoft.com'.

@mingwli

**Comment by mingwli** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.MigrationTool/pullrequest/9416?_a=overview
