### ISSUE TITLE
DocFx bolloxes case in left nav/TOC.

### ISSUE THREAD

**Issue by bryancostanich** [dotnet/docfx#3969]
**DocFX Version Used**: 2.40.7

**Template used**: default

we have a `/Guides/` directory (instead of `/articles/`), which we have configured in docfx.json:

```
  "build": {
    "content": [
      {
        "files": [
          ...
        ]
      },
      {
        "files": [
          "Guides/**.md",
          "Guides/**/toc.yml",
          "toc.yml",
          "*.md"
        ]
      }
    ],
```

But in the TOC all links are rendered as lower-case "/guides" on our left nav, e.g. `http://beta-developer.wildernesslabs.co/guides/Meadow_Basics/index.html` on our production server.

this is generally fine because all TOC links have case agreement, but when I add a link to a page that has the correct (upper-case) link, `/Guides/Meadow.Foundation/Working_w_Sensors/index.html`, i get a 404 error:

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: Guides/Meadow.Foundation/Peripherals/index.html
RequestId: 5A54F94C427606F7
HostId: HivgEfVWo0Z7JtawfGIdQnyfPKyo0/2kOFlAS37q+ST+mPeVTh1Es9F4kFoWCg3npmhIcJ1frPM=
```

Interestingly, this doesn't happen when I run locally on the mac. The left nav/TOC links are rendered with the correct case.

**Comment by superyyrrzz** [comment]
Could you check whether you use `Guides` or `guides` in your `toc.yml`'s `href`? This will determine what it renderers in TOC links.
