### ISSUE TITLE
Images with API Override files aren't copied to output.

### ISSUE THREAD

**Issue by bryancostanich** [dotnet/docfx#3978]
**DocFX Version Used**: 2.40.7

**Template used**: `default`

if you're writing API override docs in markdown, and you put images in that same overrides folder (along with the override docs), they don't get copied to the output, so they're not available.

**Comment by bryancostanich** [comment]
I even tried specifying them as a resource, e.g.:
```
    "resource": [
      {
        "files": [
          "images/**",
          "api-override/**/*.svg",
          "Common_Assets/**",
          "API_Assets/**"
        ]
      }
```

but that just copied them to an `api-override` folder in the output, rather than the location of the docs.

**Comment by superyyrrzz** [comment]
Firstly, you need to include them in the `resource` group to make them appear in output. I see you have tried it.

Secondly, you can add `src`/`dest` to make them appear in the desired place, e.g.: https://github.com/dotnet/docfx/blob/f33c8c55ecfb596be24755e0fff439a609a7e408/Documentation/docfx.json#L16-L20
