### ISSUE TITLE
Custom XML tag

### ISSUE THREAD

**Issue by mezzo9** [dotnet/docfx#3984]
Is it possible to add a custom Tag, for example:
<sql>varchar(40)</sql>
when compiling, the XML file, does have the tag, however, the yaml files does not. 
Is there a way to add custom tags, and then include them in the documentation?ehavior**:

example:
```
        /// <summary>
        /// User friendly name of the office that appears in the POS drop down.
        /// </summary>
        /// <sql>varchar(40)</sql>
        /// <remarks>
        /// Column name in table is OfficeName.
        /// </remarks>
```

**Comment by superyyrrzz** [comment]
Seems this question is resolved in [Document discussion](https://dotnet.github.io/docfx/spec/triple_slash_comments_spec.html#comment-4311480018). I also copy it here:

> You need to custom TripleSlashCommentModel to expose the new tag, then render it properly through template.
> Here is the code: https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Parsers/TripleSlashCommentModel.cs

Close this for now. Feel free to reopen it if you have any other question.

**Comment by samiramaleki** [comment]
but, how do I use the class library after changed

**Comment by mezzo9** [comment]
Just add whatever tags you want, in the discussion I've put the list of all
the locations that need to be changed.
then just compile it and use it as you would normally.

**Comment by samiramaleki** [comment]
I used [```docfx-seed```](https://github.com/docascode/docfx-seed) , how do  i add change to docfx-seed ?

**Comment by paulushub** [comment]
@samiramaleki The `TripleSlashCommentModel` is not a plugin class, so if you make changes you will have to compile your own version of the DocFX.

**Comment by SethHarlaar** [comment]
Is this answer still relevant in 2025?
