### ISSUE TITLE
pr builds' metadata is different target builds'

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3987]
![image](https://user-images.githubusercontent.com/19990166/51898935-ed2e4f80-23ec-11e9-9349-94803324af7e.png)

We may want to use configuration to get the repo + branch instead of git info itself.

@yufeih @fenxu

**Comment by OsmondJiang** [comment]
The main reason is that the branch and repo info maybe incorrect for PR build. 

I would like to use environment variables like [VSTS build variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azdevops) to setup the current repo url and repo branch, what do you think? @yufeih  @fenxu 

![image](https://user-images.githubusercontent.com/19990166/51953796-b140cc00-2478-11e9-8b48-784cd7937d1c.png)

**Comment by OsmondJiang** [comment]
# Background

During PR build, we found the metadata generated is different with target branch build, the only different is the `original_content_git_url`.

The difference has impacts to our incremental publish, which cause all PR publish is **FULL publish**. We only want to publish modified files.

The main reason is that docfx get the repo info(url + branch) from local git directly, which is incorrect during PR build, because the PR build using branch info fetched from GITHUB which is actually PR name.

# Solution

We want make this metadata `original_content_git_url` generated in PR build same with target branch builld's, which means the repo info(url + branch) provided by local git is not correct. 

Docfx need a way to get the git info(url + branch) from the caller: using environment variables `DOCFX_REPOSITORY_URL` and `DOCFX_REPOSITORY_BRANCH`.

Docfx will try to get repo url and repo branch info from environment variables firstly, if they are not set, using local git as fallback.

# Work Items

- [ ] Retrieve repo url and repo branch info from environment variable for docfx build
- [ ] Build service setup these two environment variables before run docfx.

# Propose Change

```C#
Repository Repository.Create(string docsetPath)
{
    return Repository.Create(docsetPath, AppData.GetRepoUrl(), AppData.GetBranchName());
}
string AppData.GetRepoUrl()
{
    return Environment.GetEnvironmentVariable("DOCFX_REPOSITORY_URL");
}
string AppData.GetBranchName()
{
    return Environment.GetEnvironmentVariable("DOCFX_REPOSITORY_BRANCH");
}
```

# Open Question

How about the sub modules in docset?

cc @yufeih  @fenxu  @superyyrrzz

**Comment by fenxu** [comment]
Submodule do you mean CRR or submodule itself?
If you mean submodule, we don't have that scenarios now in Docs. However, we can talk about that in if we want to support this case.
If you mean CRR
- for branch build, the information can be extracted from git.
- for PR, it should follow CRR cache file.

**Comment by OsmondJiang** [comment]
I mean submodule itself, not CRR, @fenxu

**Comment by OsmondJiang** [comment]
the `original_content_git_url` issue has been resolved, but there is another difference, the `updated_at` is different now.

![image](https://user-images.githubusercontent.com/19990166/53216399-65580000-368f-11e9-99a4-fca90a718bba.png)

**Comment by OsmondJiang** [comment]
the init investigation show the commit history file generated for source branch and target branch maybe different:

![image](https://user-images.githubusercontent.com/19990166/53217743-43ad4780-3694-11e9-838c-bfa495b7aa72.png)

![image](https://user-images.githubusercontent.com/19990166/53217752-49a32880-3694-11e9-8bdc-6156cbe998df.png)

@superyyrrzz

**Comment by OsmondJiang** [comment]
seems it's by design, the `updated_at` is the commit pushing time, so for different branch, the pushing time is different, but for PR branch, may be not useful, just like `original_content_git_url`, sincePR branch is just a temp working branch.

cc @fenxu @yufeih  @herohua

**Comment by fenxu** [comment]
It depends on when you create the source branch. I think it's by design

**Comment by OsmondJiang** [comment]
all pages publishing are impacted, images are not

**Comment by yufeih** [comment]
> all pages publishing are impacted, images are not

**Comment by yufeih** [comment]
@superyyrrzz , consider using target branches git commit time file for PR

**Comment by superyyrrzz** [comment]
@yufeih Yes.
* For an old commit that exists in both target branch and source branch: use target branch's push time
* For a new commit that exist only in source branch (new commit in PR): use source branch's push time (or UTC.Now in current implementation)

@OsmondJiang @fenxu

**Comment by OsmondJiang** [comment]
https://ceapex.visualstudio.com/Engineering/_git/OpenPublishing.Build/pullrequest/8942?_a=files&path=%2FApplications%2FGitCommitHistoryResolver%2FGitCommitUpdateTimeResolver%2FGitCommitUpdateTimeResolver.cs&discussionId=60072

**Comment by OsmondJiang** [comment]
Reopen since the contributor list generated in PR build is different with commit build, @yufeih  is working on the fix.

 
![image](https://user-images.githubusercontent.com/19990166/54892647-41d1e080-4eed-11e9-94af-892826a559ae.png)
