### ISSUE TITLE
restore and gc improvement 

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3995]
The `restore` is to **add and forget** and `gc` is to **delete**, considering the work **tree size** and check-out speed, we may want to **re-use** instead of **delete**.

re-use existing work-tree of git can help us reduce the disk size and improve the checkout speed, this actually also fits the dependency files.

But this solution need track usage status of each work tree, not a status-less design.

**Comment by OsmondJiang** [comment]
work items:
- [ ] read/write lock cross process
- [ ] pooling model of git work tree
- [ ] pooling model of downloaded file

**Comment by yufeih** [comment]
Do we still need pooling for downloading files?

**Comment by fenxu** [comment]
If the architecture is totally same, reuse that is not bad. However, if it needs more effort, it may not be necessary.

**Comment by OsmondJiang** [comment]
totally same

**Comment by OsmondJiang** [comment]
and in-process reader writer lock doesn't async/await, which doesn't meet our requirement, i am going to first implement an simple shared/exclusive lock using file system.

@yufeih  @fenxu  @herohua
