### ISSUE TITLE
clean up environment variables used in docfx

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4003]
there is one question need to be answered before the cleaning up:

    `What should be in environment variables/command options/config?`

@fenxu @yufeih @herohua 

Current environment variables:
```C#
public static class EnvironmentVariable
{
        public static string GlobalConfigPath => Environment.GetEnvironmentVariable("DOCFX_GLOBAL_CONFIG_PATH");

        public static string AppDataPath => Environment.GetEnvironmentVariable("DOCFX_APPDATA_PATH");

        public static string RepositoryUrl => Environment.GetEnvironmentVariable("DOCFX_REPOSITORY_URL");

        public static string RepositoryBranch => Environment.GetEnvironmentVariable("DOCFX_REPOSITORY_BRANCH");
}
```

**Comment by yufeih** [comment]
`-` is a file name convention used by some programs to refer to `stdin`, maybe we could leverage this to get rid of temp config file?

```bash
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-less
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000"
EOF
```

**Comment by yufeih** [comment]
There are 3 ways to configure docfx: command line arguments, config files and environment variables. Right now these are 3 separate channels and has each own definition. 

To support the flexibility of configuring docfx, we'd like to unify the config definition using an override model:

- All 3 channels share the same config definition in  `Config.cs`
- __command line args__ overrides __config file__ overrides __environment variable__
- Flatten configs as much as possible to make it cmd and env var friendly
- When the value is an object, use `.` as separator in key, escape `.` with `\.`, e.g. `--http.https://github\.com.headers.authorization XXXX`
- All secrets __MUST__ ends with `token` or `authorization` and are masked from outputs

### Command line arguments:
- Follows `lower-kebab-casing` 
> Json.Net naming strategy can help convert between these naming conventions
- Array values are handled by passing the option multiple times, e,g, `--xref 1.json --xref 2.json`
- Use the awesome [System.CommandLine](https://github.com/dotnet/command-line-api/wiki/Your-first-app-with-System.CommandLine)
- No every option needs to show help text, use `[CommandLineOption]` to opt in:

```csharp
[CommandLineOption("-o|--output", "The output path")]
public string OutputPath;

public bool Legacy;
```

### Config file
- Follows `lower_snake_casing`
- __repo config__ overrides __extend config__ overrides __global config__

### Environment variables
- Follows `UPPER_SNAKE_CASING` and are prefixed with `DOCFX_` 
- Array values are separated by `,`, e.g. `DOCS_XREF=1.json,2.json`

> Note for `Docs.Build`, environment variables uses the same name but with `DOCS_` prefix so we can batch feed environment variables to docfx.

**Comment by herohua** [comment]
Questions:
1. Naming convention
2. Does `global config` follow same schema with other config level? or do we need a different schema?
3. Need clear definition and guild lines of targeted scenarios and audience, including Docs.Build, local dev env, machine level, etc.
4. Does Docs.Build need to overwrite `repo config file`? Example: for testing purpose, it is needed to specify XREF service endpoint that is different from other repos in the same service env.
5. Where does feature flag live? Example: need PR preview flag, or resolve GitHub user.
6. Flatten configs need case-by-case design.
7. Do we need both `extend config file` and `global config file`?
8. Localization override config scenario needs to fit into this design (last item).

**Comment by fenxu** [comment]
The following part is summaries of current feature flag set in global. (Remove some that must not be used.) Please take a look and comments.

| Global Config Name | Current Functionality | Change in Future docs-pipeline |
| --- | --- | --- |
| DefaultBuildToolLogLevel | Different log level for build tool | Deprecated |
| DefaultErrorLogCodes, DefaultWarningLogCodes, DefaultSuggestionLogCodes, DefaultInfoLogCodes | Default log codes for different level, they are used to customized log level on service side conveniently | Embeded in docfx code |
| DefaultLogCodesToIgnore | log codes to ignore by default | Embeded in docfx code |
| NeedPreviewPullRequest | Indicate whether globally enable PR preview or not | Embeded in docs-pipeline code |
| BatchPublishToDHSParallelism | DHS batch publish parallelism count | Put in docs-pipeline global config |
| ContinueWithDocumentError | Indicate whether globally continue publish with document error | Put in docs-pipeline global config, can be overwrite by config |
| EnableCustomValidation | Indicate whether to enable custom validation globally | Get from Validation Service |
| RemoveResourceFilesInOutputPackage | Indicate whether to remove resource files in output package to reduce size | Deprecated, always remove |
| ResolveVsoRepoUserProfileUsingGitHub | Indicate whether to use GitHub user to resolve VSTS user profile | Deprecated. Decide only by public GitHub pair information. |
| UpdateGlobalGitUserProfileCache | Indicate whether to update git user profile after user profile expired. | Embeded in docfx code |
| UseMarkdigAsDefaultMarkdownEngine | Indicate whether to use markdig as default markdown engine | Deprecated |
| UseGlobalGitUserProfileCache | Indicate whether to use service account for sync | Always true for server. Local build TBD |

cc @herohua @yufeih @OsmondJiang @superyyrrzz @live1206 @mingwli @928PJY

**Comment by herohua** [comment]
I guess we still need discussion and following up on this one. Remove milestone of 2019-06.

@yufeih @OsmondJiang

**Comment by herohua** [comment]
@yufeih : please write an overall design doc and share with the team.
