### ISSUE TITLE
Feature request: C# 8 support

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#4007]
C# 8 is now "somewhat available" via previews of .NET Core 3.0 SDK and Visual Studio 2019.

Currently I've observed the following issues using 2.40.6:

- Switch expressions confuse docfx so that it doesn't process a member that uses them or any subsequent member (at least in some cases - I haven't looked closely)
- Nullable reference type parameters end up using `Nullable<...>` incorrectly in the uid.

I'm not at all surprised that C# 8 doesn't work out of the box, but I thought I'd express a feature request as somewhere to collect progress. I'd be very happy to test workarounds, experimental builds etc.

**Comment by roji** [comment]
Just spent a couple hours tracking this down... Confirm that any switch expression causes docfx to not recognize subsequent members. If this cannot be fixed immediately, may I at least suggest checking for a project's LangVersion and issuing a warning about it, to save people the time and frustration...

```c#
/// <summary>
/// This works: <see cref="SomeMethod"/>.
/// This does not work: <see cref="Foo.SomeOtherMethod"/>.
/// Generates: Invalid cref value "!:Foo.SomeOtherMethod" found in triple-slash-comments for Foo defined in Foo.cs Line 8, ignored.
/// </summary>
public class Foo
{
    public void SomeMethod(int a)
    {
        var x = a switch
        {
            1 => 2,
            2 => 3,
            _ => throw new ArgumentException()
        };
    }

    public void SomeOtherMethod() {}
}
```

**Comment by superyyrrzz** [comment]
@roji Thank you for the thoughts. The warning makes sense for the first step.

**Comment by superyyrrzz** [comment]
With C# 8.0 officially released with .NET Core 3.0, this feature is essential now. Due to our team's limited resources, this feature needs community users' contribution. Feel free to create a pull request to address one or all of the issues found. Thank you in advance!

**Comment by roji** [comment]
Any timeline update on this? docfx is an important part of the .NET ecosystem and is used by many OSS projects out there - keeping this a modern, functional building block is really important.

**Comment by yufeih** [comment]
We now support C# features up to C# 11 in the latest version.
