### ISSUE TITLE
v3 migration tool: what rules are there for content fix

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#4013]
using this to track fix applied to repo content.

1. redirections in yaml header
    - delete *.md file
    - add to .redirections.json

2. invalid redirect_document_id to false
    - turn redirect_document_id to false when it contains bookmark or query

3. ~~duplicate yaml header~~ (we decided to disable this rule)
    - only keep the last (limitation applies - can only deal with scalar type)
    - if not fixed: may cause ⚠`yaml-dupliacate-key`  suggestion

4. ~~reserved yaml header with upper/lower cased issue (only applies to Docs recognized metadata keys)~~ (we decided to disable this rule)
    - keep the last key line (**if of same casing in schema, use that casing; if not, use last one**)
    - use the lower cased line's value
    - apply to all reserved file-metadata keys
    - reserved keys: ['layout', 'locale', 'title', 'author', 'moniker_range', 'uid']
    - this fix is disabled by default

5. markdown toc incorrect syntax
    - leading `#[` => `# [`
    - trailing `)#` => `) #`
    - if not fixed: may cause ❌`invalid-toc-syntax` error
6. markdown toc link file name white space
    - [link](file name.md) => `[link](file%20name.md)`
    - if not fixed: may cause ⚠`file-not-found` warning
7. yaml toc homepage(home page is deprecated, this change guarantee the node stay the same in output)
    - for a toc node with absolute homepage & href
      a. homepage -> renamed as topicHref
      b. href            -> renamed as tocHref (if value is absolute path, to be compatible with v2)

**Comment by herohua** [comment]
@mingwli , can you help update this list as recently we implemented more rules?
