### ISSUE TITLE
Indentation not being processed when using external <code> source

### ISSUE THREAD

**Issue by Still34** [dotnet/docfx#4017]
**DocFX Version Used**: 
2.40.10
**Template used**: (`default` or `statictoc` or contain custom template)
`default` + [custom theme set](https://github.com/discord-net/Discord.Net/tree/dev/docs/_template/light-dark-theme)
**Steps to Reproduce**:

1. Write a code with normal tab indentation 
2. Reference such code with an `<code>` tag in xml docs of a native method
3. Build & serve

**Expected Behavior**:
Indentations to be kept

**Actual Behavior**:
All indentations are removed as shown below
![image](https://user-images.githubusercontent.com/5843208/52327077-c17f1b00-2a25-11e9-9b24-c5f5ad4d8a98.png)

**Code used**:
XML docs reference
```cs

        /// <example>
        ///     <code source="..\Discord.Net.Examples\WebSocket\BaseSocketClient.Events.Examples.cs" region="MessageDeleted"></code>
        /// </example>
```

Example `<code>` 
```cs
#region MessageDeleted
public void HookMessageDeleted(BaseSocketClient client)
{
    client.MessageDeleted += HandleMessageDelete;
}
public Task HandleMessageDelete(Cacheable<IMessage, ulong> cachedMessage, ISocketMessageChannel channel)
{
    // check if the message exists in cache; if not, we cannot report what was removed
    if (!cachedMessage.HasValue) return;
    var message = cachedMessage.Value;
    Console.WriteLine($"A message ({message.Id}) from {message.Author} was removed from the channel {channel.Name} ({channel.Id}):"
        + Environment.NewLine
        + message.Content);
    return Task.CompletedTask;
}
#endregion
```

**Comment by superyyrrzz** [comment]
DocFX has some logic to remove extra leading spaces. In this case when some embedded code exists, it removes more than needed... 

Related code:
https://github.com/dotnet/docfx/blob/da48dd4c820f4b15dbcf4cc350ab68fabc5292b4/src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Parsers/TripleSlashCommentModel.cs#L700

**Comment by superyyrrzz** [comment]
Add that we can reproduce this issue easily by dedent the following text by 4 spaces in the test:

https://github.com/dotnet/docfx/blob/380f21e70b46914656d0c3f7e9698bcef6dcbb19/test/Microsoft.DocAsCode.Metadata.ManagedReference.Tests/TripleSlashParserUnitTest.cs#L30-L36
