### ISSUE TITLE
Package installation fails looking for Microsoft.DotNet.ProjectModel.Workspaces

### ISSUE THREAD

**Issue by iosgitr** [dotnet/docfx#4018]
**DocFX Version Used**: 2.40.10

**Template used**: `default`

**Steps to Reproduce**:

1. Create empty C# class library project in VS 2017 15.9.4 targeting .NET Framework 4.6.2.
2. Using NuGet manager within VS project, attempt to add `docfx` (not `docfx.console`) package version `2.40.10`. 

**Expected Behavior**:

Package is installed without error.

**Actual Behavior**:

Error will be displayed in VS error list:  

> Unable to resolve dependency 'Microsoft.DotNet.ProjectModel.Workspaces'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.

I tried finding `Microsoft.DotNet.ProjectModel.Workspaces` on nuget.org and it looks like it's only available as a preview package:  https://www.nuget.org/packages/Microsoft.DotNet.ProjectModel.Workspaces/

Incidentally, installation and use of `docfx.console` works fine.

**Comment by superyyrrzz** [comment]
As described in the [document](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#3-use-docfx-integrated-with-visual-studio), you should use `docfx.console`.
