### ISSUE TITLE
Investigate publish performance

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4021]
Pull request publish of azure docs takes almost 10 minutes and it is increasing. Investigate and see where went wrong.

**Comment by OsmondJiang** [comment]
![image](https://user-images.githubusercontent.com/19990166/52605869-780e5000-2eab-11e9-90f0-592121126be1.png)
Log show it takes 4-5 minutes to get all documents back from DHS,

**Comment by OsmondJiang** [comment]
comparing with [log](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C1%5C30%5C0c07d4eb-0562-6512-9227-12dbf89d9a0f%5CCommit%5C201901300600534885-markdig-migration-with-docfx-v3%5Crawlog.txt?sv=2015-02-21&sr=b&sig=T%2FszGPTb1a6fJmxaYHtUq04hx%2FcfsVsb%2BJqrG2%2Fi%2Fgo%3D&st=2019-01-30T06%3A06%3A59Z&se=2019-03-02T06%3A11%3A59Z&sp=r), we found truly the perf issue was cased by "API to DHS";

![image](https://user-images.githubusercontent.com/19990166/52614991-7d30c680-2ece-11e9-90b7-20a1bcb6b2cf.png)

**Comment by yufeih** [comment]
Close this to track the work in #3793
