### ISSUE TITLE
Dependency missing for linux

### ISSUE THREAD

**Issue by pietervdvn** [dotnet/docfx#4043]
**DocFX Version Used**: 

docfx 2.40.10.0

**Template used**: `default`

**Steps to Reproduce**:

1. Unzip docfx somewhere on an Ubuntu machine
2. Run `mono docfx init`  in a project (which works)
3. Run docfx metadata: crashes

**Expected Behavior**:

Metadata is generated

**Actual Behavior**:

Crash with complaints that `SQLitePCLRaw.core` could not be loaded

** Workaround **

I installed SQLitePCLRaw.core in a different project and copied the 'Netstandard1.0' dll file into the directory containing docfx.exe. Everything worked fine afterwards
Perhaps include this by default in the stable release zip too?

**Comment by superyyrrzz** [comment]
Duplicate with #3389
