### ISSUE TITLE
Use named mutex for cross process locking

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4047]
Right now we are using file locks to synchronize cross process access to a shared resource. The current implementation is not robust on linux/mac, a dangling lock file is left on file system whenever the process is crashed or terminated by `Ctrl+C`.

We could instead use global named mutex, it works across platform and survives process crash.

**Comment by OsmondJiang** [comment]
```
new FileStream(
                    lockPath,
                    FileMode.CreateNew,
                    FileAccess.ReadWrite,
                    FileShare.None,
                    1,
                    FileOptions.DeleteOnClose)
```

we are using DeleteOnClose, so the file should be deleted even the docfx crashed, which platform are you testing?

**Comment by OsmondJiang** [comment]
i see, you are testing on linux and mac

**Comment by OsmondJiang** [comment]
windows can always clean the file: https://stackoverflow.com/questions/324045/windows-temporary-files-behaviour-are-they-deleted-by-the-system

**Comment by OsmondJiang** [comment]
https://stackoverflow.com/questions/46302756/in-dotnet-core-how-can-i-ensure-only-one-copy-of-my-application-is-running?answertab=votes#tab-top

**Comment by yufeih** [comment]
The platforms we are targeting are windows, mac (authoring environment) and linux (potential production environment). Unix is currently not a target.

**Comment by OsmondJiang** [comment]
if we change it to that way, we may also want to have Shared Lock and Exclusive Lock.
