### ISSUE TITLE
invisible metadata

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#4050]
There is a difference in metadata.page between v2 and v3 output
![image](https://user-images.githubusercontent.com/5196139/53063743-29dafb80-3500-11e9-8ff0-9a075b2e3cb6.png)

In docfx v2, there is plug-in to take care of metadata.html rendering, which refers to `op_schema.json` with schema visibilities: [helpviewer_keywords](https://ceapex.visualstudio.com/Engineering/_git/OpenPublishing.Build?path=%2FLibraries%2FSchemaValidation%2Fop_schema.json&version=GBdevelop&line=1027&lineEnd=1028&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)

**Comment by yufeih** [comment]
The list is right now kept at [here](https://github.com/dotnet/docfx/blob/v3/src/docfx/template/TemplateTransform.cs#L21).

How about first populate that list with `op_schema.json` then consider supporting `is_visible` in metadata validation?

**Comment by live1206** [comment]
> The list is right now kept at [here](https://github.com/dotnet/docfx/blob/v3/src/docfx/template/TemplateTransform.cs#L21).
> 
> How about first populate that list with `op_schema.json` then consider supporting `is_visible` in metadata validation?

sounds like a plan 👍
