### ISSUE TITLE
How to see detailed error message?

### ISSUE THREAD

**Issue by rix0rrr** [dotnet/docfx#4057]
**DocFX Version Used**:  2.40.11.0

**Template used**: custom template 

**Steps to Reproduce**:

I undoubtedly have a mistake in my template, either in the JavaScript or in the Mustache. I can't tell. The problem is very much that I can't tell what the problem is, because DocFX doesn't show me any error message. This is what I see a 100 times:

```
[19-02-20 03:05:17.969]Error:[BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply Templates](api/Amazon.CDK.AWS.KMS.EncryptionKeyAliasProps.yml)Error transforming model "/var/folders/y2/gfhldsms0bdbck1zjl2647gnr9xt2d/T/docfx/rawmodel/api/Amazon.CDK.AWS.KMS.EncryptionKeyAliasProps.raw.json" generated from "api/Amazon.CDK.AWS.KMS.EncryptionKeyAliasProps.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor: 
```

I have no idea how to use the tool to give me more details on the error it encountered.

**Expected Behavior**: Error message and stack trace tells the cause of the error (JavaScript error message, or otherwise). I noticed that if I do `throw new Error(...)` in the transformer I do see the error message, so I must have hit a messageless error, for which the lack of stack trace is causing me a problem right now.

**Actual Behavior**: Error message tells me there is a problems *somewhere* in the (potentially large) file.

**Comment by superyyrrzz** [comment]
Yes, it is really hard to debug these JS codes in [Jint](https://github.com/sebastienros/jint) engine DocFX is using. Usually I use Node.js to get more detailed stack trace. You can try this: https://github.com/docascode/docfx.js.test

**Comment by ch-hristov** [comment]
We have the same problem ending in a stackoverflow exception.

**Comment by KalleOlaviNiemitalo** [comment]
One annoying case is when JavaScript code tries to evaluate `foo.bar.baz` where `foo.bar` does not exist. In Jint 2.5.0, `Jint.Runtime.ExpressionInterpreter.EvaluateMemberExpression` then calls `Jint.Runtime.TypeConverter.CheckObjectCoercible` and that throws `new JavaScriptException(engine.TypeError)` without any details. The `Exception.Message` is an empty string and that's what DocFX displays. `JavaScriptException.Error` is a JavaScript object that has `{ "name": "TypeError" }`, which is not much more informative.

Jint 2.11.10 has the same implementation there as Jint 2.5.0. The dev branch however seems to throw better exceptions in this case, thanks to sebastienros/jint#408 and sebastienros/jint#466.

**Comment by superyyrrzz** [comment]
@KalleOlaviNiemitalo Thank you for the information! We tried v2.10.3 before but met https://github.com/sebastienros/jint/issues/364, then we reverted back to v2.5.0. Looks like it is time to upgrade Jint once these changes released.

**Comment by lahma** [comment]
Now that support for Jint 3.x was added I think you should see better error messages, this is something that has been worked on even after the issues mentioned above.
