### ISSUE TITLE
JavaScript errors during module load are swallowed

### ISSUE THREAD

**Issue by rix0rrr** [dotnet/docfx#4058]
**DocFX Version Used**: 2.40.11.0
Mono JIT compiler version 5.18.0.240 (2018-08/5266e6a8f10 Tue Jan 15 21:54:10 EST 2019)
Mac

**Template used**: custom

**Steps to Reproduce**:

Add the following to the top of `ManagedReference.html.primary.js`:

```
throw new Error('booh');
```

**Expected Behavior**: Running the renderer causes an error, preferably showing the error message "booh" and a stack trace.

**Actual Behavior**: An empty page is rendered.

**Comment by superyyrrzz** [comment]
I can see you adds this for debug purpose. Can this help you debug? https://github.com/dotnet/docfx/issues/4057#issuecomment-465826793
