### ISSUE TITLE
content files for API not generated

### ISSUE THREAD

**Issue by aggieben** [dotnet/docfx#4064]
**DocFX Version Used**: 2.40.11

**Template used**: `default`

**Steps to Reproduce**:
I have a .NET project structured in the typical way, but with `docsrc` sitting next to `src`, where `docsrc` is my docfx project folder, and `src` has all the source code for my project.

1. docfx init
2. follow steps
3. modify docfx.json slightly
4. run `docfx docsrc/docfx.json -o $tmpdir`

**Expected Behavior**:
Contents of $tmpdir should be `_site`, with all content underneath

**Actual Behavior**:
Contents of $tmpdir.  See that `api` contains only the metadata, not the generated html I was expecting, and it's also a sibling directory of `api` rather than a child as I was expecting.  This is the thing that has me the most confused.

![image](https://user-images.githubusercontent.com/1321/53162560-dfa25a80-3591-11e9-880c-f8ed18e59b4b.png)

The difference between my docfx.json and the one generated by `docfx init`:

![image](https://user-images.githubusercontent.com/1321/53162533-d6b18900-3591-11e9-9b43-c86da4b1ba80.png)

**Comment by superyyrrzz** [comment]
Could you try splitting your command into 2?
```
docfx metadata docsrc/docfx.json
docfx build docsrc/docfx.json -o $tmpdir
```

The reason behind is a docfx design defect, that  `-o` option does not work well when executing docfx without subcommand. When you run `docfx docsrc/docfx.json`, internally it runs 2 subcommands `metadata` and `build`. `build` relies on result of `metadata`. However, if you run `docfx  docsrc/docfx.json -o $tmpdir`, it is equivalent to:
```
docfx metadata docsrc/docfx.json -o $tmpdir
docfx build docsrc/docfx.json -o $tmpdir
```
This make `metadata` also output to the place you want to see html pages, while `build` cannot find these intermediate YAMLs.

**Comment by aggieben** [comment]
@superyyrrzz awesome, thank you.  That appears to have cleared things up for me.
