### ISSUE TITLE
Support schema driven documents from JSON schema

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4067]
### Phases
- 1️⃣ Support Conceptual SDP like `ContextObject`, `LandingData`
  - Page Model to generate `.raw.page.json` + `.meta.json`
  - Data Model to generate `.json`
- 2️⃣ Support Reference SDP without fragments like `OData`
- 3️⃣ Support Reference SDP with fragments.

### Feature Scope
- 1️⃣  Integration with Template json schema
  - Load json schema from Template.
  - Apply template to docfx output model.
  - Pre-process template to adapt the new output model and pipeline.
  - Local debugging and testing
- 1️⃣  Json Schema validation(#4567)
  - Some basic rules implementation.
  - Testing.
- 1️⃣  Json Schema Transform
  - Support Kinds of `content-type`
    - Markdown
    - InlineMarkdown
    - Href
    - Html
    - Xref
      - Transform xref from string to xrefSpec.
  - Testing
- 2️⃣  Build Internal Xref Map
  - Retrieve UIDs
    - Validate duplicated uid in same file.
    - Validate duplicate uid cross whole repo.
  - Get all uid and corresponding xref properties based on `XrefProperties`
    - Support leaf nodes only? @yufeih  @live1206 
    - Monikers(dotnet files)
  - Output internal xref map files.
- 2️⃣  Resolve and export XREF map by versioning
  - Respect versioning defined in config
  - Respect versioning defined per file (metadata)
  - Respect versioning defined in node (dotnet files)
- 1️⃣  Setup Integration Test and Migration Test
  - Setup integration test
  - Setup migration test
- 3️⃣  Support fragments
  - UNKNOWN
- Legacy
  - 1️⃣ Keep landing data working for a while
  - Future clean up

### Json schema validation

- [x] Json schema validation (#4567)

### Json schema transform

- [x] Basic content type transforms Html/Markdown/InlineMarkdown/Link
- [x] Basic content type testing

### Template integration

- [x] Allow template from local folder (#4559)
- [x] Read schema from template
- [x] Run JINT and mustache (both optional)
- [ ] Handle `data-linktype` for links in mustache template if template is pushed futher down the stack

### Xref handling

- [ ] Build Xref Map from XrefProperties
  - [x] Respect `XrefProperties` defined in JSON schema
  - [x] Confirm whether we need support non-root level xref properties
  - [ ] output xref map of sdp pipeline
  - [x] performance improvement (share transforming result between transforming xref and building page)
  
- [ ] Transform for content type `xref`
  - [x] Transform `xref` property to `xrefSpec`(string to object)
  - [ ] Prepare process [mustache](https://github.com/MicrosoftDocs/engineering/blob/master/engineering/projects/ops/template-changes.md#mustache)
  - [ ] Apply prepare processed mustache with generated `xrefSpec` to generated html

### Landing data handling

- [x] Keep LandingData work for a while

### Future clean up

- [ ] Remove Razor rendering, using template instead (future, after LandingData moves to SDP)
- [x] Remove Strong Model (future, after LandingData moves to SDP)
  - [x] Remove Strong Model Kinds of Attributes
  - [x] Remove Strong Model Class
- [x] Remove schema validation on `JsonUtility/YamlUtility.ToObject` (migrate TOC validation)

**Comment by OsmondJiang** [comment]
# Xref Handling

- [ ] Build Xref Map from XrefProperties
  - [ ] Respect `XrefProperties` defined in JSON schema
  - [ ] Confirm whether we need support non-root level xref properties

Schema Example:
```json
{  
   "properties":{  
      "description":{  
         "type":"string"
      }
      ...
   },
   "xrefProperties":[  
      "description",
      "remarks",
      "name",
      "type"
   ]
}
```

Xref transform will build all properties(transformed) defined in xrefProperties into xref spec, constitute a xref map group by uid:

```json
{  
   "uid-1":{  
      "href":"uid-href",
      "monikers":[  
         "dotnet-2.0"
      ],
      "properties":{  
         "description":"uid description"
      }
   }
}
```

- [ ] Transform for content type `xref`

Schema Example:
```
{  
   "properties":{  
      "name":{  
         "type":"string",
         "contentType":"xref"
      },
      "binding_type":{  
         "type":"string"
      }
   }
}
```

**Comment by mingwli** [comment]
# Template Integration

```raw
  | ✔ Read SDP file schema |
            🔻
            🔻
  | ⭕ Resolve json schema from template |
            🔻
            🔻
  | ✔ Schema validate & transform => raw model |
            🔻
            🔻
  | ⭕ Resolve template & Run Jint + Mustache |
  | ✔ I schema.json.js => '.json'| ?
  | ❌ I schema.json.tmpl |
  | ✔ II schema.mta.json.js => '.mta.json' |
  | ❌ II schema.mta.json.tmpl |
  | ✔ III schema.html.primary.js + schema.html.primary.tmpl => 'html content' | ➡ OutputModel.content ➡ 'raw.page.json'
  (* 'schema.json.js' and 'schema.html.primary' won't be used together)
```

**Comment by herohua** [comment]
@OsmondJiang @mingwli We may need a separate item on bookmark validation for SDP.

**Comment by herohua** [comment]
phase 1 is now being tracked by https://dev.azure.com/ceapex/Engineering/_workitems/edit/95863

phase 2: https://dev.azure.com/ceapex/Engineering/_workitems/edit/102269
