### ISSUE TITLE
API Documentation TOC Navigation Bar Not Loading On Google Chrome

### ISSUE THREAD

**Issue by connorheyz** [dotnet/docfx#4077]
**DocFX Version Used**: Chocolatey Package `20.40.11`

**Template used**: `default`

**Steps to Reproduce**:

1. Create a DocFX project and run the `docfx` command.
2. open `api/index.html` in Google Chrome

**Expected Behavior**:
The website should appear just as it does on firefox. The navigation bar on the left should render.

Firefox's render: https://gyazo.com/40a4da9ff049f88bde72e87b26ef37a6 

**Actual Behavior**:
The navigation bar does not load at all on Google Chrome.

Google Chrome render: https://gyazo.com/1b9d7d1a2b00987280ad1b42a2b8d1ac

**Edit 1 (Details)**: I have pinpointed the error. Google Chrome throws errors on line four of `docfx.vendor.js` saying that 
```
Access to XMLHttpRequest at 'file:///_site/api/toc.html' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```
The error is thrown on this specific chunk.  (4:15009)
```js
try{f.send(a.hasContent&&a.data||null)}catch(h){if(b)throw h}}
```

**Comment by superyyrrzz** [comment]
I cannot reproduce the issue. It may fix this if you use `docfx serve` instead of open `.html` files directly.

**Comment by connorheyz** [comment]
I used docfx --serve and it fixed it. Thanks
