### ISSUE TITLE
GitException on GetFileDetail: Timeout (1000ms) exceeded

### ISSUE THREAD

**Issue by Bhawk90** [dotnet/docfx#4094]
**DocFX Version Used**: 2.4.10

**Template used**: `default`

I am experiencing a strange issue which I have encountered when using **DocFX** with **Mono** inside of a **docker container**.  When building the HTML files in a local environment or a Linux VM, the "Improve this Doc" appears properly. However if I attempt to build from the same source repository using the same files, the link does not appear.

I receive the following warnings during the build process:
```sh
[19-02-05 09:39:45.787]Warning:[BuildCore.Build Document.Load.TocDocumentProcessor](articles/toc.md)Skipping GetFileDetail. Exception found: Microsoft.DocAsCode.Common.Git.GitException, Message: The result can't be null or empty string
[19-02-05 09:39:45.787]Warning:[BuildCore.Build Document.Load.TocDocumentProcessor](articles/dynamics/toc.md)Timeout (1000ms) exceeded. Killing process /usr/bin/mono-sgen.
```

For some reason the commands defined in `Microsoft.DocAsCode.Common/Git/GitUtility.cs` cannot run within the 1000 ms timeout limit. On the other hand if I run the build process again once or twice, the warnings do not appear and it can build properly, maybe because of some caching.

Would it be possible to somehow increase the timeout to a higher value using a command line parameter? Or did anyone encounter such issues when generating HTML files using DocFX from a Docker Container?

**Steps to Reproduce**:

1. Set up a Docker Container with Mono and download version 2.4.10 of DocFX
2. Clone GitLab repository containing Markdown files and docfx.json
3. Build html files with docfx.exe docfx.json

**Expected Behavior**:
The HTML files should be generated properly as on a local environment or virtual machine when configured correctly.

**Actual Behavior**:
The git information for each file cannot be retrieved for the first time because of the 1000 ms timeout set in `Microsoft.DocAsCode.Common/Git/GitUtility.cs` and the 'Improve this Doc' link does not appear, but it works properly in a local environment without any configuration changes.

Thank you very much in advance!

**Comment by superyyrrzz** [comment]
@Bhawk90 Does `git` exist on your container? `GitUtility` requires this. 

Of course, the timeout is not ideal and need fix.

**Comment by Bhawk90** [comment]
@superyyrrzz Of course, we use `git clone` to retrieve the contents of the repository. As I have mentioned the command always receives a timeout for the first time, but after a second/third run it can generate all the files without a problem.

The strange thing is that we have tried to run all the commands found inside `GitUtility.cs` before running `docfx` and none of them took more then 1000 ms to run.

**Comment by ms-kgorgi** [comment]
@superyyrrzz We are experiencing a this issue with our build system using docfx integrated with Visual Studio (.NET class project). We are using docfx 2.57.2.

**Comment by ms-kgorgi** [comment]
I performed some more investigation and the underlying cause is that for our build/repo git operations commonly take longer than 1 second. It is also unlikely that we can get the git operations to under 1 second. 

To fix this issue, I think the two options are:

1. Make the timeout a configurable parameter instead of a hardcoded value
2. Add retry logic with a much larger and exponentially increasing timeout

**Comment by yufeih** [comment]
1 looks like a good approach. We could have an environment variable to configure the timeout. Anyone interested in proposing a PR?

**Comment by WeihanLi** [comment]
Is there any proposed environment variable name for this? How about `DOCFX_GIT_TIMEOUT`?
