### ISSUE TITLE
Question: How can I hide attributes in output

### ISSUE THREAD

**Issue by StephanHartmann** [dotnet/docfx#4110]
**DocFX Version Used**: 2.40.10

**Template used**: `statictoc` with modified partials

**Steps to Reproduce**:
I have the following code in a c# project

```
/// <summary>
/// column definitions
/// </summary>
[Description("Column Definitions"), Category(FlexConstants.catSettings), DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
[MLCodeCompletion]
public FlexColumnCollection Columns { get; }
```
Here is produced output

![image](https://user-images.githubusercontent.com/10873640/53784323-30f90500-3f15-11e9-8c40-0b2531ccea0d.png)

The output is fine, but I don't want to have [MLCodeCompletion] attribute shown.
How can I hide this attribute?

I looked in the class.tmpl.partial file, but from my understanding this is all included in `{{syntax.content.0.value}}`, isn't it?

```
<h5 class="decalaration">{{__global.declaration}}</h5>
{{#syntax}}
<div class="codewrapper">
  <pre><code class="lang-{{_lang}} hljs">{{syntax.content.0.value}}</code></pre>
</div>
```

Is this hard coded inside docFX or is there a chance to change this ?

**Comment by superyyrrzz** [comment]
You are right. DocFX hard coded this so it cannot be removed with a simple template change.

**Comment by superyyrrzz** [comment]
You can use api filter to achieve this. Example: https://github.com/dotnet/docfx/blob/dfbe97999c941aa7e854159e6d66bc54b7747796/src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Filters/defaultfilterconfig.yml#L7

api filter doc: https://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html

**Comment by StephanHartmann** [comment]
Thank you, this is working fine.
