### ISSUE TITLE
Use v3-release branch to track internal production releases

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4116]
The proposal is to use `v3` for internal sandbox environment, and `v3-release` for internal production environment. They both use `docfx 3.0.0-beta-xxx` versioning but publish to different feeds.

@fenxu @OsmondJiang @superyyrrzz  @herohua

**Comment by OsmondJiang** [comment]
`v3` is publishing to sandbox feed, triggered by `pr merging into v3` and `impact change pr merge`.

`v3-release` is publishing to prod feed, only triggered by 'pr merging into v3-release'.

@yufeih  @fenxu  @herohua
