### ISSUE TITLE
Anchor links scroll under navbar

### ISSUE THREAD

**Issue by Thraka** [dotnet/docfx#4137]
**Operation System**: Windows

**DocFX Version Used**: 2.40.11.0

**Template used**: `default` and my own template. Saw this on my template, removed it and verified it happens in default.

**Steps to Reproduce**:

1. Click this link: http://sadconsole.com/api/SadConsole.Console.html#SadConsole_Console_Cursor
2. You'll notice that `Cursor` property is under the breadcrumb bar

**Expected Behavior**:
The main content shouldn't scroll under the navbar or the link should always scroll to below the navbar.

**Actual Behavior**:
A header is under the navbar and cannot be seen. 

If you use the right-side navbar, the first click on a level 2 item correctly scrolls, but if you click the item again the item appears under the navbar again.

**Comment by superyyrrzz** [comment]
Close as duplicate with #3133 

BTW, I like your site's theme 😊
