### ISSUE TITLE
title with tag like <name> will be rendered incorrectly

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4144]
![image](https://user-images.githubusercontent.com/19990166/54103464-7e8adb80-4407-11e9-8d60-fd9b8ea19e99.png)

Example Page: https://docs.microsoft.com/en-us/office/vba/access/concepts/miscellaneous/duplicate-output-alias-nameerror-3062

Original Content: https://raw.githubusercontent.com/MicrosoftDocs/VBA-Docs/master/access/Concepts/Miscellaneous/duplicate-output-alias-nameerror-3062.md

**Comment by OsmondJiang** [comment]
But the behavior seems like to be same with GITHUB rendering:

![image](https://user-images.githubusercontent.com/19990166/54103597-f9ec8d00-4407-11e9-82a2-250c82094be9.png)

**Comment by superyyrrzz** [comment]
As discussed, both the result of v2 and v3 comply to commonmark. See: https://babelmark.github.io/?text=%23+Duplicate+output+alias+%3Cname%3E.+(Error+3062) It depends whether we check `Normalize`.
