### ISSUE TITLE
migration tool: decide whether to build & publish unreferenced images

### ISSUE THREAD

**Issue by herohua** [dotnet/docfx#4154]
Currently, unreferenced images are not being built and published by default. Let's change the behavior to let users explicitly opt-in for this feature. Potential changes:

- [x] change of migration tool to keep v2 config on resources
- [x] change of diff tool to compare manifest without ignoring resource files

**Comment by mingwli** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.MigrationTool/pullrequest/9640?path=%2Ftest%2Ftest-drops%2Fe2e-test&_a=overview

**Comment by yufeih** [comment]
@herohua , did you observe any problems with dropping off unreferenced resources? could we turn dropping unreferenced resources by default and provide an opt-out during v3 migration?

**Comment by mingwli** [comment]
#4162

**Comment by mingwli** [comment]
https://apidrop.visualstudio.com/Content%20CI/_git/docfx-v3-migration/pullrequest/380?_a=overview
