### ISSUE TITLE
extra log InvalidInternalBookmark <h1> bookmark reference

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#4155]
Throw extra log when user references internal h1(title) using `#title` syntax.  
Take [accessibility.md](https://github.com/OPS-E2E-PPE/edge-developer/blob/master/microsoft-edge/devtools-guide/elements/accessibility.md) for example.  

The corresponding v2 report here:  
https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C3%5C11%5C7c569200-a1a3-d648-647b-fdb9da8d8241%5CCommit%5C201903110706279648-master-docfx-v3-migration%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JZDU6Ro%2Bw95PWbXIVxr6obzHaRhm7K%2Fms%2FqRJ2%2F4pUE%3D&st=2019-03-13T07%3A16%3A12Z&se=2019-04-13T07%3A21%3A12Z&sp=r

v2 validates bookmark within generated html `content`, while `<h1>` is extracted to `_op_rawTitle` and escaped the check.

**Comment by superyyrrzz** [comment]
fixed in #4248
