### ISSUE TITLE
Are custom renderers supported?

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#416]
I'd like to create a renderer which outputs all my API documentation into a specific JSON format. While I suppose I _could_ encode this logic in Javascript and then use a "no-op" Liquid/Mustache template, it feels like it would make more sense to just have a custom renderer written in C# which would take the model as input and write out the appropriate JSON files.

Is this aspect of extensibility supported at all? It doesn't feel quite like the plugin example of a DocumentProcessor, as I want access to the model _after_ all the rest of the docfx processing has happened. At least, I think I do :) In particular, I'm using overwrite files to inject example snippets - it would be good if all of that was already "done" by the time I got the model.

Along the same lines, it's not currently clear to me which part of docfx allows XML comments in C# files to be treated as Markdown (and then rendered as HTML) - is that part of the renderer, or is it earlier in the pipeline?

**Comment by vicancy** [comment]
1. Custom renderer in C# instead of JS preprocessor: after ApplyOverwrite is done: sounds like a PostBuild step for all the processors

2. Which part is treated as Markdown is defined in data model: https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.DataContracts.ManagedReference/ItemViewModel.cs with attribute [MarkdownContent]

**Comment by yufeih** [comment]
In v3, the output can be configured to be a JSON model processed by docfx. There is currently no plan to support custom renderers using a C# plugin model. Custom renderers could be implemented as a separate program that transforms these JSON outputs.
