### ISSUE TITLE
Content inside "see cref" tag is ignored

### ISSUE THREAD

**Issue by batbaille** [dotnet/docfx#4160]
**Operation System**: Windows

**DocFX Version Used**:  2.40.12.0

**Template used**: statictoc

**Steps to Reproduce**:

1. In my code, i have the summary for my class :
```
/// <summary>
/// Business class used to manage the <see cref="Product">products</see>
/// </summary>
```
2. I build HTML documentation with DocFX

**Expected Behavior**:
I expect the content of tag "see"

> Business class used to manage the [product](url)

**Actual Behavior**:
It'is the type of class which displayed
![image](https://user-images.githubusercontent.com/2175563/54290167-c4cc7000-45aa-11e9-8940-7dc9a2e6a3f8.png)

**Comment by superyyrrzz** [comment]
Do you include all your `**/*.csproj` in the same build?

**Comment by batbaille** [comment]
Thank's. It's better if the linked class is included in the build.
![image](https://user-images.githubusercontent.com/2175563/54337826-6944c580-4630-11e9-8bea-fd889cb53236.png)
