### ISSUE TITLE
Favicon not shown on subsite

### ISSUE THREAD

**Issue by andreasblueher** [dotnet/docfx#4163]
**Operation System**: `Windows` 

**DocFX Version Used**: `2.40.12.0`

**Template used**: `default`

**Steps to Reproduce**:

1. Change favicon in docfx.json as shown in the attached file [docfx.zip](https://github.com/dotnet/docfx/files/2966548/docfx.zip)
2. Create output and open page using Firefox or Chrome
3. See root page and favicon being shown as expected
4. Navigate to any page in a subdirectory where favicon is not shown

**Expected Behavior**:
Favicon should be shown for all pages

**Actual Behavior**:
Favicon is shown only for the first page

Thank you very much for your support

**Comment by superyyrrzz** [comment]
This is meant to used as the path from output root the Favicon path in output. I am not sure of this usage.

**Comment by andreasblueher** [comment]
I found the reason and maybe defining Favicon with base64 code could be enabled after all for docfx.

`<link rel="shortcut icon" href="../data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAtZJREFUeNpsVF1IFFEUPnd2ZndnZmfddjFcXFbX3c3Nta3wJQPtJVqECgPpIQsi1AqiTIqKfoiKXnqqB1N6UHzOEJPCwJ+0ROupB01KEgJDnzTXHXd2dmY6d7axtA6cmbn3nu87v3cgk8lAPB4Hh8NhKsuyQKUsVJZouXp9KHrjzqAYCldwuGfHM8sukUhANpsF05p+KIpiAgVB8B5K1rUdqK29YLikgmGhAKTL18blocEnqTevHxvr8gq1UxBDhSWEmAQozL7q/aeTybrbRX5/qYqEq7kcgKqCTXR5PcdP3BWra06t9vfeS0+M96BHoFgiyzKprz9WEwpHHiQSe2o0LQc5BDLIuIYG3bwbZHzTNeE4IDYbLH2YHAl//XzrU9+LCaJpmrOvf2B2cXGphNaDCvkN2Eqg6jpkUav8RXAlXv4lGQlVsoRhiJ3jdNElAsexkE7LoKMRsuTJUHXDADmnQdAlQEt5BBpKAiDxvGHWgD4QoJN8Ac0KU5IsRmMgMI3psHY7NJeXQtOOMBQLPJLlQFZVXbAILKEAG+bodkuQczpARqKDxX5ojsdgr7cAMhhFCosKfwE3EVgkVB08D7sKC6EhHAYvhp7WdHN/q/wTAcMw4BJF4DEdzsbCmiyDjC0TRQHVhREym4gsAkL3RMxPRDCdRkM3sHh/iplKrcH6egYkyQVOjA4dmQesrukGL/Cs08lbtvkumB0gG55oa7HlsLy8Am5Mx+aWTOeMomSUZ52dZ2ZmpqdoF6y78D+xYzckSYLR0ZH3rZcuNuHcqITegUgkDAsLP9jDR442NzaevBkIBIpxQk2Qz+fD+eCA5wWYn//2vbPj6f3e3uddwWBQm5ubA6DTF41GN7x4PNu2nz13/tHLgVept2PvjOmZWWNy6uPP1ta2hx6Px2fZxWKx/B2iBHRB+0/Vkp0VFVXt7R1jXd09w/F45W5r37KjvwBK8EuAAQDLoyksRQZQ1gAAAABJRU5ErkJggg==">
`

As you can see it automatically adds ../ for every page in a subfolder, which destroys the base64 string. 

As the "normal approach" didn't work for me right away, one more question: Do I need to add the custom favicon.ico to my template folder only or to the folder where my docfx.json is only?

**Comment by andreasblueher** [comment]
It appears this is also true for simply referencing the favicon, as you can see this source code from my website for a subpage

`<link rel="shortcut icon" href="../favicon.ico">
`

**Comment by superyyrrzz** [comment]
In my understanding, all you need is this base64 string to make favicon render properly, instead of needing a `favicon.ico` file? If so, you can custom the template to replace `{{_rel}}{{{_appFaviconPath}}}` with your string.

**Comment by andreasblueher** [comment]
Thank you @superyyrrzz  removing {{_rel}} from the header template did the trick. Just out of curiosity, whats the reasoning behind add the relative path to the favicon url? Don't you have to add the favicon.ico to every subfolder with this kind of setup?

**Comment by superyyrrzz** [comment]
No. DocFX copies `favicon.ico` only to the site's root. So files in different level of subfolders need `{{_rel}}` to get the correct path to the root (usually means how many `../`). It does not consider the base64 image presentation... Anyway, it's great to see it works 😊

**Comment by andreasblueher** [comment]
> No. DocFX copies `favicon.ico` only to the site's root. So files in different level of subfolders need `{{_rel}}` to get the correct path to the root (usually means how many `../`). It does not consider the base64 image presentation... Anyway, it's great to see it works 😊

Yeah my thinking was off there, having the {{rel}} is needed for the subfolder. I understand now.
