### ISSUE TITLE
Reference to Task.Delay(int) not resolved

### ISSUE THREAD

**Issue by lg2de** [dotnet/docfx#4164]
**Operation System**: `Windows`
**DocFX Version Used**: `2.40.12.0`
**Template used**: `custom`

**Steps to Reproduce**:

1. download `xrefmap.yml` into `docs.microsoft.com.zip`
2. add `docs.microsoft.com.zip` to `docfx.json` as `xref`
2. add following reference to c# class:
```
    /// <summary>
    ///     Implements <see cref="ITimer" /> using <see cref="Task.Delay(int)" />.
    /// </summary>
```

**Expected Behavior**:
Reference to Task.Delay is added.

**Actual Behavior**:
`[19-03-14 01:27:35.033]Warning:[MetadataCommand.ExtractMetadata]Invalid cref value "!:Task.Delay(Int32)" found in triple-slash-comments for TaskTimer defined in ../../src/AIS.TC.Core/TaskTimer.cs Line 13, ignored.`
Reference to `ITimer` (internal interface) and other classes from .NET (Core) Framework is working fine.

generated yml content:
`summary: "\nImplements <xref href=\"AIS.TC.Core.ITimer\" data-throw-if-not-resolved=\"false\"></xref> using <see cref=\"!:Task.Delay(Int32)\"></see>.\n"`

I also tried to reference `Task.Delay(Int32)`.

**Comment by superyyrrzz** [comment]
`!:` means the compiler cannot understand the `cref`. I guess you do not add `using System.Threading.Tasks;`.

After the warning is gone, you can try use the [xrefService](https://github.com/dotnet/docfx/blob/04926b3451c88be92b37571e9c7491a970690cfc/Documentation/docfx.json#L40-L42). I am not sure whether the zipped YAML file can work.

**Comment by lg2de** [comment]
System.Threading.Tasks is in the using list.

The zipped YAML file seams to work for many, many other types.

**Comment by superyyrrzz** [comment]
I failed to reproduce this issue. It works fine for me:
![image](https://user-images.githubusercontent.com/3831744/54367172-e877df00-46ac-11e9-83dc-c5b0479c01e4.png)


Could you provide a sample project?

**Comment by lg2de** [comment]
[sample.zip](https://github.com/dotnet/docfx/files/2967125/sample.zip)

**Comment by superyyrrzz** [comment]
As I commented, relace
```
    "xref": [
      "file://help/help/xrefmaps/docs.microsoft.com.zip"
    ],
```
with
```
    "xrefService": [
      "https://xref.docs.microsoft.com/query?uid={uid}"
    ],
```
then all is fine.

**Comment by bitbonk** [comment]
I really fear that using a xrefService via the internet for *each and every* API that we reference somewhere in our documentation will significantly slow down the build time. Also, if the internet breaks, our builds break.

Is there no reliable way to have a offline build?

**Comment by bitbonk** [comment]
#713

**Comment by superyyrrzz** [comment]
@bitbonk I agree this is a valid concern. v3 has a similar idea to download needed xrefMap in a pre step to avoid call API during build. This will make the build input clear.

Fow now, xrefService is the source of truth that contains the full data. XrefMap on docs site contains only partial data. The tradeoff here is: If I only need to resolve few BCL UIDs, I want to use xrefService instead of preparing the huge xrefMap beforehand. If I need to resolve a lot, xrefMap would be better.

**Comment by lg2de** [comment]
I expect to need resolving many UIDs. This is why I would like to get the faster solution.
When the v3 will be available?

**Comment by superyyrrzz** [comment]
You can refer to the [roadmap](https://github.com/dotnet/docfx/blob/v3/docs/roadmap.md).

Have you tried to reference to `xrefmap.yml` directly? `"xref": "xrefmap.yml"`

**Comment by lg2de** [comment]
Just now I did the following verification:
1. use xrefService instead of xref => same Problem as initially reported
2. use xrefmap.yml instead of xrefmap.zip => same result

So, it seems the problem is neither related to ZIP or YML or SERVICE.

**Comment by superyyrrzz** [comment]
Maybe you can try running docfx append `-f`, to disable incremental build.

Or you can try this xrefmap.yml for test (which works for me):
``` yml
### YamlMime:XRefMap
references:
- uid: System.Threading.Tasks.Task.Delay(System.Int32)
  name: Delay(Int32)
  href: https://docs.microsoft.com/dotnet/api/system.threading.tasks.task.delay#System_Threading_Tasks_Task_Delay_System_Int32_
  fullName: System.Threading.Tasks.Task.Delay(Int32)
```

**Comment by lg2de** [comment]
Today I tried again with the same docfx version: The problem is not visible anymore.
Maybe it is related to updates of (one of) the base tools, e.g. Visual Studio is used according to the output:
```
[19-06-18 12:08:34.580]Info:[ExtractMetadata]Using msbuild C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin as inner compiler.
```

We are using now version 16.1.3
