### ISSUE TITLE
Regex to exclude Markdown files (non API files) from search results

### ISSUE THREAD

**Issue by cedar-ave** [dotnet/docfx#4177]
**Operation System**: (`Windows` or `Linux` or `MacOS`) Windows

**DocFX Version Used**: 2.40.11

**Template used**: (`default` or `statictoc` or contain custom template) `default` + custom

**Steps to Reproduce**:

Add regex in `fileMetadata` in `docfx.json` to exclude Markdown files whose filenames start with `title` from search results. For example (from root):

- `articles/guide1/title-page1.md`
- `articles/guide2/title-page2.md`)
- `articles/guide3/title-page3.md`)

```
    "fileMetadata": {
      "_noindex": {
        "articles/includes/*": true,
        "articles/**/^title.*?\\.md": true
      }
    }
```
**Expected Behavior**:
Files in a designated directory whose names begin with `title` are excluded from search results (files under `articles/includes/*` are successfully excluded)

**Actual Behavior**:
Files in a designated directory whose names begin with `title` are not excluded from search results

I apologize if this is simply a Regex issue but in my testing it seems to work.

**Comment by superyyrrzz** [comment]
The key does not support regex. It is [glob pattern](https://en.wikipedia.org/wiki/Glob_(programming)). You can try: `articles/**/title*.md`

**Comment by cedar-ave** [comment]
This worked. Thank you for the explanation. I see now where glob pattern is stated clearly in the docs.
