### ISSUE TITLE
Markdig features don't seem to be working

### ISSUE THREAD

**Issue by johanvergeer** [dotnet/docfx#4201]
I have `markdig` set as the `markdownEngineName`, but the features don't seem to be working. I'm not sure if I'm missing something, or this functionality is not supported.

**Operation System**: `Windows` 

**DocFX Version Used**: 2.40.11.0

**Template used**: `default`

**Steps to Reproduce**:

1. Create a markdown file
2. Add some content. See examples below
3. `docfx build`
4. `docfx serve _site`

## First example: Task lists

**Expected Behavior**:

```markdown
- [ ] Item1
- [x] Item2
- [ ] Item3
- Item4
```

```html
<ul class="contains-task-list">
  <li class="task-list-item"><input disabled="disabled" type="checkbox" /> Item1</li>
  <li class="task-list-item"><input disabled="disabled" type="checkbox" checked="checked" /> Item2</li>
  <li class="task-list-item"><input disabled="disabled" type="checkbox" /> Item3</li>
  <li>Item4</li>
</ul>
```

**Actual Behavior**:

```html
<ul>
  <li>[ ] Item1</li> 
  <li>[x] Item2</li>
  <li>[ ] Item3</li>
  <li>Item4</li>
</ul>
```

## Second example: footnotes

**expected behavior**

```markdown
This is another reference to [^1]

[^1]: Here is the footnote.
```

```html
<p>This is another reference to <a id="fnref:2" href="#fn:1" class="footnote-ref"><sup>1</sup></a></p>

<div class="footnotes">
  <hr />
   <ol>
    <li id="fn:1">
      <p>Here is the footnote.<a href="#fnref:1" class="footnote-back-ref">&#8617;</a><a href="#fnref:2" class="footnote-back-ref">&#8617;</a></p>
    </li>
  <ol>
</div>
```

** Expected behavior **

```html
<p>This is another reference to [^1]</p>
<p>[^1]: Here is the footnote.</p>
```

**Comment by Thraka** [comment]
I ran into the same trying to use grid tables. It seems that none of the markdig extensions are enabled. I'm not sure how to turn them on. It really is disappointing because using the extensions is one of the biggest highlights to using markdig.

**Comment by superyyrrzz** [comment]
DocFX only uses limited set of Markdig extensions, but still not expose a configure to control which to use. 

For task list, we still not see the requirement clearly. See: #3643
For foot notes, DocFX supports a similar feature: https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a#file-inclusion

**Comment by superyyrrzz** [comment]
Keep track in #3387
