### ISSUE TITLE
yaml-syntax-error and merge-conflict in different scenarios

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#4219]
Note that merge-conflict for yaml-header is also on type of yaml-syntax-error.  

| file-type | merge-conflict behavior | yaml-header-syntax-error behavior |
| --- | --- | --- |
| config/sdp | error | error |
| toc.yml | error | error |
| toc.md | error | NA |
| md yaml header (corner case) |warning (treat as empty) | warning (treat as empty,  same as v2) |
| md content (corner case) | ⚒suggestion (treat as normal content) | NA |

**Comment by herohua** [comment]
@mingwli to confirm current behavior and close this issue.
