### ISSUE TITLE
Remove base path related config

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4222]
To change base path, it is best to only have 1 config that contains base path info like `base_url`. Right now `routes` also has base path info, we should remove them.

- [ ] Remove base path from `routes`
- [ ] Remove base path from `publish.json`

**Comment by OsmondJiang** [comment]
the site base path config is also related with "output.lowerCaseUrl", @yufeih

**Comment by mingwli** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.Build/pullrequest/11307?_a=overview

**Comment by mingwli** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.Build/pullrequest/11311?_a=overview

**Comment by yufeih** [comment]
The output `url` should also be an URL without `base_url`

**Comment by yufeih** [comment]
For routes, the conclusion is only remove `site_base_path`, leave `source_base_path` for document id only.

**Comment by herohua** [comment]
@928PJY @mingwli to check whether this has been finished or not
