### ISSUE TITLE
Failed PDF generation should result in Error and not Warning

### ISSUE THREAD

**Issue by lg2de** [dotnet/docfx#4232]
**Operation System**: `Windows`

**DocFX Version Used**: 2.40.12

**Template used**: custom template

**Steps to Reproduce**:

1. generate PDF documentation
2. open PDF (with a viewer locks the file, like Acrobat Reader)
3. generate PDF documentation => PDF cannot be generated because the file is protected

**Expected Behavior**:
PDF generation failed => ERROR

**Actual Behavior**:
PDF generation failed => WARNING
```
[19-03-22 04:15:25.956]Warning:[PDF]Error happen when converting pdf/toc.json to Pdf. Details: ... accessed by another process...
                       ^^^^^^^
```

The PDF file is not up-to-date. So the process was failed!

**Comment by lg2de** [comment]
@superyyrrzz , for me this is not an enhancement but a bug.

**Comment by superyyrrzz** [comment]
Thank you for your feedback. @icnocop created #4289 to fix this.
