### ISSUE TITLE
same errors/warning/suggestions are reported multiple times

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4241]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/10014?_a=files

**Comment by OsmondJiang** [comment]
The root cause is that the report generated by docfx has `line` and `column` number, but the report used for build service only have `line` info. So the same line with different column errors/warnings/suggestions will be reported multiple times in build report with same line info.

Right now it happens mostly to localized sxs content, not a really big issue, but would we add column info to build report in the future?

@yufeih  @fenxu  @herohua @live1206

**Comment by herohua** [comment]
@fenxu to open a following-up task in VSTS
