### ISSUE TITLE
Clicking a link inside the 'IN THIS ARTICLE' section twice incorrectly scrolls

### ISSUE THREAD

**Issue by tomaustin700** [dotnet/docfx#4258]
**Operation System**: Windows

**DocFX Version Used**: 2.40.12

**Template used**: default

**Steps to Reproduce**:

1. Go to http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html
2. Click "4.1 Steps" inside the 'IN THIS ARTICLE' section
3. Click "4.1 Steps" again, see how the page is scrolled down incorrectly and the 4.1 steps header is hidden.

You can even duplicate this by navigating to a 'IN THIS ARTICLE' item via a hyperlink and you can see the header is missing. e.g. https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#41-steps

**Expected Behavior**:
The header shouldn't be hidden and no additional scrolling should happen
**Actual Behavior**:
The page is incorrectly scrolled down

**Comment by superyyrrzz** [comment]
dup of #3133
