### ISSUE TITLE
bookmark in INCLUDE suggestion/resolve issue

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#4273]
1. for the invalid selfbook in the included file, if they have been included in different files, there may be several duplicates log with different suggestion:
```
{"code":"internal-bookmark-not-found","file":"includes/app-service-web-git-push-to-azure-no-h.md","line":13,"message":"Cannot find bookmark '#create' in 'includes/app-service-web-git-push-to-azure-no-h.md'","message_severity":"suggestion"}
{"code":"internal-bookmark-not-found","file":"includes/app-service-web-git-push-to-azure-no-h.md","line":13,"message":"Cannot find bookmark '#create' in 'includes/app-service-web-git-push-to-azure-no-h.md', did you mean '#next'?","message_severity":"suggestion"}
```

we could resolve this problem just generate the suggestion inside the token.
but if we still want the suggestion scope to be the whole file, I think we may need to include the parent info in the log message.

2. Do we need to support using self-bookmark to reference the parent bookmark in the included file? we support now, but that would cause confusion if this token has been included in other files which doesn't have this bookmark.

**Comment by herohua** [comment]
We need to figure out the design of bookmark validation in SDP first, then come back to discuss whether to change the current behavior of this issue.
