### ISSUE TITLE
Generated PDF's outline/bookmarks don't link to the correct page

### ISSUE THREAD

**Issue by icnocop** [dotnet/docfx#4274]
**Operation System**: Windows 10 64-bit

**DocFX Version Used**: 2.41

**Template used**: `default`

**Steps to Reproduce**:

1. Download and extract [docfx-pdf-outline-bug.zip](https://github.com/dotnet/docfx/files/3025902/docfx-pdf-outline-bug.zip) to a directory of your choice.

2. Run `build.cmd`
Note: `docfx.exe` and `wkhtmltopdf.exe` should be in your `%PATH%`.
Otherwise, update `build.cmd` as follows:
```
set PATH=<path to wkhtmltox>;%PATH%
"<path to docfx>\docfx.exe" docfx.json
```

I tested with both wkhtmltox v0.12.4_msvc2015-win64 and v0.12.5-1.msvc2015-win64.

3. Open the generated PDF file in `_pdf\*.pdf` in Adobe Acrobat Reader DC 2019.010.20098.
4. Show the Bookmarks pane.
5. Click on the `Page 2` bookmark for example.

**Expected Behavior**:

I expected the `Page 2` bookmark to take me to page 5 in the PDF.

**Actual Behavior**:

The `Page 2` bookmark takes me to page 7 in the PDF.

**Comment by icnocop** [comment]
This was caused by trying to use wkhtmltopdf's cover and toc with docfx's default outline which aren't compatible.

The fix was part of PR https://github.com/dotnet/docfx/pull/4289 and commit https://github.com/dotnet/docfx/commit/79b78aa40d341c23e26bce9f408de0cd963481f6.

So basically, you can use wkhtmltopdf's outline by setting the new `outline` JSON property to `WkDefaultOutline`.

**Comment by mattemoore** [comment]
@icnocop , how do we ensure we are not using wkhtmltopdf's cover and toc?

**Comment by mattemoore** [comment]
I'm assuming we don't pass any parameters to wkhtmltopdf or something similar?
