### ISSUE TITLE
Cyrillic is not displayed on site

### ISSUE THREAD

**Issue by KellsoHP** [dotnet/docfx#4277]
**Operation System**: (`Windows`)

**DocFX Version Used**: 2.41.0

**Template used**: `default`

**Steps to Reproduce**:

1. Add to 'index.md' on main folder that text: 'Тестовое сообщение!'
2. Build site with this command: 'docfx "PATH_TO_DOCFX.json" --build'
3. Run site with this command: 'docfx "PATH_TO_DOCFX.json" --serve'

**Expected Behavior**:
'http://localhost:8080/index.html' have text: 'Тестовое сообщение!'

**Actual Behavior**:
'http://localhost:8080/index.html' have text: '�������� ���������!'

How i can fix it?
For example, api documentation display correct cyrillic text from XML doc.

**Comment by KalleOlaviNiemitalo** [comment]
Using DocFX 2.40.12.0 on Windows 10 with system ANSI codepage 1252, your Cyrillic text works OK if I save the file in UTF-8 with or without a byte order mark, or in little-endian UTF-16 with BOM, but not if I save it in codepage 1251 (Cyrillic). So, please try UTF-8.

**Comment by KellsoHP** [comment]
> Using DocFX 2.40.12.0 on Windows 10 with system ANSI codepage 1252, your Cyrillic text works OK if I save the file in UTF-8 with or without a byte order mark, or in little-endian UTF-16 with BOM, but not if I save it in codepage 1251 (Cyrillic). So, please try UTF-8.

Thx! It's working for me!
It's true, that with codepage 1251 (Cyrillic) symbols not displayed.
When i change codepage on UTF-8, it all worked.
