### ISSUE TITLE
Missing characters at the <example> tag.

### ISSUE THREAD

**Issue by alexandretperez** [dotnet/docfx#428]
Some characters are missing in &lt;example&gt; tag which breaks this segment of the documentation.

These images explains better:

On DocFx:
![DocFx Image](https://s31.postimg.org/xi29d81kb/image.png)

For comparison, here is the output generated by Sandcastle:
![Sandcastle Image](https://s32.postimg.org/d8mg1d3at/image.png)

The XML documentation used in this example.

    /// <summary>
    /// The class description goes here...
    /// </summary>
    /// <example>
    /// Here is some example...
    /// <code>
    /// var handler = DateTimeHandler();
    /// handler.Avoid(DayOfWeek.Saturday, DayOfWeek.Sunday);
    ///
    /// var date = new DateTime(2016, 5, 21);
    /// for (var i = 0; i &lt; 10; i++){
    ///
    ///     // When the "i" == 2 the date will be 2016-08-21 (Sunday)
    ///     // When the "i" == 7 the date will be 2017-01-21 (Saturday)
    ///     date = date.AddMonths(1);
    ///
    ///     // When the date is 2016-08-21 (Sunday), the rules move the date on day forward to the 2016-08-22
    ///     // When the date is 2017-01-21 (Saturday), the rules move the date 2 days forward to the 2016-01-23
    ///     date = handler.ApplyTo(date);
    ///
    ///     Console.WriteLine(date);
    /// }
    /// </code>
    /// </example>

**Comment by ansyral** [comment]
@alexandretperez  fixed in dev branch
