### ISSUE TITLE
[Question] Generate ad-hoc documentation from markdown files

### ISSUE THREAD

**Issue by jfcarr** [dotnet/docfx#4305]
**DocFX Version Used**: 2.41.0.0

**Template used**: default

I apologize for posting a "how to" question as an issue, but I haven't been able to find an example of this anywhere.

I am going to be generating API documentation from XML comments in C# .NET Core projects.  This part is straightforward, and I had no trouble figuring it out.

Here's where I'm stuck:  In my solution folders, I will also have multiple markdown files.  I have no control over these files.  I have no idea how many there will be, or where in the folder structure they'll reside.  I simply want to scan the entire solution, including all subfolders, and add any markdown files I find to my generated documentation.  All of the examples I've found so far describe a "known" file structure, where you create a toc.yml file and add all of your markdown files to it.  Since I don't know what markdown files I'll have, I can't do this.

Is there any way to do this, to just dump all markdown file content into generated documentation?

**Comment by superyyrrzz** [comment]
> Is there any way to do this, to just dump all markdown file content into generated documentation?

If just to address this question, the `**/*.md` pattern in `docfx.json` can search all these Markdown files and generate HTML pages for them. You can see them in output folder.

As you said, the question is that you have not a TOC to organize them. So you can input the correct URL to see all pages, but cannot navigate among them easily. You have to find some way to generate a TOC to address this issue.

**Comment by jfcarr** [comment]
Sounds like we could either make it a requirement for the developers to maintain a TOC manually in the solution, or add an extra step in CI to generate one.  I think I like the idea of a CI step, then we won't have to worry about it being forgotten or incorrect.  I was hoping there was a way around the TOC requirement, but thanks for the confirmation!

**Comment by superyyrrzz** [comment]
Thank you for the information. Looks like this could be a feature request for DocFX to generate TOC automatically from folder structure?

**Comment by jfcarr** [comment]
That would certainly be useful.  I'm putting together a crude solution myself for now (https://github.com/jfcarr/docfx-adhoc-md), but it would be nice to have a more comprehensive solution baked in.  :)

**Comment by NickLocke** [comment]
Hi, I'd find this functionality very valuable too.  I also have another twist.....  

In my world there is high-level markdown documentation in a specific location.  In addition to that, the developers are expected to create an MD file named the same as any non-trivial CS file - that gives more detail than the XML documentation.  It would be great if DocFX could be configured to display that markdown in amongst the API stuff.

There will also be an MD file per namespace, and it would be great for that to be displayed when the user is on the root of the namespace in the API ToC.

**Comment by superyyrrzz** [comment]
@NickLocke Looks like what [overwrite files](https://dotnet.github.io/docfx/tutorial/intro_overwrite_files.html) does.

**Comment by superyyrrzz** [comment]
Close this as the question is resolved. Track the feature request in #3124.
