### ISSUE TITLE
Support output as MediaWiki markup rather than just HTML, and allow publishing to wikis and multiple locations at once

### ISSUE THREAD

**Issue by mwells1** [dotnet/docfx#4318]
We love how DocFX helps developers keep documentation in the same repo as code. However, we need it to output to additional languages and publish to additional kinds of sites. Our team heavily leverages MediaWiki for internal docs, but we aren't able to directly import the HTML due to the wiki requiring content to be in the [MediaWiki markup language](https://www.mediawiki.org/wiki/Wikitext). Additionally, we need DocFX to be able to publish directly to a MediaWiki-based wiki from a repo.

Ideally, DocFX would also be able to publish to multiple places at once. For instance, if a developer maintains docs on both a wiki and Docs.microsoft.com - they should be able to edit the docs directly in the repo and then publish to both locations at once. This would ensure that there is one source of truth for the content and that developers don't have to waste time tracking down all the locations where the same content lives to make manual updates to each.

While there are open source tools like[ Pandoc](http://pandoc.org/) that help convert content from one language to another, this is not feasible for users to do on their own page by page and it also does not handle images or internal doc links. This functionality should be built into DocFX to make the tool more useful to a broader range of users and platforms.

**Comment by superyyrrzz** [comment]
Related: #684
