### ISSUE TITLE
Output content restructure

### ISSUE THREAD

**Issue by fenxu** [dotnet/docfx#4323]
v3 has two modes of build to generate output, namely legacy and ideal.

- Under legacy mode, the output is like following shows
   ```
   Output Root
   | -- Manifest
   | -- Other system generated files like dependency map
   | -- {base_path}
         |-- Legacy manifest
         |-- Other Legacy system generated files like dependency map
         |-- Legacy pages output
   ```

- Under ideal mode, the output is like following shows
   ```
   Output Root
   | -- manifest
   | -- {base_path}
         |-- pages output
   ```

It's OK for ideal mode because manifest is under output folder which user specifies. However, for legacy mode, although user specify output folder, the content legacy manifest is not there but under a folder {base_path}. That's not awareness by user, so does the service. To make it more clear, we want to change the legacy mode output folder structure like following shows:

- New legacy mode output folder structure
  ```
   Output Root
   | -- Legacy manifest
   | -- Other legacy system generated files like dependency map
   | -- Other content
  ```

- Related Work Items
[ ] Docfx legacy output folder restructure
[ ] Impact tool adjustment
[ ] Docs scripts code adjustment

Because it's not a small effort, in short term, adjust service code at first. Here's tracking [link](https://ceapex.visualstudio.com/Engineering/_workitems/edit/80184)

**Comment by fenxu** [comment]
cc @OsmondJiang @herohua @mingwli @yufeih

**Comment by herohua** [comment]
Multiple docset support depends on this task.

**Comment by yufeih** [comment]
The output structure is finalized in multiple docset spec here #5102
