### ISSUE TITLE
Custom attributes not included when generate doc from assembly

### ISSUE THREAD

**Issue by drieseng** [dotnet/docfx#4367]
**Operation System**: Windows

**DocFX Version Used**: v2.41 (but also reproduces on lower versions)

**Template used**: statictoc

**Steps to Reproduce**:

1. Clone https://github.com/drieseng/docfx-issue
2. Run 'msbuild' from the checkout directory.
3. Inspect the HTML page generated in \<checkout directory\>\temp\generate-doc\assembly\_site\api\DocFxCustomAttributeProblem.DummyAttribute.html.

**Expected Behavior**:

A **DataContract** attribute should be displayed in the **Syntax** panel.

Note that you get this if you inspect the HTML page generated in \<checkout directory\>\temp\generate-doc\project\_site\api\DocFxCustomAttributeProblem.DummyAttribute.html as that site was generated from the project.

**Actual Behavior**:

A **DataContract** attribute is displayed in the **Syntax** panel for the site generated from the assembly.

**Comment by superyyrrzz** [comment]
Thank you for the detailed repro steps. Looks like a bug.

**Comment by drieseng** [comment]
Could it be because the type of the custom attribute is defined in another (BCL) assembly?
More specifically, it's defined in **System.Runtime.Serialization**.

I already tried to specify this assembly as extra item in the files list:

      "src": [
        {
          "src": "../../../src/bin/Debug/",
          "files": [
            "DocFxCustomAttributeProblem.dll",
            "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\System.Runtime.Serialization.dll"
          ],
          "exclude": [
            "**/bin/**",
            "**/obj/**",
            "_site/**"
          ]
        }
      ]

I actually don't want to generate any doc pages for that **System.Runtime.Serialization**.
I was actually expecting a way to specify reference assemblies.

**Comment by superyyrrzz** [comment]
Nice catch. You can try `references`:

```json
  "src": [
    {
      "src": "../../../src/bin/Debug/",
      "files": [
        "DocFxCustomAttributeProblem.dll"
      ],
      "references": [
        "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\System.Runtime.Serialization.dll"
      ],
      "exclude": [
        "**/bin/**",
        "**/obj/**",
        "_site/**"
      ]
    }
  ]
```

**Comment by drieseng** [comment]
I tried a "references" approach a while ago, but it didn't work for me.
Let me try it again with the latest of docfx in the next days.
