### ISSUE TITLE
source files are included to build with error in loc repository building

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4379]
https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C4%5C16%5C4709ceea-246d-76fd-3615-65fb72516268%5CCommit%5C201904160203117809-v3-loc-sxs%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=owLBCawy6A65F7K6W08P8YDkN8zv2lit%2BeRKP7cQMPk%3D&st=2019-04-17T01%3A28%3A01Z&se=2019-05-18T01%3A33%3A01Z&sp=r

![image](https://user-images.githubusercontent.com/19990166/56255521-d2b86800-60f7-11e9-8ec0-c3fb8423fb20.png)

Above file doesn't exist in loc repo build, but it's built and reported error.

**Comment by OsmondJiang** [comment]
Seems it's caused by LoadXref(Docset -> ScanScope), @live1206

**Comment by OsmondJiang** [comment]
We can resolve this when writing errors, check if the file in the errors belongs to docset build scope. @live1206  @yufeih

**Comment by OsmondJiang** [comment]
The second through is that can't docfx continue run if the one of the item in the map(xref map and toc map) failed to load?

**Comment by OsmondJiang** [comment]
Confirmed with @cillroy , that's a acceptable behavior in v3, we just need a flag to indicate this error is from source repo and link to the correct file in final report.

**Comment by yufeih** [comment]
Errors are excluded from fallback repo.
