### ISSUE TITLE
create docker for docfx

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#4385]
Already many images on docker hub: https://hub.docker.com/search?q=docfx&type=image

Some work from Den: https://github.com/dend/doctainers

User Docker to automate cross platform test in CI: https://github.com/dotnet/docfx/issues/3948#issuecomment-482562967

**Comment by superyyrrzz** [comment]
It will be very helpful with some docker based cross-platform tests when reviewing PRs like #4708 

https://github.com/docascode/docfx.test covers some cross-platform tests, but only after package release. We need some in time check in PR.

**Comment by SeanKilleen** [comment]
In case it's helpful, we've been using the following for a while with no issues: https://github.com/nunit/docfx-action/blob/master/Dockerfile (forked from https://github.com/nikeee/docfx-action/blob/master/Dockerfile)

I get that this might not be an ideal format for the container, though.

If you'd like to specify a little bit more here about what you're looking for in order for this to be considered complete, I'd be happy to work to contribute!
