### ISSUE TITLE
Literal text not preserved in inline code spans in /// XML comments

### ISSUE THREAD

**Issue by qgindi** [dotnet/docfx#4392]
**Operation System**: `Windows`

**DocFX Version Used**: 2.41

**Template used**: `default`

**Steps to Reproduce**:

1. In /// comments insert an inline code span containing \\ or " characters. For example `<c>@"\\?\"</c>`. Or `@"\\?\"` enclosed in \`.
2. Compile.
3. Open the web page in Chrome.

**Expected Behavior**: Chrome displays `@"\\?\"`.

**Actual Behavior**: if was used c tag, it displays `@"\?&quot;`. If was used \`, it displays `@&quot;\\?\&quot;`. As you see, one \\ is removed, and most " are replaced with `&quot;`. It works well in conceptual topics (md files), but not in /// comments.

Markdown in /// comments is one of main reasons I want to use DocFX and not SHFB, therefore disabling it is not an option.

**Comment by qmgindi** [comment]
Also, markdown is applied in ` <c>...</c> `.
For example, ` <c>*text*</c> ` is rendered as italic *`text`*.
