### ISSUE TITLE
DoxFX VSCode Extension not working -> vscode.previewHtml not found

### ISSUE THREAD

**Issue by cblackuk** [dotnet/docfx#4406]
You cannot use DocFX extension preview any more it comes up with.

```
vscode.previewHtml not found
```

Can this be looked at please?

Related to  https://github.com/Microsoft/vscode-cosmosdb/issues/1070 and https://github.com/ajshort/vscode-latex-preview/issues/17

Probably needs changing here:
https://github.com/dotnet/docfx/blob/master/tools/VscExtension/src/extension.ts#L191 and other places too.

**Comment by superyyrrzz** [comment]
This extension is deprecated. @928PJY Seems we need to add some notice.

**Comment by cblackuk** [comment]
@superyyrrzz will there be a replacement? Or is there a replacement already? :-)

**Comment by superyyrrzz** [comment]
Maybe... transited 😄 Any way, you can try this one: https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-markdown

**Comment by cblackuk** [comment]
> 
> 
> Maybe... transited 😄 Any way, you can try this one: https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-markdown

Will do :-) Thanks :-)

**Comment by cblackuk** [comment]
@superyyrrzz 

Is that how the new extension should render DocFX specific syntax? As this is what it does...

![image](https://user-images.githubusercontent.com/28607803/56676407-1db51b00-66b6-11e9-8bb1-88c9d2b1f804.png)

**Comment by superyyrrzz** [comment]
Looks like a missing feature... You can create an issue in https://github.com/Microsoft/vscode-docs-authoring

**Comment by cblackuk** [comment]
@superyyrrzz It is like the only feature that should be there but ok :D Thanks for getting back to me, will raise an issue there :-)
