### ISSUE TITLE
batch-1/batch-2/batch-3 vsts repo migration test

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4409]
# Batch 1
- [x] [Windows Drivers](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_drivers) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_drivers/780afb58-7a96-a386-4bca-ef364a1d77bc_docfx-v3-master_Docfx%20V3%20Migration%20Test?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1912&branchName=dev)
- [x] [Azure Kinect](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_azurekinect) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_azurekinect/eb95c6bd-5f93-a4a6-4eeb-35ba94a00c0e_docfx-v3-master_Docfx%20V3%20Migration%20Test?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1911&branchName=dev)
- [ ] Biggest One [Archived Previous Versions Root](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_archive_previous_versions_root) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_archive_previous_versions_root/a269dd9d-fe50-706b-c890-b041c5005a94_docfx-v3-master_Docfx%20V3%20Migration%20Test?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1913&branchName=dev)

# Batch 2

- [ ] ~[TFS Docs PR](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_tfs-docs-pr)~
- [x] [Desktop OPS](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_desktop-ops) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_desktop-ops/15fbfb89-1247-d783-bef8-45c5c3389d23_docfx-v3-master_docfx-v3-migration-desktop-ops?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1921&branchName=dev)
- [x] [Win 32](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_win32) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_win32/723a85e5-ae1d-5072-95ed-70e75e8098e0_docfx-v3-master_docfx-v3-migration-win32?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1922&branchName=dev)
- [x] [Wag Sandbox](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_wag-sandbox) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_wag-sandbox/0a7a8aa1-dad2-a37c-bbc0-47d889fe233a_docfx-v3-master_docfx-v3-master-migration-wag-sandbox?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1923&branchName=dev)
- [x] [SDK API Build](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_sdk-api-build) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_sdk-api-build/86e7a9eb-4ee0-0452-c56a-d20a5951b9b7_docfx-v3-master_docfx-v3-master-migration-sdk-api-build?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1924&branchName=dev)
- [x] [Wallaby](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_wallaby) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_desktop-ops/15fbfb89-1247-d783-bef8-45c5c3389d23_docfx-v3-master_docfx-v3-migration-desktop-ops?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1921&branchName=dev)
- [x] [Archived Robotics](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_microsoft-robotics-archive-pr) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_microsoft-robotics-archive-pr/31fb03b7-bab2-74c9-4009-aac3c68be34f_docfx-v3-master_microsoft-robotics-archive-pr-v3migrationCI?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1927&branchName=dev)
- [ ] ~[Archived Windows Dev XNA](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_windows-dev-docs-xna-archive-pr)~
- [x] [Archived .Net 3.0](https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_netframework-3-0-docs-archive-pr) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/Vso_mseng_docfx_v3_migration_netframework-3-0-docs-archive-pr/f08868bf-eaa7-d88d-890d-82de7420ee60_docfx-v3-master_docfx-v3-migration-netframework-3-0-docs-archive-pr-V3MigrationCI?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1925&branchName=dev)

**Comment by staceyhong** [comment]
test

**Comment by yufeih** [comment]
Close in favor of https://github.com/dotnet/docfx/issues/4028
