### ISSUE TITLE
Publish pdf documentation on https://dotnet.github.io/docfx

### ISSUE THREAD

**Issue by bahusoid** [dotnet/docfx#4416]
The search in current online documentation is quite limited. For instance I can't find all usages of file inclusions `[!include`:
![image](https://user-images.githubusercontent.com/22025304/56679659-4517e200-66ce-11e9-86fe-7ee3ef72030f.png)

So it would be much easier to download single file help file and do search right in file instead.

**Comment by yufeih** [comment]
How there is PDF docs on https://dotnet.github.io/docfx
