### ISSUE TITLE
build perf is not really good for large archived repositories(more than 1 hour)

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4420]
Repo: https://mseng.visualstudio.com/DefaultCollection/VSChina/_git/docfx_v3_migration_archive_previous_versions_root

Report: https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C4%5C24%5Ca269dd9d-fe50-706b-c890-b041c5005a94%5CCommit%5C201904240832220395-docfx-v3-master%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1YuWQzAaxFfM27bBUJhBynhOXxnUiJ6PFyxR6wj8bOQ%3D&st=2019-04-25T02%3A33%3A28Z&se=2019-05-26T02%3A38%3A28Z&sp=r

Build Time: 

![image](https://user-images.githubusercontent.com/19990166/56706262-e0e53480-6746-11e9-9165-eb196b3176d5.png)

Docfx v3 Build Time: 
![image](https://user-images.githubusercontent.com/19990166/56706281-f35f6e00-6746-11e9-9204-7c31f066d749.png)

**Comment by yufeih** [comment]
Close in favor of https://dev.azure.com/ceapex/Engineering/_workitems/edit/113226/
