### ISSUE TITLE
remove implicit option for restore

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4434]
“implicit” option of `docfx restore` brings too many unpredictable inputs for `docfx build`.

cc @yufeih

**Comment by yufeih** [comment]
go do it!

**Comment by yufeih** [comment]
Most of our dependencies are floating range version, downloads dont have versions at all, and we cannot make implicit restore both fast and correct, removing it makes build fast and correct. The only downside is an extra madantory command, so lets drop it.
