### ISSUE TITLE
Support MSBuild 16 (VS 2019)

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#4437]
Now users with VS 2019 alone cannot generate site correctly. https://github.com/dotnet/docfx/issues/2562#issuecomment-482229787 

Work items:

- [x] Upgrade from `net462` to `net472`
- [ ] Upgrade `Microsoft.Build` to 16
- [ ] Updrade logic to locate `msbuild`

**Comment by StephenHodgson** [comment]
Biggest difference here is the path after calling `vswhere`.

The new location is in `VisualStudio Install Root\MSBuild\Current\Bin` versus the old `Visual Studio Install Root\MSBuild\15.0\Bin`

**Comment by superyyrrzz** [comment]
@StephenHodgson Sure. Plan to upgrade to latest MSBuildLocator, [which handles this difference](https://github.com/microsoft/MSBuildLocator/pull/50/files).
