### ISSUE TITLE
yaml-header-not-object, invalid-metadata-type could become unexpected-type

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4442]
Now that we have `unexpected-type` error from schema validation, we can turn `yaml-header-not-object`, `invalid-metadata-type` into `unexpected-type`. The only problem is their level is now different.

**Comment by mingwli** [comment]
@yufeih @herohua Synced with Curt, he thinks that the specific codes help track how user make mistakes in telemetry, so it's better that we leave it as it is now.
