### ISSUE TITLE
Prerequisites for building from source in README are inaccurate

### ISSUE THREAD

**Issue by kborchers** [dotnet/docfx#4469]
**Operation System**: `Windows`

**DocFX Version Used**: `dev` branch

**Template used**: `default`

**Steps to Reproduce**:

1. Install Visual Studio 2017 minimum install, do not include any workloads
2. Install Node.js
3. Run `build.cmd`

**Expected Behavior**: Build succeeds

**Actual Behavior**: Build fails

Suggest changing prerequisites section to:

#### Prerequisites

1. [Visual Studio 2017](https://www.visualstudio.com/downloads/), `Visual Studio core editor` + `ASP.NET and web development` workload is enough.
1. [Node.js](https://nodejs.org), for building templates.

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps there should also be a `.vsconfig` file for Visual Studio 2019 as described in [Configure Visual Studio across your organization with .vsconfig | Visual Studio Setup](https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/). I hope DocFX will remain buildable in Visual Studio 2017, however.

**Comment by superyyrrzz** [comment]
> Install Visual Studio 2017 minimum install, do not include any workloads
The original document says "with .NET Core cross-platform development toolset". Can you try this?

**Comment by kborchers** [comment]
@superyyrrzz Sorry, I had also tried that before creating the issue. The only way I was able to complete a build was to install the ASP.NET and web development workload alongside VS2017. Also, just FYI, though the build finishes with my current install, the tests that run after the build fail. I do get a working docfx.exe and can build sites with it but the tests that run after the build completes do fail.

**Comment by superyyrrzz** [comment]
@kborchers Could you share which tests failed on your machine? I do see some tests run successfully under `build.cmd`, but not in Visual Studio.

BTW, for the document issue, I find the README was out of date. I have updated it. Thank you for pointing out!
