### ISSUE TITLE
TOC does not scroll or scrolls incorrectly

### ISSUE THREAD

**Issue by qmgindi** [dotnet/docfx#4470]
**Operation System**: `Windows`

**DocFX Version Used**: 2.42

**Template used**: `default`

**Steps to Reproduce**:

1. Open https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html in Chrome or Firefox.
2. Resize the window to make the article area height 200 pixels. This is for testing because there are not many items in TOC.
3. Scroll the article (not TOC) to the middle or bottom.
4. Reload the page (F5).

**Expected Behavior**: TOC shows Getting Started -> Quickstart.

**Actual Behavior**: TOC scrolls to the bottom.

Also, if you open a page, TOC does not scroll to show its link. If you open a page#anchor, TOC scrolls to the bottom or somewhere in middle.

Reason: function renderSidebar in docfx.js contains code "Scroll to active item". This code does not work. It calculates wrong value.

**Comment by superyyrrzz** [comment]
Thank you for reporting and investigation. Contribution is welcome for this.

related code: https://github.com/dotnet/docfx/blob/f01feb53fa4a4e2fc2191249356b41ca9ff4d709/src/docfx.website.themes/default/styles/docfx.js#L420
