### ISSUE TITLE
Code block style rendering issue

### ISSUE THREAD

**Issue by guardrex** [dotnet/docfx#4472]
Originally reported in [Markup Issus For Dialog.razor (aspnet/AspNetDocs \#12242)](https://github.com/aspnet/AspNetCore.Docs/issues/12242) opened by @stevenfowler16.

Hello, we have a code block with Razor syntax that has a styling issue in the ASP.NET Core docs.

The markdown for the code block is (I'll replace backticks with apostrophes here) ...

```cshtml
'''cshtml
<div>
    <h1>@Title</h1>

    @ChildContent

    <button onclick="@OnYes">Yes!</button>
</div>

...

'''
```

That's on the repo at https://github.com/aspnet/AspNetCore.Docs/edit/master/aspnetcore/blazor/index.md (Lines 42-63).

In the built doc, It renders with incorrect styling (red text) on the following page:

https://docs.microsoft.com/aspnet/core/blazor/#components

<img width="354" alt="Capture" src="https://user-images.githubusercontent.com/1622880/57182432-7e85e580-6e64-11e9-964e-4d9fde92b824.PNG">

**Comment by superyyrrzz** [comment]
docs.microsoft.com relies on a custom version of [highlight](https://github.com/highlightjs/highlight.js) to render code block color. So you can move this issue to DOCS support channel, or open a bug to template team to have a look.

**Comment by guardrex** [comment]
Thanks @superyyrrzz.

@scottaddie I'll yield to you, since I can't take this further.

**Comment by scottaddie** [comment]
@guardrex [Customer suggestion 91065](https://ceapex.visualstudio.com/Engineering/_workitems/edit/91065) has been opened to track this work internally.
