### ISSUE TITLE
azure devops repos are using new format url

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4493]
support identification of Azure DevOps repo by new format:

https://dev.azure.com/{account}/{project}/_git/{repo} like https://dev.azure.com/ceapex/Engineering/_git/Docs.DocFX.Impact

**Comment by OsmondJiang** [comment]
Now new issue is coming, the auth token current is not working for xxx.visualstudio.com but dev.azure.com

cc @yufeih  @mingwli  @fenxu @herohua 

Check this failed test:

https://ceapex.visualstudio.com/Engineering/_build/results?buildId=54247

**Comment by OsmondJiang** [comment]
Work Items:
  - [ ] Docfx support new URL format
  - [ ] Build service support new URL format(including Configuration Migration @mingwli  @OsmondJiang )
  - [ ] Migration tool(@928PJY )

**Comment by superyyrrzz** [comment]
Also need to support this in v2.

**Comment by chrisrichards** [comment]
Just taking a look at this, does the code in [GitUtility.cs](https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Common/Git/GitUtility.cs) need updating as well? e.g:

https://github.com/dotnet/docfx/blob/973fe1ec959aea1805e6d49f96c4ada84fecfe14/src/Microsoft.DocAsCode.Common/Git/GitUtility.cs#L29-L30

and:

https://github.com/dotnet/docfx/blob/973fe1ec959aea1805e6d49f96c4ada84fecfe14/src/Microsoft.DocAsCode.Common/Git/GitUtility.cs#L33

**Comment by superyyrrzz** [comment]
@chrisrichards Actually they have no reference except tests. It can be `Obsolete`.
