### ISSUE TITLE
Enhancement request: line numbers in broken links warnings

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docfx#450]
### Functional impact
It's more work for authors to find broken links because the information we have is at the file level, not the line level. It's even harder to search because the destination URL in the error message roots at ~, even if the link in the source file is relative to another directory.

### Minimal repro steps

Create a markdown file with an invalid links:

```
[This file doesn't exist](./no-such-file.md)
```

### Expected result
I'd like to see the warning message include line information:
"(source.md, line 1)Invalid file link(~/no-such-file.md)

### Actual result
The actual message is:

(source.md)Invalid file link(~/no-such-file.md)

### Further technical details
Any invalid link generates one warning, regardless of how many times that mistake appears in a document. It would shorten fix cycles to generate a warning for each occurrence.

**Comment by cartermp** [comment]
Here is an example: https://opbuildstorageprod.blob.core.windows.net/report/2016%5C8%5C17%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201608171818515179-908%5Cworkflow_report.html

I've been scouring the document for an offending line, but can't find anything.  The file is in that location, and all links point to it correctly.  If there's an issue here, the line number would be essential.

**Comment by vwxyzh** [comment]
It will release in v2.5.
