### ISSUE TITLE
Localization string resource fallback

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4506]
Detected from this failure: https://dev.azure.com/ceapex/Engineering/_build/results?buildId=54080 when building a loc repo.

```
Microsoft.Docs.Build.JavascriptEngine+JintException: TypeError: tutorial_allContributors is undefined
 at getContribInfo(model) @ D:\appdata\git2\github.com+Microsoft+template..ft.ja-jp+5955c944\1\ContentTemplate\Conceptual.mta.json.js 1:41
```

The root cause is `tokens.json` is removed from loc theme repos by OL (a separate bug) and causes JINT failure. In v2, these string values have English fallback so it works. I suspect both loc and English templates are cloned during build for loc in v2. But this failed for v3 because we only restore the loc repo. Need a graceful way to handle that. 

Loc regression testing is currently disabled due to this.

**Comment by OsmondJiang** [comment]
@fenxu, would you please help to confirm if v2 restore both en-us and loc template repos when building loc repo?  

cc @herohua

**Comment by fenxu** [comment]
@yufeih @OsmondJiang 
No, we won't do template fallback. That totally trusts user specified in "_themes" CRR.

**Comment by OsmondJiang** [comment]
We need re-enable localized CI as soon as possible, to make sure recent changes wouldn't bring too much changes to localized pipeline.

cc @yufeih  @herohua

**Comment by OsmondJiang** [comment]
The root cause is that there is an fallback template package in v2, which contains very old version of docs template:

![image](https://user-images.githubusercontent.com/19990166/57595021-7ff69280-7575-11e9-9c7f-bc323827e509.png)

V3 doesn't have any fallback logic here.

We want to delete these fallback packages in v2, expose this kind of errors to loc repo, what do you think? @yufeih  @fenxu  @superyyrrzz  @herohua

**Comment by OsmondJiang** [comment]
From recent commits by OL, they have fixed the bug, so I will firstly re-enable localization impact test.

![image](https://user-images.githubusercontent.com/19990166/57595204-3b1f2b80-7576-11e9-8072-1a751d09eb13.png)

**Comment by OsmondJiang** [comment]
Below is an example in v2:

![image](https://user-images.githubusercontent.com/19990166/57596658-7291d600-757e-11e9-8cda-ef9e308bbc08.png)
