### ISSUE TITLE
What's the plan to support python?

### ISSUE THREAD

**Issue by arache** [dotnet/docfx#4525]
Hi, is there any plan to support python language?
It has been "coming soon" for a long time on the website, but seems like it's not on the roadmap at all.
https://dotnet.github.io/docfx/tutorial/universalreference/intro_multiple_langs_support.html#3-supported-languages

**Comment by superyyrrzz** [comment]
From issues before, I do not hear much user voice for python support. Although we have a [tool](https://github.com/docascode/sphinx-docfx-yaml) for this, but we have not test integration into docfx and add to document. We can keep this issue open to track user voice.

**Comment by arache** [comment]
@superyyrrzz cool, i'm trying that tool now. 
My case is like, we have a project heavily using c# and python. we're using docfx to generate C# doc and it would be great if we can do the same for python so they'll be in the same style.

**Comment by superyyrrzz** [comment]
Related: #2220

**Comment by tyuanhang** [comment]
Need for python support ~

**Comment by haacked** [comment]
Is there any update about improving Python support?

**Comment by th0ger** [comment]
[Landing page](https://dotnet.github.io/docfx/index.html):

> DocFX can produce documentation from source code (including C#, F#, Visual Basic, REST, JavaScript, Java, Python and TypeScript) as well as raw Markdown files.

[Multiple Languages support](https://dotnet.github.io/docfx/tutorial/universalreference/intro_multiple_langs_support.html#3-supported-languages):

> 3. Supported Languages
>   JavaScript
>   TypeScript (coming soon ...)
>   Python (coming soon ...)

Very inconsistent, what is up and down here?

**Comment by ikivanc** [comment]
Hi team, is there any update for Python support?

**Comment by DanielsCode** [comment]
+1

**Comment by follesoe** [comment]
I would love support for more languages if the architecture was updated to allow for integrating multiple language formats docfx could be a nice alternative to MKDocs.

In my concrete situation I need:
- Python
- Protobuf
- C++
- C#

So right now I am considering "patching" together something using various tools to output Mark Down files, and then use MKDocs to combine it all into one cohesive landing page.

**Comment by bricelam** [comment]
You can generate Python API Docs by using [py2docfx](https://pypi.org/project/py2docfx/) and some [custom templates](https://github.com/bricelam/py2docfx_template).
