### ISSUE TITLE
Question: Is 5 minutes to build documentation normal?

### ISSUE THREAD

**Issue by simax** [dotnet/docfx#454]
I've recently started using docfx on an existing solution that incorporates 8 C# projects with a total of 40,000 LOC. I exclude 3 of the projects (unit tests, end to end tests etc) which brings the LOC down to 28000. 

When I run `docfx docfx.json --serve` from the command line it takes on average 5 minutes to build and then serve the documentation. 

I realize this may be a tricky question to answer but my question is, is this the expected length of time to build for a solution of this size?

P.S. This is running on a i7 2.3 GHz 64 bit Dell laptop with 16 GB Ram on Windows 10.

**Comment by chenkennt** [comment]
@simax 5 minutes seems to be a bit slow, how many classes are there in your project? And can you try run `docfx metadata` and `docfx build` to see which of the build steps is slower?

**Comment by simax** [comment]
It appears the ```docfx metadata``` is taking virtually all the time. It takes ~4 mins 30 seconds. 
```docfx build``` is only taking 30 seconds. There appear to be ~800 classes in the solution

**Comment by chenkennt** [comment]
4.5 mins is a bit slow for a project of this size. If you have more information to share (like the output yaml files), we can take a look why it's slow. And we have incremental build enabled for metadata recently (still in dev branch), it should help the performance if you build the project for a second time.

**Comment by simax** [comment]
Hi Ken,

I don't have VS2015 installed so I can't build the dev branch. I've
attached the api folder which contains the output yaml files as suggested.
Maybe these will help diagnose the performance issue.

Regards,
Simon

**Comment by chenkennt** [comment]
We took a look at your yaml files but didn't find anything special. Could you try to build our [documentation](https://github.com/dotnet/docfx/tree/dev/Documentation) project to compare the performance with your own project?

**Comment by vicancy** [comment]
Hi @simax Any updates?

**Comment by simax** [comment]
Sorry, I've moved on from this project now so no updates I'm afraid.
