### ISSUE TITLE
Error/warning/info/suggrestion count telemetry should be calculated correctly

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4552]
Even they reach the max count(1000), we should calculate the count telemetry correctly per error code.

cc @herohua  @yufeih

**Comment by yufeih** [comment]
where does the requirement came from?

**Comment by OsmondJiang** [comment]
@yufeih, As we talked offline, either we break the build when reach the max error count or we should the correct error count to user.

**Comment by OsmondJiang** [comment]
The conclusion is that once the error code reach the max count, the telemetry actually is not really useful, so let's keep it untouched
