### ISSUE TITLE
Allow git dependencies (theme) to point to a local folder

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4559]
Currently git dependencies must be a remote git repository. To develop template locally, it needs to use template from a local folder. For file references in config, we allow file to be both an external URL or a local file, we could to the same to allow git dependencies to be either a git repository (starting with http:// or https://) or a local folder.

**Comment by KalleOlaviNiemitalo** [comment]
> Currently git dependencies must be a remote git repository.

Having not used DocFX v3 yet, I was wondering how the remote git access is authenticated, but I see it is well documented in [docs/designs/credential.md](https://github.com/dotnet/docfx/blob/1408757302b2f66c9fb1515e97462104533bf9d2/docs/designs/credential.md) on the v3 branch.

**Comment by yufeih** [comment]
@KalleOlaviNiemitalo , docfx calls git.exe, so if you have all credentials hooked up in git credential managers, it will automatically authenticate. 

In other scenarios where you might want to pass the credential using a config, we support setting  [http.extraheader](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpextraHeader) in docfx config file as described in [credentials.md](https://github.com/dotnet/docfx/blob/1408757302b2f66c9fb1515e97462104533bf9d2/docs/designs/credential.md#request-header)

**Comment by yufeih** [comment]
With git dependencies supporting local folders, we might be able to deprecate `resolveAlias` and instead use:

```yaml
dependencies:
    '~': 'source_base_path'
```
