### ISSUE TITLE
[Loc] Manifest of loc file should always be a full set to unblock publish with document error.

### ISSUE THREAD

**Issue by fenxu** [dotnet/docfx#4563]
No matter document has error or not, the item should exist in the manifest. It should be a full set. Otherwise, publish can't handle delete file correctly.

**Comment by yufeih** [comment]
If we turn all the non-fatal errors into warnings for loc, then the output should be a full set of documents

**Comment by fenxu** [comment]
Then we needs a flag to tell whether a file is pass build or not.

**Comment by OsmondJiang** [comment]
it's hard to define what errors are non-fatal, even for loc.

**Comment by yufeih** [comment]
> it's hard to define what errors are non-fatal, even for loc.

What I mean by _non-fatal_ error there means errors that are `returned` vs `thrown`

**Comment by herohua** [comment]
this is now tracked by https://dev.azure.com/ceapex/Engineering/_workitems/edit/106830
