### ISSUE TITLE
[SDP] schema validation rules

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#4567]
- [x] Json Schema Validation For SDP
  - [x] type
  - [x] required
  - [x] ~additionProperties~
  - [x] additionalProperties
  - [x] ~~calls [e.g.](https://ceapex.visualstudio.com/Engineering/_git/docs-ui?path=%2Fpackages%2Fschemas%2FPowerConnector.schema.json&version=GBdevelop&line=161&lineStyle=plain&lineEnd=162&lineStartColumn=1&lineEndColumn=1) only one. should be a mistake.~~
  - [x] definitions
  - [x] '$ref'
  - [x] enum
  - [x] ~footer~
  - [x] format [e.g.](https://ceapex.visualstudio.com/Engineering/_git/docs-ui?path=%2Fpackages%2Fschemas%2FExamination.schema.json&version=GBdevelop&line=162&lineStyle=plain&lineEnd=163&lineStartColumn=1&lineEndColumn=1) only one
  - [x] items
  - [x] maxItems (item & length both are used on array)
  - [x] maxLength
  - [x] ~~metadata/pointer~~
  - [x] minItems
  - [x] minLength
  - [x] ~sections~
  - [x] ~~tags~~

#### Scanned result here:
`forTypes` stands for what type of properties the rule is applied
`valueType` stands for the type of the value of the rule in JavaScript
[rules.json.txt](https://github.com/dotnet/docfx/files/3186430/rules.json.txt)

**Comment by OsmondJiang** [comment]
`ref` and `definitions` need to be supported.

cc @yufeih  @herohua

**Comment by OsmondJiang** [comment]
Add some example link to these items, @mingwli

**Comment by OsmondJiang** [comment]
- [ ] Json Schema Validation For SDP
  - ~~[ ] additionProperties~~
  - [ ] additionalProperties
  - [ ] calls
  - [ ] definitions
  - [ ] '$ref'
  - [x] enum
  - [ ] footer
  - [ ] format
  - [x] items
  - [ ] maxItems
  - [ ] maxLength
  - [x] ~~metadata/pointer~~
  - [ ] minItems
  - [ ] minLength
  - [ ] sections
  - [x] ~~tags~~
- [ ] Json Schema Transform
  - [ ] ContentType
  - [ ] XrefProperties
- [ ] Remove Razor rendering, using template rendering
- [ ] Remove Strong Model
  - [ ] Remove Strong Model Kinds of Attributes
  - [ ] Remove Strong Model Class
- [ ] Remove schema validation on `JsonUtility/YamlUtility.ToObject`

**Comment by yufeih** [comment]
Move sdp work to #4067
