### ISSUE TITLE
Allows to user to switch template (dark or white mode)

### ISSUE THREAD

**Issue by mohaOujda** [dotnet/docfx#4568]
**Operation System**: (`Windows` )

**DocFX Version Used**: 2.42

**Template used**: (`default` or `statictoc` or contain 'Darckfx')

**Steps to Reproduce**:

I want to use two templates (dark and material) for one project and each user can selects his template (material or dark)
it s possible ?

Thanks in advance

**Comment by superyyrrzz** [comment]
Not supported for now, but can achieve through customizing template.

Related: #1862

**Comment by xlnd47** [comment]
Would be a great feature and nowadays it's standard everywhere.

**Comment by Paul-Dempsey** [comment]
Seems a ripe item for someone to contribute ;-)
