### ISSUE TITLE
obj folders - put them in intermediateFolder instead

### ISSUE THREAD

**Issue by tommikiviniemi-srs** [dotnet/docfx#4570]
One really large drawback with DocFx is that it completely pollutes the project with obj folders.

Considering that the intermediateFolder directory exists already - could the obj folder hierarchy be replicated inside it instead of polluting the project?

Also, the api folder is used for both input and output, which can be really problematic. Could the .yml files, the .manifest file, and the auto-generated .gitignore file also be placed inside intermediateFolder, instead of once again polluting source folders?

What's worse is that DocFx puts a .gitignore file and a secret .manifest file in that folder, which is committed to source control. Problem is not everyone are using git so that could be catastrophic!

All in all, all of these problems would be avoided if DocFx was a good citizen and would confine its intermediate files and cache in one place, preferably intermediateFolder as it already exists.

Thanks.

**Comment by superyyrrzz** [comment]
Sounds good. I will close this issue as a dup of #1156.

**Comment by tommikiviniemi-srs** [comment]
Hi superyyyrrzz,

The issue you referred to doesn't mention the problem with the api/ folder (namely it being used both for input/output, and that it creates hidden files with a .gitignore file, but it will only work if you're using git as the SCM).

Do you want me to create a new issue regarding those without mentioning the obj folders?

Thanks!

**Comment by superyyrrzz** [comment]
Looks like there are 2 issues here.

---

Regarding cache folder. DocFX contains 3 kinds of cache files:
1. `obj/xdoc` along with source: cache for `metadata` command. This is #1156 want to make it configurable.
2.  `obj/.cache` along with `docfx.json`: cache for `build` command. This is configurable through `intermediateFolder`.
3. YAML files in `obj`: intermediate files between `metadata` command and `build` command. This is configurable through `metadata/dest` in `docfx.json`.

A clearer solution is to put these 3 in the same folder like `obj`, and make it configurable. I think your major issue here is to make <3> configurable. This is already supported. You can take this project as a sample: https://github.com/docascode/docfx-seed

I will add that <3> is not purely cache. In some user cases this is concreted into git repos, with another pipeline to update them. We have many reference languages other than C# using this pipeline.

---

Regarding `.gitignore`. What you mentioned `.gitignore` files must be generated by `docfx init`. This is just a quick start to make users run docfx. Anything generated is OK to remove if you do not need it.

I see the problem here is that the quick start does not quite convey the "best practice", as you mentioned, not to put intermediate YAML files inside source. This can be an improvement in `init` command.

**Comment by tommikiviniemi-srs** [comment]
Hi and thanks for the reply.

Regarding 3 - `metadata/dest`, my project is set up as such:
`RootFolder/some/paths/ModuleName/Sources`
`RootFolder/some/paths/ModuleName/DocsSource~`

Where my code resides in Sources, and the document sources (.md files, templates etc) reside in `DocsSource~` within `RootFolder/some/paths/ModuleName`.

I have set up the DocFx cache to be created at the root, at `RootFolder/DocFxCache/ModuleName`.

`RootFolder/some/paths/ModuleName/DocsSource~` contains an api folder (input), `RootFolder/some/paths/ModuleName/DocsSource~/api`. As I don't want the output to go into the input folder I have set the dest such as metadata dest such as `RootFolder/DocFxCache/ModuleName/apiOut`. Furthermore, I am outputting the results into `api/` under the dest folder `../DocsIntermediate~` (so the docs should be created to `RootFolder/some/paths/ModuleName/DocsIntermediate~`.

I get the following warning when generating docs:
`[19-05-20 01:54:57.927]Warning:[BuildCommand.BuildCore.Build Document.CompilePhaseHandlerWithIncremental.TocDocumentProcessor.Prebuild.BuildTocDocument](toc.yml)Unable to find either toc.yml or toc.md inside api/. Make sure the file is included in config file docfx.json!`

Does DocFx assume that my api input and output folders are the same, because it's insisting that it's looking for the top inside `api/` (I have configured it to look for those inside `RootFolder/DocFxCache/ModuleName/apiOut`).

DocFx successfully copies the generated `toc.html` from under `RootFolder/DocFxCache/ModuleName/apiOut`, but ignores the rest of the generated files, and shows the above warning.

Here's the relevant snippet from my docfx.json:
```
{
  "metadata": [
    {
      "src": [
        {
          "files": [
            "**.cs"
          ],
          "src": "../"
        }
      ],
      "dest": "../../../../DocFxCache/AssetUsage/apiOut",
      "filter": "filterConfig.yml",
      "disableGitFeatures": false,
      "disableDefaultFilter": false
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/index.md"
        ]
      },
      {
        "files": [
          "**.yml"
        ],
        "src": "../../../../DocFxCache/AssetUsage/apiOut",
        "dest": "api",
      },
      {
        "files": [
          "guides/**.md",
          "guides/**/toc.yml",
          "toc.yml",
          "*.md"
        ]
      }
    ],
```

Why does DocFx insist on the generated toc.yml to reside under `api/`, even though I have the used
```
      {
        "files": [
          "**.yml"
        ],
        "src": "../../../../DocFxCache/AssetUsage/apiOut",
        "dest": "api",
      },
```

Thanks.

**Comment by tommikiviniemi-srs** [comment]
(Feedback: For what it's worth it's hard to configure things because some things like "intermediateFolder" seems to be in relation to where the working directory is, while others are in relation to where docfx.json is. Some things can be relative and others can't. In other words, it's hard to read and configure things when different properties have different roots. Consider the following:
```
"intermediateFolder": "DocFxCache/AssetUsage",
"dest": "../DocsIntermediate~",
```

intermediateFolder is in relation to CWD, while dest is in relation to docfx.json.)

**Comment by tommikiviniemi-srs** [comment]
Regarding my question, I think there's a bug in DocFx.

I just noticed that the generated API doc html files are placed under `RootFolder/some/paths/ModuleName/DocsIntermediate~/DocFxCache/ModuleName/apiOut`, while the generated top.html is placed correctly under `RootFolder/some/paths/ModuleName/DocsIntermediate~/api`.

Furthermore, if I change the output to following:
```
      {
        "files": [
          "DocFxCache/AssetUsage/apiOut/**.yml"
        ],
        "src": "../../../../",
        "dest": "api",
      },
```
, then BOTH the generated toc.html and the generated html files get exported to `RootFolder/some/paths/ModuleName/DocsIntermediate~/DocFxCache/ModuleName/apiOut`. So I think these are bugs:
1) Using a different input and output folder for generated documentation copies the generated toc.html to correct dest location, but ignores ignores dest location for the generated API document html files.
2) This may be a follow-up error of 1) - DocFx seems to assume that the input and output folders are the same given the warning
`[19-05-20 01:54:57.927]Warning:[BuildCommand.BuildCore.Build Document.CompilePhaseHandlerWithIncremental.TocDocumentProcessor.Prebuild.BuildTocDocument](toc.yml)Unable to find either toc.yml or toc.md inside api/. Make sure the file is included in config file docfx.json!`

Thanks.

**Comment by tommikiviniemi-srs** [comment]
Actually, it seems to be random where the html files are placed. On some runs they are placed correctly, on others they are placed in the incorrect sub directory.

Maybe 1) is a follow up error of 2) instead, and the results are random as the results seem to change with different runs.

**Comment by tommikiviniemi-srs** [comment]
Regarding 2), I was able to get rid of the warning by setting the href of the root toc.yml to `../../../../DocFxCache/AssetUsage/apiOut/`. However, the generated page doesn't show the selector with guides and API documentation anymore.

I am giving up for now because it seems to be impossible to use the shared cache folder for output if it resides higher in the hierarchy than the document folder.

The common case is to have a project structure such as
ProjectRoot/src
ProjectRoot/docs

and not
ProjectRoot/docs
ProjecRoot/docs/src

**Comment by superyyrrzz** [comment]
Related: https://github.com/dotnet/docfx/blob/7fae1ef2c69ae448bbecede12b8670e5408e1d71/src/docfx/SubCommands/BuildCommand.cs#L274

**Comment by yufeih** [comment]
Fixed by https://github.com/dotnet/docfx/pull/8388
