### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by tommikiviniemi-srs** [dotnet/docfx#4578]
The generated documentation needs to be hosted online, which makes it impossible to provide a versioned zip with your projects. Problem arises from CORS.

Maybe the generated output could be modified to allow for offline documentation?

Thanks!

**Comment by superyyrrzz** [comment]
try `-t statictoc`

**Comment by tommikiviniemi-srs** [comment]
Hi and thanks for the info.

Let's say I'd like to do two passes of generation, one with statistoc and one without. We have our own template so it must be honoured too.

If I put the statictoc theme in the docfx.json file it works (the toc is static, and our theme is there also). However I'd need TWO docfx.json files (one with statictoc and one without), so I'd rather use the command line parameter to opt in to statictoc whenever I need it. However, that command line parameter seems to completely replace the theme so our css styling is no longer there.

Is there any way to additively load a theme via the command line?

Thanks.

**Comment by superyyrrzz** [comment]
Commandline parameters will overwrite the same one in docfx.json. If I understand correctly, you have 2 scenarios:
1. Most of times, you need a normal site: use `docfx docfx.json` with a normal custom template in config.
2. Sometimes, you need a static site for offline documentaion: use `docfx docfx.json -t statictoc,custom_template` to fully overwrite the template in config.

**Comment by tommikiviniemi-srs** [comment]
Thank you, regarding 2), that's perfect and exactly what I needed!

One piece of feedback would be that the DocFx system is incredibly powerful and configurable, but it's very challenging to find the information on how to configure it. The main pages that document the command line parameters and json parameters don't contain all of the commands, and they are often instead referenced in GitHub tickets and such (take the comma separation between templates for example - I couldn't find information about the *exact* syntax for it anywhere).

Thanks again!

**Comment by tommikiviniemi-srs** [comment]
Btw the statictoc template does not add the .active class (or any other annotation) to the currently selected tab, while the regular one does. So I don't know if it's possible to style the selected tab with the statictoc theme.

Is this by design or an issue?

**Comment by superyyrrzz** [comment]
If you are using IE, it should be existing bug #2910 
If you are using Chrome, this could be a bug in the statictoc template.

**Comment by tommikiviniemi-srs** [comment]
Hi,

It happens both with Chrome and Safari (haven't tested with IE but it seems to be a template problem so am assuming it happens there as well).

So the bug is that with the statictoc template, the tabs (as coming from toc) are such as `<a href="../api/index.html" title="Api Documentation">Api Documentation</a>` even for the currently active tab. They are missing the class `.active`, which is assigned to the active tab with the regular template. This makes it impossible to highlight the selected tab with the statictoc template.

Should I create a bug report somehow or is this enough?

Thanks!

**Comment by superyyrrzz** [comment]
@tommikiviniemi-srs You can report a bug and close this issue, as this bug is a bit away from general "offline documentation" topic.

**Comment by g-amador** [comment]
This issue is still relevant
