### ISSUE TITLE
Notes for users of the schema-driven document processor in v2

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docfx#4586]
_Replying to @superyyrrzz in https://github.com/dotnet/docfx/issues/4250#issuecomment-480336406_:

> Seems the effort will not be too large if DocFX switches to Manatee.Json. However, if the effort is large and no one from community is actually using it, we will consider removing schema processor.

I tried using the schema-driven document processor of DocFX v2.41.0.0 a few days ago, for documenting a history of deployment events. It was not a good fit for that but I think it would work better for documenting relational database schemas. Here are a few notes that may help other users.

## Overwrite files for schema-driven document processor

The schema-driven document processor uses its own type of overwrite files (*.yml.md). [Schema-driven Document Processor(SDP) Design Spec](https://dotnet.github.io/docfx/spec/sdp_design_spec.html) describes the SDP overwrite process but the description is in images rather than text so it cannot be found by searching for "overwrite". The syntax of SDP overwrite files is not the same as in [other overwrite files](https://dotnet.github.io/docfx/tutorial/intro_overwrite_files.html). Rather, it is documented only in [a comment in MarkdownFragmentsCreater.cs](https://github.com/dotnet/docfx/blob/v2.42.3/src/Microsoft.DocAsCode.Build.OverwriteDocuments/MarkdownFragmentsCreater.cs#L14).

The code in the L1 code heading (``# `code`​``) is the *uid* of the article.

The code in the L2 code heading (``## `code`​``) is an *OPath* of the property that will be overwritten with the *\<markdown content section\>*. The *OPath* syntax is not documented but there is a parser in [OverwriteUtility.cs](https://github.com/dotnet/docfx/blob/v2.42.3/src/Microsoft.DocAsCode.Build.OverwriteDocuments/OverwriteUtility.cs).

Each *\<markdown content section\>* can contain any level of headings, even L1 headings (`# text`) and L2 headings (`## text`) if they are not code headings.

Each [link reference definition](https://spec.commonmark.org/0.28/#link-reference-definition) applies only to the *\<markdown content section\>* in which it appears. So if you want to link to the same URL from many such sections, it is easier to put the URL in a [cross reference map file](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-map-file) and use `xref` links.

Each property that is overwritten with an SDP overwrite file should have the `editable` [tag](https://dotnet.github.io/docfx/spec/docfx_document_schema.html#64-tags) in the schema. Otherwise, you get the warning ["You cannot overwrite a readonly property"](https://github.com/dotnet/docfx/blob/v2.42.3/src/Microsoft.DocAsCode.Build.SchemaDriven/Processors/FragmentsValidationInterpreter.cs#L62).

## Template

You need a [custom template](https://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html) that includes a renderer for the custom schema. The template is easier to implement with a JavaScript preprocessor and a Mustache renderer than with a Liquid renderer because you can then reference `{{!master('layout/_master.tmpl')}}` and not have to copy all the breadcrumb bar etc. definitions that could make the template harder to port to future versions of DocFX.

The Jint 2.5.0 JavaScript interpreter used by DocFX v2 [does not yet support ES6](https://github.com/sebastienros/jint/projects/1) features like [`for (let x of y)`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/for...of). It also does not support [named capturing groups](https://developer.mozilla.org/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges) in regular expressions as defined in ECMAScript 2018, even though it allows the `(?<name>x)` syntax because it uses [.NET regular expressions](https://docs.microsoft.com/dotnet/standard/base-types/regular-expressions). Error messages tend to be unclear (#4057).

If your HTML renderer generates heading elements like `h1`, it should also generate `id` attributes for them. Otherwise, the headings do not appear in the "In This Article" affix bar. DocFX does not check whether these `id` attributes clash with ones that it generated from Markdown headings in properties for which the schema specifies [`"contentType": "markdown"`](https://dotnet.github.io/docfx/spec/docfx_document_schema.html#63-contenttype).

**Comment by superyyrrzz** [comment]
👍 It is awesome that you figure out all these by yourself!

Regarding the overwrite files, both the old style "overwrite file" and new "Markdown fragment" is supported in SDP. The document is here: https://github.com/dotnet/docfx/blob/v3/docs/designs/markdown-fragments.md. v3 will only support Markdown fragment as the new overwrite mechanism.

**Comment by KalleOlaviNiemitalo** [comment]
I didn't even think of looking for documentation in the v3 branch 😮

**Comment by superyyrrzz** [comment]
Actually, this doc is copied from an internal v2 doc 😄 , and it will mostly keep same in v2 and v3.

The main reason for multiple L1 is for API reference page, which can contain multiple methods in a page. Each method has a unique UID. Thus, the paired fragment file need a way to overwrite multiple UIDs.

V3 will continue to support YAML header for a normal Markdown file but will abandon [overwrite files](https://dotnet.github.io/docfx/tutorial/intro_overwrite_files.html). Markdown fragment is a better replacement.

**Comment by KalleOlaviNiemitalo** [comment]
In DocFX v3, one apparently has to add `[MarkdownAttribute]` to a property of a class, instead of `"contentType": "markdown"` in a JSON schema. And DocFX v3 reads those classes only [from the Microsoft.Docs.Template assembly](https://github.com/dotnet/docfx/blob/c4cdf36950eb2ccd779acb360d503788cd72674d/src/docfx/docset/Schema.cs#L29) and is not yet able to load any custom template; I suppose that will have to wait until [roadmap phase 3](https://github.com/dotnet/docfx/blob/36aaf7101fba055f7c84a56bac50a3d2f8f6bbd0/docs/roadmap.md#phase-3-schema-contents).

**Comment by superyyrrzz** [comment]
This is prone to change. v3 is working on support JSON schema for better compatibility with v2. #4585
