### ISSUE TITLE
Moniker related log code refine

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#4599]
- [ ] invalid-uid-moniker: Turn it off until real requirement
- [ ] moniker-range-invalid:
  - Configuration: global error
  - File: single File error
- [ ] empty-monikers
  - rename to `moniker-range-out-of-scope`
  - remove this file from the  manifest
- [ ] moniker-config-missing
  - rename to `moniker-range-undefined`
  - remove this file from the manifest
- [ ] moniker-name-conflict: Turn it off since this can be handled by portal
- [ ] publish-url-conflict
  New  scenario: files published to the same url, some with version, some without version (Sample: a.png without version  and a.png with 1.0,2.0)

**Comment by yufeih** [comment]
@928PJY , is this finished?
