### ISSUE TITLE
Warning: Invalid cref value for partial classes

### ISSUE THREAD

**Issue by cdfa** [dotnet/docfx#4631]
**Operation System**: `4.19.42-1-MANJARO GNU/Linux`

**DocFX Version Used**: `docfx 2.42.3.0`

**Template used**: `statictoc, templates/darkfx`

**Steps to Reproduce**:

1. Create a project which has a partial class
2. Add a reference to the partial class with `<cref>`
3. `docfx docfx.json`

**Expected Behavior**:
No warnings

**Actual Behavior**:
```
[19-05-24 03:24:36.098]Warning:[MetadataCommand.ExtractMetadata]Invalid cref value "!:TimelineEvent" found in triple-slash-comments for TranscriptionAnalyser defined in src/Backend/AnalysisController/Analysers/CsharpAnalysers/TranscriptionAnalyser.cs Line 43, ignored.
```

**Comment by superyyrrzz** [comment]
I cannot reproduce this issue. Maybe the partial class does not exist in the same namespace? I think Visual Studio shall also complain the same warning.

**Comment by cdfa** [comment]
Yes, the partial class is in a different namespace. I use Rider because i develop on linux, but it doesn't give a warning about it and I don't know why it should.

**Comment by superyyrrzz** [comment]
Consider this case: if you have 2 namespaces, `A` and `B`. They defines the same class `Foo`. In another namespace `C`, if you use `cref="Foo"`, it does not carry enough information which `Foo` do you want. So it should be `cref="A.Foo"`
