### ISSUE TITLE
batch-1/batch-2/batch-3 localization repo migration test

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4633]
# Batch-1
- [ ] [SCCMDocs-pr.ja-jp](https://github.com/opse2epr/SCCMDocs-pr.ja-JP)[![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/GitHub_opse2epr_SCCMDocs-pr.ja-jp/82987ea3-3784-3bcc-74db-c40b000a8d34_live-sxs_SCCMDocs-prJaJp-V3MigrationTest?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=2040&branchName=dev)

- [ ] [VBA-Docs.ja-JP](https://github.com/opse2epr/VBA-Docs.ja-jp)
- [ ] [VBA-Docs.zh-cn](https://github.com/opse2epr/VBA-Docs.zh-cn)

**Comment by OsmondJiang** [comment]
depends one a new feature request to "Migration Tool", @928PJY  is working on it.

**Comment by yufeih** [comment]
Close in favor of https://github.com/dotnet/docfx/issues/4028
