### ISSUE TITLE
License and Copyright tag

### ISSUE THREAD

**Issue by FlorianOrtner** [dotnet/docfx#4646]
Hi, is it possible to add license and maybe copyright information of a class to api html documentation? 
Code like this:
`
namespace System.Windows.Forms
{
    /// <summary>
    /// Extended forms TabControl with close button.
    /// </summary>
    /// <license>This code is provided under the Code Project Open Licence (CPOL). See http://www.codeproject.com/info/cpol10.aspx for details.</license>
	public class CustomTabControl : TabControl
	{
`

**Comment by superyyrrzz** [comment]
Try set a global metadata `_appFooter`: https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html
