### ISSUE TITLE
The E2E Test ‘Build with --legacy’ Failed in Chinese Environment

### ISSUE THREAD

**Issue by LowEntropyBody** [dotnet/docfx#4655]
![image](https://user-images.githubusercontent.com/26829444/58526256-f85d8480-8200-11e9-9d5e-e1897c6157f1.png)

**Comment by LowEntropyBody** [comment]
@yufeih

**Comment by yufeih** [comment]
@LowEntropyBody would you mind taking a look and come up with a fix? the related code should be in `BuildPage.cs` line 45
