### ISSUE TITLE
Reference not found System.Object

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/docfx#4665]
I am getting a "Reference not found System.Object" exception when running `dotfx.exe` from the source code at `docfx/src/docfx/bin/Debug/net472/docfx.exe` from the [commit for the 2.42 version](https://github.com/dotnet/docfx/commit/780d5aafc):

![image](https://user-images.githubusercontent.com/1857705/58555401-08d22700-8222-11e9-850f-4f79ccb74c1e.png)

Oddly enough, this works with the installed command line `docfx.exe` with the same version (installed with chocolatey). When running from the source code, the `.yml` files are successfully generated in `obj/api`, but the `_site/api` folder is not. Both of these work with the command line tool. 

**Operation System**: (`Windows``)

**DocFX Version Used**: 2.42.4.0

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1. Run `docfx/src/docfx/bin/Debug/net472/docfx.exe docfx.json --serve --force` with a sample dll, e.g. from [docfx-seed](https://github.com/dotnet/docfx/issues/4665#issuecomment-497204118) from the source 

docfx.json
```
{
  "metadata": [
    {
      "src": [
        {
          "files": [ "CustomProject/**/*.cs" ],
          "exclude": [ "**/bin/**", "**/obj/**" ],
          "src": "src"
        }
      ],
      "dest": "obj/api"
    }
  ],
  "build": {
    "content": [
      {
        "files": [ "**/*.yml" ],
        "src": "obj/api",
        "dest": "api"
      },
      {
        "files": [ "articles/**/*.md", "*.md", "toc.yml", "restapi/**" ]
      }
    ],
    "resource": [
      {
        "files": [ "articles/images/**"]
      }
    ],
    "overwrite": "specs/*.md",
    "globalMetadata": {
      "_appTitle": "docfx seed website",
      "_enableSearch": true
    },
    "markdownEngineName": "markdig",
    "dest": "_site",
    "xrefService": [ "https://xref.docs.microsoft.com/query?uid={uid}" ]
  }
}

```

**Expected Behavior**:
 `_site/api` is generated.
**Actual Behavior**:
The exception is thrown and  `_site/api` is empty.

**Comment by superyyrrzz** [comment]
Here is a `Debug.Fail`: https://github.com/dotnet/docfx/blob/7735cd7a0270c2bf716269b34575ee6bfa2ee098/src/Microsoft.DocAsCode.Metadata.ManagedReference/Resolvers/ResolveReference.cs#L69

This will only pop out the window when you build docfx in `debug` mode. The package on chocolatey is built with `release` mode, which will swallow this.

Anyway, this means something is wrong and we should fix it, although it is not a fatal error that will terminate execution. You can try to debug and fix it. PR is welcomed. Or you can also provide a sample repo to help us reproduce.

**Comment by Stamo-Gochev** [comment]
I am able to reproduce this with the docfx-seed project:
https://github.com/docascode/docfx-seed

by running from the source code with command line arguments in the `docfx` project of this repository:
```
<path>\docfx-seed\docfx.json --serve --force
```
