### ISSUE TITLE
Docfx v3 will force call GitHub API to resolve contributor even if it hasn't expired in cache

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#4695]
To improve contributor resolve performance, we call the Graph API to resolve the current commit and first 100 commits after this, so some contributors which are already in the cache and not expired will also be resolved to the latest info.

The impact of this issue is the `impact` mode for comparing diff during the migration doesn't work now, there will be some contributors resolve diff.

one workaround is to add a new config to Docfx to distinguish the `impact` mode, so we can call the API just resolve the current commit contributor instead of the 100 commit contributors.

**Comment by herohua** [comment]
Conclusion:
1. Keep `impact` mode
2. Manually fix cache if we detect any difference.
