### ISSUE TITLE
Embellish select items in the table of contents that are not in an active state

### ISSUE THREAD

**Issue by cedar-ave** [dotnet/docfx#4698]
**Operation System**: Windows

**DocFX Version Used**: Latest

**Template used**: default + custom

**Expected Behavior**:

Ability to create the following types of user experiences (i.e., style select items in the table of contents)

Example 1:

![img](https://user-images.githubusercontent.com/15255009/58909254-e0d63e00-86cf-11e9-929d-f80e98939817.png)

Example 2:

![img2](https://user-images.githubusercontent.com/15255009/58909259-e2a00180-86cf-11e9-9fbe-fe290aebcfb0.png)

**Actual Behavior**:

I'm aware not aware of a way to accomplish this currently.

As one way to this end, would it be possible to add a property in toc.yml that becomes an ID that can then be styled with CSS? Example:

```
 - name: Home
   href: index.md
 - name: About
   href: about/toc.yml
 - name: Install
   href: install/toc.yml
   callout: true
 - name: Access Control
   href: access-control/toc.yml
   callout: true
 - name: ETL
   href: etl/toc.yml
 - name: Web apps
   href: web-apps/toc.yml
```

Thanks for DocFx.

**Comment by cedar-ave** [comment]
Can't speak to whether this is the "best" way but this was accomplished in the following way:

Add `class="{{class}}"` to lines in `templates/partials/li.tmpl.partial`:
```
<a href="{{topicHref}}" class="{{class}}" name="{{tocHref}}" title="{{name}}">{{name}}</a>
```
and
```
<a title="{{name}}" class="{{class}}">{{{name}}}</a>
```
Also do it in `templates/partials/dd-li.tmpl.partial`:

```
  <li><a href="{{topicHref}}" class="{{class}}">{{name}}</a></li>
```

In `toc.yml`:
```
 - name: My-article
   href: my-directory/
   class: my-class
```
In `templates/styles/main.css` add `.my-class`.

**Comment by superyyrrzz** [comment]
Sorry for the late reply. I would also suggest the same solution.
