### ISSUE TITLE
Cannot generate documentation for project using Microsoft.NET.Sdk.WindowsDesktop

### ISSUE THREAD

**Issue by RayKoopa** [dotnet/docfx#4699]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Windows 10 Pro x64 1903

**DocFX Version Used**: 
2.42.2

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Create a .NET Core 3 console app using the **Microsoft.NET.Sdk.WindowsDesktop** SDK
2. Run `docfx.exe metadata ConsoleApp1.csproj` on it in a VS2017 developer command prompt (I also installed the ASP.NET workload).

**Expected Behavior**:
Extracts metadata

**Actual Behavior**:
Cannot create metadata, failing with
`Warning:[ExtractMetadata](...ConsoleApp1.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file '...ConsoleApp1.csproj' with message: The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.  ...ConsoleApp1.csproj`

Am I missing something here?

**Comment by wdhodges** [comment]
The issue is still going on
