### ISSUE TITLE
Build TOC file at the same time with other type of document

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#4704]
Currently, we build TOC file after all other types of document, because we can only get the accurate moniker resolved result after we build the file if we need to consider about the blank page, but since we don't need to, we can build the TOC file at the same time  with other types of  document, which can make the build pipeline more easier.

**Comment by OsmondJiang** [comment]
any reason why we don't need that any more?

**Comment by 928PJY** [comment]
@OsmondJiang confirmed with Curt before, we don't need to do anything special for the blank page
