### ISSUE TITLE
A mentioned System exception should not yield a warning when running docfx

### ISSUE THREAD

**Issue by JoFrMueller** [dotnet/docfx#4738]
**Operation System**: Windows

**DocFX Version Used**:  2.42.4

**Template used**: default

**Steps to Reproduce**:

1. Create a public class with a public method.
2. Add <exception cref="ArgumentException">We throw because of a reason.</exception>
3. docfx docfx.json

**Expected Behavior**: A mentioned System exception should not yield a warning when running docfx.

**Actual Behavior**: 
Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply Templates](api/ClassName.yml)The value of property 'name' in uid 'System.ArgumentException' is not string
        1 Warning(s)
        0 Error(s)

Custom exceptions do work fine. I did test with other exceptions from the System namespace and the warning did stay the same.

**Comment by MartinOSchmidt** [comment]
I think the warning is there, because "System.ArgumentException" is not part of your documentation. While the warning message is somewhat confusing it is still reasonable, as something that you mention/reference won't be documented. Of course for .Net-Framework references it would be great to either exclude these or refer to external documentation ...

**Comment by JoFrMueller** [comment]
> Of course for .Net-Framework references it would be great to either exclude these or refer to external documentation ...

This is what I think too.

Otherwise you won't be able to produce fully documented libraries with exception throwing methods without DocFX warnings.

**Comment by superyyrrzz** [comment]
@JoFrMueller Thank you for reporting this. I think this is fixed in #4693. Could you try the latest version 2.43.2?

**Comment by JoFrMueller** [comment]
@superyyrrzz I did check the latest version 2.43.2 and the error was gone. Thanks for the information.

I close this issue...
