### ISSUE TITLE
Missing asset docfx.zip for release 2.43.1

### ISSUE THREAD

**Issue by x-jokay** [dotnet/docfx#4741]
There is no asset `docfx.zip` for the [release 2.43.1](https://github.com/dotnet/docfx/releases/tag/v2.43.1).

**Comment by superyyrrzz** [comment]
We meet some issue in CI/DI during releasing 2.43.1. I am re-running it to see if it will resolve this.

**Comment by superyyrrzz** [comment]
I will change the CD code for a step dedicated for publish assets + chocolatey.

TODO: split `publishReleaseAndAssetAsync`

**Comment by superyyrrzz** [comment]
fixed. see: https://github.com/dotnet/docfx/releases/tag/v2.43.1
