### ISSUE TITLE
iTextSharp is not mentioned in the documentation except for a release note

### ISSUE THREAD

**Issue by raydixon** [dotnet/docfx#4745]
**Operation System**: n/a

**DocFX Version Used**: 

**Template used**: n/a

**Steps to Reproduce**:

1. Browse to [https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html)
2. In the search box type `iTextSharp`
3. Note the search results.

**Expected Behavior**:
The search results should include at least the [Engineering Guidelines](https://dotnet.github.io/docfx/guideline/engineering_guidelines.html) page (specifically, the [External Dependencies](https://dotnet.github.io/docfx/guideline/engineering_guidelines.html#external-dependencies) section).

**Actual Behavior**:
The search results include only the [Version Notes](https://dotnet.github.io/docfx/RELEASENOTE.html) page. The [release notes for version 2.42.2](https://dotnet.github.io/docfx/RELEASENOTE.html?tabs=csharp#v2422) mention iTextSharp in the context of replacing PDFSharp.

**Comment by superyyrrzz** [comment]
Forgot to update the document.... Fixed in https://github.com/dotnet/docfx/commit/5c630cac7815d48cc7dfe4e2dc6c4162d5b2d8a0
