### ISSUE TITLE
Metadata command evaluates output option twice when run without docfx.json

### ISSUE THREAD

**Issue by lukoerfer** [dotnet/docfx#4747]
**Operation System**: `Windows`

**DocFX Version Used**: Latest (`2.43.1`)

**Template used**: None

**Steps to Reproduce**:

1. Create a new directory and insert a single valid `.cs` source file
2. Run `nuget install docfx.console`
3. Run `.\docfx.console.2.43.1\tools\docfx.exe metadata --output outputDir <SourceFile>.cs`

**Expected Behavior**:
The generated metadata files are in the subdirectory `outputDir`.

**Actual Behavior**:
The generated metadata files are in the subdirectory `outputDir/outputDir`.

In the same way, when specifying `--output sub1/sub2/sub3`, the metadata files are in `sub1/sub2/sub3/sub1/sub2/sub3`. It is getting even more crazy when navigating back to the parent directory via `--output ../sub1/sub2`, as the resulting path is `../sub1/sub1/sub2`.

**Possible cause**:
Out of curiosity, I digged through the code to search for a possible reason for this behavior and found [line 78 of the `ExtractMetadataWorker`](https://github.com/dotnet/docfx/blob/master/src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs#L78). It uses `Path.Combine` to concat two paths called `EnvironmentContext.OutputDirectory` and `input.OutputFolder`. I guess both of them are set to the same value when executing the `metadata` command without a `docfx.json`.

**Comment by superyyrrzz** [comment]
Sorry for missing this... I find the 2 duplicate values are originated from the `ParseOptions` method.

First, the outputDir is passed to `MetadataJsonConfig.Destination`, which finally goes to `input.OutputFolder` you mentioned: 
https://github.com/dotnet/docfx/blob/4207591cb1471619d37d64497721e32e34614230/src/docfx/SubCommands/MetadataCommand.cs#L104

Then, the outputDir is passed to this method's output variable, which finally goes to `EnvironmentContext.OutputDirectory`.
https://github.com/dotnet/docfx/blob/4207591cb1471619d37d64497721e32e34614230/src/docfx/SubCommands/MetadataCommand.cs#L142

If both CLI option `-output` and `docfx.json/metadata/dest` is assigned, DocFX is expected to output to the path combining them, so `ExtractMetadataWorker` is doing his job. However, we should remove L104 here to feed CLI option into `docfx.json`, which caused duplicate output.

Pull requests are welcomed.

**Comment by yufeih** [comment]
The metadata command now expect a configuration in place.
