### ISSUE TITLE
Release Chocolatey Package for 2.43.1 

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#4748]
DocFx 2.43.1 was not released as Chocolatey package. Or is it the same as 2.43. But then in this case [release notes](https://github.com/dotnet/docfx/releases/tag/v2.43.1) are wrong, which mention that Visual Studio 2019 support only came in 2.43.1

**Comment by superyyrrzz** [comment]
I will fix this together with #4741

**Comment by superyyrrzz** [comment]
fixed. see: https://chocolatey.org/packages/docfx/2.43.1
