### ISSUE TITLE
xref migration test

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#4811]
- [ ] [docs-help-pr](https://github.com/OPS-E2E-PPE/docs-help-pr) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/GitHub_OPS-E2E-PPE_docs-help-pr/b9a6c166-48e4-74be-84ea-8265e7483cc6_docfx-migration_docs-help-pr-docfx-migration?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1889&branchName=dev) (Scheduled)
- [ ] [dotnet/docs](https://github.com/OPS-E2E-PPE/docs) [![Build Status](https://apidrop.visualstudio.com/Content%20CI/_apis/build/status/PPE/GitHub_OPS-E2E-PPE_docs/6f8452e0-29d6-a32f-96d9-ed1b5494b46f_docfx-migration_dotnet-docs-migration?branchName=dev)](https://apidrop.visualstudio.com/Content%20CI/_build/latest?definitionId=1989&branchName=dev)

**Comment by yufeih** [comment]
How about we consolidate this and #4409 and #4633 into #4028 and pin just #4628 at the top, so we have just one place to track all the status?

**Comment by yufeih** [comment]
also, `docs-help-pr` is already there in #4628

**Comment by live1206** [comment]
Just want to have a place to hold the xref related repo list. Would #4028 be too long to look into if we consolidate everything into it?

`docs-help-pr` is not only in #4628, but also in #4028. Again, just wanna have an `xref` related list. It could even be in OneNote. Now we have the list both GitHub and OneNote, but only GitHub could show the build status.  

We should think about the CI status dashboard. @928PJY  @herohua

**Comment by herohua** [comment]
+1 on the CI status dashboard

**Comment by herohua** [comment]
Let's have a talk in tomorrow's pick up meeting.

**Comment by yufeih** [comment]
Close in favor of https://github.com/dotnet/docfx/issues/4028
