### ISSUE TITLE
Property description not showing

### ISSUE THREAD

**Issue by faresamr** [dotnet/docfx#4843]
Hi,

The description of referenced class is always empty 

![1](https://user-images.githubusercontent.com/14324348/60656849-ebaffa00-9e58-11e9-8607-bddfd4294a99.PNG)
![2](https://user-images.githubusercontent.com/14324348/60760768-dfd45b80-a043-11e9-82b6-4e32a422bc00.PNG)

**Comment by KalleOlaviNiemitalo** [comment]
I expect DocFX would get the description of the property value from a `<value>…</value>` comment on the property, not from the type of the property.

**Comment by superyyrrzz** [comment]
Docfx shows content in `<returns>...</returns>` tag, but I agree @KalleOlaviNiemitalo 's proposal to use `<value>` is more reasonable for property.

**Comment by KalleOlaviNiemitalo** [comment]
> `<value>` is more reasonable for property.

Especially for a write-only property! 😁

In practice though, I have found it difficult to write useful documentation in `<value>`, without duplicating information that is already in `<summary>` or `<remarks>`. In contrast, `<returns>` in methods feels like a good place to document whether the method always returns a new instance, whether the caller should treat the returned instance as read-only, and who is going to call `Dispose` if the returned instance is disposable.

**Comment by fhinkel** [comment]
So what is supported by docfx? It currently seems to pull the type and desription from `syntax > return` in the yaml file. But I can't set `@return` for a property.

**Comment by dotMorten** [comment]
Properties don't "return" in the same sense. You should use `<value>` for properties instead, and docfx will use it.

**Comment by yufeih** [comment]
Looks like `<value>` is supported: https://github.com/dotnet/docfx/blob/main/src/Microsoft.DocAsCode.Dotnet/Resources/XmlCommentTransform.xsl#LL53-L58C18
