### ISSUE TITLE
Releases could ship with a Mono wrapper script

### ISSUE THREAD

**Issue by alexrp** [dotnet/docfx#4852]
To make using DocFX convenient on my Linux system, I'm using this `docfx` script:

```bash
#!/bin/sh
exec `which mono` $MONO_OPTIONS `dirname $0`/../lib/docfx/docfx.exe "$@"
```

I have this script sitting in `/usr/local/bin`, with DocFX binaries sitting in `/usr/local/lib/docfx`.

This kind of setup is the same that's used for the many managed tools Mono ships (e.g. `mcs`, `ikdasm`, `mdoc`, ...). For example:

```console
$ cat `which mcs`
#!/bin/sh
exec /usr/local/bin/mono $MONO_OPTIONS /usr/local/lib/mono/4.5/mcs.exe "$@"
```

It might be worth considering shipping a script like this with DocFX releases to make things easier for non-Windows users in general.

**Comment by superyyrrzz** [comment]
Nice suggestion. This is partially done in #5076. I am not sure whether this should be `/usr/bin/mono` or `/usr/local/bin/mono`.

**Comment by yufeih** [comment]
Docfx now ships as a .NET global tool for non-windows platforms.
