### ISSUE TITLE
docfx not available in packages folder

### ISSUE THREAD

**Issue by boldt** [dotnet/docfx#4894]
**Operation System**: Windows 10
**DocFX Version Used**: 2.43.2
**Template used**: default

**Steps to Reproduce**:

1. I opened an existing freshly cloned solution in VS  (with a project where docfx ws added with nuget vic VS)
2. I can create docs in Visual Studio via Build -> Build Docs (project is calles Docs)
3. I cannot find the folder `docfx.console.2.43.2` within the packages folder

**Expected Behavior**:

* `docfx.console.2.43.2` should also be availabe in the `packages` folder of the project

**Actual Behavior**:

* I can find the the folder `docfx.console.2.43.2` within `packages` on the computer (where the docfx reference was added to the solution)
* I **cannot** find the folder `docfx.console.2.43.2` within `packages` on the second computer (who cloned the project)

**Comment by boldt** [comment]
I just realized, that my ``csproj`-file looks as follows:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LogLevel>Warning</LogLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

</Project>
```

So, the referenc eis not added by VS.

**Comment by boldt** [comment]
I guess, I found the problem:

# Option 1)  Class Library (.NET Framework)

If I add `docfx.console` with nuget, it will not be added to the `csproj`-file.

# Option 2) Empty project

If I add `docfx.console` with nuget, then it will be added as follows:

```
...
    <None Include="docfx.json" />
...
  <Import Project="..\packages\docfx.console.2.43.2\build\docfx.console.targets" Condition="Exists('..\packages\docfx.console.2.43.2\build\docfx.console.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\docfx.console.2.43.2\build\docfx.console.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\docfx.console.2.43.2\build\docfx.console.targets'))" />
  </Target>

```
# Conclusion

DocFX does not work with "Class Library"-projects

**Comment by boldt** [comment]
My csproj-file looks as follows:

```bash
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  ...
  <ItemGroup>
    ...
    <None Include="docfx.json" />
    ...
  </ItemGroup>
  ...
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="..\packages\docfx.console.2.43.2\build\docfx.console.targets" Condition="Exists('..\packages\docfx.console.2.43.2\build\docfx.console.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\docfx.console.2.43.2\build\docfx.console.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\docfx.console.2.43.2\build\docfx.console.targets'))" />
  </Target>
</Project>
```

The folder `docfx.console.2.43.2` within the `packages`-folder is not created, when I import that solution in VS.

**Comment by boldt** [comment]
Also a `nuget restore` in the command line does not install the package.

**Comment by kdawg1406** [comment]
Me too, nowhere to be found.

**Comment by KalleOlaviNiemitalo** [comment]
That csproj file is not using PackageReference. Is docfx.console listed in packages.config? Perhaps you did not add packages.config to version control.

**Comment by superyyrrzz** [comment]
Could it work to use `choco install docfx` as a standalone tool?

You can also try this: https://github.com/joelmartinez/mdoc-docfx
