### ISSUE TITLE
Empty description for Property Values

### ISSUE THREAD

**Issue by boldt** [dotnet/docfx#4895]
**Operation System**: Windows 10
**DocFX Version Used**: 2.43.2
**Template used**: `default`
**Steps to Reproduce**:

I have the following code:

```csharp
        /// <summary>
        /// Contains the generic varialbe names
        /// </summary>
        Dictionary<string, string> Variables { get; }
```

**Expected Behavior**:

See a description.

**Actual Behavior**:

I see an empty description:

![DocFxEmpty](https://user-images.githubusercontent.com/750793/61471318-dc659c00-a982-11e9-9d59-18207b3ebd26.png)

**Comment by KalleOlaviNiemitalo** [comment]
Duplicate of #4843.

**Comment by superyyrrzz** [comment]
Close as dup.
