### ISSUE TITLE
docfx doesn't give warnings when an md links to fragments that don't exist in the doucment

### ISSUE THREAD

**Issue by lidermanrony** [dotnet/docfx#490]
### Title

docfx doesn't validate url fragments  actually point somewhere valid 
### Functional impact

contrary to links to pages that don't exist (which docfx handles well and issues warnings about), 
If links to a nonexistent fragment in (the same or another) md file, compilation succeeds and code generation is successful, but the resulting html contains a broken link.
### Minimal repro steps
1. add the following to an md file "[this links to a fragment that doesn't exist](./#thisFragmentDoesntExist)"
2. generate and serve the site
3. verify no errors or warnings
4. browse to http:8080 and click on the link
### Expected result

docfx generate should warn on broken link
### Actual result

docfx doesn't warn, site gets generated and when clicking on the link you're not directed anywhere because such a fragment doesn't exist in the html

**Comment by vicancy** [comment]
bookmark validation is implemented now.
