### ISSUE TITLE
Feature Request: Generate YML from SQL Project File

### ISSUE THREAD

**Issue by scottmsoule** [dotnet/docfx#4929]
**Operation System**: (`Windows`,`Linux`,`MacOS`)

**Expected Output**:

1. toc.yml - to include a the various database objects in the project file. For ex:
  - A. Tables
    - 1.  Table name One
    - 2.  Table name Two
  - B. Views
    - 1.  View name One
    - 2.  View name Two
  - C. Stored Procedures
    - 1.  Stored Proc Name One
    - 2.  Stored Proc Name Two
  - D. Functions
    - 1.  Function Name One
    - 2.  Function Name Two

2. YML Content for the object types
  - A. Tables
    - 1. Column listing with datatype and other column properties like Nulls allowed
    - 2. Indexes
    - 3. Primary and foreign keys
    - 4. Triggers
    - 5. Check Constraints
    - 6. Name
  - B. Views
    - 1. Column listing with datatype
    - 2. Name
  - C. Stored Procedures
    - 1. Parameter(s) and datatype(s) with default values
    - 2. Return Type
    - 3. Name
  - D. Functions
    - 1. Parameter(s) and datatype(s) with default values
    - 2. Return Type
    - 3. Name

This, of course could and probably should be expanded, as many database properties aren't listed here, so this is really just a starting point...

**Comment by KalleOlaviNiemitalo** [comment]
I think this has to start by defining the schema and the UID formats, then the templates. After that, plugins can be added to read SQL projects or live databases and generate YAML complying with that schema.

I would be interested in porting some of our database documentation over if this were implemented. Our documentation currently includes also:

- database roles (but not database users, as those can vary between installations)
- granted or denied access rights
- user-defined types (scalar or table)
- synonyms
- result sets of stored procedures and table-valued functions
- filtered indexes
- statistics
- collations, where different from the database default
- object-relational mappings (imported from another system)
- database compatibility level

It does not currently include:

- server logins and database users, as those can vary between installations
- files and filegroups
- spatial and XML indexes
- row-level security
- sensitivity classifications
