### ISSUE TITLE
merging xrefmap.yml files from several projects into one global xrefmap.yml

### ISSUE THREAD

**Issue by ssedyl** [dotnet/docfx#4953]
In the process of trying to set up a main site acting as a portal linking to subsites, an issue arises when it comes to linking the subsites to the main site and to one another.

The main site is generated via its own docfx.json file, each 'subsite' is also generated via their own docfx.json files.

To my understanding, in order to interlink all of these generated sites together, one would have to employ the usage of uid's and xrefmap.yml files.

My current proposed approach would be to take the xrefmap.yml file generated by each project, and merge them into a global xrefmap.yml file stored somewhere on the server - and afterwards, have each docfx.json for each project have an 'xref' property linking to where that global xrefmap.yml is stored. Through this manner, there can be interlinking between subsites if needed. UID's will always be unique so there is no possibility for conflicts arising due to the same uid.

Is this a viable approach? Or does an alternative exist?

To further clarify my intents, here is an example where SubSiteA pertains to a project stored in one location, and SubSiteB pertains to a project stored in a completely different location - each having their own docfx.json:

**[Main Site - url: http://www.example.com/index.html]**
--- Link to SubSiteA's index.html (**uid: SubSiteA**, link will point to **example.com/SubSiteA/index.html**)
--- Link to SubSiteB's index.html (**uid: SubSiteB**, link will point to **example.com/SubSiteB/index.html**)

**[SubSiteA - url: http://www.example.com/SubSiteA/index.html]**
--- Articles tab
--- Api tab
--- etc. tabs
--- Link to SubSiteB's index.html (**uid: SubSiteB**, link will point to **example.com/SubSiteB/index.html**)

In order to achieve this behavior, one would need to merge the output xrefmap.yml file from SubSiteA and SubSiteB into a globalxrefmap.yml. Is there a way to merge them that I am not aware of?

**Comment by superyyrrzz** [comment]
Another option is to reference multiple xrefmaps in one `docfx.json`, e.g:
```
...
    "xref": [
        "http://www.example.com/xrefmap.yml",
        "http://www.example.com/SubSiteA/xrefmap.yml"
   ]
```
Docfx will be aware of the location of different xrefmap, and resolve links to the right place.
