### ISSUE TITLE
Release notes for 2.43.3 and newer is missing

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#4966]
The Release Notes on the Release Page and in RELEASENOTE.md are missing for version 2.43.3 and newer.

It would be nice to have release notes to know what has changed in this version.

**Comment by superyyrrzz** [comment]
We just ignore it because these are minor releases that do not affect the end user. 2.44 is same with 2.43.5, which was released by mistake...

@928PJY

**Comment by pascalberger** [comment]
From a user perspective this is not always clear since you e.g. shipped features / breaking changes with patch releases (e.g. 2.43.1 introduced support for Visual Studio 2019), while on the other hand you do minor releases which should not affect end user (as 2.44). Also there were cases where release notes were forgotten in the past. So it's not clear if it is now intentionally without release notes because it doesn't contain any changes which affects end users or if they were forgotten, and if it is a minor or patch bump also doesn't indicate if it contains new features, breaking changes or only bug fixes.

**Comment by superyyrrzz** [comment]
2.43.1 is another incident... We should try avoiding it in further releases.

Now we have many patch bump release, which contains some minor changes for docs.microsoft.com publish pipeline. It does not contain significant change for community use. This caused the empty release messages. I agree this can lead to confusion. It would be better that we add a meaningful release message anyway.

I think what we can improve:
1. Need to review the release note change through PR review.
2. Enforce [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) to help achieve semantic versioning.

@928PJY @herohua

**Comment by superyyrrzz** [comment]
Close this as each release note is formally reviewed in PR now.
