### ISSUE TITLE
How to set docfx.json file and connect with swagger.json on live server

### ISSUE THREAD

**Issue by uthens** [dotnet/docfx#5012]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Windows
**DocFX Version Used**: 
v2.44.0
**Template used**: (`default` or `statictoc` or contain custom template)
default
**Steps to Reproduce**:
1. Now it's worked on local file i save "swagger.json" file copy to folder "restapi" from debug mode, But i want to know how to link with web api online ?

**Expected Behavior**:
It's should support swgger.jason on online web site  / live server.
And also to related issue on : https://github.com/docascode/docfx-seed/issues/28

If docfx only support 'swagger.json' on local file, How to auto save 'swagger.json' to local folder ? 
now on my web api, i used Swashbuckle .

![Annotation 2019-08-21 180200](https://user-images.githubusercontent.com/10783170/63478205-13176080-c4b3-11e9-9898-c9cb407955b5.png)
![Annotation 2019-08-21 181354](https://user-images.githubusercontent.com/10783170/63478206-13176080-c4b3-11e9-993a-863daa742a15.png)
![Annotation 2019-08-21 181218](https://user-images.githubusercontent.com/10783170/63478207-13aff700-c4b3-11e9-8d05-4feee2e13aa8.png)

**Comment by superyyrrzz** [comment]
Maybe a script to download `swagger.json` before running `docfx.exe`?

**Comment by uthens** [comment]
Hi @superyyrrzz 

1) I run debug on web APIs
2) I manual save file swagger.json and copy file to restapi folder
3) After that i run command line docfx.exe docfx.json --serve
4) It's worked, i see apis methods show on docfx web site.

But i don't want to copy swagger file every time for restapi folder.
When my team modify the source code on web api.

When i run debug on web APIs, it's should automatic generate swagger.json file and  save to restapi folder.

**Comment by superyyrrzz** [comment]
@yishengjin1413 @partychen Do you have any idea?

**Comment by uthens** [comment]
team, do you have any update or any suggestion on this ? , thank you.

**Comment by partychen** [comment]
> team, do you have any update or any suggestion on this ? , thank you.

Swashbuckle has the feature to generate the swagger.json.
```
using System.Web.Http;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using Swashbuckle.Dummy;
using Swashbuckle.Swagger;
using Newtonsoft.Json;
using Swashbuckle.Application;

namespace Swashbuckle.Tests
{
    [TestFixture]
    public class Spike
    {
        [Test]
        public void GetSwagger()
        {
            var httpConfig = new HttpConfiguration();

            // 1) Apply your WebApi config.
            WebApiConfig.Register(httpConfig);
            httpConfig.EnsureInitialized();

            // 2) Generate in-memory swagger doc
            var swaggerProvider = new SwaggerGenerator(
                httpConfig.Services.GetApiExplorer(),
                httpConfig.Formatters.JsonFormatter.SerializerSettings,
                new Dictionary<string, Info> { { "v1", new Info { version = "v1", title = "My API" } } },
                new SwaggerGeneratorOptions(
                    // apply your swagger options here ...
                    schemaIdSelector: (type) => type.FriendlyId(true),
                    conflictingActionsResolver: (apiDescriptions) => apiDescriptions.First()
                )
            );
            var swaggerDoc = swaggerProvider.GetSwagger("http://tempuri.org/api", "v1");

            // 3) Serialize
            var swaggerString = JsonConvert.SerializeObject(
                swaggerDoc,
                Formatting.Indented,
                new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore,
                    Converters = new[] { new VendorExtensionsConverter() }
                }
            );
        }
    }
}
```

**Comment by superyyrrzz** [comment]
Before you run `docfx.exe docfx.json --serve`, I think you have already host the swagger file properly during debugging web API. Then you can simply run `Invoke-WebRequest -Uri $url -OutFile $output` to download it. You may need some script work to automate this.

**Comment by uthens** [comment]
using Swashbuckle.Dummy;
using Swashbuckle.Swagger;
using Swashbuckle.Application; 

 it's not support Version  Swashbuckle.AspNetCore 4.0.1 ? 
![Annotation 2019-08-27 114257](https://user-images.githubusercontent.com/10783170/63741578-e18e0300-c8bf-11e9-8d25-bea1d96fb313.png)

**Comment by KalleOlaviNiemitalo** [comment]
> it's not support .net core ?

Perhaps you should be using https://www.nuget.org/packages/Swashbuckle.AspNetCore/ instead.

**Comment by uthens** [comment]
I resolved on this issue : https://stackoverflow.com/questions/5566942/how-to-get-a-json-string-from-url
