### ISSUE TITLE
<see cref="[constructor]" /> not generating valid links

### ISSUE THREAD

**Issue by LordZoltan** [dotnet/docfx#503]
I have a \<see cref="" /\> in the XmlDoc of a class constructor which points to constructor of the base class - you can see it [here on github](https://github.com/LordZoltan/Rezolver/blob/dev/src/Rezolver/CachingContainerBase.cs#L35).

For completeness - the linked code is:
> `/// If not provided, then the base class' default (see <see cref="ContainerBase.ContainerBase(ITargetContainer, ITargetCompiler)"/> will be used.</param>`

*(it's the last line of a longer `<param />` segment,*

The cref was generated by VS2015's intellisense and passes build validation with xmldoc=true build option enabled.

[The html that is generated for this link](https://github.com/LordZoltan/Rezolver/blob/dev/doc/Rezolver.Documentation/learn-rezolver/rezolver-api/Rezolver.CachingContainerBase.html#L224), however, is wrong - it's just a `<span>` with only part of the name of the constructor.

Again, for completeness:

> `<p>If not provided, then the base class&#39; default (see <span class="xref">Rezolver.ContainerBase.</span> will be used.</p>`

The [target base constructor in question](https://github.com/LordZoltan/Rezolver/blob/dev/src/Rezolver/ContainerBase.cs#L65) has a stub XMLDoc comment - just so I could eliminate the possibility that this was failing because there was no hand-written documentation there.

I've checked the build output and, while I do get a few warnings (that I already know about and will be fixing), none of them relate to this - so it would appear that docfx *believes* it's linking correctly?

As you'll see from the output project I've linked (the second link), I am working with a customised template, but I've not changed anything except html classes and the ordering of parameter columns in the generated output, to list parameter names before their types.

I'm using docfx v2.0.1 from the nuget package.

Many thanks!

**Comment by ansyral** [comment]
this is a bug, constructor's uid contains "#", whose another meaning is link with anchor

**Comment by LordZoltan** [comment]
Thanks!

By the way - I love this tool.  It's absolute gold dust for documenting OSS and internal projects - great work 👍
