### ISSUE TITLE
Anchor reference missbehavior

### ISSUE THREAD

**Issue by HenrykBudzinski** [dotnet/docfx#5037]
**Operation System**: `Windows`

**DocFX Version Used**: `2.43.5.0`

**Template used**: `default`

**Steps to Reproduce**:

1. Clone [this](https://github.com/HenrykBudzinski/Estudo_Documentacao) repository
2. `git checkout 4784edd3be795a1007862665a13c934721f00d72`
3. `dockfx {repo_location}/docs/docfx.json build --serve
4. open `google chrome 76.0.3809.100` and press <kbd>Ctrl</kbd>+<kbd>N</kbd>
5. open the **docfx** generated site (`localhost:8080`)
6. on the top navbar, click `Login.OAuth` option
7. press <kbd>Ctrl</kbd>+<kbd>End</kbd>
8. click in `glossário` link, above header **Lixo**  
   ![01](https://user-images.githubusercontent.com/30120175/63799774-27a88e00-c8e3-11e9-9241-53c8a3f8ae89.JPG)

**Expected Behavior**:
![02](https://user-images.githubusercontent.com/30120175/63799712-02b41b00-c8e3-11e9-8f3e-4b249d606a0a.JPG)  

**Actual Behavior**:
![03](https://user-images.githubusercontent.com/30120175/63799747-165f8180-c8e3-11e9-992a-7916abab8768.JPG)

**Comment by superyyrrzz** [comment]
Sorry for late response. I cannot see your repo now, but this must be related to #3133, which is expected to be fixed since 2.43.2. To clarify, did you use the default template or a custom one?

**Comment by HenrykBudzinski** [comment]
> Sorry for late response. I cannot see your repo now, but this must be related to #3133, which is expected to be fixed since 2.43.2. To clarify, did you use the default template or a custom one?

Sorry @superyyrrzz , I realise that I was creating link to anchors in the wrong way. 

I was creating anchor link like this `[fuu.md file](@fuu#h2-header-somewere-in-fuu)`.

But the right way is describe [here](https://docs.microsoft.com/en-us/contribute/how-to-write-links#links-to-anchors).

When I create link like described in the Microsoft doc above, the "problems" is gone.

- `[fuu.md file](./../SomeDirectory/fuu#h2-header-somewere-in-fuu)`, like this the link works
