### ISSUE TITLE
Question: (How) Can I use the docs.html template for my docfx project?

### ISSUE THREAD

**Issue by EnCey** [dotnet/docfx#504]
Originally asked in the [dotnet/core-docs](https://github.com/dotnet/core-docs/issues/740) repo.

Is the beautiful `docs.html` template / theme available somewhere and are we allowed to use it for our own docfx projects?

I managed to obtain the template with `docfx template export docs.html`, however it lacks all the styling components (CSS, images, etc.). Where can I find these?

**Comment by chenkennt** [comment]
Hi @EnCey, Currently there is no plan to open docs.html for public use.

**Comment by martinoss** [comment]
I would also love to see this open sourced
