### ISSUE TITLE
`docfx init` puts external cross reference services under `build.xref` instead of `build.xrefService`

### ISSUE THREAD

**Issue by stakx** [dotnet/docfx#5053]
**Operation System**: Windows

**DocFX Version Used**: 2.45

**Template used**: default

**Steps to Reproduce**:

1. Run `docfx init` and answer the question about external API references with `https://xref.docs.microsoft.com/query?uid={uid}`:

   > C:\Projects> **`docfx init`**
   > ...
   > Do you want to specify external API references?
   > Supported external API references can be in either JSON or YAML format.
   > Press ENTER to move to the next question.
   > **`https://xref.docs.microsoft.com/query?uid={uid}`**
   >
   > ...
   > Successfully generated default docfx project to C:\Projects\docfx_project                                                                                               

2. Inspect the generated `docfx.json`. Take note of where the cross reference service URL was put.

**Expected Behavior**:

The cross service reference URL `https://xref.docs.microsoft.com/query?uid={uid}` should be put under `$.build.xrefService`, as per [the documentation](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-services).

**Actual Behavior**:

The cross service reference URL is put under `$.build.xref`. This will cause external cross references to be unresolved in generated documentation. I am seeing these warnings during a build:

> Warning:[BuildCommand.LoadSchemaDrivenDocumentProcessors]Unable to download xref map file from https://xref.docs.microsoft.com/query?uid={uid}, details: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): No node deserializer was able to deserialize the node into type Microsoft.DocAsCode.Build.Engine.XRefMap, Microsoft.DocAsCode.Build.Engine, Version=2.45.0.0, Culture=neutral, PublicKeyToken=null

> Warning:[BuildCommand.BuildCore.Build Document]Unable to download xref map file from https://xref.docs.microsoft.com/query?uid={uid}, details: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): No node deserializer was able to deserialize the node into type Microsoft.DocAsCode.Build.Engine.XRefMap, Microsoft.DocAsCode.Build.Engine, Version=2.45.0.0, Culture=neutral, PublicKeyToken=null

If I manually edit `docfx.json` and rename `$.build.xref` to `$.build.xrefService`, the warnings disappear and BCL cross references are correctly resolved.

**Comment by superyyrrzz** [comment]
This hint only means to udpate `xref` instead of `xrefService`, but I agree it need to update the message to avoid confusing user with two similar configurations.

Some thoughts:
1. Add xref service by default. This should be what most users expect.
2. Hint user xrefService is already set by default. Here only needs xref **file**.
