### ISSUE TITLE
ExtractMetadataException when building project

### ISSUE THREAD

**Issue by lunim** [dotnet/docfx#507]
Hello,

I just installed the DocFx.msbuild nuget package (v2.2) for my project and ran a clean build.  I get the following error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"C:\\src\\Common\\Libs\\Lib\\obj/api":["C:\\src\\Common\\Libs\\Lib/Lib.csproj"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":true,"UseCompatibilityFileName":false}: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

I am unable to share the source as it is a private project.  This is a standard .Net4.5 C# project.  I have made no changes to the auto-generated DocFX files.

I was able to make a quick C# sample console app, and that worked correctly.

**Comment by ansyral** [comment]
@lunim , this is a bug, and we're fixing this.

**Comment by chenkennt** [comment]
Fixed in v2.2.1
