### ISSUE TITLE
Running "init-tools.cmd" fails if the path contains spaces

### ISSUE THREAD

**Issue by TheBlueSky** [dotnet/docfx#511]
Hello everyone,

I'm unable to run "init-tools.cmd" successfully because I placed "corefx" repository is in a folder with spaces in its path.

To reproduce the issue, just clone the repository in a folder with space in its path; e.g., `C:\Users\TheBlueSky\Documents\My Programming\Open Source\corefx`, then double click "init-tools.cmd".

Instead of completing the task and exiting, the command file exits writing "error: Programming\Open" in its log file.

I identified couple of places where `%PACKAGES_DIR%` needs to be surrounded by double-quote:

    echo Running: "%DOTNET_CMD%" restore "%PROJECT_JSON_FILE%" --no-cache --packages %PACKAGES_DIR% --source "%BUILDTOOLS_SOURCE%" >> "%INIT_TOOLS_LOG%"
    call "%DOTNET_CMD%" restore "%PROJECT_JSON_FILE%" --no-cache --packages %PACKAGES_DIR% --source "%BUILDTOOLS_SOURCE%" >> "%INIT_TOOLS_LOG%"

However, after surrounding it by double-quote, I started getting "error: The given path's format is not supported."... not sure what path it's talking about and what the format is.

To be kind of sure that the issue is due to the path, I move the repository to a folder that doesn't have spaces in its path. As expected, I was able to run "init-tools.cmd" successfully.

**Comment by qinezh** [comment]
Have to say that you're in the wrong place to post the issue. Here is docfx, the neighborhood of corefx. :joy:

**Comment by TheBlueSky** [comment]
Seriously? I guess I should see an ophthalmologist 😆 

An in a serious note, sorry, I'll move it there :)
