### ISSUE TITLE
System.Threading.Tasks.Dataflow not found

### ISSUE THREAD

**Issue by lunim** [dotnet/docfx#512]
Hello,

On our build servers, running the Microsoft EWDK (https://msdn.microsoft.com/en-us/windows/hardware/drivers/develop/installing-the-enterprise-wdk), we receive the following error:

> Error opening project C:/Common/Libs/Lib/Lib.csproj: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.. Ignored.

We do not have Visual Studio installed on these machines, just the stand-alone MSBuild environment.  In the EWDK, the file can be found here:  \Program Files\Microsoft Visual Studio 12.0\Common7\IDE\FromGAC\System.Threading.Tasks.Dataflow.dll

**Comment by vwxyzh** [comment]
#259

**Comment by vicancy** [comment]
it is now depends on Build Tool 2015

**Comment by CharlesOkwuagwu** [comment]
I have the same problem, but with SQL Server 2017 and SSMS 17.3
see https://stackoverflow.com/questions/46727834/strange-exception-opening-new-ssms-query-window

All fixes I've seen point to installing [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159)

How can a dependency on an old 2015 product affect the smooth running of a fresh installation of SQL Server 2017 Management Studio - one of Microsoft's Flagship products???

This is indeed shameful.
