### ISSUE TITLE
Docfx does not wrap title on word boundary

### ISSUE THREAD

**Issue by peterennis** [dotnet/docfx#513]
![capture44](https://cloud.githubusercontent.com/assets/140737/16971136/01ffd7ca-4dd6-11e6-97e1-bbf249fe82bb.PNG)

I found this reference:
http://stackoverflow.com/questions/23406112/css-word-wrap-that-wraps-whole-word-without-breaking-them

**Comment by superyyrrzz** [comment]
This css will apply to both reference page and conceptual page. For reference page with extreme long namespace/class name (e.g. [this](http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.Build.ManagedReference.BuildOutputs.html)), `word-wrap: break-word; word-break: break-all;` seems to be the best option so far.

**Comment by peterennis** [comment]
Some other examples.
![capture46](https://cloud.githubusercontent.com/assets/140737/17007871/f3deddd2-4ea0-11e6-8731-79cf17605ead.PNG)
![capture47](https://cloud.githubusercontent.com/assets/140737/17007873/fdf91580-4ea0-11e6-9bd7-c2d6801d1001.PNG)

**Comment by svver** [comment]
@superyyrrzz, please consider the workaround for long namespace/class names  I decribed in [this issue](https://github.com/dotnet/docfx/issues/234)

**Comment by peterennis** [comment]
I agree with https://github.com/dotnet/docfx/issues/234 concerning a different location for "Improve this Doc". On a separate line above the text and right aligned as default. Configuration could change alignment with CSS.

**Comment by hellosnow** [comment]
We just moved "improve this doc" button to the right navigation via #626 in develop branch, and it will be in master branch next Monday. Next steps are refining the word wrap for conceptual pages.

**Comment by peterennis** [comment]
@hellosnow, Thanks for the update. I will look into it again after the next release.

**Comment by vicancy** [comment]
similar issue #234

**Comment by hellosnow** [comment]
We fix the title by #1695 , the [github pages](http://dotnet.github.io/docfx/index.html) will be refreshed after v2.18.0 is released.

**Comment by hellosnow** [comment]
The code is in dev branch and not in master yet, the github pages will be refreshed after v2.19 is released.
