### ISSUE TITLE
toc pdf

### ISSUE THREAD

**Issue by yabrochika** [dotnet/docfx#5135]
**Operation System**: (`Windows` or `Linux` or `MacOS`)

**DocFX Version Used**: 

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by yabrochika** [comment]
Does "wkhtmltopdf": {"additionalArguments" -xsl-style-sheet } work on Doxfx pdf generator? I get a black page...

**Comment by superyyrrzz** [comment]
Docfx supports this config. Were you using this? https://github.com/dotnet/docfx/blob/da48dd4c820f4b15dbcf4cc350ab68fabc5292b4/src/docfx/Models/WkhtmltopdfJsonConfig.cs#L19
