### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#5144]
After upgrading from Visual Studio 2017 to Visual Studio 2019 (16.2.5) we cannot build our .NET Core 3.0 documentation anymore because we get the following error:

> Info:[ExtractMetadata]Using msbuild C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin as inner compiler.
> Warning:ExtractMetadataWorkspace failed with: [Failure] Msbuild failed when processing the file 'C:/Foo/Foo.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found. C:/Foo/Foo.csproj

We tried the following combinations of tools but the error remains the same:
- docfx 2.45.1.0, .NET Core 3.0 Preview 6, Visual Studio 16.2.5
- docfx 2.45.1.0, .NET Core 3.0 RTM, Visual Studio 16.2.5
- docfx 2.45.1.0, .NET Core 3.0 RTM, Visual Studio 16.3
- docfx 2.40.12.0, .NET Core 3.0 Preview 6, Visual Studio 16.2.5

I tried to set the `MSBUILD_EXE_PATH`, bu that yields another error (log is from Azure DevOps build pipeline):
> Info:[ExtractMetadata]Environment variable MSBUILD_EXE_PATH is set to C:\build_work_tool\dncs\3.0.100-preview6-012264\x64\sdk\3.0.100-preview6-012264\MSBuild.dll, it is used as the inner compiler.
> Warning:ExtractMetadataWorkspace failed with: [Failure] Msbuild failed when processing the file 'C:/build/_work/87/s/src/Foo/Foo.csproj' with message: The imported project "C:\build_work_tool\dncs\3.0.100-preview6-012264\x64\sdk\3.0.100-preview6-012264\15.0\Microsoft.Common.props" was not found. Also, tried to find "15.0\Microsoft.Common.props" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\ProgramData\chocolatey\lib\docfx\tools\docfx.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths. C:\build_work_tool\dncs\3.0.100-preview6-012264\x64\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props

It looks like it still insists on wanting to use the old version of MSBuild

**Comment by superyyrrzz** [comment]
I cannot reproduce this issue. Here is what I tried:
1. Create an empty class library project targeting .NET Core 3.0.
2. Replace it with the one in `src` of https://github.com/docascode/docfx-seed
3. Run docfx.

I uses docfx 2.45.1, VS16.3.3.

**Comment by bitbonk** [comment]
It is important that VS2017 is not (has never been) installed on the target machine.

**Comment by superyyrrzz** [comment]
Same for me. Could you try `More` => `Export configuration` in Visual Studio Installer? Here is my output:
```
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.CoreEditor",
    "Microsoft.VisualStudio.Workload.CoreEditor",
    "Microsoft.NetCore.Component.SDK",
    "Microsoft.VisualStudio.Component.NuGet",
    "Microsoft.Net.Component.4.6.1.TargetingPack",
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.VisualStudio.Component.Roslyn.LanguageServices",
    "Microsoft.VisualStudio.Component.FSharp",
    "Microsoft.NetCore.Component.DevelopmentTools",
    "Microsoft.VisualStudio.Component.FSharp.WebTemplates",
    "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions",
    "Microsoft.VisualStudio.Component.DockerTools",
    "Microsoft.NetCore.Component.Web",
    "Microsoft.Net.Component.4.8.SDK",
    "Microsoft.Net.Component.4.7.2.TargetingPack",
    "Microsoft.Net.ComponentGroup.DevelopmentPrerequisites",
    "Microsoft.VisualStudio.Component.TypeScript.3.6",
    "Microsoft.VisualStudio.Component.JavaScript.TypeScript",
    "Microsoft.VisualStudio.Component.JavaScript.Diagnostics",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Component.Microsoft.VisualStudio.RazorExtension",
    "Microsoft.VisualStudio.Component.IISExpress",
    "Microsoft.VisualStudio.Component.SQL.ADAL",
    "Microsoft.VisualStudio.Component.SQL.LocalDB.Runtime",
    "Microsoft.VisualStudio.Component.Common.Azure.Tools",
    "Microsoft.VisualStudio.Component.SQL.CLR",
    "Microsoft.VisualStudio.Component.MSODBC.SQL",
    "Microsoft.VisualStudio.Component.MSSQL.CMDLnUtils",
    "Microsoft.VisualStudio.Component.ManagedDesktop.Core",
    "Microsoft.Net.Component.4.5.2.TargetingPack",
    "Microsoft.Net.Component.4.5.TargetingPack",
    "Microsoft.VisualStudio.Component.SQL.SSDT",
    "Microsoft.VisualStudio.Component.SQL.DataSources",
    "Component.Microsoft.Web.LibraryManager",
    "Microsoft.VisualStudio.ComponentGroup.Web",
    "Microsoft.VisualStudio.Component.Web",
    "Microsoft.VisualStudio.Component.IntelliCode",
    "Microsoft.Net.Component.4.TargetingPack",
    "Microsoft.Net.Component.4.5.1.TargetingPack",
    "Microsoft.Net.Component.4.6.TargetingPack",
    "Microsoft.Net.ComponentGroup.TargetingPacks.Common",
    "Microsoft.Net.Core.Component.SDK.2.1",
    "Component.Microsoft.VisualStudio.Web.AzureFunctions",
    "Microsoft.VisualStudio.ComponentGroup.AzureFunctions",
    "Microsoft.VisualStudio.Component.Azure.Compute.Emulator",
    "Microsoft.VisualStudio.Component.Azure.Storage.Emulator",
    "Microsoft.VisualStudio.Component.Azure.ClientLibs",
    "Microsoft.VisualStudio.Component.Azure.AuthoringTools",
    "Microsoft.VisualStudio.Component.CloudExplorer",
    "Microsoft.VisualStudio.Component.Debugger.TimeTravel",
    "Microsoft.VisualStudio.Component.Debugger.Snapshot",
    "Microsoft.VisualStudio.ComponentGroup.Web.CloudTools",
    "Microsoft.VisualStudio.Component.IntelliTrace.FrontEnd",
    "Microsoft.VisualStudio.Component.DiagnosticTools",
    "Microsoft.VisualStudio.Component.EntityFramework",
    "Microsoft.VisualStudio.Component.LiveUnitTesting",
    "Microsoft.VisualStudio.Component.AspNet45",
    "Microsoft.VisualStudio.Component.AppInsights.Tools",
    "Microsoft.VisualStudio.Component.WebDeploy",
    "Component.Microsoft.VisualStudio.LiveShare",
    "Microsoft.VisualStudio.Workload.NetWeb",
    "Microsoft.VisualStudio.Component.Azure.Waverton.BuildTools",
    "Microsoft.VisualStudio.Component.Azure.Waverton",
    "Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites",
    "Microsoft.ComponentGroup.Blend",
    "Microsoft.VisualStudio.Component.Debugger.JustInTime",
    "Microsoft.VisualStudio.Workload.ManagedDesktop",
    "Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1",
    "Microsoft.NetCore.ComponentGroup.Web.2.1",
    "Microsoft.Net.Component.4.7.2.SDK"
  ]
}
```

**Comment by bitbonk** [comment]
We can’t reproduce this issue anymore. It works now.
