### ISSUE TITLE
Improve readability of the default theme

### ISSUE THREAD

**Issue by djee-ms** [dotnet/docfx#5156]
> _Disclaimer:_ This issue is similar to #3283, but #3283 seems more subjective/vague and geared toward parity with docs.microsoft.com. It is also tagged as v3. This issue is more focused and practical, proposes some immediate change to the existing system, with simple CSS tweaks and nothing else.

I would like to propose some changes to the default theme. As mentioned in #3283, the current layout is small and cramped. It focuses on secondary items, while missing primary ones.

## tl;dr

The changes can be summarized with this commit : microsoft/MixedReality-WebRTC@a1c758fccfbce7850228d1d0d425c2f819109e3d

Here is a simple before / after showing the API reference of that project. There are still some issues, but this is I think much better from a readability point of view.

![image](https://user-images.githubusercontent.com/49064175/65826376-ebd85e00-e2be-11e9-9de5-7bf791a96939.png)

### Formatting of inline code blocks

![image](https://user-images.githubusercontent.com/49064175/65826437-e7607500-e2bf-11e9-8a1c-6606bc0fc8a6.png)

❌ Default code style looks like an invalid HMTL link, as it uses roughly the same red color as broken links in Wikipedia
❌ Similarly, code links (that is, `<a>` inside `<code>`) don't display any difference from regular `<code>` blocks (second `<code>` in screenshot is a link, first is not).

✔ Use of red should probably be avoided unless intending to carry a negative meaning
✔ Links should have a consistent color and hovering effect whether inline code or not.

### Header emphasizing in API

![image](https://user-images.githubusercontent.com/49064175/65826510-63a78800-e2c1-11e9-9b5f-4270af392194.png)

❌ The current focus, based on font size and weight, is put on items not of primary interest for an API reference.
❌ The lack of spacing makes critical information lost in a sea of text : class summary, information related to a particular property (and where that block of information stops and the next one start). Compare with _e.g._ https://www.php.net/manual/en/mysqli.commit.php or even https://docs.python.org/3/library/bisect.html
❌ The border on code blocks makes them a visual separator, splitting the member block into two parts. Compare to _e.g._ https://doc.rust-lang.org/book/ch03-02-data-types.html

✔ Spacing should be added to make the class summary stand out; this is the first and most critical piece of information for the class.
✔ Block of information about members (properties, events, etc.) must also be more clearly delimited with spacing.
✔ Emphasize on member names (bold) to start the block of information and delimit it from the previous one

## Remaining issues

Some issues are not addressed yet in this change, generally because the HTML is missing sufficient semantics (CSS class/id) to target those elements in a simple way.

❌ "See also" section is not highlighted at all. Compare this with _e.g._ docs.microsoft.com, where it is a top-level section.
❌ Tables for _e.g._ property values are useless, and their headers unimportant (should not be in bold)
❌ Assembly and namespace are in bold and dark black (`#000000`); compare with  _e.g._ docs.microsoft.com where they are in 35% dark gray instead, no bold.

And on a more subjective note, I find the C# highlighting very poor. Is there any chance to use semantic analysis from Roslyn instead of regex-based highligh.js?

**Comment by djee-ms** [comment]
Ping - Please remove the stale label, this issue has not even been triaged nor looked at in 3 months.

**Comment by superyyrrzz** [comment]
Sorry for the late response. Your proposal and customization to your site make total sense to me. I would be happy to accept if you create a pull request. Thank you!
