### ISSUE TITLE
index.md is missing in sub apis folders

### ISSUE THREAD

**Issue by alimhabib** [dotnet/docfx#5162]
**Operation System**: windows 

**DocFX Version Used**:  latest

**Template used**: default 

**Steps to Reproduce**:

I use the following docfx.json to generate documentation 

        {
      "metadata": [
        {
          "src": [
            {
              "files": "src/ProjectA/**.cs",
              "exclude": [
                "**/obj/**",
                "**/bin/**"
              ],
              "src": ".."
            }
          ],
          "dest": "api/ProjectA"
        },
        {
          "src": [
            {
              "files": "src/ProjectB/**.cs",
              "exclude": [
                "**/obj/**",
                "**/bin/**"
              ],
              "src": ".."
            }
          ],
          "dest": "api/ProjectB"
        }
      ],
      "build": {
        "content": [
          {
            "files": [
              "api/**.yml",
              "api/**/index.md"
            ]
          },
          {
            "files": [
              "articles/**.md",
              "articles/**/toc.yml",
              "toc.yml",
              "*.md"
            ],
            "exclude": [
              "obj/**",
              "bin/**"
            ]
          }
        ],
        "resource": [
          {
            "files": [
              "images/**"
            ],
            "exclude": [
              "obj/**"
            ]
          }
        ],
        "overwrite": [
          {
            "files": [
              "apidoc/**.md"
            ],
            "exclude": [
              "obj/**"
            ]
          }
        ],
        "dest": "_site",
        "globalMetadataFiles": [],
        "fileMetadataFiles": [],
        "template": [
          "default"
        ],
        "postProcessors": [],
        "noLangKeyword": false
      }
    }
but the index.md per api sub folder never be generated I tried `docfx build -serve`  even dofx metada  but nothing generated, any help how to get ride of this my toc.md looks like 

```
    - name: Welcome
      href: articles/
    - name: Project A
      href: api/ProjectA
      homepage: api/ProjectA/index.md
    - name: Project B
      href: api/ProjectB
      homepage: api/ProjectB/index.md
```

Do I miss something to make the build include index.md per api

**Comment by superyyrrzz** [comment]
I believe it should work. Is `api/ProjectA/index.md` there originally?
