### ISSUE TITLE
How to quote slashes in OPath in Markdown fragments?

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docfx#5170]
[docs/designs/markdown-fragments.md](https://github.com/dotnet/docfx/blob/6e1defa9f84216da46c8974796eb6669e5897bbc/docs/designs/markdown-fragments.md#221-overwrite-a-property-in-an-object) says an OPath (Overwrite Path) contains node names separated with slashes. If such name itself contains slashes, how should I quote or encode them in the OPath?

This happens in particular when documenting a parameter of an [OpenAPI 2.0 Path Item Object](https://github.com/OAI/OpenAPI-Specification/blob/fb059ca461bd17b10a9e3e59879f04485886d356/versions/2.0.md#pathItemObject):

```json
{
    "swagger": "2.0",
    "info": {
        "title": "Example",
        "version": "1"
    },
    "paths": {
        "/products/{productId}": {
            "parameters": [
                {
                    "name": "productId",
                    "description": "Want to overwrite this value with Markdown fragments",
                    "in": "path",
                    "required": true,
                    "type": "number",
                    "format": "int64"
                }
            ],
            "delete": {
                "operationId": "deleteProduct",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}
```

I can imagine these syntaxes but I don't know whether any of them has been chosen:

1. Backslash-slash
   ```markdown
   ## `paths/\/products\/{productId}/parameters[name="productId"]/description`
   ```
2. Quotation marks and backslash-slash
   ```markdown
   ## `paths/"\/products\/{productId}"/parameters[name="productId"]/description`
   ```
3. Backslash-u002F
   ```markdown
   ## `paths/\u002Fproducts\u002F{productId}/parameters[name="productId"]/description`
   ```
4. Quotation marks and backslash-u002F
   ```markdown
   ## `paths/"\u002Fproducts\u002F{productId}"/parameters[name="productId"]/description`
   ```
5. Only quotation marks
   ```markdown
   ## `paths/"/products/{productId}"/parameters[name="productId"]/description`
   ```
6. [RFC 6901](https://tools.ietf.org/html/rfc6901) JSON Pointer style, but that would not support escaping brackets
   ```markdown
   ## `paths/~1products~1{productId}/parameters[name="productId"]/description`
   ```

Because of #4250, I am likely to reimplement the overwriting and don't need DocFX v2 or v3 to support these escape syntaxes, but I'd like to stay compatible with the OPath specification of DocFX rather than design something different.

**Comment by superyyrrzz** [comment]
In markdown fragment, OPath is originally borrowed from XPath, while XPath has not escape ability itself. @KalleOlaviNiemitalo mentioned a valid scenario that current markdown fragment design cannot support well. @dend What do you think of this?

**Comment by KalleOlaviNiemitalo** [comment]
I suppose it would be possible to solve this specifically for OpenAPI 2.0, by assigning a UID to the Path Item Object itself and then referring to that in the Markdown fragments.
* The developer could entirely define the UID with "x-uid" or similar property in the Path Item Object. 
  + Pro: It would be easy to see exactly where the UID is defined; no need to guess how DocFX mangles special characters.
  + Con: If the developer wanted to keep the UID consistent with those that [DocFX generates from `operationId`](https://github.com/dotnet/docfx/blob/1280fcb0a055439cd1a76e1c92dd6d6c23b227ca/Documentation/tutorial/intro_rest_api_documentation.md#basic-structure), they would have to repeat the host name and other such things.
* DocFX could automatically generate a UID for each Path Item Object.
  + Pro: Would be consistent with other generated UIDs.
  + Con: The documenter would have to know how DocFX generates the UID from the path.
* The developer could define part of the UID with "x-path-id" or similar property in the Path Item Object.  DocFX would then combine that with the UID of the file, like it combines `operationId`.
  + Pro: Would be consistent with other generated UIDs.
  + Pro: The documenter would not need to know how paths are encoded.

I do think it would be better to have an escaping or quoting syntax, though.

**Comment by KalleOlaviNiemitalo** [comment]
With JSONPath, I'd apparently use this:

```markdown
## `$.paths["/products/{productId}"].parameters[?(@.name="productId")].description`
```

Or perhaps the JSONPath should start with `@.` rather than `$.`, to anchor it to the object that the first-level code heading already selected by UID.

**Comment by superyyrrzz** [comment]
JSONPath looks good. It is similar to XPath and can solve `/` issue by bracket-notation. It is a nice candidate and personally I think docfx could support both XPath and JSONPath.

I have another question. Is there any specification for JSONPath? I find [this](https://goessner.net/articles/JsonPath/), but it is not like JSON Pointer that is defined officially in RFC 6901.

**Comment by KalleOlaviNiemitalo** [comment]
JSONPath looks like a personal project without stability guarantees. ☹️ It is supported in both Newtonsoft's Json.NET and Manatee.Json; I wonder how consistent these implementations are with each other.
