### ISSUE TITLE
Console Error by accessing Logo in offline documentation with template "statictoc"

### ISSUE THREAD

**Issue by eastjie** [dotnet/docfx#5173]
**Operation System**: Windows

**DocFX Version Used**: 2.45.1.0

**Template used**: statictoc

**Steps to Reproduce**:

1.  Create a sample project "docfx init -q";
2.  Change the template to "statictoc";
3.  Build documentation;
4. Open "index.html" with browser, e.g. Chrome from FileSystem.
5. The following exception will be displayed.

```
docfx.vendor.js:4 Access to XMLHttpRequest at 'file:///C:/temp/docfx_init_proj/docfx_project/_site/logo.svg' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
send @ docfx.vendor.js:4

```

**Expected Behavior**:

We use "statictoc" in order to create offline documentation and don't want to host on web server. The exception comes after we have updated the docfx version.

Thanks.

**Comment by superyyrrzz** [comment]
Although I can also see this exception, logo shows as expected.
