### ISSUE TITLE
Trailing 0 cut from TOC entry

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#5175]
**Operation System**: Windows

**DocFX Version Used**: 2.45.0

**Template used**: default

**Steps to Reproduce**:

1. Create a TOC entry containing a trailing 0, e.g. 2019.10

**Expected Behavior**:

TOC entry should be rendered as `2019.10`

**Actual Behavior**:

TOC entry should be rendered as `2019.1`

**Comment by superyyrrzz** [comment]
I cannot reproduce this. Could you provide some sample project?
