### ISSUE TITLE
Nullable value types are rendered properly

### ISSUE THREAD

**Issue by terrajobst** [dotnet/docfx#5180]
This signature

```C#
public static double? Average (this IEnumerable<double?> source);
```

is [rendered](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.average?view=netframework-4.8#System_Linq_Enumerable_Average_System_Collections_Generic_IEnumerable_System_Nullable_System_Double___) as:

```C#
public static Nullable<double> Average (this IEnumerable<Nullable<double>> source);
```

which is valid C# code but it's not idiomatic.

**Comment by KrzysztofCwalina** [comment]
I think it should be rendered as 
```public static double? Average (this IEnumerable<double?> source);```

**Comment by terrajobst** [comment]
Ah yes. Fixed now.

**Comment by docs-product** [comment]
@terrajobst is this feedback related to out-of-the-box DocFX .NET documentation functionality, or `mdoc`?

cc: @mimisasouvanh

**Comment by terrajobst** [comment]
> @terrajobst is this feedback related to out-of-the-box DocFX .NET documentation functionality, or `mdoc`?

It's about how docs are rendered on docs.microsoft.com. Should I file those bugs elsewhere?

**Comment by mimisasouvanh** [comment]
@terrajobst Please file internal issues/requests at https://aka.ms/request-devrel-feature. For this one, we are tracking the feature request here: [Customer Suggestion 130291: C# Nullable types and Tuple types are not rendering idiomatically](https://ceapex.visualstudio.com/Engineering/_workitems/edit/130291/)
