### ISSUE TITLE
C# tuple types aren't rendered properly

### ISSUE THREAD

**Issue by terrajobst** [dotnet/docfx#5181]
This signature

```C#
public static IEnumerable<(TFirst First, TSecond Second)> Zip<TFirst,TSecond>(
    this IEnumerable<TFirst> first,
    IEnumerable<TSecond> second
);
```

is [rendered as](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip?view=netcore-3.0#System_Linq_Enumerable_Zip__2_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___1__):

```C#
public static IEnumerable<ValueTuple<TFirst,TSecond>> Zip<TFirst,TSecond>(
    this IEnumerable<TFirst> first,
    IEnumerable<TSecond> second
);
```

While that is still valid C# it's not idiomatic. Also, it doesn't show the names associated with the tuple elements.

**Comment by dlech** [comment]
Might be fixed by #5163

**Comment by superyyrrzz** [comment]
@dlech This issue is about the result in docs.microsoft.com site, which uses monodoc to generate metadata, instead of through Roslyn. We can keep this open until the site gets the ideal result.

**Comment by docs-product** [comment]
@terrajobst same as #5180 is this feedback related to out-of-the-box DocFX .NET documentation functionality, or mdoc?

cc: @mimisasouvanh

**Comment by terrajobst** [comment]
> @terrajobst same as #5180 is this feedback related to out-of-the-box DocFX .NET documentation functionality, or mdoc?

It's about how docs are rendered on docs.microsoft.com. Should I file those bugs elsewhere?

**Comment by superyyrrzz** [comment]
Track in https://ceapex.visualstudio.com/Engineering/_workitems/edit/130291/
