### ISSUE TITLE
C# nullable reference types aren't rendered

### ISSUE THREAD

**Issue by terrajobst** [dotnet/docfx#5182]
This signature

```C#
public virtual string? ToString();
```

is [rendered as](https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=netcore-3.0#System_Object_ToString):

```C#
public virtual string ToString();
```

That is unfortunate because nullability will is one of the key features of C# 8 and it's vitally important that those show up in the API docs.

**Comment by carlreinke** [comment]
I'm using docfx.console 2.45.1, and it is aware of reference-type nullability.

![image](https://user-images.githubusercontent.com/11667451/66691725-9b191b80-ec55-11e9-883c-44e83aa72706.png)

The `System.Nullable<System.String>` part is wrong though.

**Comment by superyyrrzz** [comment]
@carlreinke docs.microsoft.com uses [mdoc](https://www.mono-project.com/docs/tools+libraries/tools/monodoc/) to extract these information, so this issue may not affect docfx community version.

@terrajobst I have let PM know, and @dend will route these issues properly.

**Comment by docs-product** [comment]
@mimisasouvanh for visibility - this is likely a `mdoc` issue.

**Comment by mimisasouvanh** [comment]
@terrajobst Please file internal issues/requests at https://aka.ms/request-devrel-feature. For this one, we are tracking the feature request here: Customer Suggestion 130291: C# Nullable types and Tuple types are not rendering idiomatically

**Comment by superyyrrzz** [comment]
Track in https://ceapex.visualstudio.com/Engineering/_workitems/edit/130291/
