### ISSUE TITLE
TargetFrameworkMoniker in URL is ignored

### ISSUE THREAD

**Issue by terrajobst** [dotnet/docfx#5183]
In a .NET Framework 4.5 project invoking F1 on `Console.WriteLine` yields this URL:

```
https://docs.microsoft.com/en-us/dotnet/api/system.console.writeline?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Console.WriteLine);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.8
```

Please note the part with `k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5)`. However, this moniker is ignored and the moniker is set to .NET Framework 4.8. This happens regardless whether or not `view=netframework-4.8` is included in the URL or not.

**Comment by yufeih** [comment]
This is caused by MSDN retirement. I've forwarded this bug to the internal team that works on F1. @zhiliangxu

**Comment by docs-product** [comment]
@yufeih - do you already have an internal bug tracking this? In on itself, this is not a DocFX issue.

**Comment by mimisasouvanh** [comment]
@docs-product Internal bug is tracked here: [Bug 130335: F1 Query results does not go to the moniker specified in TargetFrameworkMoniker](https://dev.azure.com/ceapex/Engineering/_workitems/edit/130335)
