### ISSUE TITLE
What does PR 477 to support versioning really do?

### ISSUE THREAD

**Issue by thuannguy** [dotnet/docfx#5218]
I'm trying the (limited) versioning feature that is supported by https://github.com/dotnet/docfx/pull/477

What I don't understand from reading the PR as well as related issue is that what it exactly does. 

```json
{
  "build": {
    "content": [
      {
        "files": "*.yml",
        "src": "v2.0",
        "dest": "v2.0/api",
        "version": "v2.0"
      },
      {
        "files": "*.yml",
        "src": "v2.1",
        "dest": "v2.1/api",
        "version": "v2.1"
      },
      {
        "files": "conceptual/*.md",
        "src": "v2.0",
        "dest": "v2.0",
        "version": "v2.0"
      },
      {
        "files": "conceptual/*.md",
        "src": "v2.1",
        "dest": "v2.1",
        "version": "v2.1"
      },
      {
        "files": "index.md"
      }
    ],
    "dest": "_site"
  }
} 
```

It seems to me that I still have to have separate data folders for each version. So what is the improvement versus:
```json
{
  "build": {
    "content": [
      {
        "files": "conceptualv2.0/*.md"
      },
      {
        "files": "conceptualv2.1/*.md"
      },
      {
        "files": "index.md"
      }
    ],
    "dest": "_site"
  }
} 
```
Here I have two separate folders (conceptualv2.0, conceptualv2.1) to store 2 versions of my docs.

**Comment by superyyrrzz** [comment]
If you only have conceptual Markdown files, I think there is no improvement. If you have multiple versions of the same code base, say multiple YAMLs, you can use this to avoid UID conflict.
