### ISSUE TITLE
--warningsAsErrors does not work

### ISSUE THREAD

**Issue by DavidFeldhoff** [dotnet/docfx#5224]
**Operation System**: Windows 10

**DocFX Version Used**: 2.45.1.0 

**Template used**: default

**Steps to Reproduce**:

1. Create one file with an unvalid link
2. docfx build -l output.log --logLevel Warning
3. website is created with "Invalid file link"-warning as it should
4. docfx build -l output.log --logLevel Warning --warningsAsErrors true

**Expected Behavior**:
The warnings become errors
**Actual Behavior**:
Error:Config file true does not exist!
If I omit the "true" after --warningsAsErrors the website builds with warnings.

What am I doing wrong?
It seems to be the correct format like described in #1991, #3229 and #3230

**Comment by DavidFeldhoff** [comment]
Okay, sorry, it works as designed and I found my problem.
The answer to my question is that --warningAsErrors will not throw errors instead of the warnings. In the output console it is **still just a warning**! The purpose of the parameter is that the $LASTEXITCODE will be set to 1 which you can use in a pipeline.

**Comment by zdrawku** [comment]
Actually it returns Error with error code: 4294967295. I am not sure if this is a common error code for all warnings OR a specific error code for warnings related to broken hyperlinks and internal references (as it is in our case):

![image](https://user-images.githubusercontent.com/11193764/127848563-84222df8-eae1-48c2-98d2-f4be98ddb16a.png)

Either way, I am now using `on exit` event with `warningsAsErrors` option and to return my own error message [as explained here](https://github.com/dotnet/docfx/issues/7433#issuecomment-890918387)
