### ISSUE TITLE
Question: Is it possible to add the search box home page?

### ISSUE THREAD

**Issue by richorama** [dotnet/docfx#530]
The search doesn't seem to appear on the home page. Is this something that can be enabled?

**Comment by qinezh** [comment]
It's by design, as we think that it would be more clean without search box on the home page.

**Comment by richorama** [comment]
ok, is it possible to override the template and add it in somehow?

**Comment by qinezh** [comment]
Hi @madskristensen, you can modify the corresponding template file [index.html.tmpl](https://github.com/dotnet/docfx/blob/dev/Documentation/template/index.html.tmpl) like following:

```
{{!include(/^styles/.*/)}}
{{!include(/^fonts/.*/)}}
{{!include(favicon.ico)}}
{{!include(logo.svg)}}
<!DOCTYPE html>
<!--[if IE]><![endif]-->
<html>
  {{>partials/head}}
  <body data-spy="scroll" data-target="#affix">
    <div id="wrapper">
      <header>
        {{>partials/navbar}}
      </header>
      {{#_enableSearch}}
      <div class="container body-content">
        {{>partials/searchResults}}
      </div>
      {{/_enableSearch}}
      {{{conceptual}}}
      {{>partials/footer}}
    </div>
    {{>partials/scripts}}
  </body>
</html>
```
