### ISSUE TITLE
Version 3: Can't find config file 'docfx.yml/docfx.json' on any OS

### ISSUE THREAD

**Issue by LeMorrow** [dotnet/docfx#5315]
**Operation System**: Tried both `Windows 8.1`, `macOS Catalina` and `ubuntu.18.04`

**DocFX Version Used**: `3.0.0-beta-01392-226208cc8`

**Template used**: Irrelevant, but `default`.

**Steps to Reproduce**:

1. Create a folder with a `docfx.json` file looking like the one below. The contents of the folder or file doesn't seem to matter, but I tested with [this exact folder setup](https://github.com/LeMorrow/APOD.Net/tree/v0.1.0/docs).
```json
{
  "metadata": [
    {
      "src": [
        {
          "src": "../src",
          "files": [
            "Apod/**.csproj"
          ]
        }
      ],
      "dest": "api",
      "disableGitFeatures": false,
      "disableDefaultFilter": false
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "examples/**.md",
          "examples/**/toc.yml",
          "toc.yml",
          "*.md"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "overwrites/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [
      "default",
      "templates/darkfx"
    ],
    "postProcessors": [],
    "markdownEngineName": "markdig",
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}
```

2. Change directory to the folder you created and run  `dotnet tool install docfx --tool-path "." --version "3.0.0-*" --add-source https://www.myget.org/F/docfx-v3/api/v2`

3. Windows:
`docfx restore`
MacOS / Ubuntu:
`./docfx restore`
Edit:
I also tried with an absolute path to no avail.

**Expected Behavior**:
No errors

**Actual Behavior**:
Error:
```
config-not-found ./(0,0): Can't find config file 'docfx.yml/docfx.json' in '.' or subdirectories
```

**More context**:
I understand that version 3 is in beta. The problem is that I want to be able to install DocFX in Github Actions CI regardless of operating system used. Looking at the [software installed on Github-hosted runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners), you can see that I can't use NuGet or Chocolately to install the package unless I'm running on specifically macOS (has NuGet) or Windows (has Chocolately). This is why  `dotnet tool install` would be perfect for me, since I can install the dotnet sdk easily on these runners. 

I am also unable to install the tool globally as recommended in your README, since that [requires a restart of the session before running the tool after a fresh install of .NET Core SDK](https://github.com/LeMorrow/APOD.Net/runs/318420674#step:4:25).

Maybe this should be a separate issue, but would you consider adding the older stable versions as dotnet tools for convenience? Thanks! :smile:

**Comment by yufeih** [comment]
For the `config-not-found` error code, we've temporarily disabled `docfx.json` support before we fully support the `docfx.json` config schema, we'll add it back next month after all the work is completed.

For the `dotnet tool install` problem, it might be a breaking change in .NET Core 3. We are still using .NET Core SDK 2.2 and `dotnet tool install` does not require a restart [as shown here](https://github.com/dotnet/docfx/blob/v3/build.ps1#L42-L43)

**Comment by LeMorrow** [comment]
Hey, the dotnet tool install problem occurs because it has the -g flag. Sorry about the confusion, I only mentioned that in this issue as a way to explain why I couldn't use your [documented way of installing v3](https://github.com/dotnet/docfx/tree/v3#getting-started)
```powershell
dotnet tool install -g docfx --version "3.0.0-*" --add-source https://www.myget.org/F/docfx-v3/api/v2
```
and why I am required to use
```powershell
dotnet tool install docfx --tool-path "." --version "3.0.0-*" --add-source https://www.myget.org/F/docfx-v3/api/v2
```
(I figured you might ask why I didn't install docfx the regular way without the -g flag)

For my actual issue:
Glad to hear `docfx.json` support will be added back next month! Do you have any plans at all on releasing the stable versions as dotnet tools? I believe it would save a lot of workarounds for people using DocFX in GitHub Actions. Unless I'm missing something, it seems very difficult / impossible to install DocFX on their linux machines currently (unless one would create a custom action).

**Comment by yufeih** [comment]
`docfx.json` support is done
