### ISSUE TITLE
code tagname does not work from <code> tags for xaml files

### ISSUE THREAD

**Issue by Laniusexcubitor** [dotnet/docfx#5319]
**Operation System**:
Windows 10

**DocFX Version Used**: 
2.47.0

**Template used**:
default

**Steps to Reproduce**:

1.  Have an xml comment with a code reference to a xaml file:
```CSharp
/// <example>
/// The following example shows stuff.
/// <code source="../../relative/path/to/Examples.xaml" region="ExampleId" language="XML" />
```
or
```CSharp
/// <example>
/// The following example shows stuff.
/// <code source="../../relative/path/to/Examples.xaml#ExampleId" language="XML" />
```
2. Inside the Xaml file:
```XAML
<UserControl x:Class="Examples"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             mc:Ignorable="d"
             d:DesignHeight="300" d:DesignWidth="300">
    <UserControl.Resources>

        <!-- <ExampleId> -->
        <Grid>
        <!-- Example here -->
        </Grid>
        <!-- </ExampleId> -->
``` 

**Expected Behavior**:
referenced code is shown in the documentation.

**Actual Behavior**:
There is an empty code tag in the generated documentation

**Remarks**
In the logs I see
`Warning:[MetadataCommand.ExtractMetadata]Source file 'absolutePathToExamples.xaml#ExampleId' not found.`
The path is valid. If I remove the tagname or region from the code reference the complete content of the example file gets shown just fine.

**Workaround**
When I use overwrites the code reference from the markdown using the following works fine
```md
[!code-xml[Example](../relative/path/to/Examples.xaml#ExampleId)]
```

**Comment by superyyrrzz** [comment]
Overwrites use Markdown syntax, while XML comment in source code does not fully share the same syntax with it. Ideally they should be same.
