### ISSUE TITLE
Triple slash comment 'item' tag generates an empty list item

### ISSUE THREAD

**Issue by martinivanoff** [dotnet/docfx#5343]
The following C# XML comment generates a list with two empty list items.

XML:

`///<list type="bullet">`
`///       <item>Item 1</item>`
`///       <item>Item 2</item>`
`///</list>`

Generated YAML:

`remarks: "\n<ul><li></li><li></li></ul>\n"`

**Comment by vwxyzh** [comment]
See: https://docs.microsoft.com/en-us/dotnet/csharp/codedoc#list

Source code:
https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Transform/TripleSlashCommentTransform.xsl#L188

**Comment by KalleOlaviNiemitalo** [comment]
[`list` in Sandcastle XML Comments Guide](http://ewsoftware.github.io/XMLCommentsGuide/html/e433d846-db15-4ac8-a5f5-f3428609ae6c.htm) says that, for `list/@type="bullet"` and `list/@type="number"`, the inner text of the `item` element is rendered if the `term` and `description` child elements are omitted. "Area-SandcastleParity" might be appropriate.

**Comment by craigfowler** [comment]
It is not only Sandcastle which behaves in this way.  VS Code for example (with Omnisharp) will render list contents as described in this issue.  Here's a screenshot of a tool-tip from an editor.

<img src="https://user-images.githubusercontent.com/982047/103692718-17e99100-4f90-11eb-8319-f0e887af3bdb.png" alt="VSCode-list-tag" height="400">

I hadn't even realised that the `<term>` and `<description>` tags existed.  I've been using bare `<item>` for so long (and supported by every tool I'd used) that I was unaware that technically I was doing anything wrong.  So, I'd support including this feature based on the principle of least astonishment.

For now, though (now I know) I'm happy with the workaround that I must use term & description tags.

**Comment by eli-darkly** [comment]
I was also blindsided by this bug, and will now have to edit the docs in quite a few projects to add `<description>` tags.

**Comment by TermWay** [comment]
If Visual Studio support this, I think it's fair to say that docfx should also support it.

**Comment by dotMorten** [comment]
Nice to see a PR has been submitted to address this. It's been quite an issue for us.
