### ISSUE TITLE
Support for ASCIIDOC

### ISSUE THREAD

**Issue by arnom-ms** [dotnet/docfx#5344]
Feature request:

MarkDown as a format is great for general developer documentation. However for richer documentation you may need something beyond just markdown (and not just mixing markdown & HTML) and one of the standards is ASCIIDOC.
The request is to support ASCIIDOC with docfx as well.

**Comment by herohua** [comment]
As discussed over email, this is not in the scope of DocFX.

**Comment by stasberkov** [comment]
>As discussed over email, this is not in the scope of DocFX.

Can you give a bit more details why? I DocFX supported asciidoc I would use it. All our tech doc is asciidoc, not markdown.
