### ISSUE TITLE
Underscores in markdown heading stripped in id in HTML

### ISSUE THREAD

**Issue by cryxia** [dotnet/docfx#5347]
**Operation System**: Windows
**DocFX Version Used**: 2.47

**Template used**: `default` + `statictoc` 

**Steps to Reproduce**:

1. Add a heading to a markdown file that contains underscores
`# Some_heading_with_underscores`
2. Build documentation 

**Expected Behavior**:
Output html:
`<h1 id="some_heading_with_underscores">Some_heading_with_underscores</h1>`

**Actual Behavior**:
Output html:
`<h1 id="someheadingwithunderscores">Some_heading_with_underscores</h1>`

----
`-` characters are maintained, which is good. According to https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id the `.` can also be part of the id.

**Comment by cryxia** [comment]
I'm quite happy to make this change and add test cases, I'm just not sure which places I need to make the changes...

**Comment by KalleOlaviNiemitalo** [comment]
I guess it comes from `AutoIdentifierOptions.GitHub` here: <https://github.com/dotnet/docfx/blob/9beb7001e8d5b88f2fd0cee4396ef38bed972297/src/Microsoft.DocAsCode.MarkdigEngine.Extensions/MarkdownExtensions.cs#L20>

which causes `LinkHelper.UrilizeAsGfm` to be called: <https://github.com/lunet-io/markdig/blob/6dcef438c4ef716392cfc80cb112ed2dd308e959/src/Markdig/Extensions/AutoIdentifiers/AutoIdentifierExtension.cs#L174-L177>

and it then replaces underscores etc. with dashes: <https://github.com/lunet-io/markdig/blob/6dcef438c4ef716392cfc80cb112ed2dd308e959/src/Markdig/Helpers/LinkHelper.cs#L98-L113>

Changing this would break compatibility with:
- existing hyperlinks to headings
- previewing Microsoft's documentation on GitHub

so I think the change would have to be opt-in via a flag in docfx.json. It would introduce a new dialect, hurting portability later on….

Are you writing new documentation or porting existing documentation to DocFX?

**Comment by cryxia** [comment]
Interestingly I only came across this because I was upgrading from an old
version of docfx at work and all the urls with fragments broke haha. So in
some sense there was already a breaking change.

I could change the normalisation to be configurable with the current
behaviour as default. It would allow me to fix the bug in my case and allow
others to override the normalisation behaviour of ids without having to
embedded html as headers.

What do you think about this plan?

**Comment by KalleOlaviNiemitalo** [comment]
> and it then replaces underscores etc. with dashes: <https://github.com/lunet-io/markdig/blob/6dcef438c4ef716392cfc80cb112ed2dd308e959/src/Markdig/Helpers/LinkHelper.cs#L98-L113>

Oops, no; that method preserves underscores. I think yours are instead being deleted in `Microsoft.DocAsCode.MarkdownLite.MarkdownHeadingBlockRule`: <https://github.com/dotnet/docfx/blob/9beb7001e8d5b88f2fd0cee4396ef38bed972297/src/Microsoft.DocAsCode.MarkdownLite/Basic/BlockRules/MarkdownHeadingBlockRule.cs#L52> <https://github.com/dotnet/docfx/blob/9beb7001e8d5b88f2fd0cee4396ef38bed972297/src/Microsoft.DocAsCode.MarkdownLite/Basic/BlockRules/MarkdownHeadingBlockRule.cs#L75>

This implies that your `docfx.json` lacks the `"markdownEngineName": "markdig"` property that `docfx init` would nowadays set, so DocFX uses the DFM engine, which is still the default even though it is no longer recommended (<https://github.com/dotnet/docfx/pull/2650#issuecomment-382284020>).

**Comment by cryxia** [comment]
Ah, is that what was the issue? The joys of upgrading old dependencies haha.

Thanks for the help, no longer an issue :)
