### ISSUE TITLE
PDF generation fails under Azure DevOps

### ISSUE THREAD

**Issue by frederikolsen88** [dotnet/docfx#5361]
**Operation System**: `windows-2019` (Azure DevOps hosted build agent)

**DocFX Version Used**: 2.48

**Template used**: `default`

**Steps to Reproduce**:

1. Execute build pipeline task to install DocFX and WkHTMLToPDF via Chocolatey:

`choco install docfx -y`
`choco install wkhtmltopdf -y`

2. Execute build pipeline task to build solution.
3. Execute task to build documentation as PDF:

`docfx docfx_pdf.json pdf noStdin`

with working directory

`Projects/Documentation/`

and this [DocFX config and toc.yml](https://github.com/dotnet/docfx/files/3961029/config_and_toc.zip).

**Expected Behavior**:

PDF generated with no fatal errors. The task succeeds and the build pipeline continues.

**Actual Behavior**:

See [build log](https://github.com/dotnet/docfx/files/3961041/build_log.txt). Most the errors seem to be InvalidPdfExceptions. The task fails and the build pipeline stops.

I have referenced similar issues, which is why I'm using the `noStdin` argument. I'm completely stumped, though. The PDF is generated fine locally, and I'm also able to generate websites with it in DevOps. But PDF generation in DevOps just won't work.

**Comment by superyyrrzz** [comment]
You can try this option:
``` json
"pdf": {
  "noStdin": true,
...
```

See #4488

**Comment by yufeih** [comment]
Addressed in v2.73.0 with [a new PDF engine](https://dotnet.github.io/docfx/docs/pdf.html).
