### ISSUE TITLE
Link from parent directory of docfx.json is not generated correctly

### ISSUE THREAD

**Issue by fibann** [dotnet/docfx#5362]
**Operation System**: Windows

**DocFX Version Used**: 2.47

**Template used**: `default`

**Steps to Reproduce**:
Create a project with the following structure

    /
    |-.git
    |-docs
    | |-docfx.json
    | \-index.md
    \-parent.md

docfx.json:

    "build": {
      "content": [
        {
          "files": [
            "**/*.md"
          ]
        },
        {
          "files": [
            "**/*.md"
          ],
          "src": ".."
        }
      ],
      "dest": "_site",
      "globalMetadataFiles": [],
      "fileMetadataFiles": [],
      "template": [
        "default"
      ],
      "postProcessors": [],
      "markdownEngineName": "markdig",
      "noLangKeyword": false,
      "keepFileLink": false,
      "cleanupCacheHistory": false,
      "disableGitFeatures": false
      }
    }

index.md contains a relative link to parent.md:

    [Link to parent](../parent.md)

and viceversa in parent.md:

    [Link to index](docs/index.md)

Running docfx will generate a `site_` folder with `index.html` and `parent.html`

**Expected Behavior**:
`index.html` contains a link to `parent.html` and `parent.html` contains a link to `index.html`

**Actual Behavior**:
The link in `parent.html` is not generated correctly from parent to index isn't - it points to `docs/index.md`. I also get an error message about "(../parent.md#L1)Invalid file link:(~/../docs/index.md)".

**Comment by KalleOlaviNiemitalo** [comment]
I wonder what this item in [Q & A](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#5-q--a) means:

> 3. Do we support **referencing** files outside of current project folder(the folder when `docfx.json` exists)?  
>    A: NO.

Is `parent.md` a **referencing** file and therefore not supported with `docs/docfx.json`?
