### ISSUE TITLE
Inheritdoc not inheriting summaries from internal interfaces.

### ISSUE THREAD

**Issue by ijstern86** [dotnet/docfx#5367]
**Operation System**: Windows

**DocFX Version Used**: 2.48

**Template used**: default

**Steps to Reproduce**:

1. Create Library with **public** class that inherits **internal** interface.
2. Add `/// <summary/>` to internal interface property.
3. Add `/// <inheritdoc/>` to public property in public class that implements internal interface.

**Expected Behavior**: summary **is** copied from internal interface.

**Actual Behavior**: summary **is not** copied from internal interface.

**Background**: I have 20 or more classes that inherit from many different internal interfaces I don't want exposed to clients. The internal interfaces are useful because I have a lot of shared properties between the classes. I do not want to duplicate property descriptions in each of my public classes that implement the internal interfaces.

I really like the docfx project more than other documentation tools I have seen. It would be nice if this could be fixed. If not, is there some kind of workaround that may allow this behavior to work? I've thought about making my internal interfaces public and then trying to exclude them from the documentation, but I'd rather not do that if I don't have to.

I've been working through the code the last day or two trying to figure out how to make this behavior work, but haven't gotten very far yet.

Thanks for any help.

Here is a sample C# project that has the classes/interfaces described above.
[docfx_inheritdoc_issue.zip](https://github.com/dotnet/docfx/files/3969843/docfx_inheritdoc_issue.zip)

**Comment by ijstern86** [comment]
I have a solution to add this functionality. I just want to create a test before I submit a pull request.

I thought about explaining how it would work, but I think reading the code from a pull request would make more sense.

**Comment by ijstern86** [comment]
Before I create tests and submit a pull request, could someone review these code changes and give me some feedback on them.

https://github.com/ijstern86/docfx/commit/7a9184d578ab1e72b77fe10f26ee12588a96e477

I have tested locally and gotten the expected result of comments being inherited from internal interfaces.

Thanks :)

**Comment by KalleOlaviNiemitalo** [comment]
I cannot test now, but I wonder if your code does the right thing in this case:

```C#
internal static class Outer
{
    public interface IInner
    {
        /// <summary>Should inherit this.</summary>
        void Method();
    }
}

public class Implementation : Outer.IInner
{
    /// <inheritdoc/>
    public void Method() {}
}
```

**Comment by ijstern86** [comment]
Thanks for the input. I'll try to test that condition later today.

**Comment by JimBobSquarePants** [comment]
What can we do to kickstart any movement on a fix for this?
