### ISSUE TITLE
Feature Request: Versioning Suggestions Based on API Changes

### ISSUE THREAD

**Issue by Chiramisu** [dotnet/docfx#5372]
**Operation System**: Windows and WSL
**DocFX Version Used**: 2.47.0.0
**Template used**: default
**Steps to Reproduce**: n/a

**Feature Request**:
It would be fantastic if DocFX could suggest the next [semantic version](https://semver.org/) based on the changes to the API. At the least, I would think a suggestion whether or not to rev the MAJOR version number should be doable, and still very helpful, especially for changes to unfamiliar code.

**Comment by Chiramisu** [comment]
Just some thoughts on how this could be implemented:

- Say you have a method with a particular signature, but you change a parameter type in the signature (or some other change), that would be a clear indicator that the MAJOR version should rev since the API has actually changed, yes?
- If no API changes have occurred, but several files have been modified significantly, that could be an indicator that the MINOR version should rev.
- If you made only a few small changes, that may signal a simple PATCH rev.

You may make all of this relevant to the last tagged commit, or perhaps compared to the `master` branch. This could all be configurable, including the thresholds for MINOR and PATCH revs. I suspect this should be relatively straightforward to implement.

With a little guidance on where I might begin, I'm not opposed to trying my hand at this. 😉

**Comment by yufeih** [comment]
This is probably better suited for [.NET Package Validation](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview), the baseline version package validator detects binary and source breaking changes, that projects seems to be a better place for the ask whereas docfx's main concern is producing documentation.
