### ISSUE TITLE
Default template syntax highlighting is hard to read

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#540]
Various aspects of the colour choices for the default template are hard to read, but when you use an example (so not just a declaration) it's really bad. Here's an example from some of the docs I'm producting:

![api example](https://cloud.githubusercontent.com/assets/17011/17193887/06aafb7e-544d-11e6-8c7f-7f5931b4e367.png)

The low contrast between the background and the non-comment, non-keyword, non-string-literal text makes it really painful.

I could obviously fix this locally by copying the default template and changing the colours myself, but it seems to me like this colour scheme isn't going to be right for anyone.

**Comment by qinezh** [comment]
Already changed the `highlight.js` theme to `github-gist`
