### ISSUE TITLE
Guidance on building plugins

### ISSUE THREAD

**Issue by gsmeets** [dotnet/docfx#5431]
I'm new to docfx, but I want to start using it for our projects. I'll be needing to write some plugins to get code samples (js) properly into the documentation. I'm happy to work on that myself, but I see that v3 is in the works.

Is there any guidance on how to write v2 plugins so that they remain fairly compatible with v3? I can't seem to find much documentation on plugins in general, let alone this subject.

**Comment by yufeih** [comment]
> Is there any guidance on how to write v2 plugins so that they remain fairly compatible with v3

v2 plugins won't be compatible with v3. v3 intentionally limit the capabilities of plugins, and there aren't much extension point to contribute to in the initial phase. This is one of the major architectural difference.

**Comment by KalleOlaviNiemitalo** [comment]
Now I'm curious what Microsoft is doing to [their many plugins](https://github.com/dotnet/docfx/issues/4250#issuecomment-479936230) in their transition from DocFX v2 to v3. Can the plugins be migrated to the extension points provided by DocFX v3, or are they being replaced with preprocessing steps that write files for DocFX to read?

**Comment by yufeih** [comment]
> Now I'm curious what Microsoft is doing to [their many plugins](https://github.com/dotnet/docfx/issues/4250#issuecomment-479936230) in their transition from DocFX v2 to v3. Can the plugins be migrated to the extension points provided by DocFX v3, or are they being replaced with preprocessing steps that write files for DocFX to read?

They are been replaced with pre processing steps and files. Injecting C# code in-process does not fit a lot of our scenarios. Reference language importer as an example, we support more than .NET. Java, python, javascript, powershell... these importers are written using there own language.

Some of the features which used to be plugins (like versioning, localization) are now first class concepts in docfx v3 with much better support.
