### ISSUE TITLE
change default option for init

### ISSUE THREAD

**Issue by peterennis** [dotnet/docfx#544]
I want to set the init default to not create a new project and overwrite files. This way it can be scripted without overwriting work in process.
How can I do that?
![capture54](https://cloud.githubusercontent.com/assets/140737/17237959/5d8b9812-550c-11e6-87f6-23a90070e039.PNG)

**Comment by chenkennt** [comment]
Hi @peterennis , do you mean you want `docfx init` to create a `docfx.json` under current folder instead of currently creating a `docfx_project` folder and a bunch of template files?

**Comment by peterennis** [comment]
No. My intention is to avoid "Click Fever".
e.g. Working too long and being tired, the user is presented with a message:
"Do you really want to overwrite all your valuable data? (Default: Yes)" Press OK to Continue...

The default response to a prompt should be safe.
I would choose to set the default to "No" and explicitly have to select "Yes" for an event that could involve overwriting existing files.
If the default is configurable it can be set as desired by the user.

**Comment by chenkennt** [comment]
We have changed the default option to no when asking whether to overwrite existing files.
