### ISSUE TITLE
Allow custom filename for PDF output file

### ISSUE THREAD

**Issue by trush44** [dotnet/docfx#5460]
When generating a PDF document, I don't see a way to specify the output filename. Can a **name** configuration setting be added to the pdf section of docfx.json that would name the output file whatever we want (e.g. My Custom Documentation Name.pdf)

**Comment by icnocop** [comment]
I think one of the issues/complications is that docfx generates a separate PDF file for each TOC file and you can have multiple TOC files in a `pdf` section.

**Comment by yufeih** [comment]
Addressed in v2.73.0 with [a new PDF engine](https://dotnet.github.io/docfx/docs/pdf.html).
