### ISSUE TITLE
Generating Markdown?

### ISSUE THREAD

**Issue by lovettchris** [dotnet/docfx#5509]
Can docfx Generate Markdown?  Specifically I want to generate Github Pages Markdown (integrating with Jekyll, with nice FrontMatter and a .yml toc).  I can do it myself using [XmlDocMarkdown](https://github.com/ejball/XmlDocMarkdown) and the result is pretty nice, but I'm wondering if docfx has any plans in this area so I can decide which doc gen platform to build on...

![image](https://user-images.githubusercontent.com/18707114/73582030-4d146780-4440-11ea-9528-0efafd728b46.png)

**Comment by KalleOlaviNiemitalo** [comment]
> Can docfx Generate Markdown?

Not yet; see <https://github.com/dotnet/docfx/issues/684>.

**Comment by yufeih** [comment]
Close as dup
