### ISSUE TITLE
Dotnet global tool

### ISSUE THREAD

**Issue by wekempf** [dotnet/docfx#5542]
**Operation System**: all

**DocFX Version Used**: n/a

**Template used**: n/a

**Steps to Reproduce**: n/a

**Expected Behavior**: docfx can be installed as a dotnet global tool

**Actual Behavior**: docfx cannot be installed as a global tool

With all the ways you can install docfx, it's surprising that installing as a dotnet global tool isn't one of them.

dotnet install --global DocFX.Tool

That just seems like the most natural way to install a .NET build tool.

**Comment by yufeih** [comment]
v3 is distributed as a global tool from start. v2 is currently not on .NET Core yet.

**Comment by KalleOlaviNiemitalo** [comment]
@yufeih Does Microsoft intend to port DocFX v2 to .NET Core?

**Comment by yufeih** [comment]
The team does not currently have the resource to commit on that. See the v2 strategy here https://github.com/dotnet/docfx/blob/dev/Roadmap.md#v2-strategy

**Comment by 0xced** [comment]
> v3 is distributed as a global tool from start.

For the record, you can install `docfx` v3 (preview) as a [.NET Core global tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) by running the following command:

```
dotnet tool install -g docfx --version "3.0.0-*" --add-source https://docfx.pkgs.visualstudio.com/docfx/_packaging/docs-public-packages/nuget/v3/index.json
```

You can read more about docfx v3 in the [v3 branch](https://github.com/dotnet/docfx/tree/v3).

**Comment by yufeih** [comment]
Global tool published to NuGet: https://www.nuget.org/packages/docfx
