### ISSUE TITLE
Question: How can I hide left navigation bar?

### ISSUE THREAD

**Issue by picolino** [dotnet/docfx#5545]
Is it possible to hide left navigation bar like on screenshot?
I want to just display content of article without any navigation on the left.
![image](https://user-images.githubusercontent.com/17460456/74939872-a3524600-5401-11ea-83ee-936f44577dcc.png)

**Comment by KalleOlaviNiemitalo** [comment]
If you want to hide the left navigation bar from an individual page, add an [YAML header](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#yaml-header) like this:

```yaml
---
_disableToc: true
---
```

Alternatively, DocFX implicitly omits the TOC if if your top-level `toc.yml` links directly to the \*.md file without making it a child of anything. The page is then accessible directly via the top bar.

There has been a problem where omitting the TOC causes link markers at the left side of headings to reach beyond the left edge of the page. If that has not been fixed yet, then you can work around it by adding a CSS rule via a custom theme.

**Comment by picolino** [comment]
@KalleOlaviNiemitalo it works, thank you very much
