### ISSUE TITLE
Building DocFX v2.49 requires Visual Studio 2019, although README.md says 2017

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docfx#5553]
**Operation System**: Windows

**DocFX Version Used**: v2.49

**Template used**: N/A

**Steps to Reproduce**:

1. `git clone --branch master --single-branch https://github.com/dotnet/docfx/`
2. `cd docfx`
3. `git checkout v2.49`
4. Verify that `README.md` says Visual Studio 2017 is required: <https://github.com/dotnet/docfx/blob/d8f389f391d31dcc0b943fb5bf58077441a23dbf/README.md#L47-L50>
5. Open `docfx.sln` with Visual Studio Professional 2017 version 15.9.20.
6. Build Solution.

**Expected Behavior**:

The build succeeds.

**Actual Behavior**:

The build fails, because Visual Studio 2017 supports only up to C# 7.3, which does not support the `using` declarations that were added in <https://github.com/dotnet/docfx/pull/5470>. For example:

```
2>        FileAbstractLayerExtensions.cs(17,19,17,22): error CS1003: Syntax error, '(' expected
2>        FileAbstractLayerExtensions.cs(17,55,17,56): error CS1026: ) expected
2>        FileAbstractLayerExtensions.cs(23,19,23,22): error CS1003: Syntax error, '(' expected
2>        FileAbstractLayerExtensions.cs(23,55,23,56): error CS1026: ) expected
2>        FileAbstractLayerExtensions.cs(38,19,38,22): error CS1003: Syntax error, '(' expected
2>        FileAbstractLayerExtensions.cs(38,53,38,54): error CS1026: ) expected
2>    Done building target "CoreCompile" in project "Microsoft.DocAsCode.Plugins.csproj" -- FAILED.
```

## Possible fix, if the dependency change was accidental

Revert #5470.

Change `src/Shared/base.props` and `src/Shared/base.netstandard.props`  to specify C# 7.3 so that the problem will be detected by automatic tests if it recurs.

## Possible fix, if the dependency change was deliberate

Update the documentation to say that building DocFX now requires Visual Studio 2019:

* `README.md`: At least under "Prerequisites": <https://github.com/dotnet/docfx/blob/d8f389f391d31dcc0b943fb5bf58077441a23dbf/README.md#L47-L50>
  Perhaps also under "Running Status": <https://github.com/dotnet/docfx/blob/d8f389f391d31dcc0b943fb5bf58077441a23dbf/README.md#L69-L73>
* `appveyor.yml`: How did that even work? <https://github.com/dotnet/docfx/blob/d8f389f391d31dcc0b943fb5bf58077441a23dbf/appveyor.yml#L8>
* [the v2.49 release notes](https://github.com/dotnet/docfx/releases/tag/v2.49)

This one apparently need not be changed:

* `src/Microsoft.DocAsCode.Metadata.ManagedReference/MsBuildEnvironmentScope.cs`: It seems the DocFX binaries still support MSBuild of Visual Studio 2017, even if they can no longer be built with that version. <https://github.com/dotnet/docfx/blob/d8f389f391d31dcc0b943fb5bf58077441a23dbf/src/Microsoft.DocAsCode.Metadata.ManagedReference/MsBuildEnvironmentScope.cs#L83>

There is also a reference to Visual Studio Enterprise 2019, so I am not sure whether it is possible to pass the tests with only Visual Studio Professional 2019 installed: <https://github.com/dotnet/docfx/blob/d8f389f391d31dcc0b943fb5bf58077441a23dbf/test/docfx.Tests/MetadataCommandTest.cs#L59>

**Comment by yufeih** [comment]
I've updated README to require 2019, we cannot stuck on old software forever 😄

**Comment by KalleOlaviNiemitalo** [comment]
I had hoped that DocFX v2 would stay on Visual Studio 2017 and DocFX v3 would become viable before Visual Studio 2017 goes out of support. Oh well…

**Comment by yufeih** [comment]
Is there a compelling reason to stay on 2017? Since this only affect people how are actually building docfx from source code.

**Comment by KalleOlaviNiemitalo** [comment]
Licensing when the developer has no Visual Studio subscription.

Visual Studio Community 2019 might be possible but proprietary plugins would then have to be developed with a separate Visual Studio instance, risking accidental license violations.
