### ISSUE TITLE
Can't Compile DocFx Project When FIPS Compliance Mode is Enabled

### ISSUE THREAD

**Issue by ianlee74** [dotnet/docfx#5583]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Windows 10

**DocFX Version Used**: 
DocFx Console v2.48.1

**Template used**: (`default` or `statictoc` or contain custom template)
statictoc

**Steps to Reproduce**:

1. Enable Windows FIPS compliant mode by setting Enabled=1 at HKLM\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy.
2. Start a new DocFx Project in VS2019.
3. Recompile Solution

**Expected Behavior**:
Should compile without any issues and generate the _site content.

**Actual Behavior**:
Compile fails and generates the following error: "System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."

**Comment by KalleOlaviNiemitalo** [comment]
The [Reduced FIPS impact on Cryptography](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/#base-classes) changes in .NET Framework 4.8 might avoid that error. Are you running a lower version?

**Comment by ianlee74** [comment]
I tried with .NET 4.8. No improvement. Thanks for the suggestion.

**Comment by KalleOlaviNiemitalo** [comment]
DocFX 2.48.1 targets .NET Framework 4.7.2, so the .NET Framework 4.8 change does not apply to it by default. Can you try adding this to `docfx.exe.config` (and perhaps to `plugins\docfx.plugins.config` if you use plugins)?

```XML
<runtime>
  <AppContextSwitchOverrides value="Switch.System.Security.Cryptography.UseLegacyFipsThrow=false" />
</runtime>
```

If that works, I assume it would be easy to add to the DocFX source code as well.

**Comment by ianlee74** [comment]
@KalleOlaviNiemitalo that worked. This also worked.

```
<runtime>
    <enforceFIPSPolicy enabled="false" />
</runtime>
```

That complicates our automated build process a tad but not a big deal. It would certainly simplify things if DocFx contained this option by default.

THANKS!
Ian

**Comment by KalleOlaviNiemitalo** [comment]
I wonder if the option could be set as an environment variable, `COMPlus_enforceFIPSPolicy=0`. If so, that might be easier in your build process.

`enforceFIPSPolicy` is classified as a `DWORD`-type setting in older versions of the CoreCLR source code, and the configuration file parser supports `enabled="true"` and `enabled="false"` for those, but the environment variable parser seems to require a hexadecimal number. (.NET Core ignores `enforceFIPSPolicy` because it does not implement its own cryptography.)
