### ISSUE TITLE
Add a generic block to the TripleColon markdig extension

### ISSUE THREAD

**Issue by cryxia** [dotnet/docfx#5585]
Currently in the code we have the triple colon syntax (:::) that can be used to define zones, images, code and chromless blocks in code. There is a TODO to extend this syntx for other things such as monikers, rows etc (which may already be done). I want to add a generic version so that the following:
```
::: generic class="foo" id="foobar"
hello world!
::: generic-end
```

gets transformed into the following html
```
<div class="foo" id="foobar">
hello world!
</div>
```
This will allow the ability to define blocks with custom styling and attributes which is useful for targeted formatting and behaviour in html docs without having to resort to writing raw html.

The main use case I have in mind is taking advantage of some of bootstrap's dynamic features like collapsible sections.

In theory we could have done this with #3387 however docfx has disabled the custom containers extension because the custom TripleColon extension uses a similar syntax. Therefore this proposal would allow custom containers in docfx without conflict.

Let me know if I should proceed with creating a pull request for this. Also any feedback about the design is appreciated.

**Comment by yufeih** [comment]
Today we preserves your HTML tags in markdown, so you can directly write

```
<div class="foo" id="foobar">
hello world!
</div>
```

**Comment by cryxia** [comment]
Yup, I understand that. However you cannot use markdown syntax inside html. That's part of what I want to be able to do

**Comment by KalleOlaviNiemitalo** [comment]
Add a blank line after `<div class="foo" id="foobar">`. That will end the HTML block; see [CommonMark section 4.6 HTML blocks](https://spec.commonmark.org/0.29/#html-blocks), item 6. You may need a blank line after `</div>`, as well.

I don't remember using blank lines with `div` myself but they sure do the trick for Markdown within HTML `td`.

**Comment by superyyrrzz** [comment]
What about [section definition](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#section-definition)?

**Comment by cryxia** [comment]
A section definition works but it's kinda unwieldy - you have to add a > before every line.

In the end I just added a plugin to do some post processing. I'll close this issue out as I found a workaround.
