### ISSUE TITLE
docfx.exe should be signed

### ISSUE THREAD

**Issue by weshaggard** [dotnet/docfx#5610]
I've downloaded docfx.exe from both the nuget package, github release, and the chocloately package and the binary is not signed in any of them. That opens up security risk for us when we want to download and use your tool in our build pipelines because we cannot ensure it wasn't tampered with. Can we please get the exe signed?

**Comment by superyyrrzz** [comment]
AB#201338 AB#201339
Target date: 4/8

**Comment by superyyrrzz** [comment]
DocFX is signed since v2.53 https://github.com/dotnet/docfx/releases/tag/v2.53
