### ISSUE TITLE
Corporate AntiVirus is blocking docfx for "unauthorized encryption"

### ISSUE THREAD

**Issue by SimonSchulte** [dotnet/docfx#5611]
**Operation System**: 'Windows'

**DocFX Version Used**:  2.5

**Template used**: `default`

**Steps to Reproduce**:

1. Run docfx from Powershell
2. look at the html
3. change code commentary
4. Run docfx from Powershell again
5. Reapeat a few times

**Expected Behavior**:
No strike from the AntiVirus.
**Actual Behavior**:
Antivirus (Micro Trend Apex One) strikes. Due to "unauthorized encryption". 

The question is, what is docfx encrypting and may I be able to disable that? I have no way of doing something about the corporate anti virus :(

**Comment by KalleOlaviNiemitalo** [comment]
I searched for "crypto" in DocFX v2.5 source code. All matches were references to the System.Security.Cryptography namespace. There are a few MD5 hash computations in the application itself and SHA-1 in a test, but no encryption. I did not examine the libraries that DocFX uses, though.

Perhaps the antivirus vendor can fix the issue.

**Comment by pleonex** [comment]
It happened to us too. The problem is that the crappy AV (Trend Micro) that we have is detecting "overwritting an HTML file" as a malware encryption / ransomware -.-'

**Comment by yufeih** [comment]
It sounds like this isn't a docfx issue.
