### ISSUE TITLE
Extracting metadata from F# sln file.

### ISSUE THREAD

**Issue by appff** [dotnet/docfx#5648]
**Operation System**: MacOS

**DocFX Version Used**:  Latest

**Template used**: default

**Steps to Reproduce**:

1. configure docfx.json 
2. docfx metadata

[Important]: Honestly, I have already tried to extracting a fsproj file which is an isolated project directly, it didn't matter. However, my solution has various fs project that depend on each other. Therefore I tried to load the all of the fsproj files, DocFx couldn't refer the source code of other projects. Finally, I decided to use my solution file. But DocFx shows a warning below. 
Anyway, my question is that DocFx supports F# solution file or not.

**Expected Behavior**: Succeed to extract sub-project files (fsproj)

**Actual Behavior**: 
DocFX showed a warning message below.
[ExtractMetadata](/Volumes/a/About_recipe/documentation/docfx-2/docfx_project/src/mvb-recipe.sln)Workspace failed with: [Failure] Cannot open project '/Volumes/a/About_recipe/documentation/docfx-2/docfx_project/src/src/Core/Core.fsproj' because the file extension '.fsproj' is not associated with a language.

**Comment by yufeih** [comment]
Build docs from `fsproj` directly was not planned, to generate docs for fsharp project, produce an assembly and [build docs from DLLs](https://dotnet.github.io/docfx/docs/dotnet-api-docs.html#build-from-dll-csproj-or-source-code).
