### ISSUE TITLE
Docs for constants contain strange type/description table with empty description

### ISSUE THREAD

**Issue by melanchall** [dotnet/docfx#5653]
When docs generated for constants I get something like that:

![image](https://user-images.githubusercontent.com/26361185/77246106-10414180-6c35-11ea-97a8-41b756dcf3ce.png)

What purpose of the table below with empty description? Constant is fully described by its type and `<summary>` tag. Am I missing something?

If we look at MSDN, we'll see this:

![image](https://user-images.githubusercontent.com/26361185/77246164-98bfe200-6c35-11ea-884f-9c31c726cc5f.png)

Just **Field Value** with type and nothing else which is reasonable.

If there is no way to get rid of this table, can I specify some things to have non-empty **Description**? With no value in this cell it looks like I didn't specify something in the docs, but I have all required things.

**Comment by melanchall** [comment]
The same for properties:

![image](https://user-images.githubusercontent.com/26361185/77251415-4abfd400-6c5f-11ea-99c1-d02227affcc8.png)

**Comment by KalleOlaviNiemitalo** [comment]
It seems to be coming from [`<value>`](<https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/value> "<value> - C# programming guide | Microsoft Docs").

```C#
namespace ClassLibrary1
{
    public class Class1
    {
        /// <summary>
        ///  Everything.
        /// </summary>
        /// <value>
        ///  Perhaps this will show up?
        /// </value>
        public const int Answer = 42;
    }
}
```

![image](https://user-images.githubusercontent.com/46201428/77392090-db52fd00-6da2-11ea-9c4e-1e1fc4f7e987.png)

**Comment by melanchall** [comment]
From Microsoft docs:

> The `<value>` tag lets you describe the value that a property represents.

So this tag is for properties, not for fields and constants. Why docfx **requires** this tag to be presented on `const`? I can't imagine when `summary` and `value` are different for fields.

Seems like a bug.

**Comment by KalleOlaviNiemitalo** [comment]
I think DocFX generates the table from this: <https://github.com/dotnet/docfx/blob/ac8024bc50bd47d748ff99791a70e6f1ef6152d8/src/docfx.website.themes/default/partials/class.tmpl.partial#L90-L106>

A custom theme could do this differently. At docs.microsoft.com, the [IntPtr.Size](https://docs.microsoft.com/dotnet/api/system.intptr.size?view=netframework-4.8) topic shows both the type of the value and the description of the value, but not in a table; instead, the description is a paragraph below the type. The `mathew` template at [Available templates and themes](https://dotnet.github.io/docfx/templates-and-plugins/templates-dashboard.html) uses a similar layout: <https://github.com/MathewSachin/docfx-tmpl/blob/704814b8187aacf4dbd5e9d57ddc39aefbb3db8f/src/partials/class.tmpl.partial#L81-L91>

**Comment by melanchall** [comment]
@KalleOlaviNiemitalo `IntPtr.Size` is a property, it's not a field or constant. As I said in my previous comment, `<value>` tag is for properties only. There is no need use it for fields or constants since `<summary>` and `<value>` will contain the same content.

At now docfx **requires** presence of `<value>` tag on field. I suppose the proper way is to not generate table if there is no `<value>` tag on member, or duplicate content of `<summary>`. This behavior should be built-in rather than part of custom template.

Empty cell is bad especially if `<value>` is not required for fields or constants.

**Comment by KalleOlaviNiemitalo** [comment]
From [v2 strategy](https://github.com/dotnet/docfx/blob/dev/Roadmap.md#v2-strategy), it looks like the team won't fix this in DocFX v2 themselves but could accept a pull request.

**Comment by melanchall** [comment]
OK, I solved this problem by custom template with CSS that transforms those tables to type only.
