### ISSUE TITLE
Docfx and no-script

### ISSUE THREAD

**Issue by QFSW** [dotnet/docfx#5731]
After digging through, it's clear that docfx uses JS to draw the UI, which not only incurs delays for some parts of the UI (navbar, code styling) but also means the site will be broken completely when using a no js option.

Why is it like this for what should be a mostly simple static site and is there any way to circumvent this?

**Comment by KalleOlaviNiemitalo** [comment]
Try the "statictoc" template.

**Comment by QFSW** [comment]
statictoc seems like it fixes the navbar and toc to be static, as expected! The only drawbacks are some parts become less "pretty" than on default (no highlight of active navbar page, no x on search field etc). I wonder if theres a way to combine the best of both worlds, or even fallback on statictoc? To be honest, since the navbar can be statically loaded easily (as demonstrated by statictoc) I wonder why default chooses to do it with JS, that can cause worse UX?

**Comment by KalleOlaviNiemitalo** [comment]
I imagine "statictoc" might have slower incremental builds, as every HTML file needs to be rewritten if the TOC changes.

**Comment by QFSW** [comment]
> I imagine "statictoc" might have slower incremental builds, as every HTML file needs to be rewritten if the TOC changes.

I feel like slightly longer build times is more than worth it for better UX in the shipped product?

**Comment by KalleOlaviNiemitalo** [comment]
The table of contents at <https://docs.microsoft.com/en-us/windows/apps/desktop/> does not work without scripts, either. If Microsoft has decided that their own site can require scripts, I suppose it makes financial sense not to spend effort on script-free functionality for third-party sites. 🤔
