### ISSUE TITLE
Not able to run DocFX from source

### ISSUE THREAD

**Issue by DaviddH** [dotnet/docfx#5739]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Windows 10, build 1809
**DocFX Version Used**: 
2.51
**Template used**: (`default` or `statictoc` or contain custom template)
Default
**Steps to Reproduce**:

1. Download latest release from github
2. Build docfx and run in on the docfx-seed
3. Warning about no default template resource found, empty site generated

![image](https://user-images.githubusercontent.com/1622972/78654497-dfb00780-78c4-11ea-8b97-2dd30468d0c2.png)
![image](https://user-images.githubusercontent.com/1622972/78654645-1dad2b80-78c5-11ea-9ab1-57018368f74b.png)

This is on a completely clean copy, downloaded from github without any changes.  Build using Visual Studio 2019 16.4.5

**Expected Behavior**:
Site generated the same way as the docfc.console package from nuget
**Actual Behavior**:
Empty site generated because no default resource are found

**Comment by KalleOlaviNiemitalo** [comment]
> 2. Build docfx and run in on the docfx-seed

How did you build it? `build.ps1` does some NPM stuff, and skipping that does not prevent the C# part from being built but the result won't work.

**Comment by DaviddH** [comment]
I build the solution using Visual Studio since that was one of the options mentioned on the readme page.

After running the build using the build.ps1 script succesfully the error about resource missing is gone, but it looks like the resources aren't build correctly. The seed index page looks like this:

![image](https://user-images.githubusercontent.com/1622972/78869494-f7ae9500-7a44-11ea-916a-564cfd707605.png)

And when looking in the referenced CSS and JS files, I noticed that a lot of files are empty. 

The UpdateTemplate script throws the following error:

> [09:33:23] Error: File not found with singular glob: D:/xxx/docfx-2.51/src/docfx.website.themes/default/bower_components/bootstrap/dist/css/bootstrap.css (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (D:\xxx\docfx-2.51\src\docfx.website.themes\default\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (D:\xxx\docfx-2.51\src\docfx.website.themes\default\node_modules\glob\glob.js:197:8)
    at done (D:\xxx\docfx-2.51\src\docfx.website.themes\default\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (D:\xxx\docfx-2.51\src\docfx.website.themes\default\node_modules\glob\glob.js:688:12)
    at D:\xxx\docfx-2.51\src\docfx.website.themes\default\node_modules\glob\glob.js:676:10
    at Glob._stat2 (D:\xxx\docfx-2.51\src\docfx.website.themes\default\node_modules\glob\glob.js:772:12)
    at lstatcb_ (D:\xxx\docfx-2.51\src\docfx.website.themes\default\node_modules\glob\glob.js:764:12)

**Comment by KalleOlaviNiemitalo** [comment]
Following the steps in one of the azure-pipelines*.yml files might lead to a successful build. These eventually run `node_modules/gulp/bin/gulp.js` under NodeJS, and `tools/Deployment/gulpfile.js` runs `build.ps1`, but there are other steps before that.
