### ISSUE TITLE
>= 2.51.0 toc, menu and breadcrumbs not working

### ISSUE THREAD

**Issue by zkost** [dotnet/docfx#5756]
Os: `Windows` 
DocFx Ver: 2.51.0 
Template: default, custom
File based docs (not web server).

I'm running the docs as a simple file based website (not on a web server), I've been able to generate my docs and reference them locally without issue until 2.51.0. 

As of 2.51.0 the toc, breadcrumbs, and navbar menu items are not inserted into the html. Otherwise the docs look great.

Generating my docs produces no errors or warnings. 

I see other notes on here where it is suggested that should statictoc as the template. Fine, but it was working fine until the upgrade to 2.51.0. Did not see any references to any breaking changes in the for 2.51.0. 

Have tried to 
1. Reinstalled docfx, no difference.
2. Used vanilla (default) new setup, default template, new default docfx.json, no difference.

**Expected Behavior**:
For it to work as before, or guidance regarding breaking changes in upgrade to 2.51.0

**Actual Behavior**:
Just stopped producing toc, breadcrumbs, and navbar menu items. The yml documents are there and I can reference them directly from the browser but the menu's are not longer being built.

Thanks

**Comment by zkost** [comment]
Thank you superyyrrzz looking at this? Let me know if you need any additional information.

**Comment by superyyrrzz** [comment]
Yes, @v-pegao is investigating it.

My impression is that default template has never supported open HTML directly as you mentioned. I want to first confirm is this a regression. Could you provide the version of docfx that worked?

**Comment by zkost** [comment]
I installed version 2.51.0 via nuget. I just updated to 2.52.0 hoping that it was resolved but received the same results. Here is some more insight into my config. 

my ***ApiDocs.cproj*** file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  
   <PropertyGroup>
    <LogLevel>Warning</LogLevel>
  </PropertyGroup>
  
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
     <PlatformTarget>x64</PlatformTarget>
   </PropertyGroup>
  
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
     <PlatformTarget>x64</PlatformTarget>
   </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="docfx.console" Version="2.52.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

My ***docfx.json***
```
{
  "metadata": [
    {
      "src": [
        { "files": [ "**.csproj" ], "src": "D:\\Bishop\\My.API" }
      ],
      "dest": "api",
      "disableGitFeatures": false,
      "disableDefaultFilter": false
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "bapi/**"
        ]
      }
    ],
    "dest": "bapi",
    "globalMetadata": {
      "_appTitle": "blah API",
      "_appFooter": "2012-2020 Copyright, blah blah blah.",
      "_appLogoPath": "images/logo.png",
      "_appFaviconPath": "images/favicon.ico"
    },
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [ "default", "templates/bishop" ],
    "postProcessors": [],
    "markdownEngineName": "markdig",
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}
```

My custom template. Under bishop\partials I only have file ***head.tmpl.partial*** the rest of the template is driven from the default template as set in the ***docfx.json*** file (see above).
```
{{!Copyright (c) Oscar Vasquez. All rights reserved. Licensed under the MIT license. See LICENSE file in the project root for full license information.}}

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{{#title}}{{title}}{{/title}}{{^title}}{{>partials/title}}{{/title}} {{#_appTitle}}| {{_appTitle}} {{/_appTitle}}</title>
  <meta name="viewport" content="width=device-width">
  <meta name="title" content="{{#title}}{{title}}{{/title}}{{^title}}{{>partials/title}}{{/title}} {{#_appTitle}}| {{_appTitle}} {{/_appTitle}}">
  <meta name="generator" content="docfx {{_docfxVersion}}">
  {{#_description}}<meta name="description" content="{{_description}}">{{/_description}}
  <link rel="shortcut icon" href="{{_rel}}{{{_appFaviconPath}}}{{^_appFaviconPath}}favicon.ico{{/_appFaviconPath}}">
  <link rel="stylesheet" href="{{_rel}}styles/docfx.vendor.css">
  <link rel="stylesheet" href="{{_rel}}styles/docfx.css">
  <link rel="stylesheet" href="{{_rel}}styles/main.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
  <meta property="docfx:navrel" content="{{_navRel}}">
  <meta property="docfx:tocrel" content="{{_tocRel}}">
  {{#_noindex}}<meta name="searchOption" content="noindex">{{/_noindex}}
  {{#_enableSearch}}<meta property="docfx:rel" content="{{_rel}}">{{/_enableSearch}}
  {{#_enableNewTab}}<meta property="docfx:newtab" content="true">{{/_enableNewTab}}
</head>
```

**Comment by superyyrrzz** [comment]
Is there a version earlier than 2.51.0 that can work before? e.g. 2.50.0?

**Comment by zkost** [comment]
Yes, Version 2.48.0 most certainly did as did 2.48.1. I upgraded to 2.51.0 and it stopped working and as I mentioned earlier 2.52.0 is not working either.

**Comment by v-pegao** [comment]
@zkost We had a test on version 2.48.0 and 2.52.0 and didn't find behavior change. The issue is likely related to client environment. 

When testing, we find CORS policy can block the toc loading, if you can see **the error** in browser debug console , please follow **the steps** to setup chrome `--allow-file-access-from-files` and retry the html loading.

**Sample Error Message**: 
`Access to XMLHttpRequest at  'file:///D:/docfx_project/_site/articles/toc.html' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, https`

[**Steps to enable chrome `--allow-file-access-from-files` switch**](https://cmatskas.com/interacting-with-local-data-files-using-chrome/):
1. Close down your Chrome browser (make sure you close all instances if you have multiple windows open)
2. Go to Run and type the following command: chrome.exe --allow-file-access-from-files
3. Hit enter

cc @superyyrrzz

**Comment by zkost** [comment]
That is indeed is the problem! May I say that I feel like a total dumba$$ for not checking the obvious and wasting your time. Although I am using MS edge, I am getting this very error; I will figure out how to resolve with edge. Thank you very much for helping me see the tree in the forest!
