### ISSUE TITLE
Em dash not displayed in site after build

### ISSUE THREAD

**Issue by melanchall** [dotnet/docfx#5761]
If I use em dash (Alt + 0 1 5 0) in Markdown file, it's not displayed on site after build. Instead of dash I see question mark:

![image](https://user-images.githubusercontent.com/26361185/79076880-eb0c9400-7d05-11ea-9def-47fdec544159.png)

What's wrong with em dash and docfx?

**Comment by melanchall** [comment]
Ane movement on the issue? :)

**Comment by KalleOlaviNiemitalo** [comment]
Try saving the file as UTF-8.
