### ISSUE TITLE
Can't update from docfx to 2.52.0 due to missing fsharp nuget feed

### ISSUE THREAD

**Issue by crfrolik** [dotnet/docfx#5767]
**Operation System**: (`Windows` or `Linux` or `MacOS`)

Windows

**DocFX Version Used**: 

2.48.0

**Steps to Reproduce**:

1. Right click on doc project in Visual Studio 2019
2. Select "Manage NuGet Packages..."
3. Select docfx, and update to 2.52.0

**Actual Behavior**:

```
Restoring packages for C:\[...]\MyDocumentation.csproj...
  GET https://api.nuget.org/v3-flatcontainer/fsharp.compiler.service.msbuild.v12.0/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/fsharp.compiler.service.msbuild.v12.0/index.json 593ms
NU1101: Unable to find package FSharp.Compiler.Service.MSBuild.v12.0. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
Package restore failed. Rolling back package changes for 'MyDocumentation'.
Time Elapsed: 00:00:02.6587202
========== Finished ==========
```

**Comment by superyyrrzz** [comment]
You can try adding fsharp feed into nuget.config. See: https://github.com/dotnet/docfx/blob/fe608d90c5091c07edb43fcb9b3097efac73fe55/NuGet.config#L12

**Comment by crfrolik** [comment]
Thanks, that did fix it. Although it should be noted that I am not using F# at all, and the README didn't mention anything about it, so you'll likely have other users run into this as well.

**Comment by superyyrrzz** [comment]
@crfrolik Thank you for the suggestion! I am pinning this issue for more visibility.

**Comment by wccdmorgan** [comment]
My issue was referred to this one, but the proposed solution is not working. Any version of that URL returns a 404.
https://dotnet.myget.org/F/fsharp/api/v2/ (or v3)
