### ISSUE TITLE
Build docfx on OSX?

### ISSUE THREAD

**Issue by amirebrahimi** [dotnet/docfx#5782]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
MacOS

**DocFX Version Used**: 
Pulled latest from github

I'm mainly opening this issue as an inquiry as to whether it should be possible to build docfx on OSX. From what I can tell it seems no.

**Comment by amirebrahimi** [comment]
Okay, then it might be helpful to include that info in the readme.

**Comment by paulushub** [comment]
> Okay, then it might be helpful to include that info in the readme.

The move to .NET Core is currently happening in the repository.
