### ISSUE TITLE
DocFx Caching Old Content on Localhost

### ISSUE THREAD

**Issue by jeremiahjordanisaacson** [dotnet/docfx#5837]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Window
**DocFX Version Used**: 
2.51.0
**Template used**: (`default` or `statictoc` or contain custom template)
default
**Steps to Reproduce**:

1. Edit any page content.
2. Start the localhost server
3. Navigate to page that you made updates to. Notice sometimes the new updates don't appear.

**Expected Behavior**:
Updates should always appear after a save and localhost rebuild

**Actual Behavior**:
Looks like it's caching results from a previous localhost spin up. I don't want to have to clear my cache every time I work with DocFx. Is there any fix for this issue or a workaround? This is making debugging and quick edits overly difficult.

**Comment by superyyrrzz** [comment]
@jeremiahjordanisaacson Can refresh (F5) or force refresh (Ctrl+F5)help?

**Comment by icnocop** [comment]
I could not reproduce.

Pressing F5 in my browser displayed the new content without issues after a successful re-build.

Which `cache` are you clearing?

Steps I took:
1. Download [walkthrough3.zip](https://dotnet.github.io/docfx/tutorial/walkthrough/artifacts/walkthrough3.zip) and extract to `c:\walkthrough3`

2. Download [wkhtmltox-0.12.5-1.msvc2015-win64.exe](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox-0.12.5-1.msvc2015-win64.exe) and extract to `c:\wkhtmltox`

3. Copy `c:\wkhtmltox\bin\wkhtmltopdf.exe` to `c:\walkthrough3\wkhtmltopdf.exe`

4. Download [docfx.zip](https://github.com/dotnet/docfx/releases/download/v2.51/docfx.zip) and extract to `c:\docfx`

5. Open a command prompt and run the following commands:
```
cd C:\walkthrough3
c:\docfx\docfx.exe docfx.json --logLevel Verbose
```

6. Wait for build to succeed.

7. Open a new command prompt and run the following commands:
```
cd C:\walkthrough3
c:\docfx\docfx.exe serve
```
Result:
`Serving "C:\walkthrough3" on http://localhost:8080`

8. Navigate to `http://localhost:8080/_site` in a web browser and notice the text `This is the HOMEPAGE.`

9. Edit `C:\walkthrough3\index.md` and change the text `This is the HOMEPAGE.` to `This is the new HOMEPAGE.`

10. In the first command prompt run the following command:
`c:\docfx\docfx.exe docfx.json --logLevel Verbose`

11. Wait for build to succeed.

12. Press F5 in the web browser and notice the new text `This is the new HOMEPAGE.`

I tested in Firefox, Chrome, Internet Explorer, and Edge on Windows 10.

**Comment by jeremiahjordanisaacson** [comment]
Thank you @superyyrrzz for the suggestion and @icnocop for the detailed write-up and repo attempt. This is exactly (e.g. with our code) what I am doing with mixed results (e.g. it doesn't happen all the time, just sometimes for some unknown reason that I thought was a caching problem). That said, **Ctrl+Shift+F5** seems to help for anyone else experiencing this problem.
