### ISSUE TITLE
Use spoiler/details+summary tags for GitHub issue linking

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/docfx#5860]
I don't know where to put this but this is related to docs, so...

The current issue linking from docs.ms to github.com issues uses a format like this 

```md
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Enable tab completion - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**
```

It displays on every issue and it's mostly distracting from the actual comment on the issue. So, I propose we surround them with a spoiler / details+summary tags.

with details + summary the above format becomes like this...

```md
---
<details>
<summary>⚠<em>Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.<em></summary>

#### Document Details

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Enable tab completion - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

</details>
```

which previews like this...

---
<details>
<summary>⚠<em>Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.</em></summary>

#### Document Details

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Enable tab completion - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

</details>

**Comment by yufeih** [comment]
Thanks for the feedback. I've forwarded to the appropriate teams.

[AB#215012](https://dev.azure.com/ceapex/Engineering/_workitems/edit/215012)
