### ISSUE TITLE
[Question] Is there a planned date for the release of docfx v3 ?

### ISSUE THREAD

**Issue by TechWatching** [dotnet/docfx#5876]
I have looked at the roadmap of v3 but there are not expected or planned date for the release. Is it something known ?

In order to try and get started with docfx is it better to go v2 or wait for the release of  v3 ?

**Comment by WeihanLi** [comment]
I'm also expected for v3, any plan for v3 release?

**Comment by superyyrrzz** [comment]
We have plan here, but no exactly date yet. https://github.com/dotnet/docfx/blob/v3/docs/roadmap.md

**Comment by bharatgoenka** [comment]
Is it ok to use v3, or we need to wait for formal release?  We wish to integrate this in this month into our processes, if we can.

**Comment by superyyrrzz** [comment]
@bharatgoenka No, as it cannot produce HTML pages yet.

**Comment by Miki-84** [comment]
Hi @superyyrrzz, almost everythings seems done in the v3 roadmap, any update about when it will be ready?
Thansk for your greate work, i really liked v2 and i amb relly waiting for the v3 version!

**Comment by Jeavon** [comment]
@superyyrrzz Any update on the v3 release schedule, the roadmap is looking tantalising close to completion?

**Comment by superyyrrzz** [comment]
@yufeih @herohua

**Comment by dampee** [comment]
Very interested to hear what the timeline is.

**Comment by Miki-84** [comment]
Hi,
Is there any news about the v3 realese date?

Thanks for everything!

**Comment by Sotty75** [comment]
We are working with Docusaurus and waiting for DocFX v3 to be available to migrate, is there a planned date?

**Comment by yufeih** [comment]
Close as dup of #7050
