### ISSUE TITLE
Enable UseAdvancedExtensions on Markdig

### ISSUE THREAD

**Issue by lionelberton** [dotnet/docfx#5893]
Markdig is used as the default engine to render markdown but only the commonmark subset of features is enabled on markdig whereas there are extensions like math in latex, diagrams in mermaid, that can be uttely necessary to write a proper documentation.
Those extensions are enabled with **UseAdvancedExtensions** method on the pipeline creation.
It would be good to have it by default, or at least to have a documented way to enable it.
Since we can use docfx for our own documentation, we may not want to restrict ourselves to the too restrictive commommark subset.

**Comment by tibel** [comment]
Is think this is covered by #3387

**Comment by lionelberton** [comment]
yes exactly. 
Still no idea on when it will be available?
is someone working on it already?
