### ISSUE TITLE
[Bug] Json code highlight wrong

### ISSUE THREAD

**Issue by h82258652** [dotnet/docfx#5900]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 
v2.53.1

**Template used**: (`default` or `statictoc` or contain custom template)
statictoc

**Steps to Reproduce**:

The code like this:

<pre>
```JSON
{
    "propertyA": "justin",
    // See https://www.bing.com/
    "propertyB": "liu"
}
```
</pre>

**Expected Behavior**:
In my Visual Studio, the markdown preview is like this:
![Snipaste_2020-05-13_11-08-01](https://user-images.githubusercontent.com/5144550/81767083-1e5f6000-950a-11ea-878b-0ffe1fe7ead8.png)

**Actual Behavior**:
But actually:
![Snipaste_2020-05-13_11-10-03](https://user-images.githubusercontent.com/5144550/81767170-54044900-950a-11ea-8039-6d43f96ab829.png)

**Comment by superyyrrzz** [comment]
JSON does not support `//` comments. I believe it will render properly after removing it.

**Comment by h82258652** [comment]
@superyyrrzz 
Thanks for the response, it is my mistake.
