### ISSUE TITLE
inheritdoc should support built-in types

### ISSUE THREAD

**Issue by tdmowrer** [dotnet/docfx#5909]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
macOS

**DocFX Version Used**: 
2.51

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Add `<inheritdoc/>` to a method defined in a system interface, like `IEnumerable<T>.GetEnumerator` or `GetHashCode`.
2. Execute DocFX

**Expected Behavior**:
Documentation is generated.

**Actual Behavior**:
No documentation is generated.

This seems to be because `<inheritdoc/>` doesn't support system types. However, `<see cref={some system type}/>` _does_ work, so DocFX seems to be capable of this.

**Comment by DanielsCode** [comment]
Hi, 

we have the same problem. Are there any updates? 

Cheers,
Daniel

**Comment by KalleOlaviNiemitalo** [comment]
<https://xref.docs.microsoft.com/query?uid=System.Collections.Generic.IEnumerable`1.GetEnumerator> returns a `summary` property, but it does not return `returns`, `remarks`, etc. properties. So if `inheritdoc` should copy all of those, then it would have to get them from somewhere else.
