### ISSUE TITLE
'@' prefix is erroneously stripped from parameter names

### ISSUE THREAD

**Issue by Spongman** [dotnet/docfx#5917]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
windows

**DocFX Version Used**:
latest (please add instructions on where to find this)

**Template used**: (`default` or `statictoc` or contain custom template)
statictoc

**Steps to Reproduce**:

1. have a method `public void Foo(string @class) {}`
2. make docs
3. notics that the `@` has been removed resulting in an invalid declaration (`class` is a c# keyword)

**Expected Behavior**:

**don't** strip the `@` symbols

**Comment by yufeih** [comment]
Fixed in the latest release.
