### ISSUE TITLE
ExtractSearchIndex includes html comments in index.json keywords

### ISSUE THREAD

**Issue by marwie** [dotnet/docfx#5926]
**Operation System**: Windows

**DocFX Version Used**: docfx 2.52.0.0

**Template used**: default + custom

**Steps to Reproduce**:

1. download the docfx seed repo and 
2. export the default template and open "default/layout/master.tmpl"
3. add ``<!-- this is a comment on every page -->`` to line 41 (just above {{! body}}
4. build the site
5. open __site/index.json
6. note that ``<!-- this is a comment on every page -->`` has been added to the keywords for every element

**Expected Behavior**: html comments do not appear in search

**Actual Behavior**: html comments appear in search

**Comment by yufeih** [comment]
dup of #3262
