### ISSUE TITLE
Syntax highlighting for blazor/razor/cshtml

### ISSUE THREAD

**Issue by egil** [dotnet/docfx#5946]
It would be lovely if we could get support for cshtml/razor syntax highlighting.

**Operation System**: Windows

**DocFX Version Used**: docfx.console 2.50.0

**Template used**: default

**Comment by robdmoore** [comment]
If I add the following JavaScript to `main.js` then it seems to work (although the Razor syntax highlighting isn't /great/, it seems to apply styling in consistently - happy to provide examples). I'm unsure if it's just using an old version or the source is just not great):

```javascript
(function() {
    $(".lang-cshtml").addClass("cshtml").removeClass("lang-cshtml") // Patch up issue where cshtml hljs plugin doesn't work for .lang-cshtml
})();
```

I have no idea why the above works, but it does :P

**Comment by robdmoore** [comment]
OK, I've played around and removed the highlightjs that's included in the `docfx.vendor.js` file and added in highlightjs 10 and the `cshtml-razor` plugin and it all works (without my weird js above).

Would be great if docfx could be updated to the latest highlightjs so it's possible to use razor without having to change the vendor file :)

**Comment by egil** [comment]
@robdmoore I did the same, although there is bug in it, as far as I can see: https://github.com/highlightjs/highlightjs-cshtml-razor/issues/14

**Comment by romanresh** [comment]
The '@code' directive is supported in [highlightjs-cshtml-razor](https://www.npmjs.com/package/highlightjs-cshtml-razor) v2.0.0.

**Comment by yufeih** [comment]
highlight.js updated to latest version in https://github.com/dotnet/docfx/pull/8395
