### ISSUE TITLE
Github Action to deploy to Azure App Service

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/docfx#5959]
Hi, 

sorry if this has been asked before - is there a sample Github action to generate a DocFx site and deploy to an Azure Web App?

thanks

**Comment by JeremyCaney** [comment]
Really, this should just be a GitHub action to generate the HTML. 

There are well-established, existing actions for e.g., publishing to an Azure App Service—or any number of other cloud hosting providers. The missing step is a reputable GitHub action for the compilation process. 

That said, there are at least [some fledgling community efforts](https://github.com/marketplace/actions/docfx-action) to addressing this need.

**Comment by yufeih** [comment]
We likely won't ship a github action to produce HTML files, it'll be equivalent to install docfx then call docfx to build the project.
