### ISSUE TITLE
[Question] link from article to generated api?

### ISSUE THREAD

**Issue by DerAlpman** [dotnet/docfx#5994]
Hello,

I want to place a link in a MD-file that points to an automatically generated API file. Is there another way to achieve it instead of hard writing something like
"../../api/one.of.automatically.generated.files.html" in my markdown file?

Best regards,

Stefan

**Comment by KalleOlaviNiemitalo** [comment]
Yes, link to the UID that DocFX generates from the API, as described in [Links and Cross References](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#define-uid).

**Comment by DerAlpman** [comment]
Thank you.
