### ISSUE TITLE
How to install docfx 2.51 version on Mac

### ISSUE THREAD

**Issue by varunmankal** [dotnet/docfx#5995]
**Operation System**: (`MacOS`)

**Steps to Reproduce**:
How to install older versions of docfx on Mac, specifically 2.51 version ?

Does docfx works on Mac ? I have installed the latest version and looks like it is not working.

**Comment by varunmankal** [comment]
I was able to get the desired version of docfx running on Mac using mono. 

download the desired version and unzip docfx.zip from https://github.com/dotnet/docfx/releases, extract it to a local folder, and add it to PATH so you can run it anywhere.

To Run from the command line:
mono ~/Downloads/docfx/docfx.exe --version

**Comment by jaroslaw-weber** [comment]
Why this issue is closed? docfx is still uninstallable, and it only works with weird workaround
