### ISSUE TITLE
/// <inheritdoc /> Does not always display documentation 

### ISSUE THREAD

**Issue by Hamsterland** [dotnet/docfx#5996]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 
2.5.4

**Template used**: (`default` or `statictoc` or contain custom template)
Default

**Steps to Reproduce**:

1. Create an interface
2. Give the interface a method
3. Add xml documentation to the interface
4. Create a class that implements the interface
5. Add the `/// <inheritdoc />` tag to the implemented method

**Expected Behavior**:
The implemented documentation always shows 

~~**Actual Behavior**:~~
~~The implemented documentation does always show. There is no clear indication as to what triggers its showing on infrequent occasions.~~

~~https://i.imgur.com/PWMWnDo.png (In class)~~
~~https://i.imgur.com/8xzeXuG.png (In interface)~~

**Actual Behavior**
**First**
```cs
public interface IInterface {
	/// <summary>
	/// A method
	/// </summary>
	void MyMethod1();
	
	/// <summary>
	/// Another method
	/// </summary>
	void MyMethod2();
}
```
```cs
public class IClass : IInterface {
	/// <inheritdoc />
	void MyMethod1();
	
	/// <inheritdoc />
	void MyMethod2();
}
```
Implemented documentation does not show for **either methods**.

**Second**
```cs
public class IClass : IInterface {
	/// <inheritdoc cref="IInterface.MyMethod1"/>
	void MyMethod1();
	
	/// <inheritdoc />
	void MyMethod2();
}
```
Add explicit reference to interface method in **any** of the class methods. Implemented documentation for **both methods** show.

**Third**
Removing the explicit reference now fixes the issue. Documentation for class shows for all subsequent serves.

**Comment by sharwell** [comment]
📝 Note that for the first example, `IClass` does not need to explicitly include the `<inheritdoc/>` element. This element is implicitly included for methods in a class that implement an interface method or override a base class method.
