### ISSUE TITLE
Change Color of PDF Toc header

### ISSUE THREAD

**Issue by schnebi** [dotnet/docfx#6039]
**Operation System**: Windows

**DocFX Version Used**: 2.54

**Template used**: custom template
Hi
Is there anyway to change the color of the Toc Header in a pdf outcome.
I just find the given color code in the cache file.
So my question is, where is this generated and how can i affect the build of it.
Thanks

This turquoise color is what i want to change
![Toc Header](https://user-images.githubusercontent.com/65154326/83862681-92181580-a722-11ea-91bd-64fedcd77c02.PNG)

![cache file](https://user-images.githubusercontent.com/65154326/83862895-defbec00-a722-11ea-9cf5-01e6815ca2f7.PNG)
Thats the part of the cache where i found the color.

**Comment by superyyrrzz** [comment]
@schnebi You can [update this line](https://github.com/dotnet/docfx/blob/e1966fba438ef69020674517a26ab6eaa4be7785/src/docfx.website.themes/pdf.default/toc.html.tmpl#L43) by [customizing the template](https://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html).

**Comment by schnebi** [comment]
Thanks
was looking for that.
