### ISSUE TITLE
bookmark-not-found error should not be reported

### ISSUE THREAD

**Issue by easonyq** [dotnet/docfx#6067]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Windows
**DocFX Version Used**: 
docfx: 3.0.0-beta1.40+227267ebc5
**Template used**: (`default` or `statictoc` or contain custom template)
default
**Steps to Reproduce**:

1. Write a md file (let's named it after 'a.md') with content `'## Part1'`
2. Write another md file (let's named it after 'b.md') with content `'[Link](./a.md#Part1)'`
3. Error occurs when building:
`bookmark-not-found ./b.md(7,1): Cannot find bookmark '#Part1' in 'a.md', did you mean '#part1'?`

**Expected Behavior**:
This error should not be reported
**Actual Behavior**:
This error is reported

**Comment by superyyrrzz** [comment]
bookmark is case-sensitive

**Comment by easonyq** [comment]
Title in md file is usually in Pascal format (upper case for first letter). So in order to consist with it, bookmark in link should also be Pascal format.

I think bookmark-not-found error should not raise in this case.

If you mean user are suggested to write `'## Part1'` and `'[Link](./a.md#part1)'`, that will make md files difficult to read and match, in my opinion.

**Comment by yufeih** [comment]
URLs are all lowercased for SEO purposes. The title anchor generator not only lower cased the characters but also concat words by `-`.

Close this as designed.
