### ISSUE TITLE
Unable to resolve dependency 'FSharp.Compiler.Service.MSBuild.v12.0'

### ISSUE THREAD

**Issue by wccdmorgan** [dotnet/docfx#6088]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows 10

**DocFX Version Used**: 
2.55.0

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1. Open NuGet Package Manager, find docfx package
2. Click install on a .NET Framework 4.7.2 project

**Expected Behavior**: 
Installs the package including all dependencies

**Actual Behavior**: 
Errors out with:

> Unable to resolve dependency 'FSharp.Compiler.Service.MSBuild.v12.0'. Source(s) used: 'nuget.org', 'docfx temp', 'Microsoft Visual Studio Offline Packages'.

where 'docfx temp' is: https://www.myget.org/F/docfx/api/v3/index.json (found in a similar thread)

**Comment by superyyrrzz** [comment]
See #5767
