### ISSUE TITLE
pdf doc has no style

### ISSUE THREAD

**Issue by RaffaeleAprea** [dotnet/docfx#6110]
Hi, I followed the steps described at [tutorial 3 of *Walkthrough Topics*](https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_generate_pdf.html)
and I tried to use *default*, *statictoc* and *darkfx* templates found [here](https://dotnet.github.io/docfx/templates-and-plugins/templates-dashboard.html)
but the pdf file has no style.

I made a repo of the docfx project referred to this issue -> [here](https://github.com/RaffaeleAprea/docfx_htmlToPdf)
There are a simple dll and its xml file,both inside "src" folder.

*Issue infos*:
**Operating System**:           Windows

**DocFX Version Used**:         2.55

**wkhtmltopdf Version Used**:   0.12.6

**Prerequisites**:
- docfx.exe and wkhtmltopdf.exe installed. (Both tested: docfx builds currectly online documentation and wkhtmltopdf converts properly a web page into a pdf file).
- check "pdf.default" and "statitoc" are in the template list (I run *docfx template list* to check).
- put [darkfx template files](https://github.com/steffen-wilke/darkfx/tree/master/darkfx) inside a "templates" folder in the root.

**Steps**
run "docfx pdf" 

**Expected Behavior**:
pdf file has style.

**Actual Behavior**:
- If I use "template":"pdf.default" pdf has no style.(I expected it to be similar to online doc "default" style)
- If I use "template":"statictoc" pdf is not built + this warning : "Warning:\[PDF\]No TOC file is included, no PDF file will be generated."
- If I use "template": \["pdf.default","templates/darkfx"\] pdf has no style

![gitpdf](https://user-images.githubusercontent.com/51984100/85077800-6f2a3e80-b1c3-11ea-83d6-4c1a105299f7.PNG)

What am I missing?

Note: If I built the online documentation site instead it works with darkfx. (see "_docfx.json" inside the repo)

**Comment by Trits** [comment]
I have the same issue, no style like in the picture and images are not rendered in the PDF. With older DocFX version the PDF did have style (pdf.default). I have installed DocFX and wkhtmltopdf with Chocolatey.
Operating System: Windows
DocFX Version Used: 2.55
wkhtmltopdf Version Used: 0.12.6

**Comment by Trits** [comment]
This issue may be caused by wkhtmltopdf 0.12.6, which has BREAKING CHANGE: block local filesystem access by default (https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4536).

**Comment by RaffaeleAprea** [comment]
You are right, I have tried again using instead versions 0.12.5 and 0.12.4 and I confirm pdf get expected styles (default and darkfx).

**Comment by Blake-Eryx** [comment]
Add this to your JSON config file:

"wkhtmltopdf": {
      "additionalArguments": "--enable-local-file-access"
    }

This will fix it with the latest wkhtmlpdf.  Refer to #6072 , which documents this new requirement.

**Comment by RaffaeleAprea** [comment]
I have added it inside the "pdf" dict and now it works, Thanks @Blake-Eryx !

I consider this closed, but first I'm just curious to know about one last thing: what's the actual 
reason of the error regarding statictoc? (see point 2 of *Actual Behavior*).

**Comment by Blake-Eryx** [comment]
You will just want to use "pdf.default" for PDF files.  The other themes are designed for HTML output.  For example, statictoc is for when you want HTML help that is not being served by a webservice (e.g., you just want it on a website or network share where you don't have a localhost service running your help as its own website).

If you want something like dark theme, the easiest way is to make your a custom theme for PDF that goes on top of pdf.default.  It could be a simple CSS file that you model after what the regular dark theme does.  Of course, if you have a dark-themed PDF, that would be lot of ink when you print it :)

**Comment by RaffaeleAprea** [comment]
Ok, I understand, thank you very much.
I was just struggling to get a pdf output using any style, whatever they look like :)
