### ISSUE TITLE
v3: No metadata generated

### ISSUE THREAD

**Issue by dotMorten** [dotnet/docfx#6137]
I pulled the v3 branch, and tried to build my documentation with that version. However the metadata step appears to be completely stepped, and there is no longer a metadata-only command parameter either.
How do I generate metadata with v3?

According to [the roadmap](https://github.com/dotnet/docfx/blob/v3/docs/roadmap.md) this should already be possible if I read that right.

**Operating System**: Windows

**DocFX Version Used**: v3 (v3 branch)

**Template used**: `default`

**Steps to Reproduce**:

1. Clone https://github.com/dotMorten/NmeaParser, branch: `docfx3`
2. run 'docs/builddocs.cmd'

**Expected Behavior**:
Metadata gets generated

**Actual Behavior**:
Only the existing markdown/yaml files are used to generate the doc site.

**Comment by yufeih** [comment]
The .NET reference documentation pipeline in v3 will be built on top of [mdoc](https://www.mono-project.com/docs/tools+libraries/tools/monodocer/). The basic building blocks are there but we haven't provide a simple command to produce a reference API out of a .NET project yet.

**Comment by dotMorten** [comment]
So is this possible now?
