### ISSUE TITLE
View Source link refers git repo but with file:// parts

### ISSUE THREAD

**Issue by devel0** [dotnet/docfx#6181]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

windows

**DocFX Version Used**: 

2.55.0.0

**Template used**: (`default` or `statictoc` or contain custom template)

custom: https://github.com/devel0/netcore-util/blob/b421e3408040fa9008f3999e571a3fbb5a16ecd7/docfx/docfx.json

**Steps to Reproduce**:

- git clone https://github.com/devel0/netcore-util
- cd netcore-util
- git checkout b421e3408040fa9008f3999e571a3fbb5a16ecd7
- dotnet build
- cd docfx
- .\build.bat
- docfx --serve

**Expected Behavior**:

View Source link in [this page](https://devel0.github.io/netcore-util/api/SearchAThing.UtilExt.html) should results as

```
https://github.com/devel0/netcore-util/blob/master/netcore-util/String.cs/#L20
```

because I patched manually with this [script](https://github.com/devel0/netcore-util/blob/b421e3408040fa9008f3999e571a3fbb5a16ecd7/fixdocpath.sh)

**Actual Behavior**:

instead docfx generates following

```
https://github.com/devel0/netcore-util/blob/master/file:///Z:/netcore-util/netcore-util/String.cs/#L20
```

**Comment by JeremyCaney** [comment]
This issue remains open, but looking at [the page you linked to](https://devel0.github.io/netcore-util/api/SearchAThing.UtilExt.html), the "View Source" link now correctly points to:
```
https://github.com/devel0/netcore-util/blob/master/netcore-util/String.cs/#L20
```
I take it you were able to solve this issue?

**Comment by devel0** [comment]
I think the issue can be closed, because at current version of docfx I used 2.56.6.0 problem disappeared, more actually I run docfx directly from linux, btw I tried again from windows and it works correctly.

( the page I was linked is of github pages that reports only current head of master so the problem can't exhibit any more, but if someone need to reproduce that I edited my first post in *Steps to reproduce* specifying the commit version )
