### ISSUE TITLE
Special characters in code blocks in triple-slash comments appear escaped as HTML-Entities

### ISSUE THREAD

**Issue by sttz** [dotnet/docfx#6192]
**Operating System**: macOS

**DocFX Version Used**: 2.56.0.0

**Template used**: default

**Steps to Reproduce**:

1. Create a C# project with following code in the XML comments:
```cs
/// <remarks>
/// ```cs
/// var string = "Hello World!";
/// MyFunction&lt;float&gt;();
/// ```
/// </remarks>
```
2. Use docfx to create documentation and observe how the code is rendered:
<img width="436" alt="Screenshot 2020-07-04 at 18 58 33" src="https://user-images.githubusercontent.com/173249/86517476-7e4af680-be29-11ea-9fea-2c167bf84c4b.png">

**Expected Behavior**:
The code should be rendered without special characters encoded as HTML-Entities (`&quot;` and `&lt;`).

**Actual Behavior**:
The code contains HTML-Entities. If the `<` and `>` in the comment are not encoded, `docfx metadata` will generate an error, but `"` is used without warning. `"` could be escaped as well but that leads to the same result.

I tried removing the escaping in [TripleSlashCommentModel](https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Parsers/TripleSlashCommentModel.cs#L859)'s `XmlWriterWithGtDecoded`, passing the `text` string to `WriteRaw` as-is, which produces the expected result:
<img width="435" alt="Screenshot 2020-07-04 at 19 06 12" src="https://user-images.githubusercontent.com/173249/86517485-8acf4f00-be29-11ea-902a-7a42fa33d86b.png">

Special characters inside regular text in triple-slash comments are displayed fine.

**Comment by KalleOlaviNiemitalo** [comment]
If you use [\<code\>](<https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/code> "<code> - C# programming guide | Microsoft Docs") instead, then it renders OK:

```C#
/// <remarks>
/// <code>
/// var string = "Hello World!";
/// MyFunction&lt;float&gt;();
/// </code>
/// </remarks>
```

Or with a CDATA section:

```C#
/// <remarks>
/// <code><![CDATA[
/// var string = "Hello World!";
/// MyFunction<float>();
/// ]]></code>
/// </remarks>
```
