### ISSUE TITLE
“Improve this Doc” on a page in DocFx output does not go to the corresponding Markdown file in the source repo

### ISSUE THREAD

**Issue by cedar-ave** [dotnet/docfx#6270]
Based on this code in docfx.json, when a user clicks "Improve this Doc" on an HTML page output by DocFx, I would expect the user to be taken to the corresponding Markdown file in the source repo:

```
    "globalMetadata": {
      "_gitContribute": {
        "repo": "https://{company}.visualstudio.com/DefaultCollection/{project}/_git/{repo}",
        "branch": "master"
      },
      "_gitUrlPattern": "aso"
     <rest of JSON block>
    }
```

Right now, in my setup, when "Improve this Doc" is clicked on any page, the user is taken to the root of the repo.

The repo is private to my company, if that matters. I am using the latest version of DocFx.

**Comment by superyyrrzz** [comment]
This may be because of mis-configuration: "_gitUrlPattern": "~~a~~**v**so"

**Comment by cedar-ave** [comment]
Ah that was dumb of me. Thank you. Changing that to `vso` did not make it work successfully, though. I am doing something wrong in addition.

**Comment by cedar-ave** [comment]
I had modified my affix.tmpl.partial incorrectly. To anyone with this issue, that may be one thing to check. Thanks.
