### ISSUE TITLE
References failing for some but not all dependencies

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#628]
I've recently upgraded docfx to version 2.3.0.0, and also updated my project to use dotnet cli. It's possible the two are linked for this bug...

I'm now finding that `cref` attributes for dependencies are *mostly* failing with a warning:

> Warning: Invalid cref value "!:[...]" found in triple-slash-comments for [...] defined in [...]

This doesn't happen for absolutely all dependencies though.

Sample, all in a directory `DocfxBug`

docfx.json:

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [ "project.json" ]
        }
      ],
      "dest": "obj/api"
    }
  ],
  "build": {
    "content": [ ],
    "dest": "_site"
  }
}
```

project.json:

```json
{
  "dependencies": {
    "NodaTime": "1.3.2",
    "Newtonsoft.Json": "9.0.1"
  },
  
  "buildOptions": {
    "xmlDoc": true
  },

  "frameworks": {
    "net45": { }
  }
}
```

Program.cs:

```csharp
using NodaTime;
using Newtonsoft.Json;

namespace DocfxBug
{
    /// <summary />
    public class Program
    {
        /// <summary>
        /// <see cref="JsonConverter" />
        /// <see cref="LocalDate" />
        /// </summary>
        public static void Main()
        {            
        }
    }
}
```

Running `dotnet restore` and `dotnet build` works fine, and the resulting XML file shows that `LocalDate` has been resolved to `NodaTime.LocalDate`. Running `docfx metadata -f` gives a warning, but *only* for `LocalDate`:

```text
Info: Config file docfx.json found, start generating metadata...
Warning: Invalid cref value "!:LocalDate" found in triple-slash-comments for Main defined in c:/Users/skeet/Test/Projects/docfxbug/DocfxBug/Program.cs Line 12, ignored.
Info: Completed executing in 1092.3539 milliseconds.
```

Why would the Json.NET reference work, but not the Noda Time one?

**Comment by chenkennt** [comment]
@jskeet are you using DNX version of DocFX to build project.json? I guess there will be some issues as DNX is going to be retired. @qinezh please help take a look.

**Comment by jskeet** [comment]
Yes, I am. If there's a dotnet-cli-based version available, I'd be very happy to use that instead... docfx is now the last piece of our project that requires DNX to be installed.

It's not entirely clear whether the release version used in step 2 of http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html would handle dotnet cli projects, which is definitely a requirement. Working under Linux would be a bonus...

**Comment by qinezh** [comment]
@jskeet Can you try use this [CLI version of DocFX](https://github.com/dotnet/docfx/releases/tag/v2.1.0-cli-alpha)?

**Comment by jskeet** [comment]
@qinezh: Yup, that works for me. (Of course, if something was broken between 2.1 and 2.3, we wouldn't know that that was the problem, but it's a good start :)

**Comment by qinezh** [comment]
Great to hear it and we will update the CLI version of DocFX soon.

**Comment by chenkennt** [comment]
We'll keep the CLI version up-to-date. And our next step is to officially retire DNX version and replace it with CLI version in the next month or two. Will keep you updated.

**Comment by qinezh** [comment]
The [new release of DocFX](https://github.com/dotnet/docfx/releases/tag/v2.5) supports .NET Core project currently, please have a try.
