### ISSUE TITLE
When using a solution filters are not applied

### ISSUE THREAD

**Issue by RedX2501** [dotnet/docfx#6290]
**Operating System**: `Windows`

**DocFX Version Used**: 2.56.1

**Template used**: `statictoc`

**Steps to Reproduce**:

Use a solution instead of csproj or files:

```
"metadata": [
    {
      "src": [
        {
          "files": [
            "MyProj.sln"
          ],
          "src": "..\\..\\..",
          "exclude": ["**/obj/**", "**/bin/**", "**/Tests/**"]
        }
      ],
      "dest": "api",
      "filter": "filterConfig.yml"
    }
  ],
```

In the `filterConfig.yml` try to filter everything:

```
ApiRules:
- exclude:
    uidRegex: .*
    type: Type
```

**Expected Behavior**:

I don't see anything but articles in the generated code.
My goal is not to filter every API in the end but this make seeing that it is not working the easiest.

**Actual Behavior**:
Every class, enum and so on is still visible.

**Comment by RedX2501** [comment]
The filter is "ApiRules" and not "apiRules"...

There is no warning about this. Why is the casing important and if it is why is there no warning about mistyped identifiers....

**Comment by adamgit** [comment]
Well in current version the filter works fine as "apiRules" (as written in the official docs - did the case-sensitivity get fixed?).

BUT.

There are so many bugs in the parsing of this file that it's almost hopeless. It silently crashes in almost every non-trivial situation - adding a single include/exclude frequently breaks it. Character-by-character analysis in a hex editor - and git-diffs - shows there is literally nothing wrong with the file - but docFX's parsing is just very very very bad.

**Comment by paulushub** [comment]
> There are so many bugs in the parsing of this file that it's almost hopeless.

@adamgit Lets start with specific cases. Can you post a sample project to reproduce your observations?

**Comment by adamgit** [comment]
If I spot a pattern, sure. Right now literally adding or removing a single
item breaks the file unpredictably. The apparent lack of any error handling
(when it suddenly ignores all excludes the implication is that internally
it's hit an error - which someone has handled silently) makes it feel ...
not worth debugging in detail right now.

My current workaround is to:
a) try random adds and removes of letters until the file starts being read
correctly again. Revert git commits and apply similar changes until it
works.
b) write scripts that post-process docfx and implement the same
functionality but more reliably, with error-handling.

**Comment by adamgit** [comment]
NB: I commented initially because this is one of the very few hits on
google for the filtering API - and the solution at end of thread is (no
longer?) correct.

**Comment by paulushub** [comment]
@adamgit I agree without a coordinate UI for editing, it can be frustrating, and there is too much to study just for a documentation.
However, after carefully reading the manual, I never had any real problem with the filter. My only frustration is lack of plugin support, so the only method of filtering available is the one provided by the DocFX team, which is limited and the team claims it is by design.
