### ISSUE TITLE
[Question] How can DocFX read the xml files from mdoc?

### ISSUE THREAD

**Issue by SMTStuck** [dotnet/docfx#6335]
I read on the [docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/announcing-unified-dotnet-experience-on-docs#built-with-open-source-in-mind) site that Microsoft used DocFX and [mdoc ](https://github.com/mono/api-doc-tools) to generate the docs. I find the HTML generation from mdoc ugly at best without a lot of template work. Can DocFX read the these xml files to generate the HTML?

**Comment by superyyrrzz** [comment]
Currently, docfx uses [ECMA2Yaml](https://github.com/docascode/ECMA2Yaml) to generate XML into YAML files that docfx recognizes.

Docfx v3 can build from these XML files out of box.

**Comment by SMTStuck** [comment]
Thank you.
