### ISSUE TITLE
Wants to Integrate docfx with my c++ code

### ISSUE THREAD

**Issue by trivedirince3** [dotnet/docfx#6336]
I want to Integrate docfx with my c++ code, what workflow I can use to achieve this

**Comment by KalleOlaviNiemitalo** [comment]
DocFX v2 has no built-in support for C++. [Introduction to Multiple Languages Support](https://dotnet.github.io/docfx/tutorial/universalreference/intro_multiple_langs_support.html) says you'd first have to generate metadata. That step could perhaps use the [GENERATE_XML](https://www.doxygen.nl/manual/config.html#cfg_generate_xml) setting of Doxygen, or the C++ parser of [Clang](https://clang.llvm.org/).

**Comment by trivedirince3** [comment]
**@KalleOlaviNiemitalo** Thanks for you reply, with respect to your response, I have some doubts if you can help me with below questions : 

1. What is DFM?
Because in that link its mention it support C family how can I integrate with it for testing purpose to see the behavior.
[https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a#tag-name-representation-in-code-snippet-source-file](url)

2. The API metadata supported by docfx it should be of yml format. **if there’s way to map XML to docfx from doxygen and Clang ?**

**Comment by KalleOlaviNiemitalo** [comment]
DFM is DocFX Flavored Markdown.

I presume you'd have to write a program that reads the XML, transforms it, and writes the YAML.

**Comment by trivedirince3** [comment]
@KalleOlaviNiemitalo **How Can I Integrate DFM with C++ code ?**

**Comment by Shikha22061992** [comment]
@KalleOlaviNiemitalo  Thanks for your reply,i am having some doubts if you can help me with below questions :

Can you please provide us more clarity on DocFX Flavoured Markdown,How can we able to include this in our source code or in docfx that able to generate the documentation 
Is it part of API generation that able to extract from Metadata from Source code 
If you can share us any sample or any reference for it 

I presume you'd have to write a program that reads the XML, transforms it, and writes the YAML. :- 
-> Please share us any sample if you have for the same or reference

**Comment by KalleOlaviNiemitalo** [comment]
Alternatives for where you'd write your C++ documentation:
- Doxygen-style comments in C++ source files: Doxygen should support these OK but it might be difficult for your program to convert them to DFM.
- DFM-style comments in C++ source files: Might cause difficulties with Doxygen trying to parse syntax that it does not support. A program using Clang C++ parser APIs could be a better solution if you want this.
- Separate files in your own format: Your program would read the documentation from these files and copy it to the YAML, e.g. as [ItemViewModel.Summary](https://github.com/dotnet/docfx/blob/b6b22ad21e22be7c581f8e8fec871f417a7d1a57/src/Microsoft.DocAsCode.DataContracts.UniversalReference/ItemViewModel.cs#L153).
- [Overwrite files](<https://dotnet.github.io/docfx/tutorial/intro_overwrite_files.html> "Overwrite Files | DocFX website"): I don't know whether DocFX supports these with UniversalReference.
- [Markdown fragments](https://github.com/dotnet/docfx/blob/373d517f9e03da2417573cf2656b78bf2a544ef1/docs/designs/markdown-fragments.md): I don't know whether DocFX supports these with UniversalReference.

I do not have any sample code for such a converter program.

**Comment by Shikha22061992** [comment]
@KalleOlaviNiemitalo  Thanks for your response

- Can you share us some reference for DFM-style comment,I had checked in the link but could n't able to relate or link with my code ?

**Comment by KalleOlaviNiemitalo** [comment]
I meant, if you are going to write documentation as comments in C++ source files, then what are those comments going to look like?

* Doxygen style
  ```C++
  /// \brief Creates a window.
  /// \param[in] width The height of the window, in millimetres.
  /// \param[in] height The height of the window, in millimetres.
  /// \param[in] paneMaterial The type of glass in the window panes.
  void CreateWindow(int width, int height, const Material &paneMaterial);
  ```
  This has the advantage that you can process the same documentation with Doxygen as well, and I think Visual Studio supports the syntax in Intellisense. However, I don't know how Doxygen will format this in its XML output and how difficult it would be to translate that XML to something that DocFX can read.
* C# XML documentation comment style
  ```C++
  /// <summary>Creates a window.</summary>
  /// <param name="width">The height of the window, in millimetres.</param>
  /// <param name="height">The height of the window, in millimetres.</param>
  /// <param name="paneMaterial">The type of glass in the window panes.</param>
  void CreateWindow(int width, int height, const Material &paneMaterial);
  ```
  The C++/CLI compiler in Microsoft Visual Studio supports this syntax but does not let you refer to types and members that have not been declared yet, so it becomes very inconvenient if your types have circular dependencies. I don't know how Doxygen reacts to this syntax, especially if you also have Markdown in it.

Actually, Microsoft already has something for integrating DocFX with C language declarations. Compare [PO_FX_PERF_STATE structure](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_po_fx_perf_state) to [ns-wdm-_po_fx_perf_state.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/c1d5017cfaffd34bd97236436aa5e1f57b26d728/wdk-ddi-src/content/wdm/ns-wdm-_po_fx_perf_state.md). It is using specially formatted Markdown headings like `### -param WaitReason [in]` and apparently merging them with metadata parsed from header files, as the code snippet in the "Syntax" section appears on the rendered page but does not exist in the Markdown file. I assume Microsoft uses a closed-source DocFX plugin (["much more plugins"](https://github.com/dotnet/docfx/issues/4250#issuecomment-479936230)) for this merge.

**Comment by jo3w4rd** [comment]
I just happened upon this now-archived repo for this here: https://github.com/docascode/code2yaml, which seems to have been created by Microsoft at some point.

**Comment by yufeih** [comment]
> I just happened upon this now-archived repo for this here: https://github.com/docascode/code2yaml, which seems to have been created by Microsoft at some point.

That one was for Java and have been abandoned in favor of a new close sourced converter.

**Comment by yufeih** [comment]
Docfx does not natively support C++, but provides an [extension mechanism to support additional languages](https://dotnet.github.io/docfx/docs/additional-languages.html).
