### ISSUE TITLE
disable TOC - How do I disable TOC for selective pages?

### ISSUE THREAD

**Issue by mjangid** [dotnet/docfx#6337]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

**DocFX Version Used**:  Latest

**Template used**: (`default`)

**Expected Behavior**:
Page should display without TOC 

**Actual Behavior**:
TOC section is visible

**Comment by KalleOlaviNiemitalo** [comment]
For DocFX v2, see <https://github.com/dotnet/docfx/issues/5545>.

For DocFX v3, I don't know.
