### ISSUE TITLE
The file index.md doesn't contain a bookmark named 'Feedback'.

### ISSUE THREAD

**Issue by patware** [dotnet/docfx#6338]
**Operating System**: `Windows`

**DocFX Version Used**: docfx 2.56.2.0

**Template used**: `default`

**Steps to Reproduce**:

1. new folder
2. docfx init
3. edit index.md
  - add link with bookmark
  - add section
4. docfx build

``` markdown
  ---
  uid: index.md
  ---
  # This is the ##HOMEPAGE##
  
  Refer to [Markdown](http://daringfireball.net/projects/markdown/) for how to write markdown files.
  
  ## Quick Start Notes
  
  1. Add images to the *images* folder if the file is referencing an image.
  1. Check [](xref:index.md#Feedback)
  
  ## Feedback
  
  This section is the feedback.  Can you link it?
```

**Expected Behavior**:

No errors, no warnings, docfx generates link correctly with the bookmark's text.

**Actual Behavior**:
```shell
[20-07-30 06:10:50.417]Info:6 plug-in(s) loaded.
[20-07-30 06:10:50.465]Info:No files are found with glob pattern images/**, excluding <none>, under directory "E:\dev\test\doc\docfx_project"
[20-07-30 06:10:50.484]Info:Markdown engine is markdig
[20-07-30 06:10:50.637]Info:[BuildCore.Build Document]Max parallelism is 8.
[20-07-30 06:10:51.234]Info:[BuildCore.Build Document.CompilePhaseHandlerWithIncremental.ConceptualDocumentProcessor]Building 1 file(s) in ConceptualDocumentProcessor(BuildConceptualDocument=>CountWord=>ValidateConceptualDocumentMetadata)...
[20-07-30 06:10:51.239]Info:[BuildCore.Build Document.CompilePhaseHandlerWithIncremental.TocDocumentProcessor]Building 2 file(s) in TocDocumentProcessor(BuildTocDocument)...
[20-07-30 06:10:51.835]Info:[BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply Templates]Applying templates to 3 model(s)...
[20-07-30 06:10:51.987]Info:[BuildCore.Build Document]XRef map exported.
[20-07-30 06:10:52.060]Warning:[Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark](index.md#L11)Invalid link: ''<a href="#Feedback">This is the ##HOMEPAGE##</a>'. The file index.md doesn't contain a bookmark named 'Feedback'.
[20-07-30 06:10:52.096]Info:[Postprocess]Manifest file saved to manifest.json.
[20-07-30 06:10:52.129]Info:Completed building documents in 1700.8753 milliseconds.
[20-07-30 06:10:52.132]Info:Completed in 1822.4738 milliseconds
```

**Comment by KalleOlaviNiemitalo** [comment]
I wonder if this is deliberate for localization purposes. If a bookmark is automatically generated from the heading text, which is localized, then it will vary by language and you cannot link to it without knowing the language.

**Comment by KalleOlaviNiemitalo** [comment]
Or maybe it's just `feedback` vs. `Feedback`.

**Comment by patware** [comment]
Agreed and understood.  I tried with text and without text.  

Am I assuming correctly in thinking that the target anchor name is the the text following the Hashtags+space ?  Is there any other way to create an anchor?

Pat

**Comment by KalleOlaviNiemitalo** [comment]
To create an anchor for a heading, use this syntax:

```Markdown
## <a name="anchor"></a>Heading
```

In DocFX v2, [HeadingIdRewriter](https://github.com/dotnet/docfx/blob/56250e19a7fa546abb7c76d5ae4041c528bc4c2b/src/Microsoft.DocAsCode.MarkdigEngine.Extensions/HeadingId/HeadingIdRewriter.cs) will translate that to `<h2 id="anchor">Heading</h2>`, and the "In This Article" list will link to `#anchor`. This would not work if you instead placed the `</a>` closing tag at the end of the heading, or if you used apostrophes instead of double quotation marks.

HeadingIdRewriter supports `<a id="…">` too, but Microsoft seems to be using `<a name="…">`, e.g. in [binding-model.md](https://github.com/MicrosoftDocs/win32.zh-cn/blob/fe58161b7840a85b23c6d3c591b56c7c59fc0996/desktop-src/direct3d12/binding-model.md).

It might be good to document this syntax in [DocFX Flavored Markdown](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html) and mention it in [Links and Cross References](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html) as well.

**Comment by patware** [comment]
HAA !  Two things.

## Short answer.

1. DocFx generated heading anchor ids naming convention
1. Generated vs custom anchors

## Answer.

Please add the following to your documentation.

> When generating the html, docfx will convert every headings (##) into appropriate ```<h2><a href="{headinganchor}">{Heading Text}</a></h2>```.  (or h3, h4, etc.)
> 
> Example:
> 
> MarkDown:
> ```## Some text to show```
> becomes
> Generated HTML:
> ```<h2 id="some-text-to-show"><a href="#some-text-to-show">Some text to show<a></h2>```
> 
> You would then reference that anchor using ```[Something](xref:uidofyourpage#some-text-to-show)```
> 
> Optionally, you can override/specify a custom anchor id of the heading by using an ```### </a id="custom"> Heading text``` syntax.
> 
> Example: 
> 
> MarkDown:
> ```## <a id="custom-anchor"></a>Some text to show```
> becomes
> Generated HTML
> ```<h2 id="custom-anchor"><a href="#custom-anchor">Some text to show<a></h2>```
> 
> and the link becomes ```[Some place](xref:mypageuniqueid#custom-anchor)```

Also, I propose a twist to the compiler:  During the type processing of links:

- anchor found: do nothing
- anchor not found: 
  - check if there's a typo in the specified anchor: lowercase, convert spaces to dashes, etc and recheck.
    - if found, add a warning: anchor #x y z not found, did you mean #x-y-z
    - if not found, (and once per page), list the page's anchors and how the user could reference them, with the full ```[](xref:pageuid#anchor-code)``` syntax


## Long answer.

I just found out how DocFx generates the anchor ids, and it makes sense now (dumb of me for not looking at the html/code behind).

- lower case
- spaces are converted to dash(-)

Where I failed was the case sensitivity.  

Important: **The xref is case sensitive.**

BAD: xref:pageuid#Something
vs
GOOD: xref:pageuid#something


When in doubt, have docfx build the doc, browse to the generated html and look at the generated heading code.

MarkDown:
```## Feedback```
gets generated to
```<h2 id="feedback"><a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="#feedback" style="font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 1em; line-height: inherit; font-family: anchorjs-icons; position: absolute; margin-left: -1em; padding-right: 0.5em;"></a>Feedback</h2>```

Note the id and href

**Comment by yufeih** [comment]
It seems the issue was fixed by lowercase the anchor names.
