### ISSUE TITLE
Optimize display of parameter with default enum flags value

### ISSUE THREAD

**Issue by mikernet** [dotnet/docfx#6345]
**Operating System**: Windows

**DocFX Version Used**: 2.56.2

**Template used**: N/A

If there is a single enum flags value that captures a default enum parameter value then that should be used instead of spitting out all the individual flags that match. You can see how it is doing that here: 

http://www.singulink.com/Docs/Singulink.IO.FileSystem/api/Singulink.IO.DirectoryPath.html#Singulink_IO_DirectoryPath_Parse_System_ReadOnlySpan_System_Char__Singulink_IO_PathFormat_Singulink_IO_PathOptions_

Instead of having this:
```c#
public static IDirectoryPath Parse(ReadOnlySpan<char> path, PathOptions options = PathOptions.NoReservedDeviceNames | PathOptions.NoLeadingSpaces | PathOptions.NoTrailingSpaces | PathOptions.NoTrailingDots | PathOptions.NoUnfriendlyNames)
```

It should have:
```c#
public static IDirectoryPath Parse(ReadOnlySpan<char> path, PathOptions options = PathOptions.NoUnfriendlyNames)
```

**Comment by KalleOlaviNiemitalo** [comment]
Also described in <https://github.com/dotnet/docfx/issues/5694>.
