### ISSUE TITLE
[v3] Allow wbr element in HTML sanitization

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docfx#6346]
**Operating System**: Any

**DocFX Version Used**: 3.0.0-beta1-0246-g8b9773b7f0

**Template used**: Any

In DocFX v3, [sanitize-html.md](<https://github.com/dotnet/docfx/blob/8b9773b7f028aa1966c468de2bf6f9a2997eaa36/docs/designs/sanitize-html.md> "docfx/sanitize-html.md at 8b9773b7f028aa1966c468de2bf6f9a2997eaa36 · dotnet/docfx") and [HtmlUtility.cs](<https://github.com/dotnet/docfx/blob/8b9773b7f028aa1966c468de2bf6f9a2997eaa36/src/docfx/lib/HtmlUtility.cs> "docfx/HtmlUtility.cs at 8b9773b7f028aa1966c468de2bf6f9a2997eaa36 · dotnet/docfx") do not allow the [`<wbr>`](<https://developer.mozilla.org/docs/Web/HTML/Element/wbr> "<wbr> - HTML: HyperText Markup Language | MDN") element. Please consider allowing it. `<wbr>` was not discussed in <https://github.com/dotnet/docfx/pull/5580>.

`<wbr>` would be useful in some tables, e.g. if I want to display **Action\<Action\<object>, object>** but allow a line break after the first **\<** sign so that the Web browser can make that column narrower and another column wider.

A zero-width space `&#x200B;` would do the same thing visually but it causes a syntax error if someone then copies it from the documentation to source code.

**Comment by yufeih** [comment]
Makes sense. Thank you for the suggestion.
