### ISSUE TITLE
Configure indentation on external <code>

### ISSUE THREAD

**Issue by JuanZamudioGBM** [dotnet/docfx#6440]
**Operating System**: Windows
**DocFX Version Used**:  2.56.2.0

**Template used**: `default`

**Steps to Reproduce**:
In my classes with the examples I have something like this

```
namespace MyNameSpace
{
    public static class MyClass
    {
        public static void MyMethod()
        {
            #region MyRegion
            // code
            #endregion MyRegion
        }
    }
}
```

**Expected Behavior**:
In the examples there is 12 spaces of indentation in the code

**Actual Behavior**:
Some setting o configuration to avoid or reduce the indentation

**Comment by KalleOlaviNiemitalo** [comment]
[Code Snippet](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#code-snippet) mentions a `dedent` parameter for that but claims that the indentation will be trimmed by default. For `"markdownEngineName": "markdig"`, it seems to be implemented in [HtmlCodeSnippetRenderer.cs](https://github.com/dotnet/docfx/blob/56250e19a7fa546abb7c76d5ae4041c528bc4c2b/src/Microsoft.DocAsCode.MarkdigEngine.Extensions/CodeSnippet/HtmlCodeSnippetRenderer.cs).

Might your code snippet include a line that contains only spaces or tabs; more than zero, but fewer than in the indentation of the other lines?

**Comment by JuanZamudioGBM** [comment]
@KalleOlaviNiemitalo 

Thanks for the response, I forgot to mention a particularly important fact, this happens generating the PDF, the site has the spaces removed.

about the indentation, I have configured VS to use spaces, every tab is 4 spaces, so the class declaration has 4 spaces of indentation, the method has 8 spaces of indentation and everything inside the method has 12 spaces of indentation.

Do you know why only the PDF does not remove the indentation? Do I have to configure something in the docfx.json file?


Thanks for your time

**Comment by KalleOlaviNiemitalo** [comment]
@JuanZamudioGBM, how do you configure `markdownEngineName` in the `pdf` section of `docfx.json`? Because `"markdownEngineName": "dfm"` [is still the default](https://github.com/dotnet/docfx/blob/56250e19a7fa546abb7c76d5ae4041c528bc4c2b/src/Microsoft.DocAsCode.Build.Engine/DocumentBuildParameters.cs#L54) and the implementation in [DfmCodeExtractor.cs](https://github.com/dotnet/docfx/blob/56250e19a7fa546abb7c76d5ae4041c528bc4c2b/src/Microsoft.DocAsCode.Dfm/CodeRenderer/DfmCodeExtractor.cs) is quite different from the one in HtmlCodeSnippetRenderer.cs..

Also, how do you refer to the code snippet in Markdown?

**Comment by JuanZamudioGBM** [comment]
I didn't have a markdownEngineName configured in the pdf section, only in build, I added `"markdownEngineName": "markdig"` but it made no difference.

Sorry, I don't understand what you mean by `refer to the code snippet in markdown`, I use this to add the examples to my documentation:

```
/// <example>
/// <code source="..\..\..\Examples\MyClass.cs" region="MyRegion" language="c#" />
/// </example>
public static class MyCode
{
    // code
}
```

This is the [docfx.json](https://github.com/JuanZamudioGBM/DocFX/blob/master/docfx.json) file I use with the following command:
`docfx.exe "C:\repos\project\src\Documentation\docfx.json" -o ""`

Thanks

**Comment by KalleOlaviNiemitalo** [comment]
Oh, I assumed you were using `[!code-<language>[<name>](<codepath><queryoption><queryoptionvalue> "<title>")]` syntax in Markdown files, but you are instead using the `code` element in triple-slash comments.

**Comment by KalleOlaviNiemitalo** [comment]
Tried with DocFX 2.56.2:

1. `docfx init` and accept all defaults.
1. Add `docfx_project\src\CodeSnippetTest.sln`.
1. Add `docfx_project\src\CodeSnippetTest\CodeSnippetTest.csproj`:
   ```XML
   <Project Sdk="Microsoft.NET.Sdk">

     <PropertyGroup>
       <TargetFramework>netstandard2.0</TargetFramework>
     </PropertyGroup>

     <ItemGroup>
       <Compile Remove="MyClass.cs" />
     </ItemGroup>

   </Project>
   ```
1. Add `docfx_project\src\CodeSnippetTest\MyCode.cs`:
   ```C#
   namespace CodeSnippetTest
   {
       /// <example>
       ///  <code source="MyClass.cs" region="MyRegion" language="c#" />
       /// </example>
       public static class MyCode
       {
       }
   }
   ```
1. Add `docfx_project\src\CodeSnippetTest\MyClass.cs`:
   ```C#
   namespace CodeSnippetTest
   {
       class MyClass
       {
           MyClass()
           {
               #region MyRegion
               System.Console.WriteLine("WINERY");
               System.Console.WriteLine("WITTERY");
               System.Console.WriteLine("STOPPERY");
               #endregion
           }
       }
   }
   ```
1. `docfx metadata docfx_project\docfx.json`
1. `docfx build --serve docfx_project\docfx.json`
1. Open `http://localhost:8080/api/CodeSnippetTest.MyCode.html` in a Web browser.

The example in the Web browser has 12 spaces of indentation for WINERY and 7 spaces for each of WITTERY and STOPPERY. That seems pretty inconsistent. Anyway, DocFX did not remove the indentation even though I built HTML rather than PDF.

The `example` string in `docfx_project\api\CodeSnippetTest.MyCode.yml` has the same number of spaces as the Web browser displayed. So the inconsistency happens already during `docfx metadata`.

**Comment by KalleOlaviNiemitalo** [comment]
Oooh, if I indent the `code` element more:

```C#
    /// <example>
    ///                       <code source="MyClass.cs" region="MyRegion" language="c#" />
    /// </example>
```

then it removes more spaces from the lines after the first one:

```yaml
  example:
  - "\n<pre><code class=\"lang-c#\" source=\"MyClass.cs\" region=\"MyRegion\">            System.Console.WriteLine(&quot;WINERY&quot;);\nSystem.Console.WriteLine(&quot;WITTERY&quot;);\nSystem.Console.WriteLine(&quot;STOPPERY&quot;);</code></pre>\n"
```

That must be a bug; the indentation of the `code` element should not affect how many spaces are removed from the code snippet that was read from a different file. I guess it happens in `TripleSlashCommentModel.GetXmlValue`: <https://github.com/dotnet/docfx/blob/56250e19a7fa546abb7c76d5ae4041c528bc4c2b/src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Parsers/TripleSlashCommentModel.cs#L726-L739>

Perhaps `TripleSlashCommentModel.ResolveCodeSource` could add an attribute or annotation to the `XElement`, and `TripleSlashCommentModel.GetXmlValue` could then detect that and change how it removes the indentation.

All this does not explain why the behavior would be different when building PDF, though.

**Comment by JuanZamudioGBM** [comment]
Wow, that was deep.

About the PDF the lines inside #region appear to have the same indentation, the only difference is that I extract the metadata without using the solution (To avoid generating the documentation for the test project)
docfx metadata "C:\repos\project\src\1.csproj" ""C:\repos\project\src\2.csproj" -o "C:\repos\project\Documentation\api"

Thanks a lot for your time and insight.

**Comment by priomi1** [comment]
I can reproduce this issue. If I insert 2 tabs inside the triple-slash comments the example is left justified with no additional spaces.

        /// <example>          
        ///         <code source="../Hella.PDT.Http.UnitTest/CodeSamplesTest.cs" region="Step_Define"></code>
        ///         <code source="../Hella.PDT.Http.UnitTest/CodeSamplesTest.cs" region="Step_CreateHttps"></code>        
        /// </example>

**Comment by yufeih** [comment]
Leading spaces in documentation comments code snippets are automatically trimmed now.

**Comment by rapmue** [comment]
unlucky me, in version 2.73 of docfx the indentation occurs again:

![image](https://github.com/dotnet/docfx/assets/3046949/dd65d14c-c734-4a42-b675-2f64411a4dde)

![image](https://github.com/dotnet/docfx/assets/3046949/d0443598-2978-468f-9c0d-f8346fad435b)

inclusion was done with

```
/// <summary>
/// Interface for a program processor.
/// </summary>
/// <example><code source="../../../SDK.Examples/CustomProcessorExample.cs" region="SDK_CustomProcessor" /></example>
```
