### ISSUE TITLE
docfx won't serve on port 8080 with regular account, but anything else yes.

### ISSUE THREAD

**Issue by patware** [dotnet/docfx#6471]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 
docfx 2.56.2.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Command prompt with regular account
2. docfx build --serve

**Expected Behavior**:
Compiles and serves under http://localhost:8080 without issues

**Actual Behavior**:
Error:Error serving "E:\doc\_site" on http://localhost:8080, check if the port is already being in use.

I tried:
| Port | Command Prompt | Expected | Actual |
| --- | --- | --- | --- |
| 8080 | Regular | Pass | **Fail** |
| 8080 | Admin | Pass | Pass |
| 8081 | Regular | Pass | Pass |
| 8081 | Admin | Pass | Pass |

I checked, nothing is running on that port:
```shell
   netstat -aon | findstr 8080
```
found nothing

I can run a node server.js on 8080 with regular account, without a problem.
```shell
  E:\foo\> node server.js
  Server running at http://127.0.0.1:8080/
```
And when node runs, the web browser displays correctly, and netstat returns a value as expected.

I can run a dotnet core web on 8080
```shell
  E:\fooweb>dotnet run .
   info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:8081
   info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:8080
```
And when dotnet runs, the web browser displays correctly, and netstat returns a value as expected.

Finally, I couldn't find anything in pertinent in Windows Firewall.  

I'm running out of ideas.  Any clue ?

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps [netsh http show urlacl](https://docs.microsoft.com/windows/win32/http/show-urlacl) shows an ACL that limits port 8080 to Administrators only. That would affect Microsoft.Owin.Host.HttpListener used by DocFX v2, but would not affect HTTP servers that create a socket instead of using the Windows-specific HTTP Server API.

**Comment by patware** [comment]
OMG, right on.  Thank you.
