### ISSUE TITLE
Parameter Suggestions

### ISSUE THREAD

**Issue by michaelherndon** [dotnet/docfx#649]
### Parameter Suggestions
- Allow the forward slash (/) along with the hyphen (-) for command line args. 
- Add the -? in addition to the -h parameter for help.
- Add the --version or -v parameter for version information.
### Functional impact

Increases command line usability and discoverability.

**Comment by yufeih** [comment]
The command line in v3 follows [POSIX Convention](https://github.com/dotnet/corefxlab/blob/97a9012f25f7c5609383a5ff6e392119b46150d7/archived_projects/src/System.CommandLine/README.md#syntax)

`--version` is supported.
