### ISSUE TITLE
Problems with accented characters in index.json 

### ISSUE THREAD

**Issue by reinaldoarrosi** [dotnet/docfx#650]
I'm having trouble using full-text search (ExtractSearchIndex post-processor) when my markdown files contains accented characters.

For example:

/articles/aplicacao.md
`#Aplicação e módulos
Uma aplicação é um conjunto de módulos integrados.`

generates this index.json file
`{
  "toc.html": {
    "href": "toc.html",
    "title": "",
    "keywords": ""
  },
  "articles/aplicacao.html": {
    "href": "articles/aplicacao.html",
    "title": "Aplicação e módulos",
    "keywords": "AplicaÃ§Ã£o e mÃ³dulos Uma aplicaÃ§Ã£o Ã© um conjunto de mÃ³dulos integrados."
  }
}`

The .html output file (_site/articles/aplicacao.html) is generated correctly.

It seems to be there is a problem with index.json file encoding.

**Comment by evil-shrike** [comment]
Indexing definitely has problems with encoding.
It's unclear in what encoding index.json is. I have a source file which is in UTF-8 encoding and contains Russian letters:
```
	/// <summary>
	/// Типы шрифтов
	/// </summary>
	public enum FontType
	{
		WOFF,
		EOT,
		TTF, // он же OTF
		SVG
	}
```
In index.json I have:
```
  "api-server/Croc.XFW3.Web.Bootloader.FontType.html": {
    "href": "api-server/Croc.XFW3.Web.Bootloader.FontType.html",
    "title": "Enum FontType | API .Net Server | WebClient",
    "keywords": "Enum FontType Р СћР С‘Р С—РЎвЂ№ РЎв‚¬РЎР‚Р С‘РЎвЂћРЎвЂљР С•Р Р† Namespace :...skipped"
  },
```
it's not utf8, not ansi 1251, I have no idea what it is. 
Obviously in search results I can see the same gibberish.
