### ISSUE TITLE
Getting started as a contributor

### ISSUE THREAD

**Issue by GeeWee** [dotnet/docfx#6516]
Hello everyone. 

I realize this is a bit of a weird issue. I'd like to start help contributing to Docfx (particularly I'm interested in XPlatform support for v3)

However, I haven't been able to find any documents about the testing strategy, or a good way to start contributing to v3.
Is there any quick notes, codebase introduction or anything like that?

It's a little overwhelming to get started(even though I have previously been a maintainer on other large projects, such as [ts-jest](https://github.com/kulshekhar/ts-jest)), particularly because it's hard to tell what the general test strategy is, and what the featureset of v3 actually is.

If you'd be interested in getting some contributions, I'd love it if you could help me along somehow. A quick screencast that introduces some of the broad lines in the codebase or something like that would be awesome.

**Comment by yufeih** [comment]
The xplat part of v3 is baked in from the start using .NET Core and as you can see we test all v3 PRs on Windows, Linux and Mac.

![image](https://user-images.githubusercontent.com/511355/93430828-d6a47700-f8f5-11ea-9786-6dfbf9e0288f.png)

The codebase is in _v3_ branch of this repository which only needs .NET Core SDK to build and test. The actual feature set already implemented in v3 can be found in [these YAML specs](https://github.com/dotnet/docfx/tree/v3/docs/specs), we don't currently have a more end user facing documentation.

A good starting point of contribution (currently a WIP) is the default static site template, with its own repository [here](https://github.com/docascode/template). There are many issues tagged as [Area-Template](https://github.com/dotnet/docfx/issues?q=is%3Aopen+is%3Aissue+label%3AArea-Template) to start improving on.

Thank you indeed for offering the help,  and please bare with my late response.
