### ISSUE TITLE
Remove serve command with dependent assemblies

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/docfx#652]
There're so many ways to host static site currently. I don't see much sense to add one more. But this functionality adds a bunch of assemblies to distro. It's 23Mb already now.

**Comment by chenkennt** [comment]
Actually the hosting part doesn't take much space. Most assemblies in DocFX are used by Roslyn.

**Comment by evil-shrike** [comment]
not much, but these ones are obviously for hosting:
Microsoft.Owin.dll
Microsoft.Owin.FileSystems.dll
Microsoft.Owin.Host.HttpListener.dll
Microsoft.Owin.Hosting.dll
Microsoft.Owin.StaticFiles.dll
=330Kb

**Comment by superyyrrzz** [comment]
It's really small compared with Rosyln's 13.6MB...

Microsoft.CodeAnalysis.dll
Microsoft.CodeAnalysis.CSharp.dll
Microsoft.CodeAnalysis.CSharp.Workspaces.dll
Microsoft.CodeAnalysis.VisualBasic.dll
Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll
Microsoft.CodeAnalysis.Workspaces.dll
Microsoft.CodeAnalysis.Workspaces.Desktop.dll
