### ISSUE TITLE
Change the Default icon for the ToC Items.

### ISSUE THREAD

**Issue by Souradeep2304** [dotnet/docfx#6524]
**Operating System**: `Windows` 

**DocFX Version Used**: 2.56.1.0

**Template used**: `default`

I was finding a way to change the default icon that shows up by the side of the toc items which is a "+" sign and which becomes a "-" sign once the list item is being expanded. I want it to be a right arrow which rotates into a down arrow while expanding the toc. I tried to modify the docfx.css file where this thing is mentioned like this (using glyphicon-menu-right): 
```

.toc .nav > li.active > .expand-stub::before,
.toc .nav > li.in > .expand-stub::before,
.toc .nav > li.in.active > .expand-stub::before,
.toc .nav > li.filtered > .expand-stub::before  {
    content: "\e258";
    transition: transform .1s ease-in-out;
    transform: rotate(0deg);
}

.toc .nav > li > .expand-stub::before,
.toc .nav > li.active > .expand-stub::before  {
    content: "\e258";
}
```

But the icons dont show up in the docfx site. What should I do regarding the same?

**Comment by superyyrrzz** [comment]
How do you update the template? Generally, you can follow the [document](https://dotnet.github.io/docfx/tutorial/walkthrough/advanced_walkthrough.html) to:
1. `docfx export default`
2. update the exported template
3. pass the template with `-t _exported_templates/default`

**Comment by Souradeep2304** [comment]
I exported the default template and took the docfx.css file, did some modifications inside it like I mentioned in the original post, put it in another folder named custom and passing it in the docfx.json file as:

```
 "template": [
        "default",
        "custom"
      ],
```

essentially, I am overriding the default template with my modifications.

**Comment by superyyrrzz** [comment]
@Souradeep2304

There may be 2 issues here:
1. The CSS you changed is not picked up by the site.
2. The CSS you changed does not work for your purpose.

It seems what you do is correct, so it does not like the first issue. If your CSS is used by the site, can you make sure it changed the right CSS?

**Comment by Souradeep2304** [comment]
I did a check on the issue that if the modified docfx.css file is being recognized or not. I did some other small changes also and they are popping up in the docfx site, so that is not the case. When I put the changes I mentioned in the original post, the buttons appear like this :
![image](https://user-images.githubusercontent.com/36326807/92554604-5cd01600-f283-11ea-9b36-2da43bee002f.png)
 
I guess I am doing something wrong in the CSS changes that I am doing for the same then.

**Comment by superyyrrzz** [comment]
Sorry I am not expert on this. @jdanyow may help as his team owns MS Docs site UI.

**Comment by Souradeep2304** [comment]
I was able to solve the same and make it look like I wanted to using :
```
.toc .nav > li.active > .expand-stub::before,
.toc .nav > li.in > .expand-stub::before,
.toc .nav > li.in.active > .expand-stub::before,
.toc .nav > li.filtered > .expand-stub::before  {
    display: inline-block;
    transition: transform .1s ease-in-out;
    transform: rotate(90deg);
}

.toc .nav > li > .expand-stub::before,
.toc .nav > li.active > .expand-stub::before  {
    font-family: "Glyphicons Halflings";
    font-size: 10px;
    content: "\e258";
    display: inline-block;
    transition: transform .1s ease-in-out;
    transform: rotate(0deg);
}

```
