### ISSUE TITLE
Fails to generate documentation for 'Microsoft.NET.Sdk.WindowsDesktop' project

### ISSUE THREAD

**Issue by PTKu** [dotnet/docfx#6590]
Hi, I have come across the problem bellow. I am Quite new to docfx, this might be a configuration/environment/not_supported problem.

Duplicate of #4699 ?

**Operating System**: Windows

**DocFX Version Used**: 2.56.2

**Template used**: `statictoc`

**Steps to Reproduce**:

1. Create WPF netcoreapp3.1 project (Sdk=Microsoft.NET.Sdk.WindowsDesktop project)
2. Try create documentation form '**.csproj' file

**Expected Behavior**:
Would expect the build to pass and generate documentation.

**Actual Behavior**:

Following failure occurs
[Failure] Msbuild failed when processing the file 'x.csproj' with message: The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found. 

Thanks

**Comment by Overlong** [comment]
I'm observing the same behavior in Windows Forms projects targeting .NET Core 3.0 and 3.1.

Windows Forms projects targeting .NET Framework 4.7.2 work fine though.

**Comment by agent00jackson** [comment]
Having the same issue here

**Comment by hoolie** [comment]
Same for me

**Comment by hoolie** [comment]
I solved it on my CI machine by updating the VS BuildTools.

**Comment by yufeih** [comment]
Fixed in the latest version.
