### ISSUE TITLE
Renders Only First Exception 

### ISSUE THREAD

**Issue by d-vs** [dotnet/docfx#6619]
**Operating System**:  `Windows`

**DocFX Version Used**:  2.56.1.0

**Template used**:  `default`

**Steps to Reproduce**:

1. Produce XML documentation file, where a member has more than one &lt;exception&gt;
2. Generate docs with docfx based on the XML documentation file

**Expected Behavior**:
All exceptions are rendered with the member documentation

**Actual Behavior**:
Only renders the first exception in the XML documentation

**Comment by KalleOlaviNiemitalo** [comment]
Can't reproduce with DocFX 2.56.0 or 2.56.2. Tested both pointing docfx.json to the \*.csproj file and pointing docfx.json to the \*.dll file. In each of the four cases, I got all three exceptions described in HTML.

src/src.csproj:

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
```

src/Class1.cs:

```C#
using System;

namespace src
{
    public abstract class Class1
    {
        /// <exception cref="ArgumentException">Not possible.</exception>
        /// <exception cref="ArgumentException">How about that!</exception>
        /// <exception cref="InvalidOperationException">Yeah, right.</exception>
        protected abstract void Fun();
    }
}
```

docfx.json:

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [
            "src/bin/Debug/netstandard2.0/*.dll"
          ]
        }
      ],
      "dest": "api",
      "disableGitFeatures": false,
      "disableDefaultFilter": false
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [
      "default"
    ],
    "postProcessors": [],
    "markdownEngineName": "markdig",
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}
```

**Comment by d-vs** [comment]
@KalleOlaviNiemitalo thanks for the repro and apologies for the late reply. It seems that the behaviour changes depending on the src/files. If I do as you suggest, using the .dll as the source, then all exceptions are indeed output. 

But if I point it at all *.cs files in a project, then it seems only the first exception is the output.

**Comment by KalleOlaviNiemitalo** [comment]
I had also tested "pointing docfx.json to the *.csproj file" and that had worked OK. Do you mean you list the *.cs files directly and not the *.csproj?

**Comment by d-vs** [comment]
Yeah, I was using **.cs, as my source files. However, *.csproj seems to be the way to go and I can see all exceptions rendered now.

Just fyi there does seem to be more discrepancies between the various sources. If I use .dll, for example, I get this additional field output for an enum, but this is another issue.

![image](https://user-images.githubusercontent.com/21166782/116851369-25372500-abea-11eb-933d-b99913e6dd35.png)
