### ISSUE TITLE
Support for custom variables in markdown

### ISSUE THREAD

**Issue by awakecoding** [dotnet/docfx#6626]
Maybe this is an obvious one, but I couldn't figure it out: how does one use custom variables in markdown, such that the custom variable is replaced by its value at generation time? The closest answer I could find was a combination of Jekyll + liquid templating (https://jekyllrb.com/docs/liquid/), but I am looking for a solution that works with DocFX.

At a bare minimum, I would like to define custom variables for product names, such that if the name changes, it becomes much easier to update the docs. For instance:

"MyProductName" = "My Product Name"

Where "MyProductName" would be used in markdown. Now if I change the actual name to "My New Product Name" the markdown would still use the "MyProductName" variable. I suppose the easiest way would be to pass additional json files with the custom variable definitions and values, but I have no idea how to get them replaced at generation time.

Any hint on how to do this? Thanks!

**Comment by yufeih** [comment]
Put your product name into a separate file and use [`include`](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#file-inclusion) to reference that content. This is used in some of the <https://docs.microsoft.com> products, e.g. https://github.com/MicrosoftDocs/dynamics-365-customer-engagement/search?q=include

**Comment by awakecoding** [comment]
Thanks for the quick response. I knew about 'include' but I thought it was suitable for larger files, even though technically nothing prevents you from including a file containing a single product name as a "variable". I'm sure others will be searching for this, could there be a mention somewhere in the docs that this is the current way to do custom variables? Even when you read about 'include', it doesn't strike you as the appropriate method for doing custom variables.

One comment about possible improvements: wouldn't it be possible to do something like the xref, but for variables instead of link references? Defining uids + using xref:uid works well, something similar with defining 'xvar' but for variables instead would be extremely powerful and much easier to use that full file includes for a single variable.

**Comment by VaclavElias** [comment]
Is this still the only way how to pass a variable to markdown file, through ```[!INCLUDE[something](../includes/my-variable.md)]```?
