### ISSUE TITLE
_site folder seems to retain outdated content

### ISSUE THREAD

**Issue by billhenn** [dotnet/docfx#6640]
Hello, I'm new to DocFx (using v2 at the moment) and have seen scenarios where there is leftover outdated content in the _site folder.

The two cases I observed are:

1) There is a "_site/articles/intro.html" file generated from an original build, even though since then I have deleted "articles/intro.md" and rebuilt.

2) There are "_site/api/DocFxLibrary.Class1.html" and "_site/api/DocFxLibrary.html" files generated from an original build where I had added a DocFxLibrary class library with a Class1 class as a test, but have since deleted that class library and rebuilt.

In both cases, those outdated _site files in there cluttering things up.  Is there anything in the build process that will remove files from _site that are no longer used?

**Comment by superyyrrzz** [comment]
This may be related to incremental build that they are still contained in some cache files, but ideally, this should not happen as the cache will be deactivated after the original file removed. To work around this, you can try adding `-f` parameter to enforce full build.

**Comment by billhenn** [comment]
@superyyrrzz - I tried using the `-f` parameter but that didn't seem to make any difference.  Both outdated context scenarios I observed above are still there after doing the build.
