### ISSUE TITLE
Version 3 and Azure DevOps repositories

### ISSUE THREAD

**Issue by FSharpCSharp** [dotnet/docfx#6666]
We would like to maintain and manage our documentation with the soon to be released version 3 against Azure DevOps. This is especially relevant for the use of language-dependent repositories. So far, we've only been able to tell from the customizations included in Branch v3 that this works with GitHub. Is it planned to do this with DevOps as well? We think it would be very desirable.

**Comment by yufeih** [comment]
Yes. v3 works with azure devops repos, some content on docs.microsoft.com are published from azure devops and we are committed to support that scenario.
