### ISSUE TITLE
Question: is there a way to change the output result structure?

### ISSUE THREAD

**Issue by zdrawku** [dotnet/docfx#6672]
I am having [the following project structure](https://github.com/IgniteUI/igniteui-docfx/tree/master/en/components), is there a way to generate the content from "/components" folder directly under"_site" instead of "_site/components/..". I am trying to simplify the website URL as much as possible and I want to get rid of the "components" part.

This is the output:
![image](https://user-images.githubusercontent.com/11193764/96425277-86764880-1204-11eb-9f1c-463546586867.png)

The wanted result - All folders and files under the "components" folder to be generated under "_site" directly:
![image](https://user-images.githubusercontent.com/11193764/96425605-e240d180-1204-11eb-9425-72e4ef1aab99.png)

This is the [docfx.json configuration](https://github.com/IgniteUI/igniteui-docfx/blob/master/en/docfx.json#L10):
```
"build": {
        "content": [
            {
                "files": [
                    "components/**.md",
                    "components/**/toc.yml",
                    "components/themes/**.md",
                    "components/general/**.md",
                    "toc.yml",
                    "*.md"
                ],
                "exclude": [
                    "obj/**",
                    "_site/**",
                    "components/grids_templates/**"
                ]
            }
        ],
```

**Comment by KalleOlaviNiemitalo** [comment]
How about:

```json
"build": {
    "content": [
        {
            "files": [
                "toc.yml",
                "*.md"
            ],
            "exclude": [
                "obj/**",
                "_site/**"
            ]
        },
        {
            "src": "components",
            "files": [
                "**.md",
                "**/toc.yml",
                "themes/**.md",
                "general/**.md"
            ],
            "exclude": [
                "grids_templates/**"
            ]
        }
    ],
```

i.e. list the `components` directory as a separate [file mapping](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#4-supported-file-mapping-format) with a different `"src"`, but keep using the default `"dest"`.

**Comment by zdrawku** [comment]
Thank you @KalleOlaviNiemitalo, will definitely try this out!

**Comment by KalleOlaviNiemitalo** [comment]
I did test that this kind of thing works, although I did not use your documentation tree.
You mustn't have the same file names in both directories, of course.
