### ISSUE TITLE
`h1-not-first` message is not friendly when `h1-missing` happens at the same time

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#6674]
It shows `{0}`.

![image](https://user-images.githubusercontent.com/3831744/96471792-4940a380-1262-11eb-86cd-8f8b2e051e92.png)

**Comment by yufeih** [comment]
@OsmondJiang

**Comment by OsmondJiang** [comment]
Thanks for the reporting, @fkpwolf would you please help to take a look?

**Comment by fkpwolf** [comment]
@superyyrrzz can you provide the link of build report?

**Comment by superyyrrzz** [comment]
Sorry for misleading... This is from docfx v2 build.
