### ISSUE TITLE
What is the option in toc.md file for topicHref, As we can use TopicHref in toc.yml file which creates navigation bar. ? 

### ISSUE THREAD

**Issue by akshd** [dotnet/docfx#6682]
**Operating System**: (`Windows` or `Linux` or `MacOS`) Windows

**Expected Behavior**: There should be something which can behave same as of topicHref present in .yml file

**Actual Behavior**: I don't find option for .md file to put the feature similar to topicHref. I have multiple subdirectories inside root directory, so i am creating toc.md file in each directory.   

Ex. If i have directory name called ABC and also i have ABC.md file at the same level.  Below is my toc.md structure.
toc.md
# [ABC](PQR/toc.md)
# [ABC](ABC.md) 

Here, i want something like 
- name: ABC
  href:  PQR/toc.md
  topicHref: ABC.md 

I searched a lot but don't find any solution for it

**Comment by yufeih** [comment]
Markdown TOC does not support `topicHref`, use a YAML toc in this case.
