### ISSUE TITLE
There are links present in .md file which are pointing to other md files. Docfx would not able to converts those links into html. Do we have any alternative way to this ?

### ISSUE THREAD

**Issue by akshd** [dotnet/docfx#6683]
**Operating System**: (`Windows` or `Linux` or `MacOS`) Windows

**Steps to Reproduce**:

1.  I have a abc.md file, which contains * [XYZ](a/b/pqr)  i.e. this is link to the pqr.md file 
2.  When i build abc.md file using DocFx, it converts it to abc.html and it contains "href=a/b/pqr"
3. As it is not pointing to "a/b/pqr.html" so it not able to pull the content of pqr file when we click on this link

**Expected Behavior**:  It should convert the links present in .md file as well

**Actual Behavior**: It is not converting those links to html.

**Comment by yufeih** [comment]
Use ` [XYZ](a/b/pqr.md)`

**Comment by akshd** [comment]
Yes, I also tried using *[XYZ](a/b/pqr.md) in abc.md file, after the docFx build it generates abc.html file and it contains "href=a/b/pqr.md" . 

When we check on the browser, by clicking on the link XYZ it points to a/b/pqr.md.   Hence, it is not able to pick the respective html file.

Do you want me to add  [XYZ](a/b/pqr.md) in toc.md ??  I think is will not be the right place to mention, As this is the link present in abc.md file
