### ISSUE TITLE
Navigation bar is expanding and it is hiding the content of the html page

### ISSUE THREAD

**Issue by akshd** [dotnet/docfx#6704]
**Operating System**: (`Windows` or `Linux` or `MacOS`) Windows

**DocFX Version Used**:  2.56.2.0

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:
1. Created toc.yml files in root directory and subdirectories.
2. After performing docfx build, Navigation bar got expanded and it showing subdirectories and files in navigation bar itself.
3. Attached Screenshot for the reference.
4. Tried with "dropdown: true" in toc.yml but doesn't resolve the issue.

![docfxnavbar](https://user-images.githubusercontent.com/11853557/97395258-8e23a480-190a-11eb-831d-ddd07073157c.PNG)

**Expected Behavior**: Navigation bar should not expand may be it should show dropdown list or it should display in left side toc content.

**Actual Behavior**: It is expanding Navigation bar includes all files and directories. Due to this unable to see the content of web page.

**Comment by akshd** [comment]
Also facing issue, when there are "<>" symbols in .md file. it is not able to parse it properly in html file. 
Ex. if abc.md file contains ab-<applicationname>-<usage>-<environmentType>-<region> after docfx build we are getting "ab----"  result in abc.html on browser.

**Comment by yufeih** [comment]
Fixed in the modern template.
