### ISSUE TITLE
[Question] How to include external documentation as done by dotnet-api-docs.

### ISSUE THREAD

**Issue by SMTStuck** [dotnet/docfx#6718]
I have spent all of today trying to work this out with no joy, so would somebody be kind enough to help as the website is missing a much needed complete example.

Take the following example C# code:

```
using System;

namespace ClassLibrary1
{

	/// <summary>
	/// Descriptor of simple class.
	/// </summary>
	public class Class1
	{

		/// <summary>
		/// Doubles a value.
		/// </summary>
		/// <param name="a">Value to double.</param>
		/// <returns>Doubled value.</returns>
		/// <exception cref="Exception">If a is 0.</exception>
		public Int32 Double(Int32 a)
		{
			if (a == 0)
				throw new Exception();
			return a + a;
		}

	}

}
```

While DocFX handles this well, it is not what I'm after.

I do not want to have comments and documentation within the source code. How can I place the documentation in an external markdown file?

I have read that [dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs) uses DocFx extensively, and looking at a sample xml file such as [this](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Range.xml), shows that the documentation is under its own tag:

```
  <Docs>
    <summary>Represents a range that has start and end indexes.</summary>
    <remarks>
      <format type="text/markdown"><![CDATA[
## Remarks
`Range` is used by the C# compiler to support the range syntax:
```csharp
int[] someArray = new int[5] { 1, 2, 3, 4, 5 };
int[] subArray1 = someArray[0..2];               // { 1, 2 }
int[] subArray2 = someArray[1..^0];              // { 2, 3, 4, 5 }
```
          ]]></format>
    </remarks>
  </Docs>
```

How can this be replicated such that I am not relying on the XML comments for extensive documentation?

Many many thanks!

**Comment by VaclavElias** [comment]
Adding a reference which might be helpful on this subject https://dotnet.github.io/docfx/tutorial/intro_overwrite_files.html
