### ISSUE TITLE
There are links present in .md file which are pointing to other md files. Docfx would not able to converts those links into html. Is there any way with DocFX? 

### ISSUE THREAD

**Issue by akshd** [dotnet/docfx#6725]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

**DocFX Version Used**: 

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1.  I have a abc.md file, which contains * [XYZ](a/b/pqr)  i.e. this is link to the pqr.md file 
2.  When i build abc.md file using DocFx, it converts it to abc.html and it contains "href=a/b/pqr"
3. As it is not pointing to "a/b/pqr.html" so it not able to pull the content of pqr file when we click on this link

where do i need to add this links to be convert from .md to .html ?

Example: abc.md file
```
**This is sample md file**

Content of md file:

Click on the link to redirect to pqr file:
* [PQR](/a/b/pqr.md)

```
How should I change the content of md file ?  Or is docFx can recognize that the .md file content have link which is pointing to another .md file ?

Also, it is not possible to add those links in toc.md or toc.yml file. There we are just creating TOC for set of files and directories. 

**Expected Behavior**: Once it is build by DocFx, it should check the content of .md file as well, if any link present in .md file it should convert it to .html so the file can accessible via browser.

**Actual Behavior**: It is converting .md files to .html file when we build it via DocFx.  But unable to convert the content of .md file where we have added link which is pointing to another .md file and it is giving the link as it is.

**Comment by superyyrrzz** [comment]
Say you have 2 files `a/b/abc.md` and `a/b/pqr.md`, you can write a relative link in `a/b/abc/md` like:
``` md
[PQR](pqr.md)
```
A simple relative path `pqr.md` is enough if both 2 Markdown files are in the same folder.

**Comment by akshd** [comment]
We have written similar thing in .md file.  Also, i am using absolute path as it not in the same directory. 
When docfx build these .md file and convert to .html, It is not converting links from .md to .html

**Comment by superyyrrzz** [comment]
Basically, it should work if your write path like `[PQR](../../another_folder/abc.md)`. Docfx will convert the relative path of ".md" into correct path of ".html".

However, docfx will not convert an absolute path, even it ends with ".md".

So the general recommendation is to use relative path in link. You can also provide detailed repro steps to help me understand your usage.
