### ISSUE TITLE
Search term highlighting corrupts XML code snippets

### ISSUE THREAD

**Issue by richorama** [dotnet/docfx#675]
### Functional impact

If search terms match words within an xml code snippet, the XML is corrupted, and in some cases it completely disappears.

### Minimal repro steps

1. Create a page with an XML code block
1. Search for a term on that page
1. Click on the page in the search results

### Expected result

I would expect the code to be highlighted correctly, without removing any of the text.

### Actual result

The highlighters is adding `<mark></mark>` elements around matching terms, which can corrupt the XML formatting.

For example, a page containing this code: `<example></example>`, and searching for `ex` would give you something like `<<mark>ex</mark>ample></<mark>ex</mark>ample>` which would then be rendered as nonsense in the browser.

For example:

![image](https://cloud.githubusercontent.com/assets/353138/18267191/d740b048-7415-11e6-96f7-1e5fe2deb6e3.png)

[http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Configuring-SQL-Tables.html?q=t](http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Configuring-SQL-Tables.html?q=t)

**Comment by qinezh** [comment]
Hi @richorama , thanks for your feedback. The issue was already fixed in dev branch.

**Comment by jdom** [comment]
is this part of a published release? Because we've rebuilt our Orleans docs using DocFx 2.5.2 and we are still experimenting this. You can try the URL provided in the original issue description and still repro it there (which is now using 2.5.2)

**Comment by qinezh** [comment]
@jdom  Could you try the latest version v2.6 of DocFX?

**Comment by jdom** [comment]
Tried the latest (2.6.1) and the issue seems to be solved, thanks
