### ISSUE TITLE
C# 9.0 function pointers are not supported

### ISSUE THREAD

**Issue by GlebChili** [dotnet/docfx#6790]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

Windows

**DocFX Version Used**: 

docfx 2.56.5.0

**Template used**: (`default` or `statictoc` or contain custom template)

`default`

**Steps to Reproduce**:

1. Generate a doc for .NET 5 class lib with the following class: https://gist.github.com/GlebChili/c21774fe918849477e26c47fcc20bf11

**Expected Behavior**:

DocFX generates proper docs for `ShouldBreak` method.

**Actual Behavior**:

![Screenshot 2020-11-20 134831](https://user-images.githubusercontent.com/15145275/99792649-72da3c80-2b38-11eb-8579-eafbf449d0e4.png)

`ShouldBreak` parameters are ignored.

**Comment by GlebChili** [comment]
This can be due to the Roslyn issue: https://github.com/dotnet/roslyn/issues/46674

Roslyn (as in dotnet sdk 5.0.100 RTM) is failing to generate proper XML docs for methods with function pointers.

**Comment by sakno** [comment]
If method has additional parameters including function pointer type then DocFX crashes with the same error as described in #6866. As a result, there is no way to build API doc for .NET 5 project.

**Comment by yufeih** [comment]
We now support function pointers and other latest C# features in the latest version.
