### ISSUE TITLE
Question: dotnet new template for docfx

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#6818]
For our customers that user our .NET Core 3.1 based application framework, we want to create a `dotnet new` template that initialises a new docfx folder containing a custom docfx template and some predefined markdown that documents the end user facing parts our framework. That's where the customer then can add her own documentation to it.

The customer should be able to run this `dotnet new` template and thereafter she should have everything that is needed to build the documentation. Ideally, the template should install all prerequisites needed for docfx. Maybe all the prerequisites could be wrapped into a .NET Core local tool? 

How could this be done? Does something like this exist already?

**Comment by bitbonk** [comment]
@yufeih Did you add the v3 label because this can't be done in v2?

When is v3 coming? Do you think it will be released in 2021?

**Comment by thuannguy** [comment]
I also would like to know when v3 will be released. I have been waiting for it for over a year 😅

**Comment by yufeih** [comment]
>  Maybe all the prerequisites could be wrapped into a .NET Core local tool?

Seems like this issue could be closed since docfx now shipps as a .NET Core local tool.
