### ISSUE TITLE
Question on DocFX (the product) versus the MS docs DocFX build system

### ISSUE THREAD

**Issue by guardrex** [dotnet/docfx#6955]
Hello ... I'm a contractor with Aquent LLC writing documentation for the ASP.NET Core product unit. I'm confused about the difference between DocFX (the product) and MS's documentation DocFX build system: Is DocFX (the product) and the MS doc build system maintained by the same developers and managers? If so, are support requests that don't go in via SiteHelp reported on this repo? I don't have the ability to open a support request with SiteHelp. If not here, would a non-SiteHelp support request be made in the https://github.com/MicrosoftDocs/feedback/issues?

Either way, the reason that I'm asking is that I have a question about versioning content using an approach called "**_version by file_**" for MS docs on the [dotnet/AspNetCore.Docs repo](https://github.com/dotnet/AspNetCore.Docs). That's why I'm asking about where to make a support request that doesn't involve opening an internal SiteHelp issue. If this is the right spot to ask a question about **_version by file_** for MS docs, then I'll shoot my question in here.

**Comment by bianyifan** [comment]
Use "Docs Support" Teams channel.
