### ISSUE TITLE
DocFX doesn't resolve `inheritdocs` for external interfaces

### ISSUE THREAD

**Issue by smaillet** [dotnet/docfx#6995]
**Operating System**: Windows

**DocFX Version Used**: 
2.56.6

**Template used**: custom template

**Steps to Reproduce**:
1. Addd xrefservice to the docfx.json as described in [docfx doc site](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-services)
2. on a type implementing IDisposable add the `/// <inheritdoc/>` comment to the Dispose() Method
2. Build docs

**Expected Behavior**:
Docs would resolve the inheritdocs comment to the official docs for IDispose.Dispose() without errors or warnings

**Actual Behavior**:
`[21-01-17 11:30:05.020]Warning:[MetadataCommand.ExtractMetadata](foo.cs#L50)Could not resolve base documentation for 'Foo.Bar.Dispose'`

**NOTE:** The xrefservice URL for [IDispose.Dispose](https://xref.docs.microsoft.com/query?uid=System.IDisposable.Dispose) does work and retrieves the information, so it's not like the data is missing from the service. It appears that docfx, just can't resolve `inheritdocs` when the docs are inherited from an external interface. (Which is quite a common thing)

**Comment by peache85** [comment]
Any new about this issue ?

**Comment by MrDave1999** [comment]
Any news on this issue? I have the same problem...

**Comment by mikernet** [comment]
As well as external base classes.

**Comment by arnonax-tr** [comment]
Any news or at least a workaround? (other than copy/paste the original docs...)

**Comment by Crono1981** [comment]
I'm using 2.59.4 and this is still happening. :(
