### ISSUE TITLE
docfx not working with .NET 5.0

### ISSUE THREAD

**Issue by bobrundle** [dotnet/docfx#7022]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

Windows 10

**DocFX Version Used**: 

latest (2.56.6.0)

**Template used**: (`default` or `statictoc` or contain custom template)

default

**Steps to Reproduce**:

1.  docfx init
2.  in src create .NET Core library
3. docfx will work
4. Now switch the target framework in the library to .NET 5.0

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>

5. run docfx

**Expected Behavior**:

documentation generated.

**Actual Behavior**:

Build succeeded with warning, but no documentation generated.  Warning includes the following...

Msbuild failed when processing the file 'D:\...\docfx_project\src\ClassLibrary1\ClassLibrary1.csproj' with message: C:\Program Files\dotnet\sdk\2.2.104\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets: (208, 5): Assets file 'D:\...\docfx_project\src\ClassLibrary1\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v5.0'

**Comment by KalleOlaviNiemitalo** [comment]
Does it work if you make DocFX read the DLL and XML files and not see the project files?

**Comment by bobrundle** [comment]
Yes, works fine.  e.g...

$ docfx metadata .\src\ClassLibrary1\bin\Release\net5.0\ClassLibrary1.dll

**Comment by inthegarage** [comment]
I have a similar issue, where docfx does not generate if I point it to the docfx.json which uses the csproj files. If I do that I get an error as follows:

`Could not resolve type with token 01000102 from typeref (expected class 'System.StringComparer' in assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'). Ignored.","source":"MetadataCommand.ExtractMetadata"`

If I also try the dll method then that indeed works as well. So it would seem to be something to do with reading the csproj file and understanding it properly. The actual mechanism of generating the documentation files is a-OK.

My env is Ubuntu 20.04, mono with latest msbuild.
Please let me know if you require any further information.

**Comment by Xwilarg** [comment]
Any news on that?

**Comment by yufeih** [comment]
Does this issue still occur in [Version 2.60.0-preview.2](https://github.com/dotnet/docfx/discussions/8313)?
