### ISSUE TITLE
Conceptual markdown pages not in generated PDF

### ISSUE THREAD

**Issue by songyang-dev** [dotnet/docfx#7027]
**Operating System**: `Windows`

**DocFX Version Used**: 2.56.6.0

**Template used**: `default`

After using `docfx pdf` following the walk-through on the documentation, my generated PDF only contains API specifications, no manual pages. Here is the warning log. Note the website generates perfectly.

![image](https://user-images.githubusercontent.com/10444460/105765201-0f98cc00-5f26-11eb-897f-604b96b52bb2.png)

**Comment by yufeih** [comment]
Addressed in v2.73.0 with [a new PDF engine](https://dotnet.github.io/docfx/docs/pdf.html).
