### ISSUE TITLE
Extend docfx.js

### ISSUE THREAD

**Issue by jonathaneckman** [dotnet/docfx#7044]
I dont see any information on best practices for extending docfx.js to create a custom template. In the [example templates](https://dotnet.github.io/docfx/templates-and-plugins/templates-dashboard.html), I see some move a copy of docfx.js into the project and (I assume) modify it as needed. What are the consequences of doing this? Will I not be able to upgrade to newer versions of docfx? If this is not the way, what is the alternative?

**Comment by superyyrrzz** [comment]
You can add your custom logic in `main.js`. Overwrite it is safe that newer docfx will always keep it empty for extention.
