### ISSUE TITLE
Plugin for code rendering not called for included files

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#7060]
**Operating System**: Windows 10

**DocFX Version Used**: 2.56.6

**Template used**: default + plugins template

**Steps to Reproduce**:

1. Create a custom plugin as described https://dotnet.github.io/docfx/tutorial/howto_customize_docfx_flavored_markdown.html
2. Run docfx build with the plugin on a doc set that uses both inline code and included code snippets

Sample doc (where the double backticks in the middle are really tripled):

```text
# Issue demo

This is inline code:

``csharp
Console.WriteLine("Inline code");
``

This is included code:

[!code-cs[included](index.txt)]
```

where `index.txt` just contains:

```csharp
Console.WriteLine("Included code");
```

... and the custom renderer part includes code of:

```csharp
public override bool Match(IMarkdownRenderer renderer, MarkdownCodeBlockToken token, MarkdownBlockContext context)
    => true;

public override StringBuffer Render(IMarkdownRenderer renderer, MarkdownCodeBlockToken token, MarkdownBlockContext context)
    => "Customized part";
```

Zip file with all of this in, ready to build and run:
[CodeTemplate.zip](https://github.com/dotnet/docfx/files/5970179/CodeTemplate.zip)

Run `run.sh` from git bash on Windows, then look at site/index.html for the results

**Expected Behavior**:

Code should be rendered consistently, with the plugin applying to both inline code and code snippets

**Actual Behavior**:

The plugin is not called when rendering code snippets. The output of site/index.html contains:

```text
<p>This is inline code:</p>
Customized part<p>This is included code:</p>
<pre><code class="lang-cs" name="included">Console.WriteLine(&quot;Included code&quot;);
</code></pre></article>
```

So the plugin itself is clearly working - but not being called for included code.

**Comment by jskeet** [comment]
Update - if I change the file inclusion to use `[!include[included](index.txt)]` and put triple backticks in index.txt, it *does* work. So I suspect the problem is in `DfmFencesInlineRule`. (It's just possible that we can write another custom renderer part to handle this, of course...)

**Comment by jskeet** [comment]
Right: if we add a second custom part for `DfmFencesBlockToken` then that *is* called. This may be a reasonable workaround for us, but it's still inconsistent behavior - it would be nice to be able to write "this is how we want to render code" in *one* place.

**Comment by yufeih** [comment]
Consider move to markdig for markdown extensibility since DFM has been deprecated.
