### ISSUE TITLE
Sometimes Type is generated instead of System.Type in arguments of function UID

### ISSUE THREAD

**Issue by jimon** [dotnet/docfx#7065]
**Operating System**: Windows

**DocFX Version Used**: 2.51, problem doesn't seem to appear on 2.40.12

**Template used**: custom, I think

**Steps to Reproduce**: I have not identified clear steps to reproduce it yet, it's only observable on our CI under yet to be understood conditions, manually running on CI doesn't reproduce the problem

**Expected Behavior**: Function UID with signature `WithExpectedControlType(System.Type)`

**Actual Behavior**: Function UID with signature `WithExpectedControlType(Type)`

Hi, I'm trying to troubleshoot a problem when running on our CI, `System.` prefix disappears from arguments of type `Type`. We have a function of 
```
public RebindingOperation WithExpectedControlType(Type type)
{
	...
}
```
It only happens on CI and only when we run docfx as part of our release tooling, if I run it manually on CI it works as expected, which makes it a bit hard to pinpoint the exact problem.

The Problem is that sometimes `System.` prefix disappears, which breaks our internal documentation links.

Any tips where I should be looking? It maybe be a case that some of ours `filter.yml` influence the output somewhat, but I have hard time pinpointing the issue.

Thanks!

**Comment by KalleOlaviNiemitalo** [comment]
Do you run DocFX on the C# source files, or on DLL and XML files generated by the C# compiler? In the former case, I think the missing namespace could be caused by DocFX using incorrect reference assemblies.

**Comment by jimon** [comment]
@KalleOlaviNiemitalo you were spot on, after a while I managed to capture the referenced assemblies dump from, and when it worked it was referencing `.NETFramework/v4.0/mscorlib.dll` and when it didn't - the reference was missing.

Which is interesting that docfx tries to reference system .NET installation while we're running it under mono on windows .. Maybe it's not supported :)

**Comment by jimon** [comment]
To anyone in a similar situation:

After more digging, the root reason is that our setup was using `docfx metadata`, and we had "Visual Studio build tools" installed on our CI images, but not any of .NET SDK. Our code manually generated `.csproj` to feed into docfx, and it was not specifying any `<TargetFrameworkVersion>`.

Apparently the default behavior of `msbuild` in this scenario is to use .NET v4.0 assemblies, which are shipped as part of Visual Studio install, that nearly every developer has on their machines, but was not installed on the CI. Hence why everything worked locally but failing on CI.

You can observe this by running `docfx` by hand on the CI, it will print msbuild logs complaining that it couldn't find the reference assemblies, as by default it will want something similar to `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll`.

Specifying `<TargetFrameworkVersion>` to something like `v4.7.1` and installing the corresponding .NET SDK on the CI fixes the issue.
