### ISSUE TITLE
Password protect DOCFX

### ISSUE THREAD

**Issue by janfischer27** [dotnet/docfx#7080]
Hi
Can someone tell me, how to passwort-protect my docfx-website? This would be great!
thanks

**Comment by sakno** [comment]
Authentication is a function of web server. Website generated by DocFX is a collection of static resources, not sure that DocFX should be responsible for that.

**Comment by janfischer27** [comment]
Hi Sakno
Thanks for your answer. So i will see if I can solve this with the webserver.
thanks
