### ISSUE TITLE
Handling nullable reference type parameters

### ISSUE THREAD

**Issue by truegoodwill** [dotnet/docfx#7115]
**Steps to Reproduce**:

1. Enable the c# nullables language feature.
2. Create a method that has a nullable parameter, as illustrated below.
3. 

**Expected Behavior**:
It would not mistake the `string?` parameter as `Nullable<string>`

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/77037161/109643518-5465e300-7b22-11eb-823a-4c1c789b30f6.png)

**Comment by KalleOlaviNiemitalo** [comment]
Covered by <https://github.com/dotnet/docfx/issues/4007>.

**Comment by yufeih** [comment]
We now support nullable reference types and other latest C# features in the latest version.
