### ISSUE TITLE
docfx init -q doesn't work

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/docfx#7190]
**Operating System**: Windows 10

**DocFX Version Used**: 3.0.0-beta1.804+90e456a78d

I was following the step-by-step instruction and failed at the second step. Like the instruction prompts, I downloaded win7-x64  from [releases](https://github.com/dotnet/docfx/releases) and tried to run the command from the tutorial. I get this issue:

```
D:\some_path>docfx init -q
'init' was not matched. Did you mean 'new'?
'-q' was not matched. Did you mean '-h'?
Required command was not provided.
Unrecognized command or argument 'init'
Unrecognized command or argument '-q'

Usage:
  docfx [options] [command]

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information

Commands:
  new <templateName>     Creates a new docset.
  restore <directory>    Restores dependencies before build.
  build <directory>      Builds a docset.
  serve <directory>      Serves content in a docset.
```

What am I missing?

**Comment by ILogger** [comment]
It's just as u see, init or -q are unrecognized. I guess DocFX 2 and DocFX 3 are not compatible in many aspects, one of them is creating new project.

You will have to use `docfx new conceptual` or some other template if you have (u can see them with `docfx new --list`).

In the docs there should be warning that it's only for 2.x version, not new one.

**Comment by WhiteBlackGoose** [comment]
Thank you. Maybe it makes sense to make this note more explicit?
