### ISSUE TITLE
Is C# 9 supported?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/docfx#7191]
I'm trying to build docs for a project relying on C# 9 syntax features.

I added `dotnet.console` to the project and then built the project. It successfully generates docs on classes and methods, but apparently does not for `record`s.

Here's a sample project:
[CSharp9BugNotGenerating.zip](https://github.com/dotnet/docfx/files/6136697/CSharp9BugNotGenerating.zip)

The version of DocFX: 2.56.7.

Does 3.0 Beta support C# 9? Then it'd be nice if it appears on NuGet, as a pre-release at least

**Comment by BillHertzing** [comment]
V2.57.2 is not generating documentation for `record` s, either.

**Comment by rico-erhard** [comment]
V2.57.2, I am trying to generate documentation for functions using C# 9 function pointers such as
```C#
/// <summary>
/// Sets a callback.
/// </summary>
/// <param name="fptr">The function pointer.</param>
/// <remarks>
/// C# 9
/// </remarks>
[UnmanagedCallersOnly]
public static void SetCallback(delegate* unmanaged<void> fptr)
```
The parameter of this function is lost during doc generation:
![image](https://user-images.githubusercontent.com/76253376/121144302-250bf400-c83e-11eb-8267-ad0c694f6b5a.png)

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/docfx/pull/6805> has been merged, so I hope DocFX v2.58 will support C# 9. I don't know when it will be released.

**Comment by alexhelms** [comment]
It appears that is now released but it doesn't appear to support records or init properties 😞

**Comment by rico-erhard** [comment]
The issue with the function pointers mentioned above seems to be a Roslyn issue.
When compiling a C# library with such a function and
``<GenerateDocumentationFile>true</GenerateDocumentationFile>``
the resulting XML documentation file lacks the type of the parameter.

See https://gist.github.com/rico-erhard/29b17fa7a1a301ffc6c81851bb92092a

**Comment by yufeih** [comment]
We now support C# features up to C# 11 in the latest version.
