### ISSUE TITLE
Text in nested square brackets is rendered incorrect/not-linked

### ISSUE THREAD

**Issue by ferzkopp** [dotnet/docfx#7212]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Enterprise 2019 Version 16.8.6
- DocFX (nuget) 2.56.6

### Description
Rendering of nested square brackets and text in square brackets can be incorrect.

### Steps to recreate
Author markdown like
```
- [A [B][C]](https://my.link.com)  
```

### Current behavior
Renders like 
```
* [A B][C]
```
with 
```
B][C]
```
linked.

### Expected behavior
Renders like
```
* A [B][C]
```
with completed text linked.

### Correct behavior of other renderers

- Azure DevOps Online markdown preview in git
- https://stackedit.io/app
- https://markdownlivepreview.com/

Found while filing https://github.com/madskristensen/MarkdownEditor/issues/216

**Comment by yufeih** [comment]
This is fixed with markdig been the default markdown engine.
