### ISSUE TITLE
Question to license of docfx.js

### ISSUE THREAD

**Issue by cveizhans** [dotnet/docfx#7217]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 
v2.56.7

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:
Hello, 

We are planning to use DocFX to generate our documentation.

While embedding the styles we noticed something though:

In the header of docfx/src/docfx.website.themes/default/styles/docfx.js it says that this is under MIT license.
// Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license. See LICENSE file in the project root for full license information.

However we stumbled over some code marked as stackoverflow code:
"// see: http://stackoverflow.com/questions/2786538/need-to-escape-a-special-character-in-a-jquery-selector-string#answer-2837646" (line 650)
"// http://stackoverflow.com/questions/11978995/how-to-change-color-of-svg-image-using-css-jquery-svg-image-replacement" (line 702)
"// adjusted from https://stackoverflow.com/a/13067009/1523776" (line 1082)
As far as I can see this is under Creative Commons Attribution Share Alike 3.0 license or 
are you sure that the code is still under MIT?

Thanks and best regards

**Expected Behavior**:
Please clarify / replace stackoverflow code

**Comment by cveizhans** [comment]
Hello, have you had a chance to look into this?

**Comment by yufeih** [comment]
Related #8220
