### ISSUE TITLE
triple-slash links to .NET base libraries erase output

### ISSUE THREAD

**Issue by Emdot** [dotnet/docfx#7245]
**Operating System**: Windows

**DocFX Version Used**: 2.56.7.0

**Template used**: `default`

## Steps to Reproduce
Here's a minimal repro: [docfx-issue.zip](https://github.com/dotnet/docfx/files/6225724/docfx-issue.zip)

1. In C# code, add /// comments that reference a BCL class, such as System.Exception.
2. Add all relevant `using` lines.
2. In docfx.json, set xrefService to `https://xref.docs.microsoft.com/query?uid={uid}`
2. Run docfx

## Expected Behavior
Ideally, docfx should use the xrefService to make a link. At minimum, though, it should show the original text.

## Actual Behavior
docfx fails to resolve the links, and *the text does not appear*.

## Details

The C# from the repro:
```
using System;
using System.Threading.Tasks;
namespace Testing
{
	public class Class1 
	{ 
		/// <summary>
		/// Cref: <see cref="System.Threading.Tasks.Task"/>
		/// <br/>
		/// Xref: @System.Threading.Tasks.Task
		/// </summary>
		/// <exception cref="System.Exception">exception doc</exception>
		public void Foo()
		{
		}
	}
}
```

In the output, note that:
* The xref resolved correctly, which shows that docfx can resolve the reference and that `xrefService` is configured correctly. 
* For the cref, the text is missing. At minimum, it should say System.Threading.Tasks.Task even if it's not a link.
* The exception documentation is missing entirely.
![2021-03-29 21_12_31-Class Class1](https://user-images.githubusercontent.com/3241034/112923299-a6733780-90d3-11eb-9b98-f1f50120f4ec.png)

These are the warnings:
```
[21-03-30 02:09:08.783]Warning:[MetadataCommand.ExtractMetadata]Invalid cref value "!:System.Threading.Tasks.Task" found in triple-slash-comments for Foo defined in C:\Users\3mave\source\tests\docfx-issue\src\Class1.cs Line 12, ignored.
[21-03-30 02:09:08.786]Warning:[MetadataCommand.ExtractMetadata]Invalid cref value "!:System.Exception" found in triple-slash-comments for Foo defined in C:\Users\3mave\source\tests\docfx-issue\src\Class1.cs Line 12, ignored.
```

**Comment by Emdot** [comment]
If you can point me to the right place in the code, I'm willing to submit a PR (assuming it's not especially complicated).

**Comment by Algorithman** [comment]
Made a PR, it replaces the unresolved ref with the cref value, still printing the warnings, but doesn't leave doc's without the class/member names

**Comment by Emdot** [comment]
For other readers: the PR is https://github.com/dotnet/docfx/pull/7325
