### ISSUE TITLE
Namespace conflict

### ISSUE THREAD

**Issue by Shaitan1805** [dotnet/docfx#729]
Hey!

I'm currently working on a pre processor for typescript API documentation.
I want to have a C# section and a typescript section. 
Unfortunately there are colliding some C# namespaces with the typescript namespaces in the documentation. So the result is, that if I click on one of these namespaces in C# section it shows the page of typescript.

I try to make a workaround with the attempt to set a "ts." prefix in front of all typescript namespaces.

My problem is now, that I don't want to show this prefix on documentation pages.
My mynamespace.yml has the attribute `uid` with value `ts.mynamespace` and `name` (displayname) `mynamespace`.
My class has a reference to `ts.mynamespace` and attribute `namespace` is set to `ts.mynamespace`.

It works perfectly in the toc. But all classes in this namespace will show up `namespace: ts.mynamespace` because I think the docfx doesn't use the displayname of the namespace.

That's what I found in the source code of docfx.
``` 
public static ItemViewModel ToItemViewModel(this MetadataItem model)
        {
            if (model == null)
            {
                return null;
            }
            var result = new ItemViewModel
            {
                ...
                NamespaceName = model.NamespaceName,
                ...
            };
```

Is there a solution for this problem or any suggestions of what I'm forget?

PS: sorry for my bad english, I'm not a native speaker

**Comment by vwxyzh** [comment]
Looks like a template issue.

**Comment by vwxyzh** [comment]
@Shaitan1805, can you share your yaml files?

**Comment by chenkennt** [comment]
@Shaitan1805 if I understand your scenario correctly, this issue: #396 should be able to help.

**Comment by Shaitan1805** [comment]
Sorry that I didn't reply for a long time.
I had a little bug in my pre-processor. I fixed it and it works.
Thank you :)
