### ISSUE TITLE
Searchbar not working v2.57.1

### ISSUE THREAD

**Issue by DennisSchoutsen** [dotnet/docfx#7302]
Hi, 
The site layout is fixed with the 2.57.1 version. 👍🏻
We still experiencing an issue with the search function. We don't have this issue in a site generated with version 2.56.7.
When entering a keyword in the search bar the site returns the current page and no search results.

This is also true for the DocFX -documentation site ([link](https://dotnet.github.io/docfx/))

_Originally posted by @DennisSchoutsen in https://github.com/dotnet/docfx/issues/7286#issuecomment-818730390_

**Comment by superyyrrzz** [comment]
Fixed in 2.57.2
