### ISSUE TITLE
docfx v3 "--output-type html" content has to be served, cannot be browsed as files

### ISSUE THREAD

**Issue by mschofie** [dotnet/docfx#7329]
docfx v3 doesn't support PDF generation (as per [the roadmap](https://github.com/dotnet/docfx/blob/v3/docs/roadmap.md)). I'd like to be able to build the docfx content and use the generated content as an offline, browsable representation. For my scenario, I'd like to share the built content with "Private Preview" partners without having to host the content. This _may_ be "Local preview" work from [the roadmap](https://github.com/dotnet/docfx/blob/v3/docs/roadmap.md), but I'd like to get clarity and - potentially - add this use case as a requirement.

When performing a local build, the generated HTML;
1. emits links that aren't to files, but to folders that contain `index.html` files. When serving the content this is fine, since the server will default to serving the `index.html` files. But when browsing the content as files the browser doesn't have this default behavior, so the filesystem is rendered.
2. references files using absolute root.

This makes it impossible to browse the built content without serving it.

**Operating System**: Windows

**DocFX Version Used**: 3.0.0-beta1.880+9e549a660f

**Template used**: 'default', I think.

**Steps to Reproduce**:

1. Create new content: `docfx new conceptual`
2. Add a new file (e.g. `more.md`) and link to that file from the template `getting-started.md`, for example by add `Here's [a link](more.md)`
3. Build the content with `--output-type html`. With the docset in `D:\scratch\docfx\`, I ran:
    ```powershell
    docfx build D:\scratch\docfx\ --output D:\scratch\docfx\__output --output-type html
    ```
4. Open `getting-started\index.html` from the output folder.
5. Click on the link that was added.

**Expected Behavior**:
The browser navigates to the generated HTML for the linked markdown.

**Actual Behavior**:
The browser renders the HTML without styling, and navigates to a folder view when clicking the link to the linked document.

**Comment by yufeih** [comment]
For 1, try add `urlType: ugly` to docfx.yml, this will produce an `getting-started.md` instead of `getting-started/index.md`. We may expose a command line options to change url type.
For 2, links to other markdown files are using relative path, but links to styles and javascripts are still absolute path today.
