### ISSUE TITLE
Create .net tool nuget package

### ISSUE THREAD

**Issue by Bludator** [dotnet/docfx#7337]
I think this definitely should be .net **tool** package as it is easier to work with.

Now if I install `docfx.console` nuget package, I must use something like this to serve documentation:
```
 .\packages\docfx.console.2.42.0\tools\docfx.exe .\doc-project\docfx.json --serve
```

with .net tool package it would looks like:
```
dotnet tool docfx \doc-project\docfx.json --serve
```
And .net core 3 SDK and later support even local installation

[All relevant informations](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)

---

[For example Swashbuckle uses both package types](https://github.com/domaindrivendev/Swashbuckle.AspNetCore)

**Comment by KalleOlaviNiemitalo** [comment]
This reminds me: I had tried to run `docfx serve` from within MSBuild, but it exited immediately. MSBuild apparently [closes the standard input](https://github.com/dotnet/msbuild/blob/57a23d249aafe6409b3e24836a486f769cb74c2c/src/Utilities/ToolTask.cs#L705-L710) pipe of the child process right away. Packaging docfx as a .NET Tool would not help with that, although it could be useful elsewhere.

**Comment by sorashi** [comment]
Duplicate https://github.com/dotnet/docfx/issues/5542#issuecomment-674444140
