### ISSUE TITLE
readme info incorrect

### ISSUE THREAD

**Issue by BenLampson** [dotnet/docfx#7357]
Currently the ReadMe.MD's description is :
## Quick Start

``` 2.x
choco install docfx
docfx init -q
docfx docfx_project\docfx.json --serve
```

I think we need add the text below:
``` 3.x
choco install docfx
docfx new conceptual
```

**Comment by bartengine27** [comment]
Same issue here, after installation:
`
docfx new conceptual
docfx build .
`
open the index.html file in folder _site
