### ISSUE TITLE
Is there any way to preview the rendered html for the pdf template.

### ISSUE THREAD

**Issue by hardikforall** [dotnet/docfx#7376]
I am trying to customize the pdf template.

is there any way I can view the rendered html for pdf in browser.  in single file. 

one work around I see is to apply pdf.default template to docfx site and preview it. but it creates separate files. 

is there any way I can preview the files in single html like the PDF.

**Comment by KalleOlaviNiemitalo** [comment]
DocFX v2 generates separate HTML files and then runs `wkhtmltopdf` to convert the whole set of HTML files to a PDF. AFAIK, it does not have a mode for generating a merged HTML file.

I don't know whether DocFX v3 supports PDF at all.

**Comment by yufeih** [comment]
In v2.73.0, PDF templates uses CSS print media, you can print PDF templates by printing the HTML page, or turn on print media emulation in the rendering tab of browser developer tools.
