### ISSUE TITLE
Support for <note> items (to help migration from SHFB)

### ISSUE THREAD

**Issue by FranziskaRoten** [dotnet/docfx#7381]
**Operation System**: Windows

**DocFX Version Used**: Most recent

**Template used**: Default

**Steps to Reproduce**:

Add triple-slash with note tag inside remarks section:

```
/// <remarks>
///     <para>
///         ...
///     </para>
///     <note type="[note, implement, warning, important, security, etc.]">
///         ...
///     </note>
/// </remarks>
```

**Actual behavior**:
Tag is ignored completely.

**Expected behavior**:
Generate accordingly formatted output (frame, color, icon)

**Comment by KalleOlaviNiemitalo** [comment]
This was supposedly implemented in <https://github.com/dotnet/docfx/pull/1171> already in 2017. Are you using DocFX v2 or v3?
