### ISSUE TITLE
Plus "+" character seems to be not supported in PDF destination path

### ISSUE THREAD

**Issue by Swordancer** [dotnet/docfx#7399]
**Operating System**: Windows 10 x64

**DocFX Version Used**:  2.57.2 (Nuget package).

**Template used**: default

**Steps to Reproduce**:

1. In pdf config file for DocFX  (in my case docfx.pdf.json), for value "dest" of section "pdf" use path with '+' character like "C:/xD+"
2. Try to generate PDF. You will probably get "Build succeeded" but pdf file is empty and broken (0 KB file).
3. Change it to: "C:/xD" and it works.

**Expected Behavior**:  "+" is normal character for any Windows path so it should work.
**Actual Behavior**:  "+" charactere breaks generating PDF file. Without this character it works.

Im not sure if this is _wkhtmltopdf_ issue or DocFX but I do not want to change this path as it's important to keep these path the way it is (of course Im not using "xD+" but path name is important so we do not need to change any Jenkins job commands just for DocFX to work).

EDIT:
I've just tested this using "C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" https://google.com "C:\test+ test\google.pdf" and pdf is created so I guess it is DocFX issue after all.

DocFX:

```
[21-07-06 06:28:59.990]Info:[PdfCommand.PDF]Start generating PDF files...
[21-07-06 06:29:00.079]Info:[PdfCommand.PDF]Documentation_1.0_pdf.pdf is generated based on pdf/toc.json under folder C:\Users\me\Documents\Projects\Project+ Test\src\app\pdf\_result
[21-07-06 06:29:00.287]Info:[PdfCommand.PDF]Completed Scope:PdfCommand.PDF in 297,0399 milliseconds.
```
Result is empty file. Removing + and it works great.

**Comment by yufeih** [comment]
Addressed in v2.73.0 with [a new PDF engine](https://dotnet.github.io/docfx/docs/pdf.html).
