### ISSUE TITLE
Using memberpage results in exception

### ISSUE THREAD

**Issue by jamiehankins** [dotnet/docfx#7422]
**Operating System**: Windows 21H1

**DocFX Version Used**: 2.58.0

**Template used**: `default`, `memberpage`

**Steps to Reproduce**:

1. `git clone https://github.com/jamiehankins/DocFXBug.git` (this is a very small project just to repro the issue)
2. `cd DocFXBug`
3. `.\build.cmd`

**Expected Behavior**: Build the project.

**Actual Behavior**: DocFX crashes.

This regression happened somewhere between 2.56.2 and 2.58.0.

After you've built the project, you can just run docfx.exe directly like so to see the direct output:
```
docfx --loglevel error TestLib\src\docfx.json
```

Here is the direct output:
```
[21-06-11 01:25:44.865]Error:[BuildCore.Build Document.CompilePhaseHandlerWithIncremental.ManagedReferenceDocumentProcessor.Build.BuildManagedReferenceDocument](../docs/api/TestLib.TestClass.yml)Markup failed: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).


Build failed.
[21-06-11 01:25:44.933]Error:[BuildCore.Build Document.CompilePhaseHandlerWithIncremental.ManagedReferenceDocumentProcessor.Build.BuildManagedReferenceDocument](../docs/api/TestLib.TestClass.yml)Markup failed: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).
```

This is a pretty big deal for us. I can't go backwards because I run into issue [4880](https://github.com/dotnet/docfx/issues/4880). I can't use current because of this.

**Comment by jamiehankins** [comment]
Note also that there's some hackery in the csproj file to copy memberpage from the NuGet cache. This doesn't affect the repro. There's no good documentation that I can find on how I'm supposed to run memberpage. The instructions just talk about installing it from the command line directly into your DocFX project directory. That means either "exec"ing Nuget.exe every time you build, or checking in the binaries.

**Comment by dotMorten** [comment]
I'm hitting this same issue

**Comment by dotMorten** [comment]
Turns out I forgot to update the path in my docfx.json file, and it was still referencing 2.57.2. Once I changed that to 2.58 this problem went away

**Comment by Lhoerion** [comment]
This issue occurs on v2.58 whenever a plugin uses `Microsoft.DocAsCode.Build.Common` package. Seems to be an issue with C# 9.0 support #6805.

**Comment by jamiehankins** [comment]
I hope when this is fixed, unit tests are put in place that keeps this from regressing again.

It seems like a pretty big miss for a plugin that's included to just completely not work and cause the tool to not even run.

**Comment by dotMorten** [comment]
@jamiehankins @Lhoerion Did you make sure you also use v2.58.0 for the memberpage (both install the new nuget, and update the json to point to the new folder path)? I only hit this issue when my memberpage version wasn't the same as docfx. Once they were the same, this problem went away for me.

**Comment by jamiehankins** [comment]
> @jamiehankins @Lhoerion Did you make sure you also use v2.58.0 for the memberpage (both install the new nuget, and update the json to point to the new folder path)? I only hit this issue when my memberpage version wasn't the same as docfx. Once they were the same, this problem went away for me.
> Changes: [dotMorten/NmeaParser@6fb1b70](https://github.com/dotMorten/NmeaParser/commit/6fb1b709f42ac0d88e07385b7b2fa65cf93c6c54)
> Workflow: https://github.com/dotMorten/NmeaParser/runs/2831751097?check_suite_focus=true
> Doc example: https://dotmorten.github.io/NmeaParser/api/netcore/NmeaParser.Messages.Bod.DestinationId.html#NmeaParser_Messages_Bod_DestinationId

Yes, I did. It's in the repro I set up at https://github.com/jamiehankins/DocFXBug.

I'll have a look at your links.

**Comment by dotMorten** [comment]
@jamiehankins I can't see that repo. Did you make it public?

**Comment by jamiehankins** [comment]
> @jamiehankins I can't see that repo. Did you make it public?

That would do it! 😃

**Comment by dotMorten** [comment]
@jamiehankins Thanks. I can repro with your code - the big question is, why isn't it happening with mine? It doesn't seem that different.

**Comment by Lhoerion** [comment]
> @jamiehankins @Lhoerion Did you make sure you also use v2.58.0 for the memberpage (both install the new nuget, and update the json to point to the new folder path)? I only hit this issue when my memberpage version wasn't the same as docfx. Once they were the same, this problem went away for me.
> Changes: [dotMorten/NmeaParser@6fb1b70](https://github.com/dotMorten/NmeaParser/commit/6fb1b709f42ac0d88e07385b7b2fa65cf93c6c54)
> Workflow: https://github.com/dotMorten/NmeaParser/runs/2831751097?check_suite_focus=true
> Doc example: https://dotmorten.github.io/NmeaParser/api/netcore/NmeaParser.Messages.Bod.DestinationId.html#NmeaParser_Messages_Bod_DestinationId

I don't use memberpage plugin, but mine own which uses `Microsoft.DocAsCode.Build.Common` NuGet package.
All DocAsCode packages are updated to 2.58.0 version.

**Comment by jamiehankins** [comment]
@superyyrrzz Is there any hope of getting any help for this? This keeps us from moving to the latest version, and anything before the latest version doesn't work for me because of [this](https://github.com/dotnet/docfx/issues/4880).

**Comment by jamiehankins** [comment]
Okay, I'm making progress.

The way this thing works with plugins, is it copies the binaries to a temporary directory and then executes them in a new app domain. That explains why no amount of messing with the app's config file would make this go away.

To fix this, two things have to happen. Two references need to be added to Microsoft.DocAsCode.Build.MemberLevelManagedReference.csproj:
```XML
    <PackageReference Include="System.Memory" Version="4.5.4" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="5.0.0" />
```

In the process of copying the binaries, it sets up a config file, but it doesn't actually exist.
The project file change as well as adding this as a config file gets rid of the crash:
```XML
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

I'll do some testing and make sure things are good, and then I'll submit a pull-request.

**Comment by jamiehankins** [comment]
Fixed by https://github.com/dotnet/docfx/pull/7451
