### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by cilerler** [dotnet/docfx#7423]
Is this project still alive? Should we expect any further development and updated documentation, especially related to v3?

**Comment by Emdot** [comment]
https://github.com/dotnet/docfx/pulse suggests that it's still going

**Comment by cilerler** [comment]
Well, I would suggest you look into the pull requests and commit details. 
- They are "too small" and more on the deployment end; it seems to me that just for maintenance purposes.
- There is a `v3-release` branch where it is stable, but no documentation.  The only theme is the default one and not up to date.
- No project reflects the backlogs for v3.

**Comment by dotMorten** [comment]
I'm confused by this? v2.58 was released last week. Is that not alive enough?

**Comment by cilerler** [comment]
When I look into the release, I don't see continuous development other than community PRs.
When I tried v3, `serve` is broken, and no updated documentation. 

I guess it is just me.  Thanks regardless.

![image](https://user-images.githubusercontent.com/385958/121926864-66077b00-cd0c-11eb-8648-89c2d35e75df.png)

**Comment by dotMorten** [comment]
Yeah v3 branch is a bit frustrating. It's been a work in progress for a very long time, and afaik only supports the build step (metadata step is gone too). I do think the team's focus is on v3 and why v2 is a bit slow moving. I do get a sense v3 is "good enough" for a lot of the microsoft docs site, and there's not very much focus on the tool for use by 3rd parties, which is quite a shame.

**Comment by cilerler** [comment]
Correct, and that is why I asked the question to see what they are doing and what the plan is going forward.

**Comment by FSharpCSharp** [comment]
I see it in many things similarly. I have also been observing the v3 branch or branches for some time now. There are indeed activities taking place on these. But it seems to be progressing very slowly. We are also weighing up here at the company whether we can continue to use the toolkit for our documentation. We have also already tried around with the pre-release versions for the new version 3. But without official documentation, and only using the source code, it is very difficult. There seems to be some very important new features in the upcoming version, but if and when that will ever be released is nowhere to be found, which is kind of a pity.

There seems to be already an issue #7050 , in which was asked for the current status, and also received great encouragement from the community. Unfortunately, the people responsible for the project have not (yet) spoken up.

**Comment by yufeih** [comment]
Yes, this project is still alive! We've just had other priorities that have taken precedence over a formal v3 release. We still have a bit of work to do on it before it's publicly consumable, but we expect to have it done later in the summer.

The [roadmap](https://github.com/dotnet/docfx/blob/v3/docs/roadmap.md) now describes the present state and the gaps of v3.
