### ISSUE TITLE
MSBuildLocator fails to use VS2019 build tools when VS2017 is installed.

### ISSUE THREAD

**Issue by ListlessValkyrie** [dotnet/docfx#7463]
**Windows**

**DocFX v2.58**: 

**default**

**Steps to Reproduce**:

Go and have a look at:
https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Metadata.ManagedReference/MsBuildEnvironmentScope.cs

On line 68:
```
var instances = MSBuildLocator.QueryVisualStudioInstances().ToList();

// workaround for https://github.com/dotnet/docfx/issues/1969
// FYI https://github.com/dotnet/roslyn/issues/21799#issuecomment-343695700
var latest = instances.FirstOrDefault(a => a.Version.Major >= 15);
if (latest != null)
```

Our build server has multiple MSBuild versions installed, and for whatever reason when you enumerate the above the VS2017 one is enumerated first.

(I rebuilt DocFx and put in some logging to get it to log out the instances, its just logging path and version) to get this:

```
foreach(var instance in instances)
{
    Logger.LogInfo($"{instance.MSBuildPath} {instance.Version.Major}");
}
```

09-Jul-2021 13:49:15 | Running DocFx:
-- | --
09-Jul-2021 13:49:15 | [21-07-09 12:49:15.839]Info:[MetadataCommand.ExtractMetadata]C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin 15
09-Jul-2021 13:49:15 | [21-07-09 12:49:15.841]Info:[MetadataCommand.ExtractMetadata]C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin 16
09-Jul-2021 13:49:15 | [21-07-09 12:49:15.841]Info:[MetadataCommand.ExtractMetadata]C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin 16

Because you are using `var latest = instances.FirstOrDefault(a => a.Version.Major >= 15);` it is going to pick the 2017 build tools.

**Expected Behavior**:

I need it to use the VS2019 build tools.

**Actual Behavior**:

It always uses the VS2017 build tools.

**Fix**:

You just need to order them by descending first:

Change line 68 to be:
```
var latest = instances
    .OrderByDescending(a => a.Version.Major)
    .FirstOrDefault(a => a.Version.Major >= 15);
```

and then it will pick 2019 over 2017 if you have it. 

I've rebuilt this and tested locally and it fixes my issue, can we get this in an official release?

**Comment by KalleOlaviNiemitalo** [comment]
Should this be closed? <https://github.com/dotnet/docfx/pull/7469> has been merged and [v2.58.1](https://github.com/dotnet/docfx/releases/tag/v2.58.1) includes that change.

**Comment by yufeih** [comment]
Yes and thanks for the reminder!

**Comment by ListlessValkyrie** [comment]
Hey thanks for this! Busy fighting other coding issues at work right now but looking forward to running the new build later on in the week. Excellent effort 👍
