### ISSUE TITLE
Get XML documentation from satellite library

### ISSUE THREAD

**Issue by vdecristofaro** [dotnet/docfx#748]
Hello,

My web api project exports XML documentation file and docfx create documentation correctly.

However for some endpoints, I still do not understand how to fill some fields. Please see the following picture for details

![image](https://cloud.githubusercontent.com/assets/18700475/18947653/43254906-8634-11e6-8ef9-eee2a300419f.png)
1. How do I fill the fields with red question?

Also in the case where an endpoint has an input based on a POCO defined in another assembly the documentation is very poor even if the object is correctly defined in the swagger file. See the following sample:

![image](https://cloud.githubusercontent.com/assets/18700475/18947788/c49c7694-8634-11e6-8971-f2b2431c5de9.png)

and an extract of the swagger document

```
    "/pc/associate": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "Associate a promocard to a user",
        "operationId": "Associate",
        "parameters": [
          {
            "name": "model",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/AssociateCardViewModel"
            },
            "x-nullable": true,
            "description": "An  object that contains information about the cardholder"
          }
        ],

    [..........]

    "AssociateCardViewModel": {
      "type": "object",
      "x-typeName": "AssociateCardViewModel",
      "additionalProperties": false,
      "required": [
        "Card",
        "Email",
        "Shop",
        "Terminal"
      ],
      "properties": {
        "Card": {
          "type": "string"
        },
        "Email": {
          "type": "string"
        },
        "Shop": {
          "type": "string"
        },
        "Terminal": {
          "type": "string"
        },
        "CardData": {
          "$ref": "#/definitions/ExtendedCardDataViewModel"
        }
      }
    },
```

How do I can handle these cases?

**Comment by hellosnow** [comment]
@vdecristofaro refer to template [rest.child.tmpl.partial](https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/partials/rest.child.tmpl.partial), in `parameters`: 
1. `value` is supposed to be rendered as `default` value of this parameter, refer to `default` definition of [parameter schema](http://swagger.io/specification/#parameterObject).
2. `type` is to show type of this parameter, but if the type is not simple type, in you case it's a reference definition, we have task #465 to show full of complex type but not implement yet.

In `responses`, the `samples` is showing samples of this response, refer to [example schema](http://swagger.io/specification/#exampleObject) and there's samples there.

**Comment by vdecristofaro** [comment]
Thanks @hellosnow.
I'll leave the issue open while the #465 will be closed as well.

**Comment by superyyrrzz** [comment]
Close as the questions in this issue is resolved. Leave #465 to track the remaining feature.
