### ISSUE TITLE
Generated _site HTML docs don't match `docfx serve` website

### ISSUE THREAD

**Issue by svew** [dotnet/docfx#7482]
**Operating System**: `Windows 10`
**DocFX Version Used**:  2.58.0.0
**Template used**: `default`

**Steps to Reproduce**:

1. Build a docfx project. `>docfx internal-wiki\docfx.json`
2. Serve the site. The correct contents are there. `>docfx serve internal-wiki\_site`
3. Shut down the server. 
4. Make a change to the .md files.
4. Delete the _site folder.
5. Rebuild the project. `>docfx internal-wiki\docfx.json`
6. Notice the change is present in the created .html file under the _site folder
7. Serve the site. `>docfx serve internal-wiki\_site`
8. Notice the change is not present in the served site, and does not even match the html files existing in _site.
9. This is even more apparent when directly making edits to the HTML which do not appear when refreshing the page

**Comment by svew** [comment]
@schwjm That was exactly what I needed, thank you!

**Comment by bytemaestro** [comment]
Yes, this was in issue for me as well. Luckily, I accidently previewed the _site folder in VS Code and saw the correct template applied. However, running --serve still showed the previous template. Thought --serve must be caching, but it was the browser cache. thanks.
