### ISSUE TITLE
DocFX v3 - docfx.yml Example

### ISSUE THREAD

**Issue by dend** [dotnet/docfx#7485]
Is there a complete `docfx.yml` example somewhere, that shows how to use the .NET schema configuration.

When I try to build .NET documentation (generated through `ECMA2Yaml` in SDP mode), I get the following errors:

```
Loading docsets...
Loading config...
Restoring dependencies...
Building...
schema-not-found ./api/DeckSurf.SDK.Models/DeckSurf.SDK.Models.PluginMetadata.Author.yml(1,1): Unknown schema 'NetMember'.
schema-not-found ./api/DeckSurf.SDK.Models/DeckSurf.SDK.Models.ConnectedDevice.ReceivedButtonPressHandler.yml(1,1): Unknown schema 'NetDelegate'.
schema-not-found ./api/DeckSurf.SDK.Interfaces/DeckSurf.SDK.Interfaces.IDSCommand.yml(1,1): Unknown schema 'NetType'.
schema-not-found ./api/DeckSurf.SDK.Models/DeckSurf.SDK.Models.ConnectedDevice.Path.yml(1,1): Unknown schema 'NetMember'.
schema-not-found ./api/DeckSurf.SDK.Models/DeckSurf.SDK.Models.ButtonPressEventArgs.Kind.yml(1,1): Unknown schema 'NetMember'.
schema-not-found ./api/DeckSurf.SDK.Models/DeckSurf.SDK.Models.ConnectedDevice.ClearPanel.yml(1,1): Unknown schema 'NetMember'.
schema-not-found ./api/DeckSurf.SDK.Core/DeckSurf.SDK.Core.DeviceManager.SetupDevice.yml(1,1): Unknown schema 'NetMember'.
```

Where do I drop the schema mapping?

**Comment by yufeih** [comment]
Hey @dend. The [default community template](https://github.com/docascode/template) does not yet come with schemas and template files for .NET SDP. You could modify that template to drop the relevant .NET schema files and templates (which as of today hasn't been open sourced).

**Comment by dend** [comment]
Thanks @yufeih - I will fall back to using v2 for now for API documentation generation, and will follow-up once .NET SDP makes it into v3.
