### ISSUE TITLE
Consider adding an option to use `MarkdownPipelineBuilder.UseGlobalization()` in v3

### ISSUE THREAD

**Issue by peymanr34** [dotnet/docfx#7486]
> This extension adds `dir="rtl"` attribute to elements that start with Right-to-Left characters.

Related: 
- https://github.com/xoofx/markdig/pull/239#issue-210919468
- https://github.com/xoofx/markdig/issues/238#issue-349745628

**Comment by yufeih** [comment]
This could likely be addressed using `dir="rtl"` without touching the markdown engine. As an example: https://docs.microsoft.com/he-il/ supports right to left rendering using HTML and CSS.
