### ISSUE TITLE
Snippet highlights not working on staged site

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docfx#751]
### Snippet highlights not working on staged site
https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/tutorials/first-web-api

### Functional impact
we need code highlighting to work

### Minimal repro steps
The following  markdown renders correctly when I build locally with DocFX

```
In the `ConfigureServices` method, add the highlighted code:

[!code-csharp[Main](first-web-api/sample/src/TodoApi/Startup.cs?name=snippet_AddSingleton&highlight=6)]
```

but on https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/tutorials/first-web-api it's not highlighted. Search for ``add the highlighted code:``
### Expected result

Line 6 should be highlighted.

### Actual result
Line 6 is not highlighted. We see the same problem throughout our repo.

cc  @v-anpasi

**Comment by chenkennt** [comment]
Internal issue, close it.
