### ISSUE TITLE
Generate documentation from nuget packages not project reference

### ISSUE THREAD

**Issue by tomasz-lisowski-onxg** [dotnet/docfx#7520]
Hi, it is possible to generate documentation from project witch is add as a nuget package reference?
When project is added a simple project reference (many project in solutions) everything is ok and documents are generated.

is there a solution for this problem via C# , .net core ?

**Comment by Afanyiyu** [comment]
Maybe duplicate of #2635

**Comment by mikernet** [comment]
Is there a reason you can't generate docs for the other project and then reference those from the current project? Once the docs for the nuget project are posted, you use `"xref"` in `docfx.json` to point to the `xrefmap.yml` file in the root and it will map links to those references.
