### ISSUE TITLE
v3 with VS2022 Preview and VS2019 fails to build src csproj....

### ISSUE THREAD

**Issue by ameyasubhedar** [dotnet/docfx#7527]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
WIndows

**DocFX Version Used**: 
Version 3.0.0-beta1.964+76383c4869

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1.  Extract the v3 docfx zip
2.  Add the PATH to System Environment Variable
3.  Follow the Get Started guide in the documentation
4.  Define src in the docfx.json

```
"src": [
        {
            "files": [
                "**/*.csproj"
            ],
            "exclude": [ "**/bin/**", "**/obj/**" ],
            "src": "../src"
        }
      ],

```

Run docfx docfx.json

**[21-08-13 09:47:13.072]Info:[MetadataCommand.ExtractMetadata]Environment variable VSINSTALLDIR is set to C:\Program Files\Microsoft Visual Studio\2022\Preview\, it is used as the inner compiler.**
[21-08-13 09:47:14.363]Info:[MetadataCommand.ExtractMetadata]Loading projects...
[21-08-13 09:47:15.617]Warning:[MetadataCommand.ExtractMetadata](D:/this/PI/Services/src/Data/Data.csproj)Error opening project D:/this/PI/Services/src/Data/Data.csproj: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.. Ignored.

_**Same issue with VS2019 as well.**_ 

Tried force installing the VS2019 and VS2022 build tools again (although they are installed by default for SDK) but same error.

How do I get rid of this error ?

Some csproj has multitargets framework

Complete docfx.json

```

{
  "metadata": [
    {
      "src": [
        {
            "files": [
                "**/*.csproj"
            ],
            "exclude": [ "**/bin/**", "**/obj/**" ],
            "src": "../src"
        }
      ],
      "dest": "api",
      "disableGitFeatures": false,
      "disableDefaultFilter": false
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [
      "default"
    ],
    "postProcessors": [],
    "markdownEngineName": "markdig",
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}
```

**Comment by ameyasubhedar** [comment]
any update  ?

**Comment by yufeih** [comment]
v3 does not support building from csproj at the moment. We'll look at the path forward for .NET API documentation.
