### ISSUE TITLE
Change EditorBrowsableAttribute to be an opt-in filter

### ISSUE THREAD

**Issue by wekempf** [dotnet/docfx#754]
### Title

EditorBrowsableAttribute seems to now exclude classes from documentation
### Functional impact

I've got a framework that makes heavy use of EditorBrowsableAttribute to exclude certain things from IntelliSense. In particular, I exclude some classes that provide extension methods. This means the class names never show in IntelliSense **but the extension methods do**. Previously (been a while since I've updated, so I can't say when this change happened) DocFX wouldn't exclude documentation based on this attribute, but it appears that now it does, and I'd say it does so incorrectly as it causes documentation for this class to be entirely excluded while IntelliSense **will** still show the extension methods.
### Minimal repro steps

Create a project to document. Add [EditorBrowsable(EditorBrowsableState.Never)] to a static class that includes a public extension method. Build the docs and note that no documentation for the class is generated. Use the assembly in another solution and note that while the class isn't shown in IntelliSense the extension methods are.
### Expected result

I don't think EditorBrowsableAttribute should exclude anything from documentation. At the very least, it shouldn't hide anything that's still visible by IntelliSense, which means extension methods should require explicit exclusion.
### Actual result

All documentation is excluded when a class is marked with EditorBrowsableAttribute.

**Comment by wekempf** [comment]
I've thought about this some more, and I don't believe this attribute should **ever** cause documentation to be excluded. For example, this MSDN documentation for [Dispatcher.CheckAccess](https://msdn.microsoft.com/en-us/library/system.windows.threading.dispatcher.checkaccess(v=vs.110).aspx) would be excluded by DocFX, but it's actually very important thatthis be documented for end users. CheckAccess is considered an "advanced API" and so was chosen to be hidden from IntelliSense, but developers are still expected to use it.

**Comment by wekempf** [comment]
Ah... I found the [documentation](http://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html#1-api-filter-rules) about this change that surprised me. I can fix things myself by including my own filter configuration. However, I still think it's wrong to exclude things based on this attribute by default. That should be something you opt-in on.

**Comment by ansyral** [comment]
@wekempf , we could provide an option in docfx.json where you could configure whether to enable default filter, will it be ok for you?

**Comment by wekempf** [comment]
Doesn't make much sense to me to add such an option. After all, you can already do whatever you want by providing your own filter there. Now that I know about this feature, I've gotten my own build to work "correctly", so from the standpoint of there being a bug, there is none.

That said, it still makes *NO* sense to filter out APIs decorated by EditorBrowsableAttribute by default. Rarely would that make sense. This should be an opt-in filter, not an opt-out filter. I and one would assume most others, will find it very annoying to have to change this filter in every project. And I do mean every project. Not documenting an API just because you've hidden it from IntelliSense isn't appropriate. If it's an API not meant to be used at all by end users, then it shouldn't be public to begin with. All this attribute means is the API is "advanced" or rarely used. I again point you to existing practice within the framework today with Dispatcher.CheckAccess and others.
