### ISSUE TITLE
Question: Can the filenames of the html files be modified?

### ISSUE THREAD

**Issue by xxcuratorxx** [dotnet/docfx#755]
The code from some c# files can be documented into html files, where the name of the html file (and the previous metadata file) results from the full qualified class name.

Is there any way to change those filenames by, e.g., by some kind of pattern?

**Comment by vwxyzh** [comment]
Yes, you need to write [a custom step](http://dotnet.github.io/docfx/tutorial/howto_build_your_own_type_of_documentation_with_custom_plug-in.html#create-a-document-build-step), and in the step `Build` method modify [the file property of file model](http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.Plugins.FileModel.html?q=FileModel#Microsoft_DocAsCode_Plugins_FileModel_File), and [enable your plug-in](http://dotnet.github.io/docfx/tutorial/howto_build_your_own_type_of_documentation_with_custom_plug-in.html#enable-plug-in).
