### ISSUE TITLE
I must remove  "**/toc.yml" and  "**/toc.md" from docfx.json to generate pdf

### ISSUE THREAD

**Issue by rramoscabral** [dotnet/docfx#7556]
**Operating System**: Windows

**DocFX Version Used**:  2.58.0

**Template used**:  default

**Steps to Reproduce**:

1. Replicate the Walkthrough Part III: Generate PDF Documentation
2. Build or Rebuild
3

**Expected Behavior**:

Create a PDF

**Actual Behavior**:

Don't create the PDF

[BuildCommand.BuildCore.Build Document.CompilePhaseHandlerWithIncremental.TocDocumentProcessor.Prebuild.BuildTocDocument](toc.yml)Unable to find either toc.yml or toc.md inside api-vb/. Make sure the file is included in config file docfx.json!

[PdfCommand.PDF]No TOC file is included, no PDF file will be generated.
  

**How fixed temporary**:

To fix this issue I must remove or comment the **exclude** lines
```
  "pdf": {
        "content": [
            {
                "files": [
                    "api/**.yml",
                    "api-vb/**.yml"
                ],
                "exclude": [
                  //"**/toc.yml",**
                  //"**/toc.md"**
                ]
            },
 ```
 

My /toc.yml

```
- name: Articles
  href: articles/
- name: API Documentation
  href: obj/api/
  homepage: api/index.md
- name: Another Api Documentation
  href: api-vb/toc.yml
```

**Comment by yufeih** [comment]
Addressed in v2.73.0 with [a new PDF engine](https://dotnet.github.io/docfx/docs/pdf.html).
