### ISSUE TITLE
docfx syntax-highlighting in comment

### ISSUE THREAD

**Issue by DaveSenn** [dotnet/docfx#756]
### docfx syntax-highlighting in comment

I’m using 2.5.4 to generate a API documentation for a class library.
Everything is working, expect for the output result.
docfx renders all comments as code.

For example, this is the comment of the ActionEx class:

```
/// <summary>
///     Class containing some extension methods for <see cref="Action" />.
/// </summary>

```

docfx generates the following HTML code for this comment:

```
<pre sourcefile="api/Extend.ActionEx.yml" sourcestartlinenumber="2" sourceendlinenumber="2"><code class="hljs vbnet"><span class="hljs-keyword">Class</span> containing some extension methods <span class="hljs-keyword">for</span> &lt;xref href=<span class="hljs-string">"System.Action"</span> data-<span class="hljs-keyword">throw</span>-<span class="hljs-keyword">if</span>-<span class="hljs-keyword">not</span>-resolved=<span class="hljs-string">"false"</span>&gt;&lt;/xref&gt;.
</code></pre>
```

I think class.header.tmpl.partial is used as template for this part of the view.
If so {{{summary}}} would not contain the actual comment but the HTML code above.

This is the value of summary in the YAML file containing the information of the ActionEx class:

`summary: "\n    Class containing some extension methods for <xref href=\"System.Action\" data-throw-if-not-resolved=\"false\"></xref>.\n"`
### Minimal repro steps

I tried to create a documentation for the code of this repository: https://github.com/davesenn/extend/ (branch: f_docFinal)
The result can be found here: https://davesenn.github.io/Extend/api/Extend.ActionEx.html
1. Run docfx (`docfx .\.Doc\docfx_project\docfx.json`)
2. Check the output (Output\Doc)
### Expected result

I expected dotfx to render the comment as normal comment without any syntax-highlighting.
### Actual result

Comment is rendered as code element and syntax- highlighting is applied to it.
![capture](https://cloud.githubusercontent.com/assets/7510324/19022002/2d0f44f4-88ce-11e6-9958-91ffde23d302.PNG)

**Comment by qinezh** [comment]
#248

**Comment by DaveSenn** [comment]
OK I do now understand why my comments are getting rendered as text.
Will this “problem” always be part of docfx or do you plan to allow to disable this feature (with a start argument or an entry in the configuration file)?

**Comment by qinezh** [comment]
Yes, we will provide with an option in docfx.json to disable the feature rendering triple-slash comments as markdown. Is that ok with you?

**Comment by DaveSenn** [comment]
Of course, an option to enable/disable this feature sounds perfect to me.
