### ISSUE TITLE
DocFX no longer works with Visual Studio 2019

### ISSUE THREAD

**Issue by Jason1269** [dotnet/docfx#7605]
**Operating System**: `Windows`

**DocFX Version Used**: 2.58.3

**Template used**: `default`

**Steps to Reproduce**:

1. Create blank visual studio solution
2. Create .NET Framework 4.8 Class Library, add `public int MyMethod(string a)` method to Class1
3. Using Package Manager Console, install-package docfx.console
4. Build

**Expected Behavior**:
After step #3 it should add docfx files, e.g. docfx.json
Upon build, step #4, it should generate documentation files

**Actual Behavior**:
Step #3 does nothing, nuget pkg is added, but no other modification is made to project, missing docfx.json, etc

Build does not produce documentation files

This was observed on Visual Studio Enterprise 2019 v16.11.2

Also, updating nuget pkg docfx.console on an already working project to any version beyond 2.58.0 causes docfx to stop producing docs

**Comment by eriksorngard** [comment]
I observe the same behavior with versions later than 2.58.0 in Azure DevOps' VSBuild@1 task as well. Sticking to 2.58.0 keeps the build pipeline alive.

**Comment by yufeih** [comment]
Dup of https://github.com/dotnet/docfx/issues/7570
