### ISSUE TITLE
Support the 'path' and 'select' attributes for inheritdoc

### ISSUE THREAD

**Issue by sharwell** [dotnet/docfx#7628]
It appears that inheritdoc currently only supports the `cref` attribute. The `path` attribute should be supported as well (see dotnet/csharplang#1749). If the `path` attribute is omitted, the documentation tool may optionally use a `select` attribute for compatibility with older Sandcastle comments.

**Comment by dhymik** [comment]
Yes, I would also love to see support for `path` attribute. Without it, preparing DocFx compatible source comments requires a lot of redundancy in the comments.

**Comment by warcreap** [comment]
I would also highly appreciate this feature!
