### ISSUE TITLE
Add Arm64 support

### ISSUE THREAD

**Issue by Joren-Thijs** [dotnet/docfx#7670]
Currently it's impossible to run docFX on arm64 linux devices like rapberry pi 4. On Windows and MacOS there are emulation options available for x64 but on raspberry pi or linux in general, no such thing. Since the advance of Arm happening with the Apple M1,  Surface Pro and Raspberry pi 4. I think it's important to include support for this.

Also I am currently using a Raspberry pi 4 as a backup dev machine and cannot run docFX to update my documentation.

### Request:
Update the project to target .net 6 as well as netstandard and provide binaries for Arm64 as well as x64.

**Comment by FionaNobody** [comment]
Same request here. 

Wondering if Arm64 support is possible in v3, I have two products using docfx for documentation, but all of our work laptops may switch to Apple Silicon in the coming year.
