### ISSUE TITLE
`toc.html` is malformed, causing it to not appear in static client-only site

### ISSUE THREAD

**Issue by Ruin0x11** [dotnet/docfx#7672]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 
`2.58.4.0`

**Template used**: (`default` or `statictoc` or contain custom template)
`default`

**Steps to Reproduce**:

1. Generate a new site with `docfx init -q`, `docfx metadata`, and `docfx build`.
2. Open `_site/index.html`.

**Expected Behavior**:
The table of contents navigation bar should be visible.

**Actual Behavior**:
The table of contents bar is hidden, because of a parsing error. It is logged in the developer console:

```
XML Parsing Error: mismatched tag. Expected: </input>.
Location: file:///C:/[...]/_site.toc.html
Line Number 9, Column 9:
```

The problematic line is here:

https://github.com/dotnet/docfx/blob/0341b6c0e4ec999da8cef6ac50ab720160d09c35/src/docfx.website.themes/statictoc/partials/toc.tmpl.partial#L10

Adding the missing backslash to the `input` element fixes the problem.

**Comment by KalleOlaviNiemitalo** [comment]
Do you use an HTTP server or do you open the file straight from the file system? The current syntax is OK if the files are served as HTML rather than XHTML.

**Comment by yufeih** [comment]
Many of the dynamic features needs a static file server to function correctly.
