### ISSUE TITLE
Release 2.58.8 zip is corrupt

### ISSUE THREAD

**Issue by niederee** [dotnet/docfx#7689]
**Operating System**: Windows

**DocFX Version Used**: 2.58.8

**Template used**: NA

**Steps to Reproduce**:

1.  Downloaded zip https://github.com/dotnet/docfx/releases/download/v2.58.8/docfx.zip
2. Right click and extracted it gives error

**Expected Behavior**:  Unzip should work

**Actual Behavior**: Unzip doesn't work

**Comment by sidneymarie116** [comment]
+1. This version of docfx doesn't seem properly packaged for installation with chocolatey. Please notify us when this is fixed.

**Comment by v-pegao** [comment]
Fixed in v2.58.9: https://github.com/dotnet/docfx/releases/download/v2.58.9/docfx.zip

**Comment by reyang** [comment]
v2.58.9 has another issue #7842 which blocks installation.
