### ISSUE TITLE
Update MarkDig Dependency to 0.26?

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/docfx#7701]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 
2.58.9   
Microsoft.DocAsCode.MarkdigEngine.Extensions

I'm integrating `Microsoft.DocAsCode.MarkdigEngine.Extensions` into an Markdown Editor ([Markdown Monster](https://markdownmonster.west-wind.com) )with swappable  Markdown engines. The default engine - like this library - uses MarkDig, but we're running more current versions of MarkDig(0.26 at this time). Everything works fine with the newer version of MarkDig on its own, but when using the DocFx parser - due to package redirects, DocFx fails to work with the newer version of MarkDig due to type mismatches.

The problem that the older `0.20` version  used is having type issues during initialization as some of the type signatures have changed between these versions so at this point the MarkDig and DocFx parsers can't co-exist.

Specific error is:

> Could not load type 'Markdig.Parsers.Inlines.AutolineInlineParser' from assembly 'Markdig, Version=0.26.0.0, Culture=neutral, PublicKeyToken=null'.

Is there any chance that this library could update MarkDig to a more recent version?

Specifically in this project:

```
docfx/src/Microsoft.DocAsCode.MarkdigEngine.Extensions/Microsoft.DocAsCode.MarkdigEngine.Extensions.csproj
```

**Comment by yufeih** [comment]
Hi Rick, I don't see much problems blocking us upgrading markdig to the latest version, do you happened to have the interest in the upgrade?

**Comment by RickStrahl** [comment]
I don't know anything about the rest of the  large DocFx project as I only use the this one sub-project. I'm afraid changing in this one project may have many related effects in the many other projects involved that I may not be aware of.

I can take a look... but it's probably better for someone more familiar with the full project to at least give a thought how this might ripple down the entire DocFx project.

**Comment by tibel** [comment]
seems that pull-request #7424 covers this already

**Comment by RickStrahl** [comment]
Looks like this is still one version behind and the PR is several months old and they're aware but holding for that PR to be merged first. 🤷‍♂️ 

For now I guess I'll just a private version of the package with the current version to make this work in my project.

**Comment by yufeih** [comment]
We've upgraded markdig to the latest version for dev branch and it'll be shipped with our next release.

**Comment by RickStrahl** [comment]
That's great!! Thank you!

Any word when that release is out? v3?
