### ISSUE TITLE
Changes to rest.tmpl.partial not showing

### ISSUE THREAD

**Issue by joeybagofdonuts** [dotnet/docfx#7702]
I have made some changes to the rest.tmpl.partial and placed those changes in docfx_project/templates/partials/rest.tmpl.partial

I am attempting to build the documentation using this docfx.json file:
`	{
  "metadata": [
    {
      "src": [
        {
		  "src": "../",
          "files": [
            "Concorde.Core.Web/**.csproj"
          ]
        }
      ],
      "dest": "api",
      "disableGitFeatures": false,
      "disableDefaultFilter": false
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [
      "default",
		"./templates/custom"
    ],
    "postProcessors": [],
    "markdownEngineName": "markdig",
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}`

When I view the results of the build, the changes that I made to rest.tmpl.partial are not there.

**Comment by KalleOlaviNiemitalo** [comment]
> placed those changes in docfx_project/templates/partials/rest.tmpl.partial

> "template": [ "default", "./templates/custom" ]

Shouldn't you place the changes in docfx_project/templates/custom/partials/rest.tmpl.partial then?

**Comment by joeybagofdonuts** [comment]
Sorry.. Mistype there... Yes, the rest.tmpl.partial **was** placed in docfx_project/templates/custom/partials/rest.tmpl.partial
