### ISSUE TITLE
Cannot escape | inside code spans.

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#7714]
Escaping `|` like this `\|` inside a code spans does not work. This is supported in GFM and since DFM [is based on GFM ](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a)it should also work in DFM.

**Operating System**: (`Windows`)

**DocFX Version Used**:  2.58.4.0

**Template used**: custom template

**Steps to Reproduce**:

1.  Build the following markdown

```markdown
| Operator | Description          |
|:---------|:---------------------|
| `\|`     | bitwise or operator  | 
```

**Expected Behavior**:

It should look like this:

| Operator | Description          |
|:---------|:---------------------|
| `\|`      | bitwise or operator  | 

**Actual Behavior**:
The table looks totally scrambled.

**Comment by PaulDempsey-ms** [comment]
As a workaround, you can use an html character entity: &#x007C;

**Comment by yufeih** [comment]
The table should appear now that markdig has become the default the markdown engine.
