### ISSUE TITLE
Italic Text at end of bold text block in Markdown parser renders incorrectly

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/docfx#772]
The following Markdown code renders incorrectly:

`**this is bold and *italic***`

This will render bold text of this text:

`this is bold and *italic*`

Putting a space at the end:

`**this is bold and *italic** *`

produces italic text for the whole block and this text:

_this is bold and italic_ **

Using Microsoft.DocAsCode.MarkdownLite 2.6.0

**Comment by vwxyzh** [comment]
```md
**this is bold and *italic***
```
The result is same as GitHub.
```md
**this is bold and *italic** *
```
The result is different from GitHub, and we create a pull request for this bug.
