### ISSUE TITLE
Support for image format :::image type="icon" source="<folderPath>" border="false":::

### ISSUE THREAD

**Issue by bbsparkrock** [dotnet/docfx#7732]
**Operating System**: Windows

**DocFX Version Used**: 1.62.3

**Template used**: `default`

**Steps to Reproduce**:

1. In Visual Studio Code, in a markdown file, choose Alt + M.
2. For "Which command would you like to run?", choose Image.
3. For "Select an image type", choose Image.
4. For "Select image from repo", select the image that you want to insert.
5. Run docfx to generate html output.

**Expected Behavior**: Image to appear in HTML output correctly.

**Actual Behavior**: Image displays as :::image type="icon" source="<folderPath>" border="false"::: in HTML output.

**Comment by KalleOlaviNiemitalo** [comment]
I don't see a DocFX 1.62.3 release in this repo. Is that the correct version number? Maybe it's really old and does not support all the current syntax.

**Comment by yufeih** [comment]
@bbsparkrock , did you happen to have installed [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack)? That extension pack is specifically for authoring contents published to https://docs.microsoft.com, not a general-purpose markdown authoring tool. The image syntax you mentioned is specifically for https://docs.microsoft.com.

**Comment by bbsparkrock** [comment]
@yufeih @KalleOlaviNiemitalo I have installed the Docs Authoring Pack. I am using DocFX version 2.58.9. I apologize for mentioning the incorrect version above. Is that image syntax supported by DocFX? 
FYI. My company extends the Microsoft content with content of our own. When I download the Microsoft content, I have to convert the format that they are using for images. I would prefer to not have to do that if possible.
