### ISSUE TITLE
DocFx doesn't work with C# 10 implicit usings

### ISSUE THREAD

**Issue by geeknoid** [dotnet/docfx#7737]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

Windows

**DocFX Version Used**: 

2.58.9.0

**Template used**: (`default` or `statictoc` or contain custom template)

Default

**Steps to Reproduce**:

1. Specifically, set ImplicitUsings=true in a .csproj file
2. Create a source file that does NOT have "using System;" in it
3. Add a class and in the documentation for that class, include a `<see cref="Exception" />`
4. Run "docfx metadata"

You'll get errors complaining that "Exception" is not defined. If you add "using System;" in the C# file, then things work OK.

**Comment by JeremyCaney** [comment]
It's worth acknowledging that this limitation also affects—and is likely driven by a lack of support for—C# 10's **global using directives**. Implicit using directives are actually a feature of the .NET 6 SDK, which utilize C# 10's global using directives under-the-hood, so this isn't at all surprising.

It's also worth noting that the new .NET 6 project templates (used by both the .NET 6 SDK and Visual Studio) enable implicit using directives by default, so this is likely going to affect more developers as they adopt DocFx for new .NET 6 projects.

**Comment by KalleOlaviNiemitalo** [comment]
If you run the compiler separately and pass the binaries to DocFX, then the format of the using directives will not matter.

**Comment by geeknoid** [comment]
@KalleOlaviNiemitalo I didn't know that was possible. Would you have a pointer to how to do this?

Right now, our CI system does:

docfx metadata docfx.json
docfx build docfx.json

To build our docs. Of course, we also build our binaries independently as part of the CI pipeline. So it'd be great to reuse the built binaries for DocFx. What's the needed voodoo?

Thanks.

**Comment by JeremyCaney** [comment]
@geeknoid: In your `docfx.json`, just point to your assemblies, instead of e.g. your project files or source code. E.g., 
```json
{
  "metadata": [
    {
      "src": [
        {
          "files": "**/bin/Release/net6.0/**.dll",
          "src": "../"
        }
      ],
      "dest": "api"
    }
  ],
  …
}
```
> _Note:_ You'll obviously need to customize the path based on your project type and configuration. 

So long as your build task runs prior to your DocFx task in your CI pipeline, that should work just fine. It might require a bit of care when testing locally to make sure that the latest binaries are published to the correct configuration ahead of time.

**Comment by MrDave1999** [comment]
Any news on this problem? Is there a solution?

**Comment by yufeih** [comment]
File-scoped namespace was supported in the latest version of docfx. See [this as an example](https://github.com/dotnet/docfx/blob/main/samples/seed/src/DotnetNew/CSharp10.cs).
