### ISSUE TITLE
StackOverflowException on circular reference

### ISSUE THREAD

**Issue by mkonijnenburg** [dotnet/docfx#7739]
Windows, docfx2.58.9 and all previous

Add the following classes to a project:

```
/// <summary>The base class of everything.</summary>
public class AAA	{	}

/// <inheritdoc cref="BBB"/>
/// <summary>The derived class doing something better.</summary>
public class BBB	{	}

```

Class BBB has a circular reference to itself which is syntactically correct, but erroneous. docFX should report an error.

What happens is that the tool ends with an StackOverflowException.

**Comment by KalleOlaviNiemitalo** [comment]
Duplicate of <https://github.com/dotnet/docfx/issues/7035>.
