### ISSUE TITLE
Why we need the folder obj?

### ISSUE THREAD

**Issue by sogeisetsu** [dotnet/docfx#7744]
I cannot find out why docfx creates `\obj` folder when executing `docfx docfx_project\docfx.json`

**Comment by GoldThruster** [comment]
I'm just a user, but seems like it's saving some data (cache, info) useful to itself for later (to make it faster). (exactly as C# compiler does).

**Comment by sogeisetsu** [comment]
> I'm just a user, but seems like it's saving some data (cache, info) useful to itself for later (to make it faster). (exactly as C# compiler does).

Thank you for your answer, I have benefited a lot.
