### ISSUE TITLE
Improve this Doc missing when running without "origin" remote

### ISSUE THREAD

**Issue by jdom** [dotnet/docfx#778]
The `Improve this Doc` button is missing when running without `origin` remote from where the docfx.json project is.

I have a github repo cloned locally and I spent hours trying to figure out why when I build it on my machine, the generated HTML didn't contain the `Improve this Doc` button. The rest of the HTML was exactly the same as the one generated from a different machine, just that piece missing.

I found out, after explicitly outputting the view model, that the `docurl` property ended up as an empty string. I'm still not sure why, but when I added a remote called `origin`, everything started working correctly.
I do not understand why it specifically needs a remote called `origin`, since it does not seem to use it for anything in my set up (I know, typically people have a remote with that name, but what is the need to have it in this case? does it have to point somewhere?).
Without being too familiar with the code, I assume the issue is in the [getRemoteUrl function](https://github.com/dotnet/docfx/blob/master/src/docfx.website.themes/common/common.js#L120)

The metadata I'm using is:

```
    "globalMetadata": {
      "_appTitle": "Microsoft Orleans Website",
      "_enableSearch": true,
      "_gitContribute": {
        "repo": "https://github.com/dotnet/orleans",
        "branch": "gh-pages",
      },
	  "_gitUrlPattern": "github"
    }
```

I would have expected that is enough info to render the contribution div correctly.

**Comment by ansyral** [comment]
our code uses the remote `origin` to get the repository info. The check logic would fail if there is no remote named `origin`. For multiple remotes, is it better to add an option for user to assign their remote?

**Comment by jdom** [comment]
Well, the point is that the *only* difference in the html output for my case was that the button was not there. It doesn't seem like it needs that remote at least for that button, as all the info is available in _gitContribute. So it seems the check is not where it needs to be.

**Comment by ansyral** [comment]
we would check remote.repo and use _gitContribute info to overwrite remote.repo only when remote.repo exists. seems the check is the problem.

**Comment by jdom** [comment]
Exactly

**Comment by jdom** [comment]
Created PR #797 with a potential fix, since you confirmed my suspicion.
