### ISSUE TITLE
Need clearer docs for YAML input

### ISSUE THREAD

**Issue by asklar** [dotnet/docfx#7795]
I'm exploring creating a bridge from Doxygen to DocFX for C++ code, and I'm hitting issues with the yaml input I feed to docfx.
I read through https://dotnet.github.io/docfx/spec/metadata_format_spec.html, but the docs there seem to lack basic information about the format and restrictions (ordering of items, for example).
I started by creating the HelloDocfx sample from the docs, and then reverse engineering what each piece of yaml does, but as you can imagine this isn't very efficient.

**Comment by yufeih** [comment]
The docs on adding additional language support is updated here: https://dotnet.github.io/docfx/docs/additional-languages.html
