### ISSUE TITLE
DocFx Serve is not blocking when run in Kubernetes - CrashLoopBackOff - exit code 0

### ISSUE THREAD

**Issue by jsinh** [dotnet/docfx#7818]
**Operating System**: `Linux` 

**DocFX Version Used**: 2.58.9

**Template used**: `default`

**Steps to Reproduce**:

I have a docker file similar to this: 

```
FROM mono:latest

EXPOSE 8080

ADD docs/_site _site

ADD .devops/docfx .devops/docfx

COPY .devops/entrypoint.sh .devops/entrypoint.sh

CMD mono ./.devops/docfx/docfx.exe serve _site -n "*"
```

In above I have a download release of DocFx in my repo so I don't have to install it - I just copy that entire release extract to my container so I can just call docfx.exe via Mono.

`_site` has all things that are the outcome of `docfx build` command.

If I run this as a docker file it works, but if I deploy this into Kubernetes - the Pod that will run this container keeps giving me `Back-off restarting failed container` `CrashLoopBackOff` and the last status
```
terminated
Reason: Completed - exit code: 0
```
So for some reason, the `docfx serve` command does not block and stay put but instead just exit with code 0

I also confirmed this by adding a `sleep 10` and then an `echo "Testing blocking serve"` - In this case on local it just shows the `Serving "/_site" on http://*:8080` but on K8S it shows `Serving "/_site" on http://*:8080` then after approx 10 sec it shows my echo string.

Need help figuring out why is the serve command in Kubernetes not blocking and exist with code 0, thanks in advance.

**Comment by KalleOlaviNiemitalo** [comment]
I have seen docfx serve exit immediately when run from MSBuild on Windows. I think it needs to block trying to read a line from stdin. Perhaps you could pipe to it the output of some sleep-forever command.

**Comment by jsinh** [comment]
@KalleOlaviNiemitalo  - thanks for confirming that it happens for others too. By any chance you have a rough sample I can try out - sorry I am not much of an expert in Linux shell scripting

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps like this

```
CMD sleep 3600 | mono ./.devops/docfx/docfx.exe serve _site -n "*"
```

which should sleep for one hour and keep docfx serve running for that time.

If one hour is not enough, then use a larger number or a loop:

```
CMD while sleep 3600; do true; done | mono ./.devops/docfx/docfx.exe serve _site -n "*"
```

**Comment by jsinh** [comment]
@KalleOlaviNiemitalo  - Tried but still does not work. I realize the issue might be something to do with mono not being able to execute the docfx.exe in k8s specifically.

**Comment by KalleOlaviNiemitalo** [comment]
Maybe it's easiest to work around this by using a different http server, like nginx.

**Comment by jsinh** [comment]
@KalleOlaviNiemitalo  - Tried that, the issue is the docfx serve never sticks around - maybe crashes or never even starts serving because of some error with Mono, DocFx runner, underlying docker image OS - not sure as there is no info I can find anywhere that I can use to investigate more.

This is frustrating while it's hard to make docfx run consistently on all forms of hosting, specifically there is no strong support for Docker/Kubernetes hosting.

After spending 2 days with no luck with it, I have moved on and started using an alternative documentation generator CLI/Tool. Sad to see such popular tool being in such an inconsistent state.

If anyone from the DocFx team can actually solve it for future folks who will get stuck then great, for me I would say doesn't matter anymore, thanks @KalleOlaviNiemitalo  for the help and a few pointers to try but I have to keep my org's investment in me and in the tool to be efficient.
