### ISSUE TITLE
Choco install fails for version 2.58.9

### ISSUE THREAD

**Issue by florian-de-vries** [dotnet/docfx#7842]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 2.58.9

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1.  choco install docfx -y

**Expected Behavior**:
Install and checksum validation succeeds

**Actual Behavior**:
Download of docfx.zip (21.62 MB) completed.
Error - hashes do not match. Actual value was 'E6BD6D788DDB07D9BCB6D90F2822D7E2E6C4FEB0E2CAEABC60FF39232D07BC52'.
ERROR: Checksum for 'C:\Users\VssAdministrator\AppData\Local\Temp\chocolatey\docfx\2.58.9\docfx.zip' did not meet '18e2277704b318d5c785681b69296aa072eca30ee5cab5b19de77ede830bbd3c' for checksum type 'SHA256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of docfx was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\docfx\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by rohit-kumar6** [comment]
Getting the same issue. Can someone quickly help it on it.

**Comment by florian-de-vries** [comment]
> Getting the same issue. Can someone quickly help it on it.

Both DocFX and Choco had an update today, version 2.59 and 0.12.0 respectively. The `choco install docfx -y` points to the previous versions of both so the issue could be related to the updates...

**Comment by rohit-kumar6** [comment]
Whats the work around or solution ?

**Comment by florian-de-vries** [comment]
You could try to specify a specific version by doing `choco install docfx -y --version=2.58`. Haven't had the chance to try that yet myself.

**Comment by simonlindblad** [comment]
> You could try to specify a specific version by doing `choco install docfx -y --version=<version>`. Haven't had the chance to try that yet myself.

`choco install docfx -y --version=2.58` works FWIW

**Comment by nl3rz** [comment]
Thank you @simonlindblad, this worked for me as well.

**Comment by superyyrrzz** [comment]
We find 2.59.0 release accidentally overwrote 2.58.9 GitHub release. We tried to re-create the 2.58.9 package, but failed to get the same checksum as before.

# **NEED YOUR HELP**

If you happened to install 2.58.9 before, and has the zip on your local machine, please share your package with us, Thanks!

You can check the file's checksum to see if it is `18e2277704b318d5c785681b69296aa072eca30ee5cab5b19de77ede830bbd3c`:
```
Get-FileHash "$env:temp\chocolatey\docfx\2.58.9\docfx.zip" -Algorithm SHA256
```

**Comment by KalleOlaviNiemitalo** [comment]
[docfx.zip](https://github.com/dotnet/docfx/files/7903643/docfx.zip)

This has 18E2277704B318D5C785681B69296AA072ECA30EE5CAB5B19DE77EDE830BBD3C

**Comment by superyyrrzz** [comment]
@KalleOlaviNiemitalo Many thanks! 2.58.9 is back now on choco 👍👍👍

**Comment by KalleOlaviNiemitalo** [comment]
Out of curiosity, when you wrote that the correct hash is 18e2277704b318d5c785681b69296aa072eca30ee5cab5b19de77ede830bbd3c, did you verify this from a Microsoft source, or did you trust the information from Chocolatey?

(The files within are identical to those in the 2.58.9 NuGet package, anyway.)

**Comment by florian-de-vries** [comment]
Just checked and works again! Thanks all!

```
Download of docfx.zip (21.54 MB) completed.
Hashes match.
Extracting C:\Users\VssAdministrator\AppData\Local\Temp\chocolatey\docfx\2.58.9\docfx.zip to C:\ProgramData\chocolatey\lib\docfx\tools...
C:\ProgramData\chocolatey\lib\docfx\tools
 ShimGen has successfully created a shim for docfx.exe
 The install of docfx was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\docfx\tools'

Chocolatey installed 1/1 packages.
```

**Comment by superyyrrzz** [comment]
@KalleOlaviNiemitalo No, the hash is not recorded in Microsoft source... You are right that Chocolatey could potentially be hacked or docfx package entry is tampered. I can only check if the assemblies are code signed by Microsoft after getting the package.

**Comment by KalleOlaviNiemitalo** [comment]
It seems GitHub does not record changes of releases in the [audit log](https://docs.github.com/en/enterprise-cloud@latest/organizations/keeping-your-organization-secure/reviewing-the-audit-log-for-your-organization) either.

**Comment by reyang** [comment]
Maybe bump the version and release 2.58.10 is a better way (and flag 2.58.9 as a broken release)?
