### ISSUE TITLE
docfx.zip missing for for release 2.59.0

### ISSUE THREAD

**Issue by nfon-christophe** [dotnet/docfx#7844]
The compiled version (docfx.zip) usually provided when a new release becomes available is missing for the 2.59.0 release

See https://github.com/dotnet/docfx/releases/tag/v2.59.0
vs
https://github.com/dotnet/docfx/releases/tag/v2.58.9

**Comment by KalleOlaviNiemitalo** [comment]
There's are binaries available from <https://www.nuget.org/packages/docfx.console/2.59.0>; rename .nupkg to .zip, extract, and use the files in the tools directory.

**Comment by nfon-christophe** [comment]
The docfx.zip file has now been added to the release page

**Comment by KalleOlaviNiemitalo** [comment]
The missing docfx.zip caused the package verification testing to fail on Chocolatey: <https://gist.github.com/choco-bot/37bcefc5fd730b71706d1c8f308f5677#file-install-txt-L344-L367>

A maintainer should rerun it now that the file has been added.
