### ISSUE TITLE
2.59.0 API download not working

### ISSUE THREAD

**Issue by cedar-ave** [dotnet/docfx#7863]
**Operating System**: Windows

**DocFX Version Used**: 2.59.0

**Template used**: default and custom

**Steps to Reproduce**:

1. Go here https://api.github.com/repos/dotnet/docfx/releases/latest
2. Download docfx.zip
3. docfx.zip contains repo, not program
4. DocFx won't build

**Expected Behavior**:

Extracted downloads of docfx.zip in previous releases looked like this:

![2022-01-25 11_52_03-Window](https://user-images.githubusercontent.com/15255009/151040415-d0876118-f321-4ffe-9bef-40f58f6049ac.png)

**Actual Behavior**:

Extracted download of docfx.zip currently looks like this:

![2022-01-25 11_52_31-Window](https://user-images.githubusercontent.com/15255009/151040535-d685ead3-60bf-4484-baad-62d30eca1cc8.png)

Thank you

**Comment by dotMorten** [comment]
Really? I downloaded `https://github.com/dotnet/docfx/releases/download/v2.59.0/docfx.zip`
This is what I see: 
![image](https://user-images.githubusercontent.com/1378165/152058724-80f7919c-e207-4d31-8613-590ea11cc317.png)
And it worked just fine for me

**Comment by yufeih** [comment]
I am unable to repo this problem, maybe you have hit the `Source code (.zip)` link?

**Comment by cedar-ave** [comment]
I know I sound crazy but this was fixed and now it's happening again. Is anyone able to try right now?
https://api.github.com/repos/dotnet/docfx/zipball/v2.59.0
