### ISSUE TITLE
Missing cross-references for non-BCL types when running on Linux via mono

### ISSUE THREAD

**Issue by wehrend** [dotnet/docfx#7876]
Due to confidentality I cannot cite the real source here, instead just the explanation

**Operating System**: Linux (Debian Bullseye)

**DocFX Version Used**: 2.59

**Template used**: `statictoc`

**Steps to Reproduce**:

1. mono docfx-binary/docfx metadata project/docfx.json
2. mono docfx-binary/docfx build project/docfx.json

**Expected Behavior**: 
Classes inherited from Object are resolved and linked like for the 'System' namespace
This works correctly when run on a windows system

**Actual Behavior**:
Classes inherited from 'System' namespace are resolved, but not classes inherited from Object.

**Comment by yufeih** [comment]
Address in the cross-platform .net core version.
