### ISSUE TITLE
Search service worker error

### ISSUE THREAD

**Issue by glararan** [dotnet/docfx#7883]
**Operating System**: Windows

**DocFX Version Used**: 2.59.0

**Template used**: default

**Steps to Reproduce**:

1. Download newest version
2. docfx init -q
3. enable search
4. docfx docfx_project\docfx.json --serve

**Expected Behavior**:
working search

**Actual Behavior**:
search crash

```
search-worker.js:39 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'search')
    at onmessage (search-worker.js:39:26)
```

![image](https://user-images.githubusercontent.com/281441/153615328-7fad6dbc-7e16-4895-9c38-9e0b8d186204.png)

**Comment by glararan** [comment]
Ok so there was actually problem search index.json is not generated if noFollow is set to true.

Should be noted in docs.

**Comment by KalleOlaviNiemitalo** [comment]
Where was noFollow set to true?

**Comment by glararan** [comment]
![image](https://user-images.githubusercontent.com/281441/153922050-9722e2eb-7733-404c-8325-3b67320d270a.png)

I thought its google search :) meta tag no index no follow
