### ISSUE TITLE
Insanely large DocFX folder

### ISSUE THREAD

**Issue by guardrex** [dotnet/docfx#7885]
**Operating System**: `Windows`

**DocFX Version Used**: 2.59.0

**Template used**: `default` (I think)

**Steps to Reproduce**:

1. Check the size of the `.docfx/downloads3` folder.

**Expected Behavior**:

A **_reasonable size_** ... i.e., DocFX does something to keep this folder from growing forever until the system runs out of drive space.

**Actual Behavior**:

This folder had grown to 56 GB and wiped out all of my remaining drive volume space.

**Comment by yufeih** [comment]
I agree we could do something to keep that folder from growing indefinitely. In the meantime, deleting the `.docfx/download3` or `.docfx/git6` folder is completely safe. They are just for caching.

**Comment by guardrex** [comment]
A caching design that **_isn't kept tidy by the app_** and at the same time **_escapes a Windows volume Disk Cleanup_** is a disaster. This design ***never*** should've been approved in the first place.

**Comment by guardrex** [comment]
I just cleared these folders again six weeks later ... **_8 GB of DATA!_** 😩

**_Please do not let this slip off of the v3 roadmap._**

**Comment by yufeih** [comment]
Thanks for the update! I have created an [internal customer suggestion](https://dev.azure.com/ceapex/Engineering/_workitems/edit/579670) and route to the relevant team.

**Comment by ekpgh** [comment]
Hiya! I just discovered this problem on my MacBook. 

I'm running MacOS Monterey v 12.6.1 but the problem goes back to 2020 at least, so who knows what I was running then.

```
$ du -hs ~/.docfx/*
 46G	/Users/ekelly/.docfx/downloads3
 31G	/Users/ekelly/.docfx/git6
```
GrandPerspective showed 88GB of files in there this morning. I cleared out the files from 2020 and got almost 10 GB back. My oldest files were from October 2020. 

I don't directly use DocFX, but I use Visual Studio Code to work on documentation in Markdown. The cached files I see resemble the documentation repository I work in.

**Comment by yufeih** [comment]
Close as this is to be taken care of by internal Microsoft teams.

**Comment by ekpgh** [comment]
Is there a Microsoft-internal way to trace this? I'm Microsoft. I followed that work item link in the March 27 comment and it gives a 404 even though I'm logged in.

**Comment by yufeih** [comment]
@ekpgh This [internal customer suggestion](https://dev.azure.com/ceapex/Engineering/_workitems/edit/579670) is still valid, there are likely some permission problems. Meanwhile you can contact `misaso` for internal inquiries. We are in the process of transitioning docfx to be an open source community driven tool, mslearn content will be supported by a dedicated internal tool. See [this discussion  comment](https://github.com/dotnet/docfx/discussions/8277#discussioncomment-4409645) for more details.

**Comment by steved0x** [comment]
Still happening as of Feb 2023, every few days I am deleting 12+GB of files from downloads3 and git6, most of it seems to be for repos that I don't use, like azure-docs-pr (I have used/cloned it in the past but I don't use it anymore)

**Comment by flang-msft** [comment]
@guardrex  - was there ever a solution to this? It continues to happen on my computer too.

**Comment by guardrex** [comment]
Not that I'm aware of. I've abandoned using docfx locally. On my latest PC build here, I never installed it, so I don't use it any longer. Therefore, ***problem solved!*** 😆 ... of course, not quite in the way that we were hoping.

**Comment by flang-msft** [comment]
[laugh]         Francis Langlois reacted to your message:
________________________________

**Comment by v-thepet** [comment]
My (fairly new but hardly beefy) computer is dying! Uninstalled docfx and cleared space, still 18 gb of downloads! Happy to know I can delete them. Maybe they will not regenerate since I uninstalled it?

**Comment by flang-msft** [comment]
> My (fairly new but hardly beefy) computer is dying! Uninstalled docfx and cleared space, still 18 gb of downloads! Happy to know I can delete them. Maybe they will not regenerate since I uninstalled it?

What did you uninstall?
