### ISSUE TITLE
Code block scroll bars

### ISSUE THREAD

**Issue by JeremyBP** [dotnet/docfx#7893]
**Operating System**: `Windows`

**DocFX Version Used**: 2.59

**Template used**: `default`

**Steps to Reproduce**:

Just write a long line into a code block

**Expected Behavior**:

Rendering with an horizontal scroll bar like it does on GitHub:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu urna fringilla, pellentesque mi in, rhoncus ipsum. Nullam est mauris, ornare sed hendrerit nec, rutrum in dui.
```

**Actual Behavior**:

The line break mode seems to be word wrap:

![word wrap](https://camo.githubusercontent.com/1e1ba68645e8c81d52776c6593f8040a6452f7da1c00ae9e1feed4aedb3bc60b/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3837343339302f323139363531372f39313732356261342d393862302d313165332d393633322d6665343936393032396465362e706e67)

Actually, it would be cool if we could set somewhere into the docfx.json an option to choose between word wrap or scroll bar about code blocks. 
Anyway, I think I could fix my problem thanks to a custom template editing css, but if you can tell me where and what... :)

**Comment by paulushub** [comment]
@JeremyBP You can replace the `highlight.js` and/or style the code section. DocFX uses [highlight.js](https://highlightjs.org), which for speed limits the customization features. 
### Custom Usage
Source: https://highlightjs.readthedocs.io/en/latest/readme.html
> If you need a bit more control over the initialization of Highlight.js, you can use the 
> [highlightElement](http://highlightjs.readthedocs.io/en/latest/api.html#highlightelement) and 
> [configure](http://highlightjs.readthedocs.io/en/latest/api.html#configure) functions. 
> This allows you to better control what to highlight and when.
