### ISSUE TITLE
[Question] How to add external link reference for parameter

### ISSUE THREAD

**Issue by MiTschMR** [dotnet/docfx#7896]
**Operating System**: Windows

**DocFX Version Used**: 2.59.0

**Template used**: UnityFX

**Steps to Reproduce**:

1. Make a new Unity Project
2. Write a script that uses a GameObject as a parameter (i.e. DoSomething(GameObject target))

Because UnityEngine.GameObject is an external namespace, I would like to add a link to the original documentation, which is hosted by Unity itself. However, because I don't know DocFX that well, I don't know how to add an external link reference to this documentation page for it? Do I have to use the overrife file method? 

I have added an UnityEngine.GameObject.md file with the following content: 

```
---
uid: UnityEngine.GameObject
href: https://docs.unity3d.com/ScriptReference/GameObject.html
---
```

Am I doing it wrong? If yes, how would I need to do it? Any guidance is very much appreciated!

**Comment by KalleOlaviNiemitalo** [comment]
Seems you can use [xrefmap](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-map-file) for this. Someone did that in <https://github.com/NormandErwan/ArucoUnity/commit/36151ca5993d8fc57d9fbcbf68c6b54dd7500eb0>.

**Comment by KalleOlaviNiemitalo** [comment]
Also <https://github.com/NormandErwan/UnityXrefMaps>

**Comment by MiTschMR** [comment]
The second one worked perfectly, thank you very much for the quick answer!
