### ISSUE TITLE
Generate additional word-break opportunities in TOC

### ISSUE THREAD

**Issue by mikernet** [dotnet/docfx#7911]
The TOC would look much nicer if `<wbr>` elements were inserted after each dot seperating nested class names. For example:

![image](https://user-images.githubusercontent.com/1700111/155875813-0fe49c87-8a5e-41a4-a4a0-645726a52b10.png)

If I manually add `<wbr>` after every dot in chrome F12 dev tools, it wraps like:

![image](https://user-images.githubusercontent.com/1700111/155875943-873f7940-715c-49ac-960c-dcd281ee707b.png)

This would also help longer nested class chains from being cut off on the right side sometimes since right now it won't break on the dots.

**Comment by mikernet** [comment]
I figured putting something this into  `toc.extension.js` would do it but it doesn't seem to work:
```js
exports.preTransform = function (model) {
  transformItem(model);
  return model;

  function transformItem(item) {
    if (item.name)
      item.name = item.name.replace(".", ".\u200B"); // insert zero-width spaces after dots

    if (item.items && item.items.length > 0) {
      var length = item.items.length;
      for (var i = 0; i < length; i++) {
        transformItem(item.items[i]);
      };
    }
  }
}
```

Any idea what I'm doing wrong? I changed `".\u200B"` to `"XYZ"` to see if the replace is working at all and it doesn't seem to be.

**Comment by mikernet** [comment]
Okay...I figured out the problem...the memberpage plugin overrides `toc.html.js` and it does not call `preTransform` / `postTransform` in `toc.extension.js`.

Hmmm...not sure the best way to go about this now.

**Comment by KalleOlaviNiemitalo** [comment]
Is it better to break before the dot or after the dot?

**Comment by mikernet** [comment]
docs.microsoft.com breaks after so I just followed suit.

**Comment by mikernet** [comment]
Not gonna lie....I kinda like it before though:

![image](https://user-images.githubusercontent.com/1700111/155880631-af84504f-c8cc-4547-a16c-957af1427748.png)

**Comment by mikernet** [comment]
For comparison:

![image](https://user-images.githubusercontent.com/1700111/155880702-7076a35f-3d4e-45ab-a9cd-a725ce49bfb5.png)

**Comment by mikernet** [comment]
I think what I ultimately want is memberpage not to break `toc.extension.js` so that I can pre/post-process items myself on top of what memberpage does. There are other things I want to do (i.e. filter out explicit interface implementations from the list of methods in the TOC) and it would be nice to be able to do that without completely overwriting the `toc.html.js` file.

**Comment by mikernet** [comment]
This looks completed to me in new versions.
