### ISSUE TITLE
Unable to install docfx via homebrew on macOs (Apple silicoln)

### ISSUE THREAD

**Issue by sethreidnz** [dotnet/docfx#7927]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

MacOS Montery (apple slicoln)

**DocFX Version Used**: 

Trying to install latest with `brew install docfx`

**Steps to Reproduce**:

1. Install Mono using the official mac installer (latest verion 6.12.0.122)
2. Run `brew install docfx`
3. 

**Expected Behavior**:

That the mono instalation would not be necesary as I already have it installed as per docfx install guide.

**Actual Behavior**:

Error message with the following:

```bash
Error: mono: no bottle available!
You can try to install from source with:
  brew install --build-from-source mono
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

# Question

How does one install it manually? I had a look at the currnet version (not the beta) and it has an .exe file but I can't run that on mac no? I'm confused how I can manually install this to get around the issue.

**Comment by godIsAProgrammer** [comment]
I have the same error as you.

**Comment by sethreidnz** [comment]
> I have the same error as you.

What version of MacOS are you using and are you on the new apple silicon?

**Comment by sachag678** [comment]
I also installed mono as per the instructions - by getting it from the Mono Downloads page. I can run mono just fine in terminal. So I wonder if its about the build instructions not being able to find it?

**Comment by sethreidnz** [comment]
> I also installed mono as per the instructions - by getting it from the Mono Downloads page. I can run mono just fine in terminal. So I wonder if its about the build instructions not being able to find it?
> 
> I am using the new apple silicon - using Monteray 12.0.1

I have a theory that it is the Apple silicoln becuase I have a workmate on a mac running it with no problems. There is also this old issue from 2018 that was solved by adding that mono install instruction to the docs. 

https://github.com/dotnet/docfx/issues/2879

But seeing as we have three people still having the issue something must have changed and that seems like it must be the culprit. 

I'm going to test this theory on another silicon mac later today and report back!

**Comment by sethreidnz** [comment]
I can confirm that I have tested this on two different mac's that are both Apple silicon and the same issue. Does not happen on intel Macs.

**Comment by sethreidnz** [comment]
Just a follow up for anyone wondering. This is currently under investigation by Microsoft and is a known issue. HAven't tried it yet myself but perhaps this sort of approach might help in the meantime

https://medium.com/swlh/run-x86-terminal-apps-like-homebrew-on-your-new-m1-mac-73bdc9b0f343

**Comment by yufeih** [comment]
The [v2.60.0](https://github.com/dotnet/docfx/discussions/8334) release runs on .NET Core with support for MacOS and linux without mono.

**Comment by buzzware** [comment]
```dotnet tool install -g docfx``` worked for me
