### ISSUE TITLE
v3 Allow for custom Quote Notes 

### ISSUE THREAD

**Issue by DavidMarquezF** [dotnet/docfx#7939]
**Operating System**: Windows
**DocFX Version Used**: v3

`QuoteSectionNote` extension is hardcoded:

```c#
private readonly List<string> _noteTypes = new() { "[!NOTE]", "[!TIP]", "[!WARNING]", "[!IMPORTANT]", "[!CAUTION]" };
```

It would be nice if the templates could provide these through the context (`token.json` I guess?). Then all the templates would have full control over these properties.

**Comment by KalleOlaviNiemitalo** [comment]
If implemented, this would allow a custom template to recognize `[!TODO]` <https://github.com/dotnet/docfx/issues/6268>.

**Comment by DavidMarquezF** [comment]
Another option would also be to be able to maintain the current tags but allow users to set the titles themselves. I believe this is how docusaurus does it
