### ISSUE TITLE
Search doesn't work correct

### ISSUE THREAD

**Issue by Shaitan1805** [dotnet/docfx#800]
Hey there,

I've got a problem with the fulltext search.
When I type something in the search it shows only "Search Results for 'abc'" without any results.
I mean it should at least show "No results found" but there is nothing.

When I click on some articles and try the search it shows up the results after some attempts.
I can't work with that.

There are about 70 articles at the moment, is that too much for the search, or did I made a mistake in the configuration?

Greetings Shaitan1805

**Comment by qinezh** [comment]
Hi Shaitan1805, I have tried to search results for `abc` or `abz` in https://dotnet.github.io/docfx, and it works just well. Could you give some simple repro steps?

**Comment by Shaitan1805** [comment]
Hi qinezh,

I found out that it takes about 5 seconds when I type something in the searchbar on my documentation page. The problem doesn't appear on the official docfx page.
Could it be, that there was a fix since version 2.4? I didn't find a note in the version section.

**Comment by qinezh** [comment]
I don't think there's a fix about the performance of full text search, but I still suggest you to use the latest version...

**Comment by Shaitan1805** [comment]
We found out, that we were too impatient. 
When we load the page it takes about 1 or 2 seconds till the index.json is loaded. If we wait that time the search works all fine.

Thanks for your help.

Now I only have to fix the encoding problem of the search. I hope to convert the index.json to utf-8 will do the trick for the german special letters :)
