### ISSUE TITLE
Search does not find anything

### ISSUE THREAD

**Issue by schattennarr** [dotnet/docfx#8011]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 
docfx 2.59.2.0 / docfx.console 2.59.2

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. Add `"_enableSearch" :  "true"` to globalMetadata
2. Build and start Project with `docfx build docfx.json --serve` OR using the nuget package to build, then serve
3. Search in the upper right for a function name, like ValidatePhoneNumber or ValidatePhoneNumber*

**Expected Behavior**:

Something shows up when searching, eg. a method name.

**Actual Behavior**:
The Console logs "using Web Worker", however, the search results do not show up, instead the circle is just [spinning around
](https://i.imgur.com/1A68ctM.png), but doesn't find anything.

**Comment by paulushub** [comment]
@schattennarr Check the browser debug console and report any error message.

**Comment by ukrainec45** [comment]
Hi @paulushub 

I am facing the same issue but my docfx versions is **2.57.2**
After typing some query to the search field, the following error is shown in the console:
![image](https://user-images.githubusercontent.com/50486359/197702780-3df839c8-1795-4c37-a4dd-fb8ecfdba5f2.png)
and loading indicator is spinning infinitely.

**Comment by paulushub** [comment]
@ukrainec45 I could not reproduce it. Please try and see if you can reproduce it on the DocFX own documentations:

https://dotnet.github.io/docfx/

**Comment by ukrainec45** [comment]
I investigated this issue, it wasn't related to docfx but with lunr library version.
