### ISSUE TITLE
Declaration is spelled wrong

### ISSUE THREAD

**Issue by rlholden** [dotnet/docfx#8017]
Classes generated by docfx come with the tag **decalaration** instead of **declaration.** For instance:
```html
<h5 class="decalaration">Declaration</h5>
```
The source is in the [CSS file at line 1024 ](https://github.com/dotnet/docfx/blob/0341b6c0e4ec999da8cef6ac50ab720160d09c35/src/docfx.website.themes/default/styles/docfx.css#L1024). Other referenced places that would need to be fixed are:
* [class.tmpl.partial line 24](https://github.com/dotnet/docfx/blob/0341b6c0e4ec999da8cef6ac50ab720160d09c35/src/docfx.website.themes/default/partials/uref/class.tmpl.partial#L24)
* [collection.tmpl.partial line 26](https://github.com/dotnet/docfx/blob/0341b6c0e4ec999da8cef6ac50ab720160d09c35/plugins/Microsoft.DocAsCode.Build.MemberLevelManagedReference/resources/partials/collection.tmpl.partial#L26)
* [namespace.tmpl.partial line 37](https://github.com/dotnet/docfx/blob/0341b6c0e4ec999da8cef6ac50ab720160d09c35/src/docfx.website.themes/default/partials/uref/namespace.tmpl.partial#L37)
* [class.tmpl.partial line 24](https://github.com/dotnet/docfx/blob/0341b6c0e4ec999da8cef6ac50ab720160d09c35/src/docfx.website.themes/default/partials/class.tmpl.partial#L24).

Functionality is not at risk, since the CSS and HTML are both misspelled.

**Comment by yufeih** [comment]
Fixed by https://github.com/dotnet/docfx/commit/86e10ce371fe3d4bc1b7d5f7b1c792d2fa81a327
