### ISSUE TITLE
Links with Anchors in TOC.YML do not highlight in Sidenav when clicked. Breadcrumbs do not work with anchors. 

### ISSUE THREAD

**Issue by gndrew** [dotnet/docfx#8022]
**Operating System**: (`Windows` or `Linux` or `MacOS`) 
Windows

**DocFX Version Used**: 
docfx 2.58.0.0

**Template used**: (`default` or `statictoc` or contain custom template)
Material

**Steps to Reproduce**:

1. Create link to anchor in TOC.yml
2. Generate website via docfx --serve

**Expected Behavior**:
Clicking links to anchors highlights the article in the sidenav and the breadcrumb trail points to the correct location.

**Actual Behavior**:
Nothing is highlighted in the sidenav, and no breadcrumb trail appears. You just see the article and a collapsed sidenav. Removing the anchor from the URL highlights the article correctly.

**Comment by yufeih** [comment]
Fixed in the [new template](https://github.com/dotnet/docfx/releases/tag/v2.63.0)
