### ISSUE TITLE
Best practice - Document microservice architecture

### ISSUE THREAD

**Issue by Vinko90** [dotnet/docfx#8027]
Hey guys,

We would like to start using docfx in production to document a set of C# microservices. Each service is in a dedicated repository in DevOps, our idea was to create a new Doc repository, and with pipeline somehow build a single static website with the documentation of all the services.
We were thinking that for each production pipeline of each project, build the doc file and store it somewhere. Then the Doc repository should fetch and link all of those with theme + global contents. Is it even possible?

Could you please share some idea's on how this can be achieved properly? Thank you :)

**Comment by KalleOlaviNiemitalo** [comment]
AFAIK, DocFX v2 does not support placing HTML files in the same TOC if they were not built in the same DocFX run. You can perhaps do it without help from DocFX, though.

It might be easier to set up the doc repo with a build system that clones the microservice repos to subdirectories of the working tree and runs DocFX on all of the documentation at once. `src/Microsoft.DocAsCode.Common/Git/GitUtility.cs` keeps track of the repositories from which each directory came, so the "Improve this doc" links should still point to the microservice repositories.

**Comment by Vinko90** [comment]
Thank you very much for the info, we will test this out :)
