### ISSUE TITLE
Targeting multiple frameworks member versioning

### ISSUE THREAD

**Issue by BionicCode** [dotnet/docfx#8030]
Is it possible to have docfx generate a table, like in the .NET API reference, that shows the supported frameworks versions of a member, that is part of a multi framework targeting library?

![image](https://user-images.githubusercontent.com/39948423/170492576-87e07d83-c22e-40c2-92a2-c15ec34e487b.png)

**Comment by paulushub** [comment]
> Is it possible to have docfx generate a table, like in the .NET API reference,...

The `DocFx 2` does not directly support this feature, you may have to create your own plugin to handle it.
This is, however, one of features set for `DocFx 3.x`.

**Comment by yufeih** [comment]
Use #2299 to track versioning
