### ISSUE TITLE
QuickStart guide does not specify downloading DocFx 2

### ISSUE THREAD

**Issue by ITR13** [dotnet/docfx#8037]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
N/A

**DocFX Version Used**: 
[Version 3.0.0-beta1.1204+6e13fb0a39](https://github.com/dotnet/docfx/releases/tag/3.0.0-beta1.1204%2B6e13fb0a39)

**Template used**: (`default` or `statictoc` or contain custom template)
N/A

**Steps to Reproduce**:

1. Go to [DocFx homepage](https://dotnet.github.io/docfx/index.html)
2. Click "Get Started" and get sent to the [QuickStartGuide](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html)
3. On step 2 of the guide, download the topmost release from this [github's releases page](https://github.com/dotnet/docfx/releases). At the time of writing this is [Version 3.0.0-beta1.1204+6e13fb0a39](https://github.com/dotnet/docfx/releases/tag/3.0.0-beta1.1204%2B6e13fb0a39)
4. Run `docfx init -q`

**Expected Behavior**:
The guide specifying not to download version 3, or at least specifying that it's for DocFx 2. It'd be nice if DocFx 3 also had a specific error when trying to run docfx init, explaining that it's version 3 not 2.

**Actual Behavior**:
The following error:
```
'init' was not matched. Did you mean 'new'?
'-q' was not matched. Did you mean '-h'?
Required command was not provided.
Unrecognized command or argument 'init'
Unrecognized command or argument '-q'
```

**Additional Notes**
Duplicate of closed issue #7190

**Comment by paulushub** [comment]
@ITR13 [Version 3.0.0-beta1.1204+6e13fb0a39](https://github.com/dotnet/docfx/releases/tag/3.0.0-beta1.1204%2B6e13fb0a39) is **DocFX 3**, and it is in beta - you are on your own if you want to try it. 
This is not the **DocFX 2** you are referring to.
