### ISSUE TITLE
Tools page shows broken link, and cake logo looks wrong

### ISSUE THREAD

**Issue by MikeHingley22** [dotnet/docfx#8093]
**Operating System**: Windows

**DocFX Version Used**: 2.53.9

**Template used**: N/A

**Steps to Reproduce**:

1. Navigate to https://dotnet.github.io/docfx/templates-and-plugins/tools-dashboard.html
2. Notice that the first tool ([DocFxTocGenerator](https://github.com/Ellerbach/docfx-companion-tools))- has a broken image
![image](https://user-images.githubusercontent.com/99718263/178088075-1846dbd2-18cc-41e6-819d-5e9fd2ab6280.png)
3. Notice that the cake tooling logo obscures the text 
![image](https://user-images.githubusercontent.com/99718263/178088086-02919fcc-0dcc-4b36-84ed-108878107d2e.png)
 
**Expected Behavior**:
Page should be readable

**Actual Behavior**:
Page is not looking its best.

**Note** I have a patch for this which I will be submitting shortly

**Comment by paulushub** [comment]
Well, while there fix the template page also:
https://dotnet.github.io/docfx/templates-and-plugins/templates-dashboard.html

The image of the last template covers the name of the template: SingulinkFX.

**Comment by MikeHingley22** [comment]
> Well, while there fix the template page also: https://dotnet.github.io/docfx/templates-and-plugins/templates-dashboard.html
> 
> The image of the last template covers the name of the template: SingulinkFX.

@paulushub - good spot.  I had only seen the tool page - but tools, plugins and template all use the same layout, and my patch fixes the layout (and fixes the teamplate too) - here's what it looks like with the patch applied : 

![image](https://user-images.githubusercontent.com/99718263/178113515-7e732021-f5b2-4441-9bd4-d0b4ea6d8b7b.png)

and here's what we see on live
![image](https://user-images.githubusercontent.com/99718263/178113535-45753b7e-b7c4-4f71-81ae-1ed76706f931.png)

**Comment by paulushub** [comment]
This issue was also reported earlier #7999
