### ISSUE TITLE
"View Source" is not working/showing up in API docs

### ISSUE THREAD

**Issue by tig** [dotnet/docfx#8112]
**Operating System**: `Windows` 

**DocFX Version Used**:  2.59.3.0

**Template used**: (`default` or `statictoc` or contain custom template)

slight tweak to `default`

**Steps to Reproduce**:

See https://github.com/gui-cs/Terminal.Gui

1. Build docs (https://github.com/gui-cs/Terminal.Gui/tree/develop/docfx/build.ps1)
2. View localhost:8080

**Expected Behavior**:

Expect to see "View Source" somewhere in the API docs.

**Actual Behavior**:
<img width="872" alt="image" src="https://user-images.githubusercontent.com/585482/181387618-c038670b-157a-48cb-9dc2-c48bcbd1c306.png">

I'm sure I'm doing something wrong, but can't see what it is. I've read the docfx documentation, and all it says is that I need to have my branch specified in the environment variable. Even with that none of the generated HTML has "Viewsource" or "View Source" anywhere in it...

**Comment by paulushub** [comment]
@tig It seems `_gitContribute` is missing in your `docfx.jon`. Something like
```
"_gitContribute": {
"repo": "https://github.com/gui-cs/Terminal.Gui",
"branch": "develop",
"apiSpecFolder": "apidoc"
}
```
You may also like ` "_gitUrlPattern": "github"`

**Comment by tig** [comment]
Thanks. I tried your suggestions and it's still not working. 

Here's my latest `docfx.json`:

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [
            "Terminal.Gui.dll"
          ],
          "exclude": [
            "**/obj/**",
            "_site/**"
          ],
          "src": "../Terminal.Gui/bin/Release/net6.0"
        }
      ],
      "dest": "api/Terminal.Gui",
      "shouldSkipMarkup": true,
      "properties": {
          "TargetFramework": "net6.0"
      }
    },
    {
      "src": [
        {
          "files": [
            "UICatalog.dll"
          ],
          "exclude": [
            "**/obj/**",
            "_site/**"
          ],
          "src": "../UICatalog/bin/Release/net6.0"
        }
      ],
      "dest": "api/UICatalog",
      "shouldSkipMarkup": false,
      "properties": {
          "TargetFramework": "net6.0"
      }
    }
  ],
  "build": {
    "template": [
      "default",
      "./templates/default"
    ],
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "../docs",
    "globalMetadata": {
      "_enableSearch": "true",
      "_appLogoPath": "images/logo48.png",
      "_disableContribution": false,
      "_gitContribute": {
        "repo": "https://github.com/gui-cs/Terminal.Gui",
        "branch": "develop",
        "apiSpecFolder": "apidoc"
      },
      "_gitUrlPattern": "github"
    },
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "postProcessors": ["ExtractSearchIndex"],
    "noLangKeyword": false,
    "keepFileLink": false
  }
}
```

Still no View Source or Contribute links:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/585482/181411115-777c3507-d7ac-4e62-9453-d0431ade019d.png">

**Comment by paulushub** [comment]
@tig You are possibly out of luck. It seems it does not work with metadata compiled from DLL. On my PC, where I have not experienced the reported Roslyn issue, changing to project file works:

![Terminal Gui](https://user-images.githubusercontent.com/809351/181589426-be73b402-4b51-41ce-bb86-ce5420f6fb89.png)

**Comment by tig** [comment]
Oh well. Thanks for the help!

-cek
Sent via mobile. Expect brevity, typos, and dangerous driving.
________________________________

**Comment by filzrev** [comment]
It seems this issue can be closed.
Because it works as expected when using project-file-based metadata generation.
And latest version of [Terminal.Gui](https://github.com/gui-cs/Terminal.Gui) build document by using projects.

For DLL-file-based metadata generation.
`View Source` link is enabled when using SourceLink and PDB files are available. (Added by #8548)
