### ISSUE TITLE
Cannot generate proper metadata for record structs

### ISSUE THREAD

**Issue by airbreather** [dotnet/docfx#8120]
**Operating System**: `Windows`

**DocFX Version Used**: 2.59.3.0

**Template used**: whatever docfx-seed uses

**Steps to Reproduce**:

1. `git clone https://github.com/docascode/docfx-seed`
2. In `docfx.json`, change `src/DotnetNew/*.csproj` to `DotnetNew/*.csproj`
3. In `src/DotnetNew`, update the .csproj file's `TargetFramework` to `net6.0` and add a record struct.  Examples down below.
4. `docfx docfx.json --serve`
5. Navigate to http://localhost:8080/api/DotnetNew.html

**Expected Behavior**:

You should see the record struct in the list of types.

**Actual Behavior**:

Where it should have been, there's a link to `DotnetNew..html`.

**Sample Files**:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

</Project>
```

```csharp
using System;

namespace DotnetNew
{
    // generates just fine:
    public class Class1
    {
    }

    // generates OK, though it could be better
    public record Class2
    {
    }

    // generates just fine:
    public struct Struct1
    {
    }

    // generates just fine:
    public readonly struct Struct2
    {
    }

    // fails:
    public record struct Struct3
    {
    }

    // fails:
    public readonly record struct Struct4
    {
    }
}
```

**Comment by airbreather** [comment]
A workaround might be to build first and do this for the `metadata`:
```json
"metadata": [
  {
    "src": [
      {
        "files": ["DotnetNew/**/bin/**/Release/**.dll" ],
        "src": "src"
      }
    ],
    "dest": "obj/api"
  }
],
```
While this also seems to have problems, it's also not the absolute worst...

**Comment by yufeih** [comment]
We now support record structs and other latest C# features in the latest version.
