### ISSUE TITLE
which version should i use

### ISSUE THREAD

**Issue by raisr** [dotnet/docfx#8127]
I see that version 2 is still under development but there is also a beta of version 3. As far as i can see the v3 was announced a long time ago. So i'm not sure which one i should use. We want to create a huge documentation site for our c# division. Any advice?

**Comment by paulushub** [comment]
> I see that version 2 is still under development

Version 2 is basically in maintenance mode.

> but there is also a beta of version 3.

Version 3 release plan is not public. So, you cannot easily plan with this.

API Reference documentations of your codes will not change, regardless of the version you use - the contents and presentation will change.
The Markdown conceptual documentation is still supported. 
So the transition from 2 to 3, even if there is no migration tool provided should not be difficult to handle.

> We want to create a huge documentation site for our c# division. Any advice?

There is really not much choice here. If your documentation project can wait for the Version 3, then you have not problem.

Well, you can download the Version 3 beta and try it. It builds the conceptual documentation for me, but I have not yet managed to build an API reference documentation.

My observation, the DocFX team primary job is to build docs.microsoft.com.
