### ISSUE TITLE
DocFX fails with VS 17.3

### ISSUE THREAD

**Issue by asklar** [dotnet/docfx#8141]
> Reported earlier - #8097 
The work around is to use the compiled dll as the source of the metadata.

_Originally posted by @paulushub in https://github.com/dotnet/docfx/issues/8102#issuecomment-1192605506_

I can't use the workaround, becaus in my scenario there is no DLL built - I am building my code as a Windows Runtime Component, so the output is a winmd, not a dll.

**Comment by vers-one** [comment]
There is [another workaround](https://github.com/dotnet/docfx/issues/8136#issuecomment-1219512721) that seems to work for now.

**Comment by yufeih** [comment]
Did you still see the problem with the latest release?
