### ISSUE TITLE
Replace logo.svg with logo.PNG

### ISSUE THREAD

**Issue by ianceicys** [dotnet/docfx#8147]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows
**DocFX Version Used**: 
Latest
**Template used**: (`default` or `statictoc` or contain custom template)
cse
**Steps to Reproduce**:

1. How can I replace the logo.svg with a PNG static image?
2. 
3. 

**Expected Behavior**:
Easily replace the logo with a .png graphic. 
**Actual Behavior**:
Appears only svg is supported.

**Comment by paulushub** [comment]
> Appears only svg is supported.

True, you can wrap the PNG in an SVG file.

**Comment by ianceicys** [comment]
Ah that's helpful. I'll try that.
