### ISSUE TITLE
Docs folder v3 - toc.yml vs TOC.yml

### ISSUE THREAD

**Issue by VaclavElias** [dotnet/docfx#8149]
Not sure if it is intended?

There are 2 same files according Windows, probably ok on Linux.

https://github.com/dotnet/docfx/tree/v3/docs

<img width="851" alt="image" src="https://user-images.githubusercontent.com/4528464/187070002-dd7d1fa4-9bc1-49b3-b579-8e2e4b527a18.png">

**Comment by paulushub** [comment]
> Not sure if it is intended?

Nice observation.
Naturally not intended, but both present the same content so there is no observable effect on the output.

**Comment by yufeih** [comment]
Nice catch! That was a mistake of mine.
