### ISSUE TITLE
Document Private Method

### ISSUE THREAD

**Issue by mehrshad00** [dotnet/docfx#8166]
**Operating System**: Windows

**DocFX Version Used**:  2.59.3

**Template used**: default

**Expected Behavior**:
Hello, I need make document for private method.
**Actual Behavior**:
but I can't make document for private method.

How to fix it?

Thanks

**Comment by ChristianMay21** [comment]
Hi @mehrshad00 - unfortunately I believe docfx is hard-coded to exclude internal and private methods from the documentation. Please see responses in #2561

**Comment by mehrshad00** [comment]
Thanks for answer.
I maked app with c# and fix it.
now docfx for me have private method.

**Comment by mehrshad00** [comment]
> Hi @mehrshad00 - unfortunately I believe docfx is hard-coded to exclude internal and private methods from the documentation. Please see responses in #2561

Thanks for answer.
I maked app with c# and fix it.
now docfx for me have private method.

**Comment by yufeih** [comment]
https://github.com/dotnet/docfx/issues/2561#issuecomment-1033832688 seems to provide a way to configure private methods.

**Comment by mehrshad00** [comment]
> [#2561 (comment)](https://github.com/dotnet/docfx/issues/2561#issuecomment-1033832688) seems to provide a way to configure private methods.

thanks for answer.
i finded a way for fix them.
