### ISSUE TITLE
Menu behavior in multi-version sites

### ISSUE THREAD

**Issue by enzian** [dotnet/docfx#818]
Using the default template and creating a versioned page, the main TOC links to articles from the standard version
### Observed behavior
- on any versioned page (/v1.0/index.html) the headers point to the standard version (/articles etc.) instead of the versioned articles (/v1.0/articles/)
### Files

partial **project.json**

``` json

    "content": [
      {
        "files": [
          "*.md",
          "toc.yml",
          "docs/**.md",
          "docs/**/toc.yml"
        ],
        "src": "../revisions/head/docs/",
        "dest": ""
      },
      {
        "files": [
          "api/**.yml",
          "api/**.json",
          "api/index.md"
        ],
        "src": "../revisions/head/docs/",
        "dest": ""
      },
      {
        "files": [
          "docs/**.md",
          "docs/**/toc.yml"
        ],
        "src": "../revisions/v1.0/docs/",
        "dest": "v1.0",
        "version":"v1.0"
      },
      {
        "files": [
          "api/**.yml",
          "api/**.json",
          "api/index.md"
        ],
        "src": "../revisions/v1.0/docs/",
        "dest": "v1.0",
        "version":"v1.0"
      }
    ],
```

partial main **toc.yml**

``` yml
- name: Documentation
  href: docs/UserDocs/
- name: Operations
  href: docs/OperationsDocs/
- name: Developers
  href: docs/DevDocs/

```
### Expected result
- The TOC in the header should always link to the articles of the active version!

And finally: Thanks to everybody involved (as far as I can tell - @superyyrrzz) for providing multi-version support

**Comment by superyyrrzz** [comment]
Thanks for your support :)
`docfx.json` uses `version` attribute to mark different versions, but it seems not in your sample.

**Comment by enzian** [comment]
Is there any kind of documentation on this? I adapted the code in the issue with the version, but I'm still observing the same behavior!

**Comment by superyyrrzz** [comment]
Sorry there's still no detailed documentation on this. About the header menu, DocFX always chooses the toc in *output root* as nav toc to keep it stable across whole site. In your scenerio, I think you want to choose the toc in *output version root* as nav toc in versioned site. What about providing another property `navRoot` along with `version` to specify it?
BTW, the main menu missing is a bug... I'll fix it.

**Comment by enzian** [comment]
> Sorry there's still no detailed documentation on this.
Ok, so I was not looking in the wrong place! When I've figured this out, I'll gladly lend you a hand in documenting this!

> What about providing another property navRoot along with version to specify it?
Where can I specify this? Or would this need to be implemented?

**Comment by superyyrrzz** [comment]
Great! Your practical using experience is helpful to us. PR is welcomed.

This still need to be implemented, then you can specify it in `docfx.json` like:
```json
      {
        "files": [
          "api/**.yml",
          "api/**.json",
          "api/index.md"
        ],
        "src": "../revisions/v1.0/docs/",
        "dest": "v1.0",
        "navRoot": "v1.0",
        "version":"v1.0"
      }
```

**Comment by enzian** [comment]
That seems like a way to go!

**Comment by enzian** [comment]
i've checked out PR #908 and this looks good! Thank you! When will the next release be, so we can put the change to work? (For now, I guess, I'll build it myself - so no hurry!)

**Comment by superyyrrzz** [comment]
It will ship with DocFX 2.9 on 12/12. For now you should build it or try the prerelease version: https://www.myget.org/feed/docfx-dev/package/nuget/docfx

**Comment by superyyrrzz** [comment]
I create a [test repo](https://github.com/superyyrrzz/testMultiVersion). From [docfx.json](https://github.com/superyyrrzz/testMultiVersion/blob/master/docfx.json), you can find v2.0 uses its own toc as nav toc, while v2.1 use the default one.

**Comment by enzian** [comment]
Awesome! We'll be working with the prerelease package until the release!!

**Comment by enzian** [comment]
checked it out, but it seems, that navigating to a versioned page - for example `/v2.0` still does not display a menu in the header! I'd expected the top items in `/v2.0/toc.yml` (API Documentation) to be rendered in the header, not on the side! Is there any way to acceive this?

**Comment by enzian** [comment]
I'll test it with the 2.9 release and contribute the docs!

**Comment by enzian** [comment]
This seems to work - biiig thumbs up to @superyyrrzz!
