### ISSUE TITLE
Markdown code blocks marked as csharp missing defined syntax highlighting

### ISSUE THREAD

**Issue by TheBoxyBear** [dotnet/docfx#8184]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows 11

**DocFX Version Used**: 
docfx.console NuGet 2.59.4

**Template used**: (`default` or `statictoc` or contain custom template)
SingulinkFX

**Steps to Reproduce**:
1. Create a .NET 6 console project with the docfx.console v2.59.4 NuGet Package
2. Create a markdown with a multi-line C# code block
3. Build and run the site locally

The SingulinkFX provides full syntax highlithing in config.css. Inspecting the resulting HTML, code blocks generated from assembly have their code split into spans with the respective colors applied. Defining a code block such as

```csharp
Console.WriteLine("Hello World");
```
results in `<code class="lang-csharp hljs">` tags with the code left as plain text, rather than being parsed and split into spans. The same happens if `c#` is used instead of `cs` with the code class being `lang-c# hljs` [Actual example of problematic markdown](https://github.com/TheBoxyBear/charttools/blob/stable/Docs/articles/GettingStarted.md)

**Expected Behavior**:
Code in markdown code blocks are parsed and converted into spans with styles applied such as here https://www.singulink.com/Docs/Singulink.IO.FileSystem/articles/guides/getting-started.html

**Actual Behavior**:
Cotents of the code blocks are left are plain text between the opening and closing `<code>` tags, only applying styles for keywords like "new".

**Comment by paulushub** [comment]
@TheBoxyBear I am not sure I understand your issue clearly, but below is a screenshot example of a DocFX output. Is this different from yours?
![codes](https://user-images.githubusercontent.com/809351/191570262-35be0faa-7fa1-41c5-aa21-59158e316103.png)

**Comment by TheBoxyBear** [comment]
From an article ![image](https://user-images.githubusercontent.com/15822255/191584081-d88c8ca6-b381-4303-811d-478e4fed1e5d.png)

Auto-generated for api  ![image](https://user-images.githubusercontent.com/15822255/191584165-9f64cac1-9451-4eb8-9f09-d5e462e6a6d0.png)

In the article, the HTML for the code block is `<code class="lang-csharp hljs">Sont song = Song.FromFile(path); </code>`, unlike the code tags in the api pages and https://www.singulink.com/Docs/Singulink.IO.FileSystem/articles/guides/getting-started.html where elements of the code are seprated into tokens with colors applied to each one.

**Comment by TheBoxyBear** [comment]
![image](https://user-images.githubusercontent.com/15822255/191584835-a1702883-58b6-4f17-98fd-9fe32184cf99.png)

**Comment by TheBoxyBear** [comment]
Not entirely sure if this is a DocFx or template issue. I took a look through the template source files and could not find anything related to code blocks except the color definitions that are applied with the code is split into spans.

**Comment by paulushub** [comment]
The syntax highlighting support is handled by [highlight.js](https://highlightjs.org), which dynamically generate the coloring such as the `<span class="hljs-keyword">public</span>`. If this is what you are referring to, this is a JavaScript generated code so you will not see it in the output HTML file.

If your actual desire is color scheme (try some examples by clicking the `style:` on the sample demo code at [highlight.js](https://highlightjs.org)), then you will have to customize the template with your desired scheme.

**Comment by TheBoxyBear** [comment]
Indeed, they are not present in the generated HTML but do when looking at the final HTML from DevTools. There is still a discrepency with how code blocks are generated between articles and api documentation.

**Comment by TheBoxyBear** [comment]
Seems that now spans do get generated but only for the more complex code. It could be that the blocks I was looking at had no signoficant tokens to be highlighted.

**Comment by paulushub** [comment]
> There is still a discrepency with how code blocks are generated between articles and api documentation.

For the codes in the screenshot I posted, there is no difference in the outputs.

> It could be that the blocks I was looking at had no signoficant tokens to be highlighted.

The level of highlight may also depend on the color scheme, the default may not be that colorful (just click the `style:` I mentioned earlier until you get `style:default` and compare to others). So try the scheme that meets your needs and use it in your custom template.

**Comment by TheBoxyBear** [comment]
None issue. highlight.js handles method bodies different than definition with less elements being identified as tokens. In some cases with simple instructions, nothing is considered a token to highlight which may seem like syntax highlighting not taking place.

**Comment by TheBoxyBear** [comment]
None issue, highlight.js applies no syntax highlighting to things like class references in bodies, methods calls, property calls and variable references. This can cause certain code blocks to appear to not have syntax highlighting while in reality, there is nothing to highlight.
