### ISSUE TITLE
License question Apache 2.0  versus MIT Fsc.fs

### ISSUE THREAD

**Issue by SOesterreicher** [dotnet/docfx#8220]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows
**DocFX Version Used**: 
Various
**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1. Open https://github.com/dotnet/docfx/blob/v2.59.4/src/Microsoft.DocAsCode.Metadata.ManagedReference.FSharp/Fsc.fs
2. See Comment first line: // Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
3. Which license information is correct Apache 2.0 or MIT or can I choose.

**Expected Behavior**:
One license 
**Actual Behavior**:
Two licenses without a clear statement how to handle.

**Comment by yufeih** [comment]
The file was not used by the project and and is removed in https://github.com/dotnet/docfx/commit/eb6072675e00c0a7a0ac97f0b0208b779c4dcc6a
