### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by gggdttt** [dotnet/docfx#8233]
**Operating System**: `windows`

**DocFX Version Used**:  v3

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1. open this page https://github.com/dotnet/docfx/blob/v3/docs/designs/config.md
2.  try to look into the example, but return 404
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by gggdttt** [comment]
👍 Thank you !

**Comment by yufeih** [comment]
Link updated. Thank you!
