### ISSUE TITLE
warning when using default(zh-cn) template

### ISSUE THREAD

**Issue by Memoyu** [dotnet/docfx#8242]
**Operating System:** Windows

**DocFX Version Used:** 2.59.4.0

**Template used:** default(zh-cn)

**Steps to Reproduce:**

Change docfx.json file:
```json
{
   "template": [
      "default(zh-cn)"
    ],
}
```
**Expected Behavior:**
Build succeeded and no warning.

**Actual Behavior:**
Build succeeded with warning.
A warning is 
> [22-11-11 08:36:55.014]Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply 
> Templates]There is no template processing document type(s): Conceptual,ManagedReference,Toc

**Comment by paulushub** [comment]
By my understanding **default(zh-cn)** is not a full template but additional support for language.
So, try something like
```
{
   "template": [ "default", "default(zh-cn)" ],
}
```

**Comment by Memoyu** [comment]
@paulushub
you are right, it is work! thanks!
