### ISSUE TITLE
Possible for offsite content to link to content using xref uid values?

### ISSUE THREAD

**Issue by jamescl604** [dotnet/docfx#8246]
Tried searching and looking through docs, sorry if I missed this.    Our docfx content has uid's, is it possible for other sites to link into our site with just the uid?   Something like site?uid=123456.   If so, I could find the calling convention to use.  Thanks in advance.

**Comment by paulushub** [comment]
> Tried searching and looking through docs, sorry if I missed this. 

Probably not. DocFX only creates **static website**, so for a more controlling routing it will be easier if you provide a serve-side routing as part of your hosting for such stuff as `site?uid=123456`.

**Comment by yufeih** [comment]
Correct, being a static site generator, docfx does have dynamic routing capability.
