### ISSUE TITLE
C# static interface methods shown as explicit interface implementations

### ISSUE THREAD

**Issue by zp-zpanda** [dotnet/docfx#8255]
**Operating System**: `Windows`

**DocFX Version Used**: 2.59.4

**Template used**: `statictoc`

**Steps to Reproduce**:

1. Create a hierarchy using the `static abstract methods on interfaces` feature in C# 11
2. Build and serve

**Expected Behavior**:

The implemented static method belongs to the class.

Other members can `cref` it with `<inheritdoc />`.

**Actual Behavior**:

The method is listed as an explicit interface implementation. It looks a bit confusing by itself, and it just seems inappropriate with `memberpage`.

Other members can't `cref` it with `<inheritdoc />`. Their docs are just empty.

**Notes**:

Somehow IntelliSense works.

**Comment by yufeih** [comment]
We now support C# 11 static interface methods in the latest version.
