### ISSUE TITLE
The Property cannot be searched 

### ISSUE THREAD

**Issue by ZhaodongTian** [dotnet/docfx#8256]
I search property in here  but get nothing. 
![image](https://user-images.githubusercontent.com/25213046/205598268-d9633f25-25c6-408f-9f1b-1e02793bbf80.png)

it looks like only support to search Class .

**Comment by markjulmar** [comment]
Correct, that box is only a _filter_, not a search. For the value to be located, it must be present in the TOC. Since only types are listed, you can only filter on typnames.
