### ISSUE TITLE
Versioned toc.yml shown in wrong position

### ISSUE THREAD

**Issue by MiTschMR** [dotnet/docfx#8258]
**Operating System**: `Windows`

**DocFX Version Used**:  2.59.4

**Template used**: `default` and `material`

**Steps to Reproduce**:

1. Create new default `docfx_project` project with `docfx init -q`
2. Create new folders `v2.0` and `v3.0`
3. Copy paste the api and articles folder as well as the index.md and toc.yml into each of the new version folders
4. Adjust docfx.json file to this: 
```json
{
  "build": {
    "content": [
      {
        "files": "api/*.*",
        "dest": "api"
      },
      {
        "files": "articles/*.*",
        "dest": "articles"
      },
      {
        "files": "api/*.*",
        "src": "v2.0",
        "dest": "v2.0/api",
        "version": "2.0"
      },
      {
        "files": "articles/*.*",
        "src": "v2.0",
        "dest": "v2.0/articles",
        "version": "2.0"
      },
      {
        "files": "api/*.*",
        "src": "v3.0",
        "dest": "v3.0/api",
        "version": "3.0"
      },
      {
        "files": "articles/*.*",
        "src": "v3.0",
        "dest": "v3.0/articles",
        "version": "3.0"
      },
      {
        "files": [
          "index.md",
          "toc.yml"
        ]
      },
      {
        "src": "v2.0",
        "files": [
          "index.md",
          "toc.yml"
        ],
        "dest": "v2.0",
        "version": "2.0"
      },
      {
        "src": "v3.0",
        "files": [
          "index.md",
          "toc.yml"
        ],
        "dest": "v3.0",
        "version": "3.0"
      }
    ],
    "dest": "_site"
  }
}
```
5. Build the project
6. Serve the project

**Expected Behavior**: When browsing to `http://localhost:8080/v2.0/index.html` the TOC is shown (like this image)
![image](https://user-images.githubusercontent.com/47354974/206900234-bdbddb63-6b62-43de-9c68-f482823368fc.png)

**Actual Behavior**: TOC is shown in the wrong location
![image](https://user-images.githubusercontent.com/47354974/206900217-16e3f3a5-daf2-4d8c-af5b-0958e7ad7c93.png)

**Comment by yufeih** [comment]
Versioning is currently not supported by docfx #2299
