### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found.  (again)

### ISSUE THREAD

**Issue by groogiam** [dotnet/docfx#8278]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows 10

**DocFX Version Used**: 

2.59.4.0

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

This issue appears to be back. https://github.com/dotnet/docfx/issues/5554. It happens on my build server which has visual studio 2019 installed for some older builds but also has the latest .NET 6 sdk installed.

1. run `docfx metadata docs\docfx.json`

**Expected Behavior**:
Metadata should be generated.

**Actual Behavior**:
The SDK 'Microsoft.NET.Sdk' specified could not be found.  occurs and no metadata is generated.

SDK installed on the machine having the issue.

3.1.425 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
5.0.415 [C:\Program Files\dotnet\sdk]
6.0.402 [C:\Program Files\dotnet\sdk]
6.0.403 [C:\Program Files\dotnet\sdk]
6.0.404 [C:\Program Files\dotnet\sdk]

**Comment by groogiam** [comment]
I was able to resolve this by installing Visual Studio 2022. Is Visual Studio 2022 required? I don't recall seeing that anywhere in the docs but I may just have missed it.

**Comment by yufeih** [comment]
It might be a bug in [`MsBuildEnvironmentScope`](https://github.com/dotnet/docfx/blob/v2.59.4/src/Microsoft.DocAsCode.Metadata.ManagedReference/MsBuildEnvironmentScope.cs#L86), did you see any console warnings?

**Comment by groogiam** [comment]
@yufeih I did not see that specific warning. It seemed like it was able to find msbuild but for some reason whatever version the VS 2019 version could not read .csproj files.

**Comment by yufeih** [comment]
This is resolved with the latest version.
