### ISSUE TITLE
Add A toggle switch Theme

### ISSUE THREAD

**Issue by JM2K69** [dotnet/docfx#8304]
It would be nice to switch over Theme mode Dark or Light with a toggle or combobox.
For the default Theme docfx-v3

**Comment by JM2K69** [comment]
> @JM2K69 If you add the darkfx theme as a template, then you get this for free:
> 
> Install the theme as per the instructions at https://github.com/steffen-wilke/darkfx.
> 
> Put the following in your docfx.json:
> 
> ```
>     "template": [
>       "default",
>       "templates/darkfx"
>     ],
> ```
> 
> and you get a toggle button switching from light to dark.

Thanks but I need it for docfxv3 @paytools-master

**Comment by paytools-master** [comment]
Ah, sorry @JM2K69, I missed that (possibly as I was under the impression that docfxv3 is no more).

**Comment by JM2K69** [comment]
I know v3 has been discontinued but for now for staticdoc it looks great on me and I love the theme.

**Comment by paytools-master** [comment]
Understood - I understand the team's decision, but it seems a shame that so much MS Learn goodness hasn't made it into DocFX.  I wish I had time to contribute (sadly I don't) as it seems there is nothing else out there even close, but as it stands the mainstream version comes with quite a few frustrations in terms of presentation.  (Please don't take personally DocFX team.)

(I had a go with v3 myself just now but in the absence of any documentation it is just too hard to get going it seems.)

**Comment by JM2K69** [comment]
I will post  a guide for docfx V3 I'have made some change on default theme and a Black theme stay tuned

**Comment by JM2K69** [comment]
@paytools-master  have a look here [Black-theme](https://github.com/JM2K69/Dev-Docfx-Theme-v3-Black) and here [White-theme](https://github.com/JM2K69/Dev-Docfx-Theme-v3-White)

**Comment by yufeih** [comment]
dup of https://github.com/dotnet/docfx/issues/4568
