### ISSUE TITLE
[Feature Request] Global tool .NET 7 support

### ISSUE THREAD

**Issue by Apollo3zehn** [dotnet/docfx#8323]
**Is your feature request related to a problem? Please describe.**
I have only .NET 7 installed on my system (Kubuntu 22.10) by just downloading the SDK. I have also a .NET 6 SDK in a different folder but to make the global tool work I need to do the following:

```bash
sudo rm /usr/bin/dotnet
sudo ln -s /home/<user>/Dokumente/Software/dotnet-6.0/dotnet /usr/bin/dotnet
DOTNET_ROOT=/home/<user>/Dokumente/Software/dotnet-6.0 /home/<user>/.dotnet/tools/docfx metadata
```

And then switch back when done.

**Describe the solution you'd like**
I would be great if the tool is also compiled for .NET 7 so this is not required anymore.

**Additional context**
https://github.com/dotnet/docfx/releases/tag/v2.60.0-preview.2

**Comment by Apollo3zehn** [comment]
Thanks @KalleOlaviNiemitalo! While this in principal works (the build output is generated successfully), it gives me the following warning multiple times:

![grafik](https://user-images.githubusercontent.com/20972129/210778972-4c7f9090-fa0b-4626-8d22-ee70571964de.png)

**Comment by Apollo3zehn** [comment]
Since it happens in a `AssemblyLoadContext` method I guess that a plugin ia being loaded and that this plugin has the Nuget dependency.

**Comment by paulushub** [comment]
> Since it happens in a `AssemblyLoadContext` method I guess that a plugin is being loaded and that this plugin 
> has the Nuget dependency.

I found no instance of the `AssemblyLoadContext` class or the `System.Runtime.Loader` namespace. Which code are you referring to here?
The assembly referencing `NuGet.ProjectModel` and `NuGet.Packaging.Core` compiles successfully after removing them.

**Comment by paulushub** [comment]
> I would be great if the tool is also compiled for .NET 7 so this is not required anymore.

How about using a Docker?

**Comment by Apollo3zehn** [comment]
I am referencing to the stack trace in my screenshot above. I'll make a minimum sample on Monday to see if the error is related to my project targeting multiple frameworks (including .NET 6).

Docker would surely work but I think its a bit overkill and I would first like to understand what's going wrong here.

**Comment by paulushub** [comment]
@Apollo3zehn DocFX for .NET 6.x is just trying to make way for a first release, so .NET 7.x will only add more work now.

Here is few thread on managing multiple .NET Core on Linux, if that will be useful:
https://stackoverflow.com/questions/39233865/how-to-install-multiple-versions-of-net-core-side-by-side-on-ubuntu

Many preferred the Farvashani's answer, which is detailed here
https://devdojo.com/farvashani/how-to-install-multiple-versions-of-net-core-side-by-side-on-linux

**Comment by Apollo3zehn** [comment]
@paulushub Thank you, it worked.
