### ISSUE TITLE
[Feature Request] Pickup Private Serialized Fields

### ISSUE THREAD

**Issue by cookiester34** [dotnet/docfx#8330]
We would like to be able for the generated docs to include private serialized fields not just public fields in C#, I've looked around and not seen any way to do this, Is this already a feature, or could it be one?

**Comment by killeriukas** [comment]
You can create your own plugin and select the properties yourself. Or change the source code to generate it in ManagedReference.

I haven't seen it built-in.

**Comment by filzrev** [comment]
This problem seems to be solved by #8409
