### ISSUE TITLE
[Bug] "Note (Warning/Tip/Important)" Syntax fails to put content into note types

### ISSUE THREAD

**Issue by hollywoodwriter** [dotnet/docfx#8331]
**Describe the bug**
Note format does not display inline text.

**To Reproduce**

1. Create markdown in article and add Note as shown [here](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a)

```
> [!NOTE]
> <note content>
> [!WARNING]
> <warning content>
```

**Expected behaviour** 
The above content will be transformed into HTML with the text "note content" and "warning content"

**Context:** 

- OS: Mac OS Ventura 
- Docfx version: 2.59.5
- NET version: 7.0.101

- mymarkdown.md

> [!NOTE]
> < This text does render but has the bracketss. >

> [!WARNING]
> <This text does not render.>

<img width="740" alt="Screenshot 2023-01-11 at 1 27 05 PM" src="https://user-images.githubusercontent.com/88201243/211900657-93043c8d-b92e-42f7-98e0-4f59d39fc511.png">

**Comment by yufeih** [comment]
Try add a blank line in between the notes, a quota block can only be in one type:

```markdown
> [!NOTE]
> <note content>

> [!WARNING]
> <warning content>
```

**Comment by hollywoodwriter** [comment]
I added a a blank line on line 5 and it displayed the same results.

**Comment by yufeih** [comment]
Are you using the `markdig` engine? Check `docfx.json` for `"markdownEngineName": "markdig"`. [This](https://github.com/dotnet/docfx/blob/main/docs/docs/markdown.md) document seems to be working fine.
