### ISSUE TITLE
missing `docfx.zip` for 2.60.0 release

### ISSUE THREAD

**Issue by chenrui333** [dotnet/docfx#8345]
👋 it looks like `docfx.zip` for 2.60.0 release is missing, not sure if that is intentional, thanks!

**Comment by yufeih** [comment]
Yes, starting from `2.60.0`, docfx is shipped as a .NET tool published to NuGet.org and can be acquired by `dotnet tool install -g docfx`.

**Comment by paulushub** [comment]
It will not hurt to have a portable version, though 😄

**Comment by yufeih** [comment]
> It will not hurt to have a portable version, though 😄

Right, some concrete use cases can help us determine what format to ship and support: should it be operating system dependent or should it be self-contained.

**Comment by paulushub** [comment]
> should it be operating system dependent or should it be self-contained.

I have really not done .NET cross platform, and cannot tell how far the **Any CPU** goes. 
Hoping with your resources, you can pull it off for each platform.  😃 
With the .NET Core, the self-contained will make it more portable.

**Comment by yufeih** [comment]
Zip packages uploaded to the release for 3 supported platforms:
[docfx-linux-x64-v2.60.0.zip](https://github.com/dotnet/docfx/releases/download/v2.60.0/docfx-linux-x64-v2.60.0.zip)
[docfx-osx-x64-v2.60.0.zip](https://github.com/dotnet/docfx/releases/download/v2.60.0/docfx-osx-x64-v2.60.0.zip)
[docfx-win-x64-v2.60.0.zip](https://github.com/dotnet/docfx/releases/download/v2.60.0/docfx-win-x64-v2.60.0.zip)
