### ISSUE TITLE
[Bug] 2.60.0 API download not working

### ISSUE THREAD

**Issue by tlstice** [dotnet/docfx#8351]
**Docfx.zip for v 2.60.0 appears to be empty or doesn't exist and cannot be downloaded/installed.**

To reproduce:

1. Go here [https://api.github.com/repos/dotnet/docfx/releases/latest](https://api.github.com/repos/dotnet/docfx/releases/latest). Note that `assets` seems to be blank.
2. Attempt to download docfx.zip. The file is not found.
3. Go to https://github.com/dotnet/docfx/releases/download/2.60.0/docfx.zip. The file is not found

**Expected behavior**
Latest version of docfx.zip (v.2.60.0) should download.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.60.0
- .NET version: Tried with both .NET SDK 5.0.408(x64) and .NET SDK 6.0.405(x64)

**Comment by yufeih** [comment]
Zip packages uploaded to the release for 3 supported platforms:
[docfx-linux-x64-v2.60.0.zip](https://github.com/dotnet/docfx/releases/download/v2.60.0/docfx-linux-x64-v2.60.0.zip)
[docfx-osx-x64-v2.60.0.zip](https://github.com/dotnet/docfx/releases/download/v2.60.0/docfx-osx-x64-v2.60.0.zip)
[docfx-win-x64-v2.60.0.zip](https://github.com/dotnet/docfx/releases/download/v2.60.0/docfx-win-x64-v2.60.0.zip)
