### ISSUE TITLE
NullReferenceException in MetadataCommand when using global tool

### ISSUE THREAD

**Issue by bkoelman** [dotnet/docfx#8353]
**Describe the bug**
After update to v2.60.1 and running as a global tool instead of installing via choco, the build fails with the next error:
```
[23-01-18 01:09:26.827]Info:[MetadataCommand.ExtractMetadata]Loading projects...
[23-01-18 01:09:27.095]Warning:[MetadataCommand.ExtractMetadata](D:/Bart/Source/Repos/JsonApiDotNetCore/src/JsonApiDotNetCore/JsonApiDotNetCore.csproj)Error opening project D:/Bart/Source/Repos/JsonApiDotNetCore/src/JsonApiDotNetCore/JsonApiDotNetCore.csproj: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.. Ignored.
[23-01-18 01:09:27.097]Warning:[MetadataCommand.ExtractMetadata](D:/Bart/Source/Repos/JsonApiDotNetCore/src/JsonApiDotNetCore.Annotations/JsonApiDotNetCore.Annotations.csproj)Error opening project D:/Bart/Source/Repos/JsonApiDotNetCore/src/JsonApiDotNetCore.Annotations/JsonApiDotNetCore.Annotations.csproj: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.. Ignored.
[23-01-18 01:09:27.110]Info:[MetadataCommand]Completed Scope:MetadataCommand in 391,4043 milliseconds.
[23-01-18 01:09:27.110]Error:Error extracting metadata for D:/Bart/Source/Repos/JsonApiDotNetCore/src/JsonApiDotNetCore/JsonApiDotNetCore.csproj,D:/Bart/Source/Repos/JsonApiDotNetCore/src/JsonApiDotNetCore.Annotations/JsonApiDotNetCore.Annotations.csproj: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.SaveAllMembersFromCacheAsync() in /_/src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs:line 189
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.ExtractMetadataAsync() in /_/src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs:line 109
[23-01-18 01:09:27.113]Info:Completed in 395,3521 milliseconds


Build failed.
```

**To Reproduce**
1. Close the repository at https://github.com/json-api-dotnet/JsonApiDotNetCore
2. Run `dotnet tool install docfx`
4. Run `cd docs`
5. Run `dotnet build .. --configuration Release`
6. Run `dotnet docfx ./docfx.json`

**Expected behavior**
No errors.

- OS: Windows 11 with Visual Studio 2022 v17.4.4
- Docfx version: 2.60.1

**Additional context**
```
> dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
```
> dotnet --list-sdks
7.0.101 [C:\Program Files\dotnet\sdk]
7.0.102 [C:\Program Files\dotnet\sdk]
```

**Comment by yufeih** [comment]
This is likely due to docfx currently shipped as .NET 6 but the project is using .NET 7.

**Comment by bejax** [comment]
Experiencing exactly the same issue as well and I do not think it's related to the project using .NET 7.

Running the following commands reproduce the behavior on my machine, a pretty clean machine with VS 2022 Enterprise 17.4.4 installed on.

```
dotnet tool update docfx -g
docfx init --quiet
md docfx_project\src\ConsoleApp
dotnet new console -f net6.0 -o docfx_project\src\ConsoleApp
docfx "docfx_project\docfx.json" --serve
```

I saw this commit https://github.com/dotnet/docfx/commit/0345f52317e2a6352763e66d651b66aad65bbfb5, which is not released yet (I could be wrong), could it be related?

**Comment by yufeih** [comment]
> I saw this commit https://github.com/dotnet/docfx/commit/0345f52317e2a6352763e66d651b66aad65bbfb5, which is not released yet (I could be wrong), could it be related?

That one hasn't been released yet.

**Comment by bejax** [comment]
> 
> That one hasn't been released yet.

Do you think it could be related to the issue we have?

**Comment by yufeih** [comment]
> Do you think it could be related to the issue we have?

Likely not, https://github.com/dotnet/docfx/commit/0345f52317e2a6352763e66d651b66aad65bbfb5 should be a pure refactor, the `MSBuildLocator` in .NET Core [returns only .NET Core SDKs](https://github.com/microsoft/MSBuildLocator/blob/master/src/MSBuildLocator/MSBuildLocator.cs#L357).

**Comment by yufeih** [comment]
@bejax What does `dotnet --list-sdks` return in your case, does it only contain .NET 7 SDKs?

**Comment by bejax** [comment]
> @bejax What does `dotnet --list-sdks` return in your case, does it only contain .NET 7 SDKs?
Yes seams only .NET 7
```
dotnet --list-sdks
7.0.102 [C:\Program Files\dotnet\sdk]
```

**Comment by yufeih** [comment]
OK, install .NET 6 SDK should workaround the problem. 

`MSBuildLocator` [does not load msbuild newer then the runtime version](https://github.com/microsoft/MSBuildLocator/blob/master/src/MSBuildLocator/DotNetSdkLocationHelper.cs#L54), docfx is current shipped in `net6` and can only build projects using `.NET Core 6 SDK`. 

https://github.com/dotnet/docfx/commit/6d26517252fda1108aa929e2a5abe3e88ada4a77 should fix this.

**Comment by bejax** [comment]
> OK, install .NET 6 SDK should workaround the problem.
> 
Can confirm that installing .NET 6 SDK fixes the problem. 
```
dotnet --list-sdks
6.0.405 [C:\Program Files\dotnet\sdk]
7.0.102 [C:\Program Files\dotnet\sdk]
```
Thanks for your quick response and great work!

**Comment by bkoelman** [comment]
@yufeih @bejax Thanks for looking into this.

> This is likely due to docfx currently shipped as .NET 6 but the project is using .NET 7.

I wonder how you arrived at that conclusion. While my system has the .NET 7 SDK installed, the project sources target .NET 6. See [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/Directory.Build.props#L3-L5):

```xml
    <TargetFrameworkName>net6.0</TargetFrameworkName>
    <AspNetVersion>6.0.*</AspNetVersion>
    <EFCoreVersion>6.0.*</EFCoreVersion>
```

Based on the conversation above, I tried installing the .NET 6 SDK on my system, which fixed the problem.

Would you happen to know if that will still be required in the future? If so, an error message that indicates the missing SDK version would be helpful.

**Comment by yufeih** [comment]
> I wonder how you arrived at that conclusion

My bad, I was meant to say "the project is building using .NET 7 SDK".

> Would you happen to know if that will still be required in the future? If so, an error message that indicates the missing SDK version would be helpful.

This could happen in the future when a newer .NET SDK is released but docfx hasn't adopted it. We could try to minimize the time gap, but yes an error message is very helpful here.
