### ISSUE TITLE
[Bug] Nuget packages not working

### ISSUE THREAD

**Issue by zp-zpanda** [dotnet/docfx#8354]
**Describe the bug**
The Microsoft.DocAsCode.* packages aren't working as expected.

**To Reproduce**
1. Get a docfx project using the new app model (e.g. the one in /samples/extensions)
2. Use Microsoft.DocAsCode.* packages and remove all `<ProjectReference>`s to `Microsoft.DocAsCode.*.csproj`s

**Expected behavior**
Everything builds cleanly.

**Actual behavior**
1. Only `manifest.json` and `xrefmap.yml` are created
2. These errors come up, sometimes as one, sometimes as two or more:
```
There is no template processing document type(s): Conceptual,ManagedReference,Toc
```

**Context (please complete the following information):**
- OS: Windows
- Docfx version: >2.60.0

**Additional context**
This bug appears with any project.

**Comment by yufeih** [comment]
Fixed by https://github.com/dotnet/docfx/commit/255d4ed33c7be6a4d1f944c212a801cfd0210131
