### ISSUE TITLE
[Bug] Constant values all showing as null instead of literal

### ISSUE THREAD

**Issue by mossy2100** [dotnet/docfx#8357]
**Describe the bug**
In the documentation generated for `public const` fields, the value of every constant is shown as `null`, instead of the literal assigned in the code.

e.g.
`public const long YearsPerDecade = null`

instead of 
`public const long YearsPerDecade = 10`

**To Reproduce**
Create a class with a public constant, and assign it a value. It can be any type. Then generate the documentation and browse to that class.

**Expected behavior**
It's misleading to say the constant has a value of null. The literal value from the declaration assignment should be shown.

**Context (please complete the following information):**
- OS: MacOS
- Docfx version: 2.59.4.0

**Additional context**
I tried writing an extension for this, but the values of constants do not appear in the `model` object, so I'm not sure how I can insert the value into a partial.

**Comment by mossy2100** [comment]
I've downloaded and compiled v2.6 and the problem seems to be resolved. The api yml files are now showing the constant values instead of null. BUT no HTML files are being generated. Also, the output folder always has a '/' prepended. I can't seem to specify having output into the same folder as the docfx.json file.

**Comment by yufeih** [comment]
This is fixed in the latest version. Could you give a try and see if it works?
