### ISSUE TITLE
[Bug] Improper Markdown Processing of C# Doc Comments

### ISSUE THREAD

**Issue by WalkerCodeRanger** [dotnet/docfx#8363]
**Describe the bug**
Note, I have simplified my example to highlight the bug. In a C# doc comment, if you include asterisks around something in a code span, it will be improperly converted to italics by docfx.

**To Reproduce**

Doc Comment:
```csharp
/// <remarks><c>*test*<c></remarks>
```
docfx will improperly render this as italics in a code span (i.e. <code><em>test</em></code>) while Visual studio properly renders this as asterisks in a code span (i.e. `*test*`).

**Expected behavior**
docfx should match the behavior of Visual Studio and the fact that XML doc comments are not markdown based and render the example as `*test*`.

**Context:**
- OS: Windows
- Docfx version: docfx.console 2.59.4

**Additional context**
If I try to put `<c>&#42;-&ast;</c>` in, the docfx behavior is the same. None of the other workarounds I have tried have worked.

**Comment by yufeih** [comment]
Try set `shouldSkipMarkup` to `true` to disable markdown XML comments. We probably should disable it by default.

```json
{
  "metadata": {
    "shouldSkipMarkup": true
  }
}
```
