### ISSUE TITLE
Memberpage plugin does not work

### ISSUE THREAD

**Issue by killeriukas** [dotnet/docfx#8389]
**Describe the bug**
Memberpage plugin is not being applied in my case.

**To Reproduce**

Add Memberpage plugin template (from nuget - v2.59.4) into your project and build. The memberpage plugin is not being applied in the ManagedReference build step, hence no member pages are created.

**Expected behavior**
The plugins should be applied during the build step.

**Context (please complete the following information):**
- Form factor: Windows Desktop machine
- Docfx version: v2.61.0 (worked in v2.59.4)
- Template: statictoc + memberpage template (v2.59.4)

**Additional context**
Rolled back to docfx v2.59.4 for now.

**Comment by yufeih** [comment]
Does a setup like in this example work for you? https://github.com/dotnet/docfx/tree/main/samples/extensions

**Comment by yufeih** [comment]
Does a setup like in this example work for you? https://github.com/dotnet/docfx/tree/main/samples/extensions

**Comment by yufeih** [comment]
Does a setup like in this example work for you? https://github.com/dotnet/docfx/tree/main/samples/extensions

**Comment by killeriukas** [comment]
> Does a setup like in this example work for you? https://github.com/dotnet/docfx/tree/main/samples/extensions

This one seems to work fine (although with hundreds of warnings) 🤔 I used the **dotnet run --project build** command instead of using the standard docfx.exe metadata/build as requested in the comments of that link.

Does that mean the plugin needs to be rebuild specifically for v2.61.0? I tried doing that, however, it still didn't pick up for some reason. Though I used the global docfx installed through **dotnet tools update -g docfx**.

**Comment by softworkz** [comment]
Compatibility with plugins is totally messed up for quite a while. With 2.59.2, it took me two days to get the plugins working. I don't remember precisely, but there was a binding-redirect in a plugin that was contradictive to the main code and there were other dependency incompatibilities. 
I had extracted the nuget package, replaced one or two dependency dlls (something like System.Numerics.Vectors, System.Runtime.CompilerServices.Unsafe, Microsoft.CSharp or another of the usual suspects in that area). Then I re-compiled the plugins with lowered (or heightened) dependency versions and put them into the project, re-packed the modified nuget package, put it into a local-folder nuget repository with a nuget.config in the VS solution. 
It works fine with all plugins, also on Azure DevOps and I've sworn to myself to never touch it again :-) 

The source of evil is the use of "dynamic" - in combination with a plugin extensibility model. There two things just do not go well together and it will always be a lottery game whether a plugin version work with a specific host version, even when at the same version that's not granted (e.g. when the build configurations are not synchronized, binding redirects not adjusted - etc.).

The best solution for this IMO would be to always build the plugins alongside the main components and include them in the package directly, then just activate/deactivate by config.

(automated tests for whether the plugins are working might be a good idea as well :-) ).

**Comment by zp-zpanda** [comment]
I've recently migrated to 2.60.x and I want to say that you could only use `<PackageReference />`s. I hope this helps.
Examples:
https://github.com/zp-zpanda/zp.csharp.enigma/tree/09ef0147c910a1f4a4f2e2024c0d25bcb3e2d5b8/ZP.CSharp.Enigma.Docs (docfx directory)
https://github.com/zp-zpanda/zp.csharp.enigma/tree/09ef0147c910a1f4a4f2e2024c0d25bcb3e2d5b8/scripts (helper scripts)
https://github.com/zp-zpanda/zp.csharp.enigma/blob/09ef0147c910a1f4a4f2e2024c0d25bcb3e2d5b8/.github/workflows/docs.yml (github action to publish docs)

**Comment by zp-zpanda** [comment]
Also, versions <2.60.2 are unusable.
Related issue: #8354

**Comment by softworkz** [comment]
Okay - one plugin fixed (the question though: for how long...)

I'm wondering about the other two plugins - weren't they affected? (I don't see similar updated to them)

**Comment by zp-zpanda** [comment]
> Okay - one plugin fixed (the question though: for how long...)
Should be for a long time as the new plugin model would be used for later versions.
> I'm wondering about the other two plugins - weren't they affected? (I don't see similar updated to them)
They should also work as they have also turned to using the model, but I'm not certain as I don't use them.

**Comment by InFTord** [comment]
any update on this? it would be great to able to use newer versions of docfx with memberpage

**Comment by zp-zpanda** [comment]
> any update on this? it would be great to able to use newer versions of docfx with memberpage

See [my reply](https://github.com/dotnet/docfx/issues/8389#issuecomment-1426688854).

**Comment by mikernet** [comment]
Is there an update as to when a memberpage update will be available that works with the newer docfx versions?

**Comment by mikernet** [comment]
@InFTord Thanks but I'm not going to completely restructure docs and redo the doc build process for all our repos. AFAICT what you are referring to involves creating a project with docfx references, building that project and running it. I just need something I can throw into the templates folder and reference in docfx.json as normal.

**Comment by mikernet** [comment]
I pulled `v2.62.1` sources and built them, grabbed the files from: `plugins\Microsoft.DocAsCode.Build.MemberLevelManagedReference\bin\Release\net7.0`

And tried to make those work to no avail - the toc still gets messed up and links beyond the class level do not work. No idea how to get this working.

**Comment by mikernet** [comment]
Pulling the files from the `Microsoft.DocAsCode.Build.MemberLevelManagedReference` nuget package and dropping them into templates also does not seem to work. Not sure what I'm doing wrong though. Tried every combination of folder structures and files I could think of.

**Comment by mikernet** [comment]
The suggestions above don't seem to work for the latest version. when I run the program, I get:
```
C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly.
C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'NuGet.ProjectModel, Version=6.5.0.136, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
```
If I add a package reference to `Nuget.ProjectModel 6.5.0` it complains about not being able to load `Nuget.Frameworks 6.5.0.136`, and I can't get past that one by adding the `Nuget.Frameworks 6.5.0` package reference.

Also tried with a `build.csx` file, same thing:

```cs
#r "nuget: Microsoft.DocAsCode.Build.MemberLevelManagedReference, 2.62.1"
#r "nuget: Microsoft.DocAsCode.App, 2.62.1"
#r "nuget: NuGet.ProjectModel, 6.5.0"
#r "nuget: NuGet.Frameworks, 6.5.0"

using Microsoft.DocAsCode;
using Microsoft.DocAsCode.Dotnet;

await DotnetApiCatalog.GenerateManagedReferenceYamlFiles("docfx.json");
await Docset.Build("docfx.json");
```

**Comment by mikernet** [comment]
Oh wait...probably unrelated. Looks like VS17.5 update nuked my system since the last message, the project just isn't building at all now. Ugh...alright, gonna try to fix that now.

**Comment by mikernet** [comment]
Alright so yeah, got the project building fine through VS and `dotnet build` now, still same problem with this custom docfx thing, both with csx and a net7 console project. I was wrong about the project reference, it complains even if I add the references about not being able to find:
```
NuGet.Frameworks, Version=6.5.0.136
NuGet.Versioning, Version=6.5.0.136
NuGet.ProjectModel, Version=6.5.0.136
```
The messages are all like:
```
[Failure] Msbuild failed when processing the file 'C:\Projects\SL\Singulink.Collections\Source\Singulink.Collections\Singulink.Collections.csproj' with message: C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets: (266, 5): The "ResolvePackageAssets" task failed unexpectedly.
System.IO.FileLoadException: Could not load file or assembly 'NuGet.ProjectModel, Version=6.5.0.136, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
File name: 'NuGet.ProjectModel, Version=6.5.0.136, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 ---> System.IO.FileLoadException: Could not load file or assembly 'NuGet.ProjectModel, Version=6.5.0.136, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromMemory(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

**Comment by mikernet** [comment]
Got it working after a long struggle but....wouldn't it make way more sense to just include `memberpage` as part of `docfx` so that we don't need to keep jumping through hoops to get it working when it breaks each release?
