### ISSUE TITLE
docfx and docfx.msbuild different versions

### ISSUE THREAD

**Issue by msackton** [dotnet/docfx#839]
It appears that the docfx msbuild package on NuGet is version 2.4.0 and the docfx package is 2.6.3. There is a recent fix I am trying to use, but I can't figure out how to use the docfx package from Visual Studio or MSBuild.

Is there a reason the docfx.msbuild package is lagging the main package in release versions? Or is there some way I can use the latest version of docfx in Visual Studio?

**Comment by qinezh** [comment]
docfx.msbuild is deprecated, you could try [docfx.console](https://www.nuget.org/packages/docfx.console/) instead.

**Comment by Phrohdoh** [comment]
Could someone make a note on the `docfx.msbuild` nuget package that it is deprecated?

(on a slightly off-topic note, are there _any_ tutorials / docs on using `docfx.console`?)
