### ISSUE TITLE
[Feature Request] How To Add more Alerts style

### ISSUE THREAD

**Issue by JM2K69** [dotnet/docfx#8391]
I Would like to add more **Alerts** **style** but I don't find the good way ?

I found In the `docfx.js`  [Link](https://github.com/dotnet/docfx/blob/6c98ca24adbc134da805dad3a1a6399223e11c2b/templates/default/styles/docfx.js#L57)
```function renderAlerts() {
    $('.NOTE, .TIP').addClass('alert alert-info');
    $('.WARNING').addClass('alert alert-warning');
    $('.IMPORTANT, .CAUTION').addClass('alert alert-danger');
    $('.TEST').addClass('alert alert-test');
  }
```

and I try to add in `docfx.css`

```
.alert-test h5:before {
    content:"\e127"
}
```

Then in my **md file** I add 
```markdown
>[!TEST]

> test new style.....
```
**But it don't work...**

**Comment by yufeih** [comment]
#7939

**Comment by JM2K69** [comment]
@yufeih It would be great to configure CustomAlerts with **docfx.json** or **docfx.yml** with a property like this
```
_CustomAlerts : TODO,ANSWER,....

```
