### ISSUE TITLE
File UID question

### ISSUE THREAD

**Issue by vdecristofaro** [dotnet/docfx#841]
In the documentation available [here ](http://dotnet.github.io/docfx/tutorial/intro_rest_api_documentation.html) I can read:

> A single Swagger API file is considered as a unique REST File containing multiple APIs. 
> The UID(Unique IDentifier) for the File is defined as the combination of host, basePath, info.title 
> and info.version with / as separator. 

What about the UID if the `basePath `is just `/`?

**Comment by hellosnow** [comment]
If `basePathis` is `/`, it would be ignored in `uid`.

The sample below would generate uid as `microsoft.com/Contacts/1.6`
```json
{
  "swagger": "2.0",
  "info": {
    "title": "Contacts",
    "version": "1.6"
  },
  "host": "microsoft.com",
  "basePath": "",
  "schemes": [
    "https"
  ]
}
```

Code logic is here [GetUid](https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Build.RestApi/SwaggerModelConverter.cs#L127).

**Comment by vdecristofaro** [comment]
Actually I have a `/` in basePath like in the following sample:

```
{
  "swagger": "2.0",
  "info": {
    "title": "Contacts",
    "version": "1.6"
  },
  "host": "microsoft.com",
  "basePath": "/",
  "schemes": [
    "https"
  ]
}
```

and this would generate the following uid:  `microsoft.com/Contacts/1.6` (note the double forward slash).
As long as this will work for Overwrite Files I can live with it.
