### ISSUE TITLE
COM Type Libraries \ Interop Assemblies

### ISSUE THREAD

**Issue by jlnewell** [dotnet/docfx#842]
I help author the [Solid Edge SDK Help](https://docs.plm.automation.siemens.com/docs/se/109/api/webframe.html) which is a based on COM type libraries. We use a 3rd party tool that can read the type libraries directly and produce the HTML site. I also author the [Interop.SolidEdge NuGet package](https://www.nuget.org/packages/Interop.SolidEdge) which is the generated Interop Assemblies combined into a single assembly with corresponding intellisense XML. I have been working on learning docfx and am excited about it's potential. I understand that docfx was not built for this since it reads from .NET source code. 

My question is, do you see any possible path for me to leverage what docfx has to offer in this scenario? I can think of two possible solutions. Keep in mind that I'm still learning and my assumptions may be off.

1. Write custom code that reads Interop.SolidEdge.dll\Interop.SolidEdge.xml and produces metadata (similar to 'docfx metadata') that 'docfx build' could use to generate the site.
2. Fork the docfx repository and implement the feature myself.

Any and all ideas are welcome. Thank you so much!

**Comment by vwxyzh** [comment]
@jlnewell, we will support generate metadata from dll and xml file.
But this feature is NOT in current plan.
Personally, I think it will be available after 2 or more months.

**Comment by vicancy** [comment]
Extract from dll is supported now.
