### ISSUE TITLE
[Bug] Update from 2.59.2 to 2.61.0 or above is broken for Generate from source code

### ISSUE THREAD

**Issue by kevingostomski** [dotnet/docfx#8436]
**Describe the bug**
I wanted to migrate the Docfx Version from 2.59.2 to 2.62.x now, because the .NET Core version is released and I wanted to upgrade the tool. I generate API Documentation for two projects via source files (.cs files). Creating Metadata with the `docfx.json` from version 2.59.2 does not work for version 2.62.x because of #8429. When using version 2.61.0, metadata can be created and the build command works also. Now, there is a problem with the output. No HTML files will be created for public Methods inside the class files. In version 2.59.2, they are inside the output but with the 2.61.x or above version, they are missing. To reproduce this, I provide a .zip file, with the setup so it can be debugged. I do not think I am the only person with this problem, but it seems like not many people using the source files and I do not find any examples or other issues related with this problem. Many just use the .dll or .csproj but than I do need to provide a big filterContent.yml file so I get only the output I want. When not using the Plugin Memberpage or Singulinkfx, it still does not work. With both plugins, it also does not work like the setup provided.

**To Reproduce**
1. Download [API-Doc.zip](https://github.com/dotnet/docfx/files/10795225/API-Doc.zip)
2. Navigate to folder and call `docfx`
3. `docfx serve _site`
4. Navigate to localhost:8080

**Expected behavior**
When clicking on the name of the method from an API, information like in version 2.59.2 should be given, but it does not appear because the html for the methods does not get created.

### Working in version 2.59.2
<img width="1786" alt="grafik" src="https://user-images.githubusercontent.com/78415305/220395490-24840d8e-b5e9-451d-b9af-50ae12ae9d5e.png">

### Not working in version 2.61.0
<img width="1498" alt="grafik" src="https://user-images.githubusercontent.com/78415305/220398676-55ddf6ec-017f-4a62-810b-0831a0a1318c.png">

**Context (please complete the following information):**
- OS: Windows
- Docfx version: [e.g. 2.61.0 and above]

**Additional context**
To see the difference, why it is not working, I checked the output and did not find the html files for the methods. Expected output or a similar should be this one from version 2.59.2 where I see the html for the methods:  [Docfx_Doc-output-with-2.59.2.zip](https://github.com/dotnet/docfx/files/10795291/Docfx_Doc-output-with-2.59.2.zip)

I actually do not know which Docfx version broke it because I did not test it currently but I would say probably since the release of the .NET Core version, this "bug" exist. I think this is not the expected behavior.

**Comment by yufeih** [comment]
dup of #8429
