### ISSUE TITLE
[Bug] markdig doesn't handle overwrite files with multiple sections

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#8441]
**Describe the bug**

Overwrite files with multiple sections that work with `dfm` fail with `markdig` as the Markdown engine.

**To Reproduce**
1. Install docfx 2.60.2 as a dotnet tool (globally or locally)
2. Extract the attached zip file and cd into the OverwriteBroken directory
3. Run dotnet build
4. Run dotnet docfx metadata
5. Run dotnet docfx build
6. Run dotnet docfx serve _site
7. Browse to http://localhost:8080/api/OverwriteBroken.Library.html

The important part is the overwrite.md file:

```text
---
uid: OverwriteBroken.Library
summary: *content
---

Overwritten library description.

---
uid: OverwriteBroken.Library.Method
summary: *content
---

Overwritten method description.

---
```

**Expected behavior**

The class comment and method comment are overwritten normally, and shown as below. This is the result when using dfm.

![Correct documentation](https://user-images.githubusercontent.com/17011/220871389-9f3e1c9f-4f1c-40e2-843c-67ad0aed6fe0.png)

**Actual behavior**

When using markdig, it looks like the method overwrite is being treated as part of the class overwrite, leading to a ghastly mess of documentation:

![Broken documentation](https://user-images.githubusercontent.com/17011/220875382-4798d62e-4469-4101-9545-b190e463d704.png)

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: I suspect any using Markdig, but it's definitely still failing in 2.62.1

**Additional context**

It's possible that there's a different way of writing multiple sections in a single Markdown overwrite file which will work with markdig (and ideally *also* work with dfm). However, I haven't found a test for this, and it's unhelpful that the [overwrite files documentation](https://dotnet.github.io/docfx/tutorial/intro_overwrite_files.html) only gives an example with a single entry.

**Comment by jskeet** [comment]
Oops, failed to attach the zip file before:

[OverwriteBroken.zip](https://github.com/dotnet/docfx/files/10812483/OverwriteBroken.zip)

**Comment by jskeet** [comment]
@KalleOlaviNiemitalo: Doh, thanks for pointing that out. Not sure how I managed to miss that when reading the documentation multiple times. (Although the docs should now say "You should specify `"markdownEngineName": "dfm"` in `docfx.json`" now that Markdig is the default.)

If Markdig is going to be the default and dfm is removed in the future, that's a big feature gap IMO. We generate *hundreds* of overwrite sections - I really, really don't want to have to generate them as separate files in the future.

**Comment by jskeet** [comment]
(I'm happy for this issue to be renamed/relabeled as a feature request, given that it's a documented feature gap... but I think it should stay open until it's resolved, given that it's a significant feature regression.)

**Comment by jskeet** [comment]
@KalleOlaviNiemitalo: Any of those would work for me other than the last one. Just so long as the result isn't "Working as intended, we'll just remove this functionality and pretend it isn't significant."

I would note that for my *specific* use, having to have a different format for Markdig to the existing one would be unpleasant, as our docs end up being built by different systems on different versions of docfx, but that's more of an internal thing to resolve.

**Comment by yufeih** [comment]
I created a PR to markdig to see if they would accept such change.
