### ISSUE TITLE
[Bug] Redirecting with redirect_url produces no redirect and invalid markup

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet/docfx#8462]
**Describe the bug**

`redirect_url` does not appear to work as expected in markdown files. Instead, it generates a blank page with a back-tick in place of the body.

**To Reproduce**

*  In a `.md` file, use the guidance in the [release notes from docfx v2.61.0](https://github.com/dotnet/docfx/releases/tag/v2.61.0) and use the `redirect_url` markup only, e.g.:

```
---
redirect_url: https://SeanKilleen.com
---
```

* Generate the site as normal.

For a specific code branch experiencing this, see: https://github.com/nunit/docs/pull/736 -- it uses 2.62.1 (can reproduce using a Github Codespace if you want; it runs in a dev container which also uses docfx 2.62.1)

**Expected behavior**

* A redirect page should be generated.
* When visiting that page, it should redirect.

**Actual Behavior** 

* A page is generated
* However, instead of a `<body>` tag, there is a single backtick between the end of the `<head>` tag and `</html>`, e.g.:

```
  </head>
  `</html>
```

**Context (please complete the following information):**
- OS: Reproduced on Windows 11 & Ubuntu Jammy 
  - (both using .NET 6 and .NET global tool; Ubuntu Jammy is within a dev container)
- Docfx version: v2.62.1

**Comment by yufeih** [comment]
The `redirect_url` is implemented in the HTML template at the moment, for customized templates, change [this file](https://github.com/nunit/docs/blob/master/docs/custom_template/partials/head.tmpl.partial) to match [here](https://github.com/dotnet/docfx/blob/main/templates/default/partials/head.tmpl.partial#L6) should workaround the problem.

**Comment by SeanKilleen** [comment]
AH, thank you @yufeih! My confusion was because I'd completely forgotten that we were overriding the default template for that file. Sorry for the false report! I really appreciate your help.
