### ISSUE TITLE
[Feature Request] Support for Markdown code blocks in C# XML comments

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#8468]
**Is your feature request related to a problem? Please describe.**

We generate libraries from [protobuf API definitions](https://github.com/googleapis/googleapis) which have comments in Markdown.
The libraries include the comments from Markdown directly in summary/description tags, with minimal XML escaping.
Sometimes those comments contain text that should be rendered as code blocks.

Unfortunately, it doesn't *look* like that's supported at the moment - at least, I can't get it to work.

**Describe the solution you'd like**

Consider the following code:

```csharp
namespace CodeBlocks;

/// <summary>Class summary</summary>
public class Library
{
    /// <summary>
    /// This contains indented code.
    ///
    ///     for (int i = 0; i &lt; 10; i++)
    ///     {
    ///         DoSomething();
    ///     }
    /// </summary>
    public void IndentedCode() {}
    
    /// <summary>
    /// This contains code in a fence.
    ///
    /// ```
    /// for (int i = 0; i &lt; 10; i++)
    /// {
    ///     DoSomething();
    /// }
    /// ```
    /// </summary>
    public void FencedCode() {}
}
```

And a simple docfx.json:

```json
{
  "metadata": [{
    "src": [{ "files": ["CodeBlocks.csproj"]}],
    "dest": "api",
  }],
  "build": {
    "content": [{ "files": ["api/**.yml", "api/index.md"] }],
    "dest": "_site",
    "template": ["default"]
  }
}
```

I'd *like* that to display the for loop in the documentation for each method. Unfortunately, at the moment it ends up looking like this:

![Documentation without desired formatting](https://user-images.githubusercontent.com/17011/222770975-c188bd1a-cc19-4123-892a-55e95c2a6f65.png)

As you can see, the indented code doesn't trigger the code block at all, and the fenced code is missing indentation *within* the block. (It also shows the XML escaping - I can fix that in the metadata, although I'd *prefer* not to have to.)

I've tried both `dfm` and `markdig` as Markdown engines.

I *suspect* this is something to do with leading spaces not being preserved, but I don't know anything more than that.

**Comment by yufeih** [comment]
dup of #2623
