### ISSUE TITLE
Example of Overwrite Files usage

### ISSUE THREAD

**Issue by vdecristofaro** [dotnet/docfx#848]
I am trying to use Overwrite Files feature explained [here](http://dotnet.github.io/docfx/tutorial/intro_rest_api_documentation.html#overwrite-files).

I have the following swagger file

```
{
  "swagger": "2.0",
  "info": {
    "title": "MyProject",
    "description": "Documentation of the MyProject API module",
    "version": "1.0"
  },
  "host": "api.myproject.com",
  "basePath": "/cp",
  "schemes": [
    "https"
  ],
  ....
}
``` 

So standing on the documentation, I have created a file named `cp_moreinfo.md` in the same folder as the swagger file (`restapi` folder) with the following content:

```
---
uid: api.myproject.com/cp/MyProject/1.0
---

Further description for My Project API module

```

Then tried to build the doc. The text `Further description for My Project API module` does not appear in  the generated documentation. I have tried with footer and also with API uids but nothing.
Is there something that I am missing out?

**Comment by hellosnow** [comment]
@vdecristofaro in fact the overwrite file need not be in the same `restapi` folder, but need to add this md file to `overwrite` section of `docfx.json` as below:
```
"overwrite": "specs/*.md",
```

REST overwrite sample of `docfx-seed` is here: 
1. [Overwrite section in docfx.json](https://github.com/docascode/docfx-seed/blob/master/docfx.json#L30)
2. [Overwrite file](https://raw.githubusercontent.com/docascode/docfx-seed/master/specs/petstore-operations.md)
3. [Final page](http://docascode.github.io/docfx-seed/restapi/petstore.html)
