### ISSUE TITLE
[Bug] Problem Scroll down content, a class have a lot of method 

### ISSUE THREAD

**Issue by chuongmep** [dotnet/docfx#8486]
**Describe the bug**

**To Reproduce**
1. Go to https://chuongmep.github.io/OpenMEP/api/OpenMEP.ConnectorManager.Connector.html#OpenMEP_ConnectorManager_Connector_Flow_Autodesk_Revit_DB_Connector_
2. View In This Article and can't scroll to end method.
![image](https://user-images.githubusercontent.com/31106432/223453978-5bb7a65e-6e7d-480d-aed5-39d15dfe70f2.png)
3. Try Scroll this : 
![image](https://user-images.githubusercontent.com/31106432/223454340-f4340588-300b-4c01-a8e0-e6fb8c5e6ed3.png)

**Expected behavior**
It allow scroll with alot method

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: 2.59

**Additional context**

**Comment by chuongmep** [comment]
Hi @yufeih, do we need to change default template to have this feature ?

**Comment by yufeih** [comment]
Once we ship the new template, set the docfx.json config to use the modern template similar to here: https://github.com/dotnet/docfx/blob/main/samples/seed/docfx.json#L48

**Comment by chuongmep** [comment]
Nice! , thanks for your information.
