### ISSUE TITLE
[Bug] Template bug Dictionary output with return more than one parameter

### ISSUE THREAD

**Issue by chuongmep** [dotnet/docfx#8488]
**Describe the bug**
https://chuongmep.github.io/OpenMEP/api/OpenMEP.Document.Document.html

**To Reproduce**

![image](https://user-images.githubusercontent.com/31106432/223731341-e6e719a8-d259-4afb-94be-7887731602b2.png)

Method : 
```cs
/// <summary>
    /// Get Document Current
    /// </summary>
    /// <param name="toggle">toggle true to get current document</param>
    /// <returns name="RevitDocument">Document of Revit Project</returns>
    /// <returns name="DynamoDocument">Document of Dynamo Wrap</returns>
    /// <example>
    /// ![](../OpenMEPPage/document/dyn/pic/Document.Current.png)
    /// </example>
    [MultiReturn("RevitDocument","DynamoDocument")]
    public static Dictionary<string,object?> Current(bool toggle = true)
    {
        Autodesk.Revit.DB.Document? RevitDocument = null;
        Revit.Application.Document? DynamoDocument = null;
        if (toggle)
        {
            RevitDocument = DocumentManager.Instance.CurrentDBDocument;
            DynamoDocument = RevitDocument.ToDynamoType();
        }

        return new Dictionary<string, object?>()
        {
            {nameof(RevitDocument), RevitDocument},
            {nameof(DynamoDocument), DynamoDocument}
        };
    }
```
**Expected behavior**
It should be have two parameter output : 
```
 /// <returns name="RevitDocument">Document of Revit Project</returns>
    /// <returns name="DynamoDocument">Document of Dynamo Wrap</returns>
```

**Screenshots**

**Context (please complete the following information):**
- Browser: [e.g. chrome, safari, edge]
- Form factor: [e.g. desktop, mobile]
- Docfx version: [e.g. 2.59.0]
- Template: [e.g. default, statictoc]

**Additional context**

**Comment by yufeih** [comment]
A workaround is to add `xrefService` to docfx.json like [this](https://github.com/dotnet/docfx/blob/main/samples/seed/docfx.json#L50), this should produce the correct result with clickable links.
