### ISSUE TITLE
[Bug]  System.DllNotFoundException on Apple M2

### ISSUE THREAD

**Issue by bartofzo** [dotnet/docfx#8502]
**Describe the bug**
When I try to run DocFX on my machine (Apple Macbook pro with M2 chip) it immediately quits with the following error:

`System.TypeInitializationException: The type initializer for 'Microsoft.DocAsCode.Dotnet.DotnetApiCatalog' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'hostfxr' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/hostfxr.dylib, 0x0001): tried: '/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/hostfxr.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/hostfxr.dylib' (no such file), '/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/hostfxr.dylib' (no such file)
dlopen(/opt/homebrew/Cellar/docfx/2.62.2/libexec/hostfxr.dylib, 0x0001): tried: '/opt/homebrew/Cellar/docfx/2.62.2/libexec/hostfxr.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/docfx/2.62.2/libexec/hostfxr.dylib' (no such file), '/opt/homebrew/Cellar/docfx/2.62.2/libexec/hostfxr.dylib' (no such file)
dlopen(hostfxr.dylib, 0x0001): tried: 'hostfxr.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OShostfxr.dylib' (no such file), '/usr/lib/hostfxr.dylib' (no such file, not in dyld cache), 'hostfxr.dylib' (no such file), '/usr/local/lib/hostfxr.dylib' (no such file), '/usr/lib/hostfxr.dylib' (no such file, not in dyld cache)
dlopen(/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/libhostfxr.dylib, 0x0001): tried: '/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/libhostfxr.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/libhostfxr.dylib' (no such file), '/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/libhostfxr.dylib' (no such file)
dlopen(/opt/homebrew/Cellar/docfx/2.62.2/libexec/libhostfxr.dylib, 0x0001): tried: '/opt/homebrew/Cellar/docfx/2.62.2/libexec/libhostfxr.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/docfx/2.62.2/libexec/libhostfxr.dylib' (no such file), '/opt/homebrew/Cellar/docfx/2.62.2/libexec/libhostfxr.dylib' (no such file)
dlopen(libhostfxr.dylib, 0x0001): tried: 'libhostfxr.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibhostfxr.dylib' (no such file), '/usr/lib/libhostfxr.dylib' (no such file, not in dyld cache), 'libhostfxr.dylib' (no such file), '/usr/local/lib/libhostfxr.dylib' (no such file), '/usr/lib/libhostfxr.dylib' (no such file, not in dyld cache)
dlopen(/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/hostfxr, 0x0001): tried: '/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/hostfxr' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/hostfxr' (no such file), '/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/hostfxr' (no such file)
dlopen(/opt/homebrew/Cellar/docfx/2.62.2/libexec/hostfxr, 0x0001): tried: '/opt/homebrew/Cellar/docfx/2.62.2/libexec/hostfxr' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/docfx/2.62.2/libexec/hostfxr' (no such file), '/opt/homebrew/Cellar/docfx/2.62.2/libexec/hostfxr' (no such file)
dlopen(hostfxr, 0x0001): tried: 'hostfxr' (no such file), '/System/Volumes/Preboot/Cryptexes/OShostfxr' (no such file), '/usr/lib/hostfxr' (no such file, not in dyld cache), 'hostfxr' (no such file), '/usr/local/lib/hostfxr' (no such file), '/usr/lib/hostfxr' (no such file, not in dyld cache)
dlopen(/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/libhostfxr, 0x0001): tried: '/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/libhostfxr' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/libhostfxr' (no such file), '/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App/7.0.0/libhostfxr' (no such file)
dlopen(/opt/homebrew/Cellar/docfx/2.62.2/libexec/libhostfxr, 0x0001): tried: '/opt/homebrew/Cellar/docfx/2.62.2/libexec/libhostfxr' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/docfx/2.62.2/libexec/libhostfxr' (no such file), '/opt/homebrew/Cellar/docfx/2.62.2/libexec/libhostfxr' (no such file)
dlopen(libhostfxr, 0x0001): tried: 'libhostfxr' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibhostfxr' (no such file), '/usr/lib/libhostfxr' (no such file, not in dyld cache), 'libhostfxr' (no such file), '/usr/local/lib/libhostfxr' (no such file), '/usr/lib/libhostfxr' (no such file, not in dyld cache)

   at Microsoft.Build.Locator.NativeMethods.hostfxr_resolve_sdk2(String exe_dir, String working_dir, hostfxr_resolve_sdk2_flags_t flags, hostfxr_resolve_sdk2_result_fn result)
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at Microsoft.DocAsCode.Dotnet.DotnetApiCatalog..cctor() in /private/tmp/docfx-20230308-6088-1c88dtu/docfx-2.62.2/src/Microsoft.DocAsCode.Dotnet/DotnetApiCatalog.cs:line 23
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Dotnet.DotnetApiCatalog.Exec(MetadataJsonConfig config, DotnetApiOptions options, String configDirectory, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context) in /private/tmp/docfx-20230308-6088-1c88dtu/docfx-2.62.2/src/docfx/SubCommands/MetadataCommand.cs:line 35
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context) in /private/tmp/docfx-20230308-6088-1c88dtu/docfx-2.62.2/src/docfx/SubCommands/CompositeCommand.cs:line 50
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args) in /private/tmp/docfx-20230308-6088-1c88dtu/docfx-2.62.2/src/docfx/Program.cs:line 83
Completed in 9,1857 milliseconds

Build failed.

    0 warning(s)
    1 error(s)` 

**To Reproduce**
1. Run docfx via terminal. It immediately exits.

**Expected behavior**
DocFX runs. 

**Context (please complete the following information):**
- OS: MacOS Ventura 13.2.1
- Docfx version: 2.62.2

**Additional context**
DotNet 7.0.100 SDK is installed
The same docfx project ran fine om my old Intel Mac.

**Comment by yufeih** [comment]
I don't have a M2 Mac at hand, does the same issue occur if you create a .NET Core console app, add [`MSBuildLocator`](https://github.com/microsoft/MSBuildLocator), then call `MSBuildLocator.RegisterDefaults()`?

**Comment by bartofzo** [comment]
> 

Unhandled exception. System.InvalidOperationException: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at Program.<Main>$(String[] args) in /Users/bart/RiderProjects/ConsoleApp1/ConsoleApp1/Program.cs:line 5

**Comment by yufeih** [comment]
Consider open an issue for https://github.com/microsoft/MSBuildLocator/ , it seems that `MSBuildLocator` crashes on Apple M2.

**Comment by bartofzo** [comment]
> Consider open an issue for https://github.com/microsoft/MSBuildLocator/ , it seems that `MSBuildLocator` crashes on Apple M2.

Looks like that repo is kind of abandoned. No other workarounds? Kind of stuck here. Is there anybody that succeeded in running docfx on an Apple M1 or M2 machine?

**Comment by yufeih** [comment]
It seems to be a MSBuildLocator and .NET setup problem.

**Comment by nicolaiarocci** [comment]
I'm experiencing the same issue:

```
$dotnet version
7.0.2020

$ docfx docfx_project/docfx.json --serve
System.TypeInitializationException: The type initializer for 'Microsoft.DocAsCode.Dotnet.DotnetApiCatalog' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'hostfxr' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:
etc.
```
