### ISSUE TITLE
[Feature Request] My awesome feature set icon favicon

### ISSUE THREAD

**Issue by chuongmep** [dotnet/docfx#8503]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I want change this icon.
![image](https://user-images.githubusercontent.com/31106432/224595254-671df4fb-d89e-485d-a262-deffbf58aac7.png)

**Describe alternatives you've considered**

some define for change favicon of icon

**Additional context**

**Comment by yufeih** [comment]
due pf #8500
