### ISSUE TITLE
[Bug] Template bug Logo Square Not In Center

### ISSUE THREAD

**Issue by chuongmep** [dotnet/docfx#8520]
**Describe the bug**

This is a problem when we set logo is size Square like 32x32 pixel 

**To Reproduce**
1. Set Logo Square 32x32 pixel
https://chuongmep.github.io/OpenMEP/api/OpenMEP.Element.FlexPipe.html
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31106432/225486376-c7459cdc-215c-4fcb-85d4-d1125d58071c.png)

**Context (please complete the following information):**
- Browser: [e.g. chrome, safari, edge]
- Form factor: [e.g. desktop, mobile]
- Docfx version: [e.g. 2.59.0]
- Template: [e.g. default, statictoc]

**Additional context**

**Comment by yufeih** [comment]
Fixed in the modern template

**Comment by chuongmep** [comment]
@yufeih can I know how long you will publish new version ?

**Comment by yufeih** [comment]
hopefully in a couple of days

**Comment by chuongmep** [comment]
I'm really looking forward to trying out the new features you've worked so hard on, thank you so much.
