### ISSUE TITLE
[Feature Request] Mark Number for Toc

### ISSUE THREAD

**Issue by chuongmep** [dotnet/docfx#8538]
**Is your feature request related to a problem? Please describe.**
My problem is how to can set order number for toc tree Like :
1. Hello 
 1.1. Hello 1 
 1.2. Hello 2
![image](https://user-images.githubusercontent.com/31106432/226380110-95353883-60e5-402c-ae00-53237c714413.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**
At the moment is nothing

**Additional context**

**Comment by yufeih** [comment]
This is achievable with some custom CSS using [css counters](https://blog.logrocket.com/styling-numbered-lists-with-css-counters/).
