### ISSUE TITLE
[Bug] ApplyTemplatePreprocessorError when "namespaceLayout" set to "nested"

### ISSUE THREAD

**Issue by clement-or** [dotnet/docfx#8540]
**Describe the bug**
When using "namespaceLayout": "nested" in the config (which is experimental), an ApplyTemplatePreprocessorError will be thrown because the namespaces' which have more than 1 level of nesting don't have their "type" defined

Error looks something like this:

```
C:\Path\To\Solution\My.Namespace.With.Nesting.yml: error ApplyTemplatePreprocessorError: Error transforming model generated from "api/My.Namespace.With.Nesting.yml" using "ManagedReference.html.primary.js". To get the detailed raw model, please run docfx with debug mode --debug. Error running Transform function inside template preprocessor: Cannot read property 'toLowerCase' of undefined
```

**To Reproduce**
1. Get a .NET project with namespaces that have more than 1 level of namespace nesting
2. Create the docfx project for this solution
3. in the config, set "namespaceLayout" to "nested"
4. `docfx ./docfx.json --serve`

**Expected behavior**
Build successful, serving on localhost:8080

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.63.0

**Additional context**
This is caused because the nested namespaceLayout doesn't generate a type for namespaces that don't have child Types. In the default theme's ManagedReference.html.primary.js, `item.type.toLowerCase()` is called multiple times without checking `item.type` for null.

If anyone stumbles on this error, there is a simple workaround.

**Simple way**
1. Run `docfx template export default -o /path/to/your/templates` which will export the default theme.
2. Download [these files](https://github.com/dotnet/docfx/files/11023968/files.zip), place them at your theme's root 
3. Copy over the following files from the default theme
    * ManagedReference.html.primary.tmpl
    * conceptual.html.primary.tmpl
    * conceptual.html.primary.js
    * conceptual.extension.js
    * common.js

**Manual way**

1. Run `docfx template export default -o /path/to/your/templates` which will export the default theme.
2. If you want to use the default theme, rename the folder to something like "default-new" and replace it in your config.
5. If you're using another theme, copy over the following files from the default theme to the root of your own
    * ManagedReference.html.primary.tmpl
    * ManagedReference.html.primary.js
    * ManagedReference.common.js
    * ManagedReference.extension.js
    * conceptual.html.primary.tmpl
    * conceptual.html.primary.js
    * conceptual.extension.js
    * common.js

6. Add the following code in specified files right after specified line

REPLACE: ManagedReference.html.primary.js:21
```js
  if (model.type && model.type.toLowerCase() === "enum") {
```

REPLACE: ManagedReference.common.js:214
```js
  if (vm.requirements && vm.type) {
```

ADD: ManagedReference.common.js:237
```js
if (!vm.type) {return true;}
```

ADD: ManagedReference.common.js:244
```js
if (!vm.type) {return true;}
```

REPLACE:ManagedReference.common.js:77-79
```js
    } else if (c.type) {
      var type = c.type.toLowerCase();
    } else {
        var type = "";
    }
```

**Comment by yufeih** [comment]
@clement-or It seems you have come up with a fix, would you like to send a PR to incorporate the fix into the default template?

**Comment by clement-or** [comment]
Maybe the fix wouldn't be to modify the template but to define the type of nested namespaces. Imo they should still be typed as namespaces.

**Comment by yufeih** [comment]
@NanoBob looks like we hit another edge case, are you interested in taking a look? It seems in some cases the `type` property isn't set on namespaces.

**Comment by wilkinson-steve** [comment]
A few tips on the above fix by @clement-or above...

It isn't too obvious how Docfx finds templates so just to make it crystal-clear.  For the "Simple way" instructions above, I recommend the following.  I am assuming that your Docfx project is in a folder `docfx_project` and the following commands are being executed **from that folder's parent folder**.  Adjust as appropriate.

For the command `docfx template export default -o /path/to/your/templates`, I suggest using:

```
mkdir docfx_project\templates
docfx template export default -o docfx_project\templates
```

This puts a copy of the `default` template into a `templates` sub-folder within your project.  Next make a folder for the fixes:

```
mkdir docfx_project\templates\nested
```

and copy in to that new `nested` folder the three files downloaded from the link above ([repeated here](https://github.com/dotnet/docfx/files/11023968/files.zip)).

Then copy the other files across:

```
copy docfx_project\templates\default\ManagedReference.html.primary.tmpl docfx_project\templates\nested
copy docfx_project\templates\default\conceptual.html.primary.tmpl docfx_project\templates\nested
copy docfx_project\templates\default\conceptual.html.primary.js docfx_project\templates\nested
copy docfx_project\templates\default\conceptual.extension.js docfx_project\templates\nested
copy docfx_project\templates\default\common.js docfx_project\templates\nested
```

Then get rid of the default template copy: 

```
rd /s /q docfx_project\templates\default
```

Then update your templates section in your docfx.json:

```
    "template": [
      "default",
      "modern",
      "templates/nested"
    ],
```

Et voila.

**Comment by yufeih** [comment]
Is there a minimal repro of the issue? I tried a couple of setups and couldn't seem to repro the problem.
