### ISSUE TITLE
[Bug/Question] Linux installation with 2.63+

### ISSUE THREAD

**Issue by christopheblin** [dotnet/docfx#8542]
**Describe the bug**
In version 2.59.3, there is a single docfx.zip
In version 2.63.0, there are multiple docfx-[arch]-2.63.0.zip

The documentation still says to proceed with `dotnet tool update -g docfx` which does not work on linux

The multi-arch release implies that it should/may work, but maybe in a different way that is not documented...

**To Reproduce**
Run inside a docker `docker run -it mcr.microsoft.com/dotnet/sdk:6.0`
```
root@b0ceaae1b8d3:/# dotnet tool update -g docfx
You can invoke the tool using the following command: docfx
Tool 'docfx' (version '2.63.1') was successfully installed.
root@b0ceaae1b8d3:/# docfx --version
bash: docfx: command not found
root@b0ceaae1b8d3:/# dotnet docfx --version
Could not execute because the specified command or file was not found.
Possible reasons for this include:
   * You misspelled a built-in dotnet command.
   * You intended to execute a .NET program, but dotnet-docfx does not exist.
   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
root@b0ceaae1b8d3:/#

```
The same commands work under my Windows workstation

**Expected behavior**
The documentation should explain how to proceed (the best would be with docker as it is the easiest to repro in CI/CD, but any clear documentation will be good 😄 )

**Additional context**
There are already some issues (ex: #718) in this repo that talks about this (and tell to use mono as a solution)
However, the issues were before 2.63 so this is why I opened this new issue

**Comment by yufeih** [comment]
Seems to be a dotnet-docker bug: https://github.com/dotnet/dotnet-docker/issues/520

**Comment by christopheblin** [comment]
Thanks @yufeih 👍 

For the future reader, after `docker run -it mcr.microsoft.com/dotnet/sdk:6.0` :

```
root@b0ceaae1b8d3:/# dotnet tool update -g docfx
You can invoke the tool using the following command: docfx
Tool 'docfx' (version '2.63.1') was successfully installed.
root@b0ceaae1b8d3:/# docfx --version
bash: docfx: command not found
root@b0ceaae1b8d3:/# /root/.dotnet/tools/docfx --version
docfx 2.63.1+.....
root@b0ceaae1b8d3:/# export PATH=$PATH:/root/.dotnet/tools:$PATH
root@b0ceaae1b8d3:/# docfx --version
docfx 2.63.1+.....
```
