### ISSUE TITLE
[Bug] Morden Template bug GIF image not show

### ISSUE THREAD

**Issue by chuongmep** [dotnet/docfx#8571]
**Describe the bug**

format gif image not show .

**To Reproduce**
1. Go to method add path for gif  : https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEPSandbox/Geometry/Plane.cs/#L25

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31106432/228583848-3b3dafb9-2d84-4445-aee4-41ea4d894f1f.png)

**Context (please complete the following information):**
- Browser: [e.g. chrome, safari, edge]
- Form factor: [e.g. desktop, mobile]
- Docfx version: 2.63.0
- Template:  modern

**Additional context**

**Comment by yufeih** [comment]
Seem to work fine by checking out 22c3abbe4ae2177668f8517af19f4cc177d8f041 and change template to:

```
"template": [
			"default",
			"modern"
		],
```

![image](https://user-images.githubusercontent.com/511355/229025945-4032f14b-7601-4915-b6aa-0e9b3b56f6db.png)

**Comment by chuongmep** [comment]
Hi @yufeih , I changed , but it not work https://github.com/chuongmep/OpenMEP/blob/df3bd03a7d4e016c01e17affa9ab323f27359609/docs/docfx.json#L63-L66

**Comment by chuongmep** [comment]
After check with this problem, I know why, Firefox keep caching too long, just need clear browser and every working now ! Thank you so much.
