### ISSUE TITLE
[Bug] Dark theme on modern blinks/flashes white/light on initial page load

### ISSUE THREAD

**Issue by CodeCasterNL** [dotnet/docfx#8572]
**Describe the bug**
When your machine has dark mode enabled, it tells the browser, which tells the stylesheet. A docfx site, when visited with dark mode (template: modern), will first load in light mode (white), then after 0.05-0.5 second, turn dark. This gives flashbacks to Duckhunt, causing headaches.

**To Reproduce**
1. Go to https://dotnet.github.io/docfx/index.html
2. Have dark mode enabled by your system/browser, or select it
3. Hit `Ctrl`+`F5` or click any of the links in the menu

**Expected behavior**
I would want every page to load in dark

**Context**
- Browser: Firefox, Chromium
- Form factor: desktop
- Docfx version: 2.63.1
- Template: default+modern

**Comment by CodeCasterNL** [comment]
That was quick, thanks!

**Comment by dcporter65** [comment]
I'm running docfx 2.64.0 which has this fix but I still see flashes in dark mode every time I refresh the page or click a link. 

The flashing is more pronounced on sites with a large number of HTML files.

**Comment by VaclavElias** [comment]
I am running the lates `2.65.1` and I can't see any flashing on my test web dark mode. I tried in Chrome and Edge.

https://stride-docs.vaclavelias.com/tutorials/index.html

Do you have any live examples of yours?

**Comment by dcporter65** [comment]
@VaclavElias Thanks. I can see that your site renders correctly. Unfortunately, our stuff is not publicly accessible. I'll try to find you an example of flashes dark mode.

**Comment by dcporter65** [comment]
Apologies. It turns out we had implemented our customization layer incorrectly. We have fixed it and dark mode no longer flashes.

@yufeih You can close this bug again. Thanks
