### ISSUE TITLE
[Bug] Build fails with NotSupportedException when referencing paths outside the root docfx.json directory

### ISSUE THREAD

**Issue by jakraft** [dotnet/docfx#8592]
**Describe the bug**
In previous versions of DocFX, you were allowed to specify relative paths within your docfx.json file which pointed to directories outside the root directory of your docfx.json file. For example, my team references a "common" folder as one our content sources which exists one level up from our docfx.json root directory:

```json
{
    "build": {
      "content": [
        {
          "files": [ "**/*.yml", "**/*.md" ]
        },
        {
          "files": [ "**/*.yml", "**/*.md" ],
          "src": "../common",
          "dest": "common"
        }
      ],
      "resource": [
        {
          "files": [ "Resources/**" ]
        },
        {
          "files": [ "Resources/**" ],
          "src": "../common",
          "dest": "."
        }
      ],
      ...
    }
  }
```

A recent change to docfx broke this behavior, and now docfx will fail to build with the following exception:

```
Error:System.AggregateException: One or more errors occurred. (Relative to path has too many '../'.) ---> System.NotSupportedException: Relative to path has too many '../'.
  at Microsoft.DocAsCode.Common.RelativePath.MakeRelativeTo (Microsoft.DocAsCode.Common.RelativePath relativeTo) [0x0004e] in <6320abb60be94c6fa84b707c33779703>:0 
  at Microsoft.DocAsCode.Common.RelativePath.op_Subtraction (Microsoft.DocAsCode.Common.RelativePath left, Microsoft.DocAsCode.Common.RelativePath right) [0x00006] in <6320abb60be94c6fa84b707c33779703>:0 
  at Microsoft.DocAsCode.Common.FileLinkInfo.Create (System.String fromFileInSource, System.String fromFileInDest, System.String href, Microsoft.DocAsCode.Plugins.IDocumentBuildContext context) [0x00199] in <6320abb60be94c6fa84b707c33779703>:0 
...
```

**To Reproduce**
1. Create a new docset using docfx.
2. Add a new content source which references a folder one level above the root directory using the `../` pattern.
3. Run docfx on the modified docfx.json file. The build will fail with the exception above.

**Expected behavior**
Backward compatibility should be maintained to allow references to folder outside the root directory to avoid requiring large refactors to existing documentation.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.64.0

**Additional context**
This was the change which broke this functionality: https://github.com/dotnet/docfx/commit/cf300b61933725f993f8238e723eafd468a80251#diff-9bd9dfcdd27d8b6b69f2ad54be5d83000ab7b57e10692471c2132e428cd90d09

**Comment by yufeih** [comment]
Is there a minimal repro to help us diagnose the issue? I tried to create a simple resource and markdown file in the `../common` folder but couldn't seem to repro.

**Comment by FaithfulDev** [comment]
It has been a while. Eperiemented with the described scenario, but failed to reproduce the issue. It works with Docfx 2.64.0 and with the current 2.74.1.
