### ISSUE TITLE
Navigation button is missing Toc not the same style

### ISSUE THREAD

**Issue by JM2K69** [dotnet/docfx#8625]
With docfx : 2.65.1 on Windows 11 22H2 22621.1485
Fork the project or Clone it  in doc folder run docfx docfx.json build and launch your broswer on port 8000 and look difference

## The offical site 
![docfx1](https://user-images.githubusercontent.com/17923944/230914144-57af9b8c-9455-41e6-a3e1-6e3beba9e190.png)

## When I build on my workstation **TOC style** are different
![docfx2](https://user-images.githubusercontent.com/17923944/230914593-eb85f290-e181-4c30-a763-649daaa4e659.png)

## And the navigation bar is not present
![docfx3](https://user-images.githubusercontent.com/17923944/230914854-f010339f-c794-4b32-a741-c9ba74682998.png)

**Comment by yufeih** [comment]
This feature has just merged into main branch and hasn't been released yet 😆
