### ISSUE TITLE
[Bug] Modern template - Custom HTML Templates not working

### ISSUE THREAD

**Issue by VaclavElias** [dotnet/docfx#8626]
**Describe the bug**
We should be able to modify certain parts as described here https://dotnet.github.io/docfx/docs/template.html#custom-html-templates

```
partials/footer.tmpl.partial: The footer at the bottom of the page.
partials/affix.tmpl.partial: The right rail.
```
It doesn't work with the `modern` template. It does work with the `default` template.

If fixed, probably the theme selector should be still available.  So the editable footer part should be below? 🤔

**To Reproduce**
The same instructions as here https://dotnet.github.io/docfx/docs/template.html#custom-html-templates 

My `docfx.json`

![image](https://user-images.githubusercontent.com/4528464/230984614-dc44fada-791e-40c0-92d1-045f3c7f3baf.png)

My template folder

![image](https://user-images.githubusercontent.com/4528464/230984747-ad761969-de8c-4aef-a773-81243255ed2d.png)

**Expected behavior**
I should see my custom templates

**Context:**
- Browser: chrome
- Form factor: desktop
- Docfx version: 2.65.1
- Template:  modern

**Comment by VaclavElias** [comment]
I will test it 🙂

**Comment by VaclavElias** [comment]
The workaround footer works. Thanks. I don't need affix and breadcrumb and logo. This can be closed, unless you need to keep it as a reference.

**Comment by yufeih** [comment]
Thank you! I'm a bit cautious to open more extensibility options of the new template at the moment so close this issue.

**Comment by VaclavElias** [comment]
That makes sense! Thank you for introducing the new template anyway. It looks super great!
