### ISSUE TITLE
Question: Is it possible to exchange the Snippet generation for a link?

### ISSUE THREAD

**Issue by xxcuratorxx** [dotnet/docfx#865]
During the generation of html documentation, links to UIDs are converted to, e.g.,
`<a class="xref" href="../metadata/omeClass.html#SomeClass">SomeClass</a>`

Is it possible, either by template or plugin, to exchange this code to something completely different by means of a func

```
string func(string href, string anchor, ??)
{
}
```

**Comment by vwxyzh** [comment]
@xxcuratorxx, how about creating [a post processor](http://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html) to modify output html.

**Comment by xxcuratorxx** [comment]
@vwxyzh, thanks for your suggestion.

This works, but I have to "search and replace" the entries and move any modifications to the former href.

Therefore, I was looking for a way to change the creation rather than modify the result.

However, maybe this is a very specific request and the postprocessor way is sufficient
