### ISSUE TITLE
[Bug] Template bug

### ISSUE THREAD

**Issue by navaddins** [dotnet/docfx#8652]
**Describe the bug**
I set **_disableNavbar** options in "globalMetadata" to hide navigation bar. However, it is still can see the navigation bar. Does it support at **modern** theme or did i use wrongly?

Full docfx.json file
```

{
  "metadata": [
  ],
  "build": {
    "content": [      
      {
        "files": [
          "**/*.md",
          "**/*.yml"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [
      "default",
      "modern"
    ],
    "postProcessors": [],
    "keepFileLink": false,
    "disableGitFeatures": true,
    "globalMetadata": {  
      "_disableNavbar": true
    }
  }
}

```

**To Reproduce**

**Expected behavior**
Hide navigation bar.

**Screenshots**

**Context (please complete the following information):**
- Browser: [e.g. chrome, safari, edge]
- Form factor: [e.g. desktop, mobile]
- Docfx version: [e.g. docfx-win-x64-v2.65.3]
- Template: [e.g. default, statictoc]

**Additional context**
Is it anyway to change the "#" symbol to "link" symbol when we set the link?

![Untitled](https://user-images.githubusercontent.com/33715070/232486135-53c0f599-2c83-4df8-b641-cb82830cc82f.png)

**Comment by yufeih** [comment]
The `_disableNavbar` wasn't yet implemented in modern template, may I understand the use case behind hiding the navbar? Is it to replace the whole header with a different visual?

**Comment by navaddins** [comment]
@yufeih,

Thanks for your information. 
We are not going to replace whole header with a different visual. 
Current modern layout is useful if we have complex documentation such as API, Configuration and so on. It's more on specific for Technical/Developer or advance users. But we need simple and nice layout for end user.  We already shown the TOC at left panel, so we no need to show it at navigation bar again. Of course, we may need to show the navigation bar if we would like to give other information which is not inside the left panel (TOC).

At this moment i used css to hide the navigation bar 

```css
.navbar .navbar-nav {
    display: none;
}

If we can use `_disableNavbar ` in modern template, we can avoid to use CSS.

```
![Simple Layout without nav bar](https://user-images.githubusercontent.com/33715070/233258099-9b8863e7-795a-4a25-9b92-8d2a3198fb0f.png)


![Advance Layout with nav bar](https://user-images.githubusercontent.com/33715070/233258151-64c867a8-877a-409a-ac52-fde9eaecc033.png)

**Comment by yufeih** [comment]
The duplication seems to be caused by placing the main `toc.yml` placed at root directory. The `toc.yml` placing next to `docfx.json` has special meaning and is used to populate the navbar. Does this layout work?

```
|- docfx.json
|- toc.yml  // <-- set this one to empty like the screenshot below
|- docs
    |- toc.yml  // <-- use this one for left TOC
    |- welcome.md
```

![image](https://user-images.githubusercontent.com/511355/233268004-0eccfdaf-f518-4658-8317-d166667f25d4.png)

**Comment by navaddins** [comment]
@yufeih,

Really appreciate your help. I don't see "Dark" mode theme option after I follow your suggestion.

Here is folder structure before make any changes
```yml
📦docfx_project
 ┗ 📂tutorials
   ┣ 📂global
   ┃ ┣ 📜help-and-support.md
   ┃ ┗ 📜learn.md
   ┣ 📂tutorial-1
   ┃ ┣ 📜overview.md
   ┃ ┣ 📜step-1.md
   ┃ ┣ 📜step-2.md
   ┃ ┣ 📜step-3.md
   ┃ ┗ 📜toc.yml
   ┣ 📂tutorial-2
   ┃ ┣ 📜overview.md
   ┃ ┣ 📜step-1.md
   ┃ ┣ 📜step-2.md
   ┃ ┣ 📜step-3.md
   ┃ ┗ 📜toc.yml
   ┣ 📜index.md
   ┣ 📜new-and-plan.md
   ┣ 📜overview.md
   ┣ 📜docfx.json
   ┗ 📜toc.yml
```
This is folder structure after added empty yml

```yml
📦docfx_project
 ┣ 📂tutorials
 ┃ ┣ 📂global
 ┃ ┃ ┣ 📜help-and-support.md
 ┃ ┃ ┗ 📜learn.md
 ┃ ┣ 📂tutorial-1
 ┃ ┃ ┣ 📜overview.md
 ┃ ┃ ┣ 📜step-1.md
 ┃ ┃ ┣ 📜step-2.md
 ┃ ┃ ┣ 📜step-3.md
 ┃ ┃ ┗ 📜toc.yml
 ┃ ┣ 📂tutorial-2
 ┃ ┃ ┣ 📜overview.md
 ┃ ┃ ┣ 📜step-1.md
 ┃ ┃ ┣ 📜step-2.md
 ┃ ┃ ┣ 📜step-3.md
 ┃ ┃ ┗ 📜toc.yml
 ┃ ┣ 📜index.md
 ┃ ┣ 📜new-and-plan.md
 ┃ ┣ 📜overview.md
 ┃ ┗ 📜toc.yml
 ┣ 📜docfx.json
 ┣ 📜index.md
 ┗ 📜toc.yml
```

Here is sample project which is I'm doing.

[docfx_project.zip](https://github.com/dotnet/docfx/files/11300183/docfx_project.zip)

![Before Add yml](https://user-images.githubusercontent.com/33715070/233760258-cac4fe3c-5134-49a1-990b-aa1b1393b506.png)


![After Add yml](https://user-images.githubusercontent.com/33715070/233760276-cb31e7b9-d6ec-428c-8fe8-9117b7791dc1.png)

**Comment by yufeih** [comment]
`2.66.0` is released to address the theme toggle button problem.
