### ISSUE TITLE
[Bug] docfx --serve not working in latest release

### ISSUE THREAD

**Issue by markphip** [dotnet/docfx#8685]
**Describe the bug**
Updated to 2.66.0. When I run the --serve command the build happens but the server does not run. Here is complete output:

```
$ docfx docfx.json --serve
Searching custom plugins in directory /home/vscode/.dotnet/tools/.store/docfx/2.66.0/docfx/2.66.0/tools/net6.0/any/...
6 plug-in(s) loaded.
Post processor ExtractSearchIndex loaded.
Building 63 file(s) in ConceptualDocumentProcessor(BuildConceptualDocument=>CountWord=>ValidateConceptualDocumentMetadata)...
Building 39 file(s) in ResourceDocumentProcessor(ValidateResourceMetadata)...
Building 7 file(s) in TocDocumentProcessor(BuildTocDocument)...
Applying templates to 109 model(s)...
XRef map exported.
Extracting index data from 63 html files
Manifest file saved to manifest.json.
Completed building documents in 1613.6887 milliseconds.


Build succeeded.

    0 warning(s)
    0 error(s)
```

**Expected behavior**
This worked until yesterday's release. I did not see anything in the Release Notes to explain it. Maybe I am supposed to be using a new command now?

**Context (please complete the following information):**
- OS: Linux (in Codespaces)
- Docfx version: 2.66.0

**Comment by markphip** [comment]
It looks like I can do this with two commands. First do a build then run: `docfx serve _site/`

Is this the expected workflow now?

**Comment by yufeih** [comment]
Dup of #8681
