### ISSUE TITLE
[Bug] Modern Template Cannot Disable Breadcrumbs

### ISSUE THREAD

**Issue by moonymachine** [dotnet/docfx#8686]
I cannot seem to disable the breadcrumb bar with the modern template, using docfx version 2.64. I have added `"_disableBreadcrumb": true` to the `"_globalMetadata"` of my docfx.json config. Indeed, using the default template, the expected behavior is observed. However, the breadcrumb bar is not disabled when using the modern template.

**Comment by moonymachine** [comment]
I accomplished my goal for now by modifying layout/_master.tmpl in my custom theme.

**Comment by larswestman** [comment]
Can we get _disableBreadcrumb working in the modern template also (or tips on how to modify the template myself to disable it)? My issue is that the breadcumb shows the wrong path.

**Comment by glopesdev** [comment]
@larswestman @yufeih same here, both this and `_disableToc` seem to be broken in the modern template, which is hindering our migration efforts.
