### ISSUE TITLE
[Bug] Error on unknown command line options (build and help)

### ISSUE THREAD

**Issue by navaddins** [dotnet/docfx#8688]
**Describe the bug**
We can use `--build` and `-h` before v2.66.1. Now, we can't not use those parameters.
Now, we no need to add `--build` parameter if we want to build. But it'll lead to problem if someone already used this parameter in their pipeline.

**To Reproduce**
1.  docfx "x:\xxx\docfx.json" --build
2. docfx -h

**Expected behavior**

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: [v2.66.1]

**Additional context**

![E1](https://user-images.githubusercontent.com/33715070/234448923-662e0d9d-51ae-42bf-ba5b-c4c30696b8cf.png)

![E2](https://user-images.githubusercontent.com/33715070/234448950-f7ef3c2e-9354-4cd8-a2aa-1a9c48fa70cb.png)

**Comment by yufeih** [comment]
The `--build` command line args does not have effect and. Running `docfx xxx/docfx.json` is equivalent to `docfx xxx/docfx.json`. The new error makes it strict that in case a command line arg is unknown.

The `-h` is indeed a bug.

**Comment by Meandron** [comment]
Another thing is: with 2.66.0, you could state "--no-serve", what is not possible anymore with "2.66.1". I'm not sure if this command was even working with "2.66.0" (it read somewhere it was only supported till version 2.66.0), but anyhow, a change of behaviour you won't expect from a bugfix release.

**Comment by Meandron** [comment]
And even worse: -t does not work anymore.... You should test your releases in a better way before actually releasing them

**Comment by yufeih** [comment]
> And even worse: -t does not work anymore.... You should test your releases in a better way before actually releasing them

Does `docfx build -t` work?

**Comment by Meandron** [comment]
Yes, but it won't create technical reference documentation in our case. We call - with 2.66.0:
`docfx <our.json> -t <our_template>`

Somewhere, it's stated `docfx build <json>` and  `docfx <json>' would do the same. We can see a clear difference in behaviour.
