### ISSUE TITLE
[Feature Request] Use the same template directory for all target frameworks in .NET tool package

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docfx#8691]
**Is your feature request related to a problem? Please describe.**
The .NET tool package `docfx` 2.66.0 contains three copies of the same templates: one for each of net6.0, net7.0, and net8.0. These could be unified to save disk space.

```
$ du -s .nuget/packages/docfx/2.66.0
350331  .nuget/packages/docfx/2.66.0

$ du -s .nuget/packages/docfx/2.66.0/tools/*/any/templates/
41469   .nuget/packages/docfx/2.66.0/tools/net6.0/any/templates/
41469   .nuget/packages/docfx/2.66.0/tools/net7.0/any/templates/
41469   .nuget/packages/docfx/2.66.0/tools/net8.0/any/templates/
```

The files in each `templates` directory are identical.

**Describe the solution you'd like**
Have just one `templates` directory in the tree, rather than three copies.
This would reduce the disk consumption by 2 * 41469 KiB = 82938 KiB, which is approximately 23% of the total 350331 KiB.
Package download times could also improve, although the packages should be locally cached anyway.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by filzrev** [comment]
Currently build-in templates don't contains target framework dependent plugin dlls.   
It seems duplicated content files can be removed by explicitly specifying `PackagePath` as `Language- and framework-agnostic:`.

**.nuspec reference document**
https://learn.microsoft.com/en-us/nuget/reference/nuspec#package-folder-structure

https://github.com/dotnet/docfx/blob/e97eb6f388df67e429e44bdb15dcdac74bac447c/src/Microsoft.DocAsCode.App/Microsoft.DocAsCode.App.csproj#L16

Need to add following settings.

`PackagePath="contentFiles\any\any\templates"`

**Comment by filzrev** [comment]
> Change `templates` folder location in docfx.nupkg to shared location.

I've confirmed it can be achieved with following `docfx.csproj` modifications.

``` xml
<PropertyGroup> 
 <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);RewriteDocfxTemplatesPackagePath</TargetsForTfmSpecificContentInPackage>
</PropertyGroup>

<Target Name="RewriteDocfxTemplatesPackagePath" >
  <ItemGroup>
    <TfmSpecificPackageFile Update="@(TfmSpecificPackageFile)"
                            Condition="$([System.String]::new('%(TfmSpecificPackageFile.PackagePath)').StartsWith('tools/$(TargetFramework)/any/templates/'))"
                            PackagePath="$([System.String]::new('%(TfmSpecificPackageFile.PackagePath)').Replace('tools/$(TargetFramework)/any/', ''))" />
  </ItemGroup>
</Target>
```

By using above settings. `/tools/*/any/templates/**`  path is rewritten and packed to  shared location (`/templates/**`).

---

> Add some kind of templates lookup feature for .NET Local/Global Tools.

Currently `templates` directory are searched with following orders.
- `AppContext.BaseDirectory` 
- `docfx.json` directory.
-  Current directory (if directory path is not passed))

https://github.com/dotnet/docfx/blob/e97eb6f388df67e429e44bdb15dcdac74bac447c/src/Microsoft.DocAsCode.Build.Engine/TemplateProcessors/TemplateManager.cs#L45-L61

If it can add extra lookup path (`../../../`) (when running as .NET global/local tools).
`docfx.nupkg` size problem can be reduced.

**Comment by filzrev** [comment]
I've confirmed `docfx` NuGet package size is reduced as expected.

|                      | v2.70.1  |    | v2.70.2  |
|---------------|----------|----|----------|
|  .nupkg size  | 72.95 MB | -> | 51.3 MB  |
|  extracted size | 228 MB   | -> |148 MB   |

**Comment by KalleOlaviNiemitalo** [comment]
This regressed between v2.78.4 and v2.78.5; the `templates` directory is triplicated again.

```
36142   .nuget/packages/docfx/2.78.4/templates
61932   .nuget/packages/docfx/2.78.4/tools/net8.0
59624   .nuget/packages/docfx/2.78.4/tools/net9.0
121556  .nuget/packages/docfx/2.78.4/tools
261457  .nuget/packages/docfx/2.78.4

36722   .nuget/packages/docfx/2.78.5/tools/net10.0/any/templates
96860   .nuget/packages/docfx/2.78.5/tools/net10.0
36722   .nuget/packages/docfx/2.78.5/tools/net8.0/any/templates
97772   .nuget/packages/docfx/2.78.5/tools/net8.0
36722   .nuget/packages/docfx/2.78.5/tools/net9.0/any/templates
96628   .nuget/packages/docfx/2.78.5/tools/net9.0
291260  .nuget/packages/docfx/2.78.5/tools
472963  .nuget/packages/docfx/2.78.5
```

In the history <https://github.com/dotnet/docfx/compare/v2.78.4...v2.78.5>, I don't see any MSBuild project changes that look like they could have caused the regression.  My current hypothesis is that it was caused by some difference between .NET SDK 10 and earlier versions, thus trigged by <https://github.com/dotnet/docfx/pull/10859>.
