### ISSUE TITLE
[Feature Request] enable search for Chinese

### ISSUE THREAD

**Issue by hailiang-wang** [dotnet/docfx#8697]
Currently this site is built with docfx, https://docs.chatopera.com/products/chatbot-platform/index.html
It works great except the search function.

**Describe the solution you'd like**

With the `"_enableSearch": true,`, I can search in chinese.

![screenshot_20230428072427](https://user-images.githubusercontent.com/3538629/235011290-9e01da56-7d00-4c4a-871e-14952878081d.png)

**Describe alternatives you've considered**

During the build steps,  I would like to run command to build search index for the site, how to provide the indices for searching?

**Additional context**

The search experience should behave the same as English.

![screenshot_20230428072612](https://user-images.githubusercontent.com/3538629/235011473-77325945-855b-40e9-afa7-fe0e6b01e2e6.png)

**Comment by yufeih** [comment]
Does changing `"template": ["default", "templates/material"],` --> `"template": ["default", "default(zh-cn)", "templates/material"],` work?

**Comment by hailiang-wang** [comment]
> Does changing `"template": ["default", "templates/material"],` --> `"template": ["default", "default(zh-cn)", "templates/material"],` work?

I haven't tried this approach yet, but I come to a solution:
* built indice for index.json, https://github.com/chatopera/docs/blob/4022d80066d09bc25122a973d5c790dc045f49bb/admin/build.sh#L64
* customize search event on keypressed, https://github.com/chatopera/docs/blob/4022d80066d09bc25122a973d5c790dc045f49bb/assets/styles/docfx.js#L178

* search only with Enter press, because for Chinese input, searching that happens for every char press brings more latency, https://github.com/chatopera/docs/blob/4022d80066d09bc25122a973d5c790dc045f49bb/assets/styles/docfx.js#L261


Now it seems great, you may try the search box here, https://docs.chatopera.com/products/chatbot-platform/index.html

![screenshot_20230428144242](https://user-images.githubusercontent.com/3538629/235073839-5f25ed23-5223-4fc8-b2ee-b0b5e6efd6b5.png)

Thanks for your help anyway, great job in docfx.
