### ISSUE TITLE
[Bug] .NET API bug logging NRE

### ISSUE THREAD

**Issue by Aragas** [dotnet/docfx#8699]
**Describe the bug**
Two logging methods access `MetadataItem.Source` as a non nullable property.
https://github.com/dotnet/docfx/blob/e4157df4939eafd9bd33d1e4d58b2b6bb34f24c3/src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs#L345
https://github.com/dotnet/docfx/blob/e4157df4939eafd9bd33d1e4d58b2b6bb34f24c3/src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs#L356

**To Reproduce**
This is a bit tricky. The code where this is raised seems pretty normal. It's a class without an explicit constructor and with some properties.
```csharp
public class Achievement
{
    public string Id { get; set; }
    // Other props
}
```

**Expected behavior**
From what I saw in the codebase, at least one place assumes that the Source property could be null, so it might be a typo with the logging method. But it does seem strange to have symbols with a null source
https://github.com/dotnet/docfx/blob/e4157df4939eafd9bd33d1e4d58b2b6bb34f24c3/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs#L727

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.66.2
- .NET version: .NET 7.0

- `docfx.json` config
Not needed

- Exceptions
NRE

- Errors and warnings
Not needed

- .NET info
Not needed

**Additional context**
I also checked the `GetSourceDetail` method. It returns null because `syntaxRef` is null.

**Comment by DarkLiKally** [comment]
Getting the exact same error. Same scenario
