### ISSUE TITLE
Simple config for replacing logo

### ISSUE THREAD

**Issue by roji** [dotnet/docfx#873]
#239 describes how to override the navbar partial in order to replace the logo (upper-left corner).

It seems like there should be a much easier config option for doing this - practically every documentation site out there will want to put their project's logo, and overriding template partials is dangerous for compatibility as the template changes. Would you consider docfx global metadata option(s) for managing this?

**Comment by superyyrrzz** [comment]
Yes, we can provide a metadata `_appLogoPath` to replace `logo.svg` [here](https://github.com/dotnet/docfx/blob/27f7f55746dc48f0d7700205c52dff071b51427b/src/docfx.website.themes/default/partials/navbar.tmpl.partial#L13). Then by minor customizing the template to provide your own logo file, you can replace logo while keep the template compatible.

**Comment by superyyrrzz** [comment]
Now in [DocFX 2.8](https://github.com/dotnet/docfx/releases/tag/v2.8), you can use `_appLogoPath` and `_appFaviconPath` in global metadata to customize it.

**Comment by roji** [comment]
@superyyrrzz great! Should I leave this open for tracking splitting out the logo into its own separate partial?

**Comment by superyyrrzz** [comment]
It's also implemented. See: https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/partials/navbar.tmpl.partial#L12

**Comment by roji** [comment]
Oh awesome! Thanks!
