### ISSUE TITLE
[Feature Request] Dynamically load optional template dependencies

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#8742]
Today, the front-end script to process mermaid, MathJs, etc is bundled together in docfx.min.js, which is too big at 6MB. This issue is to track the splitting of the front-end script to only load what is needed for each page.

By splitting the script, we can reduce the size of the bundle that needs to be downloaded by the user, which will improve the overall performance of the site. This change will also allow users to only load the scripts that they need for each page, rather than loading the entire bundle for every page.

**Comment by paulushub** [comment]
How about use of CDN for such third-party libraries?

**Comment by yufeih** [comment]
I am looking at [esbuild code splitting](https://esbuild.github.io/api/#splitting) to automatically split the modules and download only the chunks needed for a given page. This makes it easier to manage, version and type check 3rd party libraries with npm and typescript, and ship minimal js to browser as needed.
