### ISSUE TITLE
[Bug] Unable to find dotnet SDKs on macOS 13.3.1

### ISSUE THREAD

**Issue by wh1337** [dotnet/docfx#8753]
**Describe the bug**
When attempting to run any docfx command other than `docfx init`, it fails stating that it cannot find any SDKs.

**To Reproduce**
1. `docfx init`
2. `docfx`
3. << error >>

```
❯ docfx
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
Completed in 204.5029 milliseconds
Error: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
```

**Expected behavior**
To run docfx commands to build documentation.

**Context (please complete the following information):**
- OS: MacOS 13.3.1
- Docfx version: 2.67.0

**Additional context**
dotnet --list-sdks output:

```
❯ dotnet --list-sdks
7.0.203 [/usr/local/share/dotnet/sdk]
```

Full error message:
```
❯ docfx
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
Completed in 204.5029 milliseconds
Error: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
```

**Comment by yufeih** [comment]
https://github.com/microsoft/MSBuildLocator/issues/210

**Comment by filzrev** [comment]
This issue seems to be resolved in recent docfx version. (By updating MSBuildLocator)
