### ISSUE TITLE
[Bug] Mermaid flowcharts won't generate for tabs

### ISSUE THREAD

**Issue by Lulalaby** [dotnet/docfx#8757]
## Markdown
![md](https://github.com/dotnet/docfx/assets/14029133/5a81fc01-3c14-4b4c-8ce8-9469fb983e92)

## Output
![output](https://github.com/dotnet/docfx/assets/14029133/581b37ab-0a12-46db-b93a-7d9cc4f1b083)

## Solution
Either we modify the code to support this or we add a note that this isn't supported in tabs

**Comment by yufeih** [comment]
The first example in this page is a flow chart https://dotnet.github.io/docfx/seed/articles/markdown.html?tabs=linux%2Cdotnet#mermaid-diagrams . This bug is likely because of using a mermaid chart in a non-default tab.
