### ISSUE TITLE
[Bug] Packages DocFx.Plugins.PlantUml

### ISSUE THREAD

**Issue by pele1983** [dotnet/docfx#8763]
It seems that the latest version of docfx is not executing the Packages DocFx.Plugins.PlantUml any more.
With Version 1.52.x the PlantUML charts are rendered correct.
With the latest version it seems to stop working.

Did any body faced similar issue?

**Comment by cjlotz** [comment]
Any feedback on this?  Any pointers on where to start to update the existing DocFx.Plugins.PlantUml plugin to work with the latest version of docfx?   What are the new extensibility points to override to allow the custom rendering of plantuml code blocks?
