### ISSUE TITLE
[Bug] Affix / In This Article menu does not expand in Modern template

### ISSUE THREAD

**Issue by BradBearden** [dotnet/docfx#8781]
**Describe the bug**
In the modern template, the affix side nav ("In this article" menu) does not expand to show Heading 3 or more. Also, as I scroll down the page it does not highlight the section in the right menu to show my current focus.

**To Reproduce**
Confirmed steps to reproduce the behavior:
1. Create a page with the following headings:
    -   Heading 1 (H1)
    -   Heading 2a (H2)
    -   Heading 2b (H2)
    -   Heading 3a (H3)
    -   Heading 4 (H4)
2. Build your site using the Modern template
3. In the "In This Article" side menu, click on "Heading 2b"

**Expected behavior**
I would expect that clicking on Heading 2b in the "In This Article" section would cause "Heading 3a" and "Heading 4" to be displayed under it, slightly indented. 

I would also expect "Heading 2b" to be highlighted. Likewise, if scrolling through the page, I would expect the sections in that menu to highlight and expand based on my current location in the page. (I believe this has been reported under #8539)

**Screenshots**
![DefaultTemplate](https://github.com/dotnet/docfx/assets/92607087/b02d2383-1c11-471e-9595-9671a9d177e9)

![ModernTemplate](https://github.com/dotnet/docfx/assets/92607087/01002efd-613d-4ed5-a3b9-cf22c50e8c0d)

**Context (please complete the following information):**
- Browser: Chrome
- Form factor: Desktop
- Docfx version: 2.67.0.0 (upgraded from 2.56.2)
- Template: modern

**Additional context**
This may be related to #8539, or it may be a separate issue.

**Comment by lanthonyneville** [comment]
Any news about this?
