### ISSUE TITLE
fileMetadataFiles etc not supported as command line options

### ISSUE THREAD

**Issue by didster** [dotnet/docfx#8787]
**Describe the bug**
According to the docs [here](https://dotnet.github.io/docfx/reference/docfx-json-reference.html#123-separated-metadata-files-for-global-metadata-and-file-metadata) it should be possible to specify options like `globalMetadataFiles` and `fileMetadataFiles` as command line options but doing so gives unknown option --globalMetadataFiles etc.

```
λ docfx build --globalMetadataFiles vars.json docfx.json

Error: Unknown option 'globalMetadataFiles'.

       build --globalMetadataFiles vars.json docfx.json
             ^^^^^^^^^^^^^^^^^^^^^ Unknown option
```

**Expected behavior**
Meta data specified via the command line is used 

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.67.1

**Additional context**
I would like to use this option to specify a version number of the API documentation as _appTitle i.e. `--globalMetadata '{"_appTitle": "My API v1.2.3"}'` rather than having to write out for example a version.json file which is then picked up by config in docfx.json - it seems a common thing to want to do to specify meta data from the command line.

**Comment by didster** [comment]
Aha well at least that makes sense why it doesn't work - I assumed it had been removed but couldn't locate the issue.

Such a feature really is quite useful though.  Not all metadata is static for the project.  For my use case for example I wanted to use it to set the app title to the API version of the docs I am producing.  This changes every build so I wanted to do something like `docfx ... --meta _appTitle="My API Doc V1.2.3.4"`.  I'm doing it at the moment by first running `sed` over `docfx.json` but it just seems it should be easier.  `--globalMetadataFiles` would also work nicely if taking key-value pairs on the command line is more effort (I do agree taking a JSON string on the command line isn't the best)

Would a PR to re-add `--globalMetadataFiles` be accepted?  If it was a deliberate remove?

**Comment by yufeih** [comment]
> Would a PR to re-add --globalMetadataFiles be accepted?
@didster Yes!

**Comment by JamesHurburgh** [comment]
Just got surprised by this as the documentation needs updating:
https://dotnet.github.io/docfx/reference/docfx-json-reference.html#123-separated-metadata-files-for-global-metadata-and-file-metadata
If only there was a decent tool to update the documents easily! :P
