### ISSUE TITLE
[Bug] Publish to Github Pages Not Working

### ISSUE THREAD

**Issue by Casey-Hofland** [dotnet/docfx#8798]
**Describe the bug**
The [docfx Quick Start guide](https://dotnet.github.io/docfx/index.html) describes how to [publish to github pages](https://dotnet.github.io/docfx/index.html#publish-to-github-pages), but unfortunately it isn't working for me. My workflow looks a little different but the important parts should be there.

**To Reproduce**
1. Add the following as a github action (I had to upload it as a .txt file).
[documentation.txt](https://github.com/dotnet/docfx/files/11554026/documentation.txt)
2. Github actions fails during the "Build" step.

**Expected behavior**
I would expect the github action to update docfx correctly and to the latest version so I can use it to generate my website using the modern template.

**Comment by yufeih** [comment]
> Github actions fails during the "Build" step.
Could you elaborate the details of the failure?

**Comment by Casey-Hofland** [comment]
Oh dear I meant to add it, I'm so embarrassed.

You can find the error [here](https://github.com/Casey-Hofland/UnityClock/actions/runs/5066177784/jobs/9095652419).

**Comment by yufeih** [comment]
No worries. This looks similar to #8429, does setting `allowCompilationErrors` to `true` work?

```json
{
    "metadata": [{
        "src": [{"src": "..", "files": ["**/*.cs"]}],
        "globalNamespaceId": "Global",
        "dest": "api",
        "allowCompilationErrors": true
    }],
```

**Comment by Casey-Hofland** [comment]
> No worries. This looks similar to #8429, does setting `allowCompilationErrors` to `true` work?

Yes, that worked instantly!

That's what I'll have to do then, since I'm generating documentation for Unity packages, and they don't typically reference the `.csproj`. They're actually working on that but it's still a good 2 years away.

```
/home/runner/work/UnityClock/UnityClock/Editor/ClockToolbar.cs(7,16): error CS0246: The type or namespace name 'UnityEngine' could not be found (are you missing a using directive or an assembly reference?)
```

***

However, after building, my site doesn't show images or the top menu bar anymore.

I haven't found a DocFX changelog. Do they have it? It would really help me solve these issues.
