### ISSUE TITLE
[Bug] setup dotnet in github action blocks console commands

### ISSUE THREAD

**Issue by Casey-Hofland** [dotnet/docfx#8800]
**Describe the bug**
I have a github action that fires off a bunch of console commands before building DocFX. These commands generate pages and tables of contents, but they never get build.

It worked before, when I used `choco install -y docfx` to install docfx.
After I applied the correct way of installing it:
```
- name: Dotnet Setup  
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 7.x
      
- run: dotnet tool update -g docfx
```
console commands would not get run.

***

**Example**
The following file is used to generate my website (convert to `.yml` before opening).
[documentation.txt](https://github.com/dotnet/docfx/files/11585752/documentation.txt)

It runs a few console commands (e.g. `echo # [Manual](manual/) > Documentation~\toc.md`) before running `docfx Documentation~/docfx.json`). It builds to my [gh-pages branch](https://github.com/Casey-Hofland/UnityClock/tree/gh-pages), which contains no `toc.html` file, nor a `changelog` and `license` folder. Meaning: the generated content never got build, either because the console commands aren't working or because using the latest version of docfx doesn't take them into account.

You can find the DocFX site (work in progress) [here](https://casey-hofland.github.io/UnityClock/manual/index.html), containing no table of contents in the header, nor a [changelog page](https://casey-hofland.github.io/UnityClock/changelog/CHANGELOG.html) or [license page](https://casey-hofland.github.io/UnityClock/license/LICENSE.html).

***

**Expected behavior**
The console commands get fired, a Changelog and License page get generated, as well as a table of contents for the header.

***

**Additional context**
Disclaimer: I know this is not the best practice but my use case specifically targets [Unity packages](https://docs.unity3d.com/Manual/CustomPackages.html), which have an [established layout](https://docs.unity3d.com/Manual/cus-layout.html), so it's okay to let github actions generate some stuff automatically for ease-of-use.

**Comment by Casey-Hofland** [comment]
Closed this issue as it has nothing to do with docfx. I changed from `windows-latest` to `ubuntu-latest` which has a few subtle differences in its shell commands, which seems to be the culprit.

Apologies for the needless bug report, I'm still a github actions noob.

**Comment by Casey-Hofland** [comment]
> The `echo # [Manual](manual/) > Documentation~\toc.md` command and similar ones look pretty suspicious, because you use `shell: bash`. I expect Bash to treat the `#` as a comment marker and run just `echo` to output an empty line to stdout rather than create any file. If you fix that, then I expect the backslash will be the next problem; it has special meaning in Bash, and I don't think `runs-on: ubuntu-latest` will treat it as a directory separator. How about this instead: `echo '# [Manual](manual/)' > 'Documentation~/toc.md'`

Thanks for your help! I just tried the single quotes around the echo as well as the path but it doesn't seem to work.

The strangest thing is that, for the heck of it, I tried doing this:
```
        run: |
          cd Documentation~
          echo '# [Manual](manual/)' > toc.md
          echo '# [Scripting API](api/)' >> toc.md
          echo '# [Changelog](changelog/)' >> toc.md
          echo '# [License](license/)' >> toc.md
```

And that works just fine.

This is however not an option since I'm also using the copy (`cp`) command and that requires me to copy a file in a subdirectory. You seem to know more about this stuff then I do (I'm a bit out of my league here "^_^) so if you have any suggestions I would be happy to hear them!

**Comment by yufeih** [comment]
@KalleOlaviNiemitalo Thank you!

**Comment by CaseyHofland** [comment]
I came to the same conclusion, my comments on `cp` was from before I wrote my edits on using a forwards slash

**Comment by CaseyHofland** [comment]
I have 1 more thing I am trying to do to meet all my targets, but I figured I would just ask again... you two have been a big help.

I'm trying to allow the user to add an optional `projectMetadata.json` which allows them to [override default behavior](https://docs.unity3d.com/Packages/com.unity.package-manager-doctools@2.1/manual/package-metadata.html). But I am unsure if that is even native DocFX functionality.

I am trying to mimic the requirements for [Unity's Package Manager DocTools](https://docs.unity3d.com/Packages/com.unity.package-manager-doctools@2.1/manual/developer-notes.html) so that the workflow uses similar setup: don't reinvent the wheel and all that. But it could just be that some magic is happening on their side that merges the `projectMetadata.json` with the `docfx.json`, I simply don't know.

***

Bonus:
I also couldn't find how to add the github button the docfx site has in the top right of the screen. I though contribute would take care of it but it didn't :3
