### ISSUE TITLE
[Bug] sitemap contains redirect page entries

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#8821]
**Describe the bug**

Sitemap.xml contains [redirect page](https://dotnet.github.io/docfx/docs/config.html#url-redirects)  entries.
Redirect page should not be included in sitemap's entry.

**To Reproduce**

1. Gets sitemap.xml content(`https://dotnet.github.io/docfx/sitemap.xml`)
2. Check redirected page(`https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project_2.html`) exists.

**Expected behavior**

redirect page is not appear in sitemap entries.

**How to fix this problem**

It seems `SitemapGenerator` PostProcessor can't access FileModel metadata directly as described below.

> https://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html#step3-process-all-the-files-generated-by-docfx
>> Post-processor aims to process the output files, so the FileModel can't be accessed in this phase. If some metadata is needed here,
>> an option is to save it in FileModel.ManifestProperties in build phase, then access it through ManifestItem.Metadata.
>> Another option is to save it somewhere in output files, like HTML's <meta> Tag.

---

I want to making modifications in the following directions, but if you have a better idea, please let us know.

1. Add new HtmlPostProcessor handler  to check `<meta http-equiv="refresh"` tag existence. and save metadata to `OutputFileInfo`.
2. Then SitemapGenerator use this metadata to filter redirect page.

**Pros**
- No need to modify DocumentProcessors.
- No need to open HTML file  at SitemapGenerator.

**Cons**
- It dependent on a specification that `HtmlPostProcessor` is executed in first priority
- It dependent on `<meta http-equiv="refresh"`. 
  For SEO optimization, redirect may be implemented at server side feature.  
  (Example: https://www.statiq.dev/guide/web/content-files/redirects)

**Comment by yufeih** [comment]
I'd prefer we check `redirect_url` metadata over `<meta http-equiv`, as many redirections are implemented server side. 

The `SitemapGenerator` does not have access to metadata, may be we can change the `DocumentType` of redirections to `Redirection` instead of `Conceptual` [here](https://github.com/dotnet/docfx/blob/main/src/Microsoft.DocAsCode.Build.ConceptualDocuments/ConceptualDocumentProcessor.cs#L106)?

**Comment by filzrev** [comment]
Thanks for the reply.

> we can change the DocumentType of redirections to Redirection instead of Conceptual 

If  `DocumentType` can changed to `Redirection`.
It'll be a clean and more extensible architecture.

**Comment by filzrev** [comment]
This issue is fixed by #8892
