### ISSUE TITLE
[Bug] Missing index.html

### ISSUE THREAD

**Issue by MPeli** [dotnet/docfx#8823]
**Describe the bug**
index.html is not generated. Running docfx docfx.json --serve host allows me to access documentation in a browser on this url http://localhost:8080, there I see a folder content, a list of html files.

**To Reproduce**
1. Create a new solution
2. Add a .net standard 2.0 project (My.Project.A)
3. Adda  .net 7 project (My.Project.Docs)
    - add a nuget Microsoft.DocAsCode.App 2.67.3
    - add following code to Program.cs

```
var instance = MSBuildLocator.QueryVisualStudioInstances().OrderByDescending(instance => instance.Version).First();

MSBuildLocator.RegisterInstance(instance);

const string docFxFile = "docfx.json";
await Microsoft.DocAsCode.Dotnet.DotnetApiCatalog.GenerateManagedReferenceYamlFiles(docFxFile);
await Microsoft.DocAsCode.Docset.Build(docFxFile);
```

- add docfx.json, copy it to the output folder

```
{
    "metadata": [
        {
            "src": [
                {
                    "files": [
                        "My.Project.A/My.Project.A.csproj"
                    ],
                    "src": "../../../../"
                }
            ],
            "dest": "_metadata",
            "properties": {
                "TargetFramework": "netstandard2.0"
            }
        }
    ],
    "build": {
        "content": [
            {
                "files": [ "*.yml" ],
                "src": "./_metadata"
            }
        ],
        "globalMetadata": {
            "_appTitle": "My project website",
            "_gitContribute": {
                "repo": "https://github.com/company-group/My.Repository",
                "branch": "dev",
                "apiSpecFolder": "docs-ref-overwrite"
            }
        },
        "dest": "./_site",
        "template": "default"
    }
}
```

**Expected behavior**
Metadata and documentation are generated in following folders (and they are). index.html should be in _site folder (it is not)

- My.Repository\My.Project.Docs\bin\Debug\net7.0\_metadata\
- My.Repository\My.Project.Docs\bin\Debug\net7.0\_site\

**Context (please complete the following information):**
- OS: Windows 11
- Docfx version: Microsoft.DocAsCode.App 2.67.3

**Additional context**
I have never used docfx before

**Comment by happysally001** [comment]
I have the same issue

I'm on mac and the output said "No files are found with glob pattern .{md,yml,ipynb}, excluding <none>, under directory "/Users/liyingsui/Downloads/ECSClientDoc/documentation", but I has toc.yml in that folder

**Comment by MPeli** [comment]
I think that this is by design. I found this repository yesterday https://github.com/mtirionMSFT/DocFxQuickStart and managed to create my own index.md file which was then automatically converted to index.html.

**Comment by yufeih** [comment]
Glad the problem was solved.

**Comment by MaxSomarriba** [comment]
Wanted to add to this because this was my problem but the reason for it was different. I'm adding Docfx to my Unity project and followed this repo [https://github.com/NormandErwan/DocFxForUnity](url) however following the gitignore he does not push the index.md file which was not allowing the github workflow to build index.html. It worked for him because he copied his README.md as the index.md during the workflow.
