### ISSUE TITLE
[Bug] Search doesn't work in firefox

### ISSUE THREAD

**Issue by rotanov** [dotnet/docfx#8829]
Search doesn't work in firefox, while it works in Google Chrome.

Console says: SyntaxError: import declarations may only appear at top level of a module [search-worker.min.js:1]

- OS: Windows
- Docfx version: 2.67.3+f28165af43dde2ec072a79fa2479f475fcd947ad
- Browser: Firefox 113.0.2 (64-bit)

**Comment by x5f3759df** [comment]
Second here, doesn't work in Firefox at all, docfx version 2.67.3

**Comment by yufeih** [comment]
Support of web worker modules need to be enabled manually via `about:config` and set `dom.workers.modules.enabled` to true.

https://caniuse.com/mdn-api_worker_worker_ecmascript_modules

https://github.com/mdn/content/issues/24402

**Comment by rotanov** [comment]
Thanks! It worked.

**Comment by yufeih** [comment]
> I guess it might have been https://github.com/dotnet/docfx/pull/8751/files#diff-a8c738353e7279ee1aaaa4251388ffd149c5dd0ea2f36924125d50eaf5a96576 in DocFX 2.67.1.

It is.

**Comment by TheConstructor** [comment]
At least it seems Firefox 114.0 changed the default to `dom.workers.modules.enabled = true`

**Comment by filzrev** [comment]
I've also confirmed. it works without settings with latest Firefox ESR 115.2.1.
https://www.mozilla.org/en-US/firefox/115.2.1/releasenotes
