### ISSUE TITLE
[Feature Request] Additional search locales

### ISSUE THREAD

**Issue by rotanov** [dotnet/docfx#8830]
By default a search in Cyrillic is not supported.

Is there an easy way to enable it? If no, then that would be my feature request. 

One way to implement it could be config option -- array of additional supported search locales like:

```json
{
    "additionalSearchLocales": [ "ru-RU", "ja-JP" ],
}
```

I've googled for a solution and found this [https://stackoverflow.com/questions/56624189/docfx-russian-language-search](https://stackoverflow.com/questions/56624189/docfx-russian-language-search)

but it seems like a hack. And I don't quite understand if they suggest to fork docfx and modify source, or there's some way to provide your own `search-worker.js` via template. But it's not `js` now, it's in typescript. Anyway it seems like a workaround (which I failed to apply).

**Comment by achikhv** [comment]
I suppose [this solution](https://stackoverflow.com/questions/56624189/docfx-russian-language-search) worked before docfx team minified `search-worker.js`. So now customizing it in your template has no effect. What I had to do was:

1. Export new default template `docfx export template default`
2. Add `docfx.js` from exported `default` to my template.
3. Change line `var worker = new Worker(relHref + 'styles/search-worker.min.js');` to `var worker = new Worker(relHref + 'styles/search-worker.js');`
4. Add `lunr.min.js` to my template.

Also you have to find old `search-worker.js` and apply solution from stackoverflow to it.

**Comment by rotanov** [comment]
@achikhv Yeah, that will probably do the job, but I'm using `modern` template, which have docfx.min.js generated from https://github.com/dotnet/docfx/blob/main/templates/modern/src/docfx.ts and it's using search-worker.ts, so hacking into all of that the same way becomes too much for me to handle.

**Comment by achikhv** [comment]
@yufeih, would you please give us any hint how to add additional locales? I understand I can use `configureLunr` to enable search, but it's a little bit obscure to me how to include lurn localization scripts. As I understand, docfx uses minified lunr, so I can't just add `<script>` to `_master.tmpl`.

**Comment by yufeih** [comment]
[`lunr-languages`](https://github.com/MihaiValentin/lunr-languages) needs NodeJS for many langauges but `configureLunr` is currently running in the browser. We would need to move lunr index build to compile time to support additional search locales for many languages, so this issue is still open.

**Comment by achikhv** [comment]
I need Russian language. `lunr.ru.js` works fine with modified `default` template, but I had to export 2.59 template and incorporate modified scripts to the current version. It seems like a hack to me.

**Comment by yufeih** [comment]
#9313 should work then.

**Comment by achikhv** [comment]
Just tried customizing search languages in modern template. Added this to main.js:
```js
export default {
	"lunrLanguages": ["en", "ru"]
}
```
When I first load documentation, search works ok. But after F5 search box stays disabled and console displays error:

```
Error: Cannot load unregistered function: stemmer-ru
    at lunr.js:581:13
    at Array.forEach (<anonymous>)
    at t.Pipeline.load (lunr.js:575:14)
    at t.Index.load (lunr.js:2286:32)
    at pe (search-worker.ts:32:34)
    at async de (search-worker.ts:18:27)
Promise.catch (асинхронно)
(anonymous) @ search-worker.ts:69
localhost/:1  Error: Cannot load unregistered function: stemmer-ru
```

Should I open a new issue about it?

**Comment by yufeih** [comment]
Does deleting this database help?

![image](https://github.com/dotnet/docfx/assets/511355/0bf79059-5e5a-4604-be13-bcff5e0b2bab)

**Comment by achikhv** [comment]
It helps for the first time. After second refresh error is back.

**Comment by mkubrosli-nvs** [comment]
I have added "ar" (arabic) to my main.js as following:
`export default {
  "lunrLanguages": ["en", "ar"]
}`
and it didn't work, as i am getting this error in browser console:
`TypeError: Cannot set properties of undefined (setting 'result')
    at http://localhost:8080/public/lunr.ar-E7GAKDHK.min.js:1:880
    at http://localhost:8080/public/lunr.ar-E7GAKDHK.min.js:1:21618
    at me (http://localhost:8080/public/search-worker.min.js:2:53807)
    at async Promise.all (index 1)
    at async n (http://localhost:8080/public/search-worker.min.js:2:51877)
    at async ve (http://localhost:8080/public/search-worker.min.js:2:51568)
Promise.catch (async)
onmessage @ search-worker.ts:73
TypeError: Cannot set properties of undefined (setting 'result') index.html:1`

Seems like it is also depending on NodeJS. 
Is there any plan to resolve this case?

**Comment by SokurenkoED** [comment]
I exported the modern template using:

`docfx template export modern`

Then I modified the main.js file by adding:

```
export default {
  lunrLanguages: ['ru']
};
```

After that, I updated docfx.json to include the following in the template section:

```
"template": [
  "default",
  "_exported_templates/modern"
]
```
However, search still doesn't respond to Russian words.
Could you please help me understand what I might be doing wrong?
