### ISSUE TITLE
[Feature Request] Update docfx choco package

### ISSUE THREAD

**Issue by jamaa** [dotnet/docfx#8856]
**Is your feature request related to a problem? Please describe.**
I use docfx in github actions, where docfx is installed using chocolatey. However, the [latest available choco package of docfx is 2.59.4](https://community.chocolatey.org/packages/docfx). I would like to be able to use a more recent version.

**Describe the solution you'd like**
Update the choco package of docfx to a more recent release.

**Describe alternatives you've considered**

**Additional context**

**Comment by yufeih** [comment]
Is it possible to change the installation script to use `dotnet tool install -g docfx`?

**Comment by jamaa** [comment]
Thanks, yes, that actually works. But I am now facing a different problem which I think is due to the latest docfx always using the latest available .NET SDK to build the project (in GitHub actions this is currently .NET Core SDK 7.0.302). The project in question still uses .NET Framework 4.8 and cannot be built using the newer SDKs (I think the underlying issue is `dotnet restore` not properly restoring the NuGet dependencies). (See details [here](https://github.com/bluemodel/BlueM.Wave/actions/runs/5231193392/jobs/9445184415?pr=101#step:5:7)).

Using the old docfx 2.59.4, the build [works](https://github.com/bluemodel/BlueM.Wave/actions/runs/5234285156/jobs/9450319850#step:5:7). It doesn't say so explicitly in the log, but I believe it is using .NET Core 3.1 for the build.

Is there any way to tell docfx which .NET SDK to use within a GitHub action?

**Comment by colewerner** [comment]
Similar to this it would be nice if the [docfx.console nuget package](https://www.nuget.org/packages/docfx.console) were updated to the latest as new versions are released.  We currently leverage the nuget package from a cake/ps build script system to build docfx sites.  It looks like it hasn't been updated in 9 months or so.

**Comment by colewerner** [comment]
It looks like the publishing of the [docfx.console nuget package](https://www.nuget.org/packages/docfx.console) and the choco package were both deprecated as part of the PR:
https://www.nuget.org/packages/docfx.console

It seems the approach at this point is to install the dotnet tool via `dotnet tool install -g docfx`

**Comment by jamaa** [comment]
ok thanks. Maybe it's possible to mark the choco project as deprecated or to at least add some relevant info to the description there to avoid people asking the same questions as me?
