### ISSUE TITLE
[Feature Request] Expose Metadata stage via managed API in Microsoft.DocAsCode.App

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/docfx#8866]
Using the `Microsoft.DocAsCode.App` NuGet package, I can generate documentation via `Microsoft.DocAsCode.Docset.Build`. While this method performs the `build` stage, it doesn't perform the `metadata` stage, which generates yaml files for API. This is a severe problem if I want to migrate from the command-line workflow to the managed API workflow. It would be nice to have a separate method that performs the `metadata` stage.

**Comment by yufeih** [comment]
The `metadata` step is a separate API call exposed as [DotnetApiCatalog.GenerateManagedReferenceYamlFiles](https://dotnet.github.io/docfx/api/Microsoft.DocAsCode.Dotnet.DotnetApiCatalog.html#Microsoft_DocAsCode_Dotnet_DotnetApiCatalog_GenerateManagedReferenceYamlFiles_System_String_) in the `Microsoft.DocAsCode.Dotnet` package.

**Comment by AndreyAkinshin** [comment]
@yufeih thanks for the information!
