### ISSUE TITLE
[Bug] Image markdown doesn't support width and height natively

### ISSUE THREAD

**Issue by krishnak-msft** [dotnet/docfx#8877]
**Describe the bug**
Preview md in ADO supports `![alt](image.png =widthxheight)` but docFx requires one to directly use the html <img> tag with width or height specified

**To Reproduce**
1. Edit md in ADO and use an image with widthxheight specified in the md tag ![alt](image.png =widthxheight)

**Expected behavior**
=widthxheight and =width and =xheight should be supported in markdown syntax rather than user having to specify <img>

**Context (please complete the following information):**
- OS: Windows
- Docfx version: v2.67.3

**Additional context**
[Image markdown syntax and format](https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#images)
Resize image: IMAGE_URL =WIDTHxHEIGHT

**Comment by yufeih** [comment]
May potentially workaround #1453

**Comment by yufeih** [comment]
Related discussion in markdig which is the markdown parser docfx is using: https://github.com/xoofx/markdig/issues/226 It seems they are in favor of a different syntax.

**Comment by krishnak-msft** [comment]
It doesn’t scale.
________________________________

**Comment by yufeih** [comment]
This is doable with:
1. Enable the generic attribute markdig extension in `docfx.json`
    ```json
    {
      "build": {
        "markdownEngineProperties": {
          "markdigExtensions": [
            "attributes"
          ]
        }
      }
    }
    ```
2. Use this markdown syntax: `![](http://example.com/image.jpg){width=250 height=120}`
