### ISSUE TITLE
.deb/rpm packages

### ISSUE THREAD

**Issue by TerribleDev** [dotnet/docfx#889]
I noticed you have a chocolatey package, but no package for Linux. Could you ship deb and rpm packages? Personally I am most interested in `.deb`

**Comment by dlech** [comment]
I've thrown together a Debian package.

https://github.com/dlech/docfx-deb/wiki

**Comment by yufeih** [comment]
We are switching to [.NET core global tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) for distribution in v3, it makes cross platform distribution a lot easier.
