### ISSUE TITLE
Update to 2.67.4 impossible

### ISSUE THREAD

**Issue by JM2K69** [dotnet/docfx#8890]
In **Github** there is a new release to **2.67.4** but not on nuget

![image](https://github.com/dotnet/docfx/assets/17923944/1388cd12-7244-4582-b7c0-5c7bbc3d3a93)

![image](https://github.com/dotnet/docfx/assets/17923944/ace2da3e-5756-490b-9c98-687c523bec61)

with the cmdline 
```cmd
dotnet tool update docfx -g 
```
Always install 2.67.3
I think the pipeline for the release have  a pproblem to push it to nuget.org gallery.

**Comment by yufeih** [comment]
Yep, that was one of the expired tokens. I've manually triggered the pipeline and something else is broken.

**Comment by yufeih** [comment]
A new v2.67.5 version is now available on NuGet.

**Comment by JM2K69** [comment]
Yes but as a pre-release good.

**Comment by yufeih** [comment]
Now it is marked as latest
