### ISSUE TITLE
[Feature Request] Remove dependency to CultureInfo.CurrentCulture

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#8893]
**Is your feature request related to a problem? Please describe.**

When enable following `.editorconfig` **code analyzer rules**  relating to `CultureInfo.CurrentCulture` .
About 161 warnings occurs.

``` editorconfig
dotnet_diagnostic.CA1304.severity = warning
dotnet_diagnostic.CA1305.severity = warning
dotnet_diagnostic.CA1307.severity = warning
dotnet_diagnostic.CA1310.severity = warning
```

**warning example**
> Warning	CA1310	The behavior of 'string.StartsWith(string)' could vary based on the current user's locale settings.
> Replace this call in 'Microsoft.DocAsCode.MarkdigEngine.Extensions.HtmlCodeSnippetRenderer.HtmlCodeSnippetRenderer()' 
> with a call to 'string.StartsWith(string, System.StringComparison)'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1310)

It'll not be a problem for most OS culture environment.
But some performance penalty exists. when `CurrentCulture` is implicitly used.

As far as I've tested. measurable performance differences exists.
when running on `docfx.exe` with `InvariantGlobalization` mode. (about 5%～10%)

**Simple Benchmark**
```pwsh
# Run docfx.exe with default mode.
$env:DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = 0
Measure-Command {docfx build --logLevel Warning } | select TotalSeconds

# Run docfx.exe with InvariantGlobalization mode.
$env:DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = 1
Measure-Command {docfx build --logLevel Warning } | select TotalSeconds
```

**Describe the solution you'd like**

1. Enable `InvariantGlobalization` mode on `docfx.exe` with following settings  
    `<InvariantGlobalization>true</InvariantGlobalization>`
    -> Addition to InvariantCulture, All string comparison use StringComparison.Ordinal.

or 

2. Fix all code analyzer warnings related to `CurrentCulture`.

**Comment by yufeih** [comment]
The reasons we didn't enable global invariant culture was the MSLearn site template needs some localized date strings. Now that MSLearn is not a supported target, it seems to be ok to move to invariant culture.

**Comment by filzrev** [comment]
Thanks for enabling global invariant mode.

Following are memo relating to API order changed problems when enabling globalization invariant mode.
---

In this PR, Some API orders are slightly changed.
It is caused by default string comparison mode  is changed to `CurrentCulture` to `Ordinal`. 

When running  on [Globalization Invariant Mode](https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md)
This behavior can't be changed.
Even if  explicitly specify `StringComparer.InvariantCulture` in `OrderBy()` method. It is ignored as described below.

https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md#string-sorting-and-searching

> String operations like [Compare](https://docs.microsoft.com/dotnet/api/?term=string.compare), [IndexOf](https://docs.microsoft.com/dotnet/api/?term=string.indexof) and [LastIndexOf](https://docs.microsoft.com/dotnet/api/?term=string.lastindexof) are always performed as [ordinal](https://en.wikipedia.org/wiki/Ordinal_number) and not linguistic operations regardless of the string comparing options passed to the APIs.
