### ISSUE TITLE
[Bug] Menu always expanded

### ISSUE THREAD

**Issue by ghost** [dotnet/docfx#8901]
1. Start Firefox on Arch Linux, desktop version.
1. Browse to https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-richtextblock.html

**Expected**

Can read the docs.

**Actual**

![firefox-arch](https://github.com/dotnet/docfx/assets/2131950/d0962660-ca1e-44b2-bedf-1aea17db640a)

**Comment by filzrev** [comment]
`windows-ui-xaml-controls-richtextblock.html` have following footer text.
> Last updated Saturday, August 15, 2020 1:08 AM.

and latest parent page. ([List of views implemented in Uno](https://platform.uno/docs/articles/implemented-views.html)) don't contains page link.

So it seems some outdated pages are deployed to documentation site.
It may be related to issue https://github.com/unoplatform/uno/issues/12356
