### ISSUE TITLE
[Bug] "exclude" is not works when path fragments contains folder that starts with '.'

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#8913]
**Describe the bug**

"exclude" is ignored when path fragments contains names that starts with `.` 

**Example**
`_site/.attachments/file.txt` should be excluded. but docfx process as resource.

``` json
    "resource": [
      {
        "files": [
          "**/.attachments/*.txt" // Azure DevOps wiki style attachments folder name
        ],
        "exclude": [
          "_site/**"
        ]
      }
    ],
```

**To Reproduce**
1. Clone sample test project (https://github.com/filzrev/docfx_glob_tests)
2. Run `docfx build`.  `articles\.attachments\file.txt` are handled as resource.   
    and copied to `_site\articles\.attachments/file.txt` is copied.
4. Run `docfx build`.  `_site\articles\.attachments/file.txt`  are handled as resource.   
    and copied to `_site\_site\articles\.attachments/file.txt` . 

**Expected behavior**
`"exclude": [ "_site/**" ] `  glob settings works as expected.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.67.5

**Additional context**

It seems `Microsoft.DocAsCode.Glob` handle folders that starts with '.' as special `hidden folder`.

https://github.com/dotnet/docfx/blob/b03e06e6631c8dacfe8df1780e3a3b9081619713/src/Microsoft.DocAsCode.Glob/GlobMatcher.cs#L406-L416
https://github.com/dotnet/docfx/blob/971df085ad24ba26b3c48371631841b8240e3db8/test/Microsoft.DocAsCode.Glob.Tests/GlobFileTest.cs#L19-L50

If there are no special requirements for file globbing rules.
it might be better to consider to replace globbing library to `Microsoft.Extensions.FileSystemGlobbing`.

**Comment by yufeih** [comment]
> it might be better to consider to replace globbing library to `Microsoft.Extensions.FileSystemGlobbing`.

I'd like to switch to a different glob library, the problem with `Microsoft.Extensions.FileSystemGlobbing` last time I checked is it does not support `*.{md,yml}`

**Comment by filzrev** [comment]
> Microsoft.Extensions.FileSystemGlobbing last time I checked is it does not support *.{md,yml}

I wasn’t aware that the support for the ([Brace expansion](https://en.wikipedia.org/wiki/Bash_(Unix_shell)#Brace_expansion)) feature missing.

> Related `dotnet/runtime` issue (`https://github.com/dotnet/runtime/issues/21362`)

---

Anyway, this issue occurs very specific conditions.
And can be easily avoided by not including `_site` directory with wildcard (`**/*`).
So bug fix priority is lower.

**Comment by filzrev** [comment]
This issue can be avoided by setting `"dot": true` property in file mapping.

As described in doc comment. Directory name that starts with `.` is not matched by default.
When explicitly include these hidden files.
It's required to set `"dot": true`  also, for `exclude` settings works as expected.

```cs
/// <summary>
/// Allow files start with `.` to be matched even if `.` is not explicitly specified in the pattern.
/// By default files start with `.` will not be matched by `*` unless the pattern starts with `.`.
/// </summary>
[JsonProperty("dot")]
public bool? AllowDotMatch { get; set; }
```
