### ISSUE TITLE
[Bug] <inheritdoc /> + <typeparamref > = empty string (and warning)

### ISSUE THREAD

**Issue by JeReT** [dotnet/docfx#8948]
**Describe the bug**
When you have an `<inheritdoc/>` for a generic method which references a generic parameter via `<typeparamref />` in the tripple-slash-comment, a warning is shown when serving and the generic type name is not shown in the documentation at all.

Here a test scenario:
```csharp
    public interface IMyInterface
    {
        /// <summary>
        /// Does nothing with generic type <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T">A generic type.</typeparam>
        void DoNothing<T>();
    }

    public class MyImplementation : IMyInterface
    {
        /// <inheritdoc/>
        public void DoNothing<T>() { }
    }
```

and here the output in the console:
```
Invalid cref value "!:T" found in triple-slash-comments for DoNothing defined in ...
```
and a screenshot from the documentation:
![grafik](https://github.com/dotnet/docfx/assets/530561/811a5b53-2dc7-40fb-a7cc-50e281ec5f70) 

**To Reproduce**
1. Copy the code above into a C# project
2. Setup docfx to create a documentation for that project
3. Serve the docfx project

**Expected behavior**
- No warning should be shown.
- The Type parameter name should appear in the generated documentation and it should act as a cross reference to the documentation of the type parameter.

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: 2.67.5

**Additional context**
If I don't use `<inheritdoc/>` and instead copy-paste the documentation, everything works as expected.
It doesn't seem to matter if the `<typeparamref>` occures in the summary tag or somewhere else.

**Comment by yufeih** [comment]
vs/vscode in this case does not render `T` in `MyImplementation` with a clickable link, so it did failed to resolve that `T` but we should fallback to display the `T` instead of showing an empty string. Might be related to #1887.

**Comment by KerenSl-tr** [comment]
It seems that you fixed the problem of displaying the type reference as an empty string, but still the warning appears and the displayed reference doesn't act as a link:
![image](https://github.com/dotnet/docfx/assets/132361124/f63d09ef-0cb0-42d3-9c29-a15b78ef3bae)

And there's still a warning:
```
warning: Invalid cref value "!:T" found in XML documentation comment  for Execute defined in ...
```

I think this bug should be reopened until these issues are also solved.

**Comment by KerenSl-tr** [comment]
Note: we want to add `--warningsAsErrors` in our build pipeline, but this warning prevents us from doing so. Please advise even if there's a workaround until this bug is resolved.

**Comment by yufeih** [comment]
Likely needs a Roslyn fix.

**Comment by filzrev** [comment]
This issue will be resolved in next docfx release. (By Roslyn packages update)

I've tested on `nightly version of docfx`.
And confirmed it works as expected.
