### ISSUE TITLE
Incorrect display of generics in comment

### ISSUE THREAD

**Issue by joshuaavalon** [dotnet/docfx#896]
### Minimal repro steps
```
<see cref="IEnumerable{T}" />
```

### Expected result
*What would you expect to happen if there wasn't a bug?*  
```
IEnumerable<T>
```

### Actual result
*What is actually happening?*  
```
IEnumerable<T><T>
```

**Comment by superyyrrzz** [comment]
Thanks you for your report. I can't reproduce this with your step, but this may be related to another bug introduced in DocFX 2.7. Do you meet the same problem if using [DocFX 2.6.3](https://github.com/dotnet/docfx/releases/tag/v2.6.3)?

**Comment by joshuaavalon** [comment]
Version 2.6.3 does not have this problem but 2.7.3  has this problem.

Here is my test file.

	namespace Hello_World
	{
		public class Program
		{
			public static void Main(string[] args)
			{
			}

			/// <summary>
			/// Test
			/// </summary>
			/// <param name="args"></param>
			/// <seealso cref="Test{T}"/>
			public void Hello()
			{ 
			}

			public class Test<T>
			{
			}
		}
	}

**Comment by superyyrrzz** [comment]
Thank you for your example. #900 will fix this. It will ship with DocFX 2.8 on 11/22.

**Comment by CrayonPastel** [comment]
docfx ver 2.61.0 looks degraded so as to cause the same issue.

**Comment by InFTord** [comment]
it's still broken
