### ISSUE TITLE
ValidateBookmark warnings

### ISSUE THREAD

**Issue by wekempf** [dotnet/docfx#897]
### Functional impact

Warnings are produced when building documentation:

```Warning: [Process in post processor html.ValidateBookmark](index.html#L77)index.html contains illegal link: manual/intro.html#Intro. Link text is `Intro`. The file manual/intro.html doesn't contain a bookmark named Intro, please check the src file index.md and src linkedTo file manual/intro.md or the template you applied.```

I suspected it might be my template, but I switched to not providing a custom template and the result is the same.

```@Uid``` links include an anchor, but the generated output doesn't have any anchors, so validation fails.

### Minimal repro steps

Easiest thing would be to see the result in my own repo. [Testify](https://github.com/wekempf/testify). Latest [build](https://ci.appveyor.com/project/wekempf/testify/build/1.2.0-unstable.19.build.53).

### Expected result

Either the links would not include anchors, or the generated output would have the anchor defined, and no warnings would be produced when building.

### Actual result

Warnings are produced for every ```@Uid``` link.

**Comment by superyyrrzz** [comment]
Thanks @wekempf for your feedback. This is fixed in dev branch via #860 and the link in anchor is removed. It will ship with DocFX 2.8 on 11/21.
