### ISSUE TITLE
[Bug] PDF TOC Links are not linking with correct page

### ISSUE THREAD

**Issue by Lagann311** [dotnet/docfx#9001]
**Describe the bug**
When a link from the generated TOC is clicked in the PDF file, it doesn't always jump to the associated class, but to the location a few pages beyond. The same thing happens when using Bookmarks from Adobe Acrobat Reader, although it is not always the same behaviour: sometimes the actual page is then different between the Bookmark and the TOC file link.

I have noticed the following pattern when investigating the bug, which depends on how many pages belong to a class:
- 1-2 pages -> link works
- 3-4 pages -> 1 page past expected page
- 8    pages -> 3 pages past desired page
- 9    pages -> 4 pages past desired page
- 16  pages -> 7 pages past desired page
So it seems like the formula **(pages / 2) - 1 = landingPage** applies

If I click the first Bookmark in Adobe Acrobat Reader "TableOfContents", I already land one page beyond the actual Table of Contents beginning page.

Maybe this is related to https://github.com/dotnet/docfx/issues/8994, because the error says "page 0 not found"? (I also got this error for the pdf file where this bug occurs).

**To Reproduce**
1. Use a standard pdf build configuration in docfx.json:
```
  "pdf": {
    "content": [
      {
        "files": [ "**/*.{md,yml}" ]
      }
    ],
    "template": [
      "pdf.default"
    ],
    "wkhtmltopdf": {
      "additionalArguments": "--enable-local-file-access"
    },
    "dest": "_site_pdf"
  }
```
2. Run docfx pdf

**Expected behavior**
When clicking the link, it should jump to the beginning of the class, instead pages beyond it.

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: 2.67.5

**Additional context**
This seems to be independent from custom templates, I only used the pdf.default one.

**Comment by yufeih** [comment]
Addressed in v2.73.0 with [a new PDF engine](https://dotnet.github.io/docfx/docs/pdf.html).
