### ISSUE TITLE
[Feature Request] CheckCertificateRevocationList should be configurable

### ISSUE THREAD

**Issue by christianbumann** [dotnet/docfx#9005]
**Is your feature request related to a problem? Please describe.**
With this [Pull Request](https://github.com/dotnet/docfx/pull/7481/commits/9582a82ade32843250e4ca648f3dcbb8a32f64d6) loading xref checks also the certificates validity of the xref url's.

We are using a documentation server which hosts different docs (with xref, e.g. https://abc.com/xrefmap.yml) which we wan't to use in other documentation. Our documentation server has a valid certificate.
So this was working great so far, until the change above.

As our build environment is completely offline, it is not possible to verify the certificate validity - and after a long waiting time it ends with a message "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

**Describe the solution you'd like**
It would be nice to have a flag to deactivate this in the configuration file (docfx.json)
e.g. DisableCheckCertificateRevocationList  => param array with the base url's

```json
{
    "build": {
        "xref": [
            "https://docs.example.org/lib1/xrefmap.yml"
        ],
        "DisableCheckCertificateRevocationList": [
            "https://docs.example.org"
        ]
    }
}
```

**Describe alternatives you've considered**
- Overwriting the setting in the app.config of DocFx was not working (seems that the application overwrites this)
- Adding the certificate to the build server was not working (It was worth a try :-))

**Comment by christianbumann** [comment]
@yufeih thank you for the fast fix! I like the solution with the environment variable. 👍

**Comment by yufeih** [comment]
My pleasure
