### ISSUE TITLE
[Feature Request] Additional GitHub repository settings.

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#9016]
**Is your feature request related to a problem? Please describe.**
Currently. outdated PR needs manual rebase operations using CLI.
And need to delete branch manually after merged.

**Describe the solution you'd like**
Enable following settings from [settings page](https://github.com/dotnet/docfx/settings).
- `Always suggest updating pull request branches`
- `Automatically delete head branches`

**Comment by yufeih** [comment]
all set

**Comment by filzrev** [comment]
Thanks for your support.
I've confirmed following buttons are displayed on my PR page and can execute rebase from UI.
![image](https://github.com/dotnet/docfx/assets/103790468/a70e1696-a76d-44dd-bdd0-7c0a9250a408)

Is it able to update PR #9008 that is failed with following error.
> Microsoft.Playwright.PlaywrightException : net::ERR_CONNECTION_REFUSED at http://localhost:8089/index.html
