### ISSUE TITLE
[Feature Request] Docfx and PDF 

### ISSUE THREAD

**Issue by JM2K69** [dotnet/docfx#9022]
In some case it could be nice if **Docfx** can have a reader in _JS_ for read some additionnal file in **pdf** **format**.

**Comment by yufeih** [comment]
Would you like to add some more details to the ask? Is it asking docfx to support PDF as an input file format by using a JavaScript reader to parse additional information stored in PDF?

**Comment by JM2K69** [comment]
In fact I just wanted an immersive external pdf file reader.

**Comment by yufeih** [comment]
It seems the ask isn't clear. Consider re-open with a clear feature request description.
