### ISSUE TITLE
Bring back providing global metadata properties via the command line

### ISSUE THREAD

**Issue by bronumski** [dotnet/docfx#9026]
**Is your feature request related to a problem? Please describe.**
Using version 2.62.2 we were able to provide compile time information to docfx from the build server such as version and other
dynamic information. In more recent versions that option has been removed https://github.com/dotnet/docfx/issues/8787 https://github.com/dotnet/docfx/pull/8641.

**Describe the solution you'd like**
As I understand it this was removed because of json parsing from the command line but it really removes the power from build scripts. It would be nice to be able to supply additional values this way to support reuse and dynamic values.

**Describe alternatives you've considered**
Staying on 2.62.2 is the easiest solution right now but if forced to we would need to write to a temporary file and use that as a global meta data file and pass that in.

**Additional Context**
Here is part of our Make build script which we are using.

```Make
.PHONY: generate-docs
generate-docs: clean init-project
ifdef _DOCFX_ENABLED
	dotnet docfx metadata $(DOCFX_CONFIG)
	dotnet docfx build $(DOCFX_CONFIG) \
		-o $(_DOCFX_OUTPUT) \
		-t default,../$(_DOCFX_RESOURCES)/Templates/singulinkfx \
		--globalMetadata "{ \
			'_copyrightFooter': '$(_COPYRIGHT_TEXT)', \
			'_appTitle': '$(PROJECT_DESCRIPTION)', \
			'_appName': '$(PROJECT_NAME)', \
			'_appFooter': '<strong>$(PROJECT_NAME) - v$(VERSION)</strong>', \
			'_appLogoPath': 'icon_512x512-300x300.png', \
			'_appFaviconPath': 'icon_512x512-150x150.png', \
			'_enableSearch': true, \
			'_disableSideFilter': false, \
			'_disableSideFilter': true, \
			'_disableContribution': false, \
			'_disableBreadcrumb': false, \
			}"

	cp -f $(_DOCFX_RESOURCES)/icon_512x512-150x150.png $(_DOCFX_OUTPUT)
	cp -f $(_DOCFX_RESOURCES)/icon_512x512-300x300.png $(_DOCFX_OUTPUT)
else
	$(info $(DOCFX_CONFIG) missing, skipping documentation generation)
endif
```

**Comment by yufeih** [comment]
Try the [`--metadata`](https://github.com/dotnet/docfx/blob/main/src/docfx/Models/BuildCommandOptions.cs#L20) command line option: `docfx build -m _appTitle="My App" -m _appFooter="Footer"`

**Comment by bronumski** [comment]
Thank you. It wasn't clear to me from the docs but that makes a lot of sense now.

**Comment by yufeih** [comment]
The docs could use some improvements

**Comment by bronumski** [comment]
> The docs could use some improvements

Isn't that always the case. Seeing as this is a documentation tool it stands to reason the docs are not up to date. Same reason a builders own house is never finished and plumbers own taps always drip 😁
