### ISSUE TITLE
[Bug] Unable to load shared library 'hostfxr' or one of its dependencies

### ISSUE THREAD

**Issue by mogocat** [dotnet/docfx#9047]
**Describe the bug**
When I run the command docfx build docfx_project/docfx.json --serve, I got this error.

**To Reproduce**
I am using .Net 6.0.412 and runtime is 6.0.20. I am trying to generate the docs for my unity project. Unity version is 2021.3.7f1c1.

**Expected behavior**
It shows 
```
Completed in 189.8361 milliseconds
Error: Unable to load shared library 'hostfxr' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES
environment variable: dlopen(libhostfxr, 1): image not found
```
But when I open the website, nothing there.
**Context (please complete the following information):**
MacOS 10.15.7
docfx 2.70.0

**Additional context**
I have found this link, but I really don't know what can I do.
https://github.com/microsoft/MSBuildLocator/pull/224

Any help will be great appreciated!

**Comment by YuliiaKovalova** [comment]
Hi @mogocat ,

You can try to use this workaround while we are investigating the issue.
https://github.com/microsoft/vscode-dotnettools/issues/120#issuecomment-1640892593

**Comment by YuliiaKovalova** [comment]
The issue was addressed in https://www.nuget.org/packages/Microsoft.Build.Locator/1.6.1.
