### ISSUE TITLE
[Feature Request] .Net 8 support

### ISSUE THREAD

**Issue by MarkStega** [dotnet/docfx#9064]
**Is your feature request related to a problem? Please describe.**
Since the current release of DocFx is tied to .Net Core SDK 7 (or earlier?) it is not possible to generate a documentation site for .Net 8 based projects in a github action as many of the issues are reported as errors.

**Describe the solution you'd like**
I'd like to be able to generate a complete documentation site, but failing that I'd like the failure to generate metadata not to cause an error (and then failure) in the build step..

**Describe alternatives you've considered**
I can revert to DocFx 2.59.4 and successfully build both my .Net 7 & my .Net 8 sites (although the metadata for the .Net 8 site is not resolved).

**Additional context**
```
C:\Solutions\OHI\Material.Blazor>docfx\docfx.exe docfxMD3.json --serve
Using .NET Core SDK 7.0.401
Loading project C:/Solutions/OHI/Material.Blazor/Material.Blazor.MD3/Material.Blazor.MD3.csproj
  Determining projects to restore...
C:\Program Files\dotnet\sdk\7.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(156,5): error NETSDK1045: The current .NET
 SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. [C:\Solutions\OHI\Mater
ial.Blazor\Material.Blazor.MD3\Material.Blazor.MD3.csproj::TargetFramework=net8.0]
error: C:\Solutions\OHI\Material.Blazor\Material.Blazor.MD3\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
error: C:\Solutions\OHI\Material.Blazor\Material.Blazor.MD3\obj\Release\net8.0\Material.Blazor.MD3.AssemblyInfo.cs(13,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
error: C:\Solutions\OHI\Material.Blazor\Material.Blazor.MD3\obj\Release\net8.0\Material.Blazor.MD3.AssemblyInfo.cs(14,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
error: C:\Solutions\OHI\Material.Blazor\Material.Blazor.MD3\obj\Release\net8.0\Material.Blazor.MD3.AssemblyInfo.cs(15,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)

...

```

**Comment by filzrev** [comment]
> Using .NET Core SDK 7.0.401

It seems to be resolved to .NET 7 SDK.
Because above log is outputted by following code.
https://github.com/dotnet/docfx/blob/853789762b4ea243e6ba5113dfb8526e2f96682a/src/Docfx.Dotnet/DotnetApiCatalog.cs#L94-L97

On my environment (Windows+docfx2.70.0+.NET 8 SDK Preview7)
Following repository contents can successfully extract metadata with `docfx metadata` command.
https://github.com/Material-Blazor/Material.Blazor

Is is able to gets following logs to distinguish problems.

### 1. Verify installed software versions

```
docfx --version
dotnet --version
dotnet --list-sdks
```

### 2. Get MSBuildLocator's resolve order logs.

**2.1 Create test project with following command.**

```bat
mkdir temp & pushd temp
dotnet new console --framework net8.0
dotnet add package Microsoft.Build.Locator
```
**2.2. Edit `Program.cs` with following content**

```cs
using Microsoft.Build.Locator;
var instances = MSBuildLocator.QueryVisualStudioInstances(VisualStudioInstanceQueryOptions.Default);
foreach(var instance in instances)
    Console.WriteLine($"Version: {instance.Version}, Path: {instance.MSBuildPath}");
```

**2.3. Gets result logs**
```bat
dotnet run
```

**Comment by yufeih** [comment]
As a workaround, turn on [allowcompilationerrors](https://dotnet.github.io/docfx/reference/docfx-json-reference.html#allowcompilationerrors). 2.59.4 works because it silently ignores compilation errors.

**Comment by MarkStega** [comment]
@filzrev

Here is the requested feedback

**dotnet --info output:**
```
C:\Solutions\TemporarySolutions\ConsoleApp1>dotnet --info
.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  6.0.413 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

C:\Solutions\TemporarySolutions\ConsoleApp1>
```
**Output from docfx --version**
```
C:\Solutions\OHI\Material.Blazor>cd docfx

C:\Solutions\OHI\Material.Blazor\DocFx>docfx --version
2.70.0+78b4679954c0d9c73488fb118d3e07abba3717da

C:\Solutions\OHI\Material.Blazor\DocFx>
```
**Output from console app:**
```
Version: 8.0.100, Path: C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3
Version: 7.0.401, Path: C:\Program Files\dotnet\sdk\7.0.401
Version: 6.0.413, Path: C:\Program Files\dotnet\sdk\6.0.413
```

**Comment by MarkStega** [comment]
@filzrev 

Is #9015 the problem? It seems that instead of excluding a preview version of an sdk in code it would be better to suggest use of global.json.

**global.json content:**
```
{
  "sdk": {
    "version": "7.0.401",
    "rollForward": "disable",
    "allowPrerelease": true
  }
}
```

**In my environment with a .net8 preview I can easily exclude the preview. Here is the same console output of the build locator with the global.json as above:**
```
C:\Solutions\TemporarySolutions\ConsoleApp1>dotnet run
Version: 7.0.401, Path: C:\Program Files\dotnet\sdk\7.0.401
Version: 6.0.413, Path: C:\Program Files\dotnet\sdk\6.0.413

C:\Solutions\TemporarySolutions\ConsoleApp1>
```

**Comment by MarkStega** [comment]
@yufeih 

Thanks, the allow errors is a successful workaround and at least I get the articles published for now.

**Comment by filzrev** [comment]
@MarkStega
Thanks for your response.

It seems you are using `self-contained` version of docfx that is published at [docfx release page](https://github.com/dotnet/docfx/releases/tag/v2.70.0) 

This version is build with targeting .NET 7, and don't support  .NET8 project.
I thought it's required to use NuGet distributed version docfx to build NET8 projects. 

> Is https://github.com/dotnet/docfx/pull/9015 the problem?
> It seems that instead of excluding a preview version of an sdk in code it would be better to suggest use of global.json.

That PR affects only test projects. 
So `docfx.exe` should not be affected by these changes.
And `global.json` approach require to specifing SDK version(6/7/8) explicitly so I selected to filter preview SDK in code.

**Note:**
Recently .NET 7 SDK(`7.0.400`) is released.   
So #9015 workaround (for VS preview installed environment) is not required anymore.   
I'll create PR later.

**Comment by MarkStega** [comment]
@filzrev 
I switched to the 'dotnet tool' version of docfx. When I run it, it still uses .Net core SDK 7.0.401

**Comment by filzrev** [comment]
@MarkStega 

> I switched to the 'dotnet tool' version of docfx. When I run it, it still uses .Net core SDK 7.0.401.

I've tested docfx build with your repository contents with following steps.
1.  Clone git repository (https://github.com/Material-Blazor/Material.Blazor)
2.  Switch to `vNext` branch
3.  Run `docfx  docfx.json`

docfx command is successfully completed. And `.NET Core SDK 8.0.100` is used for metadata extraction on my environment.
I don't know why it is resolved to .NET 7 SDK on your environment.

Is it able to check what version is resolved when running following command on `Material.Blazor folder`.
> dotnet --version

---

> I am not certain what you mean by a 'test project'

`RegisterNonPreviewSdkInstance` is called  by `docfx.Tests` project's `ModuleInitializer`.
So it should be executed when running `docfx.Test` related tests only.

When running `docfx.exe`.  DotnetApiCatalog's `EnsureMSBuildLocator` should be used.

> but it seems that the filtering of preview sdk's is happening more broadly. 

Yes. `RegisterNonPreviewSdkInstance` filter .NET 8 SDK preview also.
It's intentional behaviors. Because older version of .NET 8 preview SDK (preview.6?).
Always failed to execute metadata extraction by problems that are related  to `Nuget.Framework`.

**Comment by MarkStega** [comment]
I think that the issue is that the release version of 2.70.0 found on the github.com/dotnet/docfx/releases works differently than the 2.70.0 installed with 'dotnet tool install docfx -g' command.

The published release ignores the preview .Net 8 release, the toll installed version uses the preview.

Why is there a difference between the two?

**Comment by filzrev** [comment]
> the github.com/dotnet/docfx/releases works differently than the 2.70.0 installed with 'dotnet tool install docfx -g' command.

docfx that is published to [release page](https://github.com/dotnet/docfx/releases/tag/v2.70.0) is build
with targeting `net7.0` and .NET 7 runtime is included.

https://github.com/dotnet/docfx/blob/main/.github/workflows/release.yml#L33-L38

On the other hand. NuGet package version's docfx.exe contains `net6.0`/`net7.0`/`net8.0` version separately. 
So if .NET8 SDK installed environment.  `net8.0` version docfx is used by default.

**Comment by Logerfo** [comment]
Although it seems to be using the version 8.0.100 of the SDK, I'm getting [errors](https://github.com/valamistudio/vspoll.api/actions/runs/6877805884/job/18706126446) when using C# 12 features which AFAIK are not in preview anymore.

**Comment by HexMerlin** [comment]
Has anyone been able to build a DocFx site for a project using .NET 8.0 and C# 12 features, yet ?
I have not succeeded, so I am thankful for any input.

**Comment by Logerfo** [comment]
@MarkStega 
> Tool 'docfx' (version '2.[7](https://github.com/valamistudio/vspoll.api/actions/runs/6877805884/job/18706126446#step:7:8)3.2') was successfully installed.
> ...
>  error CS8652: The feature 'primary constructors' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.

The solution builds and runs just fine, but DocFX throws these errors for me.

**Comment by MarkStega** [comment]
@Logerfo 

I can't help with that error but I notice that I have 2.74.1 installed as the current version. If you still have an issue after updating I'd suggest a new issue is appropriate...

**Comment by Logerfo** [comment]
@MarkStega updating solved my problem, thanks!
