### ISSUE TITLE
[Bug] Template bug, modern+default template translation

### ISSUE THREAD

**Issue by nicolassaleron** [dotnet/docfx#9069]
**Describe the bug**
I am looking for a way to translate these strings:

* "Filter by title" https://github.com/dotnet/docfx/blob/bef1674be409b4c43b3ab3bd334001045b454da2/templates/modern/src/toc.ts#L127
* "results for" https://github.com/dotnet/docfx/blob/bef1674be409b4c43b3ab3bd334001045b454da2/templates/modern/src/search.ts#L94
* "No results for" https://github.com/dotnet/docfx/blob/bef1674be409b4c43b3ab3bd334001045b454da2/templates/modern/src/search.ts#L87
* "Table  of Content" https://github.com/dotnet/docfx/blob/bef1674be409b4c43b3ab3bd334001045b454da2/templates/default/toc.html.js#L16C20-L16C36

**Expected behavior**
I was expecting to be able to put these strings in the token.json file.

**Comment by MODUSCarstenScholling** [comment]
Great, thank you!
