### ISSUE TITLE
[Feature Request] Using git library to extract git related information

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#9088]
**Is your feature request related to a problem? Please describe.**
Current docfx v2 extracts git related information by invoking `git` command using `CommandUtility.cs`.
It takes about 30-60 milliseconds every calls to get file information.
and when it need to get additional  information (like `committer-date`) it require extra command invoke costs.

**Describe the solution you'd like**
It seems docfx v3 using `LibGit2` to get git information.
I hope these features can backport to v2. If it run faster than current implementation.

**Describe alternatives you've considered**
- Using [libgit2sharp](https://github.com/libgit2/libgit2sharp)

**Comment by filzrev** [comment]
It seems better to using **fully managed** version git reader library.

For example:
- https://www.nuget.org/packages/GitReader
- https://github.com/dotnet/Nerdbank.GitVersioning/tree/main/src/NerdBank.GitVersioning/ManagedGit

I thought following functionalities required to replace git command to library.

### 1. GetRepoRootCommand

**Git Command:** `git rev-parse --show-toplevel`

### 2. GetLocalBranchCommand

**Git Command**: `git rev-parse --abbrev-ref HEAD`

### 3. GetLocalBranchCommitIdCommand

**Git Command:**: `git rev-parse HEAD`

### 4. GetRemoteBranchCommand

**GitCommand:** `git rev-parse --abbrev-ref @{u}`

### 5. GetGitCommiterDate (Currently not included)

**Git Command:** `git log -1 --format=%cI --no-show-signature {filename}`

**Comment by yufeih** [comment]
> It seems better to using fully managed version git reader library.
Fantastic!

**Comment by filzrev** [comment]
@yufeih 
Is it able to re-open this issue?
I thought following problems are resolved at latest GitReader 1.6.0 release.

- [x] Wrong remote URL is returned by GitReader
- [x] Can't get information managed by git submodules.

Remaining Issues
- [ ] Mixed output path separators (`/`,`\`) chars problems (#9337)
- [ ] Cache GitReader's `PrimitiveRepository` instance. (As far as I've confirmed it's safe to be called by multiple thread)

**Comment by yufeih** [comment]
`GitReader` has been replaced with a different implementation due to bugs in the library. We should fix the path problem.

**Comment by filzrev** [comment]
>  Can't get information managed by git submodules.

It seems current docfx implementation don't support `git submodule` repository. (Currently, it returns root repository URL)

It needs to implement extra `gitdir:` path lookup when directory contains **`git` file**.
I'll try to create PR that fix this issue later.

**Comment by filzrev** [comment]
Git submodule supports issue is resolved by PR(#9540).

My remaining issue is to get `committer date` (Expected to be used for Sitemap/RSS feed).

> ### 5. GetGitCommiterDate (Currently not included)
> **Git Command:** `git log -1 --format=%cI --no-show-signature {filename}`

It seems complex to get this information from `.git` repository structure without library.
So I'm expected to get this information by using `git.exe` external executable call.
