### ISSUE TITLE
How to register own custom markdig extension in docfx.json configuration file?

### ISSUE THREAD

**Issue by robhanzel** [dotnet/docfx#9099]
Hallo,    
I created my own markdig extension and it works fine in my test project . I am trying to add this extension to my docfx project now and I can't get it to work.

I have installed docfx v. 2.70
Path to my extension assembly :  ./extensions/MyMarkdigExtension.dll    
docfx.json - relevant part of build section:

"markdownEngineName": "markdig",    
"markdownEngineProperties": {    
  "markdigExtensions": [    
    "MarkdigExtension.MyExtension, MyMarkdigExtension.dll"        
  ]
}    

I have a reference to Markdig (0.32.0) in my markdig extension class library    
I get this error when building a docfx project:    
 
Markup failed: Invalid extension `MarkdigExtension.MyExtension, MyMarkdigExtension.dll` from
`MarkdigExtension.MyExtension, MyMarkdigExtension.dll` (Parameter 'extensions').

I tried several configuration options in docfx.json but none of them work for me.    
Can someone tell me what I'm doing wrong and how to get my extension working correctly?

**Comment by filzrev** [comment]
`markdigExtensions` settings is used for markdig **build-in** extensions that is not enabled by default.
As far as I've tested. It seems there is no extensibility point to load custom markdown extensions from docfx plugin Dlls.

Currently It need to create custom exe using `Docfx.App`. And manually register custom extensions.
https://dotnet.github.io/docfx/docs/markdown.html#markdown-extensions
