### ISSUE TITLE
<code> elements should support source and region attributes

### ISSUE THREAD

**Issue by wekempf** [dotnet/docfx#910]
### Functional impact

Sandcastle supported a few XML doc comment extensions that were in heavy use by a lot of code. DocFX not supporting these extensions is inconvenient at best. In this case, though, the loss of the capability is really hard to deal with. Being able to do something similar with overwrite files isn't really a good solution, because it requires a LOT more effort and doesn't keep code documentation with the code.

### Minimal repro steps

You should be able to include something like the following in the triple slash comments.

```
<example>
<code source="..\Examples\SomeSourceFile.cs" region="Example 1" lang="csharp" title="Example 1"/>
</example>
```

### Expected result

The generated metadata should include the following.

```
  example:
  - >-
    <pre>

    <code>the source code found in the file ..\Examples\SomeSourceFile.cs in the region named "Example 1"</code>

    </pre>
```

### Actual result

The generated metadata only includes the following.

```
  example:
  - >-
    <pre>

    <code></code>

    </pre>
```

### Further technical details

See [Taming Sandcastle: A .NET Programmer’s Guide to Documenting Your Code](https://www.simple-talk.com/dotnet/net-tools/taming-sandcastle-a-net-programmers-guide-to-documenting-your-code/) for more on using these attributes.

I'd even be willing to work on this and provide a pull request if I knew this was functionality that would be accepted. I find not being able to use this feature with DocFX to be much more than inconvenient, and feel pretty strongly that this is something that should be supported.

**Comment by vicancy** [comment]
Hi @wekempf , we are very happy to have this feature. Thanks for you continuous contribution to DocFx. 👍

**Comment by jifka** [comment]
The region attribute only seems to be honored in csharp source code, but not when the example is in vb. If you point the source attribute to a vb file the whole vb file contents are pulled into the example, but if you include a region attribute, it fails and nothing is pulled into the example.

**Comment by superyyrrzz** [comment]
@jifka Sounds like a bug. Could you open an issue to track this?
