### ISSUE TITLE
Possible leftover config option "cleanupCacheHistory"

### ISSUE THREAD

**Issue by Lulalaby** [dotnet/docfx#9111]
I tried searching for `cleanupCacheHistory`, but it seems it isn't implemented anywhere anymore.
Could this be possible removed?

![image](https://github.com/dotnet/docfx/assets/14029133/9530ea0a-27f2-4cfd-9c62-a9fa64fd3027)

**Comment by yufeih** [comment]
Yes, we no longer use disk cache due to the removal of incremental build.
