### ISSUE TITLE
[Bug] Filter in TOC not reset

### ISSUE THREAD

**Issue by camilledervout** [dotnet/docfx#9117]
When using the filter in the TOC, if you change section in the navigation bar or reload the page, it is not reset. Even when we return to a page a few days later, the filter is still present

1. Define a filter in the TOC of this page https://dotnet.github.io/docfx/docs/basic-concepts.html
![image](https://github.com/dotnet/docfx/assets/35447715/63c6310b-ba8e-4294-a6db-220d2d3d4261)

2. Change the section by clicking on API in the navigation bar
![image](https://github.com/dotnet/docfx/assets/35447715/5d30db85-f579-49bb-8e7e-6c31a9ecf5e0)

3. The filter was kept in the TOC

It would make more sense for the filter to be reset. 

- OS: Windows
- Docfx version: 2.67.0

**Comment by yufeih** [comment]
The filter text is saved to local storage to survive page reload. It is currently stored at a global location, we could clean the value once the TOC has changed.
