### ISSUE TITLE
Bad contribution URL in multi-project scenarios

### ISSUE THREAD

**Issue by roji** [dotnet/docfx#912]
I'm generating a multi-project site where each project is included as a git submodule in the root directory - conceptual docs get included and everything works right.

The only issue I've run into is the contribution URL. I'm using `fileMetadata` rules to define `_gitContribute` for the different projects:

```json
"fileMetadata": {
  "_gitContribute" : {
    "Npgsql/**.md": {
      "repo": "https://github.com/npgsql/Npgsql",
      "branch": "master"
    }
  }
}
```
.. and so on for other projects.

The URL that gets generated is `https://github.com/npgsql/npgsql.github.io/blob/docfx/Npgsql/doc/index.md/#L1` - note the bad `Npgsql` in there, most probably because of the added Npgsql submodule dir. In other words, it would seem that docfx simply constructs the link path based on the file's path in the documentation repository. This works well as long as we're in a single-repository, single-project scenario, but breaks down with multiple projects.

This could be solved by adding a simple knob, e.g. `cwd` in the `_gitContribute` metadata.

**Comment by qinezh** [comment]
It should be fixed in next release, or you could try to build source code from our dev branch.

**Comment by roji** [comment]
Great, looking forward to turning the contribution links back on!

**Comment by roji** [comment]
Just upgraded to 2.9 and it works great, thanks!

**Comment by qinezh** [comment]
nice!
