### ISSUE TITLE
[Annoyance] No template bundle found for Resource, model will be ignored

### ISSUE THREAD

**Issue by BarkenBark** [dotnet/docfx#9128]
# Issue

When building documentation using `docfx path/to/docfx.json --serve`, I get the following info messages for my assets:

> No template bundle found for Resource, model will be ignored.

The build log looks like:

```
C:\path\to\docfx_project\images\IMG.PNG: No template bundle found for Resource, model will be ignored.
C:\path\to\docfx_project\images\reference.pdf: No template bundle found for Resource, model will be ignored.
C:\path\to\docfx_project\images\logo.svg: No template bundle found for Resource, model will be ignored.
```

## Why address the issue?

For projects with many assets, the build log will be cluttered with this message. This is confusing and disruptive.

# Minimal steps to reproduce

Create a new empty docfx project, add items to the _images_ directory which is included under `"resources"` in the default _docfx.json_ config. Build the documentation.

# Environment

`docfx` version: 2.70.1 (issue not present in version 2.67.5).
`dotnet` version: 7.0.101
OS: Windows

# Additional info

The message that is printed seems to have been introduced in this commit:
https://github.com/dotnet/docfx/blame/9a6f51a8df9054d67d4f3a27980e311ffb729158/src/Docfx.Build.Engine/TemplateProcessors/TemplateModelTransformer.cs#L80

**Comment by VaclavElias** [comment]
I am also experiencing this.

**Comment by rickbrew** [comment]
Same
