### ISSUE TITLE
[Suggestion] Show parent comment if child does not specify

### ISSUE THREAD

**Issue by joshuaavalon** [dotnet/docfx#914]
### Functional impact
Without this function, the comments have to be copied all over the place in order to show up in every classes and interfaces.

### Minimal repro steps
	public interface IHello
	{
		/// <summary>
		///     Print out Hello.
		/// </summary>
		void SaidHi();
	}

	public class Hello : IHello {
		public void SaidHi() {
			Console.WriteLine("Hello!");
		}
	}

### Expected result
`Print out Hello.` show in documentation of `Hello.SaidHi()`.

### Actual result
No documentation shown in `Hello.SaidHi()`.

**Comment by wekempf** [comment]
This is another place were DocFX doesn't support all of Sandcastle's features. I wouldn't want auto-inheritance, but support of `<inheritsdoc/>` is sorely needed.

```csharp
public class Hello : IHello {
        /// <inheritsdoc/>
	public void SaidHi() {
		Console.WriteLine("Hello!");
	}
}
```

**Comment by vicancy** [comment]
Basic support for top-level inheritdoc elements. (#1178)
