### ISSUE TITLE
[Bug] Randomly failed to scroll to anchor when opening docfx site's anchor link

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#9150]
**Describe the bug**
When opening docfx site anchor link.
Browser failed scroll to anchor randomly. 

**To Reproduce**
1. Open anchor link by browser (https://dotnet.github.io/docfx/docs/markdown.html?tabs=linux%2Cdotnet#code-snippet)
2. Sometimes scroll don't works or indicate wrong place.

Another example link without tab content/images. (https://dotnet.github.io/docfx/docs/dotnet-api-docs.html#filter-by-type)
It's scroll to `Filter by UID` randomly.

**Expected behavior**
Always scrolled to specified anchor.

**Context (please complete the following information):**
- Browser: chrome, edge
- Template: default, modern

**Additional context**
This issue might be related to browser's event timing.
https://www.bryanbraun.com/anchorjs/#dont-run-it-too-late.

**Comment by shibaev** [comment]
It seems related to the script that scrolls TOC to the active node. For modern template, it is the `scrollIntoView` call in toc.ts.

**Comment by shibaev** [comment]
[This comment](https://github.com/facebook/react/issues/23396#issuecomment-1557694564) describes problems with `scrollIntoView` implementation in Chromium and possible workarounds.

**Comment by shibaev** [comment]
Does the fix cover the situation when scroll to anchor works before scrolling TOC to an active element? Currently, I see two types of problem in Chrome:
1. TOC scrolling runs before the scrolling to anchor. In that case, TOC is properly scrolled but anchor is not reached.
2. scrollIntoView runs after the scrolling to anchor. In that case, anchor is properly reached but the TOC is not scrolled to an active element.

It looks like the fix may only address the first case.

I also tested the fix on our version of DocFX-based documentation and both issues from cases 1-2 are still there.

**Comment by filzrev** [comment]
It seems scrolling problems are still existing on latest docfx site.

**Urls for tests**
  - https://dotnet.github.io/docfx/docs/markdown.html?tabs=linux%2Cdotnet#code-snippet
  - https://dotnet.github.io/docfx/docs/dotnet-api-docs.html#filter-by-type

**Behaviors when click anchor links**
- Successfully scrolled into anchor link.
- Not scrolled at all
- Scrolled to wrong position before anchor link.

**Comment by shibaev** [comment]
Agree with @filzrev. The scroll issue still happens. For example, https://dotnet.github.io/docfx/tutorial/advanced_support_hyperlink.html#prepare is often loaded like this (pay attention on TOC scrolling):
![image](https://github.com/dotnet/docfx/assets/8813859/c0662b09-0d3b-45b9-adf2-d0d14bdf61c2)

The expected result should look like:
![image](https://github.com/dotnet/docfx/assets/8813859/d57c2c46-7310-4d80-ae2c-25b990bb667b)
