### ISSUE TITLE
[Bug] REST API docs source files will not process

### ISSUE THREAD

**Issue by cedar-ave** [dotnet/docfx#9157]
**Describe the bug**
Since [this commit](https://github.com/dotnet/docfx/commit/bef1674be409b4c43b3ab3bd334001045b454da2#diff-6b3c378f7fb11669ca0d3dbd51d8dfa44f66f74ff7c371a3ed9db2741d98f38f) (as best I can tell), which is part of release [v2.70.1](https://github.com/dotnet/docfx/releases/tag/v2.70.1), and is accompanied by the release note "Add type definition to REST API pages," none of our Swagger JSON files will process. This error is thrown for each file:

```
error ApplyTemplatePreprocessorError: Error transforming model generated from "swagger-file.json" using "RestApi.html.primary.js". To get the detailed raw model, please run docfx with debug mode --debug. Error running Transform function inside template preprocessor: Cannot read property 'forEach' of undefined
```

**To Reproduce**
1. Place Swagger JSON files in a `/restapi` directory
2. Include `/restapi` in docfx.json
3. Run `docfx build`

**Expected behavior**
I would expect the Swagger JSON file to be transformed into HTML REST API reference pages. This has been the case for a long time until this release.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.70.1

**Additional context**
Thank you for any help!

**Comment by cedar-ave** [comment]
The error continues for me! :( Is there any more info I can provide that will help? @yufeih

**Comment by yufeih** [comment]
Is there a minimal repro of a swagger file that you can share?
