### ISSUE TITLE
Internal Errors on Metadata compile [Bug]

### ISSUE THREAD

**Issue by OpCyc-Ben** [dotnet/docfx#9162]
**Describe the bug**
Calls to `DotnetApiCatalog.GenerateManagedReferenceYamlFiles` throw multiple internal errors.
Here is one such error:
`System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.CodeAnalysis.Features, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.'`

**To Reproduce**
1. run `docfx init`.
2. Using Visual Studio 2022, create a new Console Application (C#, .Net 7) inside the autogenerated `src` folder.
3. Paste the following into your solution file:
```xml
<ItemGroup><PackageReference Include="Docfx.App" Version="2.70.0" /></ItemGroup>
```
4. Replace the content of the Program.cs file with the following; hand the call the absolute file path on your disk:
```cs
using Docfx.Dotnet;
await DotnetApiCatalog.GenerateManagedReferenceYamlFiles(@"C:\Projects\docfx_project\docfx.json");
```
5. Hit Debug/Start in the toolbar.

**Expected behavior**
No errors, due to missing references.

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: [e.g. 2.70.0]
- Enabled breaks on external errors in VS.

**Additional context**
Due to circumstances in our project structure, Visual Studio is configured to break on all exceptions.

**Comment by yufeih** [comment]
Does the `FileNotFoundException` causes the `GenerateManagedReferenceYamlFiles` method to throw and fail, or is it only internal exceptions that does not impact the functionality of the method?

If latter, would enable "Just my code" suppress the exceptions during debugging?

**Comment by OpCyc-Ben** [comment]
The internal exceptions do not cause the program to fail, and "just my code" does prevent vs from breaking on the exceptions. However, enabling just my code isn't an option in our environment.

Thanks for pointing me to that though. 👍

**Comment by OpCyc-Ben** [comment]
I actually just remembered that .editorconfig files can be placed in a project folder to override global editor settings...
