### ISSUE TITLE
[Bug] Packages newer than 2.70.0 not appearing on nuget.org

### ISSUE THREAD

**Issue by chrisvanderpennen** [dotnet/docfx#9167]
**Describe the bug**
For some reason, aside from the dotnet tool package `docfx`, newer versions of the other packages eg. DocFx.App aren't showing up on nuget.org.

**To Reproduce**
1. Navigate to https://www.nuget.org/packages/Docfx.App/#versions-body-tab

**Expected behavior**
2.70.2 appears in the version list

**Additional context**
Looks like the publish worked OK in the GitHub action so I'm not really sure what's going on here - https://github.com/dotnet/docfx/actions/runs/6068399955/job/16461428764#step:5:10

**Comment by yufeih** [comment]
The packages are now published and listed on NuGet
