### ISSUE TITLE
Inconsistency in generics hyperlink

### ISSUE THREAD

**Issue by joshuaavalon** [dotnet/docfx#917]
Platform: Windows
Version: 2.8

### Minimal repro steps
```
/// <summary>
///     Using Breadth First Search to find path with given <see cref="IGraph{T}" />
///     from <paramref name="start" /> to <paramref cref="goal" />.
/// </summary>
/// <typeparam name="T">Graph node.</typeparam>
/// <param name="graph">Graph</param>
/// <param name="start">Start of the path.</param>
/// <param name="goal">End of the path.</param>
/// <returns>
///     Path from <paramref name="start" /> to <paramref cref="goal" />.
///     Empty if no path can be found.
/// </returns>
public static IEnumerable<T> BreadthFirstSearch<T>(IGraph<T> graph, T start, T goal)
{
	...
}
```

### Expected result
`IGraph<T>` is  hyperlinked.

### Actual result
In summary, `IGraph<T>` is  hyperlinked. However, in parameter, seealso, only `IGraph` is  hyperlinked. `<T>` is shown as plain text.

This may related to #896 and #900.

**Comment by joshuaavalon** [comment]
Here is a reference image.
![sc](https://cloud.githubusercontent.com/assets/7152420/20523178/c2be30e4-b0ee-11e6-9ebb-8c472694899d.png)

**Comment by vwxyzh** [comment]
@joshuaavalon this behavior is as designed.

1. Why IGragh<T> in parameter is plan text?

   ```cs
   public static IEnumerable<T> BreadthFirstSearch<T>(IGraph<T> graph, T start, T goal)
   ```
   If the parameter is `IGraph<string>`, we should create two link, `IGraph` is link to class `IGraph<TNode>`, `string` is link to string class.
   In this method, `T` is define by method, i.e. BreadthFirstSearch\<***T***\>.
   We can not create a link to this method, and actually we are just here, so we write it as plan text.

2. Why `<see cref="IGraph{T}" />` in summary is one hyper link?

   After Roslyn compile, we will get ``<see cref="YourNamespace.IGraph`1">``, so we will show the name of IGraph, i.e. `IGraph<TNode>`.

**Comment by joshuaavalon** [comment]
@vwxyzh Thank you for your explanation. I will close this issue then.
