### ISSUE TITLE
How to update documentation for changed and new files?

### ISSUE THREAD

**Issue by mbielecki** [dotnet/docfx#918]
I have many projects in docFX at the moment. After the release of a new version of the project, when I run the script that builds the documentation it creates the entire documentation for all of the projects. How to update documentation only for new and modified files without creating everything from scratch?

Thanks for help.

**Comment by vwxyzh** [comment]
We are working on incremental build.
It is partial work by now, you can find [some options](http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.BuildJsonConfig.html#Microsoft_DocAsCode_BuildJsonConfig_IntermediateFolder) in config.

**Comment by superyyrrzz** [comment]
Close as already support
