### ISSUE TITLE
[Feature Request] Remove keepFileLink option from config

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#9181]
**Is your feature request related to a problem? Please describe.**

There is document about `keepFileLink` config that is used by `incremental build`.
https://dotnet.github.io/docfx/reference/docfx-json-reference.html#keepfilelink
> A file link will be created by incremental build and copy resource file.

As far as I've confirmed. `keepFileLink` option is not used by current implementation.

**Describe the solution you'd like**
Remove or deprecate `keepFileLink` option.

**Additional context**
`keepFileLink` option is used by following `Dereference` phase.
https://github.com/dotnet/docfx/blob/9ec2d2c6bf8b42509d64301c120b599236a629c6/src/Docfx.Build.Engine/DocumentBuilder.cs#L160-L174

But currently OutputFileInfo's `LinkToPath` property seems almost be null on normal usage.
Because [TemplateModelTransformer::GetLinkToPath](https://github.com/dotnet/docfx/blob/9ec2d2c6bf8b42509d64301c120b599236a629c6/src/Docfx.Build.Engine/TemplateProcessors/TemplateModelTransformer.cs#L219-L228) returns null.

On test project. Above `GetLinkToPath` return non-null value.
And `LinkToPath` property is set by following methods.

- [ManifestFileWriter::Copy](https://github.com/dotnet/docfx/blob/9ec2d2c6bf8b42509d64301c120b599236a629c6/src/Docfx.Common/FileAbstractLayer/ManifestFileWriter.cs#L38)
- [ManifestFileWriter::Create](https://github.com/dotnet/docfx/blob/9ec2d2c6bf8b42509d64301c120b599236a629c6/src/Docfx.Common/FileAbstractLayer/ManifestFileWriter.cs#L64)

**Comment by filzrev** [comment]
Older docfx version (`v2.61.0`) seems to work as documented behaviour. (When run with `--keepFileLink` parameter)

> If set to true, docfx does not dereference (i.e., copy) the file to the output folder, instead, it saves a link_to_path property
> inside manifest.json to indicate the physical location of that file. A file link will be created by incremental build and copy resource file.

Latest docfx drop incremental build feature. so above documented behavior might be changed?

Currently resource files and template resources are overwritten every time.
It might be better to introduce a `Copy if newer` feature like MSBuild.
By comparing LastWriteTime and length check.

**Comment by filzrev** [comment]
I've created separate issue (#9183) for `copy if newer` feature.

In this issue. It need to discussing `keepFileLink` behavior.

**Available options**
- Bring back older docfx version's `keepFileLink` behavior.  
  (When option specified. don't copy resource files. instead keep `link_to_path` inside `manifest.json`)
- Keep current docfx behavior. and remove `keepFileLink` option.  
   In this case. build is slower on `build system` scenarios described above.  
   (It might be unacceptable when there are lot of resource files (e.g. `.png`/`.pdf`))

**Comment by yufeih** [comment]
Seems like optimizing for resource copying using `--keepFileLink` isn't worth the added complexity. Let's go for option `2` while reusing the incremental copy sementics in #9369
