### ISSUE TITLE
[Feature Request] Remove `localSearch` function from `default` template'

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#9193]
**Is your feature request related to a problem? Please describe.**
It seems there is code for worker is not supported environment.
https://github.com/dotnet/docfx/blob/0ce4839028d461e7fb1431414c7bd9820ecebf37/templates/default/styles/docfx.js#L131-L136

But when running this code path.  It failed because `lunr.js` is not defined.

**Describe the solution you'd like**
Remove `localSearch` function from `default` template's script.
Because major browsers are already supports web worker APIs already.

**Comment by yufeih** [comment]
Looks good, do you want to send a PR for this?

**Comment by filzrev** [comment]
OK. I'll send PR later.
