### ISSUE TITLE
[Bug] .NET API bug "must have an implementation part because it has accessibility modifiers."

### ISSUE THREAD

**Issue by xavierjohn** [dotnet/docfx#9203]
**Describe the bug**
Partial methods results in error "must have an implementation part because it has accessibility modifiers."

**To Reproduce**
1. Create a C# project with the following class
```
using System.Text.RegularExpressions;

internal partial class Class1
{
    [GeneratedRegex("\\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\\Z", RegexOptions.IgnoreCase, "en-US")]
    private static partial Regex EmailRegEx();
}
```
2. Compile with docfx

**Expected behavior**
Expect the code to compile using DocFx. The code compiles fine in Visual Studio.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: [2.70.3+3968fc5e92ebc2e4a2d97df0105000af2ec7eb82]
- .NET version: [.NET Core SDK 7.0.401]

- `docfx.json` config

```json
// Paste docfx.json config, remove sensitive info
```

- Exceptions

```csharp
// Paste the full exception with stacktrace here, remove sensitive info
```

- Errors and warnings

```csharp
// Paste warnings or errors related to this bug here, remove sensitive info
Class1.cs(7,34): error CS8795: Partial method 'Class1.EmailRegEx()' must have an implementation part because it has accessibility modifiers.
```

- .NET info

```csharp
// Paste `dotnet --info` output here
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.401\

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.414 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]
```

**Additional context**
This is the actual code I am trying to generate documentation for.
https://github.com/xavierjohn/FunctionalDDD/blob/main/CommonValueObjects/src/EmailAddress.cs

**Comment by yufeih** [comment]
At first glance it seems the project system used by docfx does not invoke code generators. Not sure if there is a flag in Roslyn to suppress errors due to not running code generators.

**Comment by filzrev** [comment]
Build successfully completed when removing `"en-US"` parameter. 
It seems `GeneratedRegex` source generator silently failed. if non-supported culture name specified.

Currently docfx enable `InvariantGlobalization` mode.
But If there is scenario that require specific culture information.
It need to revert #8893. (And enable related analyzer rules to remove culture dependent code)

**Comment by yufeih** [comment]
@xavierjohn it seems the regex is culture independent, is it possible to remove `en-US` as a workaround?

**Comment by xavierjohn** [comment]
Sure, I will remove culture and give it a try. Thanks.
