### ISSUE TITLE
[Bug] Overwrite files not applied to pdf export

### ISSUE THREAD

**Issue by Phildor92** [dotnet/docfx#9204]
**Describe the bug**

Overwrite files are not applied when exporting to pdf. When building the documentation the warning "DuplicateIds" is logged for each of the overwrite files

**To Reproduce**
1. Have an overwrite file for a metadata object
2. Add a pdf section to the docfx.json
3. Build the documentation

**Expected behavior**
The documentation in the PDF matches the web version and overwrite files are applied

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: 2.70.3+3968fc5e92ebc2e4a2d97df0105000af2ec7eb82

**Comment by yufeih** [comment]
Addressed in v2.73.0 with [a new PDF engine](https://dotnet.github.io/docfx/docs/pdf.html).
