### ISSUE TITLE
highlight is not defined

### ISSUE THREAD

**Issue by Zoolook1979** [dotnet/docfx#924]
When searching, the handleSearchResults function in docfx.js calls "highlight" in order to highlight the matching keywords in the rendered search results:

`highlight($('#search-results>.sr-items *'), word, "<strong>");`

However, there is no such function, so an error is thrown:

`Uncaught ReferenceError: highlight is not defined(…)
(anonymous function) @ docfx.js:252
onPageClick @ docfx.js:250
dispatch @ docfx.vendor.js:3
r.handle @ docfx.vendor.js:3
trigger @ docfx.vendor.js:3
(anonymous function) @ docfx.vendor.js:3
each @ docfx.vendor.js:2
each @ docfx.vendor.js:2
trigger @ docfx.vendor.js:3
show @ docfx.vendor.js:38
c @ docfx.vendor.js:38
e.fn.twbsPagination @ docfx.vendor.js:38
handleSearchResults @ docfx.js:228
worker.onmessage @ docfx.js:138`

Also, subsequent searches will not return correct results due to the above error.

Commenting out the call to highlight() seems to fix the problem with incorrect search results.

**Comment by qinezh** [comment]
Could you provide with steps to repro it? The full text search works well in our [Documentation site](https://dotnet.github.io/docfx)

**Comment by qinezh** [comment]
Thanks @Zoolook1979 , the bug would be fixed in next release.
