### ISSUE TITLE
 Can't import: MyPostProcessor: No export was found for the contract 'IPostProcessor "MyPostProcessor"'

### ISSUE THREAD

**Issue by michfuchs** [dotnet/docfx#9246]
DocFX version: 2.70.3
Project built with .NET Core SDK 7.0.401 (also tried .NET 6.0, same behaviour)

Reproducing the issue: 
1. Follow the instructions in the [Documentation](https://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html).
2. Copy the generated assembly to templates/my-template/plugins
3. Build the site

Observed behavior:
- Exception message (see below), PostProcessor does not work

Expected behavior:
- PostProcessor is picked up as the documentation would suggest

Others seem to struggle with the issue as well: 
- https://stackoverflow.com/questions/60062901/how-to-run-docfx-plugins-post-processors-under-docfx-console
- Same issue but marked as fixed: #8740

### Discussed in https://github.com/dotnet/docfx/discussions/9239

<div type='discussions-op-text'>

<sup>Originally posted by **michfuchs** September 25, 2023</sup>
One appraoch to solve #9238 seems to be implementing a custom PostProcessor, as described in the [Documentation](https://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html). 

![image](https://github.com/dotnet/docfx/assets/9607008/a6e96aaa-bf7c-4097-b3e9-9f43f9c8a4cc)

However, I don't seem to be able to load my post processor. 

My docfx.json configuration for the post processors looks like this:

`"postProcessors": [ "ExtractSearchIndex", "MyPostProcessor" ]`

Since ExtractSearchIndex works, I'm confident it's in the right spot.

Step 4 in the documentation specifies where the built dll of the assembly containing the preprocessor should be copied to:
![image](https://github.com/dotnet/docfx/assets/9607008/8cfbcd13-93dd-42da-be11-90ea723a2a01)

I tried several folder options, none seem to work:
![image](https://github.com/dotnet/docfx/assets/9607008/5251e4ed-bd22-4690-bb04-d5471bebd1f4)
![image](https://github.com/dotnet/docfx/assets/9607008/93d936d4-8af1-464d-a36b-ada63e410739)
![image](https://github.com/dotnet/docfx/assets/9607008/e1390d68-1678-4aa2-8dd3-a2ac7d93ecdb)
![image](https://github.com/dotnet/docfx/assets/9607008/d71beab1-00e3-42de-8a2e-c4a9dd683f0d)

I am consistently getting the following error:

```
1>Searching custom plugins in directory ****\802_Documentation\templates\my-template\plugins...
1>6 plug-in(s) loaded.
1>Post processor ExtractSearchIndex loaded.
1>EXEC : warning : Can't import: MyPostProcessor, System.Composition.Hosting.CompositionFailedException: No export was found for the contract 'IPostProcessor "MyPostProcessor"'.
1>   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
1>   at System.Composition.CompositionContext.GetExport(Type exportType, String contractName)
1>   at Docfx.Common.CompositionContainer.GetExport(CompositionHost container, Type type, String name) in /_/src/Docfx.Build.Engine/CompositionContainer.cs:line 41
1>EXEC : warning : Can't find the post processor: MyPostProcessor
```
It was always 6 plug-ins, even before I added the processor, so the plug-in is definitely not picked up.</div>

**Comment by yufeih** [comment]
Is there a DLL that contains `MyPostProcessor` you could share to help us diagnose the issue?

**Comment by michfuchs** [comment]
A version mismatch was responsible for the issue (see answer in#9239). Thanks for your help.

**Comment by alricsans** [comment]
Have you ever had a similar issues in docker containers ? 

On my windows machine, everything works perfectly, but inside a container based on `mcr.microsoft.com/dotnet/sdk:6.0` (or even `7.0`). I get the same error : 
```powershell
warning: Can't import: TagsProcessor, System.Composition.Hosting.CompositionFailedException: No export was found for the contract 'IPostProcessor "TagsProcessor"'.
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport(Type exportType, String contractName)
   at Docfx.Common.CompositionContainer.GetExport(CompositionHost container, Type type, String name) in /_/src/Docfx.Build/CompositionContainer.cs:line 41
warning: Can't find the post processor: TagsProcessor
```

It is exactly the same code, using `docfx` version 2.75.3 and `Docfx.Plugins` and `Docfx.Common` version 2.75.3 also. 
I tried upgrading and downgrading all of those versions accordingly from 2.75.0 to 2.76.0 but nothing woked. 

Did anyone encounter the same issue ? If there is something to do for unix-based OS so that the `Export` attribute works, please let me know.

**Comment by filzrev** [comment]
@alricsans 
Plugin DLL loading failure is reported as `Verbose` level message. 
Is there any logs outputted when running docfx with `--verbose` parameter?

**Comment by alricsans** [comment]
I compared the one that works with the one that does not (with the `--verbose` parameter), and I have no difference until the warning that appears during the `Loading plug-ins and post-processors...` step : 

- Local setup (works fine):
```powershell
Loading plug-ins and post-processors...
Searching custom plugins in directory C:\<project-path>\docs\<my-template>\plugins...
Scanning assembly file C:\<project-path>\docs\<my-template>\plugins\Docfx.TagsGenerator.PostProcessor.dll...
Post processor ExtractSearchIndex loaded.
Post processor TagsProcessor loaded.
Post processor SitemapGenerator loaded.
7 plug-in(s) loaded.
``` 

- Docker container (failing): 

```powershell
Loading plug-ins and post-processors...
warning: Can't import: TagsProcessor, System.Composition.Hosting.CompositionFailedException: No export was found for the contract 'IPostProcessor "TagsProcessor"'.
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport(Type exportType, String contractName)
   at Docfx.Common.CompositionContainer.GetExport(CompositionHost container, Type type, String name) in /_/src/Docfx.Build/CompositionContainer.cs:line 41
warning: Can't find the post processor: TagsProcessor
Post processor SitemapGenerator loaded.
```

Unfortunately I don't see any differences in the first lines (`Skipping assembly`, `Scanning assembly file` and so on)

**Comment by filzrev** [comment]
It seems that the DLL in the `<my-template>\plugins` directory is not searched on docker environment.
Because following lines are not exists on docker logs.

```
Searching custom plugins in directory C:\<project-path>\docs\<my-template>\plugins...
Scanning assembly file C:\<project-path>\docs\<my-template>\plugins\Docfx.TagsGenerator.PostProcessor.dll...
```

Is it able to confirm `<project-path>/docs/<my-template>/plugins` directory is exists on docker build environment?


---
I've also tried to run docfx on docker by using [this Dockerfile](https://github.com/dotnet/docfx/blob/main/Dockerfile)
And it seems to work as expected. (Custom template's plugin directory search log outputted).

```
Searching custom plugins in directory /root/.dotnet/tools/.store/docfx/2.76.0/docfx/2.76.0/tools/net6.0/any/...
Searching custom plugins in directory /opt/prj/docs/templates/custom/plugins...
Post processor ExtractSearchIndex loaded.
...
```
