### ISSUE TITLE
[Bug] Theme Menu

### ISSUE THREAD

**Issue by paulushub** [dotnet/docfx#9282]
**Describe the bug**
The theme menu is not displayed correctly within the browser window, maybe because the search box is not added.

**To Reproduce**
1. docfx init -q
2. docfx build docfx_project\docfx.json --serve

**Expected behavior**
The theme menu to be displayed within the window.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: [v2.71.0](https://github.com/dotnet/docfx/releases/tag/v2.71.0)

**Additional context**
![image](https://github.com/dotnet/docfx/assets/809351/1e258b69-c70f-419c-b21b-3c3d718fd345)

**Comment by paulushub** [comment]
Is there any specification of the SVG logo? Currently porting previous DocFX project, but the logo, which 300 by 300 SVG is not displayed well. The default DocFX logo is 172 by 172, is this required for compliance?
![image](https://github.com/dotnet/docfx/assets/809351/8b218c3b-f6e6-4748-8732-63ddd849d72d)

**Comment by yufeih** [comment]
> is this required for compliance?

No. The display could be improved, probably need a max height constraint on the logo image to match header height.
