### ISSUE TITLE
[Feature Request] Disable TOC in modern template

### ISSUE THREAD

**Issue by cdervout** [dotnet/docfx#9296]
Hello

I want to keep the affix area but disable TOC on one page.
As with the default template, it would be interesting to make the following available : `_disableToc` and `_disableAffix`.
Today, the only option is to create a custom template.

**Comment by paulushub** [comment]
> As with the default template, it would be interesting to make the following available : `_disableToc` and `_disableAffix`.

I do not know if I understand your point. The above options are available:
https://dotnet.github.io/docfx/reference/docfx-json-reference.html

**Comment by cdervout** [comment]
Yes. The ones I'm interested in are only available for the default template : https://dotnet.github.io/docfx/docs/template.html?q=_layout&tabs=default#template-metadata

**Comment by yufeih** [comment]
The the `_layout: landing` option would hide both the TOC and the Affix, as well as removing the extra margin/padding allowing you full control of the content.

**Comment by cdervout** [comment]
Exactly, but I'm only interested in deactivating the TOC, not the affix (for a single page).
