### ISSUE TITLE
View Source links does not generated correctly with modified docfx.json

### ISSUE THREAD

**Issue by joshuaavalon** [dotnet/docfx#930]
Version 2.8.2

### Functional impact
Link to 404 page

### Minimal repro steps
`docfx_project` is inside the project.
```
Solution
     |-docfx_project
     |-ProjectName
```
In `docfx.json`, change the path to src:
```javascript
"src": [
        {
          "files": [
            "../ProjectName/**.csproj"
          ],
          "exclude": [
            "**/obj/**",
            "**/bin/**",
            "_site/**"
          ]
        }
      ]
```

### Expected result
https://github.com/UserName/Solution/blob/master/ProjectName/namespace/class.cs/#LineNumber

### Actual
https://github.com/UserName/Solution/blob/master/docfx/src/namespace/class.cs/#LineNumber

It seems that it uses a hard coded path instead of the relative path in `docfx.json`.

**Comment by vicancy** [comment]
Hi @joshuaavalon , "../" is not supported in our glob pattern now, if you want `docfx` to look upward, please use `src` (meaning source folder) to indicate that. I suppose there should be a warning message when running `docfx`: "Warning: NOTE that `../` is currently not supported in glob pattern, please use `../` in `src` option instead."

Change the `src` part in your `docfx.json` to the following and have a try:
```
"src": [
        {
          "files": [
            "ProjectName/**.csproj"
          ],
          "exclude": [
            "**/obj/**",
            "**/bin/**",
            "_site/**"
          ],
          "src": "../"
        }
      ]
```

**Comment by joshuaavalon** [comment]
@vicancy I noticed that warning. but I was not able to find what does it mean in the documentation. Thank you for your help! I will close the issue.
