### ISSUE TITLE
[Bug] "cwd" in docfx.json (in metadata src element) is broken in 2.71.1

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#9311]
**Describe the bug**

This is a regression in 2.71.1. When a source is specified in the docfx.json metadata using "cwd", the specified file is not found.

**To Reproduce**
Steps to reproduce the behavior (see the zip file as an alternative to doing all of this by hand):

[CwdIssue.zip](https://github.com/dotnet/docfx/files/13042188/CwdIssue.zip)

- Create a "Src" directory with a C# project (in its own directory) under it
- Create a docfx.json file which specifies the C# project *relative* to Src, using a cwd of "Src"
- Run "dotnet docfx metadata" and see the warnings below, with no output

```text
Using .NET Core SDK 6.0.415
No files are found with glob pattern SampleLibrary/SampleLibrary.csproj, excluding <none>, under directory "C:\Users\jonskeet\Issues\docfx\CwdIssue"
warning: No .NET API project detected.
Creating output...
warning: No .NET API detected for .


Build succeeded with warning.

    2 warning(s)
    0 error(s)
```

**Expected behavior**

Appropriate metadata generated

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.71.1

**Additional context**

The exact same example works fine in 2.71.0.

Looking through the file history, it looks like [this commit](https://github.com/dotnet/docfx/commit/540e023df6415306e8a3b074ca37b7334a1c8536) was to blame. Changing 

The commit was labelled as a refactor, but deleted a property - that's *not* refactoring. Additionally, this change was not mentioned in the release notes (and IMO should never have happened in a patch release even if it *had* been 

As a side note: docfx is the dependency I dread upgrading more than any other due to things like this. I really appreciate the tool - but I'm frustrated by the amount of time I've spent over the years changing my build process to deal with breaking changes :(

**Comment by yufeih** [comment]
Apologies for the regression in 2.71.1. As a temporary solution, would it be ok to change `cwd` to `src` in your docfx.json? Thanks for your input and indeed we need a better change management.

**Comment by jskeet** [comment]
I'll need to find out all the places we generate docfx.json (it's a complex project) - but I'll probably try to do that.
