### ISSUE TITLE
[Bug] Cross-reference from markdown to member functions only works when the function has no arguments

### ISSUE THREAD

**Issue by TIS-Tim** [dotnet/docfx#9312]
**Describe the bug***
Cross-reference from markdown to member functions seems to only work for parameterless functions, e.g.

```
Link to `Class1.g`: [g](xref:ClassLibrary1.Class1.g)
```

works and correctly links to `ClassLibrary1.Class1.g()` while

```
Link to `Class1.f`: [f](xref:ClassLibrary1.Class1.f)

Link to `Class1.f(int)`: [f(int)](xref:ClassLibrary1.Class1.f(int))
```

both don't link to `ClassLibrary1.Class1.f(int)`.

Linking from inside the API documentation (`<see cref="ClassLibrary1.Class1.f(int)"/>`, `<see cref="ClassLibrary1.Class1.g()"/>`) works fine.

**To Reproduce**
Run docfx in the docfx_project directory of my test project:
https://github.com/TIS-Tim/docfx-markdown-cross-reference

**Expected behavior**
Generate correct links when cross-referencing API documentation from markdown.

**Context**
- OS: Windows
- Docfx version: 2.71.1+f5c0285f6a8571fbe1fe219e95b2f9add02c732c

**Comment by yufeih** [comment]
The `xref` syntax works a bit differently than `cref`.  This should work: `[](xref:ClassLibrary1.Class1.f(System.Int32))`.

You can find the correct syntax by searching for `uid:` in the generated YAML files.

**Comment by TIS-Tim** [comment]
@yufeih 

Thank you!

You are totally right. The cross-referencing tool obviously doesn't know the C#-specific aliases of the .net types.
