### ISSUE TITLE
[Bug] Upgrade to 2.71.1 breaks API generation

### ISSUE THREAD

**Issue by martintmk** [dotnet/docfx#9315]
**Describe the bug**
In Polly we upgraded the DocFx to version 2.71.1 from version 2.71.0:
https://github.com/App-vNext/Polly/pull/1705

This caused the following deployment change:
https://github.com/App-vNext/Polly/commit/99fd1b30d09bef0ac36cef8bfbcaa41511327206#diff-b6331d69d43f82568b37f3431243dbe7c3bfc9b656ee87eed347874c5a427032

As a result, our API docs are no longer rendering:
https://www.pollydocs.org/api/

**To Reproduce**
1. Checkout Polly codebase
2. Go to `/docs` folder and run `dotnet docfx --serve`

**Expected behavior**
The API docs should be build.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.71.1

**Comment by yufeih** [comment]
Is it the same reason as #9311?
