### ISSUE TITLE
Reference of bootstrap 3.4.1 that is not supported anymore

### ISSUE THREAD

**Issue by belairgrics** [dotnet/docfx#9326]
https://github.com/dotnet/docfx/blob/5082454fe5b2e24602e9183717f114794c11968e/templates/package.json#L22C4-L22C4

Are you plannning upgrading to a more recent version of bootstrap ? 

SonarQube is reportig it as an issue 
![image](https://github.com/dotnet/docfx/assets/148768919/9d40cc98-da63-45dd-a2c0-7a3da0236334)

**Comment by yufeih** [comment]
The plan is to gradually deprecate the default template (uses bootstrap 3.x) and move to `modern template` which uses latest bootstrap 5.x

**Comment by belairgrics** [comment]
thanks for the infos

**Comment by jcianci12** [comment]
Hi @yufeih im reaching out as im a maintainer of another internal web application. The lack of long term support of bootstrap 3 has put a sour taste in my mouth and im wondering if its worthwhile to create a fork of bootstrap 3 to keep it alive. I wouldn't mind upgrading but there are alot of breaking changes in the updates.

**Comment by paulushub** [comment]
Tools like docfx will try to use the latest version of each library for security reasons. 
In this case, though, I think bootstrap 5 made things easier for the docfx.
That said, I was surprised to see the newly released Nuget site using bootstrap 3!
