### ISSUE TITLE
[Bug] no Unicode in PDF?

### ISSUE THREAD

**Issue by sliekens** [dotnet/docfx#9329]
**Describe the bug**
I have some markdown containing Chinese which is rendered incorrectly in the PDF.

It seems UTF-8 is not the default character set for PDF?

![image](https://github.com/dotnet/docfx/assets/1583241/feee8816-a738-4975-8720-8262cc7485f7)

When rendered as PDF:

![image](https://github.com/dotnet/docfx/assets/1583241/c0c6562b-1e83-4d8e-81d3-69e3e391e3d1)

**To Reproduce**

You are welcome to clone my repository and build the docfx.json for yourself: https://github.com/sliekens/gw2sdk

**Expected behavior**

Unicode character support should be the default mode for PDF.

**Context (please complete the following information):**
- OS: Debian 11 (Bullseye)
- Docfx version: 2.71.1

**Additional context**
Let me know if you have any questions.

**Comment by yufeih** [comment]
Addressed in v2.73.0 with [a new PDF engine](https://dotnet.github.io/docfx/docs/pdf.html).
