### ISSUE TITLE
[VS Code DFM extention] Multi-byte Language is not supported well

### ISSUE THREAD

**Issue by chancewen** [dotnet/docfx#933]
I installed the DfmPreview plugin of Visual Studio Code.

When there are  characters in multi-byte languages, for example, Chinese, the preview fails.

### Minimal repro step
1. Copy and paste the text  “图1这是一句话。” into vs code editor.
2. Use command of "Dfm preview to the side" (Ctrl-K Q).
 
### Expected result

The preview is correct using default markdown parser.
 
![r2](https://cloud.githubusercontent.com/assets/1862520/20665439/a5398860-b59a-11e6-847a-15b1d9459dbd.PNG)

### Actual result

The preview is wrong  using DFM parser.

![r1](https://cloud.githubusercontent.com/assets/1862520/20665391/72ba3b82-b59a-11e6-803f-d6a2156b6176.PNG)

**Comment by qinezh** [comment]
Have tried several times, I just can't repro it...

![image](https://cloud.githubusercontent.com/assets/15644078/20695778/7bef7098-b629-11e6-9f93-23f08dc93511.png)

**Comment by chancewen** [comment]
Hi @qinezh,

Thank you for your reply.

I wonder if the problem is related to the encoding of the file. I tried many time with different encoding, but did not resolve.

I uploaded it here: [test.zip](https://github.com/dotnet/docfx/files/618175/test.zip)

Could you please have a try on the file?

**Comment by qinezh** [comment]
I have tried the file you provided, but still can't repro it...
BTW, do you use the latest version of Dfmpreview?

**Comment by vwxyzh** [comment]
What's your windows setting?
Control Panel/Language/Location/Administrative/Language for non-Unicode programs

**Comment by chancewen** [comment]
@qinezh : 

I am using the latest version of Dfmpreview and VS Code, Windows 10 Home Edition of Chinese, which is preinstalled with Surface pro 4, and being updated regularly.

@vwxyzh :

I checked the settings you mentioned above, and I think  it is set to the correct language .

**Comment by qinezh** [comment]
great, it seems to be the key step to repro it.

**Comment by vicancy** [comment]
Hi @chancewen The issue should be resolved now.

**Comment by vaporz** [comment]
Hi, 我今天遇到了相同的问题，
Visual Studio Community 2019，版本16.1.6，
安装了NuGet包docfx.console，版本v2.44.0，
生成的页面不能正常显示中文。

我检查了前面提到的系统设置，与前面图中相同。

**Comment by superyyrrzz** [comment]
@vaporz Sorry I cannot access https://vaporz.github.io/Kift/index_cn.html as 404.

Could you try adding `"markdownEngineName": "markdig",`? This is the markdown engine we recommend now.

**Comment by vaporz** [comment]
@superyyrrzz Sorry, the page is now restored:
https://vaporz.github.io/Kift/articles/struct_cn.html
It's generated with following config file:
https://github.com/vaporz/Kift/blob/doc_debug/server/docfx.json
I added `"markdownEngineName": "markdig"`, but it seems not work.
