### ISSUE TITLE
[Bug] Invalid Edit-this-page URL after update to docfx v2.72.0

### ISSUE THREAD

**Issue by bkoelman** [dotnet/docfx#9337]
Comparing the generated website with the output from 2.71.1:
1. Incorrect remote URL: "json-api-dotnet" changed to "verdie-g" (which is a fork of the project that I cloned a while ago)
2. Backslashes instead of forward slashes: "/api/index.md/#L1" changed to "\api\index.md/#L1"

Before update:
```html
<meta name="docfx:docurl" content="https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/docs/api/index.md/#L1">
...
<a href="https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/docs/api/index.md/#L1" class="edit-link">Edit this page</a>
```

After update:
```html
<meta name="docfx:docurl" content="https://github.com/verdie-g/JsonApiDotNetCore/blob/master/docs\api\index.md/#L1">
...
<a href="https://github.com/verdie-g/JsonApiDotNetCore/blob/master/docs\api\index.md/#L1" class="edit-link">Edit this page</a>
```

**Context:**
- OS: Windows
- Docfx version: 2.71.1

Output from `git remote -v`:
```
github-desktop-verdie-g https://github.com/verdie-g/JsonApiDotNetCore.git (fetch)
github-desktop-verdie-g https://github.com/verdie-g/JsonApiDotNetCore.git (push)
origin  https://github.com/json-api-dotnet/JsonApiDotNetCore.git (fetch)
origin  https://github.com/json-api-dotnet/JsonApiDotNetCore.git (push)
```
Output from `git config --get remote.origin.url`:
```
https://github.com/json-api-dotnet/JsonApiDotNetCore.git
```

**Comment by yufeih** [comment]
Seems to be a bug in `GitReader`.

**Comment by filzrev** [comment]
> 2. Backslashes instead of forward slashes: "/api/index.md/#L1" changed to "\api\index.md/#L1"

Mixed path separator char problems on Windows environment is still occurred on latest docfx version. (`2.73.1`)
It's seems not related to `GitReader` library. 
But caused by following path strings concatenation.
https://github.com/dotnet/docfx/blob/d3a342c81886bb77c309c83b5a62aa4c6d9faa8e/src/Docfx.Common/Git/GitUtility.cs#L45
