### ISSUE TITLE
Latest release download not listed in assets

### ISSUE THREAD

**Issue by tlstice** [dotnet/docfx#9350]
To reproduce:

1. Go here: https://api.github.com/repos/dotnet/docfx/releases/latest. Note that assets seems to be blank.
2. Attempt to download docfx.zip. The file is not found.
3. Go to https://github.com/dotnet/docfx/releases/download/v2.72.1/docfx.zip. The file is not found

**Expected behavior**
Latest version of docfx.zip (v2.72.1) should download.

Context (please complete the following information):

OS: Windows
Docfx version: v2.72.1
.NET version: Tried with both .NET SDK 5.0.408(x64) and .NET SDK 6.0.416(x64)

**Comment by yufeih** [comment]
There were some problems with NuGet signing key setup causing publish failure. Now resolved.
