### ISSUE TITLE
Create PDf won't work

### ISSUE THREAD

**Issue by JM2K69** [dotnet/docfx#9370]
**Describe the bug**
The Link in the Toc with the icon don't appear and i have an error when running the command docfx pdf

**To Reproduce**
1. Clone the project
2. In folder docs
3. run docfx build
4. run docfx pdf

**Expected behavior**
```
c:\ docfx pdf
Completed in 69.5153 milliseconds
Error: Object reference not set to an instance of an object.
```
**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.72.1

**Additional context**

**Comment by yufeih** [comment]
Aha, the `docs/dodfx.json` project in this repo has been migrated to a soon-to-be-released new PDF engine. But yes it shouldn't throw NRE on old versions.
