### ISSUE TITLE
Exploded package size and quality concerns

### ISSUE THREAD

**Issue by bkoelman** [dotnet/docfx#9396]
Package size at https://www.nuget.org/packages/docfx changed from 51 MB to 199 MB since v2.73.0. Is that really needed?

I suspect this is related to the new PDF rendering, which I'm not interested in. However, looking at the output diff, every HTML page now contains the following extra line:
```
<meta name="loc:downloadPdf" content="Download PDF">
```

Do you guys ever diff the HTML output with the previous version before release?
Or even run it through an HTML validator? For example, why does every file contain `</article>` without an opening tag?

I've been getting updates for docfx frequently since I turned on Dependabot updates, but now I'm considering turning that off. It just takes too much time to verify everything and report back. For example, see https://github.com/dotnet/docfx/issues/9337#issuecomment-1798876066 which was supposed to be fixed, but apparently was never tested. I feel like being the beta tester of your product, this is not very professional.

**Comment by ipanin** [comment]
Not only has the package size increased 4 times due to the fact that it includes (and unpacks!) node for _all_ platforms. But it also downloads Chromium and ffmpeg (407 MB on disk) at the first execution of the `docx pdf` command. Moreover, the download may not be fast, it took me 40 minutes. And if the assembly machine does not have Internet access and it takes all packages from the private Artifactory?

**Comment by filzrev** [comment]
docfx package size is increasing constantly.
And it takes 248 MB fir  `docfx v2.76.0` nupkg.

And extracted files are takes about `1.17GB` at following directories.

|                                      |                                 |                                                   |
|--------------------------|-----------------------|-----------------------------------|
| nupkg extracted files   | 1.17GB                     | Extracted to `%UserProfile%\.nuget\packages\docfx`
| .NET Global Tool package | 1.17 GB | Extracted to `%UserProfile%\.dotnet\tools\.store\docfx`
