### ISSUE TITLE
Add support for GitLab

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#942]
It seems like the `View Source` and `Improve this Doc` buttons currently only support GitHub and VSTS (as per [this documentation](http://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html)). It would be nice to have also support for other Git hosts. In our case it would be an GitLab on-prem instance.

**Comment by qinezh** [comment]
Hi @pascalberger , you could try add `"_gitUrlPattern": "github"` in global metadata to do it currently.

**Comment by pascalberger** [comment]
Thanks @qinezh. But adding ` "_gitUrlPattern": "github"` doesn't seem to have any effect. 

Please note that I'm using GitLab and not GitHub.

**Comment by qinezh** [comment]
I have already checked it, it works well for GitLab. Could you provide with the `docfx.json`?

**Comment by pascalberger** [comment]
Sorry, managed to get it working now with  `"_gitUrlPattern": "github"`

**Comment by MJ1823** [comment]
> Sorry, managed to get it working now with `"_gitUrlPattern": "github"`. Thanks for your help.

How did you manage to get it working ? I am facing the same issue

**Comment by superyyrrzz** [comment]
@MJ1823 Are you adding to this section?https://github.com/dotnet/docfx/blob/fb426d81113cfe5be65572600e98a825bd3358bd/Documentatio n/docfx.json#L44-L49

**Comment by MJ1823** [comment]
Yes, we are using a separate Global metadata file, I am adding in the global metadata file

**Comment by MJ1823** [comment]
@superyyrrzz What else should I check ?

**Comment by superyyrrzz** [comment]
`--exportRawModel` to examine the `.raw.json`. Whether it contains git info. You can compare it with the result of https://github.com/docascode/docfx-seed to see the difference.

**Comment by MJ1823** [comment]
`toc.raw.json` contains 
```
  "_gitContribute": {
    "repo": "https://gitlab.mycompany.net/BI/sites/website"
  },
  "_gitUrlPattern": "github",
```
but the option is still not coming up on the website

**Comment by superyyrrzz** [comment]
@MJ1823 Not sure of it. You can create another issue for your problem with repro steps.
