### ISSUE TITLE
Breadcrumb with multiple linked toc.yml

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#944]
I've created a documentation only with conceptual documents over different folders with several toc.yml linked together.
This works generally, but at some points down in the TOC the breadcrumb gets "reseted" (meaning it shows only the current page).

My structure looks like this:

```
\
  docfx.json
  toc.yml
  index.md
  \Folder1
    toc.yml
    index.md
    \Folder2
      \Folder3
        toc.yml
        index.md
```

Content of `\toc.yml` is:

```
- name Folder1
  href: Folder1/
```

Content of `\Folder1\toc.yml` is:

```
- name Introduction1
  href: index.md
- name Folder3
  href: Folder2/Folder3/
```

Content of `\Folder1\Folder2\Folder3\toc.yml` is:
```
- name Introduction3
  href: index.md
```

`Folder1` is now as expected a navigation menu in the horizontal main navigation and links to `/Folder1/index.html`.
If I move there the breadcrumb is as expected `Folder1 / Introduction1` and in the sidebar there are two navigation items:

* Introduction linking to `/Folder1/index.html`
* Folder 2 linking to `/Folder1/Folder2/Folder3/index.html`

But if I navigate further to `/Folder1/Folder2/Folder3/index.html` breadcrumb is `Folder3` 
instead of the expected `Folder1 / Folder3 / Introduction3`.

Is there a way to get the breadcrumb as I would have expected it on this level?

**Comment by pascalberger** [comment]
Not sure, but maybe this has todo with the [limitation to one level navigations](https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/styles/docfx.js#L292)?

**Comment by vwxyzh** [comment]
http://dotnet.github.io/docfx/tutorial/intro_toc.html#link-to-another-toc-file
`href: Folder1/` and `href: Folder1/toc.md` is different.

**Comment by superyyrrzz** [comment]
Yes, you found the root cause... A workaround is to use [TOC combination](http://dotnet.github.io/docfx/tutorial/intro_toc.html#link-to-another-toc-file). You can try changing `href: Folder2/Folder3/` in `\Folder1\toc.yml` to `href: Folder2/Folder3/toc.yml`.

**Comment by pascalberger** [comment]
Thanks @superyyrrzz. Using TOC combination works for the use case described above, but still fails if going deeper in the navigation:

Assuming content of \Folder1\Folder2\Folder3\toc.yml is:
```yaml
- name Introduction3
  href: index.md
- name Introduction4
  href: Folder4/toc.yml
```

And `\Folder1\Folder2\Folder3\Folder4\toc.yml`:

```yml
- name Introduction4
  href: index.md
```

If I navigate to `/Folder1/Folder2/Folder3/Folder4/index.html` breadcrumb is `Folder1 / Folder 4 / Introduction4` instead of the expected `Folder1 / Folder3 / Folder 4 / Introduction4`.

**Comment by pascalberger** [comment]
Thanks @superyyrrzz! Works now as expected applying the changes from #970
