### ISSUE TITLE
[Question] Adding complementary documentation to an API type with a custom markdown file

### ISSUE THREAD

**Issue by nockawa** [dotnet/docfx#9452]
I generate documentation for a library, this library implements several custom types which are documented using DocXML in the source code.

But I'd like to add custom documentation for a given type through a dedicated markdown file, so that the generated HTML documentation page for this type contains the DocXML's content, followed by the markdown's one.

My understanding is it has something to do with overwrites, I've tried many combinations but couldn't succeed in having the content of a markdown file appearing in the type's documentation page.

Could someone share some light about how to do that?
Many thanks.

**Comment by paulushub** [comment]
@nockawa Maybe use the discussion forum for this request.

**Comment by nockawa** [comment]
Hello @paulushub , I didn't know such thing even existing on GitHub... thanks for pointing it out !
