### ISSUE TITLE
[Feature Request] Add support for PDF headers and footers (from html files)

### ISSUE THREAD

**Issue by Foitn** [dotnet/docfx#9463]
With the old wkhtmltopdf there was the option to add html files to generate a header and footer for the pdf using the --header-html flag.
Now with the new pdf generation library (the chromium one) this option is gone.
It would be great if it were possible to add these headers from html files, in a similar fashion.
Could be the same as for the cover page, so it could look something like this:

```
pdf: true
pdfTocPage: true
pdfFileName: MyAmazingPdf
pdfCoverPage: articles/some-document/0-cover.html
pdfPageHeader: articles/pdf-header.html
pdfPageFooter: articles/pdf-footer.html
# Optionally even
pdfCoverPageNoHeaderFooter: true
```

**Comment by yufeih** [comment]
HTML [header/footer templates](https://playwright.dev/docs/api/class-page#page-pdf-option-header-template) are doable but handling of page numbers in the templates would be tricky.

**Comment by m3koenig** [comment]
Hi, is there an example of that? 
I tried this but there is not the content of the "html" file as header. Instead of this its the path to the file.

**Comment by Foitn** [comment]
I have the same issue, please help me with this.
My html file is not added, only the title.

If I would add the entire html into the template.
When I try to start using it with the default footer, so something like this:
`pdfFooterTemplate: <div style="width: 100%; font-size: 12px;"><div style="float: right; padding: 0 2em"><span class="pageNumber"></span> / <span class="totalPages"></span></div></div>`
I get an error:
`C:\Projects\<myPath>\toc.yml: error InvalidTocFile: C:\Projects\<myPath>\toc.yml is not a valid TOC File: (Line: 5, Col: 37, Idx: 138) - (Line: 5, Col: 37, Idx: 138): While scanning a plain scalar value, found invalid mapping.`

**Comment by stuartm9999** [comment]
> I have the same issue, please help me with this. My html file is not added, only the title.
> 
> If I would add the entire html into the template. When I try to start using it with the default footer, so something like this: `pdfFooterTemplate: <div style="width: 100%; font-size: 12px;"><div style="float: right; padding: 0 2em"><span class="pageNumber"></span> / <span class="totalPages"></span></div></div>` I get an error: `C:\Projects\<myPath>\toc.yml: error InvalidTocFile: C:\Projects\<myPath>\toc.yml is not a valid TOC File: (Line: 5, Col: 37, Idx: 138) - (Line: 5, Col: 37, Idx: 138): While scanning a plain scalar value, found invalid mapping.`

I think you need to escape it with \ like this 

```
pdfFooterTemplate: "<div style=\"width: 100%; font-size: 12px;\"><div style=\"text-align: center; padding: 0 2em\"><span class=\"pageNumber\"><\/span> \/ <span class=\"totalPages\"><\/span><\/div><\/div>"
```
