### ISSUE TITLE
Search not working on root page

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#948]
### Title
I've build a website out of only conceptual documentation and added `"postProcessors": ["ExtractSearchIndex"]` in the `docfx.json` file. While search generally works, the required files are not loaded on the root `index.html` page but search box is shown.

### Functional impact
Entering something in the search box on the root `index.html` file doesn't start search.

### Minimal repro steps
1. Clone [Seed Project](https://github.com/docascode/docfx-seed) (Commit d3bf65df3e54297c8dd3ff86dfed09c34056461f)
2. Run `docfx --serve`
3. Open `http://localhost:8080/index.html`
4. Enter `foo` in the top right search box. No search is started

### Expected result
Search should work on all pages.

### Actual result
Search doesn't work on root `index.html`

### Further technical details
It seems like the JavaScript files required for client search to work are not loaded on the root `index.html` page.

Tested with DocFx 2.8.2.0

**Comment by qinezh** [comment]
Thanks your feedback, the issue would be fixed in next release.
