### ISSUE TITLE
[Bug] Build-Actions not getting executed

### ISSUE THREAD

**Issue by hexxone** [dotnet/docfx#9485]
**Describe the bug**
Seems like Pre-Build actions from other Nuget Packages will not be executed on docfx. Specifically talking about "MinVer".

**To Reproduce**

1. Install MinVer on a new Project
2. Debug the project manually, -> it will receive Correct Assembly Version from git Tags
3. Try to build the project with docfx
4. Error: 
```
error: D:\blabla\obj\Release\net6.0\Myproject.AssemblyInfo.cs(26,55): error CS7034: The specified version string '..' does not conform to the required format - major[.minor[.build[.revision]]] 
```

**Expected behavior**

The pre-Build action from MinVer should get executed and fill the correct AssemblyVersion, before docfx throws an error about it.

```
0>------- Started building project: Myproject
dotnet "C:\Users\Hexx\.nuget\packages\minver\4.3.0\build\../minver/net6.0/MinVer.dll" "D:\blabla\Myproject" --auto-increment "" --build-metadata "" --default-pre-release-identifiers "" --default-pre-release-phase "" --minimum-major-minor "" --tag-prefix "" --verbosity "" --version-override ""
Tagging MinVer as Assembly Version... 0.1.43.11
```

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: 2.74.0

**Additional context**

My .csproj has these special actions:
```

    <ItemGroup>
        <PackageReference Include="MinVer" Version="4.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <Target Name="VersionTarget" AfterTargets="MinVer">
        <PropertyGroup>
            <MinVerPreReleaseTrimmed>$([System.Text.RegularExpressions.Regex]::Replace('$(MinVerPreRelease)', '^[^\.]*\.0', ''))</MinVerPreReleaseTrimmed>
            <AssemblyVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch)$(MinVerPreReleaseTrimmed)</AssemblyVersion>
            <FileVersion>$(AssemblyVersion)</FileVersion>
            <ProductVersion>$(MinVerVersion)</ProductVersion>
        </PropertyGroup>
        <Message Importance="high" Text="Tagging MinVer as Assembly Version... $(MinVerMajor).$(MinVerMinor).$(MinVerPatch)$(MinVerPreReleaseTrimmed)"/>
    </Target>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(RECURSION_FLAG)' != '1'">
        <Message Importance="high" Text="Creating custom AppSettings Json Schema on SDK Build..."/>
        <Exec Command="dotnet restore ../SomeOtherProject/SomeOtherProject.csproj"/>
        <MSBuild Projects="../SomeOtherProject/SomeOtherProject.csproj" Targets="Build" Properties="RECURSION_FLAG=1"/>
        <MSBuild Projects="../SomeOtherProject/SomeOtherProject.csproj" Targets="Run" Properties="RECURSION_FLAG=1;RunArguments=../../appsettings.schema.json"/>
    </Target>
```

My docfx.json looks like this:
```
{
    "metadata": [
        {
            "src": [
                {
                    "files": [
                        "**/myproject.csproj",
                        "**/myproject.Example.csproj"
                    ],
                    "exclude": [
                        "**/bin/**",
                        "**/obj/**",
                        "**/docs/**"
                    ],
                    "src": "../source"
                }
            ],
            "namespaceLayout": "nested",
            "noRestore": true,
            "properties": {
                "TargetFramework": "net6.0"
            },
            "dest": "sdk",
            "disableGitFeatures": false,
            "disableDefaultFilter": false
        }
    ],
    "build": {
        "globalMetadata": {
            "_appTitle": "myproject",
            "_appName": "myproject Backend",
            "_appFooter": "© All rights reserved",
            "_appLogoPath": "images/myproject.png",
            "_appFaviconPath": "images/myproject.ico",
            "_enableSearch": true,
            "_enableNewTab": false,
            "_disableNavbar": false,
            "_disableBreadcrumb": false,
            "_disableToc": false,
            "_disableContribution": false,
            "_gitContribute": {
                "repo": "https://gitlab.myproject.com/myproject",
                "branch": "main"
            }
        },
        "template": [
            "default",
            "modern",
            "templates/singulinkfx",
            "templates/customization"
        ],
        "content": [
            {
                "files": [
                    "articles/**.md",
                    "articles/**/toc.yml",
                    "sdk/**.yml",
                    "sdk/index.md",
                    "toc.yml",
                    "*.md"
                ]
            }
        ],
        "overwrite": [
            {
                "files": [
                    "docs/overwrite/**.md",
                    "docs/overwrite/**.yml"
                ],
                "exclude": [
                    "**/bin/**",
                    "**/obj/**"
                ]
            }
        ],
        "resource": [
            {
                "files": [
                    "images/**"
                ]
            }
        ],
        "dest": "_site"
    }
}

```

Any help would be greatly appreciated, as I think this has been working in the past.

I also cannot find any special Info / Tips for this situation with "special build actions".
E.g. Are they even supported in docrfx or not?

I just havent updated docfx and MinVer for a while and cannot say with confidence what is the culprit.
I tried debugging and enabling "TRACE" Logging level without much success.

Thanks in advance!

**Comment by hexxone** [comment]
P.S.:
as a workaround for now, I added the condition   `Condition="'$(MinVerVersion)' != ''"`   to "VersionTarget", so that it only overrides the Package Version after MinVer actually filled these variables (has run).

Then in my CI pipeline: 
- build the project manually once 
- -> AssemblyInfo get filled correctly 
- -> build with docfx 
- -> AssemblyInfo does not get overwritten 
- -> Expected result

**Comment by filzrev** [comment]
It seems MSBuild  `MinVer` target is executed only when `DesignTimeBuild` property is not set `true`.
https://github.com/adamralph/minver/blob/main/MinVer/build/MinVer.targets#L20

docfx metadata` analyze projects with `DesignTimeBuild=true` settings.
So `MinVer` target is not executed.

```
  "metadata": [
    {
      "properties": {
        "DesignTimeBuild": "false"
      }
    }
  ],
```

> [!NOTE]
> It might cause unexpected side effects when disable DesignTimeBuild.

---

And `PostBuildEvent` is never called when using `docfx metadata` command.
Because `docfx metadata` command invoke `Compile` and `CoreCompile` targets only.

**Comment by hexxone** [comment]
Hi there @filzrev ,
thanks for taking the time to investigate this and even coming up with these solutions :)

It also took me a while to get around to test this but it seems like the things you suggested are working. 

I wasnt able to see any side effects with "DesignTimeBuild" set to false so far and the docs still gets properly generated as far as I can tell.

Also using the "AfterCompile" Target instead is working perfectly as a substitute.

Maybe it would be nice if we can also put these infos into the docfx nuget package usage documentation for others to find and safe some time ^^ 

But I think because its not too critical of a "bug", I can close this issue for now.
Maybe ill find the time to do a PR myself in the future, Cheers :)
