### ISSUE TITLE
[Bug] .NET API bug UWP No longer supported

### ISSUE THREAD

**Issue by dotMorten** [dotnet/docfx#9494]
**Describe the bug**
Since v2.60.0 we can no longer support UWP and other types of projects that requires the full MSBuild. It seems only .NET Core projects are now supported.

**To Reproduce**

1. Create a UWP Class Library with a class in it.
2. Run metadata command against project with v2.74.1. 
3. Note that no metadata is generated
4. Repeat with v2.59.4 and notice API metadata is generated

**Expected behavior**
Metadata gets generated.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.74.1
- .NET version: .NET Core / UWP

- `docfx.json` config

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [ "ClassLibrary7.csproj" ],
          "src": "E:/sources.tmp/ClassLibrary7/ClassLibrary7"
        }
      ],
      "dest": "api"
    },
  ],
}
```

- Errors and warnings

```
Using .NET Core SDK 8.0.100
Loading project E:/sources.tmp/ClassLibrary7/ClassLibrary7/ClassLibrary7.csproj
warning: [Failure] Msbuild failed when processing the file 'E:\sources.tmp\ClassLibrary7\ClassLibrary7\ClassLibrary7.csproj' with message: The imported project "C:\Program Files\dotnet\sdk\8.0.100\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\8.0.100\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets" is correct, and that the file exists on disk.  E:\sources.tmp\ClassLibrary7\ClassLibrary7\ClassLibrary7.csproj
Processing ClassLibrary7
Creating output...
warning: No .NET API detected for ClassLibrary7.


Build succeeded with warning.

    2 warning(s)
    0 error(s)
```

Output with v2.59.4:
```
[23-12-01 07:55:59.779]Info:[ExtractMetadata]Using msbuild C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin as inner compiler.
[23-12-01 07:56:01.440]Info:[ExtractMetadata]Loading projects...
[23-12-01 07:56:09.575]Info:[ExtractMetadata]Generating metadata for each project...
[23-12-01 07:56:11.158]Info:Completed in 11717.1026 milliseconds


Build succeeded.
        0 Warning(s)
        0 Error(s)
```

**Additional context**
Digging into the compilation, it is now using the `'$(MSBuildRuntimeType)'=='Core'` which is not supporting these target frameworks.

This is especially a problem when using MSBuildExtras to cross compile for multiple target frameworks, including UWP and Xamarin. MSBuildExtras will generate a build error for these target frameworks:
```
1>[23-12-01 08:02:39.647]Warning:[ExtractMetadata](E:/GitHub/dotMorten/NmeaParser4/src/NmeaParser/NmeaParser.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file \.nuget\packages\msbuild.sdk.extras\3.0.22\Build\Workarounds.targets: (27, 5): If you are building projects that require targets from full MSBuild or MSBuildFrameworkToolsPath, you need to use desktop msbuild ('msbuild.exe') instead of 'dotnet build' or 'dotnet msbuild'
```

**Comment by filzrev** [comment]
As described in linked-issue comment (`https://github.com/microsoft/MSBuildLocator/issues/152#issuecomment-1839391035`)
It' required to run MSBuild on separate process.

It might be resolved when next Roslyn version(`4.9.0`) released.
Because `MSBuildWorkspace` build behavior is changed to running `out-of-proc`.
`https://github.com/dotnet/roslyn/issues/61454#issuecomment-1813193707`

**Comment by filzrev** [comment]
I've tried to use  Roslyn `4.9.0-3.23612.11` (It requires .NET preview NuGet feed).
And It can be successfully running `dotnet metadata` command.

So this issue will be resolved when  Roslyn `v4.9.0` is officially released [Expected on `Feb '24`](https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#lifecycle).

**Comment by yufeih** [comment]
> I've tried to use Roslyn `4.9.0-3.23612.11` (It requires .NET preview NuGet feed). And It can be successfully running `dotnet metadata` command.
> 
> So this issue will be resolved when Roslyn `v4.9.0` is officially released [Expected on `Feb '24`](https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#lifecycle).

Nice finding! Out of proc execution solves a whole class of problems with msbuild.

**Comment by dotMorten** [comment]
@yufeih how was this addressed? With 2.76.0 I'm not able to build UWP projects and getting this warning right before all the errors:

> warning: [Failure] Msbuild failed when processing the file 'e:\GitHub\dotMorten\NmeaParser\src\NmeaParser\NmeaParser.csproj' with message: If you are building projects that require targets from full MSBuild or MSBuildFrameworkToolsPath, you need to use desktop msbuild ('msbuild.exe') instead of 'dotnet build' or 'dotnet msbuild'

**Comment by filzrev** [comment]
>  If you are building projects that require targets from full MSBuild or MSBuildFrameworkToolsPath, you need to use desktop msbuild ('msbuild.exe') instead of 'dotnet build' or 'dotnet msbuild'

Above message is raised by `MSBuildExtras` package.
It might be resolved by setting `_SdkIgnoreMSBuildCoreWarning` property to `true`.

**Comment by dotMorten** [comment]
@filzrev Thanks I tried that both in the project and in the metadata properties, but no luck. I'm getting the same error.

**Comment by filzrev** [comment]
On my environment.
Following warning message is displayed before  `CS0246` errors.

> warning: [Failure] Msbuild failed when processing the file 'C:\projects\Rx.NET\Source\src\System.Reactive\System.Reactive.csproj' with message: The specified language targets for uap10.0.18362 is missing. Ensure correct tooling is installed for 'uap'. Missing: 'C:\Program Files\dotnet\sdk\8.0.202\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets'

Above message path indicating `.NET SDK` version of MSBuild is selected from `$(MSBuildExtensionsPath)` .
It should use `Visual Studio` version of MSBuild host instead when generating UWP app metadata.

I've checked how Roslyn 4.9.2 or later execute analysis out-of-process. (https://github.com/dotnet/roslyn/pull/70469)
But can't find ways to change behaviors.

**Comment by filzrev** [comment]
> But can't find ways to change behaviors.

BuildHost process kind selection logics are hardcoded at https://github.com/dotnet/roslyn/blob/0d1f9fea04892d9e65e9a780bb773a4d5ed18f8e/src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs#L278-L336. 

So when using SDK style projects.
 .NET SDK version of MSBuild seems used always.

---
As a workaround.
 It can be resolved by manually importing `Microsoft.Windows.UI.Xaml.CSharp.targets` file when running `docfx metadata` command for UWP.

**Steps**
1. Add following lines at end of `NmeaParser.csproj`
```
  <Import Project="$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.CSharp.targets"
          Condition="'$(TargetFramework)' == 'uap10.0.18362' AND '$(DocfxBuild)' == 'true'" />
```

2. Edit docfx.config and change settings for UWP metadata generation.

```
"properties": {
        "TargetFrameworks": "uap10.0.18362",
        "DocfxBuild": "true", 
        "MSBuildExtensionsPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild"
      },
```
Note: MSBuild path is depends on VS edition and installed paths.

I don't have `Xamarin.Android`/`Xamarin.iOS` build environment.
It'll be resolved similar steps.

**Comment by dotMorten** [comment]
@filzrev Thanks for this, but unfortunately this isn't a good solution still because of the hardcoded paths to msbuild, and not everyone is using preview, or enterprise, or professional versions.
