### ISSUE TITLE
[Bug] PDF missing some svg images but present in html

### ISSUE THREAD

**Issue by david-d-le** [dotnet/docfx#9503]
**Describe the bug**
There are missing some svg images in generated pdf file. All svg images are showing fine in html files and served web page.
However this problem occurs only sometimes (I can't test if it is problem on my machine only or not). Sometimes all images are present and sometimes are some of them (in random order) missing.

**To Reproduce**
1. Download provided sample or Initialize new docfx folder
2. Create some pages containing images
3. run `docfx .\docfx.json --serve` or even `docfx`

**Expected behavior**
Get pdf with correctly generated svg images

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: 2.74.1

**Additional context**
[docfx_svg_missing_bug.zip](https://github.com/dotnet/docfx/files/13551292/docfx_svg_missing_bug.zip)

There is .zip containing sample project with random svg images.

**UPDATE**
When setting cmd.exe to one thread, it occurs less likely. I don't know if it is coincidence or it has something to do with threads/mutual exclusion??

**Comment by yufeih** [comment]
We currently print the PDF [immediately after script execution](https://github.com/dotnet/docfx/blob/main/src/Docfx.App/PdfBuilder.cs#L155), would need to replace it with a more reliable signal that detects renders completes.
