### ISSUE TITLE
Support submodules for "Improve this Doc"

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#951]
### Title
Use case is that I've a repository with the DocFx project which contains some submodules containing the actual documentation. The "Improve this Doc" link works fine for pages lying in the main repository, but is a wrong URL for pages being part of a submodules.

### Functional impact
"Improve this Doc" cannot be used together with submodules.

### Minimal repro steps
1. Create Repo A containing a DocFx project
2. Create Repo B containing some conceptual documents
3. Add Repo B as submodule to Repo A and integrate the conceptual documents from Repo B into the DocFx project

"Improve this Doc" link for the conceptual documents of Repo B are in the form: `https://github.com/someOrg/RepoA/blob/master/RepoB/index.md/#L1

### Expected result
DocFx should check if the document is part of a submodule and use the URL of the submodule in this case.

### Actual result
"Improve this Doc" links always to the repository and not the repository of the submodule

**Comment by vwxyzh** [comment]
#919

**Comment by pascalberger** [comment]
I tried again with a recent build containing #919 and behavior seems to be differnt, but still not working in my case.

Now instead of  `https://github.com/someOrg/RepoA/blob/master/RepoB/index.md/#L1` the links are in the form of `https://github.com/someOrg/RepoA/blob/master/index.md/#L1`. Expected would be `https://github.com/someOrg/RepoB/blob/master/index.md/#L1`.

**Comment by qinezh** [comment]
I have tried [docfx-seed](https://github.com/docascode/docfx-seed.git) with running `git init` and `git remote add origin xxx` in `articles` folder. The link of `Improve the Docs` is correct with DocFX built from dev branch. 

Could you provide the repo you have tested?

**Comment by pascalberger** [comment]
@qinezh Unfortunately its a private repository.

But I don't think your repro steps lead to the same situation as mine (new repo with remote vs. a  submodule).

**Comment by qinezh** [comment]
Hi @pascalberger , I just can't repro it with your steps. Could you provide with a simple public repo which could repro it? Thanks.

**Comment by pascalberger** [comment]
@qinezh Here's a repository to reproduce:

* Clone [this repository](https://github.com/pascalberger/docfx-sample/)
* Update submodules
* Run `docfx --serve`
* Go to `http://localhost:8080/Area1/docfx-sample-subrepo/docs/index.html`
* Click on `Improve this Doc`

It will link to  `https://github.com/pascalberger/docfx-sample/blob/master/docs/index.md/#L1` instead of `https://github.com/pascalberger/docfx-sample-subrepo/blob/master/docs/index.md/#L1`

**Comment by qinezh** [comment]
sorry, this commit would be included in 2.11 for reasons hard to explain...
