### ISSUE TITLE
[Feature Request] add responsive navigation

### ISSUE THREAD

**Issue by Arhell** [dotnet/docfx#9514]
**Is your feature request related to a problem? Please describe.**

![Screenshot_1](https://github.com/dotnet/docfx/assets/26163841/193ecc55-b69f-4747-9a2a-0b9865aca0fd)

![Screenshot_2](https://github.com/dotnet/docfx/assets/26163841/cff78268-8895-460a-8541-f7b3e9599904)
**Describe the solution you'd like**
Add the ability to change navbar-expand-md to navbar-expand-lg and other options in docfx.json.

**Additional context**
If the navigation menu is large there is no way to change this.

![Screenshot_3](https://github.com/dotnet/docfx/assets/26163841/8bb200d0-d209-4005-b818-5a16c23d5fcb)

**Comment by yufeih** [comment]
The search box takes too much width, we could default to `navbar-expand-lg` and collapse the search box into an icon as needed.

**Comment by Arhell** [comment]
> The search box takes too much width, we could default to `navbar-expand-lg` and collapse the search box into an icon as needed.

Did I understand correctly that I will need to take the layout and change it there?
Example https://github.com/dotnet/docfx/blob/main/templates/default/partials/navbar.tmpl.partial

I just suggest doing this in the 1st file as I wrote in the first post **docfx.json**
