### ISSUE TITLE
ApplyTemplateRendererError: Error applying template "toc.html" generated from "toc.yml"

### ISSUE THREAD

**Issue by bbsparkrock** [dotnet/docfx#9515]
**Describe the bug**
When I run docfx docfx.json --serve, I receive the following error:

Error applying template "toc.html" generated from "toc.yml". You have reached the maximum recursion limit of 256.

**To Reproduce**
1. Run docfx docfx.json --serve

**Expected behavior**
No error to appear and my site to be available via localhost.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.74.1

**Additional info:**
toc.yml example:
- name: sparkrock.com
  href: https://sparkrock.com/

I don't receive this error in version 2.73

**Comment by KolRah** [comment]
Hi same for me with non "modern" templaces
version 2.74.1 as well

xxx\api\toc.yml: error ApplyTemplateRendererError: Error applying template "toc.html" to view model "xxx\AppData\Local\Temp\2\docfx\viewmodel\api\toc.html.raw.json" generated from "api/toc.yml". You have reached the maximum recursion limit of 256.
            at object Render(BlockToken block, Context context)
            at void Write(StringRender renderer, SectionToken obj, Context context)
            at void Write(RendererBase<TContext> renderer, MustacheToken obj, TContext context)
            at void Write<T>(T obj, TContext context)
            at object Render(BlockToken block, Context context)
            at void Write(StringRender renderer, PartialToken obj, Context context)
            at void Write(RendererBase<TContext> renderer, MustacheToken obj, TContext context)
            at void Write<T>(T obj, TContext context)
            at object Render(BlockToken block, Context context)
            at void Write(StringRender renderer, InvertedSectionToken obj, Context context)

Thanks

**Comment by filzrev** [comment]
> if I use the default template it's fine
> if I use any of the external templates in templates/xxx directory I get this
> xxx\api\toc.yml: error ApplyTemplateRendererError: Error applying template "toc.html" to view model
> "xxx\AppData\Local\Temp\2\docfx\viewmodel\api\toc.html.raw.json" generated from "api/toc.yml". You have reached the maximum recursion limit of 256.

It might be related to https://github.com/dotnet/docfx/pull/9483 changes.

If **external docfx template** contains `toc.html.tmpl` file.
It need to rename to `toc.html.primary.tmpl`.

**Comment by KolRah** [comment]
Wow wonderful it works
Thanks for your kind help, I had not found the related change
Regards

**Comment by yufeih** [comment]
Thank you @filzrev !

**Comment by rst4** [comment]
Actually I experience the same error. However, my custom template contains only `toc.html.primary.tmpl` and this produces the same error:

```
/Users/alexry/***/user-manual-v3/tutorials/toc.yml: error ApplyTemplateRendererError: Error applying template "toc.html.primary" to view model "/Users/alexry/***/user-manual-v3/_docfx_debug/viewmodel/tutorials/toc.html.raw.json" generated from "tutorials/toc.yml". You have reached the maximum recursion limit of 256.
```

docfx version is 2.73.0.

If I rename the file to `toc.html.tmpl` the build works but docfx seemingly doesn't include this template at all.  Can you please advise?

Thank you.
