### ISSUE TITLE
[Bug] DocFX recursively builds into a new destination folder inside the existing destination folder

### ISSUE THREAD

**Issue by jakraft** [dotnet/docfx#9525]
**Describe the bug**
Your docfx.json file lets you specify a directory where you want your build output to go. For example:

```json
{
  "build": {
    "content": [
      {
        "files": [ "**/*.yml", "**/*.md" ]
      }
    ],
    "resource": [
      {
        "files": [ "**/*.png" ]
      }
    ],
    "dest": "_site",
    "globalMetadata": {
      "_appTitle": "My App",
      "_enableSearch": "true",
      "_enableNewTab": "true"
    },
    "fileMetadataFiles": [],
    "template": [
      "default",
      "modern"
    ],
    "postProcessors": [],
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}
```

Every time a build is executed using the following command:

```
docfx docfx.json --serve --port 8080
```

Rather than overwriting the existing data in "_site", it creates a new "_site" folder _inside_ of that original build directory. A consequence, the total number of files in the build output increases _linearly_ with each build. This also substantially slows down build times when repeated executed without first deleting the eixsting _site folder.

![image](https://github.com/dotnet/docfx/assets/52800741/8d77678c-a144-40a2-9975-71944a1812d7)

 
**To Reproduce**
1. Create a basic docfx site using the sample docfx.json above
2. Run `docfx docfx.json --serve --port 8080` several times
3. Drill down into your "_site" folder and you should see several nested "_site" folders, each with the exact same content.

**Expected behavior**
The existing output directory should be overwritten with each execution.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: [e.g. 2.74.1]

**Additional context**

**Comment by filzrev** [comment]
It seems `_site/**/*.png` resource files are recursively included as `docfx build` input.

It can be resolved by adding `exclude` section to `docfx.json`.
https://github.com/dotnet/docfx/blob/main/docs/docfx.json#L17-L29

**Comment by jakraft** [comment]
@filzrev oh my gosh it feels so obvious now that you point it out, but I would have never guessed! I had assumed the destination folder was implicitly ignored by docfx during build. Excluding the _site folder as you suggested completely solves the problem!

For posterity, here's what my final docfx.json looks like. It's probably not necessary to add the exclusion to the content, but just added it for completeness.

```json
{
  "build": {
    "content": [
      {
        "files": [ "**/*.yml", "**/*.md", "**/*.ipynb" ],
        "exclude": [ "_site/**/*.*" ]
      }
    ],
    "resource": [
      {
        "files": [ "**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.svg", "**/*.pdf", "**/*.pptx", "**/*.json" ],
        "exclude": [ "_site/**/*.*" ]
      }
    ],
    "dest": "_site",
    "globalMetadata": {
      "_appTitle": "My App",
      "_enableSearch": "true",
      "_enableNewTab": "true"
    },
    "fileMetadataFiles": [],
    "template": [
      "default",
      "modern"
    ],
    "postProcessors": [],
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}
```
