### ISSUE TITLE
Need to upgrade bootstrap version

### ISSUE THREAD

**Issue by JayaprakashJPK** [dotnet/docfx#9534]
I am using below commands to build the docfx documentation site,

choco install docfx -y
docfx metadata
docfx build

while using this 2.59.4 version has been installed but while using this Bootstrap 3.*  version only presents due to security vulnurabilty in this version need to update latest bootstrap version and old dependent libraries also

**Comment by yufeih** [comment]
This is addressed in the latest version with the [modern template](https://dotnet.github.io/docfx/docs/template.html?tabs=modern). Please note newer versions are released through .NET tools using `dotnet tool update -g docfx` over `choco`.

**Comment by MurugananthamAlwar** [comment]
Hi @yufeih ,

I have checked with the modern template as mentioned in the document and also updated the docfx latest version using the following command: **dotnet tool update -g docfx** to the latest **2.74.1** version. Still, the boostrap version 3.4.1 is used. Need to use the latest Bootstrap version.
