### ISSUE TITLE
[Feature Request] Add MSBuild option to hide templates from VS project tree

### ISSUE THREAD

**Issue by jwfx** [dotnet/docfx#9549]
**Is your feature request related to a problem? Please describe.**

When consuming the docfx.app NuGet package, a templates folder is added to the VS project tree.

![image](https://github.com/dotnet/docfx/assets/39484381/414696e8-c628-45fb-b403-ee48bd38e0ed)

This is mainly because the corresponding issue https://github.com/NuGet/Home/issues/4856 has not been solved for multiple years.

**Describe the solution you'd like**
The linked issue proposes a [workaround](https://github.com/NuGet/Home/issues/4856#issuecomment-1363934310).

I have modified this workaround and prepared a [possible solution](https://github.com/jwfx/docfx/commit/4450ecd54db3ce70f68b78fd097964c791f87a71), that allows users to opt for hiding the folder by simple specifying `<DocfxExcludeTemplates>true</DocfxExcludeTemplates>` in their project.

Please let me know if I should turn this into a pull request.

**Describe alternatives you've considered**
The only other option I see is to apply the workaround manually to every project that is consuming docfx.app, but I believe this really  should be solved on package level for everyone, until the underlying issue is fixed.

**Comment by filzrev** [comment]
I'm also facing the same issue (it's annoying that `templates` files hits when solution-scoped search).
And same workaround by placing `Directory.Build.targets` file to solution root folder. 

```
<Project>
  <ItemGroup>
    <Content Update="@(Content)">
      <Visible Condition="'%(NuGetPackageId)' == 'Docfx.App' AND '%(NuGetItemType)' == 'Content'">false</Visible>
    </Content>
  </ItemGroup>
</Project>
```

> [!NOTE]
> *Directory.Build.props* file can't be used here. (Because `props` file is applied before importing Nuget files)

**Comment by yufeih** [comment]
@jwfx The proposed workaround looks great! Would you like to convert it into a pull request? The only change I would make is to remove the `DocfxExcludeTemplates` switch, assuming most people don't want `templates` to appear in their solution.

**Comment by jwfx** [comment]
@yufeih 
Thanks for the feedback. Pull request as above. Not sure I chose the right changelog category, so feel free to edit the title to your liking.
