### ISSUE TITLE
Add partials for DFM enhancements

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#958]
It seems like the enhancements which DFM provides [are hard coded](https://github.com/dotnet/docfx/blob/c13c1fd5192a3b9b01fa15ccf3d52a9f380e9669/src/Microsoft.DocAsCode.Dfm/DfmRenderer.cs#L79). It would be nice if instead they are rendered using a partial which can be overwritten in a theme.

**Comment by vwxyzh** [comment]
@pascalberger I add an interface [IDfmCustomizedRendererPartProvider](https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Dfm/IDfmCustomizedRendererPartProvider.cs) in 2.17. You can customize renderer by plug-in, the document is still writing.
