### ISSUE TITLE
[Feature Request] Include API summary in <meta description> tag

### ISSUE THREAD

**Issue by Thraka** [dotnet/docfx#9584]
I'm unsure what to do to get this working. I noticed this a while back but now I went to go fix it and I'm unsure what to do. I'm using docfx `2.74.1+80bc27e44183b48c74d24728655fa0729ae95689` and the default template.

I'm able to get this fixed for conceptual by modifying the `partials\head.tmpl.partial` file and changing the line for description to use `description` instead of `_description` I have no idea why there's an underscore there??

```diff
-{{#_description}}<meta name="description" content="{{_description}}">{{/_description}}
+{{#description}}<meta name="description" content="{{description}}">{{/description}}
```

I'm unsure how to get a summary of an API put into a description though, and also sanitize it of any HTML (links or other) in the summary.

**Comment by Thraka** [comment]
@yufeih I'm not seeing how your PR fixed the problem? In your PR the generated content doesn't have a description for the API. In my post above where I said:

> I'm able to get this fixed for conceptual by modifying the `partials\head.tmpl.partial` file and changing the line for description to use `description` instead of `_description` I have no idea why there's an underscore there??

I said I fixed this for **conceptual** but API is still broken.

**Comment by yufeih** [comment]
The API page does not currently populate `summary` as description. Turn this into a feature request.

**Comment by Thraka** [comment]
For SEO I need something otherwise the pages don't get indexed.
