### ISSUE TITLE
Need to upgrade bootstrap version to latest in DocFX

### ISSUE THREAD

**Issue by Murugaa19** [dotnet/docfx#9589]
I have checked with the modern template as mentioned in the document and also updated the DocFx latest version using the following command: **dotnet tool update -g docfx** to the latest **2.74.1** version. Still, the boostrap version **3.4.1** is used. We need to use the latest Bootstrap version.

**Comment by filzrev** [comment]
What would be the result of executing the following command?

> docfx --version
> where docfx    `(Note: For Windows environment. For other OS use `which` command instead)`

It's expected to be following result.
> 2.74.1+80bc27e44183b48c74d24728655fa0729ae95689
> C:\Users\{UserName}\.dotnet\tools\docfx.exe

If it's not indicating `2.74.1`.
Installed .NET global tool is not used.
It needs to modify `%PATH%` settings.

**Comment by MurugananthamAlwar** [comment]
Hi, @filzrev 

Yes worked now, but in latest HTML file, **In this Article** in the left side and **Search Filter** in the rightside is missing, how to enable this?

**Comment by Murugaa19** [comment]
Hi @filzrev,

Yes, it works now, but in the latest HTML file, **In this Article** on the left side and **Search Filter** on the right side are missing. How do I enable these?
