### ISSUE TITLE
[Feature Request] Publish from Azure DevOps

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/docfx#9594]
**Is your feature request related to a problem? Please describe.**
The docfx website https://dotnet.github.io/docfx/ has instructions for GitHub to deploy to GitHub Pages but we use Azure DevOps.

**Describe the solution you'd like**
Instructions for how to setup docfx with Azure Devops.

**Comment by vanillajonathan** [comment]
It would be good if instructions were available on https://dotnet.github.io/docfx/ as there are instructions for GitHub.

**Comment by JM2K69** [comment]
Ok I will try

**Comment by kale-swapnil** [comment]
Create a pull request for the request here #10213
