### ISSUE TITLE
[Feature Request] Publish docfx `prerelease` version NuGet packages

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#9609]
**Is your feature request related to a problem? Please describe.**
Currently it's requires `source build` to test latest docfx features that is not published to NuGet.

If `Nightly CI build` package is available.
It can test latest features with CI.
And it can reduce regression risks for users who use non-prerelease version. 

**Describe the solution you'd like**
Publish pre-release version NuGet package.
That supports following target frameworks. (To reduce package size)
- Latest `LTS` version (`.NET 8`)
- Latest `Preview` version (.NET 9 Preview) 

It's published by GitHub Actions (Daily CI build or published manually with `workflow_dispatch`). 
And older prerelease versions should be cleanup automatically by [delete-package-versions action](https://github.com/actions/delete-package-versions)

**Comment by yufeih** [comment]
Unfortunately GH packages in the dotnet org is private only.

**Comment by filzrev** [comment]
> Unfortunately GH packages in the dotnet org is private only.

Thank you for your confirmation.
It seems some packages are publicly published to [dotnet organization's GitHub packages](https://github.com/orgs/dotnet/packages).
Though currently settings are changed to `private only`?.

If there is no alternative way to publish preview NuGet feed. (e.g. MyGet or `docascode` organization GH packages feed)
It need to manually install preview version of docfx from `.nupkg`.

---

.NET 9 Preview 1 is being released today.
So, I am considering the following changes are needed to support .NET9,
What do you think?

1. Create `separate CI workflow` that targeting .NET9 and .NET8 (LTS) versions
2. Publish `docfx.nupkg` as GitHub Action's artifacts.

Who want to use `preview version of docfx` needs following steps.
1. Download `nupkg` from GitHub Action's artifact page.
2. Install docfx with `dotnet tool install docfx -g --add-source <path to nupkg>`

**Comment by ChrisSfanos** [comment]
Hmm - not sure, but will check offline with some folks and reply back here - thanks

**Comment by ChrisSfanos** [comment]
Adding @terrajobst 

From Immo:
My understanding is that packages inherit the visibility from the publishing repo. If the repo that pushed the packages is public, then the packages should be public.

How are the packages published?

**Comment by filzrev** [comment]
Thanks for publishing pre-release packages to GitHub Packages.
I'll try to test latest version of nightly build when packages are published.

---

It seems GitHub packages requires `Personal access tokens`  even if it is published as public package.
And currently it can't download nupkg from GitHub UI. (https://github.com/orgs/community/discussions/69687)

So it need to use `NuGet.config` file to install nightly version of package.

## Steps to use nightly version of docfx as .NET local tools.

**1. Create GitHub `Personal access tokens (classic)`(PAT) with following permissions**
- read:packages

**2. Create `NuGet.config` file at working directory.**

Note: It need to replace `%USER_NAME%` value to actual GitHub user name. 
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="github" value="https://nuget.pkg.github.com/dotnet/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <github>
      <add key="Username" value="%USERNAME%" />
      <add key="ClearTextPassword" value="%GITHUB_TOKEN%" />
    </github>
  </packageSourceCredentials>
</configuration>
```

**3. Set PAT to `GITHUB_TOKEN` environment variable**

**4. Install docfx as .NET local tools**

> dotnet tool install docfx --prerelease --create-manifest-if-needed

**Comment by filzrev** [comment]
It seems nightly-packages are shown on right nav area in docfx repository.
![image](https://github.com/dotnet/docfx/assets/103790468/1e0b9b94-babf-4069-8f54-4a4bfa57f260)

This is confusing with nuget published packages.
So it might be better to hide these settings from the navigation pane.
(Settings can be changed using the `Gear' icon in the top right navigation area)

**Comment by martincostello** [comment]
I would agree that the use of GitHub Packages for the pre-release packages here isn't a good user experience - the need to mess about with credentials to get the packages to restore isn't practically workable across the many repositories I'm testing prereleases within a GitHub Enterprise Server instance.

I would suggest publishing them to another platform such as feedz.io that does support true anonymous access (I use package source mappings so I need to declare another feed anyway, regardless of credentials) or just publishing the pre-release versions directly to NuGet.org.

I'll stick with `DOTNET_ROLL_FORWARD: LatestMajor` and `DOTNET_ROLL_FORWARD_TO_PRERELEASE`, though the new `--allow-roll-forward` flag for `dotnet tool restore` might help.
