### ISSUE TITLE
[Bug] Class summary appears under every documented class property 

### ISSUE THREAD

**Issue by markwaterman** [dotnet/docfx#9628]
**Describe the bug**
A class's summary appears under every one of its properties. This issue started to occur in docfx version 2.75.1.

**To Reproduce**

1. Define a class with at least one property.  For example:

```csharp
/// <summary>
/// Class representing a dog.
/// </summary>
public class Dog
{
    /// <summary>
    /// Name of the dog.
    /// </summary>
    public string Name { get; }

    /// <summary>
    /// Age of the dog.
    /// </summary>
    public int Age { get; }

    /// <summary>
    /// Constructor.
    /// </summary>
    /// <param name="name">Name of the dog.</param>
    /// <param name="age">Age of the dog.</param>
    public Dog(string name, int age)
    {
        Name = name;
        Age = age;
    }
}
```
2. Create a docfx project that documents this API. When viewing the build in a browser, the class summary appears under every property's return type:

<img width="783" alt="docfx_prop_repro" src="https://github.com/dotnet/docfx/assets/14813142/844a7950-a69e-4165-9571-e5b8a14ac278">

1. Clone https://github.com/markwaterman/DocfxPropertyRepro
2. In DocfxPropertyRepro\docfx_proj, run `docfx --serve --port=8081`
3. In your web browser, visit http://localhost:8081/api/DocfxPropertyRepro.Dog.html#properties

**Expected behavior**
A class's summary should only appear at the top of the page.

**Context (please complete the following information):**
- OS: Windows 11
- Docfx version: 2.75.1

**Comment by tony-dwire-paradigm** [comment]
Also happens for me on linux, same version of docfx.

**Comment by mikernet** [comment]
It also puts the class summary into generic parameters on the class.

**Comment by mikernet** [comment]
![image](https://github.com/dotnet/docfx/assets/1700111/d9da10e0-ef95-485e-b6c3-fab41d3cf7ad)
