### ISSUE TITLE
[Bug] 4 unit tests failing on freshly forked repo

### ISSUE THREAD

**Issue by dougclutter** [dotnet/docfx#9656]
**Describe the bug**
4 unit tests are failing.

**To Reproduce**
1. Pull the current main branch of the repo
2. Run all unit tests in Visual Studio 2022 v17.8.5

**Expected behavior**
All unit tests should pass.

**Context (please complete the following information):**
- OS: Windows 11
- Docfx version: Current version of main branch - Commit ID aff89bf780d1e917267133cb9c67a9a3dd2f7908

I was working on https://github.com/dotnet/docfx/issues/2742 but I'd like all unit tests to work so I do no harm. :)

**Additional context**
Here's a screenshot of the errors.  4 unit tests are failing.  12 showing because they fail for net6, 7, and 8:
![image](https://github.com/dotnet/docfx/assets/12717532/c7a3513b-7540-44e8-bb49-52a9de4921fe)

**Comment by yufeih** [comment]
Hi @dougclutter - Do you run `npm run build` in the `templates` directory?

**Comment by dougclutter** [comment]
Hi @yufeih - As suggested, I ran `npm install` then `npm run build` in the `templates` directory and it resolved the build errors.  
Thanks for your help!
