### ISSUE TITLE
[Bug] Field and property 'Value' entries duplicate class summary when not provided

### ISSUE THREAD

**Issue by Chippit** [dotnet/docfx#9669]
**Describe the bug**
When the xmldoc for a field or property lacks a `<value>` tag, the generated documentation instead duplicates the class documentation (but without links or formatting)

**To Reproduce**
1. Build a library with a public property lacking a `<value>` tag.
2. Execute docfx against its generated dll/xml files using the modern template.

**Expected behavior**
The Field/Property Value is blank or omitted.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: [e.g. 2.75.1]
- Modern template

**Additional context**
The expected behaviour was what happened in past versions of docfx (at least in 2.59.4) using the default template. An excerpt of a type that demonstrates this behaviour is below:
```csharp
	/// <summary>
	/// Log wrapper to orchestrate delivery of log messages to registered instances of <see cref="ILogWriter"/>.
	/// All logging messages are conditional on <c>ENABLE_LOGGING</c>, so no logging will occur without that symbol defined
	/// in the calling assembly.
	/// </summary>
	public static class Log
	{
		/// <summary>
		/// The define used to enable the logging methods in this class.
		/// </summary>
		/// <remarks>This constant can be used as parameter in the <see cref="ConditionalAttribute"/>
		/// to include/exclude methods used for Logging that also use the methods of this class. 
		/// </remarks>
		public const string EnableLoggingDefine = "ENABLE_LOGGING";

		/* ... */
	}
```

Before:
![FieldsBefore](https://github.com/dotnet/docfx/assets/870779/6993f729-74dc-460e-bcfe-91a9aeaceb72)

In 2.75.1 with modern:
![FieldsAfter](https://github.com/dotnet/docfx/assets/870779/ed364387-4ac2-43df-831e-21a2d618fd30)

**Comment by yufeih** [comment]
Closing as fixed.
