### ISSUE TITLE
Add prefix to breadcrumb

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#968]
Do you have any example somewhere how the breadcrumb can be prefixed.

I'm looking for something like you have done on docs.microsoft.com (eg. https://docs.microsoft.com/de-de/aspnet/core/getting-started where the breacrumb is `Docs / ASP​.NET / ASP​.NET Core`, where the first part links to the landing page outside of the DocFx generated page)). 

Or providing full source for docs.microsoft.com, would also help :) I saw that you have additional metadata in the project,, but unfortunately the template is not available.

**Comment by superyyrrzz** [comment]
The prefix is load from another separate TOC: https://docs.microsoft.com/zh-cn/aspnet/breadcrumb/toc.json For now, themes for docs.microsoft.com isn't open source, so you need to customize the default template to achieve this.
