### ISSUE TITLE
[Bug] Assigned enum values not included in model

### ISSUE THREAD

**Issue by jo3w4rd** [dotnet/docfx#9686]
The ManagedReference model includes a value for each member of an enum in the syntax field if (and only if) you do not explicitly assign a value to the enum members. If you explicitly assign a value, only the name is included, not the assigned value. 

Although not shown in the default templates, it was previously possible to show the assigned values by customizing the template and adding a ManagedModel extension. It was also possible to sort the table of enum members by the assigned value. See https://github.com/dotnet/docfx/issues/2285#

For some Enums, the assigned value is important information and should be included in the docs. Currently, the only way to do this is to duplicate the information in the summary field where it can easily (and inevitably) get out of sync with the code.

**To Reproduce**
Observe the ManagedReference model for enums with and without explicit values assigned to their members.

**Expected behavior**
The enum value should always be included in the model (in some form) where it can be accessed for inclusion on the documentation page. Even better if this was included by default (or selectively through some configuration mechanism).

Generated with DocFX 2.58.9 and includes the value in the syntax field: https://docs.unity3d.com/Packages/com.unity.package-manager-doctools@2.1/api/Examples.EnumWithValue.html

**Context (please complete the following information):**
- OS: MacOS
- Docfx version: 2.70.0

**Additional context**
Its also odd that a value is shown in the syntax field when you do not assign one and not shown if you do assign one. For this reason, I think the issue is a bug and not a feature request.

**Comment by filzrev** [comment]
Is is able to show minimum reproducible sample code?

I'm tested on following environment. (with GitHub Action)
- OS: macOS
- docfx: `2.70.0`
- templtates: default

But it seems works as expected, as follows.
- Enum values are included in the model's `item.syntax.content[0].value` filed.   
   Whether the enum value is explicitly assigned or not.
- It can display enum value. by customized template.

Custom template files: https://github.com/filzrev/docfx.issue9686/tree/main/docs/templates/custom
Customized Enum API page: https://filzrev.github.io/docfx.issue9686/api/SampleLib.SampleEnum2.html

**Comment by jo3w4rd** [comment]
Here's the JavaScript that deals with the model and the Enum declarations
[JSCodeAndEnum.zip](https://github.com/dotnet/docfx/files/14211930/JSCodeAndEnum.zip)

After noticing this was no longer working, I printed the Model object for the Enum (using JSON.stringify()). 

For the enums with no assigned value, the content in the model looks like:
```
                    "syntax": {
                        "content": [
                            {
                                "lang": "csharp",
                                "value": "Few = 3"
                            },
...
```
But for those with a value assigned, the content is missing the assigned value:
```
                    "syntax": {
                        "content": [
                            {
                                "lang": "csharp",
                                "value": "First"
                            },
```

**Comment by filzrev** [comment]
I've updated the content based on the provided zip content.
But I still can't reproduce the problems.

- Changed contents: https://github.com/filzrev/docfx.issue9686/commit/91a56ff4c76a5864367f8c5d76a245619cdec8e0
- Result Page: https://filzrev.github.io/docfx.issue9686/api/Examples.EnumWithValue.html

> But for those with a value assigned, the content is missing the assigned value:

I've confirmed API metadata yml files that generated by docfx `2.70.0`.
It appears that `item.syntax.content[0].value` is set as expected.

Is it able to check docfx version with `docfx --version` command.
In my environment, the following result is displayed

>2.70.0+78b4679954c0d9c73488fb118d3e07abba3717da

**Comment by filzrev** [comment]
Thanks for your response.

I've tried adjusting your environment. But I still can't reproduce the problem.

- Changes: https://github.com/filzrev/docfx.issue9686/commit/16da61781b2df7c740f2663eda4eaf6d9991ff25
- Result Page: https://filzrev.github.io/docfx.issue9686/api/Examples.EnumWithValue.html


**Output of `dotnet --info` command on GitHub Action environment**

```
.NET SDK:
 Version:   7.0.402
 Commit:    7[9](https://github.com/filzrev/docfx.issue9686/actions/runs/7836324932/job/21383704362#step:5:10)1db8e2d8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.7
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /Users/runner/.dotnet/sdk/7.0.402/

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  6.0.418 [/Users/runner/.dotnet/sdk]
  7.0.[10](https://github.com/filzrev/docfx.issue9686/actions/runs/7836324932/job/21383704362#step:5:11)2 [/Users/runner/.dotnet/sdk]
  7.0.202 [/Users/runner/.dotnet/sdk]
  7.0.306 [/Users/runner/.dotnet/sdk]
  7.0.402 [/Users/runner/.dotnet/sdk]
  7.0.405 [/Users/runner/.dotnet/sdk]
  8.0.101 [/Users/runner/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.[12](https://github.com/filzrev/docfx.issue9686/actions/runs/7836324932/job/21383704362#step:5:13) [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.[15](https://github.com/filzrev/docfx.issue9686/actions/runs/7836324932/job/21383704362#step:5:16) [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.[26](https://github.com/filzrev/docfx.issue9686/actions/runs/7836324932/job/21383704362#step:5:27) [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/Users/runner/.dotnet]

global.json file:
  /Users/runner/work/docfx.issue9686/docfx.issue9686/global.json
```

The main environment difference is whether it's running on an x64-based CPU or an arm-based CPU.
(Because  arm-based macOS GitHub Action Runner is not publicly available yet)

It might help. If anyone who can reproduce this issue with following steps.

1. Clone `https://github.com/filzrev/docfx.issue9686` content
2. Modify `global.json` settings to use already installed .NET 7 SDK version.
3. Run `docfx metadata` command at `docs` folder
4. Run `docfx build --serve` command
5. Check `http://localhost:8080/api/Examples.EnumWithValue.html` output.   
    And `enum value` is outputted as expected

**Comment by jo3w4rd** [comment]
Those steps work for me as well. It doesn't seem like this is a DocFX bug after all, but I'm a bit stumped because the ManagedReference.extension.js is the only place we touch the model.

I also just tried generating the docs for our project on Windows and it seems that the enum values show up in that case, too. This uses the same DocFX config and templates, the same version of DocFX (but dotnet 7.0.2 instead of 7.0.4).

**Comment by jo3w4rd** [comment]
Another difference is that in the scenario that doesn't work, we don't run the metadata and build commands separately. We run `docfx config.json`.

**Comment by filzrev** [comment]
Is it able to upload `api/Examples.**.yml` files that are generated by `docfx metadata` command for data comparison?

---
Enum value's text (`item.syntax.content[0].value`) seems to be generated by using [SymbolDisplay.ToDisplayParts(symbol, format)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.visualbasic.symboldisplay.todisplayparts?view=roslyn-dotnet-4.7.0) Roslyn API.

If available. Try to generate metadata with latest docfx version.
(Because Roslyn compiler version updated from 4.6.0 to 4.8.0)

**Comment by jo3w4rd** [comment]
With the latest DocFX (2.75.2+fe673ecea2ac444a4fd480e6cfcf605c78614385), one of the Enum definitions now works, but one still does not contain the assigned values. (The 3rd case with implicit values, still shows them as before.)
[EnumMetadataYaml.zip](https://github.com/dotnet/docfx/files/14215864/EnumMetadataYaml.zip)

Our project currently has several errors related to the way we create a dummy project file -- it is a Unity project, not a .NET project. While we've used DocFX this way for years now, the latest update hasn't gone so well. Given that this problem doesn't happen on Windows and doesn't happen on Mac for a "proper" .NET project, I'm not sure its worth investigating further at this point.

Thanks for your help!
