### ISSUE TITLE
[Documentation Request] codeSourceBasePath is not documented

### ISSUE THREAD

**Issue by alanSherba** [dotnet/docfx#9687]
defining `codeSourceBasePath` in docfx.json metadata allows you to define the base path for `<code source="">` comments. 

But it is not documented here: https://dotnet.github.io/docfx/reference/docfx-json-reference.html

**Comment by alanSherba** [comment]
Relevant issue where it helped me fix a bug: https://github.com/dotnet/docfx/issues/9685

**Comment by filzrev** [comment]
This PR can be closed.
Because missing documentation for `codeSourceBasePath` is added by #9813
