### ISSUE TITLE
[Bug] `<` in header not escaped when outputFormat: "markdown"

### ISSUE THREAD

**Issue by bohyunjung** [dotnet/docfx#9719]
**Describe the bug**

A rendered markdown file includes unescaped `<`.
And my markdown parser (docusaurus) fails to parse the file.

Here's a header line that includes unescaped `<`.

```
# <a id="Newtonsoft_Json_Generated_CustomBinding0_4"></a> Delegate CustomBinding0<TSelf, T0, T1, T2\>
```

**To Reproduce**

Run docfx with `metadata.outputFormat: "markdown"` option.

<details>
<summary>Whole docfx.json</summary>

```json
{
  "metadata": [
    {
      "src": [
        {
          "src": "..",
          "files": [
            "**/*.cs"
          ]
        }
      ],
      "dest": "api",
      "globalNamespaceId": "Global",
      "allowCompilationErrors": true,
      "namespaceLayout": "nested",
      "outputFormat": "markdown"
    }
  ]
}

```

</details>

**Expected behavior**

Since `>` is escaped as follows, the escape of `<` is also expected.

`CustomBinding0<TSelf, T0, T1, T2\>`

**Context (please complete the following information):**
- OS: macOS 14.2.1(23C71)
- Docfx version: 2.75.3+a5c719410037cc288c7adff010b1abf3c0f2e581
- Dotnet version: 7.0.403

**Additional context**

I'm working on a Unity package project, and I referenced the docfx settings of https://github.com/CaseyHofland/docfx-unitypackage.

**Comment by bohyunjung** [comment]
It seems like `<` is not included in `EscapeChars`. Is it intended?

https://github.com/dotnet/docfx/blob/7d511fb032de82d0105f08e1f649b2b066697397/src/Docfx.Build/ApiPage/ApiPageMarkdownTemplate.cs#L101

**Comment by yufeih** [comment]
`<` shows up correctly in your example using vscode markdown preview and it should comply with markdown standard. What markdown engine did you see problems rendering the content?

<img width="1196" alt="Screenshot 2024-02-22 at 8 45 01 PM" src="https://github.com/dotnet/docfx/assets/511355/d17a0f6d-e40b-4b5d-b6db-4bc9596d99f1">

For context, escaping one angle bracket should prevent it from becoming an HTML tag, and `>` is used for [blockquote syntax](https://commonmark.org/help/tutorial/05-blockquotes.html) hence it is escape.

**Comment by bohyunjung** [comment]
My bad. I was using the `mdx` parser in my [docusaurus config](https://docusaurus.io/docs/api/docusaurus-config#format). After setting it to `md`, it parses the docfx-generated markdown file without error.

Thank you.
