### ISSUE TITLE
`Contributor License Agreement` is not required

### ISSUE THREAD

**Issue by just-ero** [dotnet/docfx#9729]
## Description

As per [CONTRIBUTING.md](https://github.com/dotnet/docfx/blob/main/CONTRIBUTING.md#contributing-code), a signature of the .NET Contributor License Agreement is required to submit a pull request. This is not enforced.

**Comment by yufeih** [comment]
You must have already signed the CLA somewhere else, the CLA task in #9728 is green:

<img width="829" alt="Screenshot 2024-02-24 at 10 54 56 AM" src="https://github.com/dotnet/docfx/assets/511355/f112a8cb-a7b9-45ff-9dcd-97c7cf8f85b1">
