### ISSUE TITLE
Print background when creating PDF

### ISSUE THREAD

**Issue by EMaderbacher** [dotnet/docfx#9740]
Is it possible, that the PDF creating is made with option PrintBackground enabled?
This would result for example in more beautiful Alerts in created PDF file:
```markdown
> [!NOTE]
> Information the user should notice even if skimming
```
Source: https://github.com/dotnet/docfx/blob/a58fec70cdaa98d6348d1cb3e0185f19a5ca6c48/src/Docfx.App/PdfBuilder.cs#L167C17-L167C18
Suggested change:
```cs
return await page.PdfAsync( new PagePdfOptions()
{
	PrintBackground = true
});
```

**Comment by yufeih** [comment]
Same as #9730 - @EMaderbacher, @cjlotz would you like to send a pull request? We could expose a `pdfPrintBackground` option [here](https://github.com/dotnet/docfx/blob/main/src/Docfx.App/PdfBuilder.cs#L33C11-L33C18) and pass it to `PdfAsync` method.
