### ISSUE TITLE
[Feature Request] Turn off warning about project reference

### ISSUE THREAD

**Issue by xuejiaW** [dotnet/docfx#9804]
I am using docfx 2.75.3 for Unity project, and i want to generate api docs for specific csproj, the target csproj references many other csproj, like Unity packages csproj.

The metadata i used in docfx.json is like:
```json
    "metadata": [
        {
            "src": [
                {
                    "src": "../../TestProjects/Spatial Management/",
                    "files": [
                        "YVR.SpatialManagement.Runtime.csproj"
                    ]
                }
            ],
            "dest": "Apis",
            "properties": {
                "DefineConstants": "UNITY_EDITOR"
            },
            "filter": "../../DocFx/filterConfig.yml"
        }
    ]
```

and while building docs, i get the warning like:
```text
warning: [Warning] Found project reference without a matching metadata reference: D:\SDK_SpatialManagement\TestProjects\Spatial Management\Unity.ResourceManager.csproj
warning: [Warning] Found project reference without a matching metadata reference: D:\SDK_SpatialManagement\TestProjects\Spatial Management\Unity.Addressables.csproj
warning: [Warning] Found project reference without a matching metadata reference: D:\SDK_SpatialManagement\TestProjects\Spatial Management\YVR.Utilities.Runtime.csproj
warning: [Warning] Found project reference without a matching metadata reference: D:\SDK_SpatialManagement\TestProjects\Spatial Management\YVR.HybridSpatial.Runtime.csproj
warning: [Warning] Found project reference without a matching metadata reference: D:\SDK_SpatialManagement\TestProjects\Spatial Management\UnityEngine.SpatialTracking.csproj
warning: [Warning] Found project reference without a matching metadata reference: D:\SDK_SpatialManagement\TestProjects\Spatial Management\UnityEngine.XR.LegacyInputHelpers.csproj
warning: [Warning] Found project reference without a matching metadata reference: D:\SDK_SpatialManagement\TestProjects\Spatial Management\Unity.InputSystem.csproj
``` 

I have tried to add these csproj to the "exclude" field which like:
```json
                "exclude": [
                    "**/Unity.*.csproj",
                    "**/UnityEngine.*.csproj",
```

but no luck. Is there any way to eliminate the warning?

**Comment by filzrev** [comment]
Similar warning are reported at #7454.
And it seems resolved by adding `ProduceReferenceAssembly: true` settings.

What's happens when this MSBuild property enabled?

**Comment by xuejiaW** [comment]
I tried to add `"ProduceReferenceAssembly": true` to metadata, but still no luck

if i manually add   <ProduceReferenceAssembly>True</ProduceReferenceAssembly> to each dependent csproj,like:
```xml
  <PropertyGroup>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
  ...
```

The warning will disappear, but unity project may have many child csproj, we can not add this flag for all these csprojs, and these csprojs will not be managed by source control.

**Comment by xuejiaW** [comment]
i found it problem can be solved by add `Directory.Build.props` file in the project fodler, which include:
```xml
<Project>
    <PropertyGroup>
        <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    </PropertyGroup>
</Project>
```

But i still wish this can be config in docfx.json

**Comment by filzrev** [comment]
> But i still wish this can be config in docfx.json

It can override `MSBuild` property with `docfx.json` settings.
What's happens when using following configuration?
 
```
      "properties": {
        "ProduceReferenceAssembly": true
      }
```

**Comment by xuejiaW** [comment]
> It can override `MSBuild` property with `docfx.json` settings. What's happens when using following configuration?

It works!
