### ISSUE TITLE
[Bug] `Assets` is empty in https://api.github.com/repos/dotnet/docfx/releases/latest

### ISSUE THREAD

**Issue by tlstice** [dotnet/docfx#9835]
We have a script that references `assets` at [https://api.github.com/repos/dotnet/docfx/releases/latest](https://api.github.com/repos/dotnet/docfx/releases/latest) to look for the browser download URL for the latest build. In the 2.76.0 version, `assets` is empty.

**To reproduce:**
1. Go here: https://api.github.com/repos/dotnet/docfx/releases/latest. Note that assets seems to be blank.
2. Attempt to download `docfx.zip`. The file is not found.
3. Go to https://github.com/dotnet/docfx/releases/download/v2.76.0/docfx.zip. The file is not found

**Expected behavior**
Latest version of docfx.zip (v2.76.0) should download.

Context (please complete the following information):

OS: Windows
Docfx version: v2.76.0

**Additional context**
Similar issues in the past were resolved in bugs [9350](https://github.com/dotnet/docfx/issues/9350) and [8351](https://github.com/dotnet/docfx/issues/8351).

**Comment by yufeih** [comment]
Temporarily marked as pre-release

**Comment by filzrev** [comment]
It seems CI error is occurred by `Microsoft.Playwright` package updates (`1.40.0`->`1.42.0`)

The conditions for occurrence are as follows
1. `dotnet publish` is executed on non-Windows platform (Currently using `ubuntu-latest`).
2. `dotnet publish` command that targeting `Windows` and using `-p:PlaywrightPlatform=win` options.

I've reported issue to playwright repository.
https://github.com/microsoft/playwright-dotnet/issues/2899

**Comment by cjlotz** [comment]
I see the issue in the playwright repo has been closed.  Is it possible to publish a new release now?

**Comment by yufeih** [comment]
2.76.0 just released.
