### ISSUE TITLE
[Feature Request] Print PDF's in landscape orientation and using specific page size

### ISSUE THREAD

**Issue by cjlotz** [dotnet/docfx#9842]
How difficult will it be to extend to the existing PDF printing logic to specify the orientation and page size of the page that should be used?  Thinking of adding `pdfOrientation: landscape | portrait`  setting.  If not specified it should default to `portrait`.  For size, using something like `pdfPageSize:  A0 | A1 .. | Letter `   

If possible, any pointers where to start looking at adding the support to the existing code base?

**Comment by filzrev** [comment]
I've confirmed it can change page size and orientation

1. Set PagePdfOptions's `PreferCSSPageSize` property to `true`.
https://github.com/dotnet/docfx/blob/464b947169eee016e4ca166cbae3f6a82f6178eb/src/Docfx.App/PdfBuilder.cs#L169
See: https://playwright.dev/docs/api/class-page#page-pdf-option-prefer-css-page-size

2. Edit custom template's main.css
```

**Comment by yufeih** [comment]
Make sense to me to set `PreferCSSPageSize` to `true`.
