### ISSUE TITLE
[Question] Hide TOC in modern template on page in root directory

### ISSUE THREAD

**Issue by MiTschMR** [dotnet/docfx#9873]
**Describe the bug**
A clear and concise description of what the question is about: I would like to hide the TOC on the left side of the page within the modern template as it is handled by the default template. 

**To Reproduce**
1. Add some documentation with subfolders and TOC's on each level
2. Set the templates in the docfx.json file to `default` and `modern`
3. Switch between the two and compare the page results

**More information**
The TOC should only be shown on the left side if there is one specified e.g. in a subfolder. The documentation of docfx is a good example of the modern template that utilizes folders and TOCs in there to organize the content. However, if we for instance take a look at the new [material template](https://ovasquez.github.io/docfx-material/index.html) then you will see that the root TOC is used for pages in the root directory, which I do not want. I want it only at the top and can't find a way to do so. 

I have several documentation pages like this: https://mitschmr-studios.io/documentation/easyugs/
Having the top TOC e.g. on this index page would look horrible. 

**Context (please complete the following information):**
- OS: Windows 11
- Docfx version: 2.73.2 (a rather old one because I can't use the new pdf engine)

**Comment by filzrev** [comment]
What's about to specifying `_layout: landing` metadata to index page.
https://dotnet.github.io/docfx/docs/template.html?q=_layout&tabs=modern#template-metadata

This setting hide both TOC and Affix area though.

---

> hide the TOC on the left side of the page within the modern template as it is handled by the default template.

Latest docfx v2.76.0 change default behaviors to align to `default` template behavior. 
And add `_disableToc` metadata support to separately hide TOC area. (#9737/ #9741)

**Comment by MiTschMR** [comment]
Thanks, that helped a lot!
