### ISSUE TITLE
[Question] How to extend modern template's javascript and tmpl's

### ISSUE THREAD

**Issue by MiTschMR** [dotnet/docfx#9876]
**Description:** I added custom versioning to my documentation pages within the old `subnav navbar navbar-default` div from within the `breadcrumb.tmpl.partial` file and then extending the `docfx.js` script in the styles folder. However, this no longer works with the modern template. 

What is the new way of adding custom html elements and then extending the scripts? Do I need to add the same folder structure (`src/*.ts`) or how does it work?

For reference, this is one of the sites I would like to update to the modern template: https://mitschmr-studios.io/documentation/easyugs/

**Comment by filzrev** [comment]
`modern` template don't support customization with `*.tmpl.partial` (that are supported by `default` template)

I though there are two available options to support `custom versioning`. 
 
1. Replace **entire** `layout/_master.tmpl` with custom template. And load custom JavaScript.
2. Add custom UI element by using [`public/main.js` startup script extension point](https://dotnet.github.io/docfx/docs/template.html?tabs=modern#custom-template).

For option:2. 
Following Stride docs implementation might help to support versioned content. 

- https://doc.stride3d.net/latest/en/
- https://github.com/stride3d/stride-docs/blob/master/en/template/public/main.js

**Comment by MiTschMR** [comment]
Love it, thanks for the reference!
