### ISSUE TITLE
State of npm package

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#989]
I currently find two npm packages on npmjs.com:

* [docfx](https://www.npmjs.com/package/docfx)
* [docfxjs](https://www.npmjs.com/package/docfxjs)

While both of them have [docascode](https://www.npmjs.com/~docascode) as their maintainer, both are outdated (1.0.1 and 1.0.5).

Do you have any plans to support a node package further? My use case for looking for a node package is for integration in a gulp pipeline. While it's possible to spawn just the docfx command line utility I would prefer a better integrated way.

**Comment by qinezh** [comment]
We don't support npm packages anymore. You could try to use chocolatey instead of npm in your gulp pipeline.
