### ISSUE TITLE
Release through Chocolatey?

### ISSUE THREAD

**Issue by ferventcoder** [dotnet/docfx#99]
This looks like a great candidate for release through Chocolatey. Would you be interested in a PR for this?

It would quickly become a trusted package (which means it is live very soon after you push it).

**Comment by vicancy** [comment]
@ferventcoder yes, we are very interested :laughing:

**Comment by ferventcoder** [comment]
:+1:

**Comment by ferventcoder** [comment]
Target dev branch I assume?

**Comment by vicancy** [comment]
right

**Comment by wekempf** [comment]
This will be very beneficial for using docfx in CI services like Appveyor.

**Comment by vicancy** [comment]
@ferventcoder Any progress on the PR?

**Comment by ferventcoder** [comment]
Apologies, this fell off my radar temporarily. Here is what it will look like - https://chocolatey.org/packages/docfx (we will get you maintainership), do you have a chocolatey dot org account?

**Comment by ferventcoder** [comment]
This is not yet approved either, so we can continue to make adjustments to it.

**Comment by ferventcoder** [comment]
To see how it will install, you can run `choco install docfx -version 1.4`
