### ISSUE TITLE
Chocolatey Package for the VSCode extension

### ISSUE THREAD

**Issue by pascalberger** [dotnet/docfx#990]
Do you plan to provide a Chocolatey Package for the VSCode extension? Here's [an example](https://github.com/pascalberger/chocolatey-packages/tree/master/manual/vscode-csharp) how this can be done. I can also provide a PR, but I'm not sure if I fully understand your build/deployment pipeline regarding the existing Chocolatey package :)

**Comment by hellosnow** [comment]
@pascalberger thanks for your suggestion and we're still refining build/deployment pipeline the VSCode extension, once it's done we'll consider to ship it to Chocolatey Package.

**Comment by vicancy** [comment]
VSCode has its own extension installation pipeline, why is a Chocolatey package needed?

**Comment by pascalberger** [comment]
@vicancy The advantage of providing a Chocolatey package for the Visual Studio Code extension is that it can be used to setup an environment completely through Chocolatey. Eg. it can be used as dependency in another package. Internally the Chocolatey package would of course just call Visual Studio Code to handle the extension installing (as eg. [here](https://github.com/pascalberger/chocolatey-packages/blob/master/manual/vscode-csharp/tools/ChocolateyInstall.ps1)).

**Comment by superyyrrzz** [comment]
Close as the extension is no longer supported
