### ISSUE TITLE
[Bug] Can't install docfx v3 from  https://docfx.pkgs.visualstudio.com/docfx/_packaging/docs-public-packages/nuget/v3/index.json

### ISSUE THREAD

**Issue by lmolkova** [dotnet/docfx#9901]
**Describe the bug**

It seems something around docfx nuget feed has changed on 4/29.
If I try
`dotnet tool update -g docfx --version "3.0.0-*" --add-source https://docfx.pkgs.visualstudio.com/docfx/_packaging/docs-public-packages/nuget/v3/index.json`

```
A version higher than 3.0.0-0 of package docfx is not found in NuGet feeds https://api.nuget.org/v3/index.json, ...,https://docfx.pkgs.visualstudio.com/docfx/_packaging/docs-public-packages/nuget/v3/index.json".
```

If I browse the feed in VS explorer, it seems to be empty.

Did the feed change recently?

**Expected behavior**
I want to be able to install docfx v3 from (any publicly available) feed.

**Context (please complete the following information):**
- OS: Windows/Ubuntu
- Docfx version: 3.0.0*

**Additional context**
See https://github.com/open-telemetry/opentelemetry-specification/pull/4026 and
https://github.com/open-telemetry/opentelemetry-specification/actions/runs/8897991631/job/24439658872?pr=4002

**Comment by yufeih** [comment]
Close as docfx v3 has been moved as an internal project to support Microsoft Learn only.
