### ISSUE TITLE
[Bug] Creating Multiple Ordered Lists Instead of One When Reusing Steps

### ISSUE THREAD

**Issue by rgarrity** [dotnet/docfx#9906]
**Describe the bug**
I have a set of steps that are meant to be reused within a set of steps. DocFX renders the reused steps as a new `ol`, creating multiple ordered lists. The count is lost and extra space is created between the steps.

![image](https://github.com/dotnet/docfx/assets/7049342/c2644905-cceb-4427-920e-bd784baeadcb) (wrong)

When writing in VS Code, the preview renders the steps as expected: one set only.  

![image](https://github.com/dotnet/docfx/assets/7049342/9c55b3c4-27bf-40e3-8782-34e26fdf092c) (correct)

**To Reproduce**

1. Create a file in an Includes folder, name it `reused-steps.md`, and add the following content:
    ``` md
    1. Reused step 1
    1. Reused step 2
    ```
1. Create an .md file outside of an includes folder and add the following content to reuse the steps you just created.
    ``` md
    1. First step
    [!INCLUDE [reused-steps](../includes/reused-steps.md)]
    1. Last step.
    ```
1. Build the project.

**Expected behavior**
A single ordered list should be created that looks like this:
![image](https://github.com/dotnet/docfx/assets/7049342/9c55b3c4-27bf-40e3-8782-34e26fdf092c)

**Context (please complete the following information):**
- OS: Windows
- Docfx version: [e.g. 2.76.0]

**Additional context**

The bug may be due to when the reused content is processed in https://github.com/dotnet/docfx/blob/main/src/Docfx.MarkdigEngine.Extensions/Inclusion/InclusionInline/HtmlInclusionInlineRenderer.cs. It may be a MarkDig issue.

**Comment by filzrev** [comment]
This behavior is relating to https://github.com/dotnet/docfx/issues/1099#issuecomment-270855732

As described in above comment. 
DFM [Include Markdown Files](https://dotnet.github.io/docfx/docs/markdown.html?tabs=linux%2Cdotnet#include-markdown-files) syntax can't use imported context information.

And as far as I knows.
There is no `include markdown as text` feature supported by docfx/markdig extensions.

**Comment by rgarrity** [comment]
@filzrev , thanks for pointing that out.
