### ISSUE TITLE
[Bug] Unable to find package docs.validation, Microsoft.Docs.MetadataService.Models, docs.validation.analyzer

### ISSUE THREAD

**Issue by DavidMarquezF** [dotnet/docfx#9932]
**Describe the bug**
It seems like these packages do not exist anymore in nuget. They were being used in the v3 branches.

I'm aware v3 branch has been cancelled, but during the time of its development I was using it to do some documentation. Everything works and worked perfectly for my purposes. Since some time ago, I cannot compile the documentation because these nuggets are missing from the nugget store. Am I missing something or have they actually been deleted??

From what I understand from [nuget docs](https://learn.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages), packages cannot be deleted but can be unlisted

**To Reproduce**

**Expected behavior**
Nuggets should be unlisted but not deleted

**Context (please complete the following information):**
- OS: Windows
- Docfx version: [e.g. 2.59.0]

**Additional context**

**Comment by yufeih** [comment]
> From what I understand from [nuget docs](https://learn.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages), packages cannot be deleted but can be unlisted

These packages were not published to NuGet.org, they were published to an internal Azure DevOps feed that got deleted.

Its unfortunate that you might need to find alternative workarounds. These packages are unlikely to be brought back.
