### ISSUE TITLE
[Feature Request] Create Class, Interface and Enums as expanders in the TOC for .NET Documentation

### ISSUE THREAD

**Issue by UmaHarano** [dotnet/docfx#9934]
The TOC for my .NET assembly namespace types lists "Classes" "Interface" and "Enums" as "Toc Titles". Is there a way to make them into expanders in the TOC instead? This will make the TOC more compact. I have many types in a namespace and it would nice to collapse them.

![image](https://github.com/dotnet/docfx/assets/6740984/59092ea5-afac-4a92-a505-8a93e55107b7)

I want this behavior instead:
![image](https://github.com/dotnet/docfx/assets/6740984/f5e79886-5373-4333-aa8b-1cd23854cd12)

Additional information:
https://github.com/dotnet/docfx/discussions/9933#discussioncomment-9501826

**Comment by filzrev** [comment]
The proposed implementation is as follows.

- Add `categoryLayout` option to `metadata` section.
- If `"categoryLayout": "nested"` option is enabled.  
  Reorganize TOC structure as described at https://github.com/dotnet/docfx/discussions/9933#discussioncomment-9501826.

If there seems to be no particular problems. I'll create PR later.

**Config document to be added**

---

### `categoryLayout`

Specifies how categories in TOC are organized:

- `flattened` (default): Renders namespaces as a plain label.
- `nested`: Renders category in a nested tree form.

> [!NOTE]
> This setting is is available when using `ApiPage` or `Markdown` output format. `mref` format don't support categories.

**Comment by yufeih** [comment]
We could incorporate this change if there is sufficient interest. Please upvote if you find this useful.

**Comment by UmaHarano** [comment]
What is the best way to Upvote? In this issue or in the original discussion thread?

**Comment by UmaHarano** [comment]
Also, I want to also add that when I use outputFormat = apiPage, my custom template is not being used. I lose the ability to customize the site with my template (partial files, main.js, etc).

**Comment by UmaHarano** [comment]
Will this fix be in the next release of DocFX? When will this be? Thank you!
